### PR TITLE
gh-101967: add a missing error check

### LINKED ISSUE #101967: ceval.c: `positional_only_passed_as_keyword` can be failed with segfault
https://github.com/python/cpython/blob/4d8959b73ac194ca9a2f623dcb5c23680f7d8536/Python/ceval.c#L1251-L1285

This implemention doesn't take in account case when `PyList_New` returns `NULL`.
If `PyList_New(0)` returns a `NULL`, `PyList_Append` will be failed with segfault, cause of `Py_TYPE`, which will try to reach out `ob_type`. of `(PyObject *) NULL`.
This hard to reproduce, because the only way `PyList_New` can error, if it is runs out of memory, but theoretically it can happen.

### Linked PRs
* gh-101968
* gh-102016
* gh-102015
* gh-114738

### PR DESCRIPTION
**Pull request by Eclips4**
Resolves #101967 
According to the semantics of function, I prefered to return `1` instead of `NULL`. Does it correct?

* Issue: gh-101967

### CODE REVIEW

**Review by carljm — APPROVED** [review]

File: Python/ceval.c [hunk 1]
```diff
@@ -1255,7 +1255,8 @@ positional_only_passed_as_keyword(PyThreadState *tstate, PyCodeObject *co,
 {
     int posonly_conflicts = 0;
     PyObject* posonly_names = PyList_New(0);
-
+    if (posonly_names == NULL)
+        return 1;
```
Comment (sobolevn) [inline Python/ceval.c]:
```suggestion
        goto fail; 
```

**Review by sobolevn — COMMENTED** [review]
Yes, `NULL` can be returned by `PyList_New` when there's no memory left.

I don't think that we need to test this case.

File: Python/ceval.c (hunk 1 above)
Comment (carljm) [reply Python/ceval.c]: I don't think `goto fail` is necessary here. It only exists to decref `posonly_names`, which is NULL in this case. It will still work since it uses `Py_XDECREF`, but why go through that extra check?

Comment (Eclips4) [reply Python/ceval.c]: I believe that this is necessary only in order not to break the consistency of the function
Initially, i decided to `return 1` instead of `goto fail` , but if we want not to break the consistency of the function, more acceptable way to use `goto fail`

File: Python/ceval.c [hunk 2]
```diff
@@ -1255,7 +1255,8 @@ positional_only_passed_as_keyword(PyThreadState *tstate, PyCodeObject *co,
 {
     int posonly_conflicts = 0;
     PyObject* posonly_names = PyList_New(0);
-
+    if (posonly_names == NULL)
+        goto fail;
```
Comment (iritkatriel) [inline Python/ceval.c]:
```suggestion
    if (posonly_names == NULL) {
        goto fail;
    }
```

**Review by iritkatriel — APPROVED** [review]

**Comment by iritkatriel** [comment]
The MacOS build failure is unrelated.
