### PR TITLE
gh-109795: `_thread.start_new_thread`: allocate thread bootstate using raw memory allocator

### LINKED ISSUE #109795: Starting new thread during finalization leads to call to `PyMem_Free` without holding the GIL
# Crash report

### What happened?

Since #109135, `thread_run` checks if it is called during finalization, and in this case it frees thread bootstate in `thread_bootstate_free` and returns. The problem is that  `PyMem_Free` shouldn't be called if GIL is not held.

Repro and error message (just in case):
```python
import os
import random
import signal
import subprocess
import sys
import time

script = """
import threading
while True:
    t = threading.Thread()
    t.start()
    t.join()
"""

while True:
    p = subprocess.Popen([sys.executable, '-c', script], stderr=subprocess.PIPE)
    time.sleep(random.random())
    os.kill(p.pid, signal.SIGINT)
    _, err = p.communicate()
    if p.returncode == -signal.SIGABRT:
        print(err.decode('utf-8'))
        break
```

```
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/home/radislav/projects/cpython/Lib/threading.py", line 983, in start
    self._started.wait()
  File "/home/radislav/projects/cpython/Lib/threading.py", line 641, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/radislav/projects/cpython/Lib/threading.py", line 341, in wait
    waiter.acquire()
KeyboardInterrupt
Fatal Python error: _PyMem_DebugFree: Python memory allocator called without holding the GIL
Python runtime state: finalizing (tstate=0x0000561b61b67338)

Thread 0x00007f8f890b8280 (most recent call first):
  <no Python frame>
```

cc @vstinner

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.13.0a0 (heads/main:3e8fcb7df7, Sep 23 2023, 01:43:45) [GCC 10.2.1 20210110]

### Linked PRs
* gh-109808
* gh-109852

### PR DESCRIPTION
**Pull request by chgnrdv**
Fixes #109795

When new thread is starting, but Python is finalizing, `PyMem_Free` can't be called on new thread `bootstate`, because this thread doesn't own the GIL. We should use raw memory allocator to allocate/free `bootstate` to avoid crashes/other unexpected behaviour.

* Issue: gh-109795

### CODE REVIEW

**Comment by chgnrdv** [comment]
Windows (x86) failed due to #109739.

File: Modules/_threadmodule.c [hunk 1]
```diff
@@ -1184,13 +1184,13 @@ thread_PyThread_start_new_thread(PyObject *self, PyObject *fargs)
         return NULL;
     }
 
-    struct bootstate *boot = PyMem_NEW(struct bootstate, 1);
+    struct bootstate *boot = PyMem_RawMalloc(sizeof(struct bootstate));
```
Comment (vstinner) [inline Modules/_threadmodule.c:1190]: Please add a comment to explain why PyMem_RawMalloc() is used instead of PyMem_Malloc(). Mention 
gh-109795.

File: Modules/_threadmodule.c [hunk 2]
```diff
@@ -1184,13 +1184,17 @@ thread_PyThread_start_new_thread(PyObject *self, PyObject *fargs)
         return NULL;
     }
 
-    struct bootstate *boot = PyMem_NEW(struct bootstate, 1);
+    // gh-109795: Use PyMem_RawMalloc() to allocate new thread bootstate.
+    // If new thread is started at Python finalization,
+    // i.e. thread_run() routine is invoked in newly created OS thread,
+    // it should be able to free bootstate without holding the GIL.
```
Comment (vstinner) [inline Modules/_threadmodule.c]:
```suggestion
    // gh-109795: Use PyMem_RawMalloc() instead of PyMem_Malloc(),
    // because it should be possible to call thread_bootstate_free()
    // without holding the GIL.
```

File: Misc/NEWS.d/next/Core and Builtins/2023-09-24-22-26-56.gh-issue-109795.gI7KW6.rst [hunk 3]
```diff
@@ -0,0 +1 @@
+:func:`!_thread.start_new_thread` now uses raw memory allocator to allocate new thread bootstate. This helps to avoid crashes in case when new thread gets started at interpreter finalization.
```
Comment (vstinner) [inline Misc/NEWS.d/next/Core and Builtins/2023-09-24-22-26-56.gh-issue-109795.gI7KW6.rst]: Oh. Please remove this Changelog entry. I don't think that it's worth it. It doesn't impact directly users and it's a recent regression, no?

**Comment by vstinner** [comment]
Merged, thanks!
