### PR TITLE
gh-90763: Modernise xx template module initialisation

### LINKED ISSUE #90763: Py_XDECREF() module on fail in Py_mod_exec
BPO | [46605](https://bugs.python.org/issue46605)
--- | :---

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-02-01.21:49:08.439>
labels = ['type-bug', '3.8', '3.9', '3.10', '3.11', 'extension-modules', '3.7']
title = 'Py_XDECREF() module on fail in Py_mod_exec'
updated_at = <Date 2022-02-01.21:49:08.439>
user = 'https://bugs.python.org/ov2k'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-01.21:49:08.439>
actor = 'ov2k'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2022-02-01.21:49:08.439>
creator = 'ov2k'
dependencies = []
files = []
hgrepos = []
issue_num = 46605
keywords = []
message_count = 1.0
messages = ['412315']
nosy_count = 1.0
nosy_names = ['ov2k']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46605'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### PR DESCRIPTION
**Pull request by erlend-aasland**
xxmodule:
- remove incorrect decref of module object if module init fails
- modernise API usage; use PyModule_AddType iso. PyModule_AddObject

xxlimited_35:
- remove incorrect decref of module object if module init fails
- check return of PyModule_AddObject
- fix module name in type objects

### CODE REVIEW

**Comment by erlend-aasland** [comment]
@corona10, would you mind reviewing this? It's been a while since I've done the module init ref count dances :)

I note that xxlimited_35 creates _two_ objects from the same type spec. I'm not sure if there's a point in doing that.

File: Modules/xxlimited_35.c [hunk 1]
```diff
@@ -236,52 +236,58 @@ static PyMethodDef xx_methods[] = {
...
 
+static PyObject *
+create_and_add_type(PyObject *module, const char *name, PyType_Spec *spec)
+{
+    PyObject *type = PyType_FromSpec(spec);
+    if (type == NULL) {
+        return NULL;
+    }
+    int rc = PyModule_AddObject(module, name, type);
+    if (rc < 0) {
```
Comment (corona10) [inline Modules/xxlimited_35.c]:
```suggestion
    if (PyModule_AddObject(module, name, type) < 0) {
```

I prefer not to use `rc` variable. Is there any reason to use this variable?

File: Modules/xxlimited_35.c [hunk 2]
```diff
@@ -236,52 +236,58 @@ static PyMethodDef xx_methods[] = {
...
-        goto fail;
-    PyModule_AddObject(m, "Str", o);
-
-    /* Add Null */
-    o = PyType_FromSpec(&Null_Type_spec);
-    if (o == NULL)
-        goto fail;
-    PyModule_AddObject(m, "Null", o);
+    int rc = PyModule_AddObject(m, "error", ErrorObject);
+    if (rc < 0) {
```
Comment (corona10) [inline Modules/xxlimited_35.c]:
```suggestion
    if (PyModule_AddObject(m, "error", ErrorObject) < 0) {
```

ditto

**Review by corona10 — COMMENTED** [review]
Overall looks good to me with nit comment.

File: Modules/xxlimited_35.c (hunk 1 above)
Comment (erlend-aasland) [reply Modules/xxlimited_35.c]: No reason anymore; leftovers from first iteration of changes :)

**Review by corona10 — APPROVED** [review]
lgtm

**Comment by erlend-aasland** [comment]
Thanks, Dong-hee! I'll hold the merge a couple of days to give Petr (or Victor) a chance to review.

**Comment by encukou** [comment]
Looks good, thanks!
If it was me, instead of `create_and_add_type` I'd write out the two calls each time: it's a historical module so I'd keep changes to minimal bugfixes. It's OK to showcase how clunky the old API is :)
But that's a minor nit, feel free to merge as is.

**Comment by erlend-aasland** [comment]
> Looks good, thanks!
> If it was me, instead of `create_and_add_type` I'd write out the two calls each time: it's a historical module so I'd keep changes to minimal bugfixes. It's OK to showcase how clunky the old API is :)
> But that's a minor nit, feel free to merge as is.

I had to ponder a little bit about this; I agree that it's worth it keeping the changes minimal for these modules :)

**Review by encukou — APPROVED** [review]

File: Modules/xxlimited_35.c [hunk 3]
```diff
@@ -248,40 +248,50 @@ xx_modexec(PyObject *m)
...
-        if (ErrorObject == NULL)
-            goto fail;
+        ErrorObject = PyErr_NewException("xxlimited_35.error", NULL, NULL);
+        if (ErrorObject == NULL) {
+            return -1;
+        }
     }
     Py_INCREF(ErrorObject);
-    PyModule_AddObject(m, "error", ErrorObject);
+    if (PyModule_AddObject(m, "error", ErrorObject) < 0) {
```
Comment (vstinner) [inline Modules/xxlimited_35.c:259]: Can you use https://docs.python.org/dev/c-api/module.html#c.PyModule_AddObjectRef here?

File: Modules/xxlimited_35.c [hunk 4]
```diff
@@ -248,40 +248,50 @@ xx_modexec(PyObject *m)
...
+        Py_DECREF(ErrorObject);
+        return -1;
+    }
 
     /* Add Xxo */
-    o = PyType_FromSpec(&Xxo_Type_spec);
-    if (o == NULL)
-        goto fail;
-    PyModule_AddObject(m, "Xxo", o);
+    Xxo_Type = PyType_FromSpec(&Xxo_Type_spec);
```
Comment (vstinner) [inline Modules/xxlimited_35.c:265]: It seems possible to store the type in a module state and get it in xx_new(). You might try to do that in a separated PR.

File: Modules/xxmodule.c [hunk 5]
```diff
@@ -358,31 +358,32 @@ xx_exec(PyObject *m)
...
     /* Finalize the type object including setting type of the new type
      * object; doing it here is required for portability, too. */
-    if (PyType_Ready(&Xxo_Type) < 0)
-        goto fail;
+    if (PyType_Ready(&Xxo_Type) < 0) {
+        return -1;
+    }
 
     /* Add some symbolic constants to the module */
     if (ErrorObject == NULL) {
```
Comment (vstinner) [inline Modules/xxmodule.c:366]: ErrorObject is not used outside this function. Would it make sense to simply remove this global variable?

File: Modules/xxmodule.c [hunk 6]
```diff
@@ -358,31 +358,32 @@ xx_exec(PyObject *m)
 
     /* Finalize the type object including setting type of the new type
      * object; doing it here is required for portability, too. */
-    if (PyType_Ready(&Xxo_Type) < 0)
-        goto fail;
+    if (PyType_Ready(&Xxo_Type) < 0) {
```
Comment (vstinner) [inline Modules/xxmodule.c:361]: Booooh! A static type! It seems possible to store it in a module state and get it from the module state in xx_new().

By the way, XxoObject_Check() macro is unused. Maybe just remove it?

File: Modules/xxlimited_35.c (hunk 3 above)
Comment (erlend-aasland) [reply Modules/xxlimited_35.c:259]: Nope, that is not available in the 3.5 Limited API.

File: Modules/xxlimited_35.c (hunk 4 above)
Comment (erlend-aasland) [reply Modules/xxlimited_35.c:265]: I'll see what's available in the 3.5 Limited API. If possible, I'll open an issue about it.

File: Modules/xxlimited_35.c (hunk 3 above)
Comment (encukou) [reply Modules/xxlimited_35.c:259]: No, `PyModule_AddObjectRef` was added in 3.10.
Please keep in mind that this is a test module for old API.

File: Modules/xxmodule.c (hunk 6 above)
Comment (encukou) [reply Modules/xxmodule.c:361]: The point of this module is to show that static types and global variables still work.

File: Modules/xxmodule.c (hunk 5 above)
Comment (erlend-aasland) [reply Modules/xxmodule.c:366]: Maybe. It depends on what we want the xxmodule.c to communicate and what we would like to show off. It's out of scope for this PR anyway. We could elevate such a discussion to Discourse, I guess.

File: Modules/xxmodule.c (hunk 6 above)
Comment (erlend-aasland) [reply Modules/xxmodule.c:361]: Modules/xxlimited.c is for module state and heap types ;)

I think the check macro can stay; it functions as example code.

**Comment by vstinner** [comment]
> The point of this module is to show that static types and global variables still work.

The file starts with:

> Use this file as a template to start implementing a module that also declares object types.

IMO it should be a show case of the best practice to write a C extension in 2022. Otherwise, people will continue to copy/paste this old code and will propagate static types and other legacy code to their project :-(

**Comment by vstinner** [comment]
If you want to test that the old way to write a C extension, with static types and global variables, still work, IMO it should be another module than this "template".

**Comment by erlend-aasland** [comment]
> If you want to test that the old way to write a C extension, with static types and global variables, still work, IMO it should be another module than this "template".

We could adjust the wording in the top of the file, and also rename it to something like `xxlegacy.c`. But I think this warrants a broader discussion :)

**Comment by encukou** [comment]
`xxlimited` shows the new way. The historical comment in `xxmodule` could be changed, but IMO the module name isn't misleading enough to rename it.

Anyway, the more important thing to do here is converting the [tutorial](https://docs.python.org/3/extending/extending.html). That will, in my opinion, make the new way official :)
But I don't want to do that until PEP 687 is accepted, and more [PEP 630 open issues](https://peps.python.org/pep-0630/#open-issues) are solved. (FWIW: Metaclasses and Per-class scope look like they could go in anearly 3.12 alpha, Type checking should hopefully go in 3.12 as well, and lossless conversion isn't blocking for me.)

But yes, all that is out of scope of this PR.

**Comment by erlend-aasland** [comment]
FYI, I plan to merge this tomorrow.

File: Modules/xxmodule.c [hunk 7]
```diff
@@ -358,31 +358,32 @@ xx_exec(PyObject *m)
...
+    if (PyModule_AddType(m, &Str_Type) < 0) {
+        return -1;
+    }
+    if (PyModule_AddType(m, &Null_Type) < 0) {
+        return -1;
+    }
+
     return 0;
- fail:
-    Py_XDECREF(m);
```
Comment (vstinner) [inline Modules/xxmodule.c:384]: Is this a bugfix? If yes, it should be backported to stable branches (at least, just remove this line).

**Review by vstinner — APPROVED** [review]
LGTM.

File: Modules/xxmodule.c (hunk 7 above)
Comment (erlend-aasland) [reply Modules/xxmodule.c:384]: True. I'm not sure how the xx\* module policies are, but IMO we should be ok to backport the whole PR.

**Comment by vstinner** [comment]
I'm fine with backporting the whole PR. Most changes are related to the bugfix.
