### PR TITLE
gh-130273: Fix traceback color output with unicode characters

### LINKED ISSUE #130273: Traceback colors are shifted when the line contains wide unicode characters
# Bug report

### Bug description:

Image

In #28150, the carets' positions are compatible with wide unicode characters. I believe the colors should also be compatible.

### CPython versions tested on:

3.13, CPython main branch

### Operating systems tested on:

Windows, macOS

### Linked PRs
* gh-130277
* gh-142529
* gh-148218

### PR DESCRIPTION
**Pull request by grayjk**
Account for the display width of unicode characters so that colors and underlining in traceback output is correct

Closes #130273

* Issue: gh-130273

### CODE REVIEW

File: Misc/NEWS.d/next/Library/2025-12-10-15-15-09.gh-issue-130273.iCfiY5.rst
Comment (StanFromIreland) [inline Misc/NEWS.d/next/Library/2025-12-10-15-15-09.gh-issue-130273.iCfiY5.rst:1]: Please move this blurb to library.

**Comment by vstinner** [comment]
@serhiy-storchaka: Here is a PR about text width and Unicode characters :-)

File: Lib/traceback.py [hunk 1]
```diff
@@ -982,13 +990,9 @@ def _display_width(line, offset=None):
     if line.isascii():
         return offset
 
-    import unicodedata
-
-    return sum(
-        2 if unicodedata.east_asian_width(char) in _WIDE_CHAR_SPECIFIERS else 1
-        for char in line[:offset]
-    )
+    from _pyrepl.utils import wlen
```
Comment (vstinner) [inline Lib/traceback.py]: I would prefer to not depend on `_pyrepl` in the traceback module. I would prefer to move wlen() here, and modify `_pyrepl.utils` to get it from traceback.

Comment (grayjk) [reply Lib/traceback.py]: I've moved wlen/str_width in commit 467656ee4 and made them private (prefixed with _) to avoid putting them in `traceback.__all__` but mypy isn't happy about that. Should I make them public?

Comment (grayjk) [reply Lib/traceback.py]: are `# type: ignore` comments in this case okay?

Comment (grayjk) [reply Lib/traceback.py]: or alternatively I could move wlen to a new support file with a name prefixed with `_`

File: Lib/traceback.py [hunk 2]
```diff
@@ -968,7 +970,46 @@ def setup_positions(expr, force_valid=True):
...
+    category = unicodedata.category(c)
+    if category == "Cf" and c != "\u00ad":
+        return 0
+    w = unicodedata.east_asian_width(c)
+    if w in ("N", "Na", "H", "A"):
+        return 1
+    return 2
+
+
+ANSI_ESCAPE_SEQUENCE = re.compile(r"\x1b\[[ -@]*[A-~]")
```
Comment (StanFromIreland) [inline Lib/traceback.py]: It should also be private.

File: Lib/traceback.py [hunk 3]
```diff
@@ -968,7 +970,46 @@ def setup_positions(expr, force_valid=True):
...
+        char = str(char)
+        char_width = _display_width(char)
+        yield char, "".join(itertools.islice(carets, char_width))
+
+
+@functools.cache
+def _str_width(c: str) -> int:
+    import unicodedata
+    if ord(c) < 128:
+        return 1
```
Comment (vstinner) [inline Lib/traceback.py]: There is no need to import unicodedata for ASCII characters:

```suggestion
    if ord(c) < 128:
        return 1
    import unicodedata
```

File: Lib/traceback.py [hunk 4]
```diff
@@ -968,7 +970,46 @@ def setup_positions(expr, force_valid=True):
...
 
-_WIDE_CHAR_SPECIFIERS = "WF"
+
+def _zip_display_width(line, carets):
+    import unicodedata
+    carets = iter(carets)
+    for char in unicodedata.iter_graphemes(line):
+        char = str(char)
+        char_width = _display_width(char)
+        yield char, "".join(itertools.islice(carets, char_width))
```
Comment (vstinner) [inline Lib/traceback.py:988]: Would it be possible to avoid the heavy `unicodedata` import for ASCII line?

```suggestion
def _zip_display_width(line, carets):
    carets = iter(carets)
    if line.isascii():
        for char in line:
            yield char, next(carets, "")
    else:
        import unicodedata
        for char in unicodedata.iter_graphemes(line):
            char = str(char)
            char_width = _display_width(char)
            yield char, "".join(itertools.islice(carets, char_width))
```

I'm not sure that my code is correct :-)

File: Misc/NEWS.d/next/Library/2025-12-10-15-15-09.gh-issue-130273.iCfiY5.rst [hunk 5]
```diff
@@ -0,0 +1 @@
+Fix traceback color output with unicode characters
```
Comment (vstinner) [inline Misc/NEWS.d/next/Library/2025-12-10-15-15-09.gh-issue-130273.iCfiY5.rst]:
```suggestion
Fix traceback color output with Unicode characters.
```

**Comment by Wulian233** [comment]
@pablogsal You maybe make wrong something :)

File: Lib/traceback.py [hunk 6]
```diff
@@ -971,26 +973,64 @@ def setup_positions(expr, force_valid=True):
...
+            yield char, next(carets, "")
+        return
+
+    import unicodedata
+    for char in unicodedata.iter_graphemes(line):
+        char = str(char)
+        char_width = _display_width(char)
+        yield char, "".join(itertools.islice(carets, char_width))
+
+
```
[the remark this answers is not in the document]
Comment (ambv) [reply Lib/traceback.py:990]: This is a deliberate difference.
