### PR TITLE
gh-113149: improve error when json has trailing comma

### LINKED ISSUE #113149: Improving error message with trailing comma in json
# Bug report

### Bug description:

```python
import json
json.loads('{"a":1,}')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 8 (char 7)
```
The error is the trailing comma.

Initial pull proposal: #113047 but apparently this needs more attention than I can contribute.
The actual fix needs to be further down, possibly in line 206
https://github.com/python/cpython/blob/25061f5c98a47691fdb70f550943167bda77f6e0/Lib/json/decoder.py#L199-L208
we already know that we have seen a comma, and can insert a more helpful error message in line 206.
```python
if nextchar == '}':
    raise JSONDecodeError("No trailing commas allowed in JSON objects.", s, end - 1)
```
at this location, the previous character must have been a comma (line 201). Whitespace has been removed, so this will also catch `,\n}`

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

### Linked PRs
* gh-113227

### PR DESCRIPTION
**Pull request by carsonRadtke**
Fixes: gh-113149

Adds two new `JSONDecodeError` types: "Illegal trailing comma before end of {array,object}".

Some test's expected error location had to change because the error now exists with the existence of the comma, rather than the non-existence of a following object. 

Had to introduce a `Py_ssize_t comma_idx;` because we want to ensure that
```plaintext
{ "a": 123   ,            } 
             ^ <- error reported here
```

Behavior after the PR:
```shell
$ echo '[,' | ./python.exe -m json.tool
Expecting value: line 1 column 2 (char 1)
$ echo '{,}' | ./python.exe -m json.tool
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
$ echo '[123,]' | ./python.exe -m json.tool
Illegal trailing comma before end of array: line 1 column 5 (char 4)
$ echo '{"a":123,}' | ./python.exe -m json.tool
Illegal trailing comma before end of object: line 1 column 9 (char 8)
$ echo '[123,  ]' | ./python.exe -m json.tool
Illegal trailing comma before end of array: line 1 column 5 (char 4)
$ echo '{"a":123,  }' | ./python.exe -m json.tool
Illegal trailing comma before end of object: line 1 column 9 (char 8)
$ echo '{"spam":42,}' | ./python.exe -m json.tool
Illegal trailing comma before end of object: line 1 column 11 (char 10)
```

* Issue: gh-113149

### CODE REVIEW

File: Modules/_json.c [hunk 1]
```diff
@@ -741,10 +742,17 @@ _parse_object_unicode(PyScannerObject *s, PyObject *memo, PyObject *pystr, Py_ss
...
                 goto bail;
             }
+            comma_idx = idx;
             idx++;
 
             /* skip whitespace after , delimiter */
             while (idx <= end_idx && IS_WHITESPACE(PyUnicode_READ(kind, str, idx))) idx++;
+
+            if (idx <= end_idx && PyUnicode_READ(kind, str, idx) == '}')
+            {
```
Comment (serhiy-storchaka) [inline Modules/_json.c]: PEP 7.
```suggestion
            if (idx <= end_idx && PyUnicode_READ(kind, str, idx) == '}') {
```

File: Modules/_json.c [hunk 2]
```diff
@@ -822,10 +831,17 @@ _parse_array_unicode(PyScannerObject *s, PyObject *memo, PyObject *pystr, Py_ssi
...
                 goto bail;
             }
+            comma_idx = idx;
             idx++;
 
             /* skip whitespace after , */
             while (idx <= end_idx && IS_WHITESPACE(PyUnicode_READ(kind, str, idx))) idx++;
+
+            if (idx <= end_idx && PyUnicode_READ(kind, str, idx) == ']')
+            {
```
Comment (serhiy-storchaka) [inline Modules/_json.c]:
```suggestion
            if (idx <= end_idx && PyUnicode_READ(kind, str, idx) == ']') {
```

**Review by serhiy-storchaka — COMMENTED** [review]
Very good. Please fix style add add test cases with spaces between comma and closing brace.

**Review by serhiy-storchaka — APPROVED** [review]
LGTM.

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution @carsonRadtke.
