### PR TITLE
GH-94736: Fix _multiprocessing.SemLock subclassing

### LINKED ISSUE #94736: GC crash in subtype_dealloc when inherting from _multiprocessing.SemLock
**Crash report**

GC crash in subtype_dealloc when inherting from _multiprocessing.SemLock.

Reproducer (read carefully before running!):
```py
from _multiprocessing import SemLock
class S(SemLock):
    pass


s = S(1, 1, 2, 'foo', 1)
```

**Error messages**

```console
@kumaraditya303 ➜ /workspaces/cpython (main ✗) $ ./python main.py 
Segmentation fault (core dumped)
```
GDB backtrace:
```console
#0  _PyObject_GC_UNTRACK (op=<S() at remote 0x7ffff778d480>, lineno=2242, 
    filename=0x5555559ae5dc "Modules/gcmodule.c") at ./Include/internal/pycore_object.h:174
#1  PyObject_GC_UnTrack (op_raw=0x7ffff778d480) at Modules/gcmodule.c:2242
#2  0x0000555555760e71 in subtype_dealloc (self=<S() at remote 0x7ffff778d480>)
    at Objects/typeobject.c:1368
#3  0x0000555555742e85 in _Py_Dealloc (op=<optimized out>) at Objects/object.c:2382
#4  0x0000555555726b1b in Py_DECREF (op=<optimized out>, lineno=609, 
    filename=0x55555591d5dd "./Include/object.h") at ./Include/object.h:533
#5  Py_XDECREF (op=<optimized out>) at ./Include/object.h:609
#6  free_keys_object (keys=keys@entry=0x7ffff777cf70) at Objects/dictobject.c:664
#7  0x0000555555727258 in dictkeys_decref (dk=0x7ffff777cf70) at Objects/dictobject.c:324
#8  dict_dealloc (mp=0x7ffff772d490) at Objects/dictobject.c:2378
#9  0x0000555555742e85 in _Py_Dealloc (op=<optimized out>) at Objects/object.c:2382
#10 0x000055555573f7e9 in Py_DECREF (op=<optimized out>, lineno=609, 
    filename=0x55555591d5dd "./Include/object.h") at ./Include/object.h:533
#11 Py_XDECREF (op=<optimized out>) at ./Include/object.h:609
#12 module_dealloc (m=0x7ffff772da30) at Objects/moduleobject.c:699
#13 0x0000555555742e85 in _Py_Dealloc (op=<optimized out>) at Objects/object.c:2382
#14 0x000055555572bca7 in Py_DECREF (op=<optimized out>, lineno=609, 
```

**Your environment**

- CPython versions tested on: Python 3.12.0a0 da717519ec, Python 3.11.0b3+ f3212b1ec7 on linux
- Operating system and architecture: Linux 5.4.0-1074-azure  x86_64 

cc @pablogsal

### PR DESCRIPTION
**Pull request by kumaraditya303**
* Issue: gh-94736

Closes https://github.com/python/cpython/pull/94736

### CODE REVIEW

File: Modules/_multiprocessing/semaphore.c [hunk 1]
```diff
@@ -780,6 +778,7 @@ PyTypeObject _PyMp_SemLockType = {
     /* tp_init           */ 0,
     /* tp_alloc          */ 0,
     /* tp_new            */ _multiprocessing_SemLock,
+    .tp_free = PyObject_Free,
```
Comment (pablogsal) [inline Modules/_multiprocessing/semaphore.c]: I may be missing something but I don't think you need this. The default for the static type case should be `PyObject_Del` which is equivalent to `PyObject_Free` and inheritance will replace it for the appropriate generic alloc deallocator.

File: Modules/_multiprocessing/semaphore.c [hunk 2]
```diff
@@ -454,9 +454,7 @@ static PyObject *
 newsemlockobject(PyTypeObject *type, SEM_HANDLE handle, int kind, int maxvalue,
                  char *name)
 {
-    SemLockObject *self;
-
-    self = PyObject_New(SemLockObject, type);
+    SemLockObject *self = (SemLockObject *)type->tp_alloc(type, 0);
```
Comment (pablogsal) [inline Modules/_multiprocessing/semaphore.c:457]: Ah, this has bitten us more than once already. Good catch!

File: Modules/_multiprocessing/semaphore.c (hunk 1 above)
Comment (kumaraditya303) [reply Modules/_multiprocessing/semaphore.c]: Okay, I wanted to make it explicit for others which may not know this but I am fine with removing it. removed.

**Review by pablogsal — APPROVED** [review]
