### PR TITLE
gh-111123: symtable should visit exception handlers before the else block

### LINKED ISSUE #111123: global declaration in except has incorrect prior use
# Bug report

### Bug description:

I think the `global a` has no prior use in this code (and pyright tells me the same). But I don't understand why cpython thinks it has a prior use.

```python

a=5

def f():
    try:
        pass
    except:
        global a
    else:
        print(a)
```

output (Python 3.12.0):
```python
  File "/home/frank/projects/pysource-playground/pysource-codegen/bug.py", line 8
    global a
    ^^^^^^^^
SyntaxError: name 'a' is used prior to global declaration
```

the following code has no syntax error:
```python

a=5

def f():
    try:
        pass
    except:
        global a
    print(a)
```

I can also reproduce this issue in 3.7.

I also don't know what the exact semantic of global/nonlocal inside statements like if/while/try/... is. I would like to know more about it because I'm currently writing [pysource-codegen](https://github.com/15r10nk/pysource-codegen) where I generate such cases.

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-111142

### PR DESCRIPTION
**Pull request by iritkatriel**
Fixes #111123 .

* Issue: gh-111123

### CODE REVIEW

File: Misc/NEWS.d/next/Core and Builtins/2023-10-20-23-14-06.gh-issue-111123.jjVc3M.rst [hunk 1]
```diff
@@ -0,0 +1,2 @@
+Fix bug where a :keyword:`global` decleration in an :keyword:`except` block
```
Comment (iritkatriel) [inline Misc/NEWS.d/next/Core and Builtins/2023-10-20-23-14-06.gh-issue-111123.jjVc3M.rst]:
```suggestion
Fix bug where a :keyword:`global` declaration in an :keyword:`except` block
```

**Review by pablogsal — APPROVED** [review]

File: Misc/NEWS.d/next/Core and Builtins/2023-10-20-23-14-06.gh-issue-111123.jjVc3M.rst [hunk 2]
```diff
@@ -0,0 +1,2 @@
+Fix bug where a :keyword:`global` declaration in an :keyword:`except` block
```
Comment (pablogsal) [inline Misc/NEWS.d/next/Core and Builtins/2023-10-20-23-14-06.gh-issue-111123.jjVc3M.rst]:
```suggestion
Fix a bug where a :keyword:`global` declaration in an :keyword:`except` block
```

File: Doc/whatsnew/3.13.rst [hunk 3]
```diff
@@ -106,6 +106,10 @@ Other Language Changes
   the file is not accessible.
   (Contributed by Moonsik Park in :gh:`82367`.)
 
+* Fixed a bug where a :keyword:`global` decleration in an :keyword:`except` block
```
Comment (AlexWaygood) [inline Doc/whatsnew/3.13.rst:109]: Typo: should be "declaration"
