### PR TITLE
gh-123828: fix data raceing for _waiting_release method in _interpchannelsmodule.c

### LINKED ISSUE #123828: TSAN race in _waiting_release
# Bug report

### Bug description:

A TSAN (gcc-12) build of the latest version of cpython reports a race in the test_send_recv_different_interpreters_and_threads test:

```
  Read of size 4 at 0x7ffe8d0c9338 by main thread:
    #0 _waiting_finish_releasing Modules/_interpchannelsmodule.c:504 (_interpchannels.cpython-314-x86_64-linux-gnu.so+0x88f4) (BuildId: 233ea3cec8e2d6b4a5322cdab2aa3fcc24ab85f8)
    #1 channel_send_wait Modules/_interpchannelsmodule.c:1852 (_interpchannels.cpython-314-x86_64-linux-gnu.so+0x88f4)
    #2 channelsmod_send Modules/_interpchannelsmodule.c:3096 (_interpchannels.cpython-314-x86_64-linux-gnu.so+0x8dd0) (BuildId: 233ea3cec8e2d6b4a5322cdab2aa3fcc24ab85f8)
    #3 cfunction_call Objects/methodobject.c:540 (python+0x549e55) (BuildId: f667f6a4a823ca3db627f9e7bf3836f7af978c6d)

    #0 _waiting_release Modules/_interpchannelsmodule.c:498 (_interpchannels.cpython-314-x86_64-linux-gnu.so+0x37c7) (BuildId: 233ea3cec8e2d6b4a5322cdab2aa3fcc24ab85f8)
    #1 channel_recv Modules/_interpchannelsmodule.c:1937 (_interpchannels.cpython-314-x86_64-linux-gnu.so+0x863a) (BuildId: 233ea3cec8e2d6b4a5322cdab2aa3fcc24ab85f8)
    #2 channelsmod_recv Modules/_interpchannelsmodule.c:3189 (_interpchannels.cpython-314-x86_64-linux-gnu.so+0x863a)
```

Indeed, https://github.com/python/cpython/blob/8b209fd4f8a9bf9603888bda2c44b5cfd4ebf47a/Modules/_interpchannelsmodule.c#L504 spin waits for `waiting->status` to change state, with https://github.com/python/cpython/blob/8b209fd4f8a9bf9603888bda2c44b5cfd4ebf47a/Modules/_interpchannelsmodule.c#L498 triggering the spinning thread to exit the spin. Neither happens under a mutex, or with any release-acquire sequencing.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-124107
* gh-139517

### PR DESCRIPTION
**Pull request by Zheaoli**
Fix #123828 

* Issue: gh-123828

### CODE REVIEW

File: Modules/_interpchannelsmodule.c [hunk 1]
```diff
@@ -1,6 +1,7 @@
 /* interpreters module */
 /* low-level access to interpreter primitives */
 
+#include <stdbool.h>
```
Comment (picnixz) [inline Modules/_interpchannelsmodule.c]: Why is this new addition needed?

Comment (Zheaoli) [reply Modules/_interpchannelsmodule.c]: typo,fixed

**Comment by ZeroIntensity** [comment]
@picnixz out of the scope of this PR, but would it be feasible to migrate things using `PyThread` locks over to `PyMutex` in the future?

**Comment by picnixz** [comment]
Maybe. Haven't had the time to think about it and I don't know if it's possible for every case. Could you open another issue for that? also how would performances / maintenance cost be impacted?

**Comment by ZeroIntensity** [comment]
> Maybe. Haven't had the time to think about it and I don't know if it's possible for every case. Could you open another issue for that? also how would performances / maintenance cost be impacted?

It's probably worth discussing on discourse before opening an issue. AFAIK, `PyMutex` is supposed to be much more efficient than pthread mutexes.

**Comment by Zheaoli** [comment]
@picnixz May I ask if this pr is worth to merge?

**Comment by picnixz** [comment]
I am not well-versed enough in this part of the code to be sure that it's correct, so I'll let Eric decide (or @ZeroIntensity)

**Comment by ZeroIntensity** [comment]
The core change looks correct, I noticed this with Eric at the sprint. Please add a test though.

**Comment by Zheaoli** [comment]
> The core change looks correct, I noticed this with Eric at the sprint. Please add a test though.

Sorry about this. I have noticed that seems We don't have tests for the data race before(correct me if I'm wrong). You mean that we enable some test in CI?

**Comment by ZeroIntensity** [comment]
Just add something that stresses this concurrently, we'll get around to enabling TSan on `test_interpreters` later.

File: Misc/NEWS.d/next/Core_and_Builtins/2025-09-27-16-16-15.gh-issue-123828.UDxaxV.rst
Comment (ZeroIntensity) [inline Misc/NEWS.d/next/Core_and_Builtins/2025-09-27-16-16-15.gh-issue-123828.UDxaxV.rst:1]: I think we should remove this news entry. `_interpchannels` isn't exposed to any user-facing API.

**Comment by Zheaoli** [comment]
> Just add something that stresses this concurrently, we'll get around to enabling TSan on `test_interpreters` later.

This issue is triggered by TSAN test. So I think if we don't need add more test if we are planning to enable TSAN

**Comment by picnixz** [comment]
I think @ZeroIntensity wanted add a test that specifically triggers it, not one that indirectly triggers it.

**Comment by Zheaoli** [comment]
@ZeroIntensity @picnixz Actually I think we don't need new tests anymore. In #129824, we found that the current test will triger the TSAN report. And this PR can fix the test and I reenable the test now

**Review by ZeroIntensity — APPROVED** [review]
Ok, thanks, this looks good.

@ericsnowcurrently This is the race I was telling you about at the sprints. As far as I can tell, this is the only thing blocking `test_interpreters` from running on the free-threaded build.

**Comment by Zheaoli** [comment]
The test has been failed  https://buildbot.python.org/#/builders/75/builds/3415 

I'm trying to figure it out

**Comment by ZeroIntensity** [comment]
That might be the leak from #139073.

**Comment by ericsnowcurrently** [comment]
Any reason not to backport this to 3.14?

**Comment by ZeroIntensity** [comment]
I didn't think it was that big of a deal because `_interpchannels` is only used in tests at the moment, but I don't mind backporting it. We'll have to wait until 3.14.1 because 3.14 is currently locked down for the RC, though.
