### PR TITLE
gh-128002: fix `asyncio.all_tasks` against concurrent deallocations of tasks

### LINKED ISSUE #128656: `test_asyncio.test_free_threading.TestCFreeThreading.test_all_tasks_race` crashes intermittently in free-threaded builds
# Crash report

### What happened?

`test_asyncio.test_free_threading.TestCFreeThreading.test_all_tasks_race` crashes intermittently in free-threaded builds. The crash is reproducible by running the test repeatedly:

```
> ./python -m test test_asyncio.test_free_threading --match test.test_asyncio.test_free_threading.TestCFreeThreading.test_all_tasks_race -F
Using random seed: 1718500416
0:00:00 load avg: 0.85 Run tests sequentially in a single process
0:00:00 load avg: 0.85 [  1] test_asyncio.test_free_threading
0:00:00 load avg: 0.85 [  2] test_asyncio.test_free_threading
0:00:00 load avg: 0.85 [  3] test_asyncio.test_free_threading
0:00:00 load avg: 0.85 [  4] test_asyncio.test_free_threading
0:00:00 load avg: 0.85 [  5] test_asyncio.test_free_threading
0:00:00 load avg: 0.85 [  6] test_asyncio.test_free_threading
0:00:00 load avg: 0.85 [  7] test_asyncio.test_free_threading
0:00:00 load avg: 0.85 [  8] test_asyncio.test_free_threading
0:00:00 load avg: 0.85 [  9] test_asyncio.test_free_threading
0:00:00 load avg: 0.85 [ 10] test_asyncio.test_free_threading
0:00:00 load avg: 0.85 [ 11] test_asyncio.test_free_threading
0:00:00 load avg: 0.85 [ 12] test_asyncio.test_free_threading
0:00:01 load avg: 0.85 [ 13] test_asyncio.test_free_threading
0:00:01 load avg: 0.85 [ 14] test_asyncio.test_free_threading
0:00:01 load avg: 0.85 [ 15] test_asyncio.test_free_threading
0:00:01 load avg: 0.85 [ 16] test_asyncio.test_free_threading
Objects/object.c:578: PyObject_CallFinalizerFromDealloc: Assertion failed: PyObject_CallFinalizerFromDealloc called on object with a non-zero refcount
Enable tracemalloc to get the memory block allocation traceback

object address  : 0x200142d6020
object refcount : 1
object type     : 0x200015ecd10
object type name: _asyncio.Task
object repr     : <Task finished name='None' coro=<TestFreeThreading.test_all_tasks_race.<locals>.main.<locals>.coro() done, defined at /data/users/mpage/cpython/Lib/test/test_asyncio/test_free_threading.py:20> result=None>

Fatal Python error: _PyObject_AssertFailed: _PyObject_AssertFailed
Python runtime state: initialized

Thread 0x00007fbb97400640 (most recent call first):
  File "/data/users/mpage/cpython/Lib/test/test_asyncio/test_free_threading.py", line 21 in coro

Thread 0x00007fbb97e00640 (most recent call first):
  File "/data/users/mpage/cpython/Lib/asyncio/runners.py", line 208 in _cancel_all_tasks
  File "/data/users/mpage/cpython/Lib/asyncio/runners.py", line 71 in close
  File "/data/users/mpage/cpython/Lib/asyncio/runners.py", line 63 in __exit__
  File "/data/users/mpage/cpython/Lib/test/test_asyncio/test_free_threading.py", line 42 in runner
  File "/data/users/mpage/cpython/Lib/threading.py", line 996 in run
  File "/data/users/mpage/cpython/Lib/threading.py", line 1054 in _bootstrap_inner
  File "/data/users/mpage/cpython/Lib/threading.py", line 1016 in _bootstrap

Thread 0x00007fbb9ca00640 (most recent call first):
  File "/data/users/mpage/cpython/Lib/asyncio/runners.py", line 208 in _cancel_all_tasks
  File "/data/users/mpage/cpython/Lib/asyncio/runners.py", line 71 in close
  File "/data/users/mpage/cpython/Lib/asyncio/runners.py", line 63 in __exit__
  File "/data/users/mpage/cpython/Lib/test/test_asyncio/test_free_threading.py", line 42 in runner
  File "/data/users/mpage/cpython/Lib/threading.py", line 996 in run
  File "/data/users/mpage/cpython/Lib/threading.py", line 1054 in _bootstrap_inner
  File "/data/users/mpage/cpython/Lib/threading.py", line 1016 in _bootstrap

Thread 0x00007fbb9d400640 (most recent call first):
  File "/data/users/mpage/cpython/Lib/asyncio/events.py", line 98 in _run
  File "/data/users/mpage/cpython/Lib/asyncio/base_events.py", line 2026 in _run_once
  File "/data/users/mpage/cpython/Lib/asyncio/base_events.py", line 683 in run_forever
  File "/data/users/mpage/cpython/Lib/asyncio/base_events.py", line 712 in run_until_complete
  File "/data/users/mpage/cpython/Lib/asyncio/runners.py", line 127 in run
  File "/data/users/mpage/cpython/Lib/test/test_asyncio/test_free_threading.py", line 45 in runner
  File "/data/users/mpage/cpython/Lib/threading.py", line 996 in run
  File "/data/users/mpage/cpython/Lib/threading.py", line 1054 in _bootstrap_inner
  File "/data/users/mpage/cpython/Lib/threading.py", line 1016 in _bootstrap

Current thread 0x00007fbb9de00640 (most recent call first):
  File "/data/users/mpage/cpython/Lib/asyncio/events.py", line 98 in _run
  File "/data/users/mpage/cpython/Lib/asyncio/base_events.py", line 2041 in _run_once
  File "/data/users/mpage/cpython/Lib/asyncio/base_events.py", line 683 in run_forever
  File "/data/users/mpage/cpython/Lib/asyncio/base_events.py", line 712 in run_until_complete
  File "/data/users/mpage/cpython/Lib/asyncio/runners.py", line 127 in run
  File "/data/users/mpage/cpython/Lib/test/test_asyncio/test_free_threading.py", line 45 in runner
  File "/data/users/mpage/cpython/Lib/threading.py", line 996 in run
  File "/data/users/mpage/cpython/Lib/threading.py", line 1054 in _bootstrap_inner
  File "/data/users/mpage/cpython/Lib/threading.py", line 1016 in _bootstrap

Thread 0x00007fbb9e800640 (most recent call first):
  File "/data/users/mpage/cpython/Lib/asyncio/base_events.py", line 2041 in _run_once
  File "/data/users/mpage/cpython/Lib/asyncio/base_events.py", line 683 in run_forever
  File "/data/users/mpage/cpython/Lib/asyncio/base_events.py", line 712 in run_until_complete
  File "/data/users/mpage/cpython/Lib/asyncio/runners.py", line 127 in run
  File "/data/users/mpage/cpython/Lib/test/test_asyncio/test_free_threading.py", line 45 in runner
  File "/data/users/mpage/cpython/Lib/threading.py", line 996 in run
  File "/data/users/mpage/cpython/Lib/threading.py", line 1054 in _bootstrap_inner
  File "/data/users/mpage/cpython/Lib/threading.py", line 1016 in _bootstrap

Thread 0x00007fbb96000640 (most recent call first):
  File "/data/users/mpage/cpython/Lib/asyncio/runners.py", line 208 in _cancel_all_tasks
  File "/data/users/mpage/cpython/Lib/asyncio/runners.py", line 71 in close
  File "/data/users/mpage/cpython/Lib/asyncio/runners.py", line 63 in __exit__
  File "/data/users/mpage/cpython/Lib/test/test_asyncio/test_free_threading.py", line 42 in runner
  File "/data/users/mpage/cpython/Lib/threading.py", line 996 in run
  File "/data/users/mpage/cpython/Lib/threading.py", line 1054 in _bootstrap_inner
  File "/data/users/mpage/cpython/Lib/threading.py", line 1016 in _bootstrap

Thread 0x00007fbb94c00640 (most recent call first):
  <no Python frame>

Thread 0x00007fbb9f463740 (most recent call first):
  File "/data/users/mpage/cpython/Lib/threading.py", line 1105 in join
  File "/data/users/mpage/cpython/Lib/test/support/threading_helper.py", line 147 in start_threads
  File "/data/users/mpage/cpython/Lib/contextlib.py", line 148 in __exit__
  File "/data/users/mpage/cpython/Lib/test/test_asyncio/test_free_threading.py", line 53 in test_all_tasks_race
  File "/data/users/mpage/cpython/Lib/unittest/case.py", line 606 in _callTestMethod
  File "/data/users/mpage/cpython/Lib/unittest/case.py", line 660 in run
  File "/data/users/mpage/cpython/Lib/unittest/case.py", line 716 in __call__
  File "/data/users/mpage/cpython/Lib/unittest/suite.py", line 122 in run
  File "/data/users/mpage/cpython/Lib/unittest/suite.py", line 84 in __call__
  File "/data/users/mpage/cpython/Lib/unittest/suite.py", line 122 in run
  File "/data/users/mpage/cpython/Lib/unittest/suite.py", line 84 in __call__
  File "/data/users/mpage/cpython/Lib/test/libregrtest/testresult.py", line 148 in run
  File "/data/users/mpage/cpython/Lib/test/libregrtest/single.py", line 58 in _run_suite
  File "/data/users/mpage/cpython/Lib/test/libregrtest/single.py", line 38 in run_unittest
  File "/data/users/mpage/cpython/Lib/test/libregrtest/single.py", line 136 in test_func
  File "/data/users/mpage/cpython/Lib/test/libregrtest/single.py", line 92 in regrtest_runner
  File "/data/users/mpage/cpython/Lib/test/libregrtest/single.py", line 139 in _load_run_test
  File "/data/users/mpage/cpython/Lib/test/libregrtest/single.py", line 184 in _runtest_env_changed_exc
  File "/data/users/mpage/cpython/Lib/test/libregrtest/single.py", line 284 in _runtest
  File "/data/users/mpage/cpython/Lib/test/libregrtest/single.py", line 313 in run_single_test
  File "/data/users/mpage/cpython/Lib/test/libregrtest/main.py", line 372 in run_test
  File "/data/users/mpage/cpython/Lib/test/libregrtest/main.py", line 406 in run_tests_sequentially
  File "/data/users/mpage/cpython/Lib/test/libregrtest/main.py", line 552 in _run_tests
  File "/data/users/mpage/cpython/Lib/test/libregrtest/main.py", line 587 in run_tests
  File "/data/users/mpage/cpython/Lib/test/libregrtest/main.py", line 759 in main
  File "/data/users/mpage/cpython/Lib/test/libregrtest/main.py", line 767 in main
  File "/data/users/mpage/cpython/Lib/test/__main__.py", line 2 in <module>
  File "/data/users/mpage/cpython/Lib/runpy.py", line 88 in _run_code
  File "/data/users/mpage/cpython/Lib/runpy.py", line 198 in _run_module_as_main
Aborted (core dumped)
>
```

Here is the C stack trace:

```
(gdb) bt
#0  0x00007fbb9f28bacc in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007fbb9f23e686 in raise () from /lib64/libc.so.6
#2  0x00007fbb9f228833 in abort () from /lib64/libc.so.6
#3  0x00000000006f8605 in fatal_error_exit (status=<optimized out>) at Python/pylifecycle.c:3154
#4  0x00000000007037ec in fatal_error (fd=2, header=header@entry=1, prefix=prefix@entry=0x812aa0 <__func__.6> "_PyObject_AssertFailed", msg=msg@entry=0x81284f "_PyObject_AssertFailed", status=status@entry=-1)
    at Python/pylifecycle.c:3370
#5  0x0000000000703856 in _Py_FatalErrorFunc (func=func@entry=0x812aa0 <__func__.6> "_PyObject_AssertFailed", msg=msg@entry=0x81284f "_PyObject_AssertFailed") at Python/pylifecycle.c:3386
#6  0x0000000000539c83 in _PyObject_AssertFailed (obj=obj@entry=<_asyncio.Task() at remote 0x200142d6020>, expr=expr@entry=0x0,
    msg=msg@entry=0x8121a0 "PyObject_CallFinalizerFromDealloc called on object with a non-zero refcount", file=file@entry=0x812637 "Objects/object.c", line=line@entry=578,
    function=function@entry=0x812ee0 <__func__.46> "PyObject_CallFinalizerFromDealloc") at Objects/object.c:2968
#7  0x000000000053b106 in PyObject_CallFinalizerFromDealloc (self=self@entry=<_asyncio.Task() at remote 0x200142d6020>) at Objects/object.c:578
#8  0x00007fbb9efd6ed9 in TaskObj_dealloc (self=<_asyncio.Task() at remote 0x200142d6020>) at ./Modules/_asynciomodule.c:2818
#9  0x0000000000539423 in _Py_Dealloc (op=<_asyncio.Task() at remote 0x200142d6020>) at Objects/object.c:2991
#10 0x0000000000539598 in _Py_MergeZeroLocalRefcount (op=op@entry=<_asyncio.Task() at remote 0x200142d6020>) at Objects/object.c:436
#11 0x000000000055f43e in Py_DECREF (op=<_asyncio.Task() at remote 0x200142d6020>, lineno=511, filename=0x81c6e5 "Objects/setobject.c") at ./Include/refcount.h:343
#12 set_dealloc (
    self={<_asyncio.Task() at remote 0x200142d2020>, <_asyncio.Task() at remote 0x200142d4020>, <_asyncio.Task() at remote 0x200142d6020>, <_asyncio.Task() at remote 0x200142d2120>, <_asyncio.Task() at remote 0x200142d4120>, <_asyncio.Task() at remote 0x200142d6120>, <_asyncio.Task() at remote 0x200142d0220>, <_asyncio.Task() at remote 0x200142d2220>, <_asyncio.Task() at remote 0x200142d4220>, <_asyncio.Task() at remote 0x200142d6220>, <_asyncio.Task() at remote 0x200142d0320>, <_asyncio.Task() at remote 0x200142d2320>, <_asyncio.Task() at remote 0x200142d4320>, <_asyncio.Task() at remote 0x200142d6320>, <_asyncio.Task() at remote 0x200142d0420>, <_asyncio.Task() at remote 0x200142d2420>, <_asyncio.Task() at remote 0x200142d4420>, <_asyncio.Task() at remote 0x200142d6420>, <_asyncio.Task() at remote 0x200142d0520>, <_asyncio.Task() at remote 0x200142d2520>, <_asyncio.Task() at remote 0x200142d4520>, <_asyncio.Task() at remote 0x200142d6520>, <_asyncio.Task() at remote 0x200142d0620>, <_asyncio.Task() at remote 0x20014...(truncated)) at Objects/setobject.c:511
#13 0x0000000000539423 in _Py_Dealloc (
    op={<_asyncio.Task() at remote 0x200142d2020>, <_asyncio.Task() at remote 0x200142d4020>, <_asyncio.Task() at remote 0x200142d6020>, <_asyncio.Task() at remote 0x200142d2120>, <_asyncio.Task() at remote 0x200142d4120>, <_asyncio.Task() at remote 0x200142d6120>, <_asyncio.Task() at remote 0x200142d0220>, <_asyncio.Task() at remote 0x200142d2220>, <_asyncio.Task() at remote 0x200142d4220>, <_asyncio.Task() at remote 0x200142d6220>, <_asyncio.Task() at remote 0x200142d0320>, <_asyncio.Task() at remote 0x200142d2320>, <_asyncio.Task() at remote 0x200142d4320>, <_asyncio.Task() at remote 0x200142d6320>, <_asyncio.Task() at remote 0x200142d0420>, <_asyncio.Task() at remote 0x200142d2420>, <_asyncio.Task() at remote 0x200142d4420>, <_asyncio.Task() at remote 0x200142d6420>, <_asyncio.Task() at remote 0x200142d0520>, <_asyncio.Task() at remote 0x200142d2520>, <_asyncio.Task() at remote 0x200142d4520>, <_asyncio.Task() at remote 0x200142d6520>, <_asyncio.Task() at remote 0x200142d0620>, <_asyncio.Task() at remote 0x20014...(truncated)) at Objects/object.c:2991
#14 0x0000000000539598 in _Py_MergeZeroLocalRefcount (
    op=op@entry={<_asyncio.Task() at remote 0x200142d2020>, <_asyncio.Task() at remote 0x200142d4020>, <_asyncio.Task() at remote 0x200142d6020>, <_asyncio.Task() at remote 0x200142d2120>, <_asyncio.Task() at remote 0x200142d4120>, <_asyncio.Task() at remote 0x200142d6120>, <_asyncio.Task() at remote 0x200142d0220>, <_asyncio.Task() at remote 0x200142d2220>, <_asyncio.Task() at remote 0x200142d4220>, <_asyncio.Task() at remote 0x200142d6220>, <_asyncio.Task() at remote 0x200142d0320>, <_asyncio.Task() at remote 0x200142d2320>, <_asyncio.Task() at remote 0x200142d4320>, <_asyncio.Task() at remote 0x200142d6320>, <_asyncio.Task() at remote 0x200142d0420>, <_asyncio.Task() at remote 0x200142d2420>, <_asyncio.Task() at remote 0x200142d4420>, <_asyncio.Task() at remote 0x200142d6420>, <_asyncio.Task() at remote 0x200142d0520>, <_asyncio.Task() at remote 0x200142d2520>, <_asyncio.Task() at remote 0x200142d4520>, <_asyncio.Task() at remote 0x200142d6520>, <_asyncio.Task() at remote 0x200142d0620>, <_asyncio.Task() at remote 0x20014...(truncated)) at Objects/object.c:436
#15 0x00000000006b766f in Py_DECREF (
    op={<_asyncio.Task() at remote 0x200142d2020>, <_asyncio.Task() at remote 0x200142d4020>, <_asyncio.Task() at remote 0x200142d6020>, <_asyncio.Task() at remote 0x200142d2120>, <_asyncio.Task() at remote 0x200142d4120>, <_asyncio.Task() at remote 0x200142d6120>, <_asyncio.Task() at remote 0x200142d0220>, <_asyncio.Task() at remote 0x200142d2220>, <_asyncio.Task() at remote 0x200142d4220>, <_asyncio.Task() at remote 0x200142d6220>, <_asyncio.Task() at remote 0x200142d0320>, <_asyncio.Task() at remote 0x200142d2320>, <_asyncio.Task() at remote 0x200142d4320>, <_asyncio.Task() at remote 0x200142d6320>, <_asyncio.Task() at remote 0x200142d0420>, <_asyncio.Task() at remote 0x200142d2420>, <_asyncio.Task() at remote 0x200142d4420>, <_asyncio.Task() at remote 0x200142d6420>, <_asyncio.Task() at remote 0x200142d0520>, <_asyncio.Task() at remote 0x200142d2520>, <_asyncio.Task() at remote 0x200142d4520>, <_asyncio.Task() at remote 0x200142d6520>, <_asyncio.Task() at remote 0x200142d0620>, <_asyncio.Task() at remote 0x20014...(truncated), lineno=99, filename=0x8802a0 "Python/frame.c")
    at ./Include/refcount.h:343
#16 _PyFrame_ClearLocals (frame=frame@entry=0x200142001e8) at Python/frame.c:99
#17 0x00000000006b78e6 in _PyFrame_ClearExceptCode (frame=frame@entry=0x200142001e8) at Python/frame.c:124
#18 0x000000000064dab3 in clear_gen_frame (tstate=0xb5fb30, frame=0x200142001e8) at Python/ceval.c:1750
#19 0x0000000000651f66 in _PyEval_FrameClearAndPop (tstate=tstate@entry=0xb5fb30, frame=frame@entry=0x200142001e8) at Python/ceval.c:1763
#20 0x000000000067a993 in _PyEval_EvalFrameDefault (tstate=tstate@entry=0xb5fb30, frame=0x7fbb9ddff4f0, frame@entry=0x200142001e8, throwflag=throwflag@entry=0) at Python/generated_cases.c.h:7103
#21 0x00000000004e1144 in _PyEval_EvalFrame (throwflag=0, frame=0x200142001e8, tstate=0xb5fb30) at ./Include/internal/pycore_ceval.h:116
#22 gen_send_ex2 (gen=0x20014200190, arg=None, presult=0x7fbb9ddff658, exc=exc@entry=0, closing=closing@entry=0) at Objects/genobject.c:245
#23 0x00000000004e1311 in PyGen_am_send (self=<optimized out>, arg=<optimized out>, result=<optimized out>) at Objects/genobject.c:280
#24 0x0000000000492d54 in PyIter_Send (iter=iter@entry=<coroutine at remote 0x20014200190>, arg=None, result=result@entry=0x7fbb9ddff658) at Objects/abstract.c:2927
#25 0x00007fbb9efdd157 in task_step_impl (state=state@entry=0x20000591eb0, task=task@entry=0x200142d0120, exc=exc@entry=0x0) at ./Modules/_asynciomodule.c:2942
#26 0x00007fbb9efde105 in task_step (state=state@entry=0x20000591eb0, task=task@entry=0x200142d0120, exc=exc@entry=0x0) at ./Modules/_asynciomodule.c:3265
#27 0x00007fbb9efde536 in task_wakeup_lock_held (task=task@entry=0x200142d0120, o=o@entry=<_asyncio.Future() at remote 0x200142e0260>) at ./Modules/_asynciomodule.c:3365
#28 0x00007fbb9efde635 in task_wakeup (task=0x200142d0120, o=<_asyncio.Future() at remote 0x200142e0260>) at ./Modules/_asynciomodule.c:3397
#29 0x0000000000532a6f in cfunction_vectorcall_O (func=<built-in method task_wakeup of _asyncio.Task object at remote 0x200142d0120>, args=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>)
    at ./Include/cpython/methodobject.h:50
#30 0x00000000006a3456 in _PyObject_VectorcallTstate (tstate=tstate@entry=0xb5fb30, callable=<built-in method task_wakeup of _asyncio.Task object at remote 0x200142d0120>, args=args@entry=0x20014077a20,
    nargsf=nargsf@entry=1, kwnames=kwnames@entry=0x0) at ./Include/internal/pycore_call.h:167
#31 0x00000000006a493e in context_run (self=<_contextvars.Context at remote 0x20014070790>, args=0x20014077a18, nargs=2, kwnames=0x0) at Python/context.c:728
#32 0x0000000000531e1d in cfunction_vectorcall_FASTCALL_KEYWORDS (func=<built-in method run of _contextvars.Context object at remote 0x20014070790>, args=0x20014077a18, nargsf=<optimized out>, kwnames=0x0)
    at ./Include/cpython/methodobject.h:50
#33 0x00000000004b7bff in _PyVectorcall_Call (tstate=tstate@entry=0xb5fb30, func=0x531d16 <cfunction_vectorcall_FASTCALL_KEYWORDS>,
    callable=callable@entry=<built-in method run of _contextvars.Context object at remote 0x20014070790>,
    tuple=tuple@entry=(<built-in method task_wakeup of _asyncio.Task object at remote 0x200142d0120>, <_asyncio.Future() at remote 0x200142e0260>), kwargs=kwargs@entry=0x0) at ./Include/object.h:783
#34 0x00000000004b7f6b in _PyObject_Call (tstate=0xb5fb30, callable=callable@entry=<built-in method run of _contextvars.Context object at remote 0x20014070790>,
    args=(<built-in method task_wakeup of _asyncio.Task object at remote 0x200142d0120>, <_asyncio.Future() at remote 0x200142e0260>), kwargs=0x0) at Objects/call.c:348
#35 0x00000000004b7fc2 in PyObject_Call (callable=callable@entry=<built-in method run of _contextvars.Context object at remote 0x20014070790>, args=<optimized out>, kwargs=<optimized out>) at Objects/call.c:373
#36 0x000000000065ec31 in _PyEval_EvalFrameDefault (tstate=tstate@entry=0xb5fb30, frame=0x7fbb9efae540, frame@entry=0x7fbb9efae020, throwflag=throwflag@entry=0) at Python/generated_cases.c.h:1778
#37 0x000000000068260b in _PyEval_EvalFrame (throwflag=0, frame=0x7fbb9efae020, tstate=0xb5fb30) at ./Include/internal/pycore_ceval.h:116
#38 _PyEval_Vector (tstate=<optimized out>, func=<optimized out>, locals=locals@entry=0x0, args=0x7fbb9ddffd08, argcount=1, kwnames=<optimized out>) at Python/ceval.c:1911
#39 0x00000000004b5444 in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:413
#40 0x00000000004ba0c6 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=1, args=0x7fbb9ddffd08, callable=<function at remote 0x20000b8a810>, tstate=0xb5fb30) at ./Include/internal/pycore_call.h:167
#41 method_vectorcall (method=<optimized out>, args=<optimized out>, nargsf=<optimized out>, kwnames=0x0) at Objects/classobject.c:71
#42 0x00000000004b7bff in _PyVectorcall_Call (tstate=tstate@entry=0xb5fb30, func=0x4b9e34 <method_vectorcall>, callable=callable@entry=<method at remote 0x200019ccbb0>, tuple=tuple@entry=(), kwargs=kwargs@entry=0x0)
    at ./Include/object.h:783
#43 0x00000000004b7f6b in _PyObject_Call (tstate=0xb5fb30, callable=<method at remote 0x200019ccbb0>, args=(), kwargs=0x0) at Objects/call.c:348
#44 0x00000000004b7fc2 in PyObject_Call (callable=<optimized out>, args=<optimized out>, kwargs=<optimized out>) at Objects/call.c:373
#45 0x00000000007b8fc9 in thread_run (boot_raw=boot_raw@entry=0xb52d30) at ./Modules/_threadmodule.c:346
#46 0x0000000000727ff9 in pythread_wrapper (arg=<optimized out>) at Python/thread_pthread.h:242
#47 0x00007fbb9f289d82 in start_thread () from /lib64/libc.so.6
--Type <RET> for more, q to quit, c to continue without paging--
#48 0x00007fbb9f30ee20 in clone3 () from /lib64/libc.so.6
(gdb)
```

cc @kumaraditya303 

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.14.0a3+ experimental free-threading build (heads/main:58a9133fc2c, Jan  8 2025, 16:10:49) [GCC 11.5.0 20240719 (Red Hat 11.5.0-2)]

### PR DESCRIPTION
**Pull request by kumaraditya303**
* Issue: gh-128002

### CODE REVIEW

**Review by colesbury — COMMENTED** [review]
This doesn't look right to me. The object can still be part way through a dealloc call when a stop the world call happens.

Can you provide more details about what bug or crash you are trying to fix?

**Comment by kumaraditya303** [comment]
> This doesn't look right to me. The object can still be part way through a dealloc call when a stop the world call happens.

Please see https://github.com/python/cpython/issues/128002#issuecomment-2572973185

The bug is that the linked list holds borowwed references to tasks to it is possible that it is concurrently deallocated while it gets added to tasks list.

**Comment by kumaraditya303** [comment]
Crash backtrace:

<details>


Objects/object.c:578: PyObject_CallFinalizerFromDealloc: Assertion failed: PyObject_CallFinalizerFromDealloc called on object with a non-zero refcount
Enable tracemalloc to get the memory block allocation traceback

object address  : 0x7fb3781e1820
object refcount : 1
object type     : 0x7fb3629e7d10
object type name: _asyncio.Task
object repr     : <Task finished name='None' coro=<TestFreeThreading.test_all_tasks_race.<locals>.main.<locals>.coro() done, defined at /home/realkumaraditya/cpython/Lib/test/test_asyncio/test_free_threading.py:24> result=None>

Fatal Python error: _PyObject_AssertFailed: _PyObject_AssertFailed
Python runtime state: initialized

Thread 0x00007fb34edfd6c0 (most recent call first):
  File "/home/realkumaraditya/cpython/Lib/test/test_asyncio/test_free_threading.py", line 29 in main
  File "/home/realkumaraditya/cpython/Lib/asyncio/events.py", line 98 in _run
  File "/home/realkumaraditya/cpython/Lib/asyncio/base_events.py", line 2033 in _run_once
  File "/home/realkumaraditya/cpython/Lib/asyncio/base_events.py", line 678 in run_forever
  File "/home/realkumaraditya/cpython/Lib/asyncio/base_events.py", line 707 in run_until_complete
  File "/home/realkumaraditya/cpython/Lib/asyncio/runners.py", line 127 in run
  File "/home/realkumaraditya/cpython/Lib/test/test_asyncio/test_free_threading.py", line 49 in runner
  File "/home/realkumaraditya/cpython/Lib/threading.py", line 996 in run
  File "/home/realkumaraditya/cpython/Lib/threading.py", line 1054 in _bootstrap_inner
  File "/home/realkumaraditya/cpython/Lib/threading.py", line 1016 in _bootstrap

Current thread 0x00007fb34fdff6c0 (most recent call first):
  File "/home/realkumaraditya/cpython/Lib/asyncio/runners.py", line 208 in _cancel_all_tasks
  File "/home/realkumaraditya/cpython/Lib/asyncio/runners.py", line 71 in close
  File "/home/realkumaraditya/cpython/Lib/asyncio/runners.py", line 63 in __exit__
  File "/home/realkumaraditya/cpython/Lib/test/test_asyncio/test_free_threading.py", line 46 in runner
  File "/home/realkumaraditya/cpython/Lib/threading.py", line 996 in run
  File "/home/realkumaraditya/cpython/Lib/threading.py", line 1054 in _bootstrap_inner
  File "/home/realkumaraditya/cpython/Lib/threading.py", line 1016 in _bootstrap

Thread 0x00007fb3542ff6c0 (most recent call first):
  File "/home/realkumaraditya/cpython/Lib/asyncio/runners.py", line 208 in _cancel_all_tasks
  File "/home/realkumaraditya/cpython/Lib/asyncio/runners.py", line 71 in close
  File "/home/realkumaraditya/cpython/Lib/asyncio/runners.py", line 63 in __exit__
  File "/home/realkumaraditya/cpython/Lib/test/test_asyncio/test_free_threading.py", line 46 in runner
  File "/home/realkumaraditya/cpython/Lib/threading.py", line 996 in run
  File "/home/realkumaraditya/cpython/Lib/threading.py", line 1054 in _bootstrap_inner
  File "/home/realkumaraditya/cpython/Lib/threading.py", line 1016 in _bootstrap

Thread 0x00007fb3523fe6c0 (most recent call first):
  <no Python frame>

Thread 0x00007fb3a66ebf40 (most recent call first):
  File "/home/realkumaraditya/cpython/Lib/threading.py", line 1105 in join
  File "/home/realkumaraditya/cpython/Lib/test/support/threading_helper.py", line 147 in start_threads
  File "/home/realkumaraditya/cpython/Lib/contextlib.py", line 148 in __exit__
  File "/home/realkumaraditya/cpython/Lib/test/test_asyncio/test_free_threading.py", line 57 in test_all_tasks_race
  File "/home/realkumaraditya/cpython/Lib/unittest/case.py", line 606 in _callTestMethod
  File "/home/realkumaraditya/cpython/Lib/unittest/case.py", line 660 in run
  File "/home/realkumaraditya/cpython/Lib/unittest/case.py", line 716 in __call__
  File "/home/realkumaraditya/cpython/Lib/unittest/suite.py", line 122 in run
  File "/home/realkumaraditya/cpython/Lib/unittest/suite.py", line 84 in __call__
  File "/home/realkumaraditya/cpython/Lib/unittest/suite.py", line 122 in run
  File "/home/realkumaraditya/cpython/Lib/unittest/suite.py", line 84 in __call__
  File "/home/realkumaraditya/cpython/Lib/test/libregrtest/testresult.py", line 148 in run
  File "/home/realkumaraditya/cpython/Lib/test/libregrtest/single.py", line 58 in _run_suite
  File "/home/realkumaraditya/cpython/Lib/test/libregrtest/single.py", line 38 in run_unittest
  File "/home/realkumaraditya/cpython/Lib/test/libregrtest/single.py", line 136 in test_func
  File "/home/realkumaraditya/cpython/Lib/test/libregrtest/single.py", line 92 in regrtest_runner
  File "/home/realkumaraditya/cpython/Lib/test/libregrtest/single.py", line 139 in _load_run_test
  File "/home/realkumaraditya/cpython/Lib/test/libregrtest/single.py", line 184 in _runtest_env_changed_exc
  File "/home/realkumaraditya/cpython/Lib/test/libregrtest/single.py", line 284 in _runtest
  File "/home/realkumaraditya/cpython/Lib/test/libregrtest/single.py", line 313 in run_single_test
  File "/home/realkumaraditya/cpython/Lib/test/libregrtest/worker.py", line 83 in worker_process
  File "/home/realkumaraditya/cpython/Lib/test/libregrtest/worker.py", line 118 in main
  File "/home/realkumaraditya/cpython/Lib/test/libregrtest/worker.py", line 122 in <module>
  File "/home/realkumaraditya/cpython/Lib/runpy.py", line 88 in _run_code
  File "/home/realkumaraditya/cpython/Lib/runpy.py", line 198 in _run_module_as_main
Kill <WorkerThread #1 running test=test_asyncio.test_free_threading pid=35002 time=4.4 sec> process group
Kill <WorkerThread #2 running test=test_asyncio.test_free_threading pid=35001 time=4.6 sec> process group
Kill <WorkerThread #3 running test=test_asyncio.test_free_threading pid=35045 time=1.8 sec> process group

== Tests result: FAILURE ==

1 test failed:
    test_asyncio.test_free_threading

50 tests OK.

Total duration: 5 min 30 sec
Total tests: run=800
Total test files: run=51 failed=1
Result: FAILURE

</details>

**Comment by colesbury** [comment]
Do you have a command to reproduce the crash?

You wrote that:

> [A task object] can be concurrently deallocated while list is being read in another thread as deallocation doesn't hold the state lock

There are two things that confuse me:

* The `unregister_task()` function holds the state lock, which prevents concurrent traversal of the list for that important function.
* The state lock isn't held for the entire deallocation sequence, but it's also not atomic with respect to a stop the world pause. That makes me thing that it's like to have similar problems. For example, the `unregister_task` function may block on acquiring the state lock allowing a stop-the-world pause to happen concurrently (while the task is blocked on the lock). There may be other similar points where a stop the world call can happen, such as when calling other objects' destructors.

Additionally, the way this linked list works worries me:

* It's essentially a list of weak references, just not implemented using `PyWeakRef` object for performance reasons
* Weakrefs are cleared later on during dealloc -- not in `tp_finalize` -- when we know that the object will definitely be destroyed.
* Weakrefs have [special handling](https://github.com/python/cpython/blob/b9c693dcca01537eee1ef716ffebc632be37594b/Include/internal/pycore_weakref.h#L58) for dealing with similar concurrent deallocations.
* Weakrefs also have special hooks in the GC, but I'm not sure that's relevant here.

Anyways, I think it may be worth trying to match the weakref implementation since we know that it works.

File: Modules/_asynciomodule.c [hunk 1]
```diff
@@ -3767,9 +3767,18 @@ _asyncio_all_tasks_impl(PyObject *module, PyObject *loop)
...
-    struct llist_node *node;
 
+    // The linked list holds borrowed references to the tasks
+    // so before reading from it, all other threads
+    // are stopped using stop the world event so that
+    // no task could be concurrently deallocated while being
+    // added to the list.
+    // The state critical section need not to be held as
+    // all other threads are paused.
+    PyInterpreterState *interp = PyInterpreterState_Get();
```
Comment (ZeroIntensity) [inline Modules/_asynciomodule.c]: You probably want `_PyInterpreterState_GET`, the public function will do extra checking that you don't need.

**Comment by colesbury** [comment]
From looking at the crash backtrace, I think the important thing here would be to use `_Py_TryIncref` in `all_tasks` like we do in [`_PyWeakref_GET_REF`](https://github.com/python/cpython/blob/b9c693dcca01537eee1ef716ffebc632be37594b/Include/internal/pycore_weakref.h#L77). This will avoid incref'ing objects that have zero refcount (and are either about to be deallocated or partway through deallocation).

Something like:

```c
    llist_for_each_safe(node, &state->asyncio_tasks_head) {
        TaskObj *task = llist_data(node, TaskObj, task_node);
        if (_Py_TryIncref(task)) {
            if (_PyList_AppendTakeRef(tasks, (PyObject *)task) < 0) {
                ...
            }
        }
    }

```

**Comment by kumaraditya303** [comment]
> Do you have a command to reproduce the crash?

Running `test_asyncio.test_free_threading` in a loop on main reproduces the crash.
`env TSAN_OPTIONS=suppressions={$PWD}/Tools/tsan/suppressions_free_threading.txt ./python -m test
 test_asyncio.test_free_threading -j 4 -F`

**Comment by kumaraditya303** [comment]
> Anyways, I think it may be worth trying to match the weakref implementation since we know that it works.

So I think the following changes need to be made:
- Move `unregister_task` to be in `tp_dealloc` so that it is called when task is definitely getting deallocated.
-  In `all_tasks` use `_Py_TryIncref` so that if task is concurrently deallocated, it doesn't gets added to the tasks list.
- The state lock is held while iteration of linked list as it was done before this PR
- No need for stop the world pause in all_tasks


Did I get it correctly? Aside, thanks for your explanation! I didn't know that it was possible that stop the world could happen while a deallocator is running concurrently.

**Comment by colesbury** [comment]
Yes, but on second thought let's keep the `unregister_task` in the finalizer for now. I'm not entirely sure where it should be. Normal dealloc calls clear weakrefs relatively late (after finalizers are invoked), but the cyclic GC clears them earlier (before finalizers). I can't think of any concrete problems immediately, but I'm a bit worried about the ordering.

**Review by colesbury — APPROVED** [review]
