### PR TITLE
gh-104282: Fix null pointer dereference in `lzma._decode_filter_properties`

### LINKED ISSUE #104282: `lzma._decode_filter_properties` crashes with BCJ filter and buffer of zero length
Example:

```python
>>> import lzma
>>> lzma._decode_filter_properties(lzma.FILTER_X86, b"")
Segmentation fault (core dumped)
```
In `_lzma__decode_filter_properties_impl` call to `lzma_properties_decode` returns `LZMA_OK` and leaves `filter.options` intact (that is uninitialized) if `filter.id` is id of a BCJ filter (FILTER_X86, FILTER_POWERPC, FILTER_IA64, FILTER_ARM, FILTER_ARMTHUMB, FILTER_SPARC) and `encoded_props->len` is equal to zero.

https://github.com/python/cpython/blob/01cc9c1ff79bf18fe34c05c6cd573e79ff9487c3/Modules/_lzmamodule.c#L1487-L1495

Then, in `build_filter_spec`, access to `f->options->start_offset` leads to segmentation fault:

https://github.com/python/cpython/blob/01cc9c1ff79bf18fe34c05c6cd573e79ff9487c3/Modules/_lzmamodule.c#L489-L499

The PR is on the way.
3.9-3.12 are affected for sure.

### Linked PRs
* gh-104283
* gh-114181
* gh-114182

### PR DESCRIPTION
**Pull request by chgnrdv**
Fixes #104282

* Issue: gh-104282

### CODE REVIEW

File: Misc/NEWS.d/next/Library/2023-05-08-09-30-00.gh-issue-104282.h4c6Eb.rst [hunk 1]
```diff
@@ -0,0 +1 @@
+Fix use of uninitialized value in :func:`lzma._decode_filter_properties` due to improper handling of BCJ filters with properties of zero length. Patch by Radislav Chugunov.
```
Comment (serhiy-storchaka) [inline Misc/NEWS.d/next/Library/2023-05-08-09-30-00.gh-issue-104282.h4c6Eb.rst]: It is not use of uninitialized value, it is null pointer dereference.
```suggestion
Fix null pointer dereference in :func:`lzma._decode_filter_properties`
due to improper handling of BCJ filters with properties of zero length.
Patch by Radislav Chugunov.
```

File: Modules/_lzmamodule.c [hunk 2]
```diff
@@ -1495,7 +1497,9 @@ _lzma__decode_filter_properties_impl(PyObject *module, lzma_vli filter_id,
 
     /* We use vanilla free() here instead of PyMem_Free() - filter.options was
        allocated by lzma_properties_decode() using the default allocator. */
-    free(filter.options);
+    if (filter.options) {
+        free(filter.options);
+    }
```
Comment (serhiy-storchaka) [inline Modules/_lzmamodule.c]: It is not needed. `free()` accepts NULL.
```suggestion
    free(filter.options);
```

**Review by serhiy-storchaka — APPROVED** [review]
LGTM.
