### PR TITLE
GH-78724: Initialize struct.Struct in __new__ 

### LINKED ISSUE #75960: assertion failures and a crash when using an uninitialized struct.Struct object
BPO | [31779](https://bugs.python.org/issue31779)
--- | :---
Nosy | @mdickinson, @meadori, @berkerpeksag, @serhiy-storchaka, @orenmn, @izbyshev, @iritkatriel
PRs | <li>python/cpython#3984</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-10-13.10:54:20.321>
labels = ['extension-modules', '3.10', '3.9', 'type-crash', '3.11']
title = 'assertion failures and a crash when using an uninitialized struct.Struct object'
updated_at = <Date 2021-10-19.10:22:17.196>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-19.10:22:17.196>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2017-10-13.10:54:20.321>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31779
keywords = ['patch']
message_count = 3.0
messages = ['304328', '325462', '404285']
nosy_count = 7.0
nosy_names = ['mark.dickinson', 'meador.inge', 'berker.peksag', 'serhiy.storchaka', 'Oren Milman', 'izbyshev', 'iritkatriel']
pr_nums = ['3984']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31779'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### LINKED ISSUE #78724: _struct.Struct: calling functions without calling __init__ results in SystemError
BPO | [34543](https://bugs.python.org/issue34543)
--- | :---
Nosy | @ronaldoussoren, @stevendaprano, @ZackerySpytz, @dekrain, @iritkatriel
PRs | <li>python/cpython#14777</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-08-29.16:18:52.469>
labels = ['extension-modules', '3.10', '3.9', 'type-crash', '3.11']
title = '_struct.Struct: calling functions without calling __init__ results in SystemError'
updated_at = <Date 2021-10-19.11:59:55.712>
user = 'https://github.com/dekrain'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-19.11:59:55.712>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2018-08-29.16:18:52.469>
creator = 'DeKrain'
dependencies = []
files = []
hgrepos = []
issue_num = 34543
keywords = ['patch']
message_count = 12.0
messages = ['324330', '324331', '324335', '324338', '324341', '324484', '324498', '324504', '324505', '324507', '324509', '404291']
nosy_count = 5.0
nosy_names = ['ronaldoussoren', 'steven.daprano', 'ZackerySpytz', 'DeKrain', 'iritkatriel']
pr_nums = ['14777']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue34543'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-143643
* gh-143659
* gh-143695
* gh-143714

### PR DESCRIPTION
**Pull request by kumaraditya303**
Closes https://github.com/python/cpython/issues/75960
Closes https://github.com/python/cpython/issues/78724

* Issue: gh-78724

### CODE REVIEW

**Review by ambv — APPROVED** [review]
LGTM. I'm wondering if moving initialization from `__init__` to `__new__` can cause some user-facing backwards compatibility, say, wrt subclassing or something. I asked for more eyes on this.

**Comment by mdickinson** [comment]
Apologies for the silence; I'll get to this by the end of this weekend.

**Comment by mdickinson** [comment]
LGTM too.

To be on the safe side, I'd recommend _not_ backporting this to 3.10, though it seems fine to backport to 3.11 if @pablogsal agrees. The bugs being fixed seem to be of the self-inflicted "well don't do that then" variety, so while it's definitely nice to have them fixed, it seems unlikely that they'll be blocking any real users of `Struct`. And there's just enough possibility of unintended side-effects that it doesn't seem worth changing this in an already-released version of Python.

**Review by mdickinson — APPROVED** [review]

**Comment by mdickinson** [comment]
> LGTM. I'm wondering if moving initialization from `__init__` to `__new__` can cause some user-facing backwards compatibility, say, wrt subclassing or something.

Yes, it can. This is fine, on Python 3.10:

```
>>> import struct
>>> class Bob(struct.Struct):
...     def __init__(self, format):
...         super().__init__(format)
... 
>>> b = Bob("!f")
```

But it breaks on this branch:

```
>>> import struct
>>> class Bob(struct.Struct):
...     def __init__(self, format):
...         super().__init__(format)
... 
>>> b = Bob("!f")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in __init__
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
```

I'm finding it hard to imagine _why_ anyone would be subclassing `Struct` like this, so it doesn't seem like a real issue if the behaviour changes in 3.11 or 3.12 (and in particular this certainly doesn't seem worth a deprecation period), but it does seem like sufficient reason to be careful in 3.10.

**Comment by pablogsal** [comment]
> To be on the safe side, I'd recommend _not_ backporting this to 3.10, though it seems fine to backport to 3.11 if @pablogsal agrees.

I think is ok to backport to 3.11 👍  Not sure if it makes sense to mention the subclassing incompatibility in the what's new, though.

**Comment by mdickinson** [comment]
@kumaraditya303 Apologies, Kumar; I'm having second thoughts here. While common sense says that no-one will be subclassing `struct.Struct` this way, experience says that someone somewhere will be, and it would be at least a bit irresponsible to change the behaviour.

Can you think of any ways that we could fix these bugs without the backward compatibility breakage?

**Review by mdickinson — CHANGES_REQUESTED** [review]
On balance, the backwards compatibility change seems like something we should avoid if possible.

**Comment by kumaraditya303** [comment]
Thanks for the reviews!

> Can you think of any ways that we could fix these bugs without the backward compatibility breakage?

I have made it backwards compatible by adding `__init__` and added a test for subclassing.

I have made the requested changes; please review again

**Comment by kumaraditya303** [comment]
ping @mdickinson @ambv

File: Modules/_struct.c [hunk 1]
```diff
@@ -1492,8 +1521,10 @@ Struct___init___impl(PyStructObject *self, PyObject *format)
 
     Py_SETREF(self->s_format, format);
 
-    ret = prepare_s(self);
-    return ret;
+    if (prepare_s(self) < 0) {
```
Comment (mdickinson) [inline Modules/_struct.c]: It looks as though we're duplicating work at this point: `prepare_s` is being called twice for a new `struct.Struct` instance. I think we can simply drop most of the content of the `__init__` method: no need to do the `prepare_s`, the `Py_SETREF` or the type check.

Removing those things would technically be a backwards incompatible change, since it means you can't deliberately call `__init__` on an existing `struct.Struct` instance with a new format string (or at least, that that `__init__` call wouldn't have any useful effect), but I think that's not unreasonable, especially if this change only goes into 3.12.

**Comment by mdickinson** [comment]
@kumaraditya303 Sorry for taking so long to get back to this.

So the current code in this PR ends up duplicating some of the work: we end up calling `prepare_s` every time a `struct.Struct` instance is created, for example.

Suggestion:

1. Drop all content from the `__init__` method: the body of the method can simply be `return 0`.2. 
2. Apply this change only for 3.12 and later.3. 

The reason for (2) here is that (1) is technically a breaking change, in that doing something like `s = struct.Struct('<f')` followed by `s.__init__('>f')` would not have the same effect as before. But I think that change would still be okay for 3.12: unlike the subclassing that we were worried about above, deliberately calling `s.__init__` with a new format just doesn't seem like a plausible use-case.

**Comment by mdickinson** [comment]
Alternatively, if we _really_ want to try to stay perfectly backwards compatible (modulo the bugs being fixed, of course), we'd need to find a way re-organise the logic so that we don't end up calling `prepare_s` twice in normal use.

**Comment by kumaraditya303** [comment]
Thanks for the review, I'll make the changes by next weekend.

**Comment by kumaraditya303** [comment]
I removed the code duplication and it is now only for 3.12+.

File: Modules/_struct.c (hunk 1 above)
Comment (kumaraditya303) [reply Modules/_struct.c]: Fixed.

**Comment by kumaraditya303** [comment]
cc @mdickinson I have made the changes, I removed the code duplication and it is now only for 3.12+.

**Review by mdickinson — APPROVED** [review]
LGTM. I'll do a buildbot run, to be on the safe side.

**Comment by mdickinson** [comment]
The buildbots look happy. There are still three checks pending as of writing, but enough checks have passed to satisfy me. I'll merge now, but continue to watch those remaining three bots.

**Comment by dopplershift** [comment]
So I just hit this while trying to upgrade to 3.12. While subclassing works, subclasses *MUST* now match the same signature for `__init__`:

```python
from struct import Struct

class FloatStruct(Struct):
    def __init__(self):
        super().__init__('f')

f = FloatStruct()
```
gives
```pytb
Traceback (most recent call last):
  File "/Users/rmay/test.py", line 7, in <module>
    f = FloatStruct()
        ^^^^^^^^^^^^^
TypeError: Struct() missing required argument 'format' (pos 1)
```

My actual use case was passing additional arguments, but either way fails.
