### PR TITLE
gh-118692: Avoid creating unnecessary StopIteration instances for monitoring

### LINKED ISSUE #118692: Avoid creating a StopIteration instance for monitoring
# Feature or enhancement

### Proposal:

A new C-API for injecting monitoring events was discussed in https://github.com/python/cpython/issues/111997 and implemented for Py3.13 in https://github.com/python/cpython/pull/116413

A remaining issue is that signalling "STOP_ITERATION" events requires a `StopIteration` exception instance, whereas generators usually try to avoid creating one during termination to increase their performance.

I think it would be best if CPython's monitoring infrastructure created a StopIteration instance automatically when it detects that it needs to notify about it without having one. It's in the best position to detect whether it really needs an exception instance or not. Event sources shouldn't be forced to a) figure that out themselves or b) create an instance just for it to be thrown away.

CPython already creates an exception instance for submitting a monitoring event for a generator, but does so unconditionally. It would also benefit from not having to generate one unless it's really needed for signalling.

https://github.com/python/cpython/blob/52485967813acdb35c274e1b2eaedd34e9ac01fc/Python/bytecodes.c#L289-L317

Basically, we should move the existing code from the byte code handlers all the way to the other side into the notification mechanism.

In order to report the correct StopIteration value, the event creation function should accept an object value directly, and create a `StopIteration` instance for that value only if it ends up signalling it to listeners.

We might allow passing the value `NULL`  (as opposed to the object value `None`) to make the machinery look up an actually existing currently raised `StopIteration` instance. Alternatively, passing a `StopIteration` instance as value is probably also a reasonably clear indication for an instance being available already. We may also consider adding two event creation functions, one with a bare stop value and one with a readily created `StopIteration` instance.

This ticket proposes a usability/performance enhancement to a newly added feature in Py3.13, and thus does not fall under the "beta-1" release end of new features.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Links to previous discussion of this feature:

https://github.com/python/cpython/pull/116413#issuecomment-2093689068

### Linked PRs
* gh-119216
* gh-119497

### PR DESCRIPTION
**Pull request by iritkatriel**
Fixes #118692.

* Issue: gh-118692

----
📚 Documentation preview 📚: https://cpython-previews--119216.org.readthedocs.build/

### CODE REVIEW

File: Python/instrumentation.c [hunk 1]
```diff
@@ -2712,15 +2712,17 @@ _PyMonitoring_FirePyUnwindEvent(PyMonitoringState *state, PyObject *codelike, in
...
+    assert(!PyErr_Occurred());
+    PyErr_SetObject(PyExc_StopIteration, value);
     PyObject *exc;
     if (exception_event_setup(&exc, event) < 0) {
         return -1;
     }
     PyObject *args[4] = { NULL, NULL, NULL, exc };
     int err = capi_call_instrumentation(state, codelike, offset, args, 3, event);
-    return exception_event_teardown(err, exc);
+    return exception_event_teardown(err, NULL);
```
Comment (markshannon) [inline Python/instrumentation.c:2727]: If `err` is non-zero, this will crash as `exception_event_teardown` decrefs `NULL`. I think changing to in `Py_XDECREF` in `exception_event_teardown` will fix this.

**Review by markshannon — CHANGES_REQUESTED** [review]
Possible NULL dereference needs fixing. Looks good, otherwise.

**Comment by iritkatriel** [comment]
I have made the requested changes; please review again.

**Review by markshannon — APPROVED** [review]

**Comment by scoder** [comment]
This needs backporting to 3.13.
