### PR TITLE
gh-149085: Add max_threads keyword to faulthandler.dump_traceback()

### LINKED ISSUE #149085: faulthandler: make per-call thread dump cap configurable
# Feature or enhancement

### Proposal:

`faulthandler.dump_traceback()` and `faulthandler.dump_traceback_later()` cap their output at 100 threads via a hardcoded `MAX_NTHREADS = 100` in `Python/traceback.c`. Past the cap, the dump writes `"...\n"` and stops.

```c
/* Python/traceback.c */
#define MAX_NTHREADS 100

const char* _Py_NO_SANITIZE_THREAD
_Py_DumpTracebackThreads(int fd, PyInterpreterState *interp,
                         PyThreadState *current_tstate)
{
    ...
    if (nthreads >= MAX_NTHREADS) {
        PUTS(fd, "...\n");
        break;
    }
    ...
}
```

The constant has been there since faulthandler was added in 2010 (gh-2762). It's still documented as a fixed limit in `Doc/library/faulthandler.rst`:

> It is limited to 100 frames and 100 threads.

Proposal: add a keyword-only `max_threads` to both functions, default 100. Callers that omit it get identical behavior to today.

```python
faulthandler.dump_traceback(file=sys.stderr, all_threads=True, *, max_threads=100)
faulthandler.dump_traceback_later(timeout, repeat=False, file=sys.stderr,
                                  exit=False, *, max_threads=100)
```

### Motivation

100 was reasonable in 2010, but a few things can make it a problem now:

1. **Library-internal thread counts.** A `google-cloud-firestore` Watch subscription spawns ~2 long-lived gRPC threads (`google.api_core.bidi`, `grpc._channel.consume_request_iterator`). 50 active subscriptions ≈ 100 threads. Other widely-used libraries (gRPC channels generally, ThreadPoolExecutor, asyncio's default executor) push it further. Modern server processes routinely run with 100+ long-lived threads, regardless of what the application code itself spawns.

2. **Dump order is newest-thread-first.** `_Py_DumpTracebackThreads` walks `tstate` via `PyInterpreterState_ThreadHead → tstate->next`. New thread states are *prepended* to the list by `add_threadstate()` in `Python/pystate.c`, so this walk visits the most-recently-created thread first and the main thread last. With more than 100 threads alive, the cap is guaranteed to cut off the oldest entries - including the main thread.

When you reach for `dump_traceback_later` as a deadlock-detection watchdog, the dump can arrive missing the main thread - the one you actually wanted.

### Has this already been discussed elsewhere?

Searched the issue tracker, PR history, Discourse, and python-dev. Nothing found. gh-98825 is adjacent (per-thread context for tracebacks) but doesn't touch the cap.

### Links to previous discussion of this feature

None found.

---

## Implementation

Patch ready: ~180 lines across 12 files (most auto-generated clinic + globals). Builds clean on current `main`. `test_faulthandler` passes 50/50, 6 platform skips. Includes:

- Two tests in `Lib/test/test_faulthandler.py`:
  - `test_dump_traceback_max_threads`: spawns 6 worker threads, dumps with `max_threads=3`, asserts the truncation marker is present and only 3 thread headers appear.
  - `test_dump_traceback_max_threads_default`: dumps without the kwarg, asserts no marker on a process with <100 threads.
- Doc updates in `Doc/library/faulthandler.rst` (signatures, `versionchanged:: 3.15`, the limits paragraph).
- `Misc/NEWS.d/next/Library/...` entry.

### Implementation summary

| File | Change |
|---|---|
| `Python/traceback.c` | `_Py_DumpTracebackThreads` gains `max_nthreads`; `MAX_NTHREADS` define moves to the header (renamed `_Py_TRACEBACK_MAX_NTHREADS`). |
| `Include/internal/pycore_traceback.h` | Expose `_Py_TRACEBACK_MAX_NTHREADS`; update function signature. |
| `Include/internal/pycore_faulthandler.h` | Add `max_nthreads` to the watchdog `thread` struct. |
| `Modules/faulthandler.c` | New `max_threads` clinic kwarg on both functions (default 100). Fatal-signal handler passes `_Py_TRACEBACK_MAX_NTHREADS` explicitly. |
| `Python/pylifecycle.c` | `_Py_FatalError_DumpTracebacks` passes `_Py_TRACEBACK_MAX_NTHREADS` explicitly. |
| `Doc/library/faulthandler.rst` | Document the kwarg + `versionchanged`. |
| `Lib/test/test_faulthandler.py` | Two new tests. |

### Backward compatibility

Default `max_threads=100` matches the old cap, so omitting the kwarg gives no change. In-tree fatal-signal callers and the watchdog all pass `_Py_TRACEBACK_MAX_NTHREADS` explicitly.

No public C API change. `_Py_DumpTracebackThreads` and `_Py_TRACEBACK_MAX_NTHREADS` both live in `pycore_traceback.h`, gated by `Py_BUILD_CORE`.

### Open questions

1. **`register()` could get the same kwarg.** Left it out to keep the diff minimal. Signal-handler path has signal-safety constraints that make the rationale weaker there but not zero. Easy follow-up.

2. **`MAX_FRAME_DEPTH` is similarly hardcoded.** Same pattern would apply but ergonomics differ - a deep stack on a deadlocked thread is usually what you want, not what you'd cap. Probably a separate proposal.

I'll open a PR if there's interest as scoped.

### CPython versions tested on

3.15 (current `main`).

### Operating systems tested on

Linux, macOS.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Links to previous discussion of this feature:

_No response_

### Linked PRs
* gh-149106

### PR DESCRIPTION
**Pull request by efroemling**
Closes #149085.

Adds a keyword-only `max_threads` argument to `faulthandler.dump_traceback()` and `faulthandler.dump_traceback_later()`, raising the per-call cap on the number of threads dumped (previously a hardcoded `MAX_NTHREADS = 100` in `Python/traceback.c`). Default of 100 preserves existing behavior.

Motivation (covered in the issue): on server processes with many worker or gRPC threads, watchdog dumps silently lose the main thread because tstates are prepended to the interpreter's thread list and the cap chops the tail. This was the failure mode that prompted the issue.

Scope per @vstinner's confirmation in the issue: `max_threads` only; the frame/stack limits raised by @ZeroIntensity are left as-is for now.

The hardcoded 100 is moved to a new internal macro `_Py_TRACEBACK_MAX_NTHREADS` in `pycore_traceback.h` so the in-tree fatal-signal callers (`faulthandler.c`, `pylifecycle.c`) all share one source of truth.

* Issue: gh-149085

----
📚 Documentation preview 📚: https://cpython-previews--149106.org.readthedocs.build/

### CODE REVIEW

File: Modules/faulthandler.c [hunk 1]
```diff
@@ -205,7 +205,10 @@ faulthandler_dump_traceback(int fd, int all_threads,
     PyThreadState *tstate = PyGILState_GetThisThreadState();
 
     if (all_threads == 1) {
-        (void)_Py_DumpTracebackThreads(fd, NULL, tstate);
+        /* Fatal-signal path has no caller-supplied cap; use the
+           historical default. */
```
Comment (vstinner) [inline Modules/faulthandler.c]: Can you modify faulthandler.enable() to add a *max_threads* parameter and store the value in fatal_error? See _faulthandler_runtime_state structure in `Include/internal/pycore_faulthandler.h`.

File: Python/traceback.c [hunk 2]
```diff
@@ -55,7 +55,9 @@
 
 #define MAX_STRING_LENGTH 500
 #define MAX_FRAME_DEPTH 100
-#define MAX_NTHREADS 100
+/* The historical default thread-dump cap is declared as
+   _Py_TRACEBACK_MAX_NTHREADS in pycore_traceback.h so callers of
+   _Py_DumpTracebackThreads can reference it directly. */
```
Comment (vstinner) [inline Python/traceback.c]: I don't think that this comment is useful. I suggest removing it.

File: Doc/library/faulthandler.rst [hunk 3]
```diff
@@ -31,7 +31,8 @@ tracebacks:
 * Each string is limited to 500 characters.
 * Only the filename, the function name and the line number are
   displayed. (no source code)
-* It is limited to 100 frames and 100 threads.
+* It is limited to 100 frames per thread, and by default to 100 threads
+  total in newest-first order (configurable via *max_threads*).
```
Comment (vstinner) [inline Doc/library/faulthandler.rst]:
```suggestion
* It is limited to 100 frames per thread, and 100 threads
  (configurable via *max_threads*).
```

File: Doc/library/faulthandler.rst [hunk 4]
```diff
@@ -55,16 +56,20 @@ at Python startup.
 Dumping the traceback
 ---------------------
 
-.. function:: dump_traceback(file=sys.stderr, all_threads=True)
+.. function:: dump_traceback(file=sys.stderr, all_threads=True, *, max_threads=100)
 
    Dump the tracebacks of all threads into *file*. If *all_threads* is
-   ``False``, dump only the current thread.
+   ``False``, dump only the current thread. *max_threads* caps the number
+   of threads dumped; a ``...`` marker is written if there are more.
```
Comment (vstinner) [inline Doc/library/faulthandler.rst]: > a ``...`` marker is written if there are more

That's an implementation detail, please don't document it (remove it from the doc). Same remark for all documentation of this PR.

File: Doc/library/faulthandler.rst [hunk 5]
```diff
@@ -55,16 +56,20 @@ at Python startup.
...
 
    .. seealso:: :func:`traceback.print_tb`, which can be used to print a traceback object.
 
    .. versionchanged:: 3.5
       Added support for passing file descriptor to this function.
 
+   .. versionchanged:: 3.15
```
Comment (vstinner) [inline Doc/library/faulthandler.rst]:
```suggestion
   .. versionchanged:: next
```

File: Doc/library/faulthandler.rst [hunk 6]
```diff
@@ -168,6 +174,9 @@ Dumping the tracebacks after a timeout
    .. versionchanged:: 3.7
       This function is now always available.
 
+   .. versionchanged:: 3.15
```
Comment (vstinner) [inline Doc/library/faulthandler.rst]:
```suggestion
   .. versionchanged:: next
```

File: Include/internal/pycore_faulthandler.h [hunk 7]
```diff
@@ -68,6 +68,8 @@ struct _faulthandler_runtime_state {
         int exit;
         char *header;
         size_t header_len;
+        /* Thread-count cap passed to _Py_DumpTracebackThreads. */
+        unsigned int max_nthreads;
```
Comment (vstinner) [inline Include/internal/pycore_faulthandler.h]: I would prefer to use "max_threads" name everywhere to be consistent:

```suggestion
        unsigned int max_threads;
```

File: Include/internal/pycore_faulthandler.h [hunk 8]
```diff
@@ -68,6 +68,8 @@ struct _faulthandler_runtime_state {
         int exit;
         char *header;
         size_t header_len;
+        /* Thread-count cap passed to _Py_DumpTracebackThreads. */
```
Comment (vstinner) [inline Include/internal/pycore_faulthandler.h]: I don't think that this comment is useful. I suggest removing it.

File: Include/internal/pycore_traceback.h [hunk 9]
```diff
@@ -58,10 +58,19 @@ extern void _Py_DumpTraceback(
 
    This function is signal safe. */
 
+/* The historical per-call cap on the number of threads dumped by
+   _Py_DumpTracebackThreads; surfaced as the public default for the
+   max_threads kwarg on faulthandler.dump_traceback{,_later}. */
+#define _Py_TRACEBACK_MAX_NTHREADS 100
```
Comment (vstinner) [inline Include/internal/pycore_traceback.h]: Having to pass _Py_TRACEBACK_MAX_NTHREADS to get the default behavior is not convenient. I would prefer passing 0 to *max_threads*, and modify _Py_DumpTracebackThreads() to use 100 if it gets 0.

File: Lib/test/test_faulthandler.py [hunk 10]
```diff
@@ -719,6 +719,62 @@ def test_dump_traceback_later_fd(self):
...
+        # spawn_python merges stderr into stdout by default.
+        with support.SuppressCrashReport():
+            process = script_helper.spawn_python('-c', code)
+            with process:
+                output, _ = process.communicate()
+                process.wait()
+        # Truncation marker is written when the cap is hit.
+        self.assertIn(b"...\n", output)
+        # Cap of 3 means at most 3 thread headers in the dump.
+        self.assertLessEqual(output.count(b"Thread 0x"), 3)
```
Comment (vstinner) [inline Lib/test/test_faulthandler.py]: Why would it dump less than 3 threads? I would prefer to check for exactly 3 threads.

File: Lib/test/test_faulthandler.py [hunk 11]
```diff
@@ -719,6 +719,62 @@ def test_dump_traceback_later_fd(self):
...
+
+    def test_dump_traceback_max_threads_default(self):
```
Comment (vstinner) [inline Lib/test/test_faulthandler.py]: I don't think that it's useful to check the default *max_threads* value. I suggest removing the test.

File: Misc/NEWS.d/next/Library/2026-04-28-16-30-48.gh-issue-149085.5aNgBD.rst [hunk 12]
```diff
@@ -0,0 +1,7 @@
+Add a *max_threads* keyword argument to :func:`faulthandler.dump_traceback`
+and :func:`faulthandler.dump_traceback_later`, raising the per-call cap on
+the number of threads dumped (previously a hard-coded ``MAX_NTHREADS = 100``
+in :file:`Python/traceback.c`). Useful for server processes with many
+worker or gRPC threads, where dump order (newest-thread-first) means the
+historical 100-thread cap silently elided the main thread. The default of
+``100`` preserves existing behavior.
```
Comment (vstinner) [inline Misc/NEWS.d/next/Library/2026-04-28-16-30-48.gh-issue-149085.5aNgBD.rst]:
```suggestion
Add a *max_threads* keyword argument to :func:`faulthandler.dump_traceback`
and :func:`faulthandler.dump_traceback_later`.
```

I don't think that it's needed to mention gRPC usecase here, having it described in the issue is enough. Also, it's not needed to mention that the default is 100 since it's not changed.

File: Python/traceback.c [hunk 13]
```diff
@@ -1265,7 +1267,8 @@ write_thread_id(int fd, PyThreadState *tstate, int is_current)
    handlers if signals were received. */
 const char* _Py_NO_SANITIZE_THREAD
 _Py_DumpTracebackThreads(int fd, PyInterpreterState *interp,
-                         PyThreadState *current_tstate)
+                         PyThreadState *current_tstate,
+                         unsigned int max_nthreads)
```
Comment (vstinner) [inline Python/traceback.c]: I suggest renaming the parameter to *max_threads* for consistency.

File: Lib/test/test_faulthandler.py [hunk 14]
```diff
@@ -719,6 +719,62 @@ def test_dump_traceback_later_fd(self):
...
+                    t.join()
+        """).strip()
+        # spawn_python merges stderr into stdout by default.
+        with support.SuppressCrashReport():
+            process = script_helper.spawn_python('-c', code)
+            with process:
+                output, _ = process.communicate()
+                process.wait()
+        # Truncation marker is written when the cap is hit.
+        self.assertIn(b"...\n", output)
```
Comment (vstinner) [inline Lib/test/test_faulthandler.py]: Check the whole line:

```suggestion
        self.assertIn(b"\n...\n", output)
```

File: Lib/test/test_faulthandler.py [hunk 15]
```diff
@@ -719,6 +719,62 @@ def test_dump_traceback_later_fd(self):
...
+            ready.wait()
+            try:
+                faulthandler.dump_traceback(file=sys.stderr, max_threads=CAP)
+            finally:
+                stop.set()
+                for t in threads:
+                    t.join()
+        """).strip()
+        # spawn_python merges stderr into stdout by default.
+        with support.SuppressCrashReport():
```
Comment (vstinner) [inline Lib/test/test_faulthandler.py]: This process is not supposed to fail. If it fails, I would prefer to use the default crash reporter (such as dumping a coredump file).

File: Lib/test/test_faulthandler.py [hunk 16]
```diff
@@ -719,6 +719,62 @@ def test_dump_traceback_later_fd(self):
...
+            process = script_helper.spawn_python('-c', code)
+            with process:
+                output, _ = process.communicate()
+                process.wait()
```
Comment (vstinner) [inline Lib/test/test_faulthandler.py]: assert_python_ok() can be used instead (to make the code shorter):

```suggestion
        proc = script_helper.assert_python_ok('-c', code)
        output = proc.err
```

**Review by vstinner — COMMENTED** [review]
I would prefer to also add *max_threads* parameter to enable().

**Comment by efroemling** [comment]
Thanks for the feedback.
I took a pass and tried to address everything (added `max_threads` to `faulthandler.enable()`, scaled back excessive comments, removed `_Py_TRACEBACK_MAX_THREADS` in favor of 0 for historical default, etc.).
Please holler if I missed anything or you notice anything else I can clean up or improve.

File: Modules/faulthandler.c [hunk 17]
```diff
@@ -945,7 +962,7 @@ faulthandler_user(int signum)
     if (!user->enabled)
         return;
 
-    faulthandler_dump_traceback(user->fd, user->all_threads, user->interp);
+    faulthandler_dump_traceback(user->fd, user->all_threads, user->interp, 0);
```
Comment (vstinner) [inline Modules/faulthandler.c]: Please modify faulthandler.register() to add a *max_threads* parameter.

**Review by vstinner — COMMENTED** [review]
Can you replace `unsigned int max_threads` with `Py_ssize_t max_threads`? Replace also `unsigned int nthreads` with `Py_ssize_t nthreads` in `_Py_DumpTracebackThreads()`.

**Comment by vstinner** [comment]
> I took a pass and tried to address everything (added max_threads to faulthandler.enable(), scaled back excessive comments, removed _Py_TRACEBACK_MAX_THREADS in favor of 0 for historical default, etc.).

Thanks for this big update!

**Review by ZeroIntensity — COMMENTED** [review]
Please also add an entry to ["What's New in Python 3.15"](https://github.com/python/cpython/blob/main/Doc/whatsnew/3.15.rst).

**Comment by efroemling** [comment]
Ok I added the whats-new entry and switched the `max_size` args to `Py_ssize_t`. 👍

**Comment by vstinner** [comment]
Can you also modify `faulthandler.register()` to add a *max_threads* parameter?

**Comment by efroemling** [comment]
Ok `faulthandler.register()` now has `max_threads` too. (and added an associated test). Holler if anything looks off there.

File: Lib/test/test_faulthandler.py [hunk 18]
```diff
@@ -825,6 +895,41 @@ def test_register_threads(self):
...
+            def worker():
+                ready.wait()
+                stop.wait()
+
+            for _ in range(NTHREADS):
+                threading.Thread(target=worker, daemon=True).start()
+            ready.wait()
+            faulthandler.register(signal.SIGUSR1, all_threads=True,
+                                  max_threads=CAP)
+            os.kill(os.getpid(), signal.SIGUSR1)
```
Comment (vstinner) [inline Lib/test/test_faulthandler.py]: To raise the signal, you can use:

```suggestion
            signal.raise_signal(signal.SIGUSR1)
```

Can you use test_dump_traceback_max_threads() code to cleanup threads?

**Comment by efroemling** [comment]
Ok; switched to `raise_signal()` and now doing `test_dump_traceback_max_threads()` style cleanup

**Review by vstinner — APPROVED** [review]
LGTM.

**Comment by vstinner** [comment]
@ZeroIntensity: Do you want to double check the change?

It would be good to merge this change before next Tuesday to have it in Python 3.15 beta1.

**Review by ZeroIntensity — APPROVED** [review]
LGTM as well.

**Comment by ZeroIntensity** [comment]
Thanks for contributing :)
