### PR TITLE
GH-138378: Move globals-to-consts pass into main optimizer pass

### LINKED ISSUE #136154: JIT global-to-constant promotion doesn't properly validate the globals dictionary at runtime
# Bug report

This code raises a `NameError` with the JIT disabled, and succeeds with the JIT enabled:

```py
import types

GLOBAL = 42

def make_f():
    def f():
        return GLOBAL
    return f

make_f_with_bad_globals = types.FunctionType(make_f.__code__, {})

def jitted(funcs):
    for func in funcs:
        func()

def main():
    # Make a "good" f:
    f = make_f()
    # Compile jitted for the "good" f:
    jitted([f] * 4096)
    # This "bad" f has different globals, but the *same* code/function versions:
    f_with_bad_globals = make_f_with_bad_globals()
    # A "good" f to enter the JIT code, and a "bad" f to trigger the bug:
    jitted([f, f_with_bad_globals])

main()
```

We're relying on the function version to guarantee the correct globals. Functions that are created from the same code object share the same function version, but *don't* necessarily share the same globals.

The fix is probably to insert runtime checks for the identity of the globals dictionary (instead of the function version) in `remove_globals`. An identity check is safe, since if the original globals dict is deallocated then the trace will be invalidated anyways.

### PR DESCRIPTION
**Pull request by markshannon**
This also fixes #136154.

* Issue: gh-138378

### CODE REVIEW

File: Include/internal/pycore_optimizer.h [hunk 1]
```diff
@@ -276,6 +276,10 @@ struct _Py_UOpsAbstractFrame {
     // Max stacklen
     int stack_len;
     int locals_len;
+    uint32_t globals_checked_version;
```
Comment (Fidget-Spinner) [inline Include/internal/pycore_optimizer.h]: For consistency, this should be placed after the last few fields in the current struct and they should be commented. E.g. `// globals to constant promotion`.

File: Python/optimizer_bytecodes.c [hunk 2]
```diff
@@ -1238,6 +1230,98 @@ dummy_func(void) {
...
+                if (ctx->frame->globals_checked_version == version) {
+                    REPLACE_OP(this_instr, _NOP, 0, 0);
+                }
+            }
+        }
+        ctx->frame->globals_checked_version = version;
+    }
+
+    op(_LOAD_GLOBAL_BUILTINS, (version/1, index/1 -- res))
+    {
```
Comment (Fidget-Spinner) [inline Python/optimizer_bytecodes.c]:
```suggestion
    op(_LOAD_GLOBAL_BUILTINS, (version/1, index/1 -- res)) {
```

File: Python/optimizer_bytecodes.c [hunk 3]
```diff
@@ -1238,6 +1230,98 @@ dummy_func(void) {
...
+            if (!ctx->frame->builtins_watched) {
+                PyDict_Watch(BUILTINS_WATCHER_ID, builtins);
+                ctx->frame->builtins_watched = true;
+            }
+            if (ctx->frame->globals_checked_version != 0 && ctx->frame->globals_watched) {
+                cnst = convert_global_to_const(this_instr, builtins, false);
+            }
+        }
+        if (cnst == NULL) {
+            res = sym_new_unknown(ctx);
```
Comment (Fidget-Spinner) [inline Python/optimizer_bytecodes.c]: Isn't this guaranteed to not be NULL at least?
```suggestion
            res = sym_new_non_null(ctx);
```

File: Python/optimizer_bytecodes.c [hunk 4]
```diff
@@ -1238,6 +1230,98 @@ dummy_func(void) {
...
+                    REPLACE_OP(this_instr-1, _GUARD_GLOBALS_VERSION, 0, version);
+                    ctx->frame->globals_checked_version = version;
+                }
+                if (ctx->frame->globals_checked_version == version) {
+                    cnst = convert_global_to_const(this_instr, globals, false);
+                }
+            }
+        }
+        if (cnst == NULL) {
+            res = sym_new_unknown(ctx);
```
Comment (Fidget-Spinner) [inline Python/optimizer_bytecodes.c]: Ditto about non-null

**Review by Fidget-Spinner — COMMENTED** [review]
Very nice improvement!

File: Include/internal/pycore_optimizer.h (hunk 1 above)
Comment (markshannon) [reply Include/internal/pycore_optimizer.h]: Fields should be in either ascending or descending order, for best packing, so I can't just add the fields at the end. 
I'll add the comment.

**Review by Fidget-Spinner — APPROVED** [review]
