### PR TITLE
gh-134637: make PyCFuncPtr_call lock free in ctypes

### LINKED ISSUE #134637: 3.14t vs 3.13t cuts IOCP performance in half
# Bug report

### Bug description:

This is about 3.14.0bl vs 3.13.1, free threaded in both cases.
Microsoft Windows [Version 10.0.19045.4529]

I run and maintain an IOCP server in python 3.13.1t.
There are no 3rd party libraries being used.

The Problem: Using the exact same code, running 3.14t vs 3.13t cuts the throughput in half.

I've made a badly written, working benchmark, extracted/simplified from my IOCP server.

Server:
```python
from ctypes import windll,create_string_buffer,c_void_p,c_ulong,c_ulonglong,Structure,byref,cast,addressof,POINTER,c_char
from ctypes.wintypes import DWORD,HANDLE

kernel32 = windll.kernel32

CreateNamedPipeW = kernel32.CreateNamedPipeW
CreateIOCompletionPort = kernel32.CreateIoCompletionPort
ConnectNamedPipe = kernel32.ConnectNamedPipe
GetQueuedCompletionStatusEx = kernel32.GetQueuedCompletionStatusEx;
ReadFile = kernel32.ReadFile

GLE = kernel32.GetLastError

class OVERLAPPED(Structure):
	_fields_ = (("0", c_void_p),("1", c_void_p),("2", DWORD),("3", DWORD),("4", c_void_p),
				("5", c_void_p),("6",c_void_p),("7",c_void_p),("8",c_void_p))


Overlapped = (OVERLAPPED*10)()
__Overlapped = byref(Overlapped)

IOCP = CreateIOCompletionPort(HANDLE(-1),None,0,4)

flag1 = 1 | 1073741824; flag2 = 4 | 2 | 0 | 8
Pipe = CreateNamedPipeW("\\\\.\\pipe\\IOCPBenchMark",flag1,flag2,255,32,0,0, None)

if not CreateIOCompletionPort(Pipe,IOCP,1,0): print("ERROR!")

ReadBuffer = create_string_buffer(1024)
__ReadBuffer = byref(ReadBuffer)

OverlapEntries = create_string_buffer(32*128)
ove = byref(OverlapEntries); 

Completed = c_ulong(0)
__Completed = byref(Completed)

def __IOCPThread():
	while True:
		while not GetQueuedCompletionStatusEx(IOCP, ove, 255, __Completed, 0, False): continue
		ReadFile(Pipe, __ReadBuffer,32,None,__Overlapped)


from threading import Thread

Threads = []
for t in range(4): Threads.append(Thread(target=__IOCPThread))


success = ConnectNamedPipe(Pipe, __Overlapped)
if not success:
	if GLE() != 997:
		print("ERROR 2")


while not GetQueuedCompletionStatusEx(IOCP, ove, 255, __Completed, 1, False): continue
print("Connected.")

ReadFile(Pipe, __ReadBuffer,32,None,__Overlapped)
for t in Threads: t.start()


from time import sleep
while True:
	sleep(1)
```

Client:
```python
from ctypes import windll,c_char_p,byref
from ctypes.wintypes import DWORD

from time import perf_counter as pfc

kernel32 = windll.kernel32

CreateFileW = kernel32.CreateFileW
WriteFile = kernel32.WriteFile
GLE = kernel32.GetLastError

written = DWORD()
__written = byref(written)


print(GLE())

GENERIC_WRITE = 1073741824
Pipe = kernel32.CreateFileW("\\\\.\\pipe\\IOCPBenchMark",GENERIC_WRITE,0,None,3,0,None)

if GLE() == 0: print("Connected.")

test = b"test"

t = pfc()+1
while True:

	for Count in range(1000000):

		if not WriteFile(Pipe, test, 4,__written, None):
			print("ERROR ",GLE())

		if not WriteFile(Pipe, test, 4,__written, None):
			print("ERROR ",GLE())

		if not WriteFile(Pipe, test, 4,__written, None):
			print("ERROR ",GLE())

		if not WriteFile(Pipe, test, 4,__written, None):
			print("ERROR ",GLE())

		if pfc() >= t:
			t = pfc()+1
			print(Count*4)
			break

```

The server uses 4 threads. if you don't see any output, try reducing the amount.
When I use 8 threads (on my 8 core machine), I don't get any output. d'uh.
No, SMT-Threads don't count for anything here.

Each script runs in its own cmd.exe window.
Please be aware that you'll have to kill the server-process manually.

I wanted to add a call to "taskkill/F /IM:pytho*",
but then realized I might cause someone big trouble with that.

`>python3.13t server.py`:
Client output:
205536
207128
206764
206504
204768

`>python3.14t server.py`:
Client output:
107468
105516
106032
107492
108472

Perplexity suggested I should post this here,
because this is a use-case you people might be interested in.

Thank you.

### CPython versions tested on:

3.14

### Operating systems tested on:

Windows

### Linked PRs
* gh-134702
* gh-134742

### PR DESCRIPTION
**Pull request by kumaraditya303**
This fixes the performance regression mentioned on the issue, it avoids acquiring the critical section in the general case of no contention.

* Issue: gh-134637

### CODE REVIEW

File: Modules/_ctypes/_ctypes.c [hunk 1]
```diff
@@ -4575,24 +4620,44 @@ PyCFuncPtr_call_lock_held(PyObject *op, PyObject *inargs, PyObject *kwds)
         CDataObject *this;
         this = (CDataObject *)PyTuple_GetItem(inargs, 0); /* borrowed ref! */
         if (!this) {
+            Py_XDECREF(restype);
+            Py_XDECREF(converters);
+            Py_XDECREF(checker);
+            Py_XDECREF(argtypes);
+            Py_XDECREF(errcheck);
```
Comment (encukou) [inline Modules/_ctypes/_ctypes.c]: Please switch to `goto error` or `goto finally` at this point.

**Review by encukou — COMMENTED** [review]
This looks fine for 3.14 backport, but... ideally `ctypes` should, where possible, look like a “normal” C extension that a third-party could write.
I'm worried about it reaching more and more into rather obscure internal APIs.

File: Modules/_ctypes/_ctypes.c (hunk 1 above)
Comment (kumaraditya303) [reply Modules/_ctypes/_ctypes.c]: I was avoiding that to keep the diff small for backporting, I have added it now.

File: Modules/_ctypes/_ctypes.c [hunk 2]
```diff
@@ -3610,6 +3610,45 @@ generic_pycdata_new(ctypes_state *st,
   PyCFuncPtr_Type
 */
 
+static inline void
+atomic_xsetref(PyObject **field, PyObject *value)
+{
+#ifdef Py_GIL_DISABLED
+    PyObject *old = *field;
+    _Py_atomic_store_ptr(field, value);
```
Comment (ZeroIntensity) [inline Modules/_ctypes/_ctypes.c:3618]: I think sequential consistency is too strong. We can use `release` ordering here, can't we?

File: Modules/_ctypes/_ctypes.c [hunk 3]
```diff
@@ -3610,6 +3610,45 @@ generic_pycdata_new(ctypes_state *st,
...
+    This function atomically loads the reference from *field, and
+    tries to get a new reference to it. If the incref fails,
+    it acquires critical section of obj and returns a new reference to the *field.
+    In the general case, this avoids contention on acquiring the critical section.
+*/
+static inline PyObject *
+atomic_xgetref(PyObject *obj, PyObject **field)
+{
+#ifdef Py_GIL_DISABLED
+    PyObject *value = _Py_atomic_load_ptr(field);
```
Comment (ZeroIntensity) [inline Modules/_ctypes/_ctypes.c:3634]: Same here.

File: Modules/_ctypes/_ctypes.c (hunk 2 above)
Comment (kumaraditya303) [reply Modules/_ctypes/_ctypes.c:3618]: It doesn't matter much here and it is better to keep same seq consistency for both loads and stores (check _Py_TryIncrefCompare)

**Comment by kumaraditya303** [comment]
```console
❯ ./python -m test -R 3:3 test_ctypes
Using random seed: 4211406380
0:00:00 load avg: 0.24 Run 1 test sequentially in a single process
0:00:00 load avg: 0.24 [1/1] test_ctypes
beginning 6 repetitions. Showing number of leaks (. for 0 or less, X for 10 or more)
123:456
XX. .1.
test_ctypes leaked [0, 1, 0] memory blocks, sum=1 (this is fine)
0:00:15 load avg: 0.41 [1/1] test_ctypes passed

== Tests result: SUCCESS ==

1 test OK.

Total duration: 15.4 sec
Total tests: run=600 skipped=34
Total test files: run=1/1
Result: SUCCESS
```

No refleaks

**Comment by kumaraditya303** [comment]
Performance on this PR release build without pgo:
```console
 ./python.bat client.py 
Running Release|x64 interpreter...
0
Connected.
207440
203568
203348
200588
204112
```

File: Misc/NEWS.d/next/Library/2025-05-26-17-06-40.gh-issue-134637.9-3zRL.rst [hunk 4]
```diff
@@ -0,0 +1 @@
+Fix performance regression in calling ``ctypes._CFuncPtr`` in free-threading.
```
Comment (ZeroIntensity) [inline Misc/NEWS.d/next/Library/2025-05-26-17-06-40.gh-issue-134637.9-3zRL.rst]: Up to you, but I like to keep internal details away from changelog readers:
```suggestion
Fix performance regression in calling a :mod:`ctypes` function pointer in :term:`free threading`.
```

**Review by ZeroIntensity — APPROVED** [review]
LGTM. Let's run the FT buildbots just in case.
