### PR TITLE
gh-91098: Use Argument Clinic for Object/classobject.c to fix docstrings

### LINKED ISSUE #91098: Convert Object/classobject.c to Argument Clinic
BPO | [46942](https://bugs.python.org/issue46942)
--- | :---
Nosy | @arhadthedev
PRs | <li>python/cpython#31711</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-07.08:50:35.484>
labels = ['interpreter-core', 'type-feature', '3.11']
title = 'Convert Object/classobject.c to Argument Clinic'
updated_at = <Date 2022-03-07.08:50:47.992>
user = 'https://github.com/arhadthedev'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-07.08:50:47.992>
actor = 'arhadthedev'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2022-03-07.08:50:35.484>
creator = 'arhadthedev'
dependencies = []
files = []
hgrepos = []
issue_num = 46942
keywords = ['patch']
message_count = 1.0
messages = ['414643']
nosy_count = 1.0
nosy_names = ['arhadthedev']
pr_nums = ['31711']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue46942'
versions = ['Python 3.11']
```

</p></details>

### PR DESCRIPTION
**Pull request by arhadthedev**
Closes GH-91098.

### CODE REVIEW

File: Objects/classobject.c [hunk 1]
```diff
@@ -530,69 +525,47 @@ instancemethod_hash(PyObject *self)
...
-    instancemethod_dealloc,                     /* tp_dealloc */
-    0,                                          /* tp_vectorcall_offset */
-    0,                                          /* tp_getattr */
-    0,                                          /* tp_setattr */
-    0,                                          /* tp_as_async */
-    (reprfunc)instancemethod_repr,              /* tp_repr */
-    0,                                          /* tp_as_number */
-    0,                                          /* tp_as_sequence */
-    0,                                          /* tp_as_mapping */
-    0, /*(hashfunc)instancemethod_hash,         tp_hash  */
```
Comment (arhadthedev) [inline Objects/classobject.c]: @vstinner Should `instancemethod_hash` be kept or removed? It has been commented out [since its introduction](https://github.com/python/cpython/commit/a3534a6ff5602ea848b1d27f4f9d9d7913cbe31b#diff-d36823aa86f63074d7ae49b390602ea3840cabe4b54484c42aab8ea6b04a1479R595) on 11 Dec 2007 .

Comment (vstinner) [reply Objects/classobject.c]: I would prefer to have a separated PR to remove it.

**Comment by arhadthedev** [comment]
Accidentally autoclosed by deleting a wrong remote branch.

File: Misc/NEWS.d/next/Core and Builtins/2022-03-07-11-51-51.bpo-46942.57obVi.rst [hunk 2]
```diff
@@ -0,0 +1,4 @@
+:func:`idlelib.calltip.get_argspec` now correctly reports that
```
Comment (JelleZijlstra) [inline Misc/NEWS.d/next/Core and Builtins/2022-03-07-11-51-51.bpo-46942.57obVi.rst]: This is an odd way to put it. It's not idlelib that changed, but classobject.c. Can we just say something like "Use Argument Clinic for the types.MethodType constructor"?

File: Objects/classobject.c [hunk 3]
```diff
@@ -516,67 +511,42 @@ instancemethod_repr(PyObject *self)
...
 }
 
-PyDoc_STRVAR(instancemethod_doc,
-"instancemethod(function)\n\
-\n\
-Bind a function to a class.");
+/*[clinic input]
+@classmethod
+instancemethod.__new__
+    function: object
```
Comment (JelleZijlstra) [inline Objects/classobject.c:517]: Let's keep this positional-only.

File: Objects/classobject.c [hunk 4]
```diff
@@ -193,34 +203,32 @@ method_getattro(PyObject *obj, PyObject *name)
     return PyObject_GetAttr(im->im_func, name);
 }
 
-PyDoc_STRVAR(method_doc,
-"method(function, instance)\n\
-\n\
-Create a bound instance method object.");
+/*[clinic input]
+@classmethod
+method.__new__
```
Comment (JelleZijlstra) [inline Objects/classobject.c]:
```suggestion
method.__new__ as method_new
```
A bit weird to have "method" as a function name in C. Same for instancemethod below.

**Review by JelleZijlstra — COMMENTED** [review]
Thanks, happy to see more Argument Clinic in the code!

**Comment by arhadthedev** [comment]
@JelleZijlstra Thank you for the review, addressed.
