### PR TITLE
gh-120291: Fix a bashism in python-config.sh.in

### LINKED ISSUE #120291: [3.13] shell version of `python-config` started using bashisms
# Bug report

### Bug description:

Since de2a73dc4649b110351fce789de0abb14c460b97 `python-config.sh.in` is using bashisms but declaring `#!/bin/sh` as the shell. As a result, it now throws errors on systems using non-bash shells:

```
$ python3.13-config 
/usr/bin/python3.13-config: 8: [[: not found
Usage: /usr/bin/python3.13-config --prefix|--exec-prefix|--includes|--libs|--cflags|--ldflags|--extension-suffix|--help|--abiflags|--configdir|--embed
```

FWICS, there's no reason to use `[[ ... ]]` over plain shell `[ ... ]` there.

CC @kiendang 

### CPython versions tested on:

3.13, CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-120292
* gh-120341

### PR DESCRIPTION
**Pull request by mgorny**
Replace the use of bash-specific `[[ ... ]]` with POSIX-compliant `[ ... ]` to make the `python-config` shell script work with non-bash shells again.

Fixes #120291

* Issue: gh-120291

### CODE REVIEW

File: Misc/NEWS.d/next/Build/2024-06-09-15-54-22.gh-issue-120291.IpfHzE.rst [hunk 1]
```diff
@@ -0,0 +1,2 @@
+Fix the shell version of ``python-config`` script to work with non-bash
+shells.
```
Comment (picnixz) [inline Misc/NEWS.d/next/Build/2024-06-09-15-54-22.gh-issue-120291.IpfHzE.rst]:
```suggestion
Make the ``python-config`` shell script compatible with non-bash shells.
```

Strictly speaking, POSIX does not require the `local` keyword to be valid in scoped functions. So, `exit_with_usage` is still not fully POSIX compliant. If you want a purely POSIX compliant script, you should use sub-shells (but that's an overkill and most, if not all, implementations of POSIX support `local`).

**Review by picnixz — COMMENTED** [review]
Can you also check that the script is in sync with `python-config.in` as asked?

File: Misc/NEWS.d/next/Build/2024-06-09-15-54-22.gh-issue-120291.IpfHzE.rst (hunk 1 above)
Comment (mgorny) [reply Misc/NEWS.d/next/Build/2024-06-09-15-54-22.gh-issue-120291.IpfHzE.rst]: Updated, thanks. Also split the `local` while at it, that should get us the best of both worlds. Even if `local` isn't supported by the shell, the assignment will still work.

Comment (eli-schwartz) [reply Misc/NEWS.d/next/Build/2024-06-09-15-54-22.gh-issue-120291.IpfHzE.rst]: It would also print a pointless error message to the console.

I don't actually understand the point of using `local` here at all though, since it happens immediately before exiting the script entirely. Why does it need to set up a separate variable context to avoid clobbering global shell variables?

Comment (picnixz) [reply Misc/NEWS.d/next/Build/2024-06-09-15-54-22.gh-issue-120291.IpfHzE.rst]: @mgorny Actually, I just understood the "Keep this script in sync with python-config.in". There's a copy of that script in `Misc` so you should also fix that part.

@eli-schwartz You're right. There is also the RESULT variable which appears to be global and AFAICT, the latter is not used outside that script (nor is there any pollution from other scripts or the Makefile but I may be wrong).

Comment (mgorny) [reply Misc/NEWS.d/next/Build/2024-06-09-15-54-22.gh-issue-120291.IpfHzE.rst]: > @mgorny Actually, I just understood the "Keep this script in sync with python-config.in". There's a copy of that script in `Misc` so you should also fix that part.

This in `Misc`. There are two scripts: `python-config.sh.in` that's written in shell and I'm fixing that one, and `python-config.in` that's written in Python and isn't affected.

**Review by sobolevn — APPROVED** [review]

**Comment by sobolevn** [comment]
Thank you! Backport will be merged as soon as the CI will pass.

I wonder if we can use `shellcheck` for that in our CI. Since most people do make this mistake of mixing shell dialects quite common.

**Comment by mgorny** [comment]
Thanks!
