### PR TITLE
gh-134144: Fix use-after-free in zapthreads()

### LINKED ISSUE #134144: Cannot safely Py_EndInterpreter in 3.14b1
# Crash report

### What happened?

Stack trace:
```
#0  tstate_delete_common.constprop.0 (tstate=tstate@entry=0x555555666ca0, release_gil=0) at ../Python/pystate.c:1854
#1  0x00007ffff78cd341 in zapthreads (interp=0x7ffff74c8010) at ../Python/pystate.c:1915
#2  PyInterpreterState_Delete (interp=0x7ffff74c8010) at ../Python/pystate.c:1016
#3  0x00005555555552ef in main () at repro.c:16
```
(note the address passed to tstate_delete_common is definitely corrupt, and not the address of any PyThreadState created in this program)

This was triggered by creating a new PyThreeadState for the interpreter, switching to it, deleting an old thread state for the same interpreter, and then calling Py_EndInterpreter (on the new thread state).

repro.c:

```c
#include <Python.h>

int main()
{
        Py_Initialize();

        PyThreadState *orig = NULL;
        PyInterpreterConfig cfg =  _PyInterpreterConfig_INIT;
        Py_NewInterpreterFromConfig(&orig, &cfg);

        PyThreadState *temp = PyThreadState_New(orig->interp);
        PyThreadState_Swap(temp);
        PyThreadState_Clear(orig);
        PyThreadState_Delete(orig);
        Py_EndInterpreter(temp);

        Py_Finalize();
}
```

Compiled with `$ gcc -O1 -ggdb  repro.cpp -I/usr/include/python3.14 -lpython3.14`

### CPython versions tested on:

3.14

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.14.0b1 (main, May  8 2025, 08:57:13) [GCC 13.3.0]

### Linked PRs
* gh-134145
* gh-134182

### PR DESCRIPTION
**Pull request by b-pass**
Fixes #134144. This problem was introduced by #127077 which added `_Py_FOR_EACH_TSTATE_UNLOCKED`.

`_Py_FOR_EACH_TSTATE_UNLOCKED` reads the `tstate` at the end of each loop iteration to get the `next` value.  When the loop body frees the `tstate`, the result is always a use-after-free.  It doesn't always crash (seems rare, actually), I guess it just depends what the allocator does with those pages during the rest of the tstate deletion.

* Issue: gh-134144

### CODE REVIEW

**Review by ZeroIntensity — CHANGES_REQUESTED** [review]
I'm pretty sure we can drop `zapthreads` entirely, because right now the assumption is that the interpreter doesn't have any threads left. Let's hold off on this until we come to a decision on what the actual behavior should be for dangling threads.

**Review by ericsnowcurrently — APPROVED** [review]
LGTM

We just need a NEWS entry.

@ZeroIntensity, regarding gh-128640, I expect we'll do that too since it solves an additional problem.  However, this PR is a good idea regardless.

**Comment by ZeroIntensity** [comment]
We need a test case as well, but I'm more worried about the use-case as given in the issue. `zapthreads` will arbitrarily destroy a thread state (one created by `PyGILState_Ensure` in the repro), which is a recipe for crashes if the thread is still running.

**Comment by b-pass** [comment]
> We need a test as well, but I'm more worried about the use-case as given in the issue. `zapthreads` will arbitrarily destroy a thread state (one created by `PyGILState_Ensure` in the repro), which is a recipe for crashes if the thread is still running.

Sorry, the issue description isn't great.  The thread wasn't alive, but `Py_EndInterpreter` takes a `PyThreadState*` as the argument (not a `PyInterpreterState*`), so there must always been one on the interpreter. But the fact is this code ALWAYS does a use-after-free (even if there was only ever one thread state).  Here is some pseudo code of what is going on:

```c
for (PyThreadState *tstate = interp->threads.head; 
       tstate != NULL; 
       tstate = tstate->next)
{
   free(tstate);
}
```

**Comment by ZeroIntensity** [comment]
Right, I've noticed this before. In most cases, we get lucky because the initial thread is statically allocated on the interpreter state, so it doesn't actually cause UAF. It becomes an issue with something like `PyGILState_Ensure` because we have more than one thread state, but the problem is that's unsupported anyway.

**Comment by b-pass** [comment]
> It becomes an issue with something like `PyGILState_Ensure` because we have more than one thread state, but the problem is that's unsupported anyway.

It happens without the Ensure.  I've updated the linked issue with a complete program (without an Ensure).  So are you saying it's not supported to use a different `PyThreadState*` to end the interpreter than the one returned from its creation?

**Comment by ericsnowcurrently** [comment]
Yeah, a test would be nice.

File: Misc/NEWS.d/next/C_API/2025-05-17-14-41-21.gh-issue-134144.xVpZik.rst [hunk 1]
```diff
@@ -0,0 +1 @@
+Fix use-after-free during ``Py_EndInterpreter``.
```
Comment (ZeroIntensity) [inline Misc/NEWS.d/next/C_API/2025-05-17-14-41-21.gh-issue-134144.xVpZik.rst]:
```suggestion
Fix crash when calling :c:func:`Py_EndInterpreter` with a :term:`thread state` that isn't the initial thread for the interpreter.
```

**Review by kumaraditya303 — APPROVED** [review]

**Review by ZeroIntensity — APPROVED** [review]
Ok, let's go with this.
