### PR TITLE
gh-93217: fix some issues in man page and --help

### LINKED ISSUE #93217: Minor issues in python --help and man page
**Bug report**

The man page has a markup issue and is missing documentation for a couple -X options.
The output of --help has some lines that are too wide, or don’t follow the order of the man page.

These problems are taken out of GH-90300 so that there can be separate PRs and approval for their fixes.

### PR DESCRIPTION
**Pull request by merwok**

### CODE REVIEW

File: Python/initconfig.c [hunk 1]
```diff
@@ -100,9 +103,6 @@ static const char usage_3[] = "\
             when the interpreter displays tracebacks.\n\
          -X frozen_modules=[on|off]: whether or not frozen modules should be used.\n\
             The default is \"on\" (or \"off\" if you are running a local build).\n\
-\n\
---check-hash-based-pycs always|default|never:\n\
-    control how Python invalidates hash-based .pyc files\n\
```
Comment (ericsnowcurrently) [inline Python/initconfig.c]: I'm guessing this was kept separate because it is a long arg.  I don't have much opinion on whether it should be kept separate or not. 🙂

**Review by ericsnowcurrently — APPROVED** [review]
LGTM

You may want to get a second opinion about `--check-hash-based-pycs` though.

File: Python/initconfig.c (hunk 1 above)
Comment (merwok) [reply Python/initconfig.c]: I don’t mind it staying at the end (edit: but not after `-X options`), but then I would move the item in the man page to match!

Comment (ericsnowcurrently) [reply Python/initconfig.c]: Whatever works. :)

**Review by serhiy-storchaka — APPROVED** [review]

File: Python/initconfig.c [hunk 2]
```diff
@@ -38,7 +38,7 @@ Options and arguments (and corresponding environment variables):\n\
 -d     : turn on parser debugging output (for experts only, only works on\n\
          debug builds); also PYTHONDEBUG=x\n\
 -E     : ignore PYTHON* environment variables (such as PYTHONPATH)\n\
--h     : print this help message and exit (also --help)\n\
+-h     : print this help message and exit (also --help or -?)\n\
```
Comment (merwok) [inline Python/initconfig.c]:
```suggestion
-h     : print this help message and exit (also -? or --help)\n\
```

File: Python/initconfig.c (hunk 1 above)
Comment (merwok) [reply Python/initconfig.c]: I like the long options at the end of `--help` output, especially after the other PR that adds `--help-env`, `--help-xoptions` and `--help-all`).  I am also not reordering the man page: long options are on the last line of the synopsis, and in alphabetical order in the full doc, both of which are good.

File: Python/initconfig.c [hunk 3]
```diff
@@ -100,9 +100,8 @@ static const char usage_3[] = "\
             when the interpreter displays tracebacks.\n\
          -X frozen_modules=[on|off]: whether or not frozen modules should be used.\n\
             The default is \"on\" (or \"off\" if you are running a local build).\n\
-\n\
 --check-hash-based-pycs always|default|never:\n\
-    control how Python invalidates hash-based .pyc files\n\
+         control how Python invalidates hash-based .pyc files\n\
```
Comment (merwok) [inline Python/initconfig.c]:
```suggestion
    control how Python invalidates hash-based .pyc files\n\
```

**Comment by ericsnowcurrently** [comment]
Thanks for doing this, @merwok!
