### PR TITLE
gh-109889: fix compiler's redundant NOP detection to look past NOPs with no lineno when looking for the next instruction's lineno

### LINKED ISSUE #109889: flowgraph optimize_cfg Assertion for if-else-expression with if-else-expression as condition
# Bug report

### Bug description:

```python
a if (1 if b else c) else d
```

output (Python 3.12.0rc3+):
```python
python: Python/flowgraph.c:1598: optimize_cfg: Assertion `no_redundant_nops(g)' failed.
```
tested with the current 3.12 branch (538f505a3744ab1dd29861a859ab81ab65436144)

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-109899
* gh-109987
* gh-110048

### PR DESCRIPTION
**Pull request by iritkatriel**
Fixes #109889.

* Issue: gh-109889

### CODE REVIEW

File: Python/flowgraph.c [hunk 1]
```diff
@@ -1017,7 +1017,17 @@ remove_redundant_nops(basicblock *bb) {
                 }
                 /* or if last instruction in BB and next BB has same line number */
                 if (next) {
-                    if (lineno == next->b_instr[0].i_loc.lineno) {
+                    location next_loc = NO_LOCATION;
+                    for (int next_i=0; next_i < next->b_iused; next_i++) {
```
Comment (carljm) [inline Python/flowgraph.c:1021]: Initially, I thought it would be simpler to have the same behavior whether the next instruction is in the same basicblock or the next one; i.e. it would be clearer to just match the behavior above on lines 1004-1011. If the next instruction has no location, set it to this NOP's location and remove this NOP.

But then I realized that this is not actually equivalent in the case where we are crossing to the next basicblock, because the next basicblock may be a jump target, and that jump should not report the location from the current NOP. So we can't safely use the "copy location to next instr without location" approach across the basicblock boundary.

I'm not sure if this subtlety will be obvious to future readers/modifiers of this code?

We could safely use this new behavior (skip NOP without lineno that will be removed) in all cases, and restructure the code so that first we find the next "relevant" instruction (whether in current or next basic block), and then compare its location with the current NOP. I think this would be somewhat clearer and simpler, but it's up to you whether you agree / think it's worth it.

**Review by carljm — APPROVED** [review]

File: Python/flowgraph.c (hunk 1 above)
Comment (iritkatriel) [reply Python/flowgraph.c:1021]: > We could safely use this new behavior (skip NOP without lineno that will be removed) in all cases

I think we are a bit more aggressive when it's within the same basic block: we will hand the location on to any instruction that doesn't have a line number, not just a NOP.

**Comment by markshannon** [comment]
If I remove the assert statement and compile the test function, I see no `NOP`s:
```
Disassembly of <code object f at 0x7f1a9a409800, file "<stdin>", line 3>:
  3           0 RESUME                   0

  4           2 LOAD_GLOBAL              0 (b)
             12 TO_BOOL
             20 POP_JUMP_IF_FALSE        7 (to 38)
             24 LOAD_GLOBAL              4 (a)
             34 POP_TOP
             36 RETURN_CONST             0 (None)
        >>   38 LOAD_GLOBAL              2 (c)
             48 TO_BOOL
             56 POP_JUMP_IF_FALSE        7 (to 74)
             60 LOAD_GLOBAL              4 (a)
             70 POP_TOP
             72 RETURN_CONST             0 (None)
        >>   74 LOAD_GLOBAL              6 (d)
             84 POP_TOP
             86 RETURN_CONST             0 (None)
```

Is the change to the optimizer necessary, is there a case where it generates better output?
If not, then maybe just remove the assert?

**Comment by iritkatriel** [comment]
If that's the case then we should try to understand where the NOP gets removed. I wouldn't remove the assertion before I understand what's going on.

**Comment by iritkatriel** [comment]
I don't know why we do this in the optimizer and not in the assembler, after line numbers are propagated so it's easier to see what's redundant and what's not.
