### PR TITLE
GH-91079: Implement C stack limits using addresses, not counters.

### LINKED ISSUE #113655: Stack overflow collecting PGO data on Windows
# Bug report

### Bug description:

During a PGO build on Windows on main (471aa75), a test in `test_functools` fails with a stack overflow.

[Full log of build](https://gist.github.com/mdboom/86ba07fc8435f60f41f29c2d83c9f487)

```
PCbuild\build.bat --pgo
```

```
0:02:50 load avg: 0.35 [19/44] test_functools
Windows fatal exception: stack overflow

Thread 0x00002b38 (most recent call first):
  File "C:\actions-runner\_work\benchmarking\benchmarking\cpython\Lib\test\libregrtest\win_utils.py", line 43 in _update_load

Current thread 0x00000e3c (most recent call first):
  File "C:\actions-runner\_work\benchmarking\benchmarking\cpython\Lib\test\test_functools.py", line 1[875](https://github.com/faster-cpython/benchmarking/actions/runs/7367240496/job/20050307979#step:10:876) in fib
  File "C:\actions-runner\_work\benchmarking\benchmarking\cpython\Lib\test\test_functools.py", line 1875 in fib
  ...

C:\actions-runner\_work\benchmarking\benchmarking\cpython>"C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\msbuild.exe" "C:\actions-runner\_work\benchmarking\benchmarking\cpython\PCbuild\\pythoncore.vcxproj" /t:KillPython /nologo /v:m /clp:summary /p:Configuration=PGInstrument /p:Platform=x64 /p:KillPython=true 

  Killing any running python.exe instances...

C:\actions-runner\_work\benchmarking\benchmarking\cpython\PCbuild\pyproject.props(184,5): error : PGO run did not succeed (no python313!*.pgc files) and there is no data to merge [C:\actions-runner\_work\benchmarking\benchmarking\cpython\PCbuild\pythoncore.vcxproj]

Build FAILED.

```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Windows

### Linked PRs
* gh-113668
* gh-113701
* gh-113944
* gh-114148
* gh-114263
* gh-114896
* gh-115770
* gh-124264

### PR DESCRIPTION
**Pull request by markshannon**
Hopefully, this will also fix https://github.com/python/cpython/issues/113655.

* Issue: gh-91079

### CODE REVIEW

File: Include/cpython/pystate.h [hunk 1]
```diff
@@ -112,7 +112,10 @@ struct _ts {
     int py_recursion_remaining;
     int py_recursion_limit;
 
-    int c_recursion_remaining;
+    // These are addresses, but we need to convert to ints to avoid UB.
```
Comment (iritkatriel) [inline Include/cpython/pystate.h]: what is UB?

File: Lib/test/test_fstring.py [hunk 2]
```diff
@@ -628,23 +628,33 @@ def test_mismatched_parens(self):
...
+            try:
+                eval(txt)
+                self.fail("No exception raised")
+            except SyntaxError:
+                pass
+            except MemoryError:
+                pass
+            except Exception as ex:
+                self.fail(f"Should raise SyntaxError or MemoryError, not {type(ex)}")
+
```
Comment (iritkatriel) [inline Lib/test/test_fstring.py]:
```suggestion
        def raises_syntax_or_memory_error(txt):
            try:
                eval(txt)
            except (SyntaxError, MemoryError):
                pass
            except Exception as ex:
                self.fail(f"Should raise SyntaxError or MemoryError, not {type(ex)}")
            else:
                self.fail("No exception raised")
```

Comment (iritkatriel) [reply Lib/test/test_fstring.py]: Otherwise the exception raised from `self.fail` is handled in the `except Exception`.

File: Include/cpython/pystate.h (hunk 1 above)
Comment (JelleZijlstra) [reply Include/cpython/pystate.h]: undefined behavior

**Review by iritkatriel — APPROVED** [review]

**Review by encukou — CHANGES_REQUESTED** [review]
This adds new public API, which needs documentation.
It also removes public API; that needs deprecation or SC exception.

**Comment by zooba** [comment]
Love seeing this change! Thanks, Mark.

**Comment by markshannon** [comment]
> This adds new public API, which needs documentation. 

The public API is `Py_TRASHCAN_BEGIN`, `Py_ReachedRecursionLimit` is the necessary ABI addition to support it. 

> It also removes public API; that needs deprecation or SC exception.

What API?

**Comment by markshannon** [comment]
[Benchmarking](https://github.com/faster-cpython/benchmarking-public/tree/main/results/bm-20250217-3.14.0a5%2B-21366c3) shows a 0.0%-0.4% speedup on 64 bit platforms, and a 2% speedup on 32 bit windows, so it isn't slower.

**Comment by markshannon** [comment]
@encukou I've hidden the new function. I don't see any removals though, which API do you mean?

**Comment by markshannon** [comment]
We can add back `c_recursion_remaining` and `Py_C_RECURSION_LIMIT`, if you want.
The semantics have never been defined, so their values are meaningless to third party code and always have been.

**Comment by markshannon** [comment]
> There's also the newly added PyThreadState.c_stack_* members; are those meant to be private?

It's C code, there is no such thing as private.

**Comment by markshannon** [comment]
> Well, not documented, which just means people read the code to figure out what they mean.

I really don't think we should be wasting our time on supporting incompetent C/C++ programmers who can't use APIs.
Do we really want to start prefixing every field with `_DONT_USE_THIS_` just in case?

**Comment by markshannon** [comment]
I've just discovered `_PyThreadStateImpl` which is a hack to avoid this problem. I'll add stuff to that.

**Comment by markshannon** [comment]
@encukou `struct _ts` (the thread state) is unchanged and `Py_C_STACK_SIZE` restored.

File: Python/ceval.c [hunk 3]
```diff
@@ -304,36 +304,108 @@ Py_SetRecursionLimit(int new_limit)
...
+#endif
+}
+
 /* The function _Py_EnterRecursiveCallTstate() only calls _Py_CheckRecursiveCall()
    if the recursion_depth reaches recursion_limit. */
 int
 _Py_CheckRecursiveCall(PyThreadState *tstate, const char *where)
 {
-#ifdef USE_STACKCHECK
-    if (PyOS_CheckStack()) {
```
Comment (encukou) [inline Python/ceval.c:313]: Could you adjust the [`Py_EnterRecursiveCall` docs](https://docs.python.org/3/c-api/exceptions.html#c.Py_EnterRecursiveCall)?

File: Python/ceval.c [hunk 4]
```diff
@@ -304,36 +304,108 @@ Py_SetRecursionLimit(int new_limit)
...
+
+#if defined(__s390x__)
+#  define Py_C_STACK_SIZE 320000
+#elif defined(_WIN32)
+   // Don't define Py_C_STACK_SIZE, ask the O/S
+#elif defined(__ANDROID__)
+#  define Py_C_STACK_SIZE 1200000
+#elif defined(__sparc__)
+   // test_descr crashed on sparc64 with >7000 but let's keep a margin of error.
+#  define Py_C_STACK_SIZE 1600000
```
Comment (encukou) [inline Python/ceval.c]: The 7000 (and 8000 below) doesn't make much sense to me here.

File: Include/pythonrun.h [hunk 5]
```diff
@@ -21,12 +21,18 @@ PyAPI_FUNC(void) PyErr_DisplayException(PyObject *);
...
+ * stack consumption of PyEval_EvalDefault */
+#if defined(Py_DEBUG) && defined(WIN32)
+#  define PYOS_STACK_MARGIN 3072
+#else
+#  define PYOS_STACK_MARGIN 2048
+#endif
+#define PYOS_STACK_MARGIN_BYTES (PYOS_STACK_MARGIN * sizeof(void *))
 
-#if defined(WIN32) && !defined(MS_WIN64) && !defined(_M_ARM) && defined(_MSC_VER) && _MSC_VER >= 1300
+#if defined(WIN32)
```
Comment (encukou) [inline Include/pythonrun.h:35]: The *definition* of `PyOS_CheckStack` still uses `defined(_MSC_VER)`.
Looks like the `#if` there (and the MSVC-specific includes) can be removed.

Could you remove the MSVC reference from the `PyOS_CheckStack` docs?

File: Lib/test/list_tests.py [hunk 6]
```diff
@@ -59,10 +60,11 @@ def test_repr(self):
         self.assertEqual(str(a2), "[0, 1, 2, [...], 3]")
         self.assertEqual(repr(a2), "[0, 1, 2, [...], 3]")
 
+    @skip_wasi_stack_overflow()
     @skip_emscripten_stack_overflow()
     def test_repr_deep(self):
         a = self.type2test([])
-        for i in range(get_c_recursion_limit() + 1):
+        for i in range(100_000):
```
Comment (encukou) [inline Lib/test/list_tests.py:67]: Could you comment on where the 100_000, and similar magic constants below, came from?

Perhaps it would be best to reuse the name `exceeds_recursion_limit`, and set that to 100_000?

File: Lib/test/test_fstring.py [hunk 7]
```diff
@@ -628,23 +628,34 @@ def test_mismatched_parens(self):
                             r"does not match opening parenthesis '\('",
                             ["f'{a(4}'",
                             ])
-        self.assertRaises(SyntaxError, eval, "f'{" + "("*500 + "}'")
+        self.assertRaises(SyntaxError, eval, "f'{" + "("*20 + "}'")
```
Comment (encukou) [inline Lib/test/test_fstring.py:631]: This looks worrying. Did the limit for nested parentheses go down over an order of magnitude?

File: Lib/test/test_fstring.py [hunk 8]
```diff
@@ -628,23 +628,34 @@ def test_mismatched_parens(self):
...
+            try:
+                eval(txt)
+            except SyntaxError:
+                pass
+            except MemoryError:
+                pass
+            except Exception as ex:
+                self.fail(f"Should raise SyntaxError or MemoryError, not {type(ex)}")
+            else:
+                self.fail("No exception raised")
```
Comment (encukou) [inline Lib/test/test_fstring.py:645]: FWIW, you could use `with self.assertRaises((SyntaxError, MemoryError)):`

File: Python/pythonrun.c [hunk 9]
```diff
@@ -1538,24 +1538,21 @@ _Py_SourceAsString(PyObject *cmd, const char *funcname, const char *what, PyComp
 /*
  * Return non-zero when we run out of memory on the stack; zero otherwise.
  */
-int
-PyOS_CheckStack(void)
+int PyOS_CheckStack(void)
```
Comment (encukou) [inline Python/pythonrun.c]: Nitpick: please revert the style change
```suggestion
int
PyOS_CheckStack(void)
```

File: Python/pythonrun.c [hunk 10]
```diff
@@ -1538,24 +1538,21 @@ _Py_SourceAsString(PyObject *cmd, const char *funcname, const char *what, PyComp
...
-            EXCEPTION_CONTINUE_SEARCH) {
-        int errcode = _resetstkoflw();
-        if (errcode == 0)
-        {
-            Py_FatalError("Could not reset the stack!");
-        }
     }
-    return 1;
+    else {
+        return -1;
```
Comment (encukou) [inline Python/pythonrun.c]: Could this be 1 as before? Nowadays -1 is  usually used when an exception is set.

**Review by encukou — COMMENTED** [review]
Thank you!

> Do we really want to start prefixing every field with `_DONT_USE_THIS_` just in case?

No, an underscore is fine.
It's C, nothing is private at the language level, so we have a convention to mark the private/unstable stuff.

File: Lib/test/test_fstring.py (hunk 8 above)
Comment (markshannon) [reply Lib/test/test_fstring.py:645]: Oh, I don't know that was a thing. Thanks.

File: Lib/test/test_fstring.py (hunk 7 above)
Comment (markshannon) [reply Lib/test/test_fstring.py:631]: No. Previously, there was a counter and if it was exceeded a `SyntaxError` was raised, but it could crash if the stack overflowed before the limit was reached.
Now we raise a `SyntaxError` for unbalanced parens and a `RecursionError` for a (potential) stack overflow.
See the new tests added below (line 656)

**Comment by markshannon** [comment]
I have made the requested changes; please review again

**Review by encukou — APPROVED** [review]
Looks great now, thank you!

Would you be OK with me asking the SC to remove `Py_C_RECURSION_LIMIT` (and `c_recursion_remaining`) without deprecation? IMO it's the right thing to do here.

**Comment by markshannon** [comment]
> Would you be OK with me asking the SC to remove Py_C_RECURSION_LIMIT (and c_recursion_remaining) without deprecation? IMO it's the right thing to do here.

Sure, go ahead.

I was thinking that we should deprecate the whole of `struct _ts` (the thread state struct), but that probably needs a bit more discussion and it might be tricky to deprecate the struct, but still allow pointers to it in the API.

**Comment by brettcannon** [comment]
> Hi! The buildbot **wasm32-wasi 3.x** has failed when building commit [2498c22](https://github.com/python/cpython/commit/2498c22fa0a2b560491bc503fa676585c1a603d0).

@markshannon if you look at line 427 of  https://buildbot.python.org/#/builders/1046/builds/7562/steps/8/logs/stdio you will see that `test_super_deep` nows stack overflows.

**Comment by brettcannon** [comment]
I opened https://github.com/python/cpython/issues/130319 and assigned it to @markshannon .

**Comment by freakboy3742** [comment]
This also appears to have caused a failure on the iOS buildbot (masked because there was an existing failure with the colorise tests). However, [this build, triggered by the merge of this PR](https://buildbot.python.org/#/builders/1380/builds/2632) is the first one that has a failure in test_sys
```
======================================================================FAIL: test_getallocatedblocks (test.test_sys.SysModuleTest.test_getallocatedblocks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/buildbot/Library/Developer/XCTestDevices/8A66533E-162E-4905-BE21-60D36FEECA7F/data/Containers/Bundle/Application/AB83D4DE-36DA-4FB0-ADE1-C02F896A0910/iOSTestbed.app/python/lib/python3.14/test/test_sys.py", line 1104, in test_getallocatedblocks
    self.assertLess(a, sys.gettotalrefcount())
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 592882 not less than 517807
----------------------------------------------------------------------
```

**Comment by freakboy3742** [comment]
@markshannon Looking into the iOS failure - the comment before the test that is failing says:
```
            # While we could imagine a Python session where the number of
            # multiple buffer objects would exceed the sharing of references,
            # it is unlikely to happen in a normal test run.
```
What constitutes "normal" here? Is it possible a sequential, single process run (i.e., how iOS runs the test suite) might trigger this? I'm a bit out my depth here on diagnosing the cause of this one, so any pointers or suggestions for possible causes would be most welcome.

**Comment by markshannon** [comment]
`sys.gettotalrefcount()` is the total refcount per interpreter, but `sys.getallocatedblocks()` seems to be the total number of allocated blocks per process. If multiple interpreters were involved, I could see this test failing. Otherwise, it is puzzling.

This PR does no refcounting, allocation or deallocation.
My guess is that this PR is exposing an already existing miscounting of references when a recursion error occurs. Just a guess though.

**Comment by freakboy3742** [comment]
@markshannon I've opened #130384 to track the problem. Annoyingly, I can't reproduce this locally - the test passes reliably on my own iOS test setup.

**Comment by cceneag** [comment]
This pull request introduces significant changes to how recursion limits and stack checks are handled in the CPython codebase. The changes aim to simplify the recursion logic, remove platform-specific recursion limits, and improve stack safety. Key updates include replacing `c_recursion_remaining` with stack-based recursion checks, removing platform-specific recursion limits, and updating tests to reflect these changes.

### Recursion and Stack Handling Updates:
* Replaced `c_recursion_remaining` checks with stack-based recursion checks using new fields `c_stack_soft_limit` and `c_stack_hard_limit` in `_PyThreadStateImpl`. This improves stack safety and removes dependency on platform-specific recursion limits. (`Include/cpython/object.h`, `Include/internal/pycore_ceval.h`, `Include/internal/pycore_tstate.h`) [[1]](diffhunk://#diff-7c8590641fc0d835bdab9395a95dbacfb2abb056cec4217466c0f3ca6cca8270R490-R502) [[2]](diffhunk://#diff-7d65c03065cc654fe51b92748324dcc062d995c291981e586bba827af6aa7045R24-R28) [[3]](diffhunk://#diff-9e7eb7e81667528dfa3a35bbf32fe622d4721c3c71385ea0ea2250abbd15d545L196-L207) [[4]](diffhunk://#diff-9e7eb7e81667528dfa3a35bbf32fe622d4721c3c71385ea0ea2250abbd15d545L223-L239)

* Removed platform-specific recursion limits (`Py_C_RECURSION_LIMIT`) and associated code, consolidating recursion handling into a unified mechanism. (`Include/cpython/pystate.h`)

### Documentation Updates:
* Updated documentation to reflect the new stack-based recursion handling and removed references to `USE_STACKCHECK` and `Py_C_RECURSION_LIMIT`. (`Doc/c-api/exceptions.rst`)

### Test Updates:
* Refactored tests to align with the new recursion handling, replacing `get_c_recursion_limit` with constants or new logic. Tests now use a fixed recursion depth or `support.exceeds_recursion_limit()` where appropriate. (`Lib/test/test_call.py`, `Lib/test/test_compile.py`, `Lib/test/list_tests.py`, `Lib/test/mapping_tests.py`) [[1]](diffhunk://#diff-23fb8097524d5bfb5c43fd973f8ab6839b6fa1d7f283e4a82b4597dc5d81215fR63-R67) [[2]](diffhunk://#diff-24d6e2ce89859eaa162353695fa4264941d92dc86b20de1940befababdd53c9eL625-R629) [[3]](diffhunk://#diff-c69ceae0611c40012b4691e3536bf17efacdb5b51b8e155eec9a939108e42e43L715-R719)

* Added a new helper `skip_wasi_stack_overflow` to handle stack overflow tests on WASI. (`Lib/test/support/__init__.py`)

### Code Cleanup:
* Removed unused or legacy fields and functions, such as `recursion_depth` and `recursion_limit` in the symbol table and `get_c_recursion_limit` in test support. (`Include/internal/pycore_symtable.h`, `Lib/test/support/__init__.py`) [[1]](diffhunk://#diff-2a51d92a01c0bc62a48f185bdae9d50adebaffdc9bb4a1aff64f41edca712ddfL85-L86) [[2]](diffhunk://#diff-d925268c057737ba320c489ca302fd5125f14840d22e50cfe226bdb5bb88ba8dL2627-R2631)

These changes collectively improve the maintainability, safety, and consistency of recursion handling in the Python interpreter.
