### PR TITLE
gh-124285: Fix bug where bool() is called multiple times for the same part of a boolean expression

### LINKED ISSUE #124285: Behavior change for `foo and 1 or 2`: 3.12 newly converts `foo` to bool twice
# Bug report

### Bug description:

We noticed a behavior change between 3.11 and 3.12. The following code calls `Foo.__bool__` once in 3.11 and twice in 3.12. Consequently for this contrived example, the expression evaluates to different results in 3.11 and 3.12.

```python
class Foo:
    def __init__(self):
        self._a = True
    def __bool__(self):
        self._a = not self._a
        print(f"Foo.__bool__ -> {self._a}")
        return self._a

Foo() and "a string" or 42
```

In Python 3.11:

```
>>> Foo() and "a string" or 42
Foo.__bool__ -> False
42
```

In Python 3.12 (and 3.13.0b2):

```
>>> Foo() and "a string" or 42
Foo.__bool__ -> False
Foo.__bool__ -> True
<__main__.Foo object at 0x7f0ae554c1a0>
```

Is this change intentional?

Note that I'm not necessarily asking to change this. We should arguably change the code to `"a string" if Foo() else 42`, which evaluates the same in 3.11 and 3.12.

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-124394
* gh-124723

### PR DESCRIPTION
**Pull request by iritkatriel**
Fixes #124285.

* Issue: gh-124285

----
📚 Documentation preview 📚: https://cpython-previews--124394.org.readthedocs.build/

### CODE REVIEW

File: Python/bytecodes.c [hunk 1]
```diff
@@ -2571,6 +2571,16 @@ dummy_func(
             JUMP_BACKWARD_NO_INTERRUPT,
         };
 
+        pseudo(JUMP_IF_FALSE, (cond -- cond)) = {
+            JUMP_FORWARD,
+            JUMP_BACKWARD,
```
Comment (iritkatriel) [inline Python/bytecodes.c]: I'm cheating here, it's not the right definition. I need to think how to do this properly in the generator. I think we need a version of pseudo that takes a sequence of instructions rather than a set of options. I'll think about that tomorrow.

File: Tools/cases_generator/opcode_metadata_generator.py [hunk 2]
```diff
@@ -305,7 +305,8 @@ def generate_pseudo_targets(analysis: Analysis, out: CWriter) -> None:
     table_size = len(analysis.pseudos)
     max_targets = max(len(pseudo.targets) for pseudo in analysis.pseudos.values())
     out.emit("struct pseudo_targets {\n")
-    out.emit(f"uint8_t targets[{max_targets + 1}];\n")
+    out.emit(f"uint8_t as_sequence;\n")
+    out.emit(f"uint8_t targets[{1 + max_targets + 1}];\n")
```
Comment (markshannon) [inline Tools/cases_generator/opcode_metadata_generator.py]: Maybe add a comment here: why `1 + max_targets + 1` rather than `max_targets + 2`, and why that size?

**Review by markshannon — APPROVED** [review]
Very nice. 
One suggestion for a comment, otherwise lgtm.

File: Tools/cases_generator/opcode_metadata_generator.py (hunk 2 above)
Comment (iritkatriel) [reply Tools/cases_generator/opcode_metadata_generator.py]: Oops, we don't need to add the 1+ now. It's a relic from a previous iteration. Now we have the as_sequence field.

**Comment by JelleZijlstra** [comment]
@ncoghlan on the issue suggested we could do this in the AST optimizer without changing the eval loop. Is that approach worth considering? It would involve transforming `a and b or c` into `(b or c) if a else c`.

**Comment by iritkatriel** [comment]
> @ncoghlan on the issue suggested we could do this in the AST optimizer without changing the eval loop. Is that approach worth considering? It would involve transforming `a and b or c` into `(b or c) if a else c`.

I'm not sure I see what the general solution is, but I'm all for trying it.

**Comment by iritkatriel** [comment]
I'll merge this though - we can easily replace this with the alternative idea. The "sequence" pseudo-ops change is worth having anyway.
