### PR TITLE
gh-129156: Fix variable quoting in `android-env.sh` script

### LINKED ISSUE #129156: ./android.py configure-host HOST fails because export CXXFLAGS is unquoted
I encountered an issue during ./android.py configure-host in a Docker container that failed the build:

**error**:
```
/bin/sh: 90: export: -I/cpython/cross-build/aarch64-linux-android/prefix/include: bad variable name
```
**workaround**: patch ./android-env.sh to fix the export
```
RUN sed -i 's/export CXXFLAGS=\$CFLAGS/export CXXFLAGS="\$CFLAGS"/' ./android-env.sh
```
Reference: [Android/android-env.sh#L90](https://github.com/python/cpython/blob/d147e5e52cdb90496ae5fe85b3263cdfa9407a28/Android/android-env.sh#L90)

### Linked PRs
* gh-129321
* gh-129332

### PR DESCRIPTION
**Pull request by zanieb**
As reported in https://github.com/python/cpython/issues/129156, the lack of quoting can cause problems.

I added quoting to variables throughout the script. I used `shellcheck` to confirm that there were not remaining cases.

* Closes gh-129156

### CODE REVIEW

**Comment by zanieb** [comment]
This is a draft because I need to setup a cross-build for Android and test everything works still.

File: Android/android-env.sh [hunk 1]
```diff
@@ -87,11 +87,13 @@ fi
...
 # Use the same variable name as conda-build
-if [ $(uname) = "Darwin" ]; then
-    export CPU_COUNT=$(sysctl -n hw.ncpu)
+if [ "$(uname)" = "Darwin" ]; then
+    CPU_COUNT="$(sysctl -n hw.ncpu)"
+    export CPU_COUNT
 else
-    export CPU_COUNT=$(nproc)
+    CPU_COUNT="$(nproc)"
+    export CPU_COUNT
```
Comment (zanieb) [inline Android/android-env.sh:98]: The `export` is separated from the assignment as a failed command would be ignored otherwise (see https://www.shellcheck.net/wiki/SC2155)

**Comment by zanieb** [comment]
It'd still be nice to test against the shell in the report, but I couldn't reproduce the failure they described with several shells.

**Comment by mhsmith** [comment]
!buildbot android

**Review by mhsmith — APPROVED** [review]
Looks good to me. Thanks for the fixes!

@freakboy3742: If you're happy, please merge and backport.

**Review by freakboy3742 — APPROVED** [review]
Possibly a little overzealous on some of the quoting (API level can't have spaces pretty much by definition), but it doesn't hurt to be consistent. Thanks for the PR!
