### PR TITLE
gh-129928: Rework sqlite3 error helpers

### LINKED ISSUE #129928: Refactor sqlite3 error handler
In most error cases, we can use the error indicator from the SQLite database pointer when we raise exceptions. However, for some SQLite C APIs, we have to use the result code directly. This is the case for some of the blob APIs, where the error indicator is not stored on the database pointer.

Currently, our "set error" handler only handles the case where the error indicator is set on the database pointer. We also need an `Modules/_sqlite` private API for raising exception from the SQLite C API result codes.

See also https://github.com/python/cpython/pull/128507#discussion_r1903334073

### Linked PRs
* gh-129929
* gh-129941

### PR DESCRIPTION
**Pull request by erlend-aasland**
Add a private API for raising DB-API compatible exceptions based on the 
result code of SQLite C APIs. Some APIs do not store the error indicator
on the database pointer, so we need to be able to deduce the DB-API
compatible exception directly from the error code.

- rename _pysqlite_seterror() as set_error_from_db()
- introduce set_error_from_code()

----
📚 Documentation preview 📚: https://cpython-previews--129929.org.readthedocs.build/

* Issue: gh-129928

### CODE REVIEW

**Comment by erlend-aasland** [comment]
cc. @hashbrowncipher, WDYT?

**Comment by hashbrowncipher** [comment]
LGTM

File: Modules/_sqlite/connection.c [hunk 1]
```diff
@@ -1307,6 +1307,12 @@ create_window_function_impl(pysqlite_Connection *self, PyTypeObject *cls,
                         "SQLite 3.25.0 or higher");
         return NULL;
     }
+    int limit = sqlite3_limit(self->db, SQLITE_LIMIT_FUNCTION_ARG, -1);
+    if (num_params < -1 || num_params > limit) {
+        return PyErr_Format(self->ProgrammingError,
+                            "'num_params' must be between -1 and %d, not %d",
+                            limit, num_params);
+    }
```
Comment (erlend-aasland) [inline Modules/_sqlite/connection.c]: Actually, I think I'll extract this to a separate PR; we also need to perform this check before `sqlite3_create_function_v2` calls. Raising `ProgrammingError` is more accurate than the existing `OperationalError`.

Comment (erlend-aasland) [reply Modules/_sqlite/connection.c]: PR: #129941

**Comment by erlend-aasland** [comment]
Thanks for the review, @hashbrowncipher!
