### PR TITLE
gh-118201: Simplify conv_confname

### LINKED ISSUE #118201: Intermittent "unrecognized configuration name" failure on iOS and Android
# Bug report

### Bug description:

The iOS buildbot is seeing an intermittent testing failure in `test_posix.PosixTester.test_confstr: 

```python
======================================================================
ERROR: test_confstr (test.test_posix.PosixTester.test_confstr)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/buildbot/Library/Developer/XCTestDevices/4FED991E-7280-4D2F-B63A-C7FECDE66EAD/data/Containers/Bundle/Application/0809D9E4-34B6-4223-A3AD-079D76671D9D/iOSTestbed.app/python/lib/python3.13/test/test_posix.py", line 569, in test_confstr
    self.assertEqual(len(posix.confstr("CS_PATH")) > 0, True)
                         ~~~~~~~~~~~~~^^^^^^^^^^^
ValueError: unrecognized configuration name
----------------------------------------------------------------------
```
See [this PR](https://github.com/python/cpython/pull/118190#issuecomment-2073083883) for the buildbot report; [this build](https://buildbot.python.org/all/#/builders/1380/builds/66) is the resulting failure.

The failure appears to be completely transient, affecting ~1 in 10 builds; the next buildbot run almost always passes, with no changes addressing this issue.

I've been unsuccessful reproducing the test locally.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Other

### Linked PRs
* gh-118452
* gh-118453
* gh-126089
* gh-131375

### PR DESCRIPTION
**Pull request by mhsmith**
On Android and iOS we've been seeing intermittent buildbot failures where `os.confstr`, `os.pathconf` or `os.sysconf` raise a ValueError. This is not a failure in the underlying system call, but a failure to look up a mapping from strings to integers before making the system call.

I haven't been able to explain this (see #118201 for details), but I have found a way to simplify the relevant code, which will hopefully fix the issue, or at least give us some more information about it.

All three functions depend on`conv_confname`, which currently maps from strings to integers using a binary search in a C array. This PR changes it to use `os.{confstr,pathconf,sysconf}_names`, which are dicts containing the same information.

I also took the opportunity to improve the test coverage of this area.

* Fixes gh-118201
* Reverts #118452
* Reverts #118453

### CODE REVIEW

**Comment by mhsmith** [comment]
!buildbot android

**Comment by mhsmith** [comment]
!buildbot ios

**Comment by mhsmith** [comment]
Well I'm not sure why it ran the buildbots on all platforms when I only asked for two, but I've checked the failures and all of them are already present on the main branch.

**Comment by mhsmith** [comment]
@sobolevn: You've done some work on the `posix` module recently; are you able to review this PR?

**Comment by mhsmith** [comment]
I'm not sure if any active developer is familiar with this code, but I hope the change should be fairly self-explanatory. @JelleZijlstra: are you able to take a look, or can you recommend anyone else?

**Comment by JelleZijlstra** [comment]
I can take a look but I'm also not familiar so I'll need a bit of time to familiarize myself with it. Have you tried looking at the `git blame` for the affected functions to see if any were written by people who are still active?

**Comment by mhsmith** [comment]
It looks like this code has remained almost unchanged since it was written in 1999 by @freddrake.

**Comment by JelleZijlstra** [comment]
Wow, that seems like a good reason to be extra careful with any changes.

File: Modules/posixmodule.c [hunk 1]
```diff
@@ -13535,46 +13539,33 @@ struct constdef {
...
-                *valuep = table[mid].value;
-                return 1;
+conv_confname(PyObject *module, PyObject *arg, int *valuep, const char *tablename)
+{
+    if (PyUnicode_Check(arg)) {
+        PyObject *table = PyObject_GetAttrString(module, tablename);
+        if (table != NULL) {
+            arg = PyObject_GetItem(table, arg);
+            if (arg == NULL) {
+                PyErr_SetString(
```
Comment (JelleZijlstra) [inline Modules/posixmodule.c]: Call `PyErr_Clear();` first to clear the existing exception.

File: Modules/posixmodule.c [hunk 2]
```diff
@@ -13535,46 +13539,33 @@ struct constdef {
...
+                    PyExc_ValueError, "unrecognized configuration name");
             }
+            Py_DECREF(table);
         }
-        PyErr_SetString(PyExc_ValueError, "unrecognized configuration name");
-        return 0;
+        if (PyErr_Occurred())
```
Comment (JelleZijlstra) [inline Modules/posixmodule.c]: Why do we need to check this? Seems like it should be sufficient to return 0 if `PyObject_GetAttrString`. `PyErr_Occurred()` is relatively expensive and we should avoid calling it if possible.

File: Modules/posixmodule.c (hunk 1 above)
Comment (mhsmith) [reply Modules/posixmodule.c]: The documentation could be clearer about this, but it looks like the `PyErr_Set...` functions all go through `PyErr_SetRaisedException`, which clears the existing exception automatically.

Comment (JelleZijlstra) [reply Modules/posixmodule.c]: It presumably creates a chained exception though, right? I think we don't want that here.

Comment (mhsmith) [reply Modules/posixmodule.c]: It doesn't create a chained exception:
```
Python 3.14.0a1+ (heads/simplify-conv-confname-dirty:2a3e50a5587, Nov  9 2024, 23:42:24) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.confstr("whatever")
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    os.confstr("whatever")
    ~~~~~~~~~~^^^^^^^^^^^^
ValueError: unrecognized configuration name
>>> 
```

Like it says in the [C API documentation](https://docs.python.org/3/c-api/exceptions.html):

> The error indicator is not the result of [sys.exc_info()](https://docs.python.org/3/library/sys.html#sys.exc_info). The former corresponds to an exception that is not yet caught (and is therefore still propagating), while the latter returns an exception after it is caught (and has therefore stopped propagating).

An exception can only chain after it's been caught, but in this case the KeyError raised by `PyObject_GetItem` is never caught. `PyErr_SetString` will decref and replace it.

File: Modules/posixmodule.c (hunk 2 above)
Comment (mhsmith) [reply Modules/posixmodule.c]: OK, I've rearranged the code to avoid `PyErr_Occurred`, and it's ended up clearer than before.

Why is `PyErr_Occurred` expensive, though? It looks like it's just checking a member in the current thread state.

**Comment by mhsmith** [comment]
!buildbot android

File: Modules/posixmodule.c [hunk 3]
```diff
@@ -13546,46 +13550,34 @@ struct constdef {
...
+
+    if (PyLong_Check(arg)) {
+        *valuep = PyLong_AsInt(arg);
+    } else {
+        PyErr_SetString(PyExc_TypeError,
+            "configuration names must be strings or integers");
+    }
+
+    Py_DECREF(arg);
+    return !PyErr_Occurred();
```
Comment (JelleZijlstra) [inline Modules/posixmodule.c]: Avoid the call to `PyErr_Occurred`; instead, return NULL directly in error paths.

Comment (mhsmith) [reply Modules/posixmodule.c]: OK, I've changed it to only call `PyErr_Occurred` in the unavoidable case when `PyLong_AsInt` returns -1.

**Comment by mhsmith** [comment]
!buildbot android|ios

**Review by JelleZijlstra — APPROVED** [review]

**Comment by JelleZijlstra** [comment]
@mhsmith thanks, this looks good! I assume the buildbot failure are the result of the unrelated GC change that came in the other day?

**Comment by mhsmith** [comment]
Yes, and it looks like that's been fixed on the main branch now, so I'll try another run.

Let's not backport this PR to 3.13, as it's a relatively disruptive change, and a backport isn't really necessary:

* On iOS, the relevant tests are already skipped.
* On Android, the tests have never failed on the 3.13 branch.
