### PR TITLE
gh-142781: Fix type confusion in zoneinfo weak cache

### LINKED ISSUE #142781: Type confusion in `zoneinfo_ZoneInfo_impl` via overridden cache `setdefault()`
### What happened?

Handler `zoneinfo_ZoneInfo_impl()` calls `weak_cache.setdefault(key, tmp)` and blindly treats the returned object as a `ZoneInfo`, immediately casting to `PyZoneInfo_ZoneInfo` and writing to its fields. A subclass can swap `_weak_cache` with a dict-like object whose `setdefault()` returns a non-`ZoneInfo` (e.g., an `int`), causing type confusion and subsequent memory corruption/crash under ASan. A minimal PoC overrides `setdefault()` to return the wrong type and triggers a buffer overflow during teardown.

**Proof of Concept:**
```python
import zoneinfo

class EvilCache(dict):
    def setdefault(self, key, value):
        return 1337  # wrong type

class Evil(zoneinfo.ZoneInfo):
    pass

Evil._weak_cache = EvilCache()  # override the inherited cache

Evil("UTC")
```

**Affected Versions:**
<details>

| Python Version | Status | Exit Code |
|---|---|---|
| `Python 3.9.24+ (heads/3.9:9c4638d, Oct 17 2025, 11:19:30) ` | ASAN | 1 |
| `Python 3.10.19+ (heads/3.10:0142619, Oct 17 2025, 11:20:05) [GCC 13.3.0]` | ASAN | 1 |
| `Python 3.11.14+ (heads/3.11:88f3f5b, Oct 17 2025, 11:20:44) [GCC 13.3.0]` | ASAN | 1 |
| `Python 3.12.12+ (heads/3.12:8cb2092, Oct 17 2025, 11:21:35) [GCC 13.3.0]` | ASAN | 1 |
| `Python 3.13.9+ (heads/3.13:0760a57, Oct 17 2025, 11:22:25) [GCC 13.3.0]` | ASAN | 1 |
| `Python 3.14.0+ (heads/3.14:889e918, Oct 17 2025, 11:23:02) [GCC 13.3.0]` | ASAN | 1 |
| `Python 3.15.0a1+ (heads/main:fbf0843, Oct 17 2025, 11:23:37) [GCC 13.3.0]` | ASAN | 1 |

</details>

**Related Code Snippet**

<details>

```
static PyObject *
zoneinfo_ZoneInfo_impl(PyTypeObject *type, PyObject *key)
/*[clinic end generated code: output=95e61dab86bb95c3 input=ef73d7a83bf8790e]*/
{
	   if (instance == Py_None) {
        Py_DECREF(instance);
        PyObject *tmp = zoneinfo_new_instance(state, type, key);
        if (tmp == NULL) {
            return NULL;
        }

        instance =
            PyObject_CallMethod(weak_cache, "setdefault", "OO", key, tmp);
        Py_DECREF(tmp);
        if (instance == NULL) {
            return NULL;
        }
        
	// Bug: Type Confusion
        ((PyZoneInfo_ZoneInfo *)instance)->source = SOURCE_CACHE;
    }

    update_strong_cache(state, type, key, instance);
    return instance;
}
```

</details>

**Sanitizer Report**

<details>

```python
=================================================================
==1440071==ERROR: AddressSanitizer: global-buffer-overflow on address 0x568a2b530208 at pc 0x568a2ac75512 bp 0x7ffe6e89f060 sp 0x7ffe6e89f050
READ of size 8 at 0x568a2b530208 thread T0
    #0 0x568a2ac75511 in _Py_Dealloc Objects/object.c:3174
    #1 0x568a2acbf5cb in Py_DECREF Include/refcount.h:401
    #2 0x568a2acbf5ea in Py_XDECREF Include/refcount.h:511
    #3 0x568a2acc1a9c in tuple_dealloc Objects/tupleobject.c:213
    #4 0x568a2ac75481 in _Py_Dealloc Objects/object.c:3200
    #5 0x568a2abc2e2b in Py_DECREF Include/refcount.h:401
    #6 0x568a2abc33a8 in Py_XDECREF Include/refcount.h:511
    #7 0x568a2abc533a in code_dealloc Objects/codeobject.c:2423
    #8 0x568a2ac75481 in _Py_Dealloc Objects/object.c:3200
    #9 0x568a2ac0cb65 in Py_DECREF Include/refcount.h:401
    #10 0x568a2ac0f5c9 in func_dealloc Objects/funcobject.c:1158
    #11 0x568a2ac75481 in _Py_Dealloc Objects/object.c:3200
    #12 0x568a2ac40874 in Py_DECREF Include/refcount.h:401
    #13 0x568a2ac40893 in Py_XDECREF Include/refcount.h:511
    #14 0x568a2ac40edf in dictkeys_decref Objects/dictobject.c:462
    #15 0x568a2ac514e9 in clear_lock_held Objects/dictobject.c:2947
    #16 0x568a2ac5168f in PyDict_Clear Objects/dictobject.c:2976
    #17 0x568a2acdca6c in type_clear Objects/typeobject.c:6962
    #18 0x568a2ace181c in subtype_clear Objects/typeobject.c:2690
    #19 0x568a2aee3fe0 in delete_garbage Python/gc.c:1199
    #20 0x568a2aee472c in gc_collect_region Python/gc.c:1814
    #21 0x568a2aee5ce2 in gc_collect_full Python/gc.c:1728
    #22 0x568a2aee7045 in _PyGC_Collect Python/gc.c:2096
    #23 0x568a2aee711a in _PyGC_CollectNoFail Python/gc.c:2137
    #24 0x568a2af5b2dc in finalize_modules Python/pylifecycle.c:1795
    #25 0x568a2af66618 in _Py_Finalize Python/pylifecycle.c:2255
    #26 0x568a2af666f2 in Py_FinalizeEx Python/pylifecycle.c:2378
    #27 0x568a2afc8847 in Py_RunMain Modules/main.c:774
    #28 0x568a2afc8a2e in pymain_main Modules/main.c:802
    #29 0x568a2afc8db3 in Py_BytesMain Modules/main.c:826
    #30 0x568a2aa4c645 in main Programs/python.c:15
    #31 0x7add2d02a1c9 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #32 0x7add2d02a28a in __libc_start_main_impl ../csu/libc-start.c:360
    #33 0x568a2aa4c574 in _start (/home/jackfromeast/Desktop/entropy/tasks/grammar-afl++-latest/targets/cpython/python+0x2dd574) (BuildId: ff3dc40ea460bd4beb2c3a72283cca525b319bf0)

Address 0x568a2b530208 is a wild pointer inside of access range of size 0x000000000008.
SUMMARY: AddressSanitizer: global-buffer-overflow Objects/object.c:3174 in _Py_Dealloc
Shadow bytes around the buggy address:
  0x568a2b52ff80: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x568a2b530000: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x568a2b530080: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x568a2b530100: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x568a2b530180: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
=>0x568a2b530200: f9[f9]f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x568a2b530280: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x568a2b530300: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x568a2b530380: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x568a2b530400: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x568a2b530480: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==1440071==ABORTING
```

</details>

### Linked PRs
* gh-142925
* gh-145418
* gh-145419

### PR DESCRIPTION
**Pull request by superboy-zjc**
Validate the types returned from `_weak_cache.get()` and `_weak_cache.setdefault()` to prevent type confusion when a ZoneInfo subclass provides a misbehaving cache implementation.

Fixes gh-142781.

### CODE REVIEW

File: Modules/_zoneinfo.c [hunk 1]
```diff
@@ -327,6 +327,15 @@ zoneinfo_ZoneInfo_impl(PyTypeObject *type, PyObject *key)
         return NULL;
     }
 
+    if (instance != Py_None && !PyObject_TypeCheck(instance, type)) {
+        const char *e = "%s._weak_cache.get() returned %s, expected %s";
```
Comment (picnixz) [inline Modules/_zoneinfo.c]: No need to have a temporary variable. In addition, avoid exposing implementation details about weak_cache here. Instead, I would simply say that the instance is incorrect (something like "expecting a %T, got %T")

File: Misc/NEWS.d/next/Library/2025-12-18-00-14-16.gh-issue-142781.gcOeYF.rst [hunk 2]
```diff
@@ -0,0 +1,3 @@
+Fix a type confusion in zoneinfo where a malicious override of _weak_cache
+in a zoneinfo subclass can cause memory corruption and crash the
+interpreter.
```
Comment (picnixz) [inline Misc/NEWS.d/next/Library/2025-12-18-00-14-16.gh-issue-142781.gcOeYF.rst]: This entry should be rewritten, it doesn't help for the end user. It's not necessarily a "malicious" override, it could be accidental as well. I would rather have something like

```rst
:mod:`zoneinfo`: fix a crash when instantiating :class:`~zoneinfo.Zoneinfo`
objects for which the internal class-level cache is consistent.
```

File: Lib/test/test_zoneinfo/test_zoneinfo.py [hunk 3]
```diff
@@ -1575,6 +1575,33 @@ class EvilZoneInfo(self.klass):
 class CZoneInfoCacheTest(ZoneInfoCacheTest):
     module = c_zoneinfo
 
+    def test_weak_cache_get_type_confusion(self):
```
Comment (picnixz) [inline Lib/test/test_zoneinfo/test_zoneinfo.py]:
```suggestion
    def test_inconsistent_weak_cache_get(self):
```

File: Lib/test/test_zoneinfo/test_zoneinfo.py [hunk 4]
```diff
@@ -1575,6 +1575,33 @@ class EvilZoneInfo(self.klass):
...
+
+        class EvilZoneInfo(self.klass):
+            pass
+
+        EvilZoneInfo._weak_cache = EvilCache()
+
+        with self.assertRaises(TypeError):
+            EvilZoneInfo("America/Los_Angeles")
+
+    def test_weak_cache_setdefault_type_confusion(self):
```
Comment (picnixz) [inline Lib/test/test_zoneinfo/test_zoneinfo.py]:
```suggestion
    def test_inconsistent_weak_cache_setdefault(self):
```

File: Lib/test/test_zoneinfo/test_zoneinfo.py [hunk 5]
```diff
@@ -1575,6 +1575,33 @@ class EvilZoneInfo(self.klass):
...
+        class EvilCache:
```
Comment (picnixz) [inline Lib/test/test_zoneinfo/test_zoneinfo.py]: Rename EvilCache with Cache and EvilZoneInfo by ZI only. In addition, create _weak_cache when instantiating the class:

```py
class ZI(self.class):
    _weak_cache = Cache()
```

Then, check the TypeError message.

**Review by picnixz — DISMISSED** [review]

File: Misc/NEWS.d/next/Library/2025-12-18-00-14-16.gh-issue-142781.gcOeYF.rst (hunk 2 above)
Comment (superboy-zjc) [reply Misc/NEWS.d/next/Library/2025-12-18-00-14-16.gh-issue-142781.gcOeYF.rst]: done

**Comment by superboy-zjc** [comment]
Thanks for the review! I have addressed all the comments above. Ready for another look.

File: Modules/_zoneinfo.c [hunk 6]
```diff
@@ -327,6 +327,14 @@ zoneinfo_ZoneInfo_impl(PyTypeObject *type, PyObject *key)
         return NULL;
     }
 
+    if (instance != Py_None && !PyObject_TypeCheck(instance, type)) {
+        PyErr_Format(PyExc_TypeError, "expected %s, got %s",
+                     type->tp_name, Py_TYPE(instance)->tp_name);
+        Py_DECREF(instance);
+        Py_DECREF(weak_cache);
+        return NULL;
+    }
```
Comment (picnixz) [inline Modules/_zoneinfo.c]: This can come up as an `else` branch. We already have `if (instance == Py_None)`, so you can add an else branch.

File: Lib/test/test_zoneinfo/test_zoneinfo.py [hunk 7]
```diff
@@ -1575,6 +1575,37 @@ class EvilZoneInfo(self.klass):
...
+                return 1337
+
+        class ZI(self.klass):
+            pass
+        # Must set AFTER class creation to override __init_subclass__
+        ZI._weak_cache = Cache()
+
+        with self.assertRaises(TypeError) as te:
+            ZI("America/Los_Angeles")
+        # Heap type objects' tp_name should just be the type name, i.e. ZI
```
Comment (picnixz) [inline Lib/test/test_zoneinfo/test_zoneinfo.py]: No need for this comment.

File: Lib/test/test_zoneinfo/test_zoneinfo.py [hunk 8]
```diff
@@ -1575,6 +1575,37 @@ class EvilZoneInfo(self.klass):
...
```
Comment (picnixz) [inline Lib/test/test_zoneinfo/test_zoneinfo.py]: ditto

File: Lib/test/test_zoneinfo/test_zoneinfo.py [hunk 9]
```diff
@@ -1575,6 +1575,37 @@ class EvilZoneInfo(self.klass):
...
+    def test_inconsistent_weak_cache_setdefault(self):
+        class Cache:
+            def get(self, key, default=None):
+                return default
+            def setdefault(self, key, value):
+                return 1337
+
+        class ZI(self.klass):
+            pass
+        # Must set AFTER class creation to override __init_subclass__
```
Comment (picnixz) [inline Lib/test/test_zoneinfo/test_zoneinfo.py]:
```suggestion
        # Class attribute must be set after class creation
        # to override zoneinfo.Zoneinfo.__init_subclass__.
```

And update the comment in the other test as well.

**Review by picnixz — COMMENTED** [review]
You should update the branch as we ZoneInfo was modified recently.

**Comment by superboy-zjc** [comment]
> You should update the branch as we ZoneInfo was modified recently.

Thanks for your advice! All comments are resolved. Let me know if anything else is needed!

File: Modules/_zoneinfo.c [hunk 10]
```diff
@@ -342,7 +342,22 @@ zoneinfo_ZoneInfo_impl(PyTypeObject *type, PyObject *key)
...
+        if (!PyObject_TypeCheck(instance, type)) {
+            PyErr_Format(PyExc_TypeError, "expected %s, got %s",
+                         type->tp_name, Py_TYPE(instance)->tp_name);
+            Py_DECREF(instance);
+            Py_DECREF(weak_cache);
+            return NULL;
+        }
+
         ((PyZoneInfo_ZoneInfo *)instance)->source = SOURCE_CACHE;
+    } else if (!PyObject_TypeCheck(instance, type)) {
```
Comment (picnixz) [inline Modules/_zoneinfo.c]:
```suggestion
    }
    else if (!PyObject_TypeCheck(instance, type)) {
```

File: Modules/_zoneinfo.c
Comment (serhiy-storchaka) [inline Modules/_zoneinfo.c]: Incorrect call. The re should be one argument after format "O". Py_None is ignored.

File: Modules/_zoneinfo.c [hunk 11]
```diff
@@ -342,8 +342,24 @@ zoneinfo_ZoneInfo_impl(PyTypeObject *type, PyObject *key)
...
+                         type->tp_name, Py_TYPE(instance)->tp_name);
+            Py_DECREF(instance);
+            Py_DECREF(weak_cache);
+            return NULL;
+        }
+
         ((PyZoneInfo_ZoneInfo *)instance)->source = SOURCE_CACHE;
     }
+    else if (!PyObject_TypeCheck(instance, type)) {
+        PyErr_Format(PyExc_TypeError, "expected %s, got %s",
```
Comment (serhiy-storchaka) [inline Modules/_zoneinfo.c]: This error message is rather confusing. "Expected" means that you passed argument of wrong type. I would write something like "Unexpected instance of %T in %T weak cache for key %R". And we can use RuntimeError here, to accent that this is an unexpected error.

File: Modules/_zoneinfo.c [hunk 12]
```diff
@@ -342,8 +342,24 @@ zoneinfo_ZoneInfo_impl(PyTypeObject *type, PyObject *key)
...
+
+        if (!PyObject_TypeCheck(instance, type)) {
+            PyErr_Format(PyExc_TypeError, "expected %s, got %s",
+                         type->tp_name, Py_TYPE(instance)->tp_name);
+            Py_DECREF(instance);
+            Py_DECREF(weak_cache);
+            return NULL;
+        }
+
         ((PyZoneInfo_ZoneInfo *)instance)->source = SOURCE_CACHE;
```
Comment (serhiy-storchaka) [inline Modules/_zoneinfo.c]: Objects in the weak cache should have source = SOURCE_CACHE. We only need to set it for new objects. So, I think that we should move this line up and set source for tmp instead of instance.

Then we could deduplicate the check and error formatting code.

File: Modules/_zoneinfo.c (hunk 11 above)
Comment (superboy-zjc) [reply Modules/_zoneinfo.c]: Agreed! Done.

File: Modules/_zoneinfo.c [hunk 13]
```diff
@@ -335,27 +335,20 @@ zoneinfo_ZoneInfo_impl(PyTypeObject *type, PyObject *key)
...
-        ((PyZoneInfo_ZoneInfo *)instance)->source = SOURCE_CACHE;
     }
-    else if (!PyObject_TypeCheck(instance, type)) {
-        PyErr_Format(PyExc_TypeError, "expected %s, got %s",
-                     type->tp_name, Py_TYPE(instance)->tp_name);
+
+    if (!PyObject_TypeCheck(instance, type)) {
+        PyErr_Format(PyExc_RuntimeError,
+                     "Unexpected instance of %T in %s weak cache for key %R",
+                     instance, type->tp_name, key);
```
Comment (serhiy-storchaka) [inline Modules/_zoneinfo.c]: You can use `_PyType_Name()` instead of `tp_name`. It always returns a short name.

**Review by serhiy-storchaka — APPROVED** [review]
LGTM. 👍

File: Modules/_zoneinfo.c (hunk 13 above)
Comment (StanFromIreland) [reply Modules/_zoneinfo.c]:
```suggestion
                     instance, _PyType_Name(type), key);
```

File: Lib/test/test_zoneinfo/test_zoneinfo.py [hunk 14]
```diff
@@ -1577,6 +1577,44 @@ class EvilZoneInfo(self.klass):
...
+        class Cache:
+            def get(self, key, default=None):
+                return default
+            def setdefault(self, key, value):
+                return 1337
+
+        class ZI(self.klass):
+            pass
+        # Class attribute must be set after class creation
+        # to override zoneinfo.Zoneinfo.__init_subclass__.
```
Comment (StanFromIreland) [inline Lib/test/test_zoneinfo/test_zoneinfo.py]:
```suggestion
        # to override zoneinfo.ZoneInfo.__init_subclass__.
```

File: Lib/test/test_zoneinfo/test_zoneinfo.py [hunk 15]
```diff
@@ -1577,6 +1577,44 @@ class EvilZoneInfo(self.klass):
...
 
+    def test_inconsistent_weak_cache_get(self):
+        class Cache:
+            def get(self, key, default=None):
+                return 1337
+
+        class ZI(self.klass):
+            pass
+        # Class attribute must be set after class creation
+        # to override zoneinfo.Zoneinfo.__init_subclass__.
```
Comment (StanFromIreland) [inline Lib/test/test_zoneinfo/test_zoneinfo.py]:
```suggestion
        # to override zoneinfo.ZoneInfo.__init_subclass__.
```

**Review by StanFromIreland — APPROVED** [review]
LGTM
