### PR TITLE
gh-120225: fix crash in compiler on empty block at end of exception handler

### LINKED ISSUE #120225: flowgraph.c: push_cold_blocks_to_end: Assertion `prev_instr' failed
# Bug report

### Bug description:

The following code causes a crash with cpython 3.13 (56a7e0483436d1ebd2af97c02defe0e67c4bb495) and with the current main branch (d68a22e7a68ae09f7db61d5a1a3bd9c0360cf3ee)

```python
async def name_4():
    match b'':
        case True:
            pass
        case name_5 if f'e':
            {name_3: name_4 async for name_2 in name_5}
        case []:
            pass
    [[]]
```

output (Python 3.13.0b2+):
```python
python: Python/flowgraph.c:2282: push_cold_blocks_to_end: Assertion `prev_instr' failed.
```
I bisected the problem down to this commit 2091fb2a85c1aa2d9b22c02736b07831bd875c2a.
@iritkatriel can you take a look at it?

### CPython versions tested on:

3.13, CPython main branch

### Operating systems tested on:

_No response_

### Linked PRs
* gh-120235
* gh-120249

### PR DESCRIPTION
**Pull request by iritkatriel**
Fixes #120225.

It's not necessary to set a line number here. It can be propagated later (and if it's not that's also ok, JUMP_NO_INTERRUPT doesn't require a line number).

* Issue: gh-120225

### CODE REVIEW

File: Python/flowgraph.c [hunk 1]
```diff
@@ -2304,15 +2304,11 @@ push_cold_blocks_to_end(cfg_builder *g) {
...
-            // b cannot be empty because at the end of an exception handler
-            // there is always a POP_EXCEPT + RERAISE/RETURN
-            assert(prev_instr);
-
             basicblock_addop(explicit_jump, JUMP_NO_INTERRUPT, b->b_next->b_label.id,
-                             prev_instr->i_loc);
+                             NO_LOCATION);
             explicit_jump->b_cold = 1;
             explicit_jump->b_next = b->b_next;
+            explicit_jump->b_predecessors = 1;
```
Comment (iritkatriel) [inline Python/flowgraph.c:2311]: This was missing here - it is needed later for line number propagation to work.

File: Lib/test/test_compile.py [hunk 2]
```diff
@@ -1409,6 +1409,16 @@ def f():
         for kw in ("except", "except*"):
             exec(code % kw, g, l);
 
+    def test_regression_gh_120225(self):
+        async def name_4():
+            match b'':
+                case True:
+                    pass
+                case name_5 if f'e':
+                    {name_3: name_4 async for name_2 in name_5}
```
Comment (carljm) [inline Lib/test/test_compile.py:1418]: I guess the exception handling block is coming from inlining this comprehension?

**Review by carljm — APPROVED** [review]
