### PR TITLE
GH-104510: Fix refleaks in _io base types

### LINKED ISSUE #104510: Ref leaks introduced by _io isolation (gh-101948)
Tried on current main.
```python
./python -m test -R 3:3 test_nntplib
0:00:00 load avg: 2.49 Run tests sequentially
0:00:00 load avg: 2.49 [1/1] test_nntplib
beginning 6 repetitions
123456
......
test_nntplib leaked [1222, 1220, 1222] references, sum=3664
test_nntplib leaked [828, 827, 829] memory blocks, sum=2484
test_nntplib failed (reference leak)

== Tests result: FAILURE ==

1 test failed:
    test_nntplib

Total duration: 640 ms
Tests result: FAILURE
```
OS: WSL Ubuntu 20.04 & Windows 10

UPD:
Leaked tests:
test_nntplib
test_gzip
test_httpservers
test_xmlrpc
test_tarfile

### Linked PRs
* gh-104516

### PR DESCRIPTION
**Pull request by kumaraditya303**
* Issue: gh-104510

### CODE REVIEW

**Review by sunmy2019 — APPROVED** [review]
LGTM

File: Modules/_io/iobase.c [hunk 1]
```diff
@@ -26,12 +26,6 @@ class _io._RawIOBase "PyObject *" "clinic_state()->PyRawIOBase_Type"
  * IOBase class, an abstract class
```
Comment (Eclips4) [inline Modules/_io/iobase.c]: Should we delete this comment after moving `iobase` to `_iomodule.h`?

**Review by Eclips4 — APPROVED** [review]
All ref leaks are gone!
Thanks for the fix.

**Comment by erlend-aasland** [comment]
The reason why this fix works is not obvious. Can you add a clarifying comment, alternatively expand on the C API docs for `tp_traverse`?

Note to self: we also need to document the GC peculiarities of heap-type-inherits-from-static-type (for example `defdict` in the \_collections extension module).

File: Modules/_io/bufferedio.c [hunk 2]
```diff
@@ -2444,13 +2437,12 @@ static PyMethodDef bufferediobase_methods[] = {
...
     {Py_tp_doc, (void *)bufferediobase_doc},
     {Py_tp_methods, bufferediobase_methods},
-    {Py_tp_traverse, bufferediobase_traverse},
     {0, NULL},
 };
 
 PyType_Spec bufferediobase_spec = {
     .name = "_io._BufferedIOBase",
-    .flags = (Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE | Py_TPFLAGS_HAVE_GC |
+    .flags = (Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE |
```
Comment (erlend-aasland) [inline Modules/_io/bufferedio.c:2446]: How does this fare when run though this?

```python
import gc
import sys

for _ in range(5):
    gc.collect()
    before = sys.gettotalrefcount()

    import _io
    del sys.modules["_io"]
    del _io

    gc.collect()
    after = sys.gettotalrefcount()

    print(f"{before=}, {after=}")
    # assert after == before
```

Comment (kumaraditya303) [reply Modules/_io/bufferedio.c:2446]: Hmm, I am testing if this approach is better, so far it fails assertion on your script but the refleaks tests pass.

Comment (sunmy2019) [reply Modules/_io/bufferedio.c:2446]: I remembered all heap types should have GC. #87138

**Review by erlend-aasland — APPROVED** [review]
AFAICS, this is the correct solution.

We still need to write a sentence or two in the docs about our recent GC adventures (\_io, \_collections).

File: Modules/_io/bufferedio.c (hunk 2 above)
Comment (kumaraditya303) [reply Modules/_io/bufferedio.c:2446]: > I remembered all heap types should have GC. https://github.com/python/cpython/issues/87138

The heap type still has GC but it now inherits traverse and clear slots from its base because `Py_TPFLAGS_HAVE_GC` isn't set. See https://docs.python.org/3.12/c-api/gcsupport.html

**Comment by sunmy2019** [comment]
> The heap type still has GC but it now inherits traverse and clear slots from its base because `Py_TPFLAGS_HAVE_GC` isn't set. See https://docs.python.org/3.12/c-api/gcsupport.html

The doc's a bit unclear here.
>When calling [PyType_Ready()](https://docs.python.org/3.12/c-api/type.html#c.PyType_Ready) or some of the APIs that indirectly call it like [PyType_FromSpecWithBases()](https://docs.python.org/3.12/c-api/type.html#c.PyType_FromSpecWithBases) or [PyType_FromSpec()](https://docs.python.org/3.12/c-api/type.html#c.PyType_FromSpec) the interpreter will automatically populate the [tp_flags](https://docs.python.org/3.12/c-api/typeobj.html#c.PyTypeObject.tp_flags), [tp_traverse](https://docs.python.org/3.12/c-api/typeobj.html#c.PyTypeObject.tp_traverse) and [tp_clear](https://docs.python.org/3.12/c-api/typeobj.html#c.PyTypeObject.tp_clear) fields if the type inherits from a class that implements the garbage collector protocol and the child class does not include the [Py_TPFLAGS_HAVE_GC](https://docs.python.org/3.12/c-api/typeobj.html#Py_TPFLAGS_HAVE_GC) flag.

From the code, we see,
https://github.com/python/cpython/blob/0bb61dd5b0ffc248e18f1b33cddd18788f28e60a/Objects/typeobject.c#L6670-L6678

To get the [tp_traverse](https://docs.python.org/3.12/c-api/typeobj.html#c.PyTypeObject.tp_traverse) and [tp_clear](https://docs.python.org/3.12/c-api/typeobj.html#c.PyTypeObject.tp_clear) inherited, the child type must have them both `NULL`.

This is against the doc. Also, the comparisons in lines 6674 and 6676 are unnecessary.

I guess the author was trying to write 
```c
-      (!type->tp_traverse && !type->tp_clear)) { 
+      (!type->tp_traverse || !type->tp_clear)) {  
```

It was a 22-yr old code 13d52f0b3289e34298fbf5d3912cb642f3d2fbd9. Don't know what to do.

**Comment by kumaraditya303** [comment]
> Don't know what to do. Maybe we should only update the doc.

The best we can do is to fix docs, the behavior here is ancient.

**Comment by vstinner** [comment]
Next time, it would be nice to elaborate the rationale for the fix in the commit, rather than just saying "fix" without any commit message ;-) It's really hard to handle the GC correctly with heap types. Better documentation is required.

The _io module is one of the few C extensions which use class inheritance with heap types implemented in C.

**Comment by vstinner** [comment]
cc @pablogsal: GC issues are hard :-(
