### PR TITLE
gh-95324: Emit a warning if an object doesn't call PyObject_GC_UnTrack during deallocation in debug mode

### LINKED ISSUE #95324: Some GC types can crash during destruction if a GC runs executes
We have been bitten a couple of times already if C extension types that implement the GC interface don't call `PyObject_GC_UnTrack` in their `tp_dealloc` slot. The last issue was https://github.com/python/cpython/issues/95045

Although this is technically not always an error (the `tp_free` slot untracks the object from the GC), if the GC executes during the deallocator is possible that it will see an object with 0 reference count.

To avoid this in the future, we should add a warning if this happens so we can fix it within CPython

### PR DESCRIPTION
**Pull request by pablogsal**
Closes: #95324

* Issue: gh-95324

### CODE REVIEW

File: Modules/gcmodule.c [hunk 1]
```diff
@@ -2347,6 +2347,13 @@ PyObject_GC_Del(void *op)
     size_t presize = _PyType_PreHeaderSize(((PyObject *)op)->ob_type);
     PyGC_Head *g = AS_GC(op);
     if (_PyObject_GC_IS_TRACKED(op)) {
+#ifdef Py_DEBUG
+    if (PyErr_WarnExplicitFormat(PyExc_ResourceWarning, "gc", 0,
```
Comment (iritkatriel) [inline Modules/gcmodule.c]: Is the indentation correct here?

Comment (pablogsal) [reply Modules/gcmodule.c]: No, it lacks one level. Fixing, one sec

**Review by iritkatriel — APPROVED** [review]
