### PR TITLE
bpo-32782: PEP3118 itemsize of an empty ctypes array should not be 0

### LINKED ISSUE #76963: memoryview & ctypes: incorrect itemsize for empty array
BPO | [32782](https://bugs.python.org/issue32782)
--- | :---
Nosy | @terryjreedy, @amauryfa, @abalkin, @skrah, @meadori, @eric-wieser
PRs | <li>python/cpython#5576</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-02-06.18:53:21.025>
labels = ['interpreter-core', 'type-bug', '3.8', '3.9', '3.10', 'ctypes']
title = 'memoryview & ctypes: incorrect itemsize for empty array'
updated_at = <Date 2020-05-23.15:47:49.464>
user = 'https://github.com/eric-wieser'
```

bugs.python.org fields:
```python
activity = <Date 2020-05-23.15:47:49.464>
actor = 'cheryl.sabella'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core', 'ctypes']
creation = <Date 2018-02-06.18:53:21.025>
creator = 'Eric.Wieser'
dependencies = []
files = []
hgrepos = []
issue_num = 32782
keywords = ['patch']
message_count = 9.0
messages = ['311740', '321290', '324705', '340230', '340231', '340232', '340235', '340236', '348004']
nosy_count = 8.0
nosy_names = ['terry.reedy', 'teoliphant', 'amaury.forgeotdarc', 'belopolsky', 'skrah', 'meador.inge', 'Eric.Wieser', 'Eric Wieser']
pr_nums = ['5576']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32782'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

### Linked PRs
* gh-100451
* gh-100452

### PR DESCRIPTION
**Pull request by eric-wieser**
The itemsize should be computed from the item type, not by dividing the total size by the length and assuming that the length is not zero.

The tests already expected this behavior, they were just missing the test-case needed to trigger it.

https://bugs.python.org/issue32782

(fixes #76963)

### CODE REVIEW

**Comment by eric-wieser** [comment]
@pv: Since you've made PEP3118 patches to cpython before, would you mind reviewing this?

File: Modules/_ctypes/_ctypes.c [hunk 1]
```diff
@@ -2613,12 +2648,11 @@ static int PyCData_NewGetBuffer(PyObject *myself, Py_buffer *view, int flags)
...
     view->ndim = dict->ndim;
     view->shape = dict->shape;
-    view->itemsize = self->b_size;
-    if (view->itemsize) {
-        for (i = 0; i < view->ndim; ++i) {
-            view->itemsize /= dict->shape[i];
-        }
+    item_dict = PyCData_item_stgdict(dict);
+    if (item_dict == NULL) {
+        return NULL;
```
Comment (mattip) [inline Modules/_ctypes/_ctypes.c]: Should return an error state, not NULL

Comment (mattip) [reply Modules/_ctypes/_ctypes.c]: It seems from the [PEP](https://legacy.python.org/dev/peps/pep-3118) that for `getbufferproc` the error status is -1

Comment (eric-wieser) [reply Modules/_ctypes/_ctypes.c]: Good catch, thanks

Comment (eric-wieser) [reply Modules/_ctypes/_ctypes.c]: Fixed

File: Modules/_ctypes/_ctypes.c [hunk 2]
```diff
@@ -2596,10 +2596,45 @@ static PyMemberDef PyCData_members[] = {
...
+        StgDictObject *item_dict;
+
+        type_attr = PyDict_GetItemString((PyObject *)dict, "_type_");
+        if (!type_attr) {
+            PyErr_SetString(PyExc_AttributeError,
+                            "class must define a '_type_' attribute");
+            return NULL;
+        }
+
+        item_dict = PyType_stgdict(type_attr);
```
Comment (mattip) [inline Modules/_ctypes/_ctypes.c]: Missing `Py_DECREF(type_attr)`

Comment (eric-wieser) [reply Modules/_ctypes/_ctypes.c]: Don't think so - `PyDict_GetItemString`, which is used to get `type_attr` returns a borrowed reference

Comment (mattip) [reply Modules/_ctypes/_ctypes.c]: sorry, my bad

**Comment by mattip** [comment]
LGTM

the test failures do not seem related to this pull request

**Comment by eric-wieser** [comment]
@mattip: Can you approve via github so that this goes through the process automation that's set up?

**Review by mattip — APPROVED** [review]

**Comment by eric-wieser** [comment]
Thanks @mattip. If you've more ctypes appetite left, there's also #5561

**Comment by eric-wieser** [comment]
Re-opening to restart the tests

**Comment by terryjreedy** [comment]
Tests for empty arrays of floats and doubles are added.

My naive question is this: The PEP suggests that itemsize should cache the return from PyBuffer_SizeFromFormat.  Was that function actual added?  Can it be used?

**Comment by eric-wieser** [comment]
I can't find an reference to `PyBuffer_SizeFromFormat` in the source code other than a prototype, and the docs say it's unimplemented.

At any rate, ctypes knows the size without having to resort to string parsing

File: Modules/_ctypes/_ctypes.c [hunk 3]
```diff
@@ -2596,10 +2596,45 @@ static PyMemberDef PyCData_members[] = {
     { NULL },
 };
 
+/*
+  Get the StgDictObject corresponding to a single item of a multidimensional
+  array.
+  Takes and returns a borrowed reference.
+*/
+static StgDictObject *PyCData_item_stgdict(StgDictObject *dict)
```
Comment (ZackerySpytz) [inline Modules/_ctypes/_ctypes.c]: `PyCData_item_stgdict(StgDictObject *dict)` should be on its own line to comply with [PEP 7](https://www.python.org/dev/peps/pep-0007/#code-lay-out).

Comment (eric-wieser) [reply Modules/_ctypes/_ctypes.c]: This matches the style of `PyCData_NewGetBuffer` below. Shall I change both?

**Comment by skrah** [comment]
@terryjreedy No, `PyBuffer_SizeFromFormat()` has never been added. `struct.calcsize()` works for simple formats but cannot handle records.

To implement that function properly for nested types, you need some sort of a type tree.

File: Modules/_ctypes/_ctypes.c [hunk 4]
```diff
@@ -2613,12 +2648,11 @@ static int PyCData_NewGetBuffer(PyObject *myself, Py_buffer *view, int flags)
     view->format = dict->format ? dict->format : "B";
     view->ndim = dict->ndim;
     view->shape = dict->shape;
-    view->itemsize = self->b_size;
-    if (view->itemsize) {
-        for (i = 0; i < view->ndim; ++i) {
-            view->itemsize /= dict->shape[i];
-        }
+    item_dict = PyCData_item_stgdict(dict);
```
Comment (skrah) [inline Modules/_ctypes/_ctypes.c]: Would it be possible to have `dict->itemsize` on every dict object instead of traversing the tree to find it?

File: Modules/_ctypes/_ctypes.c (hunk 3 above)
Comment (skrah) [reply Modules/_ctypes/_ctypes.c]: Yes, since most of the functions in that file follow PEP 7.

**Comment by csabella** [comment]
@eric-wieser, please respond to @skrah's review.  Thanks!

File: Modules/_ctypes/_ctypes.c (hunk 4 above)
Comment (eric-wieser) [reply Modules/_ctypes/_ctypes.c]: Seems reasonable since we already do that for shape. I did it this way because it seemed like a smaller change. I'll have a go at doing it the way you suggest.

**Comment by eric-wieser** [comment]
@skrah, I took at look at what you suggested, and it looks far too hard to get correct. There are too many places that construct a `StgDictObject` and just assume all the fields (like

**Comment by eric-wieser** [comment]
@skrah: Updated the existing commit to fix PEP7, and made a follow-up to use the approach you suggested. It's been over a year since I authored this, so I no longer remember how to run the tests on my setup - I'll leave that to CI.

**Comment by eric-wieser** [comment]
Ci fails on the second commit - an assertion error checking that `stgdict.itemsize` was populated by the time get_buffer is called.

There are way too many places that construct `stgdict` objects fieldwise, and while I tried to find all of them to populate the `itemsize` member. I seems to have missed some. At any rate, storing information in two places seems like a recipe for it to become out of sync, and I don't think we care about whatever marginal speed boost caching gives here - memoryviews are probably used mostly on large buffers, and the overhead of my original approach scales with number of dimensions (rarely more than 3) not array size.

@skrah, are you happy with the patch of the first commit by itself?

**Comment by skrah** [comment]
@eric-wieser Thanks for trying out the other approach, if it's too much work I agree that we should not spend too much time on it.   The principle of f4e3ca9 looks good to me, I haven't really reviewed it yet though.

**Comment by eric-wieser** [comment]
I'm at a loss here. Tests pass on my machine (WSL on windows 10), but fail on CI with:
```
Re-running test_ctypes in verbose mode
Fatal Python error: Floating point exception
```

I'm miles away from floating point here, so I have no clue what is happening

**Comment by eric-wieser** [comment]
Restart tests now that #13881 is in

**Comment by eric-wieser** [comment]
@skrah: All passing - although probably best to backport #13881 to 2.7 first so that this passes when backported

**Comment by eric-wieser** [comment]
Worth tagging this as wanting a backport this to 2.7 as well?

**Comment by eric-wieser** [comment]
@skrah: Mind taking another look?

**Comment by eric-wieser** [comment]
@csabella, do you have suggestions for finding a core reviewer with time to review this?

**Comment by seberg** [comment]
I have not looked at this closely, but it seems like @skrah has reviewed it, and this has been looked at by a few people involved in heavier buffer protocol users (i.e. NumPy).  Can we somehow help moving issues like this ahead, by reviewing it, or is this hinging too much at specific python core devs?  In the back of my mind, the buffer protocol came as much from NumPy as from Python itself, which maybe adds to making it difficult to push these type of issues over the finish line?

**Comment by skrah** [comment]
I've only reviewed the principle. The buffer protocol is maintained, it is `ctypes` that hardly anyone wants to touch.

The buffer protocol part in the abstract looks correct, I don't have time or inclination for a deep `ctypes` review.

**Comment by ambv** [comment]
This missed the boat for inclusion in Python 3.9 which accepts security fixes only as of today.

**Comment by eric-wieser** [comment]
Is there anything I can do to help prevent this forever being pushed to a later release?

**Comment by eric-wieser** [comment]
The CI failure here looks completely unrelated to the change; is there anything I can do about it?

**Comment by eric-wieser** [comment]
@mdickinson, I see you recently reviewed some ctypes PRs; would you mind taking a quick look at this one?

**Comment by mdickinson** [comment]
@eric-wieser Will do. It might take me a few days to get to it.

**Review by mdickinson — APPROVED** [review]
LGTM, and works as expected on my machine (confirmed that the new unit tests fail before the fix and pass afterward). I'm wondering whether we should upgrade the `assert`s in `PyCData_itemtype` to use `Py_FatalError` instead. I was unable to convince myself that there was no possibility of `stg_dict` being `NULL` on this code path.

**Comment by eric-wieser** [comment]
Thanks for testing!

Given this file has 52 asserts (11 on std_dict) and no `Py_FatalError`s, I'd be inclined to declare that change out of scope.

Is that ok?

**Comment by eric-wieser** [comment]
Oops, just realized that I probably clobbered the buildbot status by merging main; github was giving me a red cross so I clicked the update button without looking carefully enough...

**Comment by mdickinson** [comment]
> Is that ok?

Yep, seems reasonable.

Buildbot failures look unrelated. Merging.
