### PR TITLE
gh-125398: Convert paths in venv activate script when using Git Bash under Windows

### LINKED ISSUE #125398: The virtualenv activate script does not correctly detect the Windows Git Bash shell
# Bug report

### Bug description:

When using the virtualenv activate script in Git Bash for Windows, the environment is not correctly detected and paths are not converted.

This results in `$PATH` being set to something like `D:\a\github-actions-shells\github-actions-shells\venv/Scripts:...`, instead of `/d/a/github-actions-shells/github-actions-shells/venv/Scripts`.

Prior to https://github.com/python/cpython/pull/112508, the detection used `$OSTYPE`, which reports `msys` in Git Bash for Windows, however `uname` returns `MINGW...`.

This is a regression in Python 3.13.0

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

### Linked PRs
* gh-125399
* gh-125733

### PR DESCRIPTION
**Pull request by julienp**
With https://github.com/python/cpython/pull/112508 the check to convert paths when running on Windows was changed from using the non-posix environment variable `$OSTYPE` to using `uname` instead.

However this missed the fact that when running under Git Bash on Windows, uname reports `MINGW*` (`$OSTYPE` is still `msys`).

This results in `$PATH` being set to something like `D:\a\github-actions-shells\github-actions-shells\venv/Scripts:…`, instead of `/d/a/github-actions-shells/github-actions-shells/venv/Scripts`.

Notably, the Git Bash is the bash shell that’s used for GitHub Actions Windows runners, and ships with VSCode.

Fixes https://github.com/python/cpython/issues/125398

* Issue: gh-125398

### CODE REVIEW

File: Misc/NEWS.d/next/Library/2024-10-13-15-04-58.gh-issue-125398.UW7Ndv.rst [hunk 1]
```diff
@@ -0,0 +1 @@
+Fix the conversion of the VIRTUAL_ENV path in the activate script in :mod:`venv` when running in Git Bash for Windows.
```
Comment (rruuaanng) [inline Misc/NEWS.d/next/Library/2024-10-13-15-04-58.gh-issue-125398.UW7Ndv.rst]: Recommend used this.
```suggestion
Fix the conversion of the ``VIRTUAL_ENV`` path in the activate script in :mod:`venv` when running in Git Bash for Windows.
```

Comment (erlend-aasland) [reply Misc/NEWS.d/next/Library/2024-10-13-15-04-58.gh-issue-125398.UW7Ndv.rst]: Actually, the correct markup would be `:envvar:` :) See also the relevant parts of [the devguide](https://devguide.python.org/documentation/markup/).

File: Misc/NEWS.d/next/Library/2024-10-13-15-04-58.gh-issue-125398.UW7Ndv.rst [hunk 2]
```diff
@@ -0,0 +1 @@
+Fix the conversion of the ``VIRTUAL_ENV`` path in the activate script in :mod:`venv` when running in Git Bash for Windows.
```
Comment (vsajip) [inline Misc/NEWS.d/next/Library/2024-10-13-15-04-58.gh-issue-125398.UW7Ndv.rst]:
```suggestion
Fix the conversion of the :envvar:`VIRTUAL_ENV` path in the activate script in :mod:`venv` when running in Git Bash for Windows.
```

File: Misc/NEWS.d/next/Library/2024-10-13-15-04-58.gh-issue-125398.UW7Ndv.rst (hunk 1 above)
Comment (vsajip) [reply Misc/NEWS.d/next/Library/2024-10-13-15-04-58.gh-issue-125398.UW7Ndv.rst]: I edited the PR to use the `:envvar:` role, but it seems to fail documentation linting:
```
WARNING: 'envvar' reference target not found: VIRTUAL_ENV [ref.envvar]
```
Perhaps a nits file needs updating? @erlend-aasland, any ideas?

Comment (erlend-aasland) [reply Misc/NEWS.d/next/Library/2024-10-13-15-04-58.gh-issue-125398.UW7Ndv.rst]: You can use ``` :envvar:`!VIRTUAL_ENV` ``` :)

Comment (erlend-aasland) [reply Misc/NEWS.d/next/Library/2024-10-13-15-04-58.gh-issue-125398.UW7Ndv.rst]: Ideally though, `VIRTUAL_ENV` should be documented in `Doc/library/venv.rst`.

Comment (zooba) [reply Misc/NEWS.d/next/Library/2024-10-13-15-04-58.gh-issue-125398.UW7Ndv.rst]: Pretty sure `VIRTUAL_ENV` is undocumented on purpose. It's `sys.argv[0]` that determines whether you're in a venv or not (and if `argv[0]` is a relative path, it's resolved using `PATH`, which makes that the other relevant environment variable).

Comment (erlend-aasland) [reply Misc/NEWS.d/next/Library/2024-10-13-15-04-58.gh-issue-125398.UW7Ndv.rst]: Ah, but it's not _undocumented_; it is mentioned multiple places in our docs, _but_ it lacks a "formal" `.. envvar::` definition ;)

File: Misc/NEWS.d/next/Library/2024-10-13-15-04-58.gh-issue-125398.UW7Ndv.rst [hunk 3]
```diff
@@ -0,0 +1 @@
+Fix the conversion of the :envvar:`VIRTUAL_ENV` path in the activate script in :mod:`venv` when running in Git Bash for Windows.
```
Comment (vsajip) [inline Misc/NEWS.d/next/Library/2024-10-13-15-04-58.gh-issue-125398.UW7Ndv.rst]:
```suggestion
Fix the conversion of the :envvar:`!VIRTUAL_ENV` path in the activate script in :mod:`venv` when running in Git Bash for Windows.
```

File: Misc/NEWS.d/next/Library/2024-10-13-15-04-58.gh-issue-125398.UW7Ndv.rst (hunk 1 above)
Comment (zooba) [reply Misc/NEWS.d/next/Library/2024-10-13-15-04-58.gh-issue-125398.UW7Ndv.rst]: Looking at the documentation in the venv module for it, I'd be okay with adding the reference location to there (in short, it says "don't use or rely on this variable, but it might be set")

Comment (vsajip) [reply Misc/NEWS.d/next/Library/2024-10-13-15-04-58.gh-issue-125398.UW7Ndv.rst]: OK, I'm minded to commit this as it is currently (with `!VIRTUAL_ENV`), and that `envvar` definition can be added in a subsequent PR. Any objections?

**Comment by julienp** [comment]
Thank you for merging this! I see the bot comment about the backport to 3.12 failing. I think that's expected, as this was a regression in 3.13.0, and the [change that introduced the regression](https://github.com/python/cpython/pull/112508) was not applied to 3.12.
