### PR TITLE
gh-141982: Fix pdb can't set breakpoints on async functions

### LINKED ISSUE #141982: Support `pdb` breakpoints on `async` functions
# Bug report

### Bug description:

I found that while debugging with pdb you currently cannot set a breakpoint on an async function. Reproducer:
```python3
import asyncio

async def main():
    print(f"Hello")
    await asyncio.sleep(1)
    print(f"World!")

asyncio.run(main())
```

If you run pdb and try to set a breakpoint on main you get:

```
λ › ./python -m pdb main.py                                                                                                                                          
> /cpython/main.py(1)<module>()
-> import asyncio
(Pdb) break main
*** The specified object 'main' is not a function or was not found along sys.path.
(Pdb) quit
```
This happens because the regular expression used by `find_function` does not match async functions: https://github.com/python/cpython/blob/2ff8608b4da33f667960e5099a1a442197acaea4/Lib/pdb.py#L132-L133

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-141983

### PR DESCRIPTION
**Pull request by cocolato**
Fix: https://github.com/python/cpython/issues/141982

I found that while debugging with pdb you currently cannot set a breakpoint on an async function. Reproducer:
```python3
import asyncio

async def main():
    print(f"Hello")
    await asyncio.sleep(1)
    print(f"World!")

asyncio.run(main())
```

If you run pdb and try to set a breakpoint on main you get:

```
λ › ./python -m pdb main.py                                                                                                                                          
> /cpython/main.py(1)<module>()
-> import asyncio
(Pdb) break main
*** The specified object 'main' is not a function or was not found along sys.path.
(Pdb) quit
```
This happens because the regular expression used by find_function does not match async functions: https://github.com/python/cpython/blob/2ff8608b4da33f667960e5099a1a442197acaea4/Lib/pdb.py#L132-L133

After the fix:

```
λ › ./python -m pdb main.py                                                                                                                                          
> /cpython/main.py(1)<module>()
-> import asyncio
(Pdb) break main
Breakpoint 1 at /cpython/main.py:4
(Pdb) continue
> /cpython/main.py(4)main()
-> print(f"Hello")
(Pdb) quit
```
Now we can set breakpoints on async functions as expected.

* Issue: gh-141982

### CODE REVIEW

File: Misc/NEWS.d/next/Library/2025-11-26-15-36-55.gh-issue-141982.-8yHA3.rst [hunk 1]
```diff
@@ -0,0 +1 @@
+:mod:`pdb` console can now set breakpoints on async functions.
```
Comment (aisk) [inline Misc/NEWS.d/next/Library/2025-11-26-15-36-55.gh-issue-141982.-8yHA3.rst]: Nitpick: pdb is a debugger, not a console:
```suggestion
:mod:`pdb` can now set breakpoints on async functions.
```

**Comment by aisk** [comment]
I'm not familiar with the `pdb` module, but I think that even after this change, functions defined within an if branch or other indented blocks still can't be found by this function. Perhaps we could use another approach, like walking the AST in the `find_function` to handle this situation.

For now, however, I think it's acceptable to just handle the async function case described in the original issue because this is the most common situation.

**Review by aisk — APPROVED** [review]

**Review by gaogaotiantian — COMMENTED** [review]
Let's optimize the test case a bit. So we want a test case that is accurate and comprehensive, while being concise. The sleep and `World` part did not do anything - we don't need them.

Checking `Hello` is not the best practice because there could be many ways that `Hello` appears in stdout - it's part of the source code and you are printing it. Say the breakpoint is never set, you'd still have `Hello` in stdout. 

One way is to check `World` is not printed out - which could be an indicator that a breakpoint is set. For `Hello` I think we need to check it in a better way.

**Comment by cocolato** [comment]
Thanks for review, @gaogaotiantian ! Do you think the current tests are sufficient?

File: Lib/test/test_pdb.py [hunk 2]
```diff
@@ -4587,6 +4587,33 @@ def bar():
...
+        """
+        commands = """
+            break main
+            break do_something
+            continue
+            continue
+            quit
+        """
+        stdout, stderr = self.run_pdb_script(script, commands)
+        print(stdout)
```
Comment (yihong0618) [inline Lib/test/test_pdb.py]: better print in the scripts if we need a print I think

Comment (cocolato) [reply Lib/test/test_pdb.py]: Sorry, this was code I used for local debugging. I will remove it.

File: Lib/test/test_pdb.py [hunk 3]
```diff
@@ -4587,6 +4587,32 @@ def bar():
             ]))
             self.assertIn('break in bar', stdout)
 
+    def test_async_break(self):
+        script = """
+            import asyncio
+
+            async def do_something():
+                test_str = "second break"
```
Comment (gaogaotiantian) [inline Lib/test/test_pdb.py]: The two breaks on two async functions use the exact same mechanism. You don't need to test it twice. Just make the test simple and easy to understand.

File: Lib/test/test_pdb.py [hunk 4]
```diff
@@ -4587,6 +4587,24 @@ def bar():
             ]))
             self.assertIn('break in bar', stdout)
 
+    def test_async_break(self):
+        script = """
+            import asyncio
+
+            async def main():
+                test_str = "test break"
```
Comment (gaogaotiantian) [inline Lib/test/test_pdb.py]: Let's just change this line to `pass` and check that.

Comment (cocolato) [reply Lib/test/test_pdb.py]: Thank you again for the reminder. I will be more careful about this in the future.

**Review by gaogaotiantian — APPROVED** [review]

**Comment by gaogaotiantian** [comment]
Thank you for fixing this.
