### PR TITLE
gh-90871: fix connection backlog offset in asyncio

### LINKED ISSUE #90871: asyncio.create_unix_server has an off-by-one error concerning the backlog parameter
BPO | [46715](https://bugs.python.org/issue46715)
--- | :---
Nosy | @asvetlov, @1st1, @jnsnow
Files | <li>[issue.patch](https://bugs.python.org/file50618/issue.patch "Uploaded as text/plain at 2022-02-10.21:24:35 by @jnsnow")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-02-10.21:24:35.963>
labels = ['type-bug', '3.8', '3.9', '3.10', '3.11', '3.7', 'expert-asyncio']
title = 'asyncio.create_unix_server has an off-by-one error concerning the backlog parameter'
updated_at = <Date 2022-02-10.21:24:35.963>
user = 'https://github.com/jnsnow'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-10.21:24:35.963>
actor = 'jnsnow'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2022-02-10.21:24:35.963>
creator = 'jnsnow'
dependencies = []
files = ['50618']
hgrepos = []
issue_num = 46715
keywords = ['patch']
message_count = 1.0
messages = ['413025']
nosy_count = 3.0
nosy_names = ['asvetlov', 'yselivanov', 'jnsnow']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46715'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-134392
* gh-134421
* gh-142739

### PR DESCRIPTION
**Pull request by ChristianHrs**
* Issue: gh-90871

### CODE REVIEW

File: Misc/NEWS.d/next/Library/2025-05-20-21-45-58.gh-issue-90871.Gkvtp6.rst [hunk 1]
```diff
@@ -0,0 +1,2 @@
+Fixed an off by one error concerning the backlog parameter in
+asyncio.create_unix_server. Contributed by Christian Harries.
```
Comment (kumaraditya303) [inline Misc/NEWS.d/next/Library/2025-05-20-21-45-58.gh-issue-90871.Gkvtp6.rst]:
```suggestion
:meth:`~asyncio.loop.create_unix_server`. Contributed by Christian Harries.
```

**Review by kumaraditya303 — APPROVED** [review]
As per FreeBSD docs and https://www.man7.org/linux/man-pages/man2/listen.2.html about backlog, this is correct.

**Comment by ambv** [comment]
To backport to 3.13, we might consider backporting #127532 first.

**Comment by serhiy-storchaka** [comment]
Reminder about backporting. @ChristianHrs @ambv
