### PR TITLE
gh-129248: Filter out the iOS log prefix from testbed runner output.

### LINKED ISSUE #129248: iOS buildbot failure comments don't contain failure details anymore
Specificially, they don't contain:
* The names of the failed tests
* The tracebacks

It looks like this changed in December 2024, probably because the test script was updated to add a prefix to every log line. The relevant regexes are [here](https://github.com/python/buildmaster-config/blob/main/master/custom/testsuite_utils.py).

Before:
* https://github.com/python/cpython/pull/122992#issuecomment-2287532747
* https://github.com/python/cpython/pull/124646#issuecomment-2378299107

After:
* https://github.com/python/cpython/pull/128925#issuecomment-2598703448
* https://github.com/python/cpython/pull/127412#issuecomment-2546494964

@freakboy3742: FYI

### Linked PRs
* gh-129252
* gh-129283

### PR DESCRIPTION
**Pull request by freakboy3742**
Modifies the iOS test runner to strip out the log prefix inserted by the Apple system log.

iOS test logs are gathered by streaming the Apple System log looking for log items from the test process. These log prefixes look like:
```
2025-01-17 16:14:29.090 Df iOSTestbed[23987:1fd393b4] (Python) ...
2025-01-17 16:14:29.090 E  iOSTestbed[23987:1fd393b4] (Python) ...
```

The existence of these prefixes was preventing the buildbots from parsing log output to discover test failures. Since the prefix doesn't actually help diagnose issues with the Python test suite, this PR strips out the prefix. This matches what the Android test runner does with ADB log prefixes. It *doesn't* strip the prefix from the iOS setup/teardown code (the ObjC code that instantiates the XUnit test case, which *might* be helpful in a diagnostic context, but won't interfere with the Python operation

The acid test for this fix is a test failing and being correctly parsed by the buildbot; that's a little difficult to manufacture, though. For review purposes, you can inspect the test log for the buildbot to see that it matches the test output from other platforms; at which point the buildbot log parser should work as it does on any other platform.

Fixes #129248.

* Issue: gh-129248

### CODE REVIEW

**Comment by freakboy3742** [comment]
!buildbot iOS

File: Misc/NEWS.d/next/Tools-Demos/2025-01-24-14-49-40.gh-issue-129248.JAapG2.rst [hunk 1]
```diff
@@ -0,0 +1,2 @@
+The iOS test runner now strips the log prefix from each line output by the
```
Comment (StanFromIreland) [inline Misc/NEWS.d/next/Tools-Demos/2025-01-24-14-49-40.gh-issue-129248.JAapG2.rst:1]:
```suggestion
The iOS test runner now strips the log prefix from each line of output by the
```

Comment (StanFromIreland) [reply Misc/NEWS.d/next/Tools-Demos/2025-01-24-14-49-40.gh-issue-129248.JAapG2.rst:1]: Minor typo/clarification

Comment (freakboy3742) [reply Misc/NEWS.d/next/Tools-Demos/2025-01-24-14-49-40.gh-issue-129248.JAapG2.rst:1]: I'm not convinced that correction is correct - "each line output by the program" is grammatically valid; "each line of output by the program" is not. "each line of output *of* the program" might be; but it's not any clearer IMHO. Besides, this is a draft release note that will be edited by the release manager, so if they disagree, they can change it when it is collated.

**Review by ned-deily — APPROVED** [review]
LGTM
