### PR TITLE
gh-93442: Make C++ version of _Py_CAST work with 0/NULL.

### LINKED ISSUE #93442: PyTuple_SET_ITEM fails to compile in C++ source
- CPython versions tested on: 3.11b3
- Operating system and architecture: Debian Linux, GCC 10.2.1-6

The kiwisolver extension doesn't compile with beta 3.  The error is:
```
/usr/local/python3.11.0b3/include/python3.11/pyport.h:47:24: error: invalid ‘static_cast’ from type ‘int’ to type ‘_object*’
   47 |                 return static_cast<type>(const_cast<expr_type &>(expr));
      |                        ^~~~~
```

This seems to be an issue with the new inline functions for things that used to be macros.  E.g. PyTuple_SET_ITEM.  The C++ code triggering the issue is:
```
--- a/py/src/symbolics.h
+++ b/py/src/symbolics.h
@@ -123,7 +123,7 @@ PyObject* BinaryMul::operator()( Expression* first, double second )
                return 0;
        Py_ssize_t end = PyTuple_GET_SIZE( first->terms );
        for( Py_ssize_t i = 0; i < end; ++i )  // memset 0 for safe error return
-               PyTuple_SET_ITEM( terms.get(), i, 0 );
+               PyTuple_SetItem( terms.get(), i, 0 );
        for( Py_ssize_t i = 0; i < end; ++i )
        {
                PyObject* item = PyTuple_GET_ITEM( first->terms, i );
```

Replacing the macro with the function version seems to allow the extension to compile.

This seems related to https://github.com/python/cpython/issues/92898

### PR DESCRIPTION
**Pull request by nascheme**
Add C++ overloads for _Py_CAST_impl() to handle 0/NULL.  This will allow
C++ extensions that pass 0 or NULL to macros using _Py_CAST() to
continue to compile.  Without this, you get an error like:

    invalid ‘static_cast’ from type ‘int’ to type ‘_object*’

The modern way to use a NULL value in C++ is to use nullptr.  However,
we want to not break extensions that do things the old way.

Co-authored-by: serge-sans-paille

### CODE REVIEW

File: Lib/test/_testcppext.cpp [hunk 1]
```diff
@@ -74,6 +74,10 @@ test_api_casts(PyObject *Py_UNUSED(module), PyObject *Py_UNUSED(args))
     Py_INCREF(strong_ref);
     Py_DECREF(strong_ref);
 
+    // gh-93442: Pass 0 as NULL for PyObject*
+    Py_XINCREF(0);
+    Py_XDECREF(0);
+
```
Comment (corona10) [inline Lib/test/_testcppext.cpp:80]: nit
```suggestion
    Py_XINCREF(nullptr);
    Py_XDECREF(nullptr);
    
    Py_XINCREF(NULL);
    Py_XDECREF(NULL);
```

**Review by corona10 — APPROVED** [review]

**Comment by vstinner** [comment]
Since there is a _Py_CAST_impl() implementation for nullptr, it would be nice to add a test on nullptr.

What is the purpose of ``_Py_CAST_impl(long int ptr)``? Is it to pass a pointer as a number? Or is it to pass ``0L`` or ``(long)0``? Who uses such code?

**Comment by nascheme** [comment]
I added a test for `nullptr`.  The reason for the `int` overloads is because the C++ template type is created from the expression, not the type it is being coerced to.  So, `_Py_CAST(0)` or `_Py_CAST(NULL)` expands the template with `long int` or similar as the type.  I think the `long int` is due to what type C++ uses for a literal `0` value.

I'm a bit scared about how complicated `_Py_CAST_impl()` has become.  AFAICT, it only exists to avoid a gcc warning.  It's nice to avoid the warning but my concern is if there are more issues and the long term maintenance of that "magic" code.  Since it seems to work, I guess we should keep it.

**Comment by vstinner** [comment]
> I'm a bit scared about how complicated _Py_CAST_impl() has become. AFAICT, it only exists to avoid a gcc warning.

It's more about generating "correct" code for a very tricky operation: convert any operation to ``PyObject*``. With PEP 670, the limited C API version 3.11 simply removes the cast: you must pass ``PyOject*`` and only ``PyObject*``. The complexity of the C++ implementation is more the cost of the past, keeping backward compatibility without emiting new C++ compiler warnings.

But you're right that my initial concern was fixing **new** C++ compiler warnings: to fix a **regression**. See https://github.com/python/cpython/issues/91320#issuecomment-1093947454 for the rationale and why it's a regression.

**Comment by vstinner** [comment]
> I added a test for nullptr

Ah right, commit 713eb184b50f2b8b138fb01187ee32fa29a815c9: thanks!

**Comment by vstinner** [comment]
test_cppext is new in Python 3.11! Previously, there was simply zero test on the C++ compatibility of the Python **C** API ;-)
