### PR TITLE
gh-106739: Add `rtype_cache` to `warnings.warn` message when leaked objects found

### LINKED ISSUE #106739: Add `rtype_cache` to `warnings.warn` message when leaked objects found
# Feature or enhancement

Add the `rtype_cache` (which is a `set` that includes all leaked objects of a particular type) to the `warnings.warn` message in `Lib/multiprocessing/resource_tracker.py` when any leaked objects are found to make debugging easier:
https://github.com/python/cpython/blob/490295d651d04ec3b3eff2a2cda7501191bad78a/Lib/multiprocessing/resource_tracker.py#L224-L226

# Pitch

When the `resource_tracker` module (`Lib/multiprocessing/resource_tracker.py`) finds leaked objects, the `finally` block in the `main` function includes the type of leaked objects and the number of leaked objects, but does not actually include the objects that are leaked. Adding the `set` of `rtype_cache` to the `warnings.warn` message will make debugging much more useful, as the names of the leaked objects could help more quickly identify what was leaked and/or why the leaked object was not properly cleaned up.

The permalink attached above links directly to the relevant code as it is currently implemented, but I'm adding it again below with some surrounding code for reference here:
```
    finally:
        # all processes have terminated; cleanup any remaining resources
        for rtype, rtype_cache in cache.items():
            if rtype_cache:
                try:
                    warnings.warn('resource_tracker: There appear to be %d '
                                  'leaked %s objects to clean up at shutdown' %
                                  (len(rtype_cache), rtype))
                except Exception:
                    pass
```

# Previous discussion

A recent example of an issue where the additional context would have been useful is https://github.com/python/cpython/issues/104090, in which the current warning message is `/workspace/cpython/Lib/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown`.

### Linked PRs
* gh-106740

### PR DESCRIPTION
**Pull request by shailshouryya**
Closes Issue #106739: [Add rtype_cache to warnings.warn message when leaked objects found](https://github.com/python/cpython/issues/106739)

See message in commit a54a5fb84dba76aa42430addaa8914be2ac1da72 for the updated warning message.

* Issue: gh-106739

### CODE REVIEW

**Comment by shailshouryya** [comment]
I'm not sure what the corresponding news entry should be for this in `Misc/NEWS` - would this go under `Core and Builtins`?

Or should we apply the `skip news` label here? I can't seem to modify labels here, though, so someone else might need to add the `skip news` label for me in that case. (I'm guessing this is because I don't have high enough permissions to modify labels here)

**Comment by shailshouryya** [comment]
@iritkatriel tagging you here since I saw you were also involved in #104090 and the pull requests associated with that issue.

Let me know what you think of this when you get the chance! 🤓 (Or let me know if I should tag someone else instead)

**Comment by iritkatriel** [comment]
CC @pitrou .

File: Misc/NEWS.d/next/Library/2023-07-20-06-00-35.gh-issue-106739.W1hygr.rst [hunk 1]
```diff
@@ -0,0 +1 @@
+Adds the `rtype_cache` `set` to the `warnings.warn` message (as an addition to the type of leaked objects and the number of leaked objects already included in the `warnings.warn` message) to make debugging leaked objects easier when the `resource_tracker` module (`Lib/multiprocessing/resource_tracker.py`) finds leaked objects. Including the names of the leaked objects will help more quickly identify what was leaked and/or why the leaked object was not properly cleaned up.
```
Comment (pitrou) [inline Misc/NEWS.d/next/Library/2023-07-20-06-00-35.gh-issue-106739.W1hygr.rst]:
```suggestion
Add the ``rtype_cache`` to the warning message (as an addition to the type of leaked objects and the number of leaked objects already included in the message) to make debugging leaked objects easier when the multiprocessing resource tracker process finds leaked objects at shutdown. This helps more quickly identify what was leaked and/or why the leaked object was not properly cleaned up.
```

**Comment by pitrou** [comment]
@shailshouryya Can you show an example of the improved warning message?

File: Lib/multiprocessing/resource_tracker.py [hunk 2]
```diff
@@ -222,8 +222,8 @@ def main(fd):
             if rtype_cache:
                 try:
                     warnings.warn('resource_tracker: There appear to be %d '
-                                  'leaked %s objects to clean up at shutdown' %
-                                  (len(rtype_cache), rtype))
+                                  'leaked %s objects to clean up at shutdown: %s' %
+                                  (len(rtype_cache), rtype, rtype_cache))
```
Comment (pitrou) [inline Lib/multiprocessing/resource_tracker.py]: Not mandatory, but you could perhaps update this to use a f-string.

File: Misc/NEWS.d/next/Library/2023-07-20-06-00-35.gh-issue-106739.W1hygr.rst (hunk 1 above)
Comment (shailshouryya) [reply Misc/NEWS.d/next/Library/2023-07-20-06-00-35.gh-issue-106739.W1hygr.rst]: I updated the entry in commit 16ec55739400259a6b02b9a4553d1217d1fc56d1. Thanks for catching the incorrect formatting for `rtype_cache`! (I used markdown formatting and missed the double backticks)

File: Lib/multiprocessing/resource_tracker.py (hunk 2 above)
Comment (shailshouryya) [reply Lib/multiprocessing/resource_tracker.py]: Sure thing, added in commit 819915e1d2ebe9d9069fd72a8675498bc1873a80 (and fixed the formatting in commit 1611dd4d8c3744e14bc72b7b7b53eef51b6bde96).

I kept the warning split out into multiple lines since keeping the entire message on 1 line resulted in 156 characters on a line, which seems a bit long. I couldn't find a formal formatting guide for multiline f-strings, so I currently have it formatted as
```
                    warnings.warn(
                        f'resource_tracker: There appear to be {len(rtype_cache)} '
                        f'leaked {rtype} objects to clean up at shutdown: {rtype_cache}'
                    )
```
but I wasn't sure if I should go with the following instead:
```
                    warnings.warn(f'resource_tracker: There appear to be {len(rtype_cache)} '
                                  f'leaked {rtype} objects to clean up at shutdown: {rtype_cache}')
```

Is there a preference for these kinds of scenarios?

**Comment by shailshouryya** [comment]
> Can you show an example of the improved warning message?

Sure! Prior to these changes, the warning message looked like

`/Users/username/cpython/Lib/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown`

and after these changes, the warning message looks like

`/Users/username/cpython/Lib/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown: {'/mp-x7qw67gg', '/mp-bwptfpzm', '/mp-evehw7gr', '/mp-qxl5kdci', '/mp-a90ggt9g', '/mp-pi9c59yl'}`

I got these outputs by running `./python.exe -m test test_concurrent_futures --verbose` on this branch before these changes and after these changes.

<details>
<summary><strong>Full command to rebuild and test (on macOS)</strong></summary>

<pre>
GDBM_CFLAGS="-I$(dirname $(dirname $(which port)))/include" \
GDBM_LIBS="-L$(dirname $(dirname $(which port)))/lib -lgdbm" \
./configure --with-pydebug  && make regen-global-objects && make -s -j3 \
&& ./python.exe -m test test_concurrent_futures --verbose
</pre>

</details>

File: Lib/multiprocessing/resource_tracker.py (hunk 2 above)
Comment (pitrou) [reply Lib/multiprocessing/resource_tracker.py]: I would go with the former in this case, to limit the indentation amount.

Comment (shailshouryya) [reply Lib/multiprocessing/resource_tracker.py]: Okay, sounds good - in that case, this part should be good to go!

**Review by pitrou — APPROVED** [review]
+1, thank you @shailshouryya
