### PR TITLE
gh-104955: Fix __release_buffer__ signature

### LINKED ISSUE #104955: Signature for `__release_buffer__` is incorrect
Currently the signature for PEP-688's `__release_buffer__` method is as follows:

```
>>> bytearray.__release_buffer__.__text_signature__
'($self, /)'
```

This is incorrect; the method takes a single argument that according to the PEP should be called `buffer`.

### Linked PRs
* gh-104956
* gh-104973

### PR DESCRIPTION
**Pull request by JelleZijlstra**
Fixes #104955

* Issue: gh-104955

### CODE REVIEW

**Review by kumaraditya303 — APPROVED** [review]

File: Misc/NEWS.d/next/Core and Builtins/2023-05-25-21-40-39.gh-issue-104955.LZx7jf.rst [hunk 1]
```diff
@@ -0,0 +1,2 @@
+Fix signature for the new :meth:`__release_buffer__` slot. Patch by Jelle
```
Comment (kumaraditya303) [inline Misc/NEWS.d/next/Core and Builtins/2023-05-25-21-40-39.gh-issue-104955.LZx7jf.rst]:
```suggestion
Fix signature for the new :meth:`~object.__release_buffer__` slot. Patch by Jelle
```

I don't know if this works, just guessing.

Comment (JelleZijlstra) [reply Misc/NEWS.d/next/Core and Builtins/2023-05-25-21-40-39.gh-issue-104955.LZx7jf.rst]: Seems like it should given this:

```
Doc/reference/datamodel.rst:.. method:: object.__release_buffer__(self, buffer)
```
