### PR TITLE
gh-105539: Emit ResourceWarning if sqlite3 database is not closed explicitly

### LINKED ISSUE #105539: Emit resource warning if sqlite3 fails to close the database
_See https://github.com/python/cpython/issues/103837#issuecomment-1541808307 and https://github.com/python/cpython/issues/103837#issuecomment-1543936079_:

EAA:
> I still think we should consider changing the underlying API so we can emit a resource warning if close failed.

VS:
> IMO sqlite3 should be modified to emit a ResourceWarning.
>
> Currently, no ResourceWarning is emitted when a connection is not closed explicitly:

### Linked PRs
* gh-108015
* gh-108017
* gh-108360
* gh-108565

### PR DESCRIPTION
**Pull request by erlend-aasland**
* Issue: gh-105539

----
:books: Documentation preview :books:: https://cpython-previews--108015.org.readthedocs.build/

### CODE REVIEW

**Comment by erlend-aasland** [comment]
@vstinner: with this PR, sqlite3 emits a ResourceWarning if `close()` was not called explicitly on a `sqlite3.Connection` object before it is deleted. I did not (yet) add a resource warning for the case where close fails (future enhancement).

As you can see from the test changes, we've been pretty lax with resource handling in the sqlite3 test suite 😆

**Review by vstinner — COMMENTED** [review]
Can you please try to extract changes on tests and merge these fixes first? I would make this PR easier to review.

**Comment by erlend-aasland** [comment]
> Can you please try to extract changes on tests and merge these fixes first? I would make this PR easier to review.

Done: see gh-108017

**Comment by erlend-aasland** [comment]
cc. @felixxm

**Comment by erlend-aasland** [comment]
cc. @simonw

File: Modules/_sqlite/connection.c [hunk 1]
```diff
@@ -440,40 +442,56 @@ remove_callbacks(sqlite3 *db)
...
-                remove_callbacks(self->db);
-            }
-            (void)connection_exec_stmt(self, "ROLLBACK");
+    assert(self->db);
+    if (self->autocommit == AUTOCOMMIT_DISABLED &&
+        !sqlite3_get_autocommit(self->db))
+    {
+        /* If close is implicitly called as a result of interpreter
+         * tear-down, we must not call back into Python. */
+        if (_Py_IsInterpreterFinalizing(PyInterpreterState_Get())) {
```
Comment (vstinner) [inline Modules/_sqlite/connection.c]: IMO you should move this logic into the caller which has the knowledge if the function was called explicitly or by the finalizer.

For example, add a "autocommit_remove_callbacks" parameter which would be 0 in the close() method, and set to _Py_IsInterpreterFinalizing(...) by the finalize function.

File: Modules/_sqlite/connection.c [hunk 2]
```diff
@@ -440,40 +442,56 @@ remove_callbacks(sqlite3 *db)
...
+            remove_callbacks(self->db);
         }
+        (void)connection_exec_stmt(self, "ROLLBACK");
```
Comment (vstinner) [inline Modules/_sqlite/connection.c]: Ignoring the exception here is a bug.

connection_finalize() clears any exception with PyErr_SetRaisedException(), but pysqlite_connection_close_impl() must not ignore silently error, since here we are talking about a raised Python exception! The function must report if an exception was raised. Then the caller is free to ignore it or not.

I suggest to continue ignoring it in finalize, but then write a separated PR to *log* the "unraisable exception".

File: Modules/_sqlite/connection.c [hunk 3]
```diff
@@ -440,40 +442,56 @@ remove_callbacks(sqlite3 *db)
...
+static void
+connection_finalize(PyObject *self)
+{
+    pysqlite_Connection *con = (pysqlite_Connection *)self;
+    PyObject *exc = PyErr_GetRaisedException();
+    /* Clean up if user has not called .close() explicitly. */
+    if (con->db) {
+        if (PyErr_ResourceWarning(self, 1, "unclosed %R", self)) {
+            /* Spurious errors can appear at shutdown */
+            if (PyErr_ExceptionMatches(PyExc_Warning)) {
```
Comment (vstinner) [inline Modules/_sqlite/connection.c:499]: Why only log Warning exception? Is it a good thing to call connection_close() with an exception set?

File: Modules/_sqlite/connection.c [hunk 4]
```diff
@@ -440,40 +442,56 @@ remove_callbacks(sqlite3 *db)
...
+                PyErr_WriteUnraisable(self);
```
Comment (vstinner) [inline Modules/_sqlite/connection.c:500]: This log doesn't give much context about why an exception is logged here. I created issue #108082 to discuss this problem.

File: Modules/_sqlite/connection.c (hunk 2 above)
Comment (erlend-aasland) [reply Modules/_sqlite/connection.c]: Ouch! And there is at least one more case where the exception is ignored. Let's fix those in a separate PR.

File: Modules/_sqlite/connection.c (hunk 3 above)
Comment (erlend-aasland) [reply Modules/_sqlite/connection.c:499]: I followed the pattern from other places in the code base which uses this approach :)

Comment (erlend-aasland) [reply Modules/_sqlite/connection.c:499]: https://github.com/python/cpython/blob/2da67a5789a9247ae6611185bf786b697aa04fbe/Modules/posixmodule.c#L15234-L15256

and

https://github.com/python/cpython/blob/2da67a5789a9247ae6611185bf786b697aa04fbe/Modules/socketmodule.c#L5223-L5253

Comment (erlend-aasland) [reply Modules/_sqlite/connection.c:499]: Why not simply call `PyErr_WriteUnraisable` if `PyErr_ResourceWarning` fails? I don't get it.

File: Modules/_sqlite/connection.c (hunk 1 above)
Comment (erlend-aasland) [reply Modules/_sqlite/connection.c]: Hm, yeah that may be nicer. I'll try that.

File: Modules/_sqlite/connection.c (hunk 2 above)
Comment (erlend-aasland) [reply Modules/_sqlite/connection.c]: See gh-108084

File: Modules/_sqlite/connection.c (hunk 1 above)
Comment (erlend-aasland) [reply Modules/_sqlite/connection.c]: I think that played out nice. Have a look in 8ebc8a73196a0715ed6b629d0e9721384d1e660f; thanks for the tip.

File: Modules/_sqlite/connection.c (hunk 4 above)
Comment (erlend-aasland) [reply Modules/_sqlite/connection.c:500]: For the user, the current warning ends up looking like this:

> ResourceWarning: unclosed <sqlite3.Connection object at 0x1052589e0>

I guess we could use a more informative warning message. I'll think of something.

File: Modules/_sqlite/connection.c (hunk 3 above)
Comment (vstinner) [reply Modules/_sqlite/connection.c:499]: Maybe these two files should be fixed to remove ExceptionMatches() call?

File: Modules/_sqlite/connection.c (hunk 4 above)
Comment (vstinner) [reply Modules/_sqlite/connection.c:500]: Oh ok, maybe it's enough.

Comment (erlend-aasland) [reply Modules/_sqlite/connection.c:500]: Perhaps _"unclosed database in <sqlite3.Connection object at ...>"_

File: Modules/_sqlite/connection.c (hunk 3 above)
Comment (erlend-aasland) [reply Modules/_sqlite/connection.c:499]: I suspect there is a reason for those guards; I'd like to find out that first.

File: Modules/_sqlite/connection.c (hunk 4 above)
Comment (erlend-aasland) [reply Modules/_sqlite/connection.c:500]: I applied my suggestion in 980d4d2a446db058434bce529fe77efde59618f3

**Review by vstinner — APPROVED** [review]
LGTM. This change does what it says. There is room for enhancement, but it can be addressed separately (@erlend-aasland already creates issues to track remaining points).

**Comment by erlend-aasland** [comment]
Thanks for the review, Victor! I asked about https://github.com/python/cpython/pull/108015#discussion_r1297089560 on the core dev Discord. If it is an issue, we can fix it later.

**Comment by erlend-aasland** [comment]
I'll wait with merging until I've heard from @simonw and @felixxm, in case they've got opinions about this.

File: Modules/_sqlite/connection.c (hunk 3 above)
Comment (erlend-aasland) [reply Modules/_sqlite/connection.c:499]: They were added in respectively ffe96ae10be8a3117fa18c35034fcfc45c3cf7b7 and e033e06db077d5abcb4bc3729d03f8a4a09b2486 by Serhiy and Antoine.

Comment (erlend-aasland) [reply Modules/_sqlite/connection.c:499]: Let's handle this post merge.

**Comment by felixxm** [comment]
> I'll wait with merging until I've heard from @simonw and @felixxm, in case they've got opinions about this.

Thanks for pinging me. I'm going to check it out next week, after my holidays :beach_umbrella:

**Comment by felixxm** [comment]
> > I'll wait with merging until I've heard from @simonw and @felixxm, in case they've got opinions about this.
> 
> Thanks for pinging me. I'm going to check it out next week, after my holidays 🏖️

This change doesn't break anything important in Django :+1: (at the first glance). I've started fixing `ResourceWarning`s in our tests, check out https://github.com/django/django/pull/17178.

**Comment by erlend-aasland** [comment]
> This change doesn't break anything important in Django 👍 (at the first glance). I've started fixing `ResourceWarning`s in our tests, check out [django/django#17178](https://github.com/django/django/pull/17178).

Great, thanks for chiming in.

**Comment by erlend-aasland** [comment]
Thanks for the reviews!

**Comment by vstinner** [comment]
Congrats :-) IMO it's a nice enhancement.

File: Lib/test/test_sqlite3/test_dbapi.py [hunk 5]
```diff
@@ -583,6 +583,12 @@ def test_connect_positional_arguments(self):
             cx.close()
         self.assertEqual(cm.filename, __file__)
 
+    def test_connection_resource_warning(self):
+        with self.assertWarns(ResourceWarning):
+            cx = sqlite.connect(":memory:")
+            del cx
+            gc_collect()
```
Comment (erlend-aasland) [inline Lib/test/test_sqlite3/test_dbapi.py:590]: @vstinner: this test does not play well if run multiple times (for example during ref leak hunting); the `ResourceWarning` escapes the test during the second run, so we get an "env changed" warning and a failed test. I'm not sure how to fix this.

Comment (vstinner) [reply Lib/test/test_sqlite3/test_dbapi.py:590]: I cannot reproduce the issue. Do you have logs where it occurred? A way to reproduce the issue? I tried ``./python -m test -m test_connection_resource_warning -v test_sqlite3 test_sqlite3`` to run the test twice in the same process. Using a debug build, it doesn't fail.

Comment (erlend-aasland) [reply Lib/test/test_sqlite3/test_dbapi.py:590]: Hm, there's something fishy here. It's not _this_ particular test that is emitting resource warnings, it's something else. Try:

```
$ ./python -m test -R : test_sqlite3 -m test_dbapi
```

Comment (erlend-aasland) [reply Lib/test/test_sqlite3/test_dbapi.py:590]: Ok, I found them:

    ./python -m test -R : test_sqlite3 -m ClosedCurTests

Comment (felixxm) [reply Lib/test/test_sqlite3/test_dbapi.py:590]: This is because we close a cursor, not a connection:
```diff
diff --git a/Lib/test/test_sqlite3/test_dbapi.py b/Lib/test/test_sqlite3/test_dbapi.py
index d80ad7af32..e99333625b 100644
--- a/Lib/test/test_sqlite3/test_dbapi.py
+++ b/Lib/test/test_sqlite3/test_dbapi.py
@@ -1757,6 +1757,7 @@ def test_closed(self):
             with self.assertRaises(sqlite.ProgrammingError):
                 method = getattr(cur, method_name)
                 method(*params)
+        con.close()
 
 
 class SqliteOnConflictTests(unittest.TestCase):
```
I can prepare PR in 2 minutes.

Comment (felixxm) [reply Lib/test/test_sqlite3/test_dbapi.py:590]: Check out #108360.
