### PR TITLE
gh-102406: replace exception chaining by PEP-678 notes in codecs

### LINKED ISSUE #102406: codecs can use PEP-678 notes instead of wrapping/chaining exceptions
[In codecs.c](https://github.com/python/cpython/blob/cb944d0be869dfb1189265467ec8a986176cc104/Python/codecs.c#L397) there is a call to _PyErr_TrySetFromCause (a function that is only called from here), which tries to create a new exception of the same type with a different message, but bails out if there are any complications that make this unsafe. The purpose is to add information about the context of the operation that failed, without changing the type of the exception. This can be solved more easily and robustly with PEP-678 exception notes. 

### Linked PRs
* gh-102407

### PR DESCRIPTION
**Pull request by iritkatriel**
Fixes #102406.

This replaces exception wrapping in codecs by PEP-678 notes. 

Simplifies the code and removes the restrictions that prevent wrapping of exceptions that we cannot safely create copies of (because they have args or ``__init__`` overrides, etc).

* Issue: gh-102406

### CODE REVIEW

**Comment by iritkatriel** [comment]
CC @Zac-HD

**Comment by doerwalter** [comment]
I'm not sure why wrapping of the codec errors was added in the first place. IMHO the encoding name and codec operation should be clear enough from the stacktrace.

However using exception notes for that is definitiely an improvement.

I fear that I can't review the patch in detail, as I'm no longer familiar with Python's C API.

**Review by erlend-aasland — APPROVED** [review]

File: Misc/NEWS.d/next/Core and Builtins/2023-03-03-23-21-16.gh-issue-102406.XLqYO3.rst [hunk 1]
```diff
@@ -0,0 +1 @@
+codecs encoding/decoding errors now get the context information (which operation and which codecs) attached as PEP-678 notes instead of through chaining a new instance of the exception.
```
Comment (erlend-aasland) [inline Misc/NEWS.d/next/Core and Builtins/2023-03-03-23-21-16.gh-issue-102406.XLqYO3.rst]:
```suggestion
:mod:`codecs` encoding/decoding errors now get the context information (which operation and which codecs) attached as :pep:`678` notes instead of through chaining a new instance of the exception.
```

**Review by gpshead — APPROVED** [review]
Excellent cleanup!
