### PR TITLE
gh-93372: Fix typo in os.rename documentation

### LINKED ISSUE #93372: An extra word in the os.rename documentation
**Documentation**

In https://docs.python.org/3/library/os.html#os.rename, the line
> If both are files, dst **it** will be replaced silently if the user has permission.

has an extra `it`.

### PR DESCRIPTION
**Pull request by Yang-Wei-Ting**
Fixes #93372

### CODE REVIEW

File: Misc/NEWS.d/next/Documentation/2022-06-01-04-54-33.gh-issue-93372.SCa_tP.rst [hunk 1]
```diff
@@ -0,0 +1 @@
+Fix typo in ``os.rename`` documentation.
```
Comment (serhiy-storchaka) [inline Misc/NEWS.d/next/Documentation/2022-06-01-04-54-33.gh-issue-93372.SCa_tP.rst]: Simple typo fix does not need a NEWS entry.

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution @Yang-Wei-Ting!
