### PR TITLE
gh-146287: Fix signed/unsigned mismatch in _hashlib_hmac_digest_size

### LINKED ISSUE #146287: `_hashopenssl.c‍`: Missing negative return check in `EVP_get_block_size` and `EVP_get_digest_size`
# Bug report

### Bug description:

`EVP_get_block_size` and `EVP_get_digest_size` pass the return value of
`EVP_MD_CTX_block_size()` / `EVP_MD_CTX_size()` directly to `PyLong_FromLong()`
without checking for a negative error return. When OpenSSL signals an error by
returning `-1`, Python silently exposes that value to the caller instead of
raising a `ValueError`.

## Vulnerable Code

```c
// Modules/_hashopenssl.c

static PyObject *
EVP_get_block_size(EVPobject *self, void *closure)
{
    long block_size;
    block_size = EVP_MD_CTX_block_size(self->ctx);
    return PyLong_FromLong(block_size);   // no check for negative value
}

static PyObject *
EVP_get_digest_size(EVPobject *self, void *closure)
{
    long size;
    size = EVP_MD_CTX_size(self->ctx);
    return PyLong_FromLong(size);         // no check for negative value
}
```

## Root Cause

In OpenSSL 3.x, both macros are defined in `<openssl/evp.h>` as:

```c
#define EVP_MD_CTX_get_size(e)        EVP_MD_get_size(EVP_MD_CTX_get0_md(e))
#define EVP_MD_CTX_size               EVP_MD_CTX_get_size

#define EVP_MD_CTX_get_block_size(e)  EVP_MD_get_block_size(EVP_MD_CTX_get0_md(e))
#define EVP_MD_CTX_block_size         EVP_MD_CTX_get_block_size
```

Both expand to `EVP_MD_get_size(EVP_MD_CTX_get0_md(ctx))`.
When the context has no digest set, `EVP_MD_CTX_get0_md()` returns `NULL`,
and `EVP_MD_get_size(NULL)` returns **`-1`** an error signal that Python never checks.

---

## Proof of Concept

```python
import ctypes, ctypes.util, ssl

print(f"OpenSSL: {ssl.OPENSSL_VERSION}\n")

lib = ctypes.CDLL(ctypes.util.find_library('crypto'))
lib.EVP_MD_CTX_new.restype         = ctypes.c_void_p
lib.EVP_MD_CTX_free.restype        = None
lib.EVP_MD_CTX_free.argtypes       = [ctypes.c_void_p]
lib.EVP_MD_CTX_get0_md.restype     = ctypes.c_void_p
lib.EVP_MD_CTX_get0_md.argtypes    = [ctypes.c_void_p]
lib.EVP_MD_get_size.restype        = ctypes.c_int
lib.EVP_MD_get_size.argtypes       = [ctypes.c_void_p]
lib.EVP_MD_get_block_size.restype  = ctypes.c_int
lib.EVP_MD_get_block_size.argtypes = [ctypes.c_void_p]

# context without EVP_DigestInit_ex => get0_md() returns NULL
ctx = lib.EVP_MD_CTX_new()
md  = lib.EVP_MD_CTX_get0_md(ctx)

print(f"EVP_MD_CTX_get0_md()    = {md or 'NULL'}")
print(f"EVP_MD_get_size(NULL)   = {lib.EVP_MD_get_size(md)}")
print(f"EVP_MD_get_block_size() = {lib.EVP_MD_get_block_size(md)}\n")

digest_size = lib.EVP_MD_get_size(md)
block_size  = lib.EVP_MD_get_block_size(md)
print(f"hash.digest_size => {digest_size}  (no ValueError raised)")
print(f"hash.block_size  => {block_size}  (no ValueError raised)")

lib.EVP_MD_CTX_free(ctx)
```

**Output:**

```
OpenSSL: OpenSSL 3.3.1 4 Jun 2024

EVP_MD_CTX_get0_md()    = NULL
EVP_MD_get_size(NULL)   = -1
EVP_MD_get_block_size() = -1

hash.digest_size => -1  (no ValueError raised)
hash.block_size  => -1  (no ValueError raised)
```

---

## Suggested Fix

```c
static PyObject *
EVP_get_block_size(EVPobject *self, void *closure)
{
    long block_size = EVP_MD_CTX_block_size(self->ctx);
    if (block_size <= 0) {
        PyErr_SetString(PyExc_ValueError, "block size unavailable");
        return NULL;
    }
    return PyLong_FromLong(block_size);
}

static PyObject *
EVP_get_digest_size(EVPobject *self, void *closure)
{
    long size = EVP_MD_CTX_size(self->ctx);
    if (size <= 0) {
        PyErr_SetString(PyExc_ValueError, "digest size unavailable");
        return NULL;
    }
    return PyLong_FromLong(size);
}
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-148407

### PR DESCRIPTION
**Pull request by gpshead**
## Summary

`_hashlib_hmac_digest_size()` returns `unsigned int`, but on the legacy OpenSSL 1.1.1 path it gets its value from `EVP_MD_size()` which returns `int`. A negative error return (-1) would silently wrap to UINT_MAX, bypassing the `== 0` error check and propagating a bogus size to callers.

This can't be triggered through the Python API today (the `md` pointer is always validated before use), but the type mismatch means the safety net has a hole.

- Change `_hashlib_hmac_digest_size()` return type to `int`
- Add explicit `< 0` guard in the legacy OpenSSL path
- Use `SystemError` instead of `ValueError` for these checks, since
  they represent internal invariant violations
- Add `assert()` to `EVP_get_block_size` and `EVP_get_digest_size`
  to document that the hash context is always initialized
- Update callers to use `int` instead of `unsigned int`

* Issue: gh-146287

fixes #146287

### CODE REVIEW

**Comment by gpshead** [comment]
there's nothing observable to users in this change, so skip news added.

File: Modules/_hashopenssl.c [hunk 1]
```diff
@@ -2215,15 +2217,19 @@ _hashlib_hmac_digest_size(HMACobject *self)
     }
     int digest_size = EVP_MD_size(md);
     /* digest_size < 0 iff EVP_MD context is NULL (which is impossible here) */
-    assert(digest_size >= 0);
+    assert(digest_size > 0);
     assert(digest_size <= (int)EVP_MAX_MD_SIZE);
+    if (digest_size < 0) {
+        raise_ssl_error(PyExc_SystemError, "invalid digest size");
+        return BAD_DIGEST_SIZE;
+    }
```
Comment (picnixz) [inline Modules/_hashopenssl.c]:
```suggestion
    assert(digest_size <= (int)EVP_MAX_MD_SIZE);
    if (digest_size < 0) {
        raise_ssl_error(PyExc_SystemError, "invalid digest size");
        return BAD_DIGEST_SIZE;
    }
```

You'll crash before you hit `if (digest_size < 0)` otherwise.

File: Modules/_hashopenssl.c [hunk 2]
```diff
@@ -2215,15 +2217,19 @@ _hashlib_hmac_digest_size(HMACobject *self)
...
 #endif
     /* digest_size == 0 means that the context is not entirely initialized */
     if (digest_size == 0) {
-        raise_ssl_error(PyExc_ValueError, "missing digest size");
+        raise_ssl_error(PyExc_SystemError, "missing digest size");
```
Comment (picnixz) [inline Modules/_hashopenssl.c:2228]: I'm not sure we want a SystemError. It's not thaaaat critical I'd say and it's fine to keep the ValueError IMO.

Comment (gpshead) [reply Modules/_hashopenssl.c:2228]: yeah I was waffling either way... this is basically an "unseen error" that is here for correctness but won't come up in practice.  nobody should be trying to catch it either way.

Comment (picnixz) [reply Modules/_hashopenssl.c:2228]: Ok. Actually.. it's very funny because I said:

> I am not against an explicit assert() for debug builds or a comment and if we want a real check, it should raise a SystemError and not a ValueError.

So now I'm no more agreeing with myself :D

Comment (picnixz) [reply Modules/_hashopenssl.c:2228]: Do we have a precedent elsewhere just so that we know what to raise.. just in case? like in sqlite extension module or in decimal maybe?

File: Modules/_hashopenssl.c (hunk 1 above)
Comment (gpshead) [reply Modules/_hashopenssl.c]: accepting that change, thanks.  in reality - it may be "fine" for it to crash in builds with assertions enabled.  this is defensive code, not something i'm expecting actually happens in practice.

File: Modules/_hashopenssl.c (hunk 2 above)
Comment (gpshead) [reply Modules/_hashopenssl.c:2228]: I'm just going off of a feeling that "believed impossible internal state encountered" implies SystemError or Py_FatalError() rather than ValueError which implies it is related to something the users code did.

Comment (picnixz) [reply Modules/_hashopenssl.c:2228]: Ok, let's for a system error. I think that's also my initial feeling (when it wasn't 1 AM!)
