### PR TITLE
gh-106558: Fix multiprocessing manager exception ref cycle.

### LINKED ISSUE #106558: multiprocessing Manager exceptions create cyclic references
# Bug report

`multiprocessing.managers` uses `convert_to_error(kind, result)` to make a raisable exception out of `result` when a call has responded with some sort of error. If `kind == "#ERROR"`, then `result` is already an exception and the caller raises it directly—but because `result` was created in a frame at or under the caller, this creates a reference cycle `result` → `result.__traceback__` → (some frame)`.f_locals['result']`.

In particular, every time I've used a manager queue I've expected frequent occurrences of `queue.Empty`, and the buildup of reference cycles sporadically wakes up the garbage collector and wrecks my hopes of consistent latency.

I'm including an example script below. PR coming in a moment, so please let me know if I should expand the example into a test and bundle that in. (Please also feel free to tell me if this is a misuse of queue.Empty and I should buzz off.)

# Your environment

- CPython versions tested on: 3.11.3
- Operating system and architecture: `uname -a` says `Linux delia 6.3.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 11 May 2023 16:40:42 +0000 x86_64 GNU/Linux`

# Minimal example

## Output

```
net allocations:  0
got from queue:   [0, 1, 2, 3, 4]
net allocations:  23
garbage produced: Counter({<class 'traceback'>: 3, <class 'frame'>: 3, <class 'list'>: 1, <class '_queue.Empty'>: 1})
net allocations:  0
```

## Script

```py
#!/usr/bin/env python

import collections
import gc
import multiprocessing
import queue
import time


def sender(q):
    for i in range(5):
        q.put_nowait(i)

def get_all_available(q):
    result = []
    try:
        while True:
            result.append(q.get_nowait())
    except queue.Empty:
        ...
    return result

def main():
    q = multiprocessing.Manager().Queue()
    p = multiprocessing.Process(target=sender, args=(q,))
    p.start()

    # take control of gc
    gc.disable()
    gc.collect()
    gc.set_debug(gc.DEBUG_SAVEALL)
    time.sleep(0.1)  # just in case the new process took a while to create
    print('net allocations: ', gc.get_count()[0])

    # trigger a queue.Empty
    print('got from queue:  ', get_all_available(q))

    # check for collectable garbage and print it
    print('net allocations: ', gc.get_count()[0])
    gc.collect()
    print('garbage produced:', collections.Counter(type(x) for x in gc.garbage))
    gc.set_debug(0)
    gc.garbage.clear()
    gc.collect()
    print('net allocations: ', gc.get_count()[0])

    # clean up
    p.join()


if __name__ == '__main__':
    main()
```

### Linked PRs
* gh-106559

### PR DESCRIPTION
**Pull request by pteromys**
If `kind == '#ERROR'`, then `result` is an exception whose attached traceback includes the frame that calls `convert_to_error()` and has `result` in scope. So delete `result` from the scope as we raise it, to save the consumer of these exceptions from having to cope with a buildup of cyclic references.

(This is the same [try/finally/del](https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/) pattern that `logging.Handler.handleError` uses and the [docs for the `except E as N` syntax](https://docs.python.org/3/reference/compound_stmts.html#except-clause) hint at.)

Closes #106558.

* Issue: gh-106558

### CODE REVIEW

File: Misc/NEWS.d/next/Library/2023-07-09-00-36-33.gh-issue-106558.Zqsj6F.rst [hunk 1]
```diff
@@ -0,0 +1,3 @@
+Fix ref cycle in callers of
```
Comment (iritkatriel) [inline Misc/NEWS.d/next/Library/2023-07-09-00-36-33.gh-issue-106558.Zqsj6F.rst]:
```suggestion
Remove ref cycle in callers of
```

File: Misc/NEWS.d/next/Library/2023-07-09-00-36-33.gh-issue-106558.Zqsj6F.rst [hunk 2]
```diff
@@ -0,0 +1,3 @@
...
+:func:`~multiprocessing.managers.convert_to_error` by deleting ``result``
+from scope in a ``finally`` block if it's an exception.
```
Comment (iritkatriel) [inline Misc/NEWS.d/next/Library/2023-07-09-00-36-33.gh-issue-106558.Zqsj6F.rst]:
```suggestion
from scope in a ``finally`` block.
```

I think you're deleting it regardless of its type, right?

**Comment by iritkatriel** [comment]
Yes, we need to do this sometimes with exceptions because the traceback cycles back to the exception through the frame locals *sigh*.

File: Misc/NEWS.d/next/Library/2023-07-09-00-36-33.gh-issue-106558.Zqsj6F.rst (hunk 2 above)
Comment (pteromys) [reply Misc/NEWS.d/next/Library/2023-07-09-00-36-33.gh-issue-106558.Zqsj6F.rst]: Yeah—so long as it actually reached calling `convert_to_error` at all, we'll delete `result` with no further conditions on `kind`.

**Comment by iritkatriel** [comment]
Can you add a unit test based on your example from the issue?

File: Lib/test/_test_multiprocessing.py [hunk 3]
```diff
@@ -3149,6 +3149,29 @@ def test_rapid_restart(self):
             if hasattr(manager, "shutdown"):
                 self.addCleanup(manager.shutdown)
 
+#
+# Issue 106558: Manager exceptions should not create cyclic references.
+#
+
+class TestManagerExceptions(unittest.TestCase):
```
Comment (iritkatriel) [inline Lib/test/_test_multiprocessing.py]:
```suggestion

class TestManagerExceptions(unittest.TestCase):
    # Issue 106558: Manager exceptions avoids creating cyclic references.
```

**Review by iritkatriel — COMMENTED** [review]
I've confirmed that the test fails on main. Just a suggestion to move the comment into the class, so they stay together as things move around.

File: Lib/multiprocessing/managers.py [hunk 4]
```diff
@@ -90,7 +90,10 @@ def dispatch(c, id, methodname, args=(), kwds={}):
     kind, result = c.recv()
     if kind == '#RETURN':
         return result
-    raise convert_to_error(kind, result)
+    try:
+        raise convert_to_error(kind, result)
+    finally:
+        del result
```
Comment (iritkatriel) [inline Lib/multiprocessing/managers.py]:
```suggestion
        del result  # break reference cycle
```

File: Lib/multiprocessing/managers.py [hunk 5]
```diff
@@ -833,7 +836,10 @@ def _callmethod(self, methodname, args=(), kwds={}):
             conn = self._Client(token.address, authkey=self._authkey)
             dispatch(conn, None, 'decref', (token.id,))
             return proxy
-        raise convert_to_error(kind, result)
+        try:
+            raise convert_to_error(kind, result)
+        finally:
+            del result
```
Comment (iritkatriel) [inline Lib/multiprocessing/managers.py]:
```suggestion
            del result   # break reference cycle
```

File: Lib/test/_test_multiprocessing.py [hunk 6]
```diff
@@ -3149,6 +3149,29 @@ def test_rapid_restart(self):
...
+    def test_queue_get(self):
+        queue = self.mgr.Queue()
+        if gc.isenabled():
+            gc.disable()
+            self.addCleanup(gc.enable)
+        try:
+            queue.get_nowait()
+        except pyqueue.Empty as e:
+            wr = weakref.ref(e)
+        self.assertEqual(wr(), None)
```
Comment (iritkatriel) [inline Lib/test/_test_multiprocessing.py:3178]: Actually, this doesn't cover the changes to lines 93-96.  Can we add a test for that?

Comment (pteromys) [reply Lib/test/_test_multiprocessing.py:3178]: Yep, added, though now I'm having second thoughts:

Apparently `dispatch` as the standard library actually uses it will only ever* respond with `kind` being `'#RETURN'` (then `convert_to_error` is not called) or `'#TRACEBACK'` (then `result` is a string so it's not a link in a reference cycle).

The most I could imagine that changing is if someone tries to introduce a custom connection class, so the test vaguely gestures in that direction. But since the caller of `dispatch` has to know about this `(kind, result)` return type, it still feels like exposing internal implementation details to the test. Now I'm starting to wonder if the better tradeoff would be to revert lines 93-96—maybe at most leaving some version of this comment in the commit message to explain why we're only wrapping one of the two calls to `convert_to_error`.

(*Proof: All calls to `dispatch` are on freshly created `self._Client` instances, so they all are answered by `serve_forever → accepter → handle_request → _handle_request`, and `_handle_request` only responds with those two `kind`s.

For context, the one line that does generate `'#ERROR'` is inside `serve_client`—only contactable by reusing a connection on which we previously `dispatch`ed `accept_connection`, and the one place that happens is when `_callmethod` calls `_connect`. Even the `dispatch` call that's later in `_callmethod` comes after replacing `conn` with a fresh `self._Client`.)

File: Lib/test/_test_multiprocessing.py [hunk 7]
```diff
@@ -3149,6 +3149,43 @@ def test_rapid_restart(self):
             if hasattr(manager, "shutdown"):
                 self.addCleanup(manager.shutdown)
 
+
+class FakeConnection:
+    def send(self, payload):
+        pass
```
Comment (iritkatriel) [inline Lib/test/_test_multiprocessing.py:3155]:
```suggestion
        pass

```

(PEP8)

File: Lib/test/_test_multiprocessing.py (hunk 6 above)
Comment (iritkatriel) [reply Lib/test/_test_multiprocessing.py:3178]: I would leave the fix in, I think this test is fine, good enough to prevent regression if someone reverts the change to the code (which I think we should have).

**Review by iritkatriel — APPROVED** [review]

**Comment by ambv** [comment]
Closing and re-opening to retrigger CLA checks. Sorry for the noise.
