### PR TITLE
gh-102594: PyErr_SetObject adds note to exception raised on normalization error

### LINKED ISSUE #102594: Suspected `PyErr_Fetch()` behavior change
# Bug report

While testing pybind11 with Python 3.12alpha6 I ran into what looks like a `PyErr_Fetch()` behavior change. I also tried with the main branch @ c6858d1e7f4cd3184d5ddea4025ad5dfc7596546.

I think the issue reduces to:

* `PyErr_SetObject()` as e.g. here: https://github.com/pybind/pybind11/blob/442261da585536521ff459b1457b2904895f23b4/tests/test_exceptions.cpp#L309

* Followed more-or-less immediately by a `PyErr_Fetch()` as e.g. here: https://github.com/pybind/pybind11/blob/442261da585536521ff459b1457b2904895f23b4/include/pybind11/pytypes.h#L482

The special twist is that the exception type involved raises a `ValueError` in its `__init__`:

* https://github.com/pybind/pybind11/blob/442261da585536521ff459b1457b2904895f23b4/tests/test_exceptions.py#L295

For easy reference the same code copy-pasted here:

```
class FlakyException(Exception):
    def __init__(self, failure_point):
        if failure_point == "failure_point_init":
            raise ValueError("triggered_failure_point_init")
        self.failure_point = failure_point
```

* Up to and including 3.12alpha3: `PyErr_Fetch()` produces the `FlakyException` type ([this here](https://github.com/pybind/pybind11/blob/442261da585536521ff459b1457b2904895f23b4/include/pybind11/pytypes.h#L488)).

* **With 3.12alpha6: `PyErr_Fetch()` produces the `ValueError` type** instead.

Additional detail:

Up to and including 3.12alpha3: only `PyErr_NormalizeException()` hits the `ValueError` in `FlakyException._init__`, but not `PyErr_Fetch()`.

# Your environment

- CPython versions tested on: 3.12alpha6,  main branch @ c6858d1e7f4cd3184d5ddea4025ad5dfc7596546
- Operating system and architecture: Debian 5.19.11 clang14, ubuntu22 gcc11

### Linked PRs
* gh-102606
* gh-102607
* gh-102675

### PR DESCRIPTION
**Pull request by iritkatriel**
Fixes #102594.

Co-authored-by: Ralf W. Grosse-Kunstleve <rwgk@google.com>

* Issue: gh-102594

### CODE REVIEW

**Comment by erlend-aasland** [comment]
I was under the impression that we should not use exception notes internally. I'll try to find a link to the previous discussion (between Victor and Irit, IIRC); it may be relevant to this change.

**Comment by iritkatriel** [comment]
> I was under the impression that we should not use exception notes internally. I'll try to find a link to the previous discussion (between Victor and Irit, IIRC); it may be relevant to this change.

There is no general ban on using the notes in the interpreter. The discussion you are referring to was about splitting the message into a "core error message" as arg and "explanation" on the note, so that IDEs can toggle the explanation on and off. The objection was to introduce assumptions about what is in the note, and how IDEs should handle it.  There is also a general guideline that information which is known at the time the exception object is constructed does not belong on the note.  Technically of course you can put it on the note, but that was not their intended use.

This PR addresses the classic use case for PEP-678: we have an exception that we did not construct, and we want to enrich it with additional information which was not available at the time that the exception was constructed.

**Comment by erlend-aasland** [comment]
Yeah, that discussion sounds familiar. Do you happen to have a link to it?

File: Python/errors.c [hunk 1]
```diff
@@ -169,6 +191,16 @@ _PyErr_SetObject(PyThreadState *tstate, PyObject *exception, PyObject *value)
...
+            PyObject *exc = _PyErr_GetRaisedException(tstate);
+            assert(PyExceptionInstance_Check(exc));
+
+            PyObject *note = get_normalization_failure_note(tstate, exception, value);
+            if (note != NULL) {
+                PyObject *res = _PyException_AddNote((PyBaseExceptionObject*)exc, note);
+                Py_DECREF(note);
+                Py_XDECREF(res);
+            }
+            _PyErr_SetRaisedException(tstate, exc);
```
Comment (iritkatriel) [inline Python/errors.c:202]: If get_normalization_failure_note returns NULL then this will overwrite whatever exception came from there (including MemoryError). Should I do something else?

**Comment by iritkatriel** [comment]
> Yeah, that discussion sounds familiar. Do you happen to have a link to it?

I don't, sorry.

**Comment by iritkatriel** [comment]
FYI @Zac-HD

**Comment by AlexWaygood** [comment]
> > Yeah, that discussion sounds familiar. Do you happen to have a link to it?
> 
> I don't, sorry.

There was some previous discussion in:
- #96878
- #96958

File: Lib/test/test_capi/test_exceptions.py [hunk 2]
```diff
@@ -169,5 +169,25 @@ class Broken(Exception, metaclass=Meta):
         with self.assertRaises(ZeroDivisionError) as e:
             _testcapi.exc_set_object(Broken, Broken())
 
+    def test_set_object_and_fetch(self):
+        class Broken(Exception):
+            def __init__(self, *arg):
+                 raise ValueError("Broken __init__")
+
+        exc = _testcapi.exc_set_object_fetch(Broken, ('abcd'))
```
Comment (gvanrossum) [inline Lib/test/test_capi/test_exceptions.py]: Why the `()` around `'abcd'`? They don't make a tuple (for that you'd need a trailing comma).

File: Lib/test/test_capi/test_exceptions.py [hunk 3]
```diff
@@ -169,5 +169,25 @@ class Broken(Exception, metaclass=Meta):
...
+        self.assertIsInstance(exc, ValueError)
+        self.assertEqual(exc.__notes__[0],
+                         "Normalization failed: type=Broken args='abcd'")
+
+        class BadArg:
+            def __repr__(self):
+                raise TypeError('Broken arg type')
+
+        exc = _testcapi.exc_set_object_fetch(Broken, (BadArg()))
```
Comment (gvanrossum) [inline Lib/test/test_capi/test_exceptions.py]: Ditto.

**Review by gvanrossum — COMMENTED** [review]
(We discussed this extensively offline, but here are some nits I had already found.)

FWIW I think this is an excellent use case for notes, unlike the two issues Alex linked to.

File: Python/errors.c [hunk 4]
```diff
@@ -182,28 +182,27 @@ _PyErr_SetObject(PyThreadState *tstate, PyObject *exception, PyObject *value)
...
+                _PyException_AddNote(exc, note);
                 Py_DECREF(note);
-                Py_XDECREF(res);
             }
             _PyErr_SetRaisedException(tstate, exc);
             return;
         }
-
+        Py_XDECREF(value);
         value = fixed_value;
```
Comment (gvanrossum) [inline Python/errors.c]: I think there's a macro to do this? `Py_SETREF(value, fixed_value);` -- though it's only needed if there's a chance that source and destination may be the same object (*and* there's only one reference left to it), which IIUC can't be the case here.

**Review by gvanrossum — APPROVED** [review]
LG, just one optional suggestion.

**Review by gvanrossum — APPROVED** [review]

**Comment by gvanrossum** [comment]
PS. Shouldn't `PyErr_NormalizeException` also add the same note?

**Comment by iritkatriel** [comment]
> PS. Shouldn't `PyErr_NormalizeException` also add the same note?

We could, but it's deprecated so I'm not sure how much it matters now.

**Comment by gvanrossum** [comment]
Fair
