### PR TITLE
gh-91581: Check result of utc_to_seconds

### LINKED ISSUE #91581: Error condition in _datetimemodule.c is unchecked with `datetime.fromtimestamp` on local times > Y10k
[On twitter](https://twitter.com/RaphaelWimmer/status/1514610148353880075?s=20&t=zpY5y-FQQuCplJnncUZnGg), someone asked about a weird difference in the error messages from `datetime.fromtimestamp()` when called with a timestamp that falls on 10000-01-01 when compared to 10000-01-02. Compare:

```
$ TZ=UTC python -c "from datetime import *; datetime.fromtimestamp(253402300799 + 1)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: year 0 is out of range

$ TZ=UTC python -c "from datetime import *; datetime.fromtimestamp(253402300799 + 1 + 24 * 3600)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: year 10000 is out of range
```

Turns out that this is because in the localtime-specific implementation of `datetime.fromtimestamp` in `_datetimemodule.c`, there's an unchecked error condition when calling [`utc_to_seconds`](https://github.com/python/cpython/blob/7acedd71dec4e60400c865911e8961dbb49d5597/Modules/_datetimemodule.c#L4988-L4989), which fails with `-1`.

As a practical matter, this always results in basically the same error anyway, since in all situations where `result_seconds` gets set to `-1` the subsequent calculations fail anyway, and the only difference is that the error message has a slightly different form, but we may as well fix this.

### PR DESCRIPTION
**Pull request by pganssle**
This result could fail. On Linux here's a minimal reproducer:

```
TZ=UTC python -c "from datetime import *; datetime.fromtimestamp(253402300799 + 1)"
```

The old behavior still raised an error in a similar way, but only because subsequent calculations happened to fail as well. Better to fail fast.

Fixes GH-91581

### CODE REVIEW

**Comment by pganssle** [comment]
I don't understand why github thinks I didn't author this commit. The e-mail I used on the commit is on my GH account.

**Review by serhiy-storchaka — COMMENTED** [review]
If it does not have user-facing effect, it does not need a NEWS entry. If it changes the error message, it would be worth to add a test for this.

**Comment by serhiy-storchaka** [comment]
I would add tests for Dec 30, 1 BCE and Dec 31, 1 BCE.

**Comment by pganssle** [comment]
Thanks for the review Serhiy!

> If it does not have user-facing effect, it does not need a NEWS entry. If it changes the error message, it would be worth to add a test for this.

It changes the error message but not in any way that I am prepared to make assertions about — this is a mostly cosmetic change for consistency. I'm not even sure that the error message is the same across the C and Python implementations.

I generally like to add a NEWS entry for code changes anyway, in case the change had an unexpected effect and someone is looking for hints as to what might have caused the behavior change in the changelog.

> I would add tests for Dec 30, 1 BCE and Dec 31, 1 BCE.

Done, and when doing that I refactored the relevant tests to get us a lot closer to the actual limits we're expecting.  This turned up some other issues around these edge cases, so I've added [this comment](https://github.com/python/cpython/issues/91012#issuecomment-1123974894) to #91012. Fixing that should let us make these tests a lot cleaner.

As part of the refactor I ended up tweaking the pure Python implementation of `utcfromtimestamp`, since it was erroneously erroring out in cases where the C version wasn't.

File: Modules/_datetimemodule.c [hunk 1]
```diff
@@ -5071,6 +5071,10 @@ datetime_from_timet_and_us(PyObject *cls, TM_FUNC f, time_t timet, int us,
 
         result_seconds = utc_to_seconds(year, month, day,
                                         hour, minute, second);
+        if (result_seconds == -1) {
```
Comment (serhiy-storchaka) [inline Modules/_datetimemodule.c]: I would add `&& PyErr_Occurred()` just for the case if we enable support of BCE dates.

File: Lib/test/datetimetester.py [hunk 2]
```diff
@@ -2515,45 +2515,89 @@ def test_microsecond_rounding(self):
             self.assertEqual(t.microsecond, 7812)
 
     def test_timestamp_limits(self):
-        # minimum timestamp
+        with self.subTest("minimum UTC"):
+            min_dt = self.theclass.min.replace(tzinfo=timezone.utc)
+            min_ts = min_dt.timestamp()
+
+            self.assertLess(min_ts, 0)
```
Comment (serhiy-storchaka) [inline Lib/test/datetimetester.py]: Should not it be constant -62135596800?

File: Lib/test/datetimetester.py [hunk 3]
```diff
@@ -2515,45 +2515,89 @@ def test_microsecond_rounding(self):
...
+
+        with self.subTest("maximum UTC"):
+            # Set microseconds to 0 to avoid rounding issues
+            max_dt = self.theclass.max.replace(tzinfo=timezone.utc)
+            max_ts = max_dt.timestamp()
+
+            self.assertGreater(max_ts, 0)
```
Comment (serhiy-storchaka) [inline Lib/test/datetimetester.py]: Should not it be constant 253402300800?

File: Lib/test/datetimetester.py [hunk 4]
```diff
@@ -2515,45 +2515,89 @@ def test_microsecond_rounding(self):
...
+
+    def test_fromtimestamp_limits(self):
+        # XXX: Replace these with datetime.{min,max}.timestamp() when we solve
+        # the issue with gh-91012
+        min_dt = self.theclass.min + timedelta(days=1)
+        min_ts = min_dt.timestamp()
+
+        max_dt = self.theclass.max.replace(microsecond=0)
+        max_ts = ((self.theclass.max - timedelta(hours=23)).timestamp() +
+                  timedelta(hours=22, minutes=59, seconds=59).total_seconds())
```
Comment (serhiy-storchaka) [inline Lib/test/datetimetester.py:2549]: Why is it so complicated? Why not `self.theclass.max - timedelta(seconds=1)`?

File: Lib/test/datetimetester.py [hunk 5]
```diff
@@ -2515,45 +2515,89 @@ def test_microsecond_rounding(self):
...
+                ("minimum", min_ts, min_dt),
+                ("maximum", max_ts, max_dt),
+        ]:
+            with self.subTest(test_name, ts=ts, expected=expected):
+                try:
+                    actual = self.theclass.fromtimestamp(ts)
+                except (OSError, OverflowError) as exc:
+                    self.skipTest(str(exc))
+
+                self.assertEqual(actual, expected)
```
Comment (serhiy-storchaka) [inline Lib/test/datetimetester.py:2558]: I am confused. `max_ts` is not `max_dt.timestamp()`. Why is it converted back to `max_dt`?

File: Misc/NEWS.d/next/Library/2022-04-15-13-16-25.gh-issue-91581.9OGsrN.rst [hunk 6]
```diff
@@ -0,0 +1,5 @@
+Check the result of the ``utc_to_seconds`` call when calling
```
Comment (serhiy-storchaka) [inline Misc/NEWS.d/next/Library/2022-04-15-13-16-25.gh-issue-91581.9OGsrN.rst]: `utc_to_seconds` is an implementation detail. It is completely invisible to user. Please describe only user-visible behavior.

**Review by serhiy-storchaka — COMMENTED** [review]
I have some questions and minor suggestions.

File: Lib/test/datetimetester.py (hunk 2 above)
Comment (pganssle) [reply Lib/test/datetimetester.py]: I'm not really sure if we want to rely on the value of `datetime.min` at all — I'm not sure if there are other platforms where it's a different value, or if we might eventually support a different value.

Maybe I'll assert the specific value and add a comment saying, "This assumes `datetime.min` is 0001-01-01, if this changes, change this test" or something.

File: Lib/test/datetimetester.py (hunk 4 above)
Comment (pganssle) [reply Lib/test/datetimetester.py:2549]: `(self.theclass.max - timedelta(seconds=1)).timestamp()` fails in some time zones, but `self.theclass.max - timedelta(hours=23)` succeeds in all available time zones, while `fromtimestamp` will succeed for any value up to 1 second before `datetime.max`, so we get a fixed amount of time away from the edge with our `datetime`, then make up the gap on the integer side.

I have a fix for #91012 that fixes both the `datetime.timestamp()` and `datetime.fromtimestamp()` behaviors, so I imagine this hack will be short-lived.

File: Lib/test/datetimetester.py (hunk 5 above)
Comment (pganssle) [reply Lib/test/datetimetester.py:2558]: They should represent the same datetime, it's just that `max_dt.timestamp()` fails in some zones, e.g.:

```
$ TZ=Europe/Prague python -c\
> "from datetime import datetime, timedelta; (datetime.max - timedelta(seconds=1)).timestamp()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: year 10000 is out of range
```

File: Misc/NEWS.d/next/Library/2022-04-15-13-16-25.gh-issue-91581.9OGsrN.rst (hunk 6 above)
Comment (pganssle) [reply Misc/NEWS.d/next/Library/2022-04-15-13-16-25.gh-issue-91581.9OGsrN.rst]: Done.

File: Modules/_datetimemodule.c (hunk 1 above)
Comment (pganssle) [reply Modules/_datetimemodule.c]: Done.

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by pganssle** [comment]
Buildbot failures seem unrelated:

- buildbot/AMD64 FreeBSD Shared PR — Build done. [Details](https://buildbot.python.org/all/#builders/203/builds/619)
- buildbot/x86 Gentoo Installed with X PR — Build done. [Details](https://buildbot.python.org/all/#builders/465/builds/599)
- buildbot/x86 Gentoo Non-Debug with X PR — Build done. [Details](https://buildbot.python.org/all/#builders/344/builds/600)

I'm going to go ahead and merge this.
