### PR TITLE
gh-110235: Raise `TypeError` for duplicate/unknown fields in PyStructSequence constructor

### LINKED ISSUE #110235: PyStructSequence constructor ignores unknown field names
# Bug report

PyStructSequence constructor takes two arguments: tuple and dict. The tuple specifies values for "visible" fields (i.e. what you get when interpret PyStructSequence as a tuple), the dict specifies values for fields that are accessible only by name (they are like `__slot__` attributes).

```pyshell
>>> import time
>>> time.struct_time((2023, 10, 2, 17, 50, 53, 0, 275, 0), {'tm_zone': 'GMT', 'tm_gmtoff': 0})
time.struct_time(tm_year=2023, tm_mon=10, tm_mday=2, tm_hour=17, tm_min=50, tm_sec=53, tm_wday=0, tm_yday=275, tm_isdst=0)
```

The problem is that all invalid names are silently ignored. It includes names of "visible" fields and typos.

```pyshell
>>> time.struct_time((0,)*9, {'tm_zone': 'GMT', 'tm_gmtoff': 0, 'tm_year': 2023, 'invalid': 1})
time.struct_time(tm_year=0, tm_mon=0, tm_mday=0, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=0, tm_yday=0, tm_isdst=0)
```

### Linked PRs
* gh-110258

### PR DESCRIPTION
**Pull request by XuehaiPan**
Fixes #110235

In this PR, we iterate over `dict` keys and check if there are duplicate fields provided by `sequence` or there are any unexpected field names.

* Issue: gh-110235

### CODE REVIEW

File: Objects/structseq.c [hunk 1]
```diff
@@ -216,10 +216,62 @@ structseq_new_impl(PyTypeObject *type, PyObject *arg, PyObject *dict)
...
+                    Py_DECREF(unknown_keys);
+                    return NULL;
+                }
+            }
+            Py_DECREF(key);
+        }
+        if (PySet_GET_SIZE(unknown_keys) > 0) {
+            PyErr_Format(PyExc_TypeError,
+                         "%.500s() got unexpected field name(s): %R",
+                         type->tp_name, unknown_keys);
```
Comment (XuehaiPan) [inline Objects/structseq.c]: Here we have a set rather than a list in the error message:

```python
TypeError: somestructseq() got unexpected field name(s): {'a', 'b', 'c'}
```

vs.

```python
TypeError: somestructseq() got unexpected field name(s): ['a', 'b', 'c']
```

Should we use a list instead?

File: Lib/test/test_structseq.py [hunk 2]
```diff
@@ -108,7 +156,23 @@ def __len__(self):
 
     def test_reduce(self):
         t = time.gmtime()
-        x = t.__reduce__()
+        cls, (tup, dct) = t.__reduce__()
```
Comment (serhiy-storchaka) [inline Lib/test/test_structseq.py]: Usually we do not have tests for `__reduce__()`. Instead we have tests for pickling and copying. I opened a separate issue for this: #110267.

File: Lib/test/test_structseq.py [hunk 3]
```diff
@@ -93,6 +94,53 @@ def test_constructor(self):
         s = "123456789"
         self.assertEqual("".join(t(s)), s)
 
+    def test_constructor_with_duplicate_fields(self):
+        t = time.struct_time
+        self.assertEqual(t("123456789"), tuple("123456789"))
+        self.assertEqual(t("1234567890"), tuple("123456789"))
+        self.assertEqual(t("1234567890").tm_zone, "0")
+        self.assertEqual(t("123456789", dict={"tm_zone": "some zone"}), tuple("123456789"))
+        self.assertEqual(t("123456789", dict={"tm_zone": "some zone"}).tm_zone, "some zone")
```
Comment (serhiy-storchaka) [inline Lib/test/test_structseq.py]: These tests do not actually test duplicate fields, so it is better to move them to `test_constructor`.

There is a test for positional first argument and keyword "dict" argument. I think that it is better to pass both arguments as positional for most tests, but add also a case for both passed by keyword.

**Review by serhiy-storchaka — COMMENTED** [review]
The code in the constructor is too complicated, and it slow down normal case, because it tests fields already passed in the sequence argument.

Simply count the number of fields found in the `dict` argument. If it less than the size of the dict, then raise a TypeError.

I think that it is not needed to make the error message more specific, test whether some of keys match the fields already specified in `sequence` argument or are not field names at all -- it only adds a lot of complicated code for a little gain. If users came with requests for more details, then we may provide them, but currently it is a waste of efforts.

File: Lib/test/test_structseq.py (hunk 2 above)
Comment (XuehaiPan) [reply Lib/test/test_structseq.py]: I reverted and moved these changes to another PR:

- #110272

**Comment by XuehaiPan** [comment]
I updated the implementation to only count the number of unexpected fields rather than list them in the error message.

**Review by serhiy-storchaka — COMMENTED** [review]
It is still too complicated. No need to check for multiple values for field.

**Comment by XuehaiPan** [comment]
> It is still too complicated. No need to check for multiple values for field.

The signature for `structseq.__new__()` is:

```python
SomeStructSeq(sequence: Iterable[Any], dict: Dict[str, Any]) -> SomeStructSeq
```

In this PR, I raise an error for values that come from both `sequence` and `dict`.

IMO, it should raise an error as we did for `namedtuple.__new__(*args, **kwargs)`. If a value is provided in both `args` and `kwargs`, it will raise a `TypeError`.

```python
mport collections
MyTuple = collections.namedtuple('MyTuple', ['a', 'b', 'c', 'd'])

MyTuple(1, 2, 3, 4, a=5, b=6)  # TypeError: MyTuple.__new__() got multiple values for argument 'a'
```

But `namedtuple` and `structseq` are slightly different. In `structseq`, the arguments `sequence` and `dict` do not have `*` and `**` unpacking.

```python
def func(a, **kwargs):
    pass

func(1, a=2)  # TypeError: func() got multiple values for argument 'a'
```

**Comment by serhiy-storchaka** [comment]
I meant that it will automatically raise TypeError if `dict` contains extra keys. No need to check it specially, and no need to generate more specific error message. Simply:

```python
for i in range(len, max_len):
    name = fields[i].name
    if name in dict:
        items[i] = dict[name]
        count++
    else:
        items[i] = None
    i++
if count < len(dict):
    raise TypeError("simple generic error message")
```
In C it will be just few additional lines of code.

**Comment by XuehaiPan** [comment]
> I meant that it will automatically raise TypeError if dict contains extra keys.

Thanks for the code snippet. My point is https://github.com/python/cpython/pull/110258#issuecomment-1746403387:

> The signature for `structseq.__new__()` is:
> 
> ```python
> SomeStructSeq(sequence: Iterable[Any], dict: Dict[str, Any]) -> SomeStructSeq
> ```
> 
> In this PR, I raise an error for values that come from both `sequence` and `dict`. If we don't do this, in the result tuple, the value from `dict` will override the value from `sequence`.

For example:

```python
time.struct_time
fields: [
    "tm_year",    #  0, visiable
    "tm_mon",     #  1, visiable
    "tm_mday",    #  2, visiable
    "tm_hour",    #  3, visiable
    "tm_min",     #  4, visiable
    "tm_sec",     #  5, visiable
    "tm_wday",    #  6, visiable
    "tm_yday",    #  7, visiable
    "tm_isdst",   #  8, visiable
    "tm_zone",    #  9, invisiable
    "tm_gmtoff",  # 10, invisible
]
n_sequence_fields: 9
n_unnamed_fields: 2
n_fields: 11
```

In the code snippet (https://github.com/python/cpython/pull/110258#issuecomment-1746424986), it will raise an error if there is a visible field name or an unknown name in `dict` (already part of this PR). But it will silently override the value for invisible fields when the value came from both `sequence` and `dict`.

```python
time.struct_time(seqeunce=list(range(10)), dict={'tm_zone': -1})
# tm_zone is firstly set from sequence[9], then it will be override by dict['tm_zone'] without raising an error
```

The implementation of this PR is roughly equivalent to:

```diff
  len = sequence.__len__()
  min_len = n_sequence_fields
  max_len = n_fields
  
  for i, value in enumerate(sequence):
      items[i] = value  # for i >= min_len, it will set invisible fields
  
  count = 0
- for i in range(len, max_len):
+ for i in range(min_len, max_len):
      name = fields[i].name
+     if i < len:
+         if name in dict:
+             raise TypeError("duplicate invisible field values")
+         continue
      if name in dict:
          items[i] = dict[name]
          count += 1
      else:
          items[i] = None
  if count < len(dict):
      raise TypeError("simple generic error message")
```

**Comment by XuehaiPan** [comment]
> passes your tests (ignoring error message). It raises error for your example

I check this and it works. I have updated my implementation to raise a single generic error.

File: Objects/structseq.c [hunk 4]
```diff
@@ -216,19 +216,34 @@ structseq_new_impl(PyTypeObject *type, PyObject *arg, PyObject *dict)
         res->ob_item[i] = Py_NewRef(v);
     }
     Py_DECREF(arg);
-    for (; i < max_len; ++i) {
-        PyObject *ob = NULL;
-        if (dict != NULL) {
-            const char *name = type->tp_members[i-n_unnamed_fields].name;
+    if (dict != NULL && PyDict_GET_SIZE(dict) > 0) {
```
Comment (XuehaiPan) [inline Objects/structseq.c:219]: I add this guard check before the for-loop to avoid unnecessary dictionary lookup for empty `dict`.

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by XuehaiPan** [comment]
Thanks for the code review and suggestions!
