### PR TITLE
gh-119109: improve `functools.partial` vectorcall with keywords

### LINKED ISSUE #128050: Race between `partial_vectorcall_fallback` and `_PyVectorcall_FunctionInline` under free-threading
# Bug report

### Bug description:

Repro:

Run the following Python code under v3.13.1t with thread-sanitizer enabled.
```
import concurrent.futures
import functools
import threading

def f(a, b):
  return a + b

def closure(b, g):
  b.wait()
  g(77)

num_threads = 8
with concurrent.futures.ThreadPoolExecutor(max_workers=num_threads) as executor:
  for _ in range(10000):
    b = threading.Barrier(num_threads)
    g = functools.partial(f, a=42)
    for _ in range(num_threads):
      executor.submit(functools.partial(closure, b, g))
```

Get:
```
==================
WARNING: ThreadSanitizer: data race (pid=130482)
  Read of size 8 at 0x7ff6e09ed1a8 by thread T2:
    #0 _PyVectorcall_FunctionInline /usr/local/google/home/phawkins/p/cpython/./Include/internal/pycore_call.h:129:5 (python3.13+0x1eaf8f) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #1 _PyObject_VectorcallTstate /usr/local/google/home/phawkins/p/cpython/./Include/internal/pycore_call.h:163:12 (python3.13+0x1eaf8f)
    #2 PyObject_Vectorcall /usr/local/google/home/phawkins/p/cpython/Objects/call.c:327:12 (python3.13+0x1eaf8f)
    #3 _PyEval_EvalFrameDefault /usr/local/google/home/phawkins/p/cpython/Python/generated_cases.c.h:813:23 (python3.13+0x3e24fb) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #4 _PyEval_EvalFrame /usr/local/google/home/phawkins/p/cpython/./Include/internal/pycore_ceval.h:119:16 (python3.13+0x3de62a) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #5 _PyEval_Vector /usr/local/google/home/phawkins/p/cpython/Python/ceval.c:1811:12 (python3.13+0x3de62a)
    #6 _PyFunction_Vectorcall /usr/local/google/home/phawkins/p/cpython/Objects/call.c (python3.13+0x1eb61f) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #7 _PyObject_VectorcallTstate /usr/local/google/home/phawkins/p/cpython/./Include/internal/pycore_call.h:168:11 (python3.13+0x571bb2) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #8 partial_vectorcall /usr/local/google/home/phawkins/p/cpython/./Modules/_functoolsmodule.c:252:16 (python3.13+0x571bb2)
    #9 _PyVectorcall_Call /usr/local/google/home/phawkins/p/cpython/Objects/call.c:273:16 (python3.13+0x1eb293) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #10 _PyObject_Call /usr/local/google/home/phawkins/p/cpython/Objects/call.c:348:16 (python3.13+0x1eb293)
    #11 PyObject_Call /usr/local/google/home/phawkins/p/cpython/Objects/call.c:373:12 (python3.13+0x1eb315) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #12 _PyEval_EvalFrameDefault /usr/local/google/home/phawkins/p/cpython/Python/generated_cases.c.h:1355:26 (python3.13+0x3e46e2) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #13 _PyEval_EvalFrame /usr/local/google/home/phawkins/p/cpython/./Include/internal/pycore_ceval.h:119:16 (python3.13+0x3de62a) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #14 _PyEval_Vector /usr/local/google/home/phawkins/p/cpython/Python/ceval.c:1811:12 (python3.13+0x3de62a)
    #15 _PyFunction_Vectorcall /usr/local/google/home/phawkins/p/cpython/Objects/call.c (python3.13+0x1eb61f) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #16 _PyObject_VectorcallTstate /usr/local/google/home/phawkins/p/cpython/./Include/internal/pycore_call.h:168:11 (python3.13+0x1ef5ef) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #17 method_vectorcall /usr/local/google/home/phawkins/p/cpython/Objects/classobject.c:70:20 (python3.13+0x1ef5ef)
    #18 _PyVectorcall_Call /usr/local/google/home/phawkins/p/cpython/Objects/call.c:273:16 (python3.13+0x1eb293) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #19 _PyObject_Call /usr/local/google/home/phawkins/p/cpython/Objects/call.c:348:16 (python3.13+0x1eb293)
    #20 PyObject_Call /usr/local/google/home/phawkins/p/cpython/Objects/call.c:373:12 (python3.13+0x1eb315) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #21 thread_run /usr/local/google/home/phawkins/p/cpython/./Modules/_threadmodule.c:337:21 (python3.13+0x564292) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #22 pythread_wrapper /usr/local/google/home/phawkins/p/cpython/Python/thread_pthread.h:243:5 (python3.13+0x4bd637) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)

  Previous write of size 8 at 0x7ff6e09ed1a8 by thread T8:
    #0 partial_vectorcall_fallback /usr/local/google/home/phawkins/p/cpython/./Modules/_functoolsmodule.c:224:21 (python3.13+0x571d8b) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #1 partial_vectorcall /usr/local/google/home/phawkins/p/cpython/./Modules/_functoolsmodule.c:238:16 (python3.13+0x571a06) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #2 _PyObject_VectorcallTstate /usr/local/google/home/phawkins/p/cpython/./Include/internal/pycore_call.h:168:11 (python3.13+0x1eafaa) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #3 PyObject_Vectorcall /usr/local/google/home/phawkins/p/cpython/Objects/call.c:327:12 (python3.13+0x1eafaa)
    #4 _PyEval_EvalFrameDefault /usr/local/google/home/phawkins/p/cpython/Python/generated_cases.c.h:813:23 (python3.13+0x3e24fb) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #5 _PyEval_EvalFrame /usr/local/google/home/phawkins/p/cpython/./Include/internal/pycore_ceval.h:119:16 (python3.13+0x3de62a) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #6 _PyEval_Vector /usr/local/google/home/phawkins/p/cpython/Python/ceval.c:1811:12 (python3.13+0x3de62a)
    #7 _PyFunction_Vectorcall /usr/local/google/home/phawkins/p/cpython/Objects/call.c (python3.13+0x1eb61f) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #8 _PyObject_VectorcallTstate /usr/local/google/home/phawkins/p/cpython/./Include/internal/pycore_call.h:168:11 (python3.13+0x571bb2) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #9 partial_vectorcall /usr/local/google/home/phawkins/p/cpython/./Modules/_functoolsmodule.c:252:16 (python3.13+0x571bb2)
    #10 _PyVectorcall_Call /usr/local/google/home/phawkins/p/cpython/Objects/call.c:273:16 (python3.13+0x1eb293) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #11 _PyObject_Call /usr/local/google/home/phawkins/p/cpython/Objects/call.c:348:16 (python3.13+0x1eb293)
    #12 PyObject_Call /usr/local/google/home/phawkins/p/cpython/Objects/call.c:373:12 (python3.13+0x1eb315) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #13 _PyEval_EvalFrameDefault /usr/local/google/home/phawkins/p/cpython/Python/generated_cases.c.h:1355:26 (python3.13+0x3e46e2) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #14 _PyEval_EvalFrame /usr/local/google/home/phawkins/p/cpython/./Include/internal/pycore_ceval.h:119:16 (python3.13+0x3de62a) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #15 _PyEval_Vector /usr/local/google/home/phawkins/p/cpython/Python/ceval.c:1811:12 (python3.13+0x3de62a)
    #16 _PyFunction_Vectorcall /usr/local/google/home/phawkins/p/cpython/Objects/call.c (python3.13+0x1eb61f) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #17 _PyObject_VectorcallTstate /usr/local/google/home/phawkins/p/cpython/./Include/internal/pycore_call.h:168:11 (python3.13+0x1ef5ef) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #18 method_vectorcall /usr/local/google/home/phawkins/p/cpython/Objects/classobject.c:70:20 (python3.13+0x1ef5ef)
    #19 _PyVectorcall_Call /usr/local/google/home/phawkins/p/cpython/Objects/call.c:273:16 (python3.13+0x1eb293) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #20 _PyObject_Call /usr/local/google/home/phawkins/p/cpython/Objects/call.c:348:16 (python3.13+0x1eb293)
    #21 PyObject_Call /usr/local/google/home/phawkins/p/cpython/Objects/call.c:373:12 (python3.13+0x1eb315) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #22 thread_run /usr/local/google/home/phawkins/p/cpython/./Modules/_threadmodule.c:337:21 (python3.13+0x564292) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
    #23 pythread_wrapper /usr/local/google/home/phawkins/p/cpython/Python/thread_pthread.h:243:5 (python3.13+0x4bd637) (BuildId: 9c1c16fb1bb8a435fa6fa4c6944da5d41f654e96)
```

`partial_vectorcall_fallback` sets `vectorcall` to nullptr if it decides to fall back to a non-vectorcall code path:
https://github.com/python/cpython/blob/b92f101d0f19a1df32050b8502cfcce777b079b2/Modules/_functoolsmodule.c#L366

But this races with the code that reads an object's `vectorcall` in the core function call code: https://github.com/python/cpython/blob/b92f101d0f19a1df32050b8502cfcce777b079b2/Include/internal/pycore_call.h#L128

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

### Linked PRs
* gh-136418

### PR DESCRIPTION
**Pull request by dg-pb**
(Potentially closes https://github.com/python/cpython/issues/128050)

This IMO is the best approach to resolve fallback "issue". It:
a) Eliminates the need for the fallback or any need to switch between implementation after initial construction
b) Delivers performance benefits for vectorcall when `partial` has keywords

Benchmark:
```bash
# BENCH 2 ARGS
# ------------
S="
from functools import partial
f=lambda a, b: a - b
p1 = partial(f)
p2 = partial(f, b=2)
l = lambda a: f(a, b=2)
"

$PYCMD -c "${S}; print(p1(1, 2))"   # -1     | -1     |
$PYCMD -c "${S}; print(p2(1))"      # -1     | -1     |
                                    # BEFORE | AFTER  | %CHN | LAMBDA LB
$PYCMD -m timeit -s $S 'p1(1, 2)'   #  87 ns |  85 ns |      |
$PYCMD -m timeit -s $S 'p1(1, b=2)' # 100 ns |  96 ns |      |
$PYCMD -m timeit -s $S 'p2(1)'      # 240 ns | 135 ns | -45% |  94 ns
$PYCMD -m timeit -s $S 'p2(a=1)'    # 350 ns | 160 ns | -55% | 110 ns


# BENCH 10 ARGS
# -------------
S="
from functools import partial
func = lambda a, b, c, d, e, f, g, h, i, j: (a + b + c + d + e + f + g + h + i + j)
p = partial(func, f=5, g=6, h=7, i=8, j=9)
l = lambda a, b, c, d, e, f=5, g=6, h=7, i=8, j=9: func(a, b, c, d, e, f=f, g=g, h=h, i=i, j=j)
"

C0="${S}; print(p(0, 1, 2, 3, 4))"
C1='p(0, 1, 2, 3, 4)'
C2='p(a=0, b=1, c=2, d=3, e=4)'                             # disjoint kw and pto_kw
C3='p(a=0, b=1, c=2, d=3, e=4, f=5, g=6)'                   # kw partially overlaps pto_kw
C4='p(a=0, b=1, c=2, d=3, e=4, f=5, g=6, h=7, i=8, j=9)'    # kw overrides pto_kw


$PYCMD -c $C0               #  45     | 45     |
                            #  BEFORE | AFTER  | %CHN | LAMBDA LB
$PYCMD -m timeit -s $S $C1  #  440 ns | 320 ns | -28% | 240 ns
$PYCMD -m timeit -s $S $C2  #  890 ns | 440 ns | -50% | 260 ns
$PYCMD -m timeit -s $S $C3  # 1000 ns | 600 ns | -40% | 270 ns
$PYCMD -m timeit -s $S $C4  # 1250 ns | 700 ns | -44% | 300 ns

# FUNCTION CALL - 210 ms
$PYCMD -m timeit -s $S 'f(a=0, b=1, c=2, d=3, e=4, f=5, g=6, h=7, i=8, j=9)'
```

No penalty for calls without `pto_kwds`.
Non negligible speed improvement for calls with `pto_kwds`: 27 - 55%

* Issue: gh-119109

### CODE REVIEW

File: Modules/_functoolsmodule.c [hunk 1]
```diff
@@ -367,36 +355,55 @@ partial_vectorcall(partialobject *pto, PyObject *const *args,
...
-        PyObject **newargs = (PyObject **)args - 1;
-        PyObject *tmp = newargs[0];
-        newargs[0] = pto_args[0];
-        PyObject *ret = _PyObject_VectorcallTstate(tstate, pto->fn,
-                                                   newargs, nargs + 1, kwnames);
-        newargs[0] = tmp;
-        return ret;
+        for (Py_ssize_t i=0; i < nkwds; i++) {
+            key = PyTuple_GET_ITEM(kwnames, i);
+            if (PyDict_SetItem(new_kw, key, args[nargs + i]) != 0) {
```
Comment (rruuaanng) [inline Modules/_functoolsmodule.c]: Maybe could change to
```C
if (PyDict_SetItem(new_kw, key, args[nargs + i]))
```

File: Modules/_functoolsmodule.c [hunk 2]
```diff
@@ -367,36 +355,55 @@ partial_vectorcall(partialobject *pto, PyObject *const *args,
...
-    }
-
+    /* Divergence on whether pto has kwds */
+    Py_ssize_t tot_nargs = pto_nargs + nargs - pto_phcount;
+    Py_ssize_t tot_nkwds;
+    Py_ssize_t tot_nargskw;
     PyObject **pto_args = _PyTuple_ITEMS(pto->args);
-    Py_ssize_t pto_nargs = PyTuple_GET_SIZE(pto->args);
+    PyObject *new_kw, *key, *val;
+    if (pto_nkwds == 0) {
```
Comment (rruuaanng) [inline Modules/_functoolsmodule.c]: I think there should be a blank line between the declaration area and the statements.
```
PyObject *new_kw, *key, *val;
/* blank line */
if (...) {
...
}
...

```

**Comment by rhettinger** [comment]
Perhaps @vstinner has the time and interest in looking at this.

**Comment by dg-pb** [comment]
This is a very possible candidate.

However, looking at some further performance improvements. I.e. pre-caching key and value tuples.

One issue is that `keywords` can be modified, thus would need to reset cache on such event. Looking at dict watchers, but no luck yet.

Any help would be appreciated. I.e. How to know if `dict` has been modified without thorough comparison?

**Comment by dg-pb** [comment]
I think it is a good compromise between simplicity and performance now.

One micro-optimization that I couldn't figure out how to do simply is pre-storing `kwnames` tuple so it doesn't need to be created on every call. It would drop another ~50 ns.

Not sure how much sense it makes yet, but I posted https://github.com/faster-cpython/ideas/issues/699 in relation to this.

Ready for review now.

File: Modules/_functoolsmodule.c [hunk 3]
```diff
@@ -422,20 +499,22 @@ partial_vectorcall(partialobject *pto, PyObject *const *args,
             }
         }
         assert(j == pto_phcount);
-        if (nargskw > pto_phcount) {
-            memcpy(stack + pto_nargs, args + j, (nargskw - j) * sizeof(PyObject*));
+        /* Add remaining args from new_args */
+        if (nargs > pto_phcount) {
+            memcpy(stack + pto_nargs, args + j, (nargs - j) * sizeof(PyObject*));
```
Comment (rruuaanng) [inline Modules/_functoolsmodule.c:537]: When using `sizeof` on a structure, you cannot use pointer types, because pointer types are **8 bytes** on most machines, not the size of the structure.

File: Modules/_functoolsmodule.c [hunk 4]
```diff
@@ -422,20 +499,22 @@ partial_vectorcall(partialobject *pto, PyObject *const *args,
...
         }
     }
     else {
-        tot_nargs = pto_nargs + nargs;
-        /* Copy to new stack, using borrowed references */
         memcpy(stack, pto_args, pto_nargs * sizeof(PyObject*));
-        memcpy(stack + pto_nargs, args, nargskw * sizeof(PyObject*));
+        memcpy(stack + pto_nargs, args, nargs * sizeof(PyObject*));
```
Comment (rruuaanng) [inline Modules/_functoolsmodule.c:542]: You should only use `sizeof(PyObject)` to get the size of a structure.

File: Modules/_functoolsmodule.c [hunk 5]
```diff
@@ -367,53 +376,121 @@ partial_vectorcall(partialobject *pto, PyObject *const *args,
...
+        tot_nkwds = pto_nkwds + nkwds;
+        tot_nargskw = tot_nargs + tot_nkwds;
+        ALLOCATE_STACK(PyObject, tot_nargskw, small_stack, stack);
 
-    Py_ssize_t tot_nargskw = pto_nargs + nargskw - pto_phcount;
-    if (tot_nargskw <= (Py_ssize_t)Py_ARRAY_LENGTH(small_stack)) {
-        stack = small_stack;
+        if (nkwds) {
+            /* if !pto_nkwds & nkwds, then simply append kw */
+            memcpy(stack + tot_nargs, args + nargs, nkwds * sizeof(PyObject*));
```
Comment (rruuaanng) [inline Modules/_functoolsmodule.c:449]: Here, too, the reasons are the same as other.

File: Modules/_functoolsmodule.c (hunk 3 above)
Comment (dg-pb) [reply Modules/_functoolsmodule.c:537]: I beieve it is the size of the pointer is what is needed.

```C
PyObject **stack
```

**Comment by dg-pb** [comment]
Was wandering if it might be worth factoring out macros for private use.

File: Modules/_functoolsmodule.c [hunk 6]
```diff
@@ -355,31 +355,41 @@ partial_descr_get(PyObject *self, PyObject *obj, PyObject *type)
...
-Py_NO_INLINE static PyObject *
-partial_vectorcall_fallback(PyThreadState *tstate, partialobject *pto,
-                            PyObject *const *args, size_t nargsf,
-                            PyObject *kwnames)
-{
-    pto->vectorcall = NULL;
-    Py_ssize_t nargs = PyVectorcall_NARGS(nargsf);
-    return _PyObject_MakeTpCall(tstate, (PyObject *)pto, args, nargs, kwnames);
-}
+#define ALLOCATE_STACK(elsize, size, small_stack, stack)        \
```
Comment (picnixz) [inline Modules/_functoolsmodule.c]: Ideally, those macros should be kept within the function's definition since they return. Then, you can `#undef` them accordingly (different error handling might be needed if they are used in more than one function)

File: Modules/_functoolsmodule.c [hunk 7]
```diff
@@ -355,31 +355,41 @@ partial_descr_get(PyObject *self, PyObject *obj, PyObject *type)
...
+    do {                                                        \
+        if (size <= (Py_ssize_t)Py_ARRAY_LENGTH(small_stack)) { \
+            stack = small_stack;                                \
+        }                                                       \
+        else {                                                  \
+            stack = PyMem_Malloc(size * elsize);                \
```
Comment (picnixz) [inline Modules/_functoolsmodule.c]: Strictly speaking, `size * elsize` can overflow before being passed to `PyMem_Malloc`, (although this would require a LOT of arguments which I'm not sure it's possible to pass to) but you can add a comment saying so (even though the previous code wasn't checking this I think?)

File: Modules/_functoolsmodule.c [hunk 8]
```diff
@@ -477,7 +561,6 @@ partial_setvectorcall(partialobject *pto)
     }
 }
 
-
```
Comment (picnixz) [inline Modules/_functoolsmodule.c]: Unrelated change.

File: Misc/NEWS.d/next/Library/2024-10-17-01-12-22.gh-issue-119109.u4hcvb.rst [hunk 9]
```diff
@@ -0,0 +1 @@
+:func:`functools.partial` calls are now faster when keyword arguments are used.
```
Comment (picnixz) [inline Misc/NEWS.d/next/Library/2024-10-17-01-12-22.gh-issue-119109.u4hcvb.rst:1]: Can you also report the performance gain? that would help selling the product more. Also, is this correct that it should be read as "use keyword arguments instead of positional arguments"? is it a recommendation for using keyword arguments? (because that's how I read it). 

If the recommendation should only be followed when possible, you can write:

```rst
Calling :func:`functools.partial` objects with bound keyword arguments are XXX% faster.
```

Comment (dg-pb) [reply Misc/NEWS.d/next/Library/2024-10-17-01-12-22.gh-issue-119109.u4hcvb.rst:1]: No, it is "use cases with keyword arguments are now faster" it is like for like, before versus after:
```
partial(foo, a=1)()
```
will now be faster

Comment (picnixz) [reply Misc/NEWS.d/next/Library/2024-10-17-01-12-22.gh-issue-119109.u4hcvb.rst:1]: To be perfectly clear:

- `partial(foo, a=1)` is not faster than before.
- `x()` is faster when `x = partial(foo, a=1)`.

If this is the case, then I think my suggestion would be less confusing, because otherwise, the current wording either reads as "calls to the functools.partial function constructor" or "calls to functools.partial objects are faster if you use keyword arguments" (at least to me). OTOH, "partial objects with bound keyword arguments" means an instance of functools.partial that was constructed with keyword arguments and which we call normally.

**Comment by picnixz** [comment]
Is the performance change a direct effect of the simplification or is this the other way around? (namely, can we decouple the performance gains from the simplification?)

**Comment by dg-pb** [comment]
Your title change is incorrect, this has wider implications.

It removes dynamic switching, which causes issues with free threading.

The fact that `vectorcall` will be used in more cases, which is faster is only a benefit. Although from users perspective the performance gain is the only thing worth mentioning.

**Comment by dg-pb** [comment]
> Is the performance change a direct effect of the simplification

yes, it is one atomic change. There is no way to split it.

File: Misc/NEWS.d/next/Library/2024-10-17-01-12-22.gh-issue-119109.u4hcvb.rst (hunk 9 above)
Comment (dg-pb) [reply Misc/NEWS.d/next/Library/2024-10-17-01-12-22.gh-issue-119109.u4hcvb.rst:1]: So:
```rst
Calling :func:`functools.partial` objects with bound keyword arguments are now up to 50% faster.
```
?

File: Modules/_functoolsmodule.c (hunk 7 above)
Comment (dg-pb) [reply Modules/_functoolsmodule.c]: Yeah, this is a direct copy of what was used before, I did not devise this myself. Will add comment, useful information I think so too.

File: Misc/NEWS.d/next/Library/2024-10-17-01-12-22.gh-issue-119109.u4hcvb.rst (hunk 9 above)
Comment (picnixz) [reply Misc/NEWS.d/next/Library/2024-10-17-01-12-22.gh-issue-119109.u4hcvb.rst:1]: Yes, something like this. Before committing this, it would be good if a native English speaker were to decide if this is correct for them as well (cc @ZeroIntensity)

File: Modules/_functoolsmodule.c (hunk 6 above)
Comment (dg-pb) [reply Modules/_functoolsmodule.c]: I see myself needing this in other places in the future and if there are enough usages I would probably suggest to factor these out to more generic location. 

So in case that happens, I think it is best to factor out error handling outside to keep them more generic (even if they are not used anywhere else for now).

They can be undefined after `partial_vectorcall`.

Comment (erlend-aasland) [reply Modules/_functoolsmodule.c]: Please follow up Bénédikt's remark.

Comment (picnixz) [reply Modules/_functoolsmodule.c]: By the way, those can be `static inline` functions actually, no?

Comment (dg-pb) [reply Modules/_functoolsmodule.c:358]: Yup, it works, but there is an issue as then `static inline` is bound to one type. Although both cases here are `PyObject` I personally keep this macro generic as it comes handy from time to time for different types.

So it is either:
a) Keep a more generic macro so that it can be copied and re-used for different types
b) make it more strict `static inline`, which is arguably a bit better given this isolated case, but then it will not be `copy-pastable-potentially-factoroutable-macro-which-works-for-any-type`.

I would prefer to keep it as macro as I like sensibly generic stuff, but don't mind changing to `static inline` if there are objections.

Comment (dg-pb) [reply Modules/_functoolsmodule.c:358]: There is another alternative, which would eliminate this macro all together.

I could just allocate it with maximum possible size. E.g.:
```
bound_keywords = {'a': 1, 'b': 2, 'c': 3}
call_keywords = {'a': 1, 'b': 2, 'c': 3}
# Then:
initialized_stack_size = 6
used_stack_size = 3
```

Currently it still does allocate more than needed for `kwtail`, but it is short lived, while option above would mean it would stay over-allocated throughout function call.

What is the worst case? Say 256 keyword arguments on `partial.__call__` and all of them override bound ones. This would mean 1kb overallocation throughout function call. If this is acceptable, I can eliminate the need for macro.

Comment (dg-pb) [reply Modules/_functoolsmodule.c:358]: But I might still need to do this for `tot_kwnames: tuple` so not sure if it is possible...

It was a while ago, need to reexamine...

Comment (dg-pb) [reply Modules/_functoolsmodule.c]: Did post-resizing instead. No need for macros or inlines anymore.

File: Modules/_functoolsmodule.c [hunk 10]
```diff
@@ -355,31 +355,20 @@ partial_descr_get(PyObject *self, PyObject *obj, PyObject *type)
...
-    return _PyObject_MakeTpCall(tstate, (PyObject *)pto, args, nargs, kwnames);
-}
-
 static PyObject *
 partial_vectorcall(PyObject *self, PyObject *const *args,
                    size_t nargsf, PyObject *kwnames)
 {
     partialobject *pto = _PyPartialObject_CAST(self);;
     PyThreadState *tstate = _PyThreadState_GET();
+    /* Sizes */
```
Comment (erlend-aasland) [inline Modules/_functoolsmodule.c]: This comments adds no value. It is obvious from the code (both the data types and APIs called) that these are sizes.

File: Modules/_functoolsmodule.c [hunk 11]
```diff
@@ -443,22 +519,36 @@ partial_vectorcall(PyObject *self, PyObject *const *args,
...
     return ret;
+
+error_0:
+    Py_DECREF(tot_kwnames);
+error_1:
+    Py_XDECREF(pto_kw_merged);
+error_2:
+    if (stack != small_stack) {
+        PyMem_Free(stack);
+    }
```
Comment (erlend-aasland) [inline Modules/_functoolsmodule.c]: I would encourage you to rethink the error handling in this PR. This label mess does not make for readable code. Perhaps refactoring can help.

File: Modules/_functoolsmodule.c (hunk 10 above)
Comment (dg-pb) [reply Modules/_functoolsmodule.c]: You mean all of them?

They are helpful to me personally to follow the code.

I can remove them if this isn't the case for others.

Comment (erlend-aasland) [reply Modules/_functoolsmodule.c]: I meant this comment. Line 364.

File: Modules/_functoolsmodule.c (hunk 11 above)
Comment (dg-pb) [reply Modules/_functoolsmodule.c]: Labels removed.

Comment (dg-pb) [reply Modules/_functoolsmodule.c]: Each was used only once eventually so just put the code back to its place.

File: Modules/_functoolsmodule.c (hunk 10 above)
Comment (erlend-aasland) [reply Modules/_functoolsmodule.c]: ... and the comment in line 544.

File: Modules/_functoolsmodule.c [hunk 12]
```diff
@@ -388,53 +377,152 @@ partial_vectorcall(PyObject *self, PyObject *const *args,
...
+                    pto_kw_merged = PyDict_Copy(pto->kw);
+                    if (pto_kw_merged == NULL) {
+                        if (stack != small_stack) {
+                            PyMem_Free(stack);
+                        }
+                        return NULL;
+                    }
+                }
+                if (PyDict_SetItem(pto_kw_merged, key, val) < 0) {
+                    Py_XDECREF(pto_kw_merged);
```
Comment (erlend-aasland) [inline Modules/_functoolsmodule.c]:
```suggestion
                    Py_DECREF(pto_kw_merged);
```

File: Modules/_functoolsmodule.c [hunk 13]
```diff
@@ -388,53 +377,152 @@ partial_vectorcall(PyObject *self, PyObject *const *args,
...
+            }
+        }
+        Py_ssize_t n_merges = nkwds - n_tail;
+
+        /* Create tot_kwnames */
+        tot_kwnames = PyTuple_New(pto_nkwds + n_tail);
+        for (Py_ssize_t i = 0; i < n_tail; ++i) {
+            key = stack[tot_nargskw + i];
+            PyTuple_SET_ITEM(tot_kwnames, pto_nkwds + i, key);
+            Py_INCREF(key);
```
Comment (erlend-aasland) [inline Modules/_functoolsmodule.c]:
```suggestion
            key = Py_NewRef(stack[tot_nargskw + i]);
            PyTuple_SET_ITEM(tot_kwnames, pto_nkwds + i, key);
```

File: Modules/_functoolsmodule.c [hunk 14]
```diff
@@ -388,53 +377,152 @@ partial_vectorcall(PyObject *self, PyObject *const *args,
...
+        if (n_merges && stack != small_stack) {
+            tmp_stack = PyMem_Realloc(stack, (tot_nargskw - n_merges) * sizeof(PyObject *));
+            if (tmp_stack == NULL) {
+                Py_DECREF(tot_kwnames);
+                Py_XDECREF(pto_kw_merged);
+                if (stack != small_stack) {
+                    PyMem_Free(stack);
+                }
+                PyErr_NoMemory();
+                return NULL;
```
Comment (erlend-aasland) [inline Modules/_functoolsmodule.c]:
```suggestion
                return PyErr_NoMemory();
```

File: Modules/_functoolsmodule.c [hunk 15]
```diff
@@ -388,53 +377,152 @@ partial_vectorcall(PyObject *self, PyObject *const *args,
...
+            key = stack[tot_nargskw + i];
+            PyTuple_SET_ITEM(tot_kwnames, pto_nkwds + i, key);
+            Py_INCREF(key);
+        }
+
+        /* Copy pto_kw_merged to stack */
+        Py_ssize_t pos = 0, i = 0;
+        while (PyDict_Next(n_merges ? pto_kw_merged : pto->kw, &pos, &key, &val)) {
+            PyTuple_SET_ITEM(tot_kwnames, i, key);
+            Py_INCREF(key);
```
Comment (erlend-aasland) [inline Modules/_functoolsmodule.c]:
```suggestion
            PyTuple_SET_ITEM(tot_kwnames, i, Py_NewRef(key));
```

File: Modules/_functoolsmodule.c (hunk 10 above)
Comment (erlend-aasland) [reply Modules/_functoolsmodule.c]: By the way, why did you move the intermingled declarations? They were perfectly fine where they were, at least `nargskw`, `pto_nargs`. This leads to unneeded clutter for the reviewers and unneeded diff churn. Unless the variables are used earlier (it does not look like that to me), please revert these changes.

`pto_nkwds` and `nkwds` can also be declared just above where they are used.

File: Misc/NEWS.d/next/Library/2024-10-17-01-12-22.gh-issue-119109.u4hcvb.rst (hunk 9 above)
Comment (ZeroIntensity) [reply Misc/NEWS.d/next/Library/2024-10-17-01-12-22.gh-issue-119109.u4hcvb.rst:1]: English is hard! I'd be more in favor of something like this:

```rst
Calling objects wrapped in :func:`functools.partial` with keyword arguments, both on the call site of :func:`functools.partial` and on calls to the returned object, are now up to 50% faster.
```

For `functools.partial`-wrapped objects, we have precedent for the phrase "x wrapped in `functools.partial`" from the [inspect docs](https://docs.python.org/3/library/inspect.html#inspect.isgeneratorfunction).

Comment (dg-pb) [reply Misc/NEWS.d/next/Library/2024-10-17-01-12-22.gh-issue-119109.u4hcvb.rst:1]: This only affects `__call__`, not `__new__`.

```rst
Calling objects wrapped in :func:`functools.partial` with keyword arguments is now up to 50% faster.
```
?

But to me it reads as if I am calling an object which was wrapped and not the wrapper which was constructed from the object.

Comment (ZeroIntensity) [reply Misc/NEWS.d/next/Library/2024-10-17-01-12-22.gh-issue-119109.u4hcvb.rst:1]: I'm getting confused. Both of these are faster with this PR, right?

```py
x = partial(foo, bar=1)
x()
```

```py
y = partial(foo)
y(bar=1)
```

Comment (dg-pb) [reply Misc/NEWS.d/next/Library/2024-10-17-01-12-22.gh-issue-119109.u4hcvb.rst:1]: Only the former. Or to be more specific:

When there are bound keyword arguments:
```python
x = partial(foo, bar=1)    # This is the same speed as before
```
This becomes faster as it uses `vectorcall`:
```
x()
```

File: Modules/_functoolsmodule.c (hunk 7 above)
Comment (dg-pb) [reply Modules/_functoolsmodule.c]: I have removed the comment. Although I agree that this might need to be noted, I don't think this is the place.

The root of this pattern is in other places, just `grep _PY_FASTCALL_SMALL_STACK` - this points to where it initiated.

Thus, I think this needs to be investigated separately at its source, and this specific case just adapts, thus the comment would be misplaced.

File: Modules/_functoolsmodule.c (hunk 10 above)
Comment (erlend-aasland) [reply Modules/_functoolsmodule.c]: My last remark in this conversation has not been addressed.

Comment (dg-pb) [reply Modules/_functoolsmodule.c]: Yup, missed it completely. I think you wrote it at the same time I pressed resolve.

It was simply clearer to have them in the same place. I agree moving things about when minor adjustments are made can be inconvenient. However, I don't see how this is a big deal when the method is pretty much rewritten and these are the only 2 lines that are left (exaggerating a bit :)).

Either way, I moved all of the declarations after the error handling - that does makes more sense.

Comment (dg-pb) [reply Modules/_functoolsmodule.c]: Let me know if it is ok now.

File: Modules/_functoolsmodule.c [hunk 16]
```diff
@@ -401,53 +385,143 @@ partial_vectorcall(PyObject *self, PyObject *const *args,
...
+                /* Copy keyword tail to stack */
+                stack[tot_nargs + pto_nkwds + n_tail] = val;
+                stack[tot_nargskw + n_tail] = key;
+                n_tail++;
+            }
+        }
+        Py_ssize_t n_merges = nkwds - n_tail;
+
+        /* Create total kwnames */
+        tot_kwnames = PyTuple_New(tot_nkwds - n_merges);
```
Comment (kumaraditya303) [inline Modules/_functoolsmodule.c:484]: missing NULL check

File: Modules/_functoolsmodule.c [hunk 17]
```diff
@@ -400,53 +384,149 @@ partial_vectorcall(PyObject *self, PyObject *const *args,
...
+                        }
+                        return NULL;
+                    }
+                }
+                if (PyDict_SetItem(pto_kw_merged, key, val) < 0) {
+                    Py_DECREF(pto_kw_merged);
+                    if (stack != small_stack) {
+                        PyMem_Free(stack);
+                    }
+                    return NULL;
```
Comment (serhiy-storchaka) [inline Modules/_functoolsmodule.c]: These lines are repeated multiple times. I suggest to move them to the end of the function and use `goto`.

File: Modules/_functoolsmodule.c [hunk 18]
```diff
@@ -400,53 +384,149 @@ partial_vectorcall(PyObject *self, PyObject *const *args,
...
+                stack[tot_nargskw + n_tail] = key;
+                n_tail++;
+            }
+        }
+        Py_ssize_t n_merges = nkwds - n_tail;
+
+        /* Create total kwnames */
+        tot_kwnames = PyTuple_New(tot_nkwds - n_merges);
+        if (tot_kwnames == NULL) {
+            if (stack != small_stack) {
```
Comment (serhiy-storchaka) [inline Modules/_functoolsmodule.c]:
```suggestion
            Py_XDECREF(pto_kw_merged);
            if (stack != small_stack) {
```

File: Modules/_functoolsmodule.c [hunk 19]
```diff
@@ -400,53 +384,149 @@ partial_vectorcall(PyObject *self, PyObject *const *args,
...
+        }
+
+        /* Copy pto_keywords with overlapping call keywords merged */
+        Py_ssize_t pos = 0, i = 0;
+        while (PyDict_Next(n_merges ? pto_kw_merged : pto->kw, &pos, &key, &val)) {
+            PyTuple_SET_ITEM(tot_kwnames, i, Py_NewRef(key));
+            stack[tot_nargs + i] = val;
+            i++;
+        }
+        Py_XDECREF(pto_kw_merged);
```
Comment (serhiy-storchaka) [inline Modules/_functoolsmodule.c:504]:
```suggestion
        assert(i == tot_nkwds - n_merges);
        Py_XDECREF(pto_kw_merged);
```

File: Modules/_functoolsmodule.c [hunk 20]
```diff
@@ -400,53 +384,149 @@ partial_vectorcall(PyObject *self, PyObject *const *args,
...
         }
+        for (Py_ssize_t i = 0; i < n_tail; ++i) {
+            key = Py_NewRef(stack[tot_nargskw + i]);
+            PyTuple_SET_ITEM(tot_kwnames, pto_nkwds + i, key);
+        }
+
+        /* Copy pto_keywords with overlapping call keywords merged */
+        Py_ssize_t pos = 0, i = 0;
+        while (PyDict_Next(n_merges ? pto_kw_merged : pto->kw, &pos, &key, &val)) {
+            PyTuple_SET_ITEM(tot_kwnames, i, Py_NewRef(key));
```
Comment (serhiy-storchaka) [inline Modules/_functoolsmodule.c:499]:
```suggestion
            assert(i < tot_nkwds - n_merges);
            PyTuple_SET_ITEM(tot_kwnames, i, Py_NewRef(key));
```

File: Modules/_functoolsmodule.c [hunk 21]
```diff
@@ -400,53 +384,149 @@ partial_vectorcall(PyObject *self, PyObject *const *args,
...
+            stack[tot_nargs + i] = val;
+            i++;
+        }
+        Py_XDECREF(pto_kw_merged);
+
+        /* Resize Stack if the call has keywords */
```
Comment (serhiy-storchaka) [inline Modules/_functoolsmodule.c]: Is it needed? The stack can be slightly overallocated, but is this a problem?

File: Modules/_functoolsmodule.c [hunk 22]
```diff
@@ -400,53 +384,149 @@ partial_vectorcall(PyObject *self, PyObject *const *args,
...
     }
 
-    Py_ssize_t tot_nargs;
+    /* Copy Positionals to stack */
     if (pto_phcount) {
-        tot_nargs = pto_nargs + nargs - pto_phcount;
         Py_ssize_t j = 0;       // New args index
         for (Py_ssize_t i = 0; i < pto_nargs; i++) {
-            if (pto_args[i] == pto->placeholder) {
+            if (pto_args[i] == pto->placeholder){
```
Comment (serhiy-storchaka) [inline Modules/_functoolsmodule.c]:
```suggestion
            if (pto_args[i] == pto->placeholder) {
```

File: Modules/_functoolsmodule.c (hunk 21 above)
Comment (dg-pb) [reply Modules/_functoolsmodule.c]: In theory this can grow to moderate size.

E.g.
```
len(pto_kwds) = 100
len(kwds) = 100
set(pto_kwds) == set(kwds)

len(stack) = 300
len(used_stack) = 100

say all keys and values are 1-character strings.
Then, size of used objects is 100 * 2 * 42 = 8400.
Over-allocated memory is 200 * 8 = 1600.
```
So that is 20% of extra memory.

Of course, this is both overestimation and an extreme case.

But still, maybe it is a good idea to eliminate 0.1% of extreme cases.

github search:
* `/\bpartial\(/` - 900K files
* `/\bpartial\((.*=){7,}.*/` - 1K files

So I say maybe instead of completely removing it, could change `if (nkwds && ...)` to `if (nkwds > 6 && ...)`.

This would eliminate performance overhead for 99% of cases and would safeguard against unconventional usage.

Also, for say 1 keyword argument, reallocation can have a visible performance impact, but for 7 or more, it will be a negligible percentage of total.

Comment (serhiy-storchaka) [reply Modules/_functoolsmodule.c]: I am worrying more about the code complexity than performance and memory consumption. Although resizing the stack takes a time.

If you want to leave it and make it conditional, use something like `nkwds + n_merges > init_stack_size/2`, so the stack will only be resized if this saves significant amount memory.

Comment (dg-pb) [reply Modules/_functoolsmodule.c]: I am in favour of keeping this for now. Given the whole block can be removed without breaking anything at any time, I think this is more like a "soft complexity". I will see to a bit better rule and add a comment.

**Review by serhiy-storchaka — APPROVED** [review]
LGTM. :+1:

**Comment by kumaraditya303** [comment]
No refleaks:

```console
❯ ./python.exe -m test -R 3:3 test_functools
Using random seed: 458260461
0:00:00 load avg: 1.72 Run 1 test sequentially in a single process
0:00:00 load avg: 1.72 [1/1] test_functools
beginning 6 repetitions. Showing number of leaks (. for 0 or less, X for 10 or more)
123:456
XX. ...
0:00:02 load avg: 1.66 [1/1] test_functools passed

== Tests result: SUCCESS ==

1 test OK.

Total duration: 2.1 sec
Total tests: run=321 skipped=1
Total test files: run=1/1
Result: SUCCESS
```

File: Modules/_functoolsmodule.c (hunk 21 above)
Comment (dg-pb) [reply Modules/_functoolsmodule.c]:
```C
Py_ssize_t noveralloc = n_merges + nkwds
if (noveralloc > 6 && noveralloc * 10 > init_stack_size && ...) {
```

E.g.: For `init_stack_size = 1000` overallocation of 100 or more would be trimmed.

**Comment by dg-pb** [comment]
> No refleaks:

I get the same on `main`.

And also the same if I remove all tests except `test_functools:TestImportTime`.

Maybe not related to this PR?

EDIT: I assumed this shows that there are refleaks? Or am I failing to interpret something? Never used `-R` - a bit more explicit comment would be much appreciated.

File: Modules/_functoolsmodule.c (hunk 21 above)
Comment (kumaraditya303) [reply Modules/_functoolsmodule.c]: I agree with Serhiy that resizing part  is more complex than needed, also the resizing is dependent on the underlying allocator, some allocators would return the same block if the under allocation is not significant like on mimalloc. I think that this part should be removed altogether, the extreme cases shouldn't really need to be optimised.

**Comment by kumaraditya303** [comment]
> I assumed this shows that there are refleaks? Or am I failing to interpret something? Never used -R - a bit more explicit comment would be much appreciated.

The output I posted means that there are no leaks, -R is used to check for reference leaks and 3:3 indicates the numbers of runs to checks for leaks.

See https://devguide.python.org/testing/run-write-tests/

**Comment by kumaraditya303** [comment]
I think the resizing logic is unnecessary and adds extra complexity, would you simplify it to what Serhiy suggested or alternatively remove it altogether @dg-pb?

**Comment by dg-pb** [comment]
> simplify it to what Serhiy suggested

I don't think it was simplification. He did propose an alternative and I incorporated it into the logic.

Why I kept the old one `noveralloc > 6` is because without it:
```python
# only: (noveralloc > init_stack_size / 2)
p = partial(a=1)
f(a=2)
# initial stack size: 3
# used stack size: 1
```
Thus, would be kicking in too often.
And I took 10 instead of 2, as it wouldn't capture cases such as:
initial stack size = 1000
used stack size = 499

10% is I think a good number, given we are talking about the pool of 0.01% of cases.

I feel that what is currently there provides necessary protection at minimal cost and is unlikely to cause any issues.

But if you have better rationale in mind, I am open to further amendments.

> alternatively remove it altogether

Things like recursion of `partial` objects or `partial` calls with very high number of keyword arguments, although not common and not the best idea for production code, but given description of `partial` object are perfectly valid use cases that can be useful in prototyping/testing something quickly.

"Anything that can go wrong will go wrong."
0.1% doesn't seem much, out of 10M it is 10K. Out of those 10K who decide to use more than 7 keywords, say 0.1% will have a noticeable memory consumption by `partial` object, that is 10 people.

Thus, given enough time it is very likely that more than 1 instance of issues with this will happen.

Given it is pretty much for free, and the block can be easily removed if there is a need for it in the future, I am in favour of being "better safe than sorry" here.

**Comment by kumaraditya303** [comment]
> But if you have better rationale in mind, I am open to further amendments.

I don't have better resizing strategy in mind atm so I'll not block this PR on it now, I'll merge this now thanks.

File: Modules/_functoolsmodule.c [hunk 23]
```diff
@@ -400,50 +384,143 @@ partial_vectorcall(PyObject *self, PyObject *const *args,
...
+            stack[tot_nargs + i] = val;
+            i++;
+        }
+        assert(i == pto_nkwds);
+        Py_XDECREF(pto_kw_merged);
+
+        /* Resize Stack if the removing overallocation saves some noticable memory
+         * NOTE: This whole block can be removed without breaking anything */
+        Py_ssize_t noveralloc = n_merges + nkwds;
+        if (stack != small_stack && noveralloc > 6 && noveralloc * 10 > init_stack_size) {
```
Comment (serhiy-storchaka) [inline Modules/_functoolsmodule.c]: `noveralloc * 10` can potentially overflow.

**Review by kumaraditya303 — APPROVED** [review]

**Comment by hawkinsp** [comment]
Is a 3.14 backport possible for this PR, given it fixes a free threading race also?

**Comment by kumaraditya303** [comment]
> Is a 3.14 backport possible for this PR, given it fixes a free threading race also?

This is performance improvement so it cannot be backported, I haven't seen any real crashes on this so adding supression should be fine for 3.14.
