### PR TITLE
gh-105658: fix excess trace events for except block ending with a conditional block

### LINKED ISSUE #105658: 3.12 tracing regression: a conditional in a finally block will revisit the condition before exiting the block.
Python 3.12 introduced a change in tracing behavior.  Now a conditional in a finally block will revisit the condition before exiting the block.

Here is test.py:
```python
import sys
print(sys.version)

def example(raise_exc: bool, enter_finally_cond: bool):
    try:
        if raise_exc:
            print("raising exception")
            raise Exception
        print("not raising exception")
    finally:
        if enter_finally_cond:
            print("in finally conditional")

    print("after finally")

try:
    example(raise_exc=True, enter_finally_cond=True)
except:
    pass
```

When traced under 3.11:
```
% python3.11 -m trace --trace test.py
 --- modulename: test, funcname: <module>
test.py(1): import sys
test.py(2): print(sys.version)
3.11.4 (main, Jun  7 2023, 08:42:37) [Clang 14.0.3 (clang-1403.0.22.14.1)]
test.py(4): def example(raise_exc: bool, enter_finally_cond: bool):
test.py(16): try:
test.py(17):     example(raise_exc=True, enter_finally_cond=True)
 --- modulename: test, funcname: example
test.py(5):     try:
test.py(6):         if raise_exc:
test.py(7):             print("raising exception")
raising exception
test.py(8):             raise Exception
test.py(11):         if enter_finally_cond:
test.py(12):             print("in finally conditional")
in finally conditional
test.py(18): except:
test.py(19):     pass
```

When traced under 3.12:
```
% python3.12 -m trace --trace test.py
 --- modulename: test, funcname: <module>
test.py(1): import sys
test.py(2): print(sys.version)
3.12.0b2 (main, Jun  7 2023, 08:47:18) [Clang 14.0.3 (clang-1403.0.22.14.1)]
test.py(4): def example(raise_exc: bool, enter_finally_cond: bool):
test.py(16): try:
test.py(17):     example(raise_exc=True, enter_finally_cond=True)
 --- modulename: test, funcname: example
test.py(5):     try:
test.py(6):         if raise_exc:
test.py(7):             print("raising exception")
raising exception
test.py(8):             raise Exception
test.py(11):         if enter_finally_cond:
test.py(12):             print("in finally conditional")
in finally conditional
test.py(11):         if enter_finally_cond:             # <******
test.py(18): except:
test.py(19):     pass
```

The extra line is marked with `<******`.  There's no reason for the if statement to be traced again.

### Linked PRs
* gh-109384
* gh-109411

### LINKED ISSUE #109156: Remove INSTRUCTION event monitoring will remove LINE events as well
# Bug report

### Bug description:

The current de-instrumentation code for instructions incorrectly de-instruments line too. So if INSTRUCTION events are removed, event if the LINE events are still there, it won't trigger the event.

```python
import sys
E = sys.monitoring.events

def line(*args):
    print("Line event: ", args)

def inst(*args):
    print("Instruction event: ", args)

sys.monitoring.use_tool_id(0, "test")
sys.monitoring.set_events(0, 0)
sys.monitoring.register_callback(0, E.LINE, line)
sys.monitoring.register_callback(0, E.INSTRUCTION, inst)
sys.monitoring.set_events(0, E.LINE | E.INSTRUCTION)
sys.monitoring.set_events(0, E.LINE)
a = 1
sys.monitoring.set_events(0, 0)
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-109157
* gh-109384

### PR DESCRIPTION
**Pull request by iritkatriel**
This will remove the event with the wrong line number. It will still work because RERAISE doesn't need to have a line number attached. In exception_unwind, the instruction pointer on the frame is used to determine which exception handler should be invoked. The location of the reraise doesn't show up in the traceback.

Fixes #105658.

* Issue: gh-105658

### CODE REVIEW

File: Misc/NEWS.d/next/Core and Builtins/2023-09-13-19-16-51.gh-issue-105658.z2nR2u.rst [hunk 1]
```diff
@@ -0,0 +1,2 @@
+Fix bug where the line trace of an except block ending with a conditional
+includes an excess even with the line of the conditional expression.
```
Comment (carljm) [inline Misc/NEWS.d/next/Core and Builtins/2023-09-13-19-16-51.gh-issue-105658.z2nR2u.rst]:
```suggestion
includes an excess event with the line of the conditional expression.
```

**Review by carljm — COMMENTED** [review]
I don't see a test here that reflects the case in the filed bug, where the line number actually jumps back to a previous line in a conditional. I believe that this change would fix that, but would it make sense to add an explicit test for it?

File: Lib/test/test_sys_settrace.py [hunk 2]
```diff
@@ -929,6 +929,35 @@ def func():
...
+            return result
+
+        self.run_and_compare(func,
+            [(0, 'call'),
+             (1, 'line'),
+             (2, 'line'),
+             (3, 'line'),
+             (3, 'exception'),
+             (5, 'line'),
+             (6, 'line'),
```
Comment (iritkatriel) [inline Lib/test/test_sys_settrace.py:955]: On main we have here another 
`             (5, 'line'),
`

**Review by carljm — APPROVED** [review]
