### PR TITLE
gh-104265 Disallow instantiation of `_csv.Reader` and `_csv.Writer`

### LINKED ISSUE #104265: `_csv` `Reader` and `Writer` types shouldn't be directly instantiable
The accepted way to create these objects is to use constructor functions `_csv.reader()` and `_csv.writer()` with appropriate arguments. Objects that are created through type constructors `_csv.Reader` and `_csv.Writer` turn out to be not properly initialized, and operations on them easily lead to crash:
```python
>>> import _csv
>>> _csv.Writer().writerow([])
Segmentation fault (core dumped)
```
```python
>>> import _csv
>>> list(_csv.Reader())
Segmentation fault (core dumped)
```
Although this is an internal detail, I'm sure that this should be fixed. I'll submit a PR shortly.
The crash appears on 3.10, 3.11 and current main.

### Linked PRs
* gh-104266
* gh-104278

### PR DESCRIPTION
**Pull request by chgnrdv**
Fixes #104265 

Set `Py_TPFLAGS_DISALLOW_INSTANTIATION` and unset `Py_TPFLAGS_BASETYPE` flags on `Reader` and `Writer` types to prevent their instantiation and subtyping

* Issue: gh-104265

### CODE REVIEW

**Comment by erlend-aasland** [comment]
Thanks! This needs a NEWS entry, preferrably with a reference to when the bug was introduced. I think this should be backported through to 3.10.

**Comment by erlend-aasland** [comment]
Also, please add tests. There's a dedicated test.support helper for this. Grep through the code base to find it and see how it's used.

**Comment by chgnrdv** [comment]
@erlend-aasland, are you talking about `assert_python_ok`? Can't we just check if `TypeError` with proper message is raised on attempt to create instance?

**Comment by erlend-aasland** [comment]
There's a disallow_instantiation helper in test.support.

**Comment by erlend-aasland** [comment]
> Thanks! This needs a NEWS entry, preferrably with a reference to when the bug was introduced. I think this should be backported through to 3.10.

Ah, 3.10 is in security fix mode, so we can only backport to 3.11.

**Comment by erlend-aasland** [comment]
Some history, the original issue for applying PEP-384 to the \_csv extension module:

- gh-59140 (bpo-14935)
- gh-23224

A later (duplicate issue); the linked PRs were closed and incorporated into gh-23224

- gh-78714 (bpo-34533)
- gh-8977
- gh-16078

As you can see, both the Writer and the Reader class had `Py_TPFLAGS_BASETYPE` when they were converted from static to heap types. Removing that flag is a _backwards incompatible change_, as third-party software may depend on that behaviour. Please revert that particular change.

**Review by erlend-aasland — CHANGES_REQUESTED** [review]
Changes requested:

- [x] Revert `Py_TPFLAGS_BASETYPE` changes
- [x] Add NEWS entry

**Comment by chgnrdv** [comment]
Looks like 6a02b384751dbc13979efc1185f0a7c1670dc349 from #23224 introduced this issue. How can I reflect this in NEWS entry text? Should I specify an issue number?

**Comment by erlend-aasland** [comment]
> Looks like [6a02b38](https://github.com/python/cpython/commit/6a02b384751dbc13979efc1185f0a7c1670dc349) from #23224 introduced this issue. How can I reflect this in NEWS entry text? Should I specify an issue number?

Indeed it did.

You can reference GitHub issues/PRs with the `:gh:` Sphinx directive. Here's a suggestion to a NEWS entry:

```
Prevent possible crash by disallow instantiation of the :class:`!_csv.Reader`
and :class:`!_csv.Writer` types. The regression was introduced by :gh:`23224`
in Python 3.10. Patch by <your-name-here>.
```

**Comment by chgnrdv** [comment]
I have made the requested changes; please review again

File: Misc/NEWS.d/next/Library/2023-05-07-19-56-45.gh-issue-104265.fVblry.rst [hunk 1]
```diff
@@ -0,0 +1 @@
+Prevent possible crash by disallow instantiation of the :class:`!_csv.Reader` and :class:`!_csv.Writer` types. The regression was introduced in 3.10.0a4 with PR 23224 (:issue:`14935`). Patch by Radislav Chugunov.
```
Comment (erlend-aasland) [inline Misc/NEWS.d/next/Library/2023-05-07-19-56-45.gh-issue-104265.fVblry.rst]: Fix a typo and break within 79 chars linewidth.

```suggestion
Prevent possible crash by disallowing instantiation of the
:class:`!_csv.Reader` and :class:`!_csv.Writer` types.
The regression was introduced in 3.10.0a4 with PR 23224 (:issue:`14935`).
Patch by Radislav Chugunov.
```

File: Lib/test/test_csv.py [hunk 2]
```diff
@@ -1430,5 +1431,11 @@ def test_subclassable(self):
         # issue 44089
         class Foo(csv.Error): ...
 
+    def test_reader_disallow_instantiation(self):
+        check_disallow_instantiation(self, _csv.Reader)
+
+    def test_writer_disallow_instantiation(self):
+        check_disallow_instantiation(self, _csv.Writer)
```
Comment (erlend-aasland) [inline Lib/test/test_csv.py]: This is a CPython only implementation detail, so we should decorate the tests with `@test.support.cpython_only`. I'd also suggest to use the `test.support.import_helper` to import the C extension module instead of doing that toplevel.

```suggestion
    @support.cpython_only
    def test_disallow_instantiation(self):
        _csv = support.import_helper.import_module("_csv")
        for tp in _csv.Reader, _csv.Writer:
            with self.subTest(tp=tp):
                check_disallow_instantiation(self, tp)

```

**Review by erlend-aasland — APPROVED** [review]

**Comment by erlend-aasland** [comment]
Thank you so much for the report and bugfix, Radislav; good job!

**Comment by chgnrdv** [comment]
@erlend-aasland, thank you for your patient review :)
