### PR TITLE
gh-124609: Fix _Py_ThreadId for Windows builds using MinGW

### LINKED ISSUE #124609: _Py_ThreadId() fails when compiled using GCC on Windows
# Bug report

### Bug description:

It should be possible to build a C extension module using GCC on Windows, but when defining Py_GIL_DISABLED any call to _Py_ThreadId fails.

The if/defs in _Py_ThreadId look for _MSC_VER to be defined to determine whether it's a Windows build or not, but that specifies the VS version and not whether the build is for Windows or not.

Instead it would be better to use _WIN32 (see https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170)

Something along these lines...

```
#if defined(_WIN32)
#include <intrin.h>
#endif

static inline uintptr_t
_Py_ThreadId(void)
{
    uintptr_t tid;
#if defined(_WIN32) && defined(_M_X64)
    tid = __readgsqword(48);
#elif defined(_WIN32) && defined(_M_IX86)
    tid = __readfsdword(24);
#elif defined(_WIN32) && defined(_M_ARM64)
    tid = __getReg(18);
...
```

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

### Linked PRs
* gh-124663
* gh-124698

### PR DESCRIPTION
**Pull request by tonyroberts**
Fixes #124609

* Issue: gh-124609

### CODE REVIEW

**Comment by ZeroIntensity** [comment]
(FWIW, the main branch is 3.14, not 3.13. Code goes into 3.13 via backports.)

**Review by ZeroIntensity — DISMISSED** [review]
I think this looks fine, there's nothing that concerns me here.

**Comment by tonyroberts** [comment]
Thanks @ZeroIntensity. Do I need to submit another PR into a 3.13 branch, or will that happen after this is merged?

**Comment by ZeroIntensity** [comment]
The bot will create a 3.13 PR automatically :)

File: Include/Python.h [hunk 1]
```diff
@@ -55,6 +55,10 @@
 #  include <intrin.h>             // __readgsqword()
 #endif
 
+#if defined(Py_GIL_DISABLED) && defined(MS_WINDOWS) && defined(__GNUC__)
```
Comment (zooba) [inline Include/Python.h]: Is `__GNUC__` the right test here? I thought that was cross-platform and represents the language version, rather than the compiler?

`MS_WINDOWS` is only going to be defined when building CPython using MSBuild or including headers that were built using MSBuild. So a Cygwin build (based around the makefile) won't have it set.

I can't find any documentation about the `intrin.h` header for anything except MSVC, and a few hints that Clang has a copy/compatibility layer. Which distributions include this header, and how can we identify them at build time?

**Comment by ZeroIntensity** [comment]
Sorry, this needs blurb entry, I didn't see that in my initial review. Could you add one?

File: Include/Python.h (hunk 1 above)
Comment (tonyroberts) [reply Include/Python.h]: Can change it for ``__MINGW32__`` if you prefer? It is included in mingw

Comment (tonyroberts) [reply Include/Python.h]: Also I guess if using ``__MINGW__`` also checking for ``MS_WINDOWS`` is no longer needed. Would you agree?

**Comment by zooba** [comment]
`__MINGW32__` seems like the right level to me, yeah. I'll let Sam finish up the PR with you (unless he really doesn't want to).

**Review by ZeroIntensity — APPROVED** [review]

File: Misc/NEWS.d/next/Windows/2024-09-27-13-40-25.gh-issue-124609.WaKk8G.rst [hunk 2]
```diff
@@ -0,0 +1 @@
+Fix _Py_ThreadId for Windows builds using MinGW.
```
Comment (picnixz) [inline Misc/NEWS.d/next/Windows/2024-09-27-13-40-25.gh-issue-124609.WaKk8G.rst]:
```suggestion
Fix ``_Py_ThreadId`` for Windows builds using MinGW. Patch by Tony Roberts.
```

File: Include/Python.h [hunk 3]
```diff
@@ -55,6 +55,10 @@
 #  include <intrin.h>             // __readgsqword()
 #endif
 
+#if defined(Py_GIL_DISABLED) && defined(__MINGW32__)
+#  include <intrin.h>             // __readgsqword()
```
Comment (picnixz) [inline Include/Python.h:59]: This include is not just for `__readqsqword` right? depending on the architecture, it could mean different functions. Also, would it work to merge the `defined(_MSC_VER)` and `defined(__MINGW32__)` tests? (mainly, would it be fine in the future or is there a chance where the includes could diverge?)

File: Include/object.h [hunk 4]
```diff
@@ -180,6 +180,12 @@ _Py_ThreadId(void)
     tid = __readfsdword(24);
 #elif defined(_MSC_VER) && defined(_M_ARM64)
     tid = __getReg(18);
+#elif defined(__MINGW32__) && defined(_M_X64)
+    tid = __readgsqword(48);
+#elif defined(__MINGW32__) && defined(_M_IX86)
+    tid = __readfsdword(24);
+#elif defined(__MINGW32__) && defined(_M_ARM64)
+    tid = __getReg(18);
```
Comment (picnixz) [inline Include/object.h:188]: How about `#if (defined(_MSC_VER) || defined(__MINGW32__)) && defined(_M_X64)` since the bodies are the same? (unless this could diverge in the future)

File: Include/Python.h (hunk 3 above)
Comment (tonyroberts) [reply Include/Python.h:59]: Merging those would work, but @zooba was against doing it in a single if/def and so I did it this way. The comment was taken from the line above since this new line has the exact same purpose. Happy to change it if you want to suggest an alternative.

File: Include/object.h (hunk 4 above)
Comment (tonyroberts) [reply Include/object.h:188]: I did it this way based on @zooba's preference

File: Include/Python.h (hunk 3 above)
Comment (picnixz) [reply Include/Python.h:59]: Oh no need for the change then! I don't have a better comment but I was a bit surprised with `__getReg(18)` and `__readfsdword` (I have NO idea of what is present in these files!). Are `__getReg` and `__readfsdword` part of this include? if so, I would add them to the comment (otherwise, it's fine).

Comment (tonyroberts) [reply Include/Python.h:59]: They're all related functions in the same file, more or less just different variants for the different architectures

Comment (picnixz) [reply Include/Python.h:59]: Let's keep the original comment. Those who know the file will probably know the rest (that way, we reduce the diff). Thanks for clarifying this!

**Review by picnixz — APPROVED** [review]

File: Include/Python.h (hunk 3 above)
Comment (tonyroberts) [reply Include/Python.h:59]: My view is it's fairly clear. Anyone looking through the code might search for __readgsqword and find the others, so the comment does its job of indicating why that include is necessary. I wouldn't complicate it by adding everything in the comment and leave it as it is above, but happy to take your guidance.

**Review by colesbury — APPROVED** [review]
Thanks for fixing this Tony
