### PR TITLE
gh-143123: Protect against recursive tracer calls/finalization

### LINKED ISSUE #143123: JIT: Assertion failure in `_PyOptimizer_Optimize`
# Crash report

### What happened?

It's possible to abort a patched debug JIT build by running the code below. The interpreter must be called from a venv in which lafleur is installed as editable, likely due to that priming the GC into a state suitable for the crash.

Sorry about the convoluted reproduction steps.

The necessary patch is:
```diff
diff --git a/Include/internal/pycore_backoff.h b/Include/internal/pycore_backoff.h
index 23ca7299e0d..0289b5fee7c 100644
--- a/Include/internal/pycore_backoff.h
+++ b/Include/internal/pycore_backoff.h
@@ -124,7 +124,7 @@ trigger_backoff_counter(void)
 // For example, 4095 does not work for the nqueens benchmark on pyperformance
 // as we always end up tracing the loop iteration's
 // exhaustion iteration. Which aborts our current tracer.
-#define JUMP_BACKWARD_INITIAL_VALUE 4000
+#define JUMP_BACKWARD_INITIAL_VALUE 63
 #define JUMP_BACKWARD_INITIAL_BACKOFF 6
 static inline _Py_BackoffCounter
 initial_jump_backoff_counter(void)
@@ -137,7 +137,7 @@ initial_jump_backoff_counter(void)
  * Must be larger than ADAPTIVE_COOLDOWN_VALUE,
  * otherwise when a side exit warms up we may construct
  * a new trace before the Tier 1 code has properly re-specialized. */
-#define SIDE_EXIT_INITIAL_VALUE 4000
+#define SIDE_EXIT_INITIAL_VALUE 63
 #define SIDE_EXIT_INITIAL_BACKOFF 6

 static inline _Py_BackoffCounter
```

To install lafleur as editable, first create a venv and activate it, then clone the [lafleur repo](https://github.com/devdanzin/lafleur/) and run `pip install -e /path/to/lafleur/clone`.

This MRE must be invoked like this:

```
/path/to/venv/with/editable/lafleur/install/bin/python mre.py
```

MRE:
```python
import asyncio
any_v2 = None
tuple_v4 = (1, "")

def f1():
    class A:
        def _():...
        def __(): ...
        def ___():...

    class B: ...
    class C:
        def _(): ...    
    class D:
        def _(): ...    
    class E:
        def _(): ...    
    class F:
        def _(): ...    
    class G:
        def _(): ...    
    class H:
        def _(): ...    
    
    l = []
    for i in range(5):
        def _(): ...
    class I:
        async def _(): ...
        try:
            c = _()
        except Exception: ...

    def __(): ...
    class J:
        def _(): ...

    for _ in range(300):
        try:
            try: ValueError("")
            except E: ...
        except Exception: ...
    (
        any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2,
        any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2,
        any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2,
        any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2,
        any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2,
        any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2,
        any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2, any_v2,
        any_v2, any_v2, 
    )
    class K:
        def _():...
        def __(): ...
        def ___():...
    class AsyncCtx_9078:
        def _(self): ...
        async def __():
            try:
                for _ in K(10): ...
            except Exception: ...
        try:
            c = __()
        except Exception: ...
    x, *y = tuple_v4
    class L:
        def _():...
        def __(): ...
        def ___():...
    class M:
        def _(self): ...
        async def __():
            try:
                for _ in L(10): ...
            except Exception: ...
        try:
            c = __()
        except Exception: ...

    x, *y = x, *y = tuple_v4
    class M:
        def _():...
        def __(): ...
        def ___():...
    class N:
        def _():...
        def __(): ...
        def ___():...
    class O:
        def _(self): ...
        async def __():
            try:
                for _ in N(10): ...
            except Exception: ...
        try:
            c = __()
        except Exception: ...
    class P:
        def _():...
        def __(): ...
        def ___():...
    class Q:
        def _(self): ...
        async def __():
            try:
                with Q(): ...
            except Exception: ...
        try:
            c = __()
        except Exception: ...
    class R:
        def _(self): ...
        async def __():
            try:
                with R(): ...
            except Exception: ...
        try:
            c = __()
        except Exception: ...

    x, *y = x, *y = tuple_v4
    class S:
        def __init__(self, lit):
            selit = self.count = 0
        def __aiter__(self):return self
        async def __anext__(self):
            if self.count: n
            self.count += 1
    class T:
        def _(self): ...
        async def __():
            try:
                async for _ in S(10): ...
            except Exception: ...
        try:
            c = __()
            while True:
                try: c.send(None)
                except Exception: break
        except Exception: ...

for i in range(300):
    print(i)
    f1()
```

Traceback:
```
1
[...]
200
201
python: Python/optimizer.c:144: int _PyOptimizer_Optimize(_PyInterpreterFrame *, PyThreadState *): Assertion `_tstate->jit_tracer_state.initial_state.func != NULL' failed.

Program received signal SIGABRT, Aborted.

#0  __pthread_kill_implementation (threadid=<optimized out>, signo=6, no_tid=0) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (threadid=<optimized out>, signo=6) at ./nptl/pthread_kill.c:89
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:100
#3  0x00007ffff7c45e2e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff7c28888 in __GI_abort () at ./stdlib/abort.c:77
#5  0x00007ffff7c287f0 in __assert_fail_base (fmt=<optimized out>, assertion=<optimized out>, file=<optimized out>, line=<optimized out>, function=<optimized out>) at ./assert/assert.c:118
#6  0x00007ffff7c3c19f in __assert_fail (assertion=<optimized out>, file=<optimized out>, line=<optimized out>, function=<optimized out>) at ./assert/assert.c:127
#7  0x00005555563c0bd0 in _PyOptimizer_Optimize (frame=frame@entry=0x7e8ff6de5298, tstate=tstate@entry=0x555556e62830 <_PyRuntime+358864>) at Python/optimizer.c:144
#8  0x0000555555ed2e64 in stop_tracing_and_jit (tstate=0x555556e62830 <_PyRuntime+358864>, frame=frame@entry=0x7e8ff6de5298) at Python/ceval.c:1405
#9  0x0000555555e8eeed in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=<optimized out>, throwflag=<optimized out>) at Python/generated_cases.c.h:11628
#10 0x0000555555e6bf98 in _PyEval_EvalFrame (tstate=0x555556e62830 <_PyRuntime+358864>, frame=0x7e8ff6de5220, throwflag=0) at ./Include/internal/pycore_ceval.h:119
#11 _PyEval_Vector (tstate=<optimized out>, func=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kwnames=0x0) at Python/ceval.c:2483
#12 0x0000555555e6b9b5 in PyEval_EvalCode (co=<optimized out>, globals=<optimized out>, locals=0x7c7ff6e86440) at Python/ceval.c:1008
```

Output from running with `PYTHON_LLTRACE=4 PYTHON_OPT_DEBUG=4`:
[830_abort_lltrace_opt_debug.txt](https://github.com/user-attachments/files/24319421/830_abort_lltrace_opt_debug.txt)

Found using [lafleur](https://github.com/devdanzin/lafleur/).

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.15.0a3+ (heads/main-dirty:3cc57505e53, Dec 23 2025, 19:04:15) [Clang 21.1.2 (2ubuntu6)]

### Linked PRs
* gh-143126

### LINKED ISSUE #143358: JIT: Assertion `exc && PyExceptionInstance_Check(exc)` failed in `*_PyEval_EvalFrameDefault`
# Crash report

### What happened?

It's possible to cause an abort in a patched debug JIT build by running the following MRE.

The necessary patch:
```diff
diff --git a/Include/internal/pycore_backoff.h b/Include/internal/pycore_backoff.h
index 23ca7299e0d..0289b5fee7c 100644
--- a/Include/internal/pycore_backoff.h
+++ b/Include/internal/pycore_backoff.h
@@ -124,7 +124,7 @@ trigger_backoff_counter(void)
 // For example, 4095 does not work for the nqueens benchmark on pyperformance
 // as we always end up tracing the loop iteration's
 // exhaustion iteration. Which aborts our current tracer.
-#define JUMP_BACKWARD_INITIAL_VALUE 4000
+#define JUMP_BACKWARD_INITIAL_VALUE 63
 #define JUMP_BACKWARD_INITIAL_BACKOFF 6
 static inline _Py_BackoffCounter
 initial_jump_backoff_counter(void)
@@ -137,7 +137,7 @@ initial_jump_backoff_counter(void)
  * Must be larger than ADAPTIVE_COOLDOWN_VALUE,
  * otherwise when a side exit warms up we may construct
  * a new trace before the Tier 1 code has properly re-specialized. */
-#define SIDE_EXIT_INITIAL_VALUE 4000
+#define SIDE_EXIT_INITIAL_VALUE 63
 #define SIDE_EXIT_INITIAL_BACKOFF 6

 static inline _Py_BackoffCounter
```

MRE:
```python
def f1():

    class EvilIterator:

        def __init__(self):
            self._items = [1, 2]
            self._index = 1

        def __iter__(self):
            return self

        def __next__(self):
            if not len(self._items) % 13:
                self._items.clear()

            for i_loop_9279 in range(10):
                self._items.extend([1, "", None])

            if not len(self._items) % 11:
                return 'unexpected_type_from_iterator'

            if self._index >= len(self._items):
                raise StopIteration

            item = self._items[self._index]
            self._index += 1
            return item

    evil_iter = EvilIterator()

    large_num = 2**31
    for _ in range(400):
        try:
            _ = [x + y for x in evil_iter for y in evil_iter if evil_iter._items.append(x) or large_num]
        except TypeError:
            pass

f1()
```

Backtrace:
```batch
python: Python/generated_cases.c.h:9901: PyObject *_PyEval_EvalFrameDefault(PyThreadState *, _PyInterpreterFrame *, int): Assertion `exc && PyExceptionInstance_Check(exc)' failed.

Program received signal SIGABRT, Aborted.

#0  __pthread_kill_implementation (threadid=<optimized out>, signo=6, no_tid=0) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (threadid=<optimized out>, signo=6) at ./nptl/pthread_kill.c:89
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:100
#3  0x00007ffff7c45e2e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff7c28888 in __GI_abort () at ./stdlib/abort.c:77
#5  0x00007ffff7c287f0 in __assert_fail_base (fmt=<optimized out>, assertion=<optimized out>, file=<optimized out>, line=<optimized out>, function=<optimized out>) at ./assert/assert.c:118
#6  0x00007ffff7c3c19f in __assert_fail (assertion=<optimized out>, file=<optimized out>, line=<optimized out>, function=<optimized out>) at ./assert/assert.c:127
#7  0x0000555555ebab3f in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=<optimized out>, throwflag=<optimized out>) at Python/generated_cases.c.h:9901
#8  0x0000555555e6dc98 in _PyEval_EvalFrame (tstate=0x555556e808c0 <_PyRuntime+359392>, frame=0x7e8ff6fe5220, throwflag=0) at ./Include/internal/pycore_ceval.h:118
#9  _PyEval_Vector (tstate=<optimized out>, func=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kwnames=0x0) at Python/ceval.c:2542
#10 0x0000555555e6d6b5 in PyEval_EvalCode (co=<optimized out>, globals=<optimized out>, locals=0x7c7ff70865c0) at Python/ceval.c:1008
#11 0x00005555564626df in run_eval_code_obj (tstate=tstate@entry=0x555556e808c0 <_PyRuntime+359392>, co=co@entry=0x7d1ff701afd0, globals=globals@entry=0x7c7ff70865c0,
    locals=locals@entry=0x7c7ff70865c0) at Python/pythonrun.c:1366
#12 0x00005555564618ac in run_mod (mod=<optimized out>, filename=<optimized out>, globals=<optimized out>, locals=<optimized out>, flags=<optimized out>, arena=<optimized out>,
    interactive_src=<optimized out>, generate_new_source=<optimized out>) at Python/pythonrun.c:1469
#13 0x000055555645bead in pyrun_file (fp=fp@entry=0x7d4ff6fefa80, filename=filename@entry=0x7ccff6ffafc0, start=start@entry=257, globals=globals@entry=0x7c7ff70865c0,
    locals=locals@entry=0x7c7ff70865c0, closeit=closeit@entry=1, flags=0x7bfff5e1e910) at Python/pythonrun.c:1294
#14 0x0000555556459a0d in _PyRun_SimpleFileObject (fp=<optimized out>, filename=<optimized out>, closeit=<optimized out>, flags=<optimized out>) at Python/pythonrun.c:518
#15 0x0000555556458d7e in _PyRun_AnyFileObject (fp=fp@entry=0x7d4ff6fefa80, filename=filename@entry=0x7ccff6ffafc0, closeit=closeit@entry=1, flags=flags@entry=0x7bfff5e1e910)
    at Python/pythonrun.c:81
#16 0x00005555564d4cfb in pymain_run_file_obj (program_name=0x7caff7026d50, filename=0x7ccff6ffafc0, skip_source_first_line=0) at Modules/main.c:410
#17 pymain_run_file (config=0x555556e4b998 <_PyRuntime+142520>) at Modules/main.c:429
#18 0x00005555564d2dc4 in pymain_run_python (exitcode=0x7bfff5e1e500) at Modules/main.c:691
#19 Py_RunMain () at Modules/main.c:772
#20 0x00005555564d3cc7 in pymain_main (args=<optimized out>) at Modules/main.c:802
#21 0x00005555564d3e38 in Py_BytesMain (argc=<optimized out>, argv=0x7fffffffdbe8) at Modules/main.c:826
#22 0x00007ffff7c2a575 in __libc_start_call_main (main=main@entry=0x555555919c40 <main>, argc=argc@entry=2, argv=argv@entry=0x7fffffffdbe8) at ../sysdeps/nptl/libc_start_call_main.h:58
#23 0x00007ffff7c2a628 in __libc_start_main_impl (main=0x555555919c40 <main>, argc=2, argv=0x7fffffffdbe8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>,
    stack_end=0x7fffffffdbd8) at ../csu/libc-start.c:360
#24 0x00005555558304f5 in _start ()
```

Output from running with `PYTHON_LLTRACE=4 PYTHON_OPT_DEBUG=4`:
[2394_segfault_lltrace.txt](https://github.com/user-attachments/files/24408834/2394_segfault_lltrace.txt)

Found using [lafleur](https://github.com/devdanzin/lafleur/).

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.15.0a3+ (heads/main-dirty:61f2ad9a3a7, Jan  2 2026, 11:43:51) [Clang 21.1.2 (2ubuntu6)]

### PR DESCRIPTION
**Pull request by Fidget-Spinner**
Fixes https://github.com/python/cpython/issues/143358
Fixes https://github.com/python/cpython/issues/143123

* Issue: gh-143123

### CODE REVIEW

**Comment by markshannon** [comment]
Can we have a test for this?

File: Python/optimizer.c [hunk 1]
```diff
@@ -138,6 +138,12 @@ _PyOptimizer_Optimize(
         // return immediately without optimization.
         return 0;
     }
+    if (_tstate->jit_tracer_state.initial_state.func == NULL) {
+        // gh-143123: It is possible for another function to finalize the current
```
Comment (markshannon) [inline Python/optimizer.c]: What do you mean by "another function"? Which other function?

File: Python/optimizer.c [hunk 2]
```diff
@@ -138,6 +138,12 @@ _PyOptimizer_Optimize(
         // return immediately without optimization.
         return 0;
     }
+    if (_tstate->jit_tracer_state.initial_state.func == NULL) {
```
Comment (markshannon) [inline Python/optimizer.c]: We shouldn't be able to get into this state, should we?
This seems like it should be an assert and the fix should be elsewhere.

**Comment by Fidget-Spinner** [comment]
> Can we have a test for this?

The reproducer provided by the OP requires installation of a package to crash. I don't think we can unit test this if that's the case.

**Review by markshannon — COMMENTED** [review]
What is the root issue here, and does this fix it?

Is the problem that we are unable to distinguish between tracing happening in an invocation of `_PyEval_EvalFrameDefault` higher up the call stack and tracing happening in this invocation of `_PyEval_EvalFrameDefault`?

So we start/stop tracing when we shouldn't?

**Comment by Fidget-Spinner** [comment]
> Is the problem that we are unable to distinguish between tracing happening in an invocation of _PyEval_EvalFrameDefault higher up the call stack and tracing happening in this invocation of _PyEval_EvalFrameDefault?

Yes I suspect that's the case.

**Comment by markshannon** [comment]
@Fidget-Spinner 
We could add a "jit_depth" field to the thread state, initialized to 0.

* On entering `_PyEval_EvalFrameDefault`: if jit_depth is non-zero, increase it by one.
* On leaving: if jit_depth is non-zero, decrease it by one
* Don't start tracing if jit_depth is non-zero. 
* When starting tracing, set it to 1.
* Tracing is active if `jit _depth == 1`
* Assert that it is 1 anywhere we call the optimizer, start or stop tracing, etc.

**Comment by Fidget-Spinner** [comment]
So I spent 30 minutes trying to create a simple reproducer to no avail. The following needs to happen:

1. Outer Python -> C -> Inner Python calls.
2. That just so happen to **all** be tracing at the same time.
3. Outer traces, inner traces. Inner trace stomp on outer.

This is really hard to create a reproducer for as I'm not sure how to finangle the counters to be just right.

**Comment by markshannon** [comment]
Not once across all threads. Once *per* thread.

**Comment by markshannon** [comment]
Maybe, but the current approach seems hard to follow and fragile.
I'm fairly sure we don't always stop tracing cleanly when exceptions are raised. 

I think we need a clear way to express the two queries:
1. "is tracing happening in *this* invocation of PyEval_EvalFrame?", and
2. "is tracing happening in this thread?"

And add some asserts that (1) always implies (2).

We should only start tracing if (2) is false, and only stop tracing if (1) is true.

I think we already have these two queries:
1. IS_JIT_TRACING()
2. tstate->jit_tracer_state.initial_state.code != NULL

We should probably add a `is_tracing` field to the thread state for clarity instead of the very unclear `tstate->jit_tracer_state.initial_state.code != NULL`

File: Python/bytecodes.c [hunk 3]
```diff
@@ -5607,6 +5607,16 @@ dummy_func(
 #else
             assert(_PyErr_Occurred(tstate));
 #endif
+#if _Py_TIER2
+            if (IS_JIT_TRACING()) {
+                LEAVE_TRACING();
+                int res = stop_tracing_and_jit(tstate, frame);
```
Comment (markshannon) [inline Python/bytecodes.c]: We just want to stop tracing, but not jit here. Can we just call `_PyJit_FinalizeTracing`?

File: Python/bytecodes.c [hunk 4]
```diff
@@ -5607,6 +5607,16 @@ dummy_func(
 #else
             assert(_PyErr_Occurred(tstate));
 #endif
+#if _Py_TIER2
+            if (IS_JIT_TRACING()) {
```
Comment (markshannon) [inline Python/bytecodes.c]: Is this the correct place for this, or should it be in `label(exception_unwind)`?

**Review by markshannon — CHANGES_REQUESTED** [review]
One small issue and one question, otherwise this looks sound.

File: Python/bytecodes.c (hunk 3 above)
Comment (Fidget-Spinner) [reply Python/bytecodes.c]: No, because we need that function to reset the counters as well

File: Python/bytecodes.c (hunk 4 above)
Comment (Fidget-Spinner) [reply Python/bytecodes.c]: Don't we want to stop tracing whenever an error happens anyways, because we currently dont deal with errors?

Comment (markshannon) [reply Python/bytecodes.c]: `label(error)` always goes to `label(execption_unwind)` ~so it will get handled then~.

Comment (markshannon) [reply Python/bytecodes.c]: I forgot about the call to `_PyEval_MonitorRaise` so we do need this here.
I think we also need this check before any calls to monitoring before `JUMP_TO_LABEL(exception_unwind);`

Maybe make a `STOP_TRACING()` macro to keep the code duplication down?

File: Python/bytecodes.c (hunk 3 above)
Comment (markshannon) [reply Python/bytecodes.c]: Which counters need resetting, and shouldn't `_PyJit_FinalizeTracing` do that anyway?

**Review by markshannon — APPROVED** [review]
Thanks.
That looks good now.
