### PR TITLE
gh-91118: Fix docstrings that do not honor --without-doc-strings

### LINKED ISSUE #91118: Fix docstrings that do not honor --without-doc-strings
BPO | [46962](https://bugs.python.org/issue46962)
--- | :---
Nosy | @arhadthedev
PRs | <li>python/cpython#31769</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-08.18:59:44.544>
labels = ['extension-modules', 'interpreter-core', '3.11', 'type-bug', 'docs']
title = 'Fix docstrings that do not honor --without-doc-strings'
updated_at = <Date 2022-03-08.19:01:28.471>
user = 'https://github.com/arhadthedev'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-08.19:01:28.471>
actor = 'arhadthedev'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'Extension Modules', 'Interpreter Core']
creation = <Date 2022-03-08.18:59:44.544>
creator = 'arhadthedev'
dependencies = []
files = []
hgrepos = []
issue_num = 46962
keywords = ['patch']
message_count = 1.0
messages = ['414768']
nosy_count = 2.0
nosy_names = ['docs@python', 'arhadthedev']
pr_nums = ['31769']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46962'
versions = ['Python 3.11']
```

</p></details>

### PR DESCRIPTION
**Pull request by arhadthedev**
To support `--without-doc-strings`, all docstrings must be wrapped into `PyDoc_STRVAR` or `PyDoc_STR` ([PEP 7](https://www.python.org/dev/peps/pep-0007/)). However, there are 18 occurrences in code and 10 in C API documentation that do not follow this rule. The documentation is important too because it should not teach people the wrong things.

To find the occurrences I searched for `(?:^\s*.tp_doc = "|" \/\* tp_doc \*\/$)` and`^(?:static\s+)?const\s+char\s+[^=]+=\s*"`.

Fixes GH-91118.

### CODE REVIEW

File: Misc/NEWS.d/next/Core and Builtins/2022-03-08-21-59-57.bpo-46962.UomDfz.rst [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+
+The classes affected are :class:`~ctypes.UnionType`,
+:class:`~pickle.PickleBuffer`, and :class:`~types.GenericAlias`.
+
+The functions affected are :func:`ctypes.addressof`,
+:func:`ctypes.alignment`, :func:`ctypes.byref`,
+:func:`ctypes.CopyComPointer`, :func:`ctypes.FormatError`,
+:func:`ctypes.FreeLibrary`, :func:`ctypes.LoadLibrary`, and
+:func:`ctypes.sizeof`, along with a bunch of methods in
+:class:`~_ctypes.PyCPointerType:, :class:`~_ctypes.PyCSimpleType:, and
```
Comment (JelleZijlstra) [inline Misc/NEWS.d/next/Core and Builtins/2022-03-08-21-59-57.bpo-46962.UomDfz.rst]:
```suggestion
:class:`~_ctypes.PyCPointerType`, :class:`~_ctypes.PyCSimpleType`, and
```

File: Misc/NEWS.d/next/Core and Builtins/2022-03-08-21-59-57.bpo-46962.UomDfz.rst [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+:class:`~_ctypes.PyCStructType:.
```
Comment (JelleZijlstra) [inline Misc/NEWS.d/next/Core and Builtins/2022-03-08-21-59-57.bpo-46962.UomDfz.rst]:
```suggestion
:class:`~_ctypes.PyCStructType`.
```

**Review by JelleZijlstra — COMMENTED** [review]
There are a bunch of others, mostly in ctypes:

```
% git grep '".*tp_doc\s*'
Doc/c-api/typeobj.rst:       "My objects",                   /* tp_doc */
Modules/_ctypes/_ctypes.c:    "deletes a key from a dictionary",          /* tp_doc */
Modules/_ctypes/_ctypes.c:    "metatype for the CData Objects",           /* tp_doc */
Modules/_ctypes/_ctypes.c:    "metatype for the CData Objects",           /* tp_doc */
Modules/_ctypes/_ctypes.c:    "metatype for the Pointer Objects",         /* tp_doc */
Modules/_ctypes/_ctypes.c:    "metatype for the Array Objects",           /* tp_doc */
Modules/_ctypes/_ctypes.c:    "metatype for the PyCSimpleType Objects",           /* tp_doc */
Modules/_ctypes/_ctypes.c:    "metatype for C function pointers",         /* tp_doc */
Modules/_ctypes/_ctypes.c:    "XXX to be provided",                       /* tp_doc */
Modules/_ctypes/_ctypes.c:    "Function Pointer",                         /* tp_doc */
Modules/_ctypes/_ctypes.c:    "Structure base class",                     /* tp_doc */
Modules/_ctypes/_ctypes.c:    "Union base class",                         /* tp_doc */
Modules/_ctypes/_ctypes.c:    "XXX to be provided",                       /* tp_doc */
Modules/_ctypes/_ctypes.c:    "XXX to be provided",                       /* tp_doc */
Modules/_ctypes/_ctypes.c:    "XXX to be provided",                       /* tp_doc */
Modules/_ctypes/callbacks.c:    "CThunkObject",                             /* tp_doc */
Modules/_ctypes/cfield.c:    "Structure/Union member",                   /* tp_doc */
Modules/_testcapimodule.c:    "Instantiating this exception starts infinite recursion.", /* tp_doc */
```

I'm a bit skeptical about how useful this is, though—does anyone actually use the configure option to strip docstrings?

File: Misc/NEWS.d/next/Core and Builtins/2022-03-08-21-59-57.bpo-46962.UomDfz.rst (hunk 2 above)
Comment (arhadthedev) [reply Misc/NEWS.d/next/Core and Builtins/2022-03-08-21-59-57.bpo-46962.UomDfz.rst]: > I'm a bit skeptical about how useful this is, though—does anyone actually use the configure option to strip docstrings?

I think that if a flag exists, it should work fully. Also it's enabled by default so strings that should not be in the binary are no longer there.

File: Misc/NEWS.d/next/Core and Builtins/2022-03-08-21-59-57.bpo-46962.UomDfz.rst [hunk 3]
```diff
@@ -0,0 +1,10 @@
+Classes and functions that unconditionally declared their docstrings
+ignoring --without-doc-strings compilation flag no longer do so.
+
+The classes affected are :class:`~ctypes.UnionType`,
+:class:`~pickle.PickleBuffer`, :class:`~testcapi.RecursingInfinitelyError`,
+and :class:`~types.GenericAlias`.
```
Comment (merwok) [inline Misc/NEWS.d/next/Core and Builtins/2022-03-08-21-59-57.bpo-46962.UomDfz.rst]: I don’t think the module names should be hidden here.

File: Misc/NEWS.d/next/Documentation/2022-03-08-22-10-38.bpo-46962.FIVe9I.rst [hunk 4]
```diff
@@ -0,0 +1,4 @@
+All docstrings in code snippets are now wrapped into :func:`PyDoc_STR` to
+not teach programmers violation of `PEP 7's Documentation Strings paragraph
```
Comment (merwok) [inline Misc/NEWS.d/next/Documentation/2022-03-08-22-10-38.bpo-46962.FIVe9I.rst]:
```suggestion
follow the guideline of `PEP 7's Documentation Strings paragraph
```

File: Misc/NEWS.d/next/Core and Builtins/2022-03-08-21-59-57.bpo-46962.UomDfz.rst (hunk 3 above)
Comment (arhadthedev) [reply Misc/NEWS.d/next/Core and Builtins/2022-03-08-21-59-57.bpo-46962.UomDfz.rst]: Fixed.

File: Misc/NEWS.d/next/Core and Builtins/2022-03-08-21-59-57.bpo-46962.UomDfz.rst [hunk 5]
```diff
@@ -0,0 +1,10 @@
+Classes and functions that unconditionally declared their docstrings
+ignoring --without-doc-strings compilation flag no longer do so.
```
Comment (JelleZijlstra) [inline Misc/NEWS.d/next/Core and Builtins/2022-03-08-21-59-57.bpo-46962.UomDfz.rst]:
```suggestion
ignoring the `--without-doc-strings` compilation flag no longer do so.
```

File: Misc/NEWS.d/next/Core and Builtins/2022-03-08-21-59-57.bpo-46962.UomDfz.rst [hunk 6]
```diff
@@ -0,0 +1,10 @@
...
+
+The classes affected are :class:`ctypes.UnionType`,
+:class:`pickle.PickleBuffer`, :class:`testcapi.RecursingInfinitelyError`,
+and :class:`types.GenericAlias`.
+
+The functions affected are 24 methods of :mod:`ctypes`'s classes.
```
Comment (JelleZijlstra) [inline Misc/NEWS.d/next/Core and Builtins/2022-03-08-21-59-57.bpo-46962.UomDfz.rst]:
```suggestion
The functions affected are 24 methods in :mod:`ctypes`.
```

**Review by JelleZijlstra — APPROVED** [review]

**Comment by JelleZijlstra** [comment]
@arhadthedev do you want to do the backports? I feel like the docs changes are most important to backport.

**Comment by arhadthedev** [comment]
That backport to 3.9 was targeted to main instead of 3.9.

The new, correct entry is GH-91664.
