### PR TITLE
gh-120367: fix bug where compiler detects redundant jump after pseudo op replacement

### LINKED ISSUE #120367: no_redundant_jumps: Assertion `0' failed
# Bug report

### Bug description:

The following code causes a crash on cpython 3.13 branch (f5289c450a324bd560b328ecd42ac9faf578276e) and the current main.

```python
import ast

code="""
try:
    if name_4:
        pass
    else:
        pass
except* name_0:
    pass
else:
    name_4
"""

tree = ast.parse(code)
for node in ast.walk(tree):
    if hasattr(node,"lineno"):
         del   node.lineno
         del   node.end_lineno
         del   node.col_offset
         del   node.end_col_offset

compile(ast.fix_missing_locations(tree), "<file>", "exec")
```

output (Python 3.13.0a3+):
```python
python: Python/flowgraph.c:511: no_redundant_jumps: Assertion `0' failed.
```

I bisected the problem down to 2091fb2a85c1aa2d9b22c02736b07831bd875c2a.
@iritkatriel can you take a look at it?

### CPython versions tested on:

3.13, CPython main branch

### Operating systems tested on:

_No response_

### Linked PRs
* gh-120425
* gh-120621
* gh-120714
* gh-120716

### PR DESCRIPTION
**Pull request by iritkatriel**
Fixes #120367. 

This can't happen with an AST that comes from real code, because the try can't be on the same line as the following instruction. It can happen with a synthetic AST though.

* Issue: gh-120367

### CODE REVIEW

**Review by carljm — APPROVED** [review]

File: Misc/NEWS.d/next/Core and Builtins/2024-06-18-21-34-30.gh-issue-120367.zDwffP.rst [hunk 1]
```diff
@@ -0,0 +1 @@
+Fix bug where compiler creates a redundant jump during pseudo-op replacement. Can only happen with a synthetic AST that has a `try` on the same line as the instruction following the exception handler.
```
Comment (iritkatriel) [inline Misc/NEWS.d/next/Core and Builtins/2024-06-18-21-34-30.gh-issue-120367.zDwffP.rst]:
```suggestion
Fix bug where compiler creates a redundant jump during pseudo-op replacement. Can only happen with a synthetic AST that has a try on the same line as the instruction following the exception handler.
```
