### PR TITLE
bpo-44859: Raise more accurate exceptions in `sqlite3`

### LINKED ISSUE #89022: Improve some sqlite3 errors
BPO | [44859](https://bugs.python.org/issue44859)
--- | :---
Nosy | @berkerpeksag, @serhiy-storchaka, @JelleZijlstra, @erlend-aasland
PRs | <li>python/cpython#27654</li><li>python/cpython#27695</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-08-07.14:14:16.688>
labels = ['extension-modules', '3.11']
title = 'Improve some sqlite3 errors'
updated_at = <Date 2022-03-17.05:58:28.684>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-17.05:58:28.684>
actor = 'JelleZijlstra'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2021-08-07.14:14:16.688>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 44859
keywords = ['patch']
message_count = 8.0
messages = ['399183', '399185', '399187', '399211', '399241', '399289', '399441', '415388']
nosy_count = 4.0
nosy_names = ['berker.peksag', 'serhiy.storchaka', 'JelleZijlstra', 'erlendaasland']
pr_nums = ['27654', '27695']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue44859'
versions = ['Python 3.11']
```

</p></details>

### PR DESCRIPTION
**Pull request by erlend-aasland**
Improve exception compliancy with PEP 249

* Raise InterfaceError instead of ProgrammingError for SQLITE_MISUSE.
  If SQLITE_MISUSE is raised, it is a sqlite3 module bug. Users of the
  sqlite3 module are not responsible of using the SQLite C API correctly.
* Don't overwrite BufferError with ValueError when conversion to BLOB fails.
* Raise ProgrammingError instead of Warning if user tries to execute() more
  than one SQL statement.
* Raise ProgrammingError instead of ValueError if an SQL query contains null characters.
* Make sure `_pysqlite_set_result` raises an exception if it returns -1.

Fixes #89022

### CODE REVIEW

**Comment by erlend-aasland** [comment]
@serhiy-storchaka would you mind reviewing this?

**Comment by erlend-aasland** [comment]
@serhiy-storchaka PTAL. I just fixed bug in `_pysqlite_set_result` that could result in a segfault.

File: Misc/NEWS.d/next/Library/2021-08-10-00-05-53.bpo-44859.9e9_3V.rst [hunk 1]
```diff
@@ -0,0 +1,7 @@
+Raise more accurate exceptions in :mod:`sqlite3`.
+
+* Raise InterfaceError iso. ProgrammingError for SQLITE_MISUSE
```
Comment (JelleZijlstra) [inline Misc/NEWS.d/next/Library/2021-08-10-00-05-53.bpo-44859.9e9_3V.rst]:
```suggestion
* Raise InterfaceError instead of ProgrammingError for SQLITE_MISUSE
```
I don't think "iso." is a widely understood abbreviation.

File: Misc/NEWS.d/next/Library/2021-08-10-00-05-53.bpo-44859.9e9_3V.rst [hunk 2]
```diff
@@ -0,0 +1,7 @@
...
+* Don't overwrite BufferError with ValueError when converting to BLOB
+* Raise ProgrammingError iso. Warning if user tries to execute() more than one
+  statement
+* Raise DataError iso. ValueError if query contains NULL characters
```
Comment (JelleZijlstra) [inline Misc/NEWS.d/next/Library/2021-08-10-00-05-53.bpo-44859.9e9_3V.rst]:
```suggestion
* Raise ProgrammingError instead of Warning if user tries to execute() more than one
  statement
* Raise DataError instead of ValueError if query contains NULL characters
```

File: Modules/_sqlite/connection.c [hunk 3]
```diff
@@ -569,6 +567,10 @@ _pysqlite_set_result(sqlite3_context* context, PyObject* py_val)
         sqlite3_result_blob(context, view.buf, (int)view.len, SQLITE_TRANSIENT);
         PyBuffer_Release(&view);
     } else {
+        callback_context *ctx = (callback_context *)sqlite3_user_data(context);
+        PyErr_Format(ctx->state->ProgrammingError,
+                     "UDF's cannot return '%s' values to SQLite",
```
Comment (JelleZijlstra) [inline Modules/_sqlite/connection.c]:
```suggestion
                     "User-defined functions cannot return '%s' values to SQLite",
```
No other error message uses the "UDF" abbreviation.

File: Modules/_sqlite/connection.c [hunk 4]
```diff
@@ -556,8 +556,6 @@ _pysqlite_set_result(sqlite3_context* context, PyObject* py_val)
     } else if (PyObject_CheckBuffer(py_val)) {
         Py_buffer view;
         if (PyObject_GetBuffer(py_val, &view, PyBUF_SIMPLE) != 0) {
-            PyErr_SetString(PyExc_ValueError,
```
Comment (JelleZijlstra) [inline Modules/_sqlite/connection.c:581]: Looks like there's no test for this change.

**Review by JelleZijlstra — CHANGES_REQUESTED** [review]

File: Misc/NEWS.d/next/Library/2021-08-10-00-05-53.bpo-44859.9e9_3V.rst (hunk 1 above)
Comment (erlend-aasland) [reply Misc/NEWS.d/next/Library/2021-08-10-00-05-53.bpo-44859.9e9_3V.rst]: Yes; it's a bad habit I have. Thanks for catching.

File: Modules/_sqlite/connection.c (hunk 3 above)
Comment (erlend-aasland) [reply Modules/_sqlite/connection.c]: Yes, this is a good opportunity to get rid of those abbreviations!

File: Modules/_sqlite/connection.c (hunk 4 above)
Comment (erlend-aasland) [reply Modules/_sqlite/connection.c:581]: I'll add one, thanks!

**Comment by JelleZijlstra** [comment]
Looks like you didn't push the changes I previously asked for.

**Comment by erlend-aasland** [comment]
> Looks like you didn't push the changes I previously asked for.

Actually, it seems I forgot about this; I didn't make any changes yet :) I'll see if I can get to it any time soon. Thanks for the reminder!

File: Modules/_sqlite/connection.c (hunk 4 above)
Comment (erlend-aasland) [reply Modules/_sqlite/connection.c:581]: Added in commit b4a95bdb096d379bc1698778a1506537224ea660

**Comment by erlend-aasland** [comment]
I'd like to run this through the Django test suite before eventually merging. Also, I'll have a talk with MAL regarding this change.

**Comment by erlend-aasland** [comment]
> I'd like to run this through the Django test suite before eventually merging. Also, I'll have a talk with MAL regarding this change.

I finally got to run this through the Django test suite, and it works all fine; one down, one to go.

<details>

I got sidetracked with a long bisect operation because I was using SQLite 3.39.0 (development version), and because b899126094731bc49fecb61f2c1b7557d74ca839 produces a ton of warnings in the Django test suite. I reverted b899126094731bc49fecb61f2c1b7557d74ca839 and compiled strictly against SQLite 3.36.0 (macOS bundled), and all was ok.

</details>

File: Misc/NEWS.d/next/Library/2021-08-10-00-05-53.bpo-44859.9e9_3V.rst [hunk 5]
```diff
@@ -0,0 +1,10 @@
+Raise more accurate and :pep:`249` compatible exceptions in :mod:`sqlite3`.
+
+* Raise :exc:`~sqlite3.InterfaceError` instead of
+  :exc:`~sqlite3.ProgrammingError` for ``SQLITE_MISUSE`` errors.
```
Comment (JelleZijlstra) [inline Misc/NEWS.d/next/Library/2021-08-10-00-05-53.bpo-44859.9e9_3V.rst:4]: You might run into https://github.com/python/core-workflow/issues/394 here

Comment (erlend-aasland) [reply Misc/NEWS.d/next/Library/2021-08-10-00-05-53.bpo-44859.9e9_3V.rst:4]: Hm, I manually edited the NEWS file after blurb generated it, so I think I'm fine. I did a `make html` just to be sure, and the changelog was formatted correctly.

Comment (JelleZijlstra) [reply Misc/NEWS.d/next/Library/2021-08-10-00-05-53.bpo-44859.9e9_3V.rst:4]: Confirmed that it works right, I wonder what changed.

**Review by JelleZijlstra — APPROVED** [review]
