### PR TITLE
gh-140104: Set next_instr properly in the JIT during exceptions

### LINKED ISSUE #140104: JIT (correctness): Different `UnboundLocalError` for same code with JIT on or off
# Bug report

### Bug description:

The following code results in two different `UnboundLocalError` exceptions depending on whether it's run with the JIT on or off:

```python
def f():

    if 0:
        class Class:
            pass

    if 0:
        instance = Class()

    for _ in range(5000):
        try:
            _ = instance.f()
        except Exception:
            pass
    Class.__bases__ = (object,)

f()
```

With JIT on, the `UnboundLocalError` points to `'instance'`, while with JIT off it points to `'Class'`.

Traceback with JIT on:
```python
Traceback (most recent call last):
  File "/home/danzin/divergences/divergence_child_6010_3_1.py", line 17, in <module>
    f()
    ~^^
  File "/home/danzin/divergences/divergence_child_6010_3_1.py", line 12, in f
    _ = instance.f()
        ^^^^^^^^
UnboundLocalError: cannot access local variable 'instance' where it is not associated with a value
```

Traceback with JIT off:
```python
Traceback (most recent call last):
  File "/home/danzin/divergences/divergence_child_6010_3_1.py", line 17, in <module>
    f()
    ~^^
  File "/home/danzin/divergences/divergence_child_6010_3_1.py", line 15, in f
    Class.__bases__ = (object,)
    ^^^^^
UnboundLocalError: cannot access local variable 'Class' where it is not associated with a value
```

Output for `PYTHON_LLTRACE=4`:
[divergence_01_lltrace.txt](https://github.com/user-attachments/files/22903957/divergence_01_lltrace.txt)

Output for `PYTHON_OPT_DEBUG=4`:
[divergence_01_opt_debug.txt](https://github.com/user-attachments/files/22903958/divergence_01_opt_debug.txt)

Please let me know whether you're able to reproduce this issue.

Found using [lafleur](https://github.com/devdanzin/lafleur/).

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-140233
* gh-140687
* gh-140890
* gh-141495

### PR DESCRIPTION
**Pull request by Fidget-Spinner**
Fixes #140104

* Issue: gh-140104

### CODE REVIEW

**Comment by devdanzin** [comment]
This PR fixes all correctness bugs found by the fuzzer so far, thank you!

**Comment by chris-eibl** [comment]
Tailcall CI is broken for x86_64-pc-windows-msvc and aarch64-pc-windows-msvc.

Updating `opcode_metadata_generator.py` and regenerating `pycore_opcode_metadata.h` fixes the x86_64 build and passes the tests for me:
```
diff --git a/Tools/cases_generator/opcode_metadata_generator.py b/Tools/cases_generator/opcode_metadata_generator.py
index b649b381233..e3ac335ed48 100644
--- a/Tools/cases_generator/opcode_metadata_generator.py
+++ b/Tools/cases_generator/opcode_metadata_generator.py
@@ -147,7 +147,7 @@ def generate_instruction_formats(analysis: Analysis, out: CWriter) -> None:
 
 
 def generate_deopt_table(analysis: Analysis, out: CWriter) -> None:
-    out.emit("extern const uint8_t _PyOpcode_Deopt[256];\n")
+    out.emit("PyAPI_DATA(const uint8_t) _PyOpcode_Deopt[256];\n")
     out.emit("#ifdef NEED_OPCODE_METADATA\n")
     out.emit("const uint8_t _PyOpcode_Deopt[256] = {\n")
     deopts: list[tuple[str, str]] = []
@@ -170,7 +170,7 @@ def generate_deopt_table(analysis: Analysis, out: CWriter) -> None:
 
 
 def generate_cache_table(analysis: Analysis, out: CWriter) -> None:
-    out.emit("extern const uint8_t _PyOpcode_Caches[256];\n")
+    out.emit("PyAPI_DATA(const uint8_t) _PyOpcode_Caches[256];\n")
     out.emit("#ifdef NEED_OPCODE_METADATA\n")
     out.emit("const uint8_t _PyOpcode_Caches[256] = {\n")
     for inst in analysis.instructions.values():
```
Unfortunately, I cannot test aarch64. Hopefully, this fixes it as well. 

Would have liked to fail it during compiling like x86_64, not at runtime, though?

**Comment by markshannon** [comment]
`frame->instr_ptr` is set correctly in `_ERROR_POP_N`. I think the bug is in `TIER1_TO_TIER2` which needs to set `next_instr = frame->instr_ptr + 1;` in the error case.

File: Python/ceval_macros.h [hunk 1]
```diff
@@ -358,7 +358,9 @@ do {                                                   \
     frame = tstate->current_frame;                     \
     stack_pointer = _PyFrame_GetStackPointer(frame);   \
     if (next_instr == NULL) {                          \
-        next_instr = frame->instr_ptr;                 \
+        /* gh-140104: The exception handler expects frame->instr_ptr
+            to be pointing to next_instr, not this_instr! */ \
+        next_instr = frame->instr_ptr + 1 + _PyOpcode_Caches[_PyOpcode_Deopt[frame->instr_ptr->op.code]];                 \
```
Comment (markshannon) [inline Python/ceval_macros.h]:
```suggestion
        next_instr = frame->instr_ptr + 1;
```
Just `+1` to compensate for the the -1 in `label(exception_unwind)`

Pointing to the next instruction does work, but it is unnecessary. As long as `next_inst -1` points into the current instruction, unwinding works correctly.

**Review by markshannon — CHANGES_REQUESTED** [review]

File: Lib/test/test_capi/test_opt.py [hunk 2]
```diff
@@ -2637,6 +2637,17 @@ def f2():
 
         f2()
 
+    def test_next_instr_for_exception_handler_set(self):
+        # gh-140104: We just want the exception to be caught properly.
+        def f():
+            for i in range(TIER2_THRESHOLD + 3):
+                try:
+                    g(i)
```
Comment (markshannon) [inline Lib/test/test_capi/test_opt.py]:
```suggestion
                    undefined_variable(i)
```
I'm assuming that the exception here is that `g` is undefined?


Can we have two tests?
1. where the exception is raised on the first instruction of the block (like this one), and
2. where it is raised on the last instruction.
Something like:
```
      a_list[""] = 0
```

**Comment by markshannon** [comment]
The code looks good now.
Can we add a test to check that raising an exception works for the last instruction in a block, as well as for the first?

File: Lib/test/test_capi/test_opt.py (hunk 2 above)
Comment (Fidget-Spinner) [reply Lib/test/test_capi/test_opt.py]: I don't quite understand how to raise something on the last instruction. What does `a_list` contain?

Comment (markshannon) [reply Lib/test/test_capi/test_opt.py]: `a_list` contains a list.

`a_list[""] = 0`
compiles to 
```
              LOAD_SMALL_INT           0
              LOAD_FAST_BORROW         0 (a_list)
              LOAD_CONST               1 ('')
              STORE_SUBSCR
```
The `STORE_SUBSCR` will raise an exception.

Comment (Fidget-Spinner) [reply Lib/test/test_capi/test_opt.py]: I have to admit I straight up forgot how to code Python and thought that was valid Python code that wouldn't raise an exception.

**Review by markshannon — APPROVED** [review]
Thanks
