### PR TITLE
gh-114875: Add `getgrent` as a prerequisite for building the `grp` module

### LINKED ISSUE #114875: `grp` module attempts to build even if `getgrent` family of functions are unavailable
# Bug report

### Bug description:

In the configure script, the only prerequisite for the `grp` module is currently the `getgrgid` function. Older versions of Android have this function, but they don't have the `getgrent` function, which the `grp` module uses unconditionally. This causes the build to fail as follows:

```
/Users/msmith/Library/Android/sdk/ndk/22.1.7171670/toolchains/llvm/prebuilt/darwin-x86_64/bin/x86_64-linux-android21-clang  -fno-strict-overflow -Wsign-compare -Wunreachable-code -DNDEBUG -g -O3 -Wall    -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -fvisibility=hidden  -I./Include/internal -I./Include/internal/mimalloc  -I. -I./Include     -c ./Modules/grpmodule.c -o Modules/grpmodule.o
./Modules/grpmodule.c:127:24: warning: unused variable 'buf2' [-Wunused-variable]
    char *buf = NULL, *buf2 = NULL;
                       ^
./Modules/grpmodule.c:205:24: warning: unused variable 'buf2' [-Wunused-variable]
    char *buf = NULL, *buf2 = NULL, *name_chars;
                       ^
./Modules/grpmodule.c:287:5: error: implicit declaration of function 'setgrent' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    setgrent();
    ^
./Modules/grpmodule.c:288:17: error: implicit declaration of function 'getgrent' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    while ((p = getgrent()) != NULL) {
                ^
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Other

### Linked PRs
* gh-114876

### PR DESCRIPTION
**Pull request by mhsmith**
This allows the module to be correctly skipped on older versions of Android which don't have `getgrent` and related functions:
```
checking for getgrent... no
checking for getgrgid... yes
checking for getgrgid_r... no
[...]
checking for stdlib extension module grp... missing
```

* Fixes: gh-114875

### CODE REVIEW

File: Misc/NEWS.d/next/Build/2024-02-01-20-08-11.gh-issue-114875.x_2iZ9.rst [hunk 1]
```diff
@@ -0,0 +1 @@
+Add ``getgrent`` as a prerequisite for building the :mod:`grp` module.
```
Comment (erlend-aasland) [inline Misc/NEWS.d/next/Build/2024-02-01-20-08-11.gh-issue-114875.x_2iZ9.rst]:
```suggestion
Add :c:func:`!getgrent` as a prerequisite for building the :mod:`grp` module.
```

File: configure.ac [hunk 2]
```diff
@@ -7293,7 +7293,9 @@ PY_STDLIB_MOD([_socket],
                     -a "$ac_cv_header_netinet_in_h" = "yes"]))
 
 dnl platform specific extensions
-PY_STDLIB_MOD([grp], [], [test "$ac_cv_func_getgrgid" = yes -o "$ac_cv_func_getgrgid_r" = yes])
+PY_STDLIB_MOD([grp], [],
+  [test "$ac_cv_func_getgrent" = yes &&
+   test "$ac_cv_func_getgrgid" = yes -o "$ac_cv_func_getgrgid_r" = yes])
```
Comment (erlend-aasland) [inline configure.ac]: Quoting the Autoconf guide for portable shell programming:

> The `-a`, `-o`, `(`, and `)` operands are not present in all implementations, and have been marked obsolete by Posix 2008. This is because there are inherent ambiguities in using them.

Let's fix the `-o` usage now that we have the opportunity:

```suggestion
  [test "$ac_cv_func_getgrent" = "yes" &&
   { test "$ac_cv_func_getgrgid" = "yes" || test "$ac_cv_func_getgrgid_r" = "yes"; }])
```

(You'll have to regen configure after applying this suggestion.)

**Review by erlend-aasland — COMMENTED** [review]
Thanks!

**Comment by mhsmith** [comment]
Thanks; suggestions all applied.

**Review by erlend-aasland — APPROVED** [review]

**Comment by erlend-aasland** [comment]
Thanks again :)
