### PR TITLE
gh-114563: C decimal falls back to pydecimal for unsupported format strings

### LINKED ISSUE #114563: Possible memory leak in _cdecimal.c with 'z' format
# Bug report

### Bug description:

See https://mail.python.org/archives/list/python-announce-list@python.org/thread/DHZROL7YYJZTPWJQ3WME4HI3Z65K2H4F/

This feature was originally implemented in https://github.com/python/cpython/pull/30049

I have not verified the memory leak or looked at Stefan's suggestions.

@mdickinson @belm0 

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

_No response_

### Linked PRs
* gh-114879
* gh-115353
* gh-115384

### PR DESCRIPTION
**Pull request by belm0**
When the mpdecimal lib fails to parse a format string, we fall back to the pydecimal format implementation.

Notably this allows complex workarounds for 'z' format support to be removed.  (mpdecimal added 'z' support in [version 4.0.0](https://www.bytereef.org/mpdecimal/changelog.html), so this becomes efficient in the long term.)

  * remove 'z' format implementation from C decimal
  * fix 'z' format memory leak
  * fix 'z' format applied to type 'F'
  * fix missing '#' format support

Suggested and prototyped by Stefan Krah.

Fixes gh-114563, gh-91060

### CODE REVIEW

File: Modules/_decimal/_decimal.c [hunk 1]
```diff
@@ -3411,6 +3364,55 @@ dict_get_item_string(PyObject *dict, const char *key, PyObject **valueobj, const
...
+    pydec = PyObject_CallFunctionObjArgs(state->PyDecimal, u, NULL);
+    Py_DECREF(u);
+    if (pydec == NULL) {
+        return NULL;
+    }
+
+    result = PyObject_CallMethod(pydec, "__format__", "(O)", fmt);
+    Py_DECREF(pydec);
+
+    if (result == NULL) {
```
Comment (mdickinson) [inline Modules/_decimal/_decimal.c]: Can we restrict this to just catching `ValueError`, so that other exceptions propagate as normal?

**Review by mdickinson — COMMENTED** [review]
LGTM, with one suggestion about the exception handling for the `__format__` call.

@skrah Thank you for your help with this. If you happen to have the bandwidth and inclination to take a quick glance at this PR, I'd very much appreciate your input.

File: Modules/_decimal/_decimal.c [hunk 2]
```diff
@@ -3411,6 +3364,55 @@ dict_get_item_string(PyObject *dict, const char *key, PyObject **valueobj, const
...
+
+    if (state->PyDecimal == NULL) {
+        PyObject *obj = PyImport_ImportModule("_pydecimal");
+        if (obj == NULL) {
+            return NULL;
+        }
+
+        state->PyDecimal = PyObject_GetAttrString(obj, "Decimal");
+        Py_DECREF(obj);
+
```
Comment (serhiy-storchaka) [inline Modules/_decimal/_decimal.c]: Since this code is not limited to pure public C API, you can use `_PyImport_GetModuleAttrString()`.
```suggestion
        state->PyDecimal = _PyImport_GetModuleAttrString("_pydecimal", "Decimal");
```

File: Modules/_decimal/_decimal.c [hunk 3]
```diff
@@ -3411,6 +3364,55 @@ dict_get_item_string(PyObject *dict, const char *key, PyObject **valueobj, const
...
+        return NULL;
+    }
+
+    pydec = PyObject_CallFunctionObjArgs(state->PyDecimal, u, NULL);
+    Py_DECREF(u);
+    if (pydec == NULL) {
+        return NULL;
+    }
+
+    result = PyObject_CallMethod(pydec, "__format__", "(O)", fmt);
```
Comment (serhiy-storchaka) [inline Modules/_decimal/_decimal.c]:
```suggestion
    result = PyObject_Format(pydec, fmt);
```

File: Modules/_decimal/_decimal.c [hunk 4]
```diff
@@ -3411,6 +3364,55 @@ dict_get_item_string(PyObject *dict, const char *key, PyObject **valueobj, const
...
+            return NULL;
+        }
+    }
+
+    u = dec_str(dec);
+    if (u == NULL) {
+        return NULL;
+    }
+
+    pydec = PyObject_CallFunctionObjArgs(state->PyDecimal, u, NULL);
```
Comment (serhiy-storchaka) [inline Modules/_decimal/_decimal.c]:
```suggestion
    pydec = PyObject_CallOneArg(state->PyDecimal, u);
```

File: Modules/_decimal/_decimal.c [hunk 5]
```diff
@@ -3423,16 +3425,11 @@ dec_format(PyObject *dec, PyObject *args)
     PyObject *fmtarg;
     PyObject *context;
     mpd_spec_t spec;
-    char const *fmt;
-    char *fmt_copy = NULL;
+    char *fmt;
```
Comment (serhiy-storchaka) [inline Modules/_decimal/_decimal.c:3421]: It is not related to handling the 'z' format. It is safer to keep `fmt` a const string.

File: Lib/test/test_decimal.py [hunk 6]
```diff
@@ -1111,6 +1111,12 @@ def test_formatting(self):
             ('x>z6.1f', '-0.', 'xxx0.0'),
             ('🖤>z6.1f', '-0.', '🖤🖤🖤0.0'),  # multi-byte fill char
```
Comment (serhiy-storchaka) [inline Lib/test/test_decimal.py:1112]: Is there a test for 'z' format with null fill character?
```suggestion
            ('🖤>z6.1f', '-0.', '🖤🖤🖤0.0'),  # multi-byte fill char
            ('\0>z6.1f', '-0.', '\0\0\00.0'),  # null fill char
```

File: Modules/_decimal/_decimal.c (hunk 1 above)
Comment (skrah) [reply Modules/_decimal/_decimal.c]: Yes, that's nicer.

**Comment by skrah** [comment]
If I checkout d96a8cdfe201546f6d077fa93953b695c4ea8c59 and then apply my own patches, I reach the exact same state as in this PR.

When comparing the result to `3.9`, the diff in the `dec_format` area is clean and manageable.

I tested my own patches with `deccheck` (z-format extended version), so I approve!

@serhiy-storchaka's `pydec_format` changes look correct to me, but I'd have to look up some of the new functions, so I'll stay out of that part.

File: Modules/_decimal/_decimal.c (hunk 5 above)
Comment (skrah) [reply Modules/_decimal/_decimal.c:3421]: I disagree for two reasons:

The revert of the z-format change should be clean. Then, `fmt` is allocated iff `replace_fillchar` is true, so I do not see any safety issues in general. `replace_fillchar` is more informative than `fmt_copy` (and the 3.9 code has been tested with my own test suite patches that inject all allocation failures).

Comment (serhiy-storchaka) [reply Modules/_decimal/_decimal.c:3421]: You should be care to not modify the content referred by `fmt` without a help from the C compiler, but otherwise it is not a big deal.

Comment (belm0) [reply Modules/_decimal/_decimal.c:3421]: While I don't doubt the code prior to the original `z` format PR was correct, I added this const-correctness because the PR was doing yet more hacking of the format string, and I wanted the overall code to be clear and supported by compile-time checks as much as possible.

I'm OK to revert this change, but I think there are advantages to the new implementation.

File: Lib/test/test_decimal.py (hunk 6 above)
Comment (belm0) [reply Lib/test/test_decimal.py:1112]: this added null fill test fails

```
AssertionError: '\x00\x00\x000.0' != '\x00\x00\x00.0'
- 0.0
?    -
+ .0
```

I'm not sure which is correct, nor how the new mpdecimal `z` implementation will respond, so perhaps this is for another PR.

File: Lib/test/test_decimal.py [hunk 7]
```diff
@@ -1110,6 +1110,13 @@ def test_formatting(self):
             ('z>z6.1f', '-0.', 'zzz0.0'),
             ('x>z6.1f', '-0.', 'xxx0.0'),
             ('🖤>z6.1f', '-0.', '🖤🖤🖤0.0'),  # multi-byte fill char
+            ('\0>z6.1f', '-0.', '\0\0\00.0'),  # null fill char
```
Comment (serhiy-storchaka) [inline Lib/test/test_decimal.py]:
```suggestion
            ('\x00>z6.1f', '-0.', '\x00\x00\x000.0'),  # null fill char
```

File: Lib/test/test_decimal.py (hunk 6 above)
Comment (belm0) [reply Lib/test/test_decimal.py:1112]: (Serhiy corrected the test-- thank you)

**Review by serhiy-storchaka — APPROVED** [review]
LGTM.

Is it okay that the PyDecimal instance can have a different context?

**Comment by skrah** [comment]
> Is it okay that the PyDecimal instance can have a different context?

This is an excellent observation! It is the one thing that cannot be caught by `deccheck`, because the `_decimal` and `_pydecimal` contexts are always in sync. `_pydecimal.__format__` needs `rounding` and `capitals`.

Maybe the easiest thing would be to add another private  method to `_pydecimal`, something like:

```
def fallback_format(self, specifier, rounding, caps):
    # make a new context with rounding and caps
    # return __format__ with that context
```

File: Modules/_decimal/_decimal.c [hunk 8]
```diff
@@ -3411,6 +3364,48 @@ dict_get_item_string(PyObject *dict, const char *key, PyObject **valueobj, const
...
+            return NULL;
+        }
+    }
+
+    u = dec_str(dec);
+    if (u == NULL) {
+        return NULL;
+    }
+
+    pydec = PyObject_CallOneArg(state->PyDecimal, u);
```
Comment (belm0) [inline Modules/_decimal/_decimal.c:3391]: > > Is it okay that the PyDecimal instance can have a different context?
> 
> This is an excellent observation! It is the one thing that cannot be caught by deccheck, because the _decimal and _pydecimal contexts are always in sync. _pydecimal.__format__ needs rounding and capitals.
> 
> Maybe the easiest thing would be to add another private method to _pydecimal, something like:
> 
> ```python
> def fallback_format(self, specifier, rounding, caps):
>     # make a new context with rounding and caps
>     # return __format__ with that context
> ```

(trying to move this to a thread at relevant part of the code)

Is the problem here, at the invocation of `Decimal` constructor?

I'm not sure how to call it correctly, or why it isn't enough to adopt the existing context.

Comment (skrah) [reply Modules/_decimal/_decimal.c:3391]: The decimal constructor is fine. It can only raise on an invalid input (which cannot happen here, since the output of `tosci` is valid).

The following is very quick and dirty and possibly full of mistakes. It is just to show the idea.

In _pydecimal, something like this:

```
--- cpython/Lib/_pydecimal.py   2024-02-10 13:48:19.119618369 +0000
+++ XXX/Lib/_pydecimal.py       2024-02-10 22:12:17.513196343 +0000
@@ -3841,6 +3841,10 @@
         # of the formatting to the _format_number function
         return _format_number(adjusted_sign, intpart, fracpart, exp, spec)
 
+    def fallback_format(self, specifier, rounding, caps):
+        c = Context(rounding=rounding, capitals=caps)
+        return self.__format__(specifier, c)
+
 def _dec_from_triple(sign, coefficient, exponent, special=False):
     """Create a decimal instance directly, without any validation,
     normalization (e.g. removal of leading zeros) or argument
```

In _decimal, something like this:

```
--- cpython/Modules/_decimal/_decimal.c 2024-02-10 19:40:48.125845778 +0000
+++ XXX/Modules/_decimal/_decimal.c     2024-02-10 22:17:33.494205488 +0000
@@ -3370,10 +3370,12 @@
  * https://www.bytereef.org/mpdecimal/doc/libmpdec/assign-convert.html#to-string
  */
 static PyObject *
-pydec_format(PyObject *dec, PyObject *fmt, decimal_state *state)
+pydec_format(PyObject *dec, PyObject *context, PyObject *fmt, decimal_state *state)
 {
     PyObject *result;
     PyObject *pydec;
+    PyObject *rounding;
+    PyObject *caps;
     PyObject *u;
 
     if (state->PyDecimal == NULL) {
@@ -3394,7 +3396,12 @@
         return NULL;
     }
 
-    result = PyObject_Format(pydec, fmt);
+    rounding = context_getround(context, NULL);
+    caps = context_getcapitals(context, NULL);
+
+    result = PyObject_CallMethod(pydec, "fallback_format", "(OOO)", fmt, rounding, caps);
+    Py_DECREF(rounding);
+    Py_DECREF(caps);
     Py_DECREF(pydec);
 
     if (result == NULL && PyErr_ExceptionMatches(PyExc_ValueError)) {
@@ -3466,7 +3473,7 @@
             PyMem_Free(fmt);
         }
 
-        return pydec_format(dec, fmtarg, state);
+        return pydec_format(dec, context, fmtarg, state);
     }
 
     if (replace_fillchar) {
```

Comment (belm0) [reply Modules/_decimal/_decimal.c:3391]: added with unit tests

File: Modules/_decimal/_decimal.c [hunk 9]
```diff
@@ -3411,6 +3364,54 @@ dict_get_item_string(PyObject *dict, const char *key, PyObject **valueobj, const
...
+    Py_DECREF(u);
+    if (pydec == NULL) {
+        return NULL;
+    }
+
+    rounding = context_getround(context, NULL);
+    caps = context_getcapitals(context, NULL);
+    result = PyObject_CallMethod(pydec, "_fallback_format", "(OOO)", fmt, rounding, caps);
```
Comment (serhiy-storchaka) [inline Modules/_decimal/_decimal.c]: `context_getcapitals()` can fail, so you need to check its result. It is easy to pass `CtxCaps(context)` to `PyObject_CallMethod()` and use format unit "i".

But if you have a context object, why not pass it directly to `__format__()`, without an intermediate method? From Python point of view, both C and Python implementations of Context should be compatible.

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by skrah** [comment]
This is a clever use of the `_decimal` context! It works because `ctx.rounding` is a string and `ctx.capitals` is a bool. For others who happen to come by this issue, I want to (pedantically) point out that the `_pydecimal` and `_decimal` contexts are not in general interchangeable.

LGTM.

**Review by skrah — APPROVED** [review]

**Review by serhiy-storchaka — COMMENTED** [review]
Now please add a NEWS entry (it is a user visible change), and it will be done.

Describe what behavior was changed, not implementation details.

File: Misc/NEWS.d/next/Library/2024-02-11-20-23-36.gh-issue-114563.RzxNYT.rst [hunk 10]
```diff
@@ -0,0 +1,4 @@
+Fix several `format()` bugs when using the C implementation of `Decimal`:
+* memory leak in some rare cases when using the `z` format option (coerce negative 0)
```
Comment (serhiy-storchaka) [inline Misc/NEWS.d/next/Library/2024-02-11-20-23-36.gh-issue-114563.RzxNYT.rst]: It is reStructuredText, not Markdown. Use either double backquotes ``` ``z`` ```, or simple quotes 'z', or no quotes at all.

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by serhiy-storchaka** [comment]
@belm0, do you mind to create a backport for 3.12?

It will be easier to backport then from 3.12 to 3.11 than directly to 3.11.
