### PR TITLE
gh-124022: Fix bug where class docstring is removed in interactive mode

### LINKED ISSUE #124022: class docstring is removed in interactive mode
```
>>> import dis
>>> src = """class C:
...     "docstring"
...     x = 42"""
>>> dis.dis(compile(src, "<string>", "single"))
  0           RESUME                   0

  1           LOAD_BUILD_CLASS
              PUSH_NULL
              LOAD_CONST               0 (<code object C at 0x10c3b4f40, file "<string>", line 1>)
              MAKE_FUNCTION
              LOAD_CONST               1 ('C')
              CALL                     2
              STORE_NAME               0 (C)
              RETURN_CONST             2 (None)

Disassembly of <code object C at 0x10c3b4f40, file "<string>", line 1>:
  1           RESUME                   0
              LOAD_NAME                0 (__name__)
              STORE_NAME               1 (__module__)
              LOAD_CONST               0 ('C')
              STORE_NAME               2 (__qualname__)
              LOAD_CONST               1 (1)
              STORE_NAME               3 (__firstlineno__)

  2           NOP                                             <--- line 2 is where the docstring is. This NOP shouldn't be here

  3           LOAD_CONST               2 (42)
              STORE_NAME               4 (x)
              LOAD_CONST               3 (())
              STORE_NAME               5 (__static_attributes__)
              RETURN_CONST             4 (None)

```

### Linked PRs
* gh-124023
* gh-124052
* gh-124075

### PR DESCRIPTION
**Pull request by iritkatriel**
Fixes #124022.

Class docstring is removed in interactive mode, but since the `first_instr` is not bumped to 1, this ends up being a `NOP` with the line number of the docstring.

* Issue: gh-124022

### CODE REVIEW

File: Python/codegen.c [hunk 1]
```diff
@@ -758,10 +758,10 @@ _PyCodegen_Body(compiler *c, location loc, asdl_stmt_seq *stmts)
...
     }
     Py_ssize_t first_instr = 0;
-    if (!IS_INTERACTIVE(c)) {
-        PyObject *docstring = _PyAST_GetDocString(stmts);
-        if (docstring) {
-            first_instr = 1;
+    PyObject *docstring = _PyAST_GetDocString(stmts);
+    if (docstring) {
+        first_instr = 1;
+        if (!IS_INTERACTIVE(c)) {
```
Comment (JelleZijlstra) [inline Python/codegen.c]: Why does this depend on interactive mode at all? I see that class docstrings are removed on current main in the REPL, but I'm not sure why that would happen, and it doesn't match the behavior on 3.12.

Comment (iritkatriel) [reply Python/codegen.c]: It seems to have been added here: https://github.com/python/cpython/commit/9b8611eeea172cd4aa626ccd1ca333dc4093cd8c#diff-ebc983d9f91e5bcf73500e377ac65e85863c4f77fd5b6b6caf4fcdf7c0f0b057R1506

Comment (JelleZijlstra) [reply Python/codegen.c]: Oops. I don't know why I did that, I don't think it makes sense. I can take over this fix if you like since it's my bug.

Comment (iritkatriel) [reply Python/codegen.c]: It's not your bug. Once you commit it it's our bug.

Comment (iritkatriel) [reply Python/codegen.c]: So I just remove the `if (!IS_INTERACTIVE(c)` ?

Comment (JelleZijlstra) [reply Python/codegen.c]: I think so, the condition should just be removed. My best guess is I was messing around with some interaction between annotations and interactive mode, and ended up with this change. The code block deals purely with docstrings and not annotations though, so I should never have made this change.

And yes, it's not just my bug now because it's been merged, but I still feel a sense of responsibility for what I committed :)

Comment (iritkatriel) [reply Python/codegen.c]: It a nice bug, one that nobody will ever care about.

File: Lib/test/test_compile.py [hunk 2]
```diff
@@ -919,12 +935,13 @@ class C:
                 return h
         """)
         for opt in [-1, 0, 1, 2]:
-            with self.subTest(opt=opt):
-                code = compile(src, "<test>", "exec", optimize=opt)
-                output = io.StringIO()
-                with contextlib.redirect_stdout(output):
-                    dis.dis(code)
-                self.assertNotIn('NOP' , output.getvalue())
+            for mode in ["exec",  "single"]:
```
Comment (JelleZijlstra) [inline Lib/test/test_compile.py]:
```suggestion
            for mode in ["exec", "single"]:
```

File: Lib/test/test_compile.py [hunk 3]
```diff
@@ -919,12 +935,13 @@ class C:
...
+                with self.subTest(opt=opt, mode=mode):
+                    code = compile(src, "<test>", mode, optimize=opt)
+                    output = io.StringIO()
+                    with contextlib.redirect_stdout(output):
+                        dis.dis(code)
+                    self.assertNotIn('NOP' , output.getvalue())
```
Comment (JelleZijlstra) [inline Lib/test/test_compile.py]:
```suggestion
                    self.assertNotIn('NOP', output.getvalue())
```

File: Lib/test/test_compile.py [hunk 4]
```diff
@@ -902,6 +902,22 @@ def with_const_expression():
                 self.assertIsNone(ns['with_fstring'].__doc__)
                 self.assertIsNone(ns['with_const_expression'].__doc__)
 
+    @support.cpython_only
+    def test_docstring_interactive_mode(self):
+        src = textwrap.dedent("""
```
Comment (JelleZijlstra) [inline Lib/test/test_compile.py]: Maybe test both a class and a function here

File: Misc/NEWS.d/next/Core_and_Builtins/2024-09-12-21-53-26.gh-issue-124022.fQzUiW.rst [hunk 5]
```diff
@@ -0,0 +1 @@
+Fix bug where docstring it removed from classes in interactive mode.
```
Comment (JelleZijlstra) [inline Misc/NEWS.d/next/Core_and_Builtins/2024-09-12-21-53-26.gh-issue-124022.fQzUiW.rst]:
```suggestion
Fix bug where docstring is removed from classes in interactive mode.
```

**Review by JelleZijlstra — COMMENTED** [review]
Thanks, some small suggestions

**Review by JelleZijlstra — APPROVED** [review]

**Comment by JelleZijlstra** [comment]
A number of tests are failing. The issue is that now string literals in the REPL are interpreted as docstrings:

```
>>> "x"
>>> __doc__
'x'
```

I now also understand why I made the change. I changed the code so that Interactive_kind uses `compiler_body()` (because I wanted to reuse its annotation handling), but I had to add the is_interactive condition to prevent the bug we're now seeing. The problem is that `compiler_body()` also gets called in other cases within a larger interactive code object, and there we don't want to strip the docstring.

A more robust solution would be to add a parameter to `_PyCodeGen_Body` to reflect whether we're in interactive mode. I'll push that change, but if you'd prefer a different solution, I'm open to it.

File: Python/codegen.c [hunk 6]
```diff
@@ -758,7 +758,10 @@ _PyCodegen_Body(compiler *c, location loc, asdl_stmt_seq *stmts)
         return SUCCESS;
     }
     Py_ssize_t first_instr = 0;
-    if (!IS_INTERACTIVE(c)) {
+    // If this is a top-level interactive statement, we don't want to
+    // extract a docstring, because then writing a string literal in the REPL
+    // would get interpreted as a docstring.
+    if (!is_interactive) {
```
Comment (iritkatriel) [inline Python/codegen.c]:
```suggestion
    if (!is_interactive) {      /* A string literal typed on the REPL prompt is not a docstring */
```

File: Python/codegen.c [hunk 7]
```diff
@@ -758,7 +758,7 @@ _PyCodegen_Body(compiler *c, location loc, asdl_stmt_seq *stmts)
         return SUCCESS;
     }
     Py_ssize_t first_instr = 0;
-    if (!IS_INTERACTIVE(c)) {
+    if (!is_interactive) {      /* A string literal typed on the REPL prompt is not a docstring */
```
Comment (iritkatriel) [inline Python/codegen.c]:
```suggestion
    if (!is_interactive) { /* A string literal on REPL prompt is not a docstring */
```

**Review by JelleZijlstra — APPROVED** [review]
