### PR TITLE
gh-102493: fix normalization in PyErr_SetObject

### LINKED ISSUE #102493: gh-101607 causes regression in third-party psutil package on macOS
As part of the cPython release process for macOS installers, besides the standard cPython test suite, we run a small set of additional smoke tests. One of these involves an install from source of [the psutil package](https://github.com/giampaolo/psutil) which includes the building of a C extension module. In the run up to the 3.12.0a6 release, we found that our long-unchanged simple test was now failing, a regression from 3.12.0a5 and 3.11.x. The commit causing the failure was bisected to feec49c40736fc05626a183a8d14c4ebbea5ae28 from GH-101607, a part of issue #101578. From a cursory glance at the traceback and the psutil code, it appears that psutil uses a [decorator to translate certain OSError exceptions](https://github.com/giampaolo/psutil/blob/master/psutil/_psosx.py#L339) from its C module into other Python exceptions that its calling code is prepared to handle or ignore. For some reason, that exception translation is now failing. FWIW, this is the first failure of this psutil smoke test in recent memory including previous 3.12.0 alphas. Also, FWIW, this same smoke test does not fail on a reasonably recent Debian Linux system but, of course, that exercises a different platform-dependent code path in psutil.

Because of its dependencies, it is a bit complicated to build and reproduce without changes. Here is one way to do it; it is likely not optimal. This assumes a fairly recent macOS system with Homebrew installed (as described in the devguide) and assumes git checkouts of the cpython and psutil Github repos.

```
brew install pkg-config openssl@1.1 xz

mkdir /tmp/test_psutil
cd /tmp/test_psutil
git clone https://github.com/giampaolo/psutil.git
git clone https://github.com/python/cpython.git # or from an existing repo

cd cpython
git checkout feec49c40736fc05626a183a8d14c4ebbea5ae28^ # last good commit
git clean -fdxq
./configure -q  --prefix=/tmp/none --with-pydebug \
              --with-openssl="$(brew --prefix openssl@1.1)"
make -s -j2
cd ..
git -C ./psutil clean -fdxq
rm -rf venv
./cpython/python.exe -m venv venv
venv/bin/python -m pip install --no-binary psutil ./psutil/
venv/bin/python -c 'import psutil, pprint; pprint.pprint(list(psutil.process_iter()))'
```
The expected result should be something like:

```
[psutil.Process(pid=0, name='kernel_task', status='running', started='03:25:52'),
 psutil.Process(pid=1, name='launchd', status='running', started='03:25:52'),
 psutil.Process(pid=75, name='logd', status='running', started='03:25:54'),
 psutil.Process(pid=76, name='UserEventAgent', status='running', started='03:25:54'),
 ...

```

With the failing commit applied (up to and including the current head of the main branch):

`git checkout feec49c40736fc05626a183a8d14c4ebbea5ae28 # failing commit
`

and repeating the above build and test, the result is now something like:

 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/tmp/cpython/Lib/pprint.py", line 55, in pprint
    printer.pprint(object)
  File "/private/tmp/cpython/Lib/pprint.py", line 153, in pprint
    self._format(object, self._stream, 0, 0, {}, 0)
  File "/private/tmp/cpython/Lib/pprint.py", line 175, in _format
    rep = self._repr(object, context, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/cpython/Lib/pprint.py", line 455, in _repr
    repr, readable, recursive = self.format(object, context.copy(),
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/cpython/Lib/pprint.py", line 468, in format
    return self._safe_repr(object, context, maxlevels, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/cpython/Lib/pprint.py", line 619, in _safe_repr
    orepr, oreadable, orecur = self.format(
                               ^^^^^^^^^^^^
  File "/private/tmp/cpython/Lib/pprint.py", line 468, in format
    return self._safe_repr(object, context, maxlevels, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/cpython/Lib/pprint.py", line 629, in _safe_repr
    rep = repr(object)
          ^^^^^^^^^^^^
  File "/private/tmp/venv/lib/python3.12/site-packages/psutil/__init__.py", line 389, in __str__
    info["name"] = self.name()
                   ^^^^^^^^^^^
  File "/private/tmp/venv/lib/python3.12/site-packages/psutil/__init__.py", line 628, in name
    cmdline = self.cmdline()
              ^^^^^^^^^^^^^^
  File "/private/tmp/venv/lib/python3.12/site-packages/psutil/__init__.py", line 681, in cmdline
    return self._proc.cmdline()
           ^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/venv/lib/python3.12/site-packages/psutil/_psosx.py", line 346, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/venv/lib/python3.12/site-packages/psutil/_psosx.py", line 404, in cmdline
    return cext.proc_cmdline(self.pid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 1] Operation not permitted (originated from sysctl(KERN_PROCARGS2))

```

Note this seems to come from trying to inspect a privileged process and the point of the exception wrapping is to effectively ignore such errors.

Flagging as a potential release-blocker for @Yhg1s

### Linked PRs
* gh-102502
* gh-102602

### PR DESCRIPTION
**Pull request by iritkatriel**
Fixes #102493.

* Issue: gh-102493

### CODE REVIEW

File: Misc/NEWS.d/next/Core and Builtins/2023-03-07-16-56-28.gh-issue-102502.gTXrcD.rst [hunk 1]
```diff
@@ -0,0 +1 @@
+Fix regression in semantics of normalisation in ``PyErr_SetObject``.
```
Comment (ned-deily) [inline Misc/NEWS.d/next/Core and Builtins/2023-03-07-16-56-28.gh-issue-102502.gTXrcD.rst]: It looks like the blurb entry used the PR number (gh-102502) rather than the issue number (gh-102493).

**Review by ned-deily — COMMENTED** [review]
One minor nit about the NEWS blurb entry but otherwise I verified that the PR does fix the observed regression with psutil on macOS and that no new test suite regressions are observed.  Thanks, @iritkatriel, for the fast work!

**Review by Yhg1s — APPROVED** [review]

**Review by ned-deily — APPROVED** [review]

File: Python/errors.c [hunk 2]
```diff
@@ -208,7 +215,7 @@ _PyErr_SetObject(PyThreadState *tstate, PyObject *exception, PyObject *value)
     }
     if (value != NULL && PyExceptionInstance_Check(value))
         tb = PyException_GetTraceback(value);
-    _PyErr_Restore(tstate, Py_XNewRef(exception), value, tb);
+    _PyErr_Restore(tstate, Py_NewRef(Py_TYPE(value)), value, tb);
```
Comment (JelleZijlstra) [inline Python/errors.c:219]: This would crash if `value` is NULL. The if check immediately above suggests that that is possible here.

File: Python/errors.c [hunk 3]
```diff
@@ -151,7 +151,14 @@ _PyErr_SetObject(PyThreadState *tstate, PyObject *exception, PyObject *value)
     }
     Py_XINCREF(value);
     /* Normalize the exception */
-    if (value == NULL || (PyObject *)Py_TYPE(value) != exception) {
+    int is_subclass = 0;
+    if (value != NULL) {
+        is_subclass = PyObject_IsSubclass((PyObject*)Py_TYPE(value), exception);
```
Comment (JelleZijlstra) [inline Python/errors.c]:
```suggestion
        is_subclass = PyObject_IsSubclass((PyObject *)Py_TYPE(value), exception);
```

Comment (gvanrossum) [inline Python/errors.c]: IIUC `PyObject_IsSubclass` is relatively expensive. What if we skip calling it when `(PyObject *)Py_TYPE(value) != exception`?

Comment (iritkatriel) [reply Python/errors.c]: I don't think it can be, if it's NULL then it gets assigned fixed_value above. I can change this to be an assertion.

Comment (iritkatriel) [reply Python/errors.c]: That's not equivalent though.

Comment (Yhg1s) [reply Python/errors.c]: I think Guido meant `is_subclass = (Py_TYPE(value) == exception || PyObject_IsSubclass(Py_TYPE(value), exception)`.

Comment (gvanrossum) [reply Python/errors.c]: You'd have to do
```
if ((PyObject *)Py_TYPE(value) == exception)
    is_subclass = 1;
else
    is_subclass = PyObject_IsSubclass((PyObject*)Py_TYPE(value), exception);
```
(After the NULL check.)

Don't hold up the alpha for this though.

Comment (gvanrossum) [reply Python/errors.c]: (Whoops, note `==`, not `!=`. Corrected in place.)

Comment (iritkatriel) [reply Python/errors.c]: Do you mean when it's not an exception, as in `!PyExceptionInstance_Check(value)`?

Comment (gvanrossum) [reply Python/errors.c]: Never mind me.

**Review by JelleZijlstra — APPROVED** [review]

File: Python/errors.c (hunk 3 above)
Comment (Yhg1s) [reply Python/errors.c]: After checking PyObject_IsSubclass, I don't think it's worth it: after a bit of indirection through tstate it does:

```
    /* We know what type's __subclasscheck__ does. */
    if (PyType_CheckExact(cls)) {
        /* Quick test for an exact match */
        if (derived == cls)
            return 1;
```
... so it's only an extra pointer comparison and a couple of quick C function calls more expensive in this case.

**Review by gvanrossum — APPROVED** [review]

File: Python/errors.c [hunk 4]
```diff
@@ -151,7 +151,14 @@ _PyErr_SetObject(PyThreadState *tstate, PyObject *exception, PyObject *value)
     }
     Py_XINCREF(value);
     /* Normalize the exception */
-    if (value == NULL || (PyObject *)Py_TYPE(value) != exception) {
+    int is_subclass = 0;
+    if (value != NULL && PyExceptionInstance_Check(value)) {
+        is_subclass = PyObject_IsSubclass((PyObject *)Py_TYPE(value), exception);
+        if (is_subclass < 0) {
+            return;
```
Comment (Yhg1s) [inline Python/errors.c:157]: I think this would leak the reference to value (it was INCREFed on line 152).

Comment (iritkatriel) [reply Python/errors.c:157]: I see what you mean, but this should have caused 

`./python.exe -m test -v -R3:3 test_capi -m test_set_object`

to fail and it didn't, so I want to understand why.

Comment (Yhg1s) [reply Python/errors.c:157]: Did you add a test that involves a `__subclasscheck__` that raises an exception?

Comment (iritkatriel) [reply Python/errors.c:157]: ah that's the case where the is subclass check fails. it's not covered in the tests.

**Review by Yhg1s — APPROVED** [review]
