### PR TITLE
gh-87822: Make traceback module robust to exceptions from repr() of local values

### LINKED ISSUE #87822: TracebackException or StackSummary.extract with capture_locals=True fail to catch exceptions raised by repr() on value of frame local variable in FrameSummary.__init__.
BPO | [43656](https://bugs.python.org/issue43656)
--- | :---
Nosy | @rbtcollins, @serhiy-storchaka, @iritkatriel, @moi90, @akulakov
PRs | <li>python/cpython#25062</li><li>python/cpython#29299</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-03-29.09:36:49.757>
labels = ['invalid', 'type-feature', '3.8', '3.9', '3.10']
title = 'TracebackException or StackSummary.extract with capture_locals=True fail to catch exceptions raised by repr() on value of frame local variable in FrameSummary.__init__.'
updated_at = <Date 2021-11-25.14:52:05.471>
user = 'https://github.com/moi90'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-25.14:52:05.471>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-03-29.09:36:49.757>
creator = 'moi90'
dependencies = []
files = []
hgrepos = []
issue_num = 43656
keywords = ['patch']
message_count = 43.0
messages = ['389679', '389680', '389794', '389815', '389819', '389840', '389842', '393199', '393298', '393519', '404319', '404330', '404392', '404445', '404452', '404456', '404457', '404464', '404468', '404514', '404567', '404603', '404736', '404950', '404988', '404989', '405028', '405033', '405049', '405214', '405238', '405893', '405918', '405935', '405994', '406008', '406012', '406042', '406107', '406997', '406998', '406999', '407001']
nosy_count = 6.0
nosy_names = ['rbcollins', 'serhiy.storchaka', 'iritkatriel', 'moi90', 'andrei.avk', 'jbw']
pr_nums = ['25062', '29299']
priority = 'normal'
resolution = 'not a bug'
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue43656'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

### PR DESCRIPTION
**Pull request by moi90**
Fixes #87822.

* Issue: gh-87822

### CODE REVIEW

File: Misc/NEWS.d/next/Library/2022-07-08-17-49-12.gh-issue-87822.F9dzkf.rst [hunk 1]
```diff
@@ -0,0 +1 @@
+Make FrameSummary robust to unrepresentable values.
```
Comment (iritkatriel) [inline Misc/NEWS.d/next/Library/2022-07-08-17-49-12.gh-issue-87822.F9dzkf.rst]:
```suggestion
When called with ``capture_locals=True``, the :mod:`traceback` module functions swallow exceptions raised from calls to ``repr()`` on local variables of frames. This is in order to prioritize the original exception over rendering errors.  An indication of the failure is printed in place of the missing value.  (Patch by Simon-Martin Schroeder).
```

File: Lib/test/test_traceback.py [hunk 2]
```diff
@@ -2514,12 +2517,12 @@ def test_locals(self):
...
         e = Exception("uh oh")
         c = test_code('/foo.py', 'method')
-        f = test_frame(c, globals(), {'something': 1, 'other': 'string'})
+        f = test_frame(c, globals(), {'something': 1, 'other': 'string', 'unrepresentable': Unrepresentable()})
         tb = test_tb(f, 6, None, 0)
         exc = traceback.TracebackException(
             Exception, e, tb, capture_locals=True)
         self.assertEqual(
-            exc.stack[0].locals, {'something': '1', 'other': "'string'"})
+            exc.stack[0].locals, {'something': '1', 'other': "'string'", 'unrepresentable': '<local repr() failed>'})
```
Comment (iritkatriel) [inline Lib/test/test_traceback.py]: Needs to be wrapped to 80 chars.

```suggestion
            exc.stack[0].locals,
            {'something': '1', 'other': "'string'", 'unrepresentable': '<local repr() failed>'})
```

File: Doc/library/traceback.rst [hunk 3]
```diff
@@ -339,7 +339,9 @@ capture data for later printing in a lightweight fashion.
       creating the :class:`StackSummary` cheaper (which may be valuable if it
       may not actually get formatted). If *capture_locals* is ``True`` the
       local variables in each :class:`FrameSummary` are captured as object
-      representations.
+      representations. If, for some reason, a representation can not be
+      created (i.e. :func:`repr` fails), it is replaced with a placeholder
+      (``'<local repr() failed>'``).
```
Comment (iritkatriel) [inline Doc/library/traceback.rst]: It's over-specified to include the exact error string. I'm not sure we even need to write in the main text that errors are swallowed (it's not mentioned for the other cases where this is done). So I think it's not necessary as part of the main text, but we should mention the change. So how about remove this sentence, and then add below

```
   .. versionchanged:: 3.12
       Exceptions raised from :func:`repr` on a local variable are no longer propagated to the caller.
```

Comment (arhadthedev) [reply Doc/library/traceback.rst]: > It's over-specified to include the exact error string

Can it go as "to satisfy reader's сuriosity"?

File: Misc/NEWS.d/next/Library/2022-07-08-17-49-12.gh-issue-87822.F9dzkf.rst (hunk 1 above)
Comment (moi90) [reply Misc/NEWS.d/next/Library/2022-07-08-17-49-12.gh-issue-87822.F9dzkf.rst]: Is it customary to include the author? I did not find any other message file that does this.

File: Doc/library/traceback.rst (hunk 3 above)
Comment (moi90) [reply Doc/library/traceback.rst]: I was unsure whether to include the exact "wording", too. I thought this way this section of the documentation pops up in the search results if users search for this error.

File: Misc/NEWS.d/next/Library/2022-07-08-17-49-12.gh-issue-87822.F9dzkf.rst (hunk 1 above)
Comment (arhadthedev) [reply Misc/NEWS.d/next/Library/2022-07-08-17-49-12.gh-issue-87822.F9dzkf.rst]: > Is it customary to include the author

Someone includes, someone doesn't. `git grep "(Patch by "` on `Misc\NEWS.d` gives the following:

```plain
3.11.0b1.rst:for most cases. (Patch by Inada Naoki.)
3.5.0a1.rst:asyncio tests no longer rely on tests.txt file. (Patch by Vajrasky Kok)
3.5.0b1.rst:Property() docstrings are now writeable. (Patch by Berker Peksag.)
3.5.3rc1.rst:dictitems_contains no longer swallows compare errors. (Patch by Xiang Zhang)
3.6.0b2.rst:Enables Unicode for ps1/ps2 and input() prompts. (Patch by Eryk Sun)
3.6.0rc2.rst:completed. (Patch by HoHo-Ho)
3.6.1rc1.rst:Ignores blank lines in ._pth files (Patch by Alexey Izbyshev)
3.6.1rc1.rst:Implement :pep:`529` for io.FileIO (Patch by Eryk Sun)
3.6.1rc1.rst:winreg does not truncate string correctly (Patch by Eryk Sun)
3.6.6rc1.rst:``MetaPathFinder``. (Patch by Himanshu Lakhara)
3.7.0a1.rst:winreg does not truncate string correctly (Patch by Eryk Sun)
3.7.0a1.rst:Enables Unicode for ps1/ps2 and input() prompts. (Patch by Eryk Sun)
3.7.0a3.rst:argument to ``Traceback.format()``. (Patch by Jesse Bakker.)
3.7.0b3.rst:``MetaPathFinder``. (Patch by Himanshu Lakhara)
3.8.0a1.rst:``MetaPathFinder``. (Patch by Himanshu Lakhara)
3.9.0a1.rst:Make json.loads faster for long strings. (Patch by Marco Paolini)
3.9.0a1.rst:of :pep:`442`. Patch by Joannah Nanjekye. (Patch by Joannah Nanjekye)
3.9.0b1.rst:Initialize ``n->n_col_offset``. (Patch by Joannah Nanjekye)
```

Comment (iritkatriel) [reply Misc/NEWS.d/next/Library/2022-07-08-17-49-12.gh-issue-87822.F9dzkf.rst]: It’s standard to add the author in the change log, but not always done. Sometimes the release manager adds the name. If you do it you save them a few clicks.

File: Doc/library/traceback.rst (hunk 3 above)
Comment (iritkatriel) [reply Doc/library/traceback.rst]: We don’t normally put error msg text in the docs for the purpose of it coming up in search engines. 

We also don’t consider them part of the published API. Changing the type of an exception is a backwards compatibility break, but changing the msg is not. So that’s another indication that it shouldn’t be documented.

**Comment by moi90** [comment]
Thanks for the feedback! I made the requested changes.

File: Doc/library/traceback.rst [hunk 4]
```diff
@@ -341,6 +341,10 @@ capture data for later printing in a lightweight fashion.
       local variables in each :class:`FrameSummary` are captured as object
       representations.
 
+      .. versionchanged:: 3.12
+         Exceptions raised from :func:`repr` on a local variable are no longer
+         propagated to the caller and a placeholder is stored instead.
```
Comment (iritkatriel) [inline Doc/library/traceback.rst]:
```suggestion
         propagated to the caller.
```

File: Doc/library/traceback.rst [hunk 5]
```diff
@@ -341,6 +341,10 @@ capture data for later printing in a lightweight fashion.
       local variables in each :class:`FrameSummary` are captured as object
       representations.
 
+      .. versionchanged:: 3.12
+         Exceptions raised from :func:`repr` on a local variable are no longer
+         propagated to the caller.
```
Comment (iritkatriel) [inline Doc/library/traceback.rst]:
```suggestion
         Exceptions raised from :func:`repr` on a local variable (when
         *capture_locals* is ``True``) are no longer propagated to the caller.
```

**Review by iritkatriel — APPROVED** [review]
