### PR TITLE
gh-138584: Fix missing type2test in Lib/tests/list_tests.py 

### LINKED ISSUE #138584: Lib/tests/list_tests.py is missing type2test in a few methods
# Bug report

### Bug description:

There's almost no documentation for the file `Lib/tests/list_tests.py`.  But I infer from context that it's a suite of tests for list-like objects--not just `list`, but `types.UserList` and so on.  (I assumed `collections.deque` would take advantage of this... but it doesn't, huh.)

To use, you define a subclass of `list_tests.CommonTest` that defines a `type2test` method which converts an iterable into an object of your type, and run the tests in that object.  Then, all the tests in that class use that callable to create the objects they test against.

Or... _nearly_ all.  There are (at least) three methods that don't call `self.type2test`; they only test against list objects.  The three methods I found.
- `CommonTest.test_getitem_error`
- `CommonTest.test_setitem_error`
- `CommonTest.test_constructor_exception_handling`

I skimmed over the whole file and only saw those three.  Of course I could have easily missed more.

I think someone should update those three tests so they test objects created using `self.type2test`, and make a more thorough pass over the file making sure there aren't any other missing `type2test` casts.

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

### Linked PRs
* gh-138586
* gh-138590
* gh-138611
* gh-138612

### PR DESCRIPTION
**Pull request by dbXD320**
This PR updates three tests in Lib/test/list_tests.py (CommonTest) to consistently use self.type2test instead of directly constructing a list (or []).

test_getitem_error

test_setitem_error

test_constructor_exception_handling

Previously, these tests only applied to the builtin list, and skipped other list-like classes (such as collections.UserList) that reuse CommonTest.

By switching to self.type2test, the tests now correctly apply to all list-like types under test, ensuring consistency across the test suite.

fixes #138584 

* Issue: gh-138584

### CODE REVIEW

File: Misc/NEWS.d/next/Tests/2025-09-06-21-50-00.gh-issue-138584.XyZ9Ab.rst [hunk 1]
```diff
@@ -0,0 +1 @@
+gh-138584: Fixed list_tests.CommonTest to use type2test in test_getitem_error, test_setitem_error, and test_constructor_exception_handling in Lib/tests/list_tests.py.
```
Comment (picnixz) [inline Misc/NEWS.d/next/Tests/2025-09-06-21-50-00.gh-issue-138584.XyZ9Ab.rst]: Actually, this PR doesn't need a NEWS entry. Let's remove it and I'll add the corresponding label.

Comment (dbXD320) [reply Misc/NEWS.d/next/Tests/2025-09-06-21-50-00.gh-issue-138584.XyZ9Ab.rst]: Okay, But could you please tell me what was causing the error was it gh-138584:? Thanks for the help.

Comment (picnixz) [reply Misc/NEWS.d/next/Tests/2025-09-06-21-50-00.gh-issue-138584.XyZ9Ab.rst]: Do you mean in the NEWS entry? the error was caused by a trailing whitespace on the first line (after the comma).

Comment (dbXD320) [reply Misc/NEWS.d/next/Tests/2025-09-06-21-50-00.gh-issue-138584.XyZ9Ab.rst]: Got it, Thanks

Comment (dbXD320) [reply Misc/NEWS.d/next/Tests/2025-09-06-21-50-00.gh-issue-138584.XyZ9Ab.rst]: Could you Please share some guidance or resources for spotting and avoiding formatting and style issues in Python PRs?

Comment (picnixz) [reply Misc/NEWS.d/next/Tests/2025-09-06-21-50-00.gh-issue-138584.XyZ9Ab.rst]: See PEP-8 for Python code and PEP-7 for C code.

File: Lib/test/list_tests.py [hunk 2]
```diff
@@ -32,13 +32,13 @@ def test_init(self):
...
-        a = []
+        a = self.type2test([])
         msg = "list indices must be integers or slices"
         with self.assertRaisesRegex(TypeError, msg):
             a['a']
 
     def test_setitem_error(self):
-        a = []
+        a = self.type2test([])
         msg = "list indices must be integers or slices"
```
Comment (picnixz) [inline Lib/test/list_tests.py:42]: We could have a different error message here, so that may be the reason why we do this. I think it's good if we still the error message exactly.

Comment (dbXD320) [reply Lib/test/list_tests.py:42]: Thanks for the clarification! I understand why it’s important to keep the error message exactly as is. Is there anything else I should do next?

Comment (picnixz) [reply Lib/test/list_tests.py:42]: I don't know. I want to keep the error message check but at the same time it appears that tests still pass even though we use other types. For the keyboardinterrupt test, it's fine to change it.

Comment (dbXD320) [reply Lib/test/list_tests.py:42]: I’m still new to open source contributions. Could you please guide me on what I should do next to get this PR ready to merge? Should I wait on this PR, or would it be better if I start working on a new issue while it’s being reviewed?

Comment (picnixz) [reply Lib/test/list_tests.py:42]: I'll see how we can move forward tomorrow. Open source contributions may be slow for updates so you can pick other contributions (that is, it's not surprsing that a PR remains stale for a few weeks or months). For this specific PR, I will look at the code when I'm back on my working session.

**Review by serhiy-storchaka — APPROVED** [review]
LGTM. :+1:

**Review by picnixz — APPROVED** [review]
I've checked the usage of this class but I think we can just assume that we'll only be using it for list and userlist so it's fine to keep the error message as is. If it needs to be changed later, we'll just refactor the tests nicely.

**Comment by picnixz** [comment]
For the sake of reducing the diff and correctly improve test coverage, I'm going to backport this.

**Comment by dbXD320** [comment]
@serhiy-storchaka @picnixz Thank you for the review and guidance, I really appreciate it!

**Comment by picnixz** [comment]
Thank *you* for the fix
