### PR TITLE
gh-52551: Fix encoding issues in strftime()

### LINKED ISSUE #52551: time.strftime() and Unicode characters on Windows
BPO | [8304](https://bugs.python.org/issue8304)
--- | :---
Nosy | @terryjreedy, @pfmoore, @abalkin, @vstinner, @ericvsmith, @tjguk, @ezio-melotti, @shimizukawa, @zware, @eryksun, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2010-04-03.15:08:42.673>
labels = ['3.8', '3.9', 'extension-modules', 'expert-unicode', 'type-bug', '3.10', 'library', 'OS-windows']
title = 'time.strftime() and Unicode characters on Windows'
updated_at = <Date 2021-03-08.19:17:29.084>
user = 'https://bugs.python.org/AndiDogold'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-08.19:17:29.084>
actor = 'eryksun'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules', 'Library (Lib)', 'Unicode', 'Windows']
creation = <Date 2010-04-03.15:08:42.673>
creator = 'AndiDog_old'
dependencies = []
files = []
hgrepos = []
issue_num = 8304
keywords = []
message_count = 16.0
messages = ['102269', '102298', '102310', '102332', '102335', '159341', '222667', '226114', '251554', '251558', '251560', '255043', '255133', '388241', '388277', '388286']
nosy_count = 12.0
nosy_names = ['terry.reedy', 'paul.moore', 'belopolsky', 'vstinner', 'eric.smith', 'tim.golden', 'ezio.melotti', 'AndiDog_old', 'shimizukawa', 'zach.ware', 'eryksun', 'steve.dower']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue8304'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

### Linked PRs
* gh-125193
* gh-125657
* gh-125658
* gh-125661

### LINKED ISSUE #124531: `datetime.strftime` strings can be terminated by "\x00" literals
# Bug report

### Bug description:

Apparently the `strftime` parser treats `\x00` as "end of string" in the format code, and the remainder of the string is ignored:

```python
>>> from datetime import datetime
>>> datetime(2024, 9, 25).strftime("\x00%Y-%m-%d")
""
```

I would have expected:

```python
>>> from datetime import datetime
>>> datetime(2024, 9, 25).strftime("\x00%Y-%m-%d")
"\x002024-09-25"
```

Discovered this when adding some hypothesis tests for `strptime`/`strftime`. I suspect again that if you include a null character in your datetime format string you should expect something to act weird as hell about it, but we should probably fix this anyway if it's not too costly.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-125003
* gh-125193

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
Fix time.strftime(), the strftime() method and formatting of the datetime classes datetime, date and time.

* Characters not encodable in the current locale are now acceptable in the format string.
* Surrogate pairs and sequence of surrogatescape-encoded bytes are no longer recombinated.
* Embedded null character no longer terminates the format string.

Closes #52551, #78662 and #124531.

* Issue: gh-52551

* Issue: gh-78662

* Issue: gh-124531

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
@vstinner, could you please review this PR?

File: Modules/_datetimemodule.c [hunk 1]
```diff
@@ -1990,69 +1948,68 @@ wrap_strftime(PyObject *object, PyObject *format, PyObject *timetuple,
...
+            goto Done;
         }
+        newformat = _PyUnicodeWriter_Finish(&writer);
     }
+    if (newformat != NULL) {
+        result = PyObject_CallFunctionObjArgs(strftime,
+                                                newformat, timetuple, NULL);
+        Py_DECREF(newformat);
+    }
+    if (0) {
```
Comment (vstinner) [inline Modules/_datetimemodule.c]: This `if (0)` is weird. Why not adding a label after _PyUnicodeWriter_Dealloc() and using goto?

File: Modules/_datetimemodule.c [hunk 2]
```diff
@@ -1990,69 +1948,68 @@ wrap_strftime(PyObject *object, PyObject *format, PyObject *timetuple,
...
+        _PyUnicodeWriter_Dealloc(&writer);
+        newformat = Py_NewRef(format);
+    }
+    else {
+        if (_PyUnicodeWriter_WriteSubstring(&writer, format, start, flen) < 0) {
+            goto Done;
         }
+        newformat = _PyUnicodeWriter_Finish(&writer);
     }
+    if (newformat != NULL) {
```
Comment (vstinner) [inline Modules/_datetimemodule.c]: I would prefer to exit early: `if (newformat == NULL) goto ...`.

By the way, only the `_PyUnicodeWriter_Finish()` code path can fail, no?

File: Modules/_datetimemodule.c [hunk 3]
```diff
@@ -1990,69 +1948,68 @@ wrap_strftime(PyObject *object, PyObject *format, PyObject *timetuple,
                     goto Done;
                 }
             }
-            ntoappend = PyOS_snprintf(buf, sizeof(buf),
+            /* Buffer of maximum size of formatted year permitted by long.
+             * +6 to accommodate dashes, 2-digit month and day for %F. */
+            char buf[SIZEOF_LONG * 5 / 2 + 2 + 6];
```
Comment (vstinner) [inline Modules/_datetimemodule.c:1953]: Does it include the NUL trailing character? Maybe add "+1".

File: Modules/_datetimemodule.c [hunk 4]
```diff
@@ -1947,10 +1908,7 @@ wrap_strftime(PyObject *object, PyObject *format, PyObject *timetuple,
...
                     goto Done;
             }
-            assert(freplacement != NULL);
-            assert(PyBytes_Check(freplacement));
-            ptoappend = PyBytes_AS_STRING(freplacement);
-            ntoappend = PyBytes_GET_SIZE(freplacement);
+            replacement = freplacement;
         }
 #ifdef Py_NORMALIZE_CENTURY
         else if (ch == 'Y' || ch == 'G'
```
Comment (vstinner) [inline Modules/_datetimemodule.c:1914]: Do we have existing tests covering %Y, %G, %F and %C?

File: Modules/_datetimemodule.c (hunk 3 above)
Comment (vstinner) [inline Modules/_datetimemodule.c:1953]: It may be interesting to add a test on LONG_MAX year to check for buffer overflow.

File: Modules/timemodule.c [hunk 5]
```diff
@@ -834,101 +824,127 @@ time_strftime(PyObject *module, PyObject *args)
...
-    format = PyUnicode_AsWideCharString(format_arg, NULL);
-    if (format == NULL)
-        return NULL;
-    fmt = format;
-#else
-    /* Convert the unicode string to an ascii one */
-    format = PyUnicode_EncodeLocale(format_arg, "surrogateescape");
-    if (format == NULL)
+    format_size = PyUnicode_GET_LENGTH(format_arg);
+    format = PyMem_Malloc((format_size + 1)*sizeof(time_char));
```
Comment (vstinner) [inline Modules/timemodule.c:915]: I suggest to add an explicit integer overflow check: fail with PyErr_NoMemory() on overflow.

File: Modules/timemodule.c [hunk 6]
```diff
@@ -834,101 +824,127 @@ time_strftime(PyObject *module, PyObject *args)
...
-            /* If the buffer is 256 times as long as the format,
-               it's probably not failing for lack of room!
-               More likely, the format yields an empty result,
-               e.g. an empty format, or %Z when the timezone
-               is unknown. */
+            /* I hate these functions that presume you know how big the output
+             * will be ahead of time...
+             */
+            while (1) {
+                outbuf = (time_char *)PyMem_Realloc(outbuf, bufsize*sizeof(time_char));
```
Comment (vstinner) [inline Modules/timemodule.c]: You may also add an explicit integer overflow check here.

File: Modules/timemodule.c [hunk 7]
```diff
@@ -834,101 +824,127 @@ time_strftime(PyObject *module, PyObject *args)
...
-            PyMem_Free(outbuf);
-            break;
+            if (_PyUnicodeWriter_WriteStr(&writer, unicode) < 0) {
+                Py_DECREF(unicode);
+                goto error;
+            }
+            Py_DECREF(unicode);
+        }
+
+        j = i;
```
Comment (vstinner) [inline Modules/timemodule.c]: You should declare the `j` variable here, and I suggest to rename it to `start`.

File: Modules/timemodule.c [hunk 8]
```diff
@@ -834,101 +824,127 @@ time_strftime(PyObject *module, PyObject *args)
...
+    while (i < format_size) {
+        fmtlen = 0;
+        for (; i < format_size; i++) {
+            Py_UCS4 c = PyUnicode_READ_CHAR(format_arg, i);
+            if (!c || c > 127) {
+                break;
+            }
+            format[fmtlen++] = (char)c;
+        }
+        if (fmtlen) {
```
Comment (vstinner) [inline Modules/timemodule.c:933]: This function is quite big. You might move the code handling `format` in a sub-function (the whole `if` block).

File: Modules/_datetimemodule.c (hunk 4 above)
Comment (serhiy-storchaka) [reply Modules/_datetimemodule.c:1914]: Yes, there were tests when this code was added.

File: Modules/_datetimemodule.c (hunk 3 above)
Comment (serhiy-storchaka) [reply Modules/_datetimemodule.c:1953]: Yes, it includes the minus sign and the trailing NUL. See #120820 for details.

Comment (serhiy-storchaka) [reply Modules/_datetimemodule.c:1953]: Perhaps. But this is not related to this PR.

File: Modules/_datetimemodule.c (hunk 2 above)
Comment (serhiy-storchaka) [reply Modules/_datetimemodule.c]: This would require adding more labels. The flow would look more complicated.

File: Modules/_datetimemodule.c (hunk 1 above)
Comment (serhiy-storchaka) [reply Modules/_datetimemodule.c]: This would require changing more code. Renaming label Done to Error (there are many `goto Done` in not changed code) and adding new Done label. The `if (0)` idiom is weird, but used in many places.

File: Modules/timemodule.c (hunk 8 above)
Comment (serhiy-storchaka) [reply Modules/timemodule.c:933]: This may be inconvenient, because this code changes several outer variables.: `outbuf` and `bufsize`.

**Comment by serhiy-storchaka** [comment]
I addressed all comments. Perhaps it is now more difficult to review.

File: Modules/_datetimemodule.c (hunk 3 above)
Comment (vstinner) [reply Modules/_datetimemodule.c:1953]: Right. I saw later that this code exists before your PR.

File: Modules/timemodule.c [hunk 9]
```diff
@@ -776,27 +776,100 @@ the C library strftime function.\n"
...
+    /* I hate these functions that presume you know how big the output
+     * will be ahead of time...
+     */
+    while (1) {
+        if (*bufsize > PY_SSIZE_T_MAX/sizeof(time_char)) {
+            PyErr_NoMemory();
+            return NULL;
+        }
+        *outbuf = (time_char *)PyMem_Realloc(*outbuf,
+                                                *bufsize*sizeof(time_char));
```
Comment (vstinner) [inline Modules/timemodule.c]:
```suggestion
        *outbuf = (time_char *)PyMem_Realloc(*outbuf,
                                             *bufsize*sizeof(time_char));
```

File: Modules/timemodule.c [hunk 10]
```diff
@@ -776,27 +776,100 @@ the C library strftime function.\n"
 #endif
 
 static PyObject *
-time_strftime(PyObject *module, PyObject *args)
+strftime1(time_char **outbuf, size_t *bufsize,
```
Comment (vstinner) [inline Modules/timemodule.c]: nitpick: you might rename the function to `time_strftime1()` to avoid any conflict with a potential `strftime1()` name from the C library.

**Review by vstinner — APPROVED** [review]
LGTM. I just left minor coding style suggestions that you can ignore.

Thanks for the exhaustive added tests, it's very helpful.

**Comment by serhiy-storchaka** [comment]
Thank you for your review @vstinner.

**Comment by vstinner** [comment]
Congrats! That's a nice change. Using Unicode instead of bytes for the internal buffer is a good move.
