### PR TITLE
gh-93356: Lay out exception handling code at end of code unit 

### LINKED ISSUE #93356: Lay out exception handling code at end of code unit
We would like try-except to run fastest when no exception is raised ('the happy path'). Currently the code is laid out such that in the happy path we need to jump over the except block (see https://github.com/faster-cpython/ideas/issues/226).

We can avoid this jump if we place the except block at the end of the function's bytecode block. To do this, the compiler will detect "cold" basic blocks (those only reachable from exception targets) and reorder the blocks so that the cold blocks are at the end.

Example:

```
def f():
   try:
     x = "try"
   except:
     x = "except"
   finally:
     x = "finally"
     return x
```

Becomes:

```
    1           0 RESUME                   0

  2           2 NOP

  3           4 LOAD_CONST               1 ('try')
              6 STORE_FAST               0 (x)

  7     >>    8 LOAD_CONST               3 ('finally')
             10 STORE_FAST               0 (x)

  8          12 LOAD_FAST                0 (x)
             14 RETURN_VALUE
        >>   16 PUSH_EXC_INFO

  4          18 POP_TOP

  5          20 LOAD_CONST               2 ('except')
             22 STORE_FAST               0 (x)
             24 POP_EXCEPT
             26 JUMP_BACKWARD           10 (to 8)
        >>   28 COPY                     3
             30 POP_EXCEPT
             32 RERAISE                  1
        >>   34 PUSH_EXC_INFO

  7          36 LOAD_CONST               3 ('finally')
             38 STORE_FAST               0 (x)

  8          40 LOAD_FAST                0 (x)
             42 SWAP                     2
             44 POP_TOP
             46 SWAP                     2
             48 POP_EXCEPT
             50 RETURN_VALUE
        >>   52 COPY                     3
             54 POP_EXCEPT
             56 RERAISE                  1
ExceptionTable:
  4 to 6 -> 16 [0]
  16 to 22 -> 28 [1] lasti
  24 to 32 -> 34 [0]
  34 to 46 -> 52 [1] lasti
```

instead of:

```
   1           0 RESUME                   0

  2           2 NOP

  3           4 LOAD_CONST               1 ('try')
              6 STORE_FAST               0 (x)
              8 JUMP_FORWARD             9 (to 28)    <--  this jump was removed
        >>   10 PUSH_EXC_INFO

  4          12 POP_TOP

  5          14 LOAD_CONST               2 ('except')
             16 STORE_FAST               0 (x)
             18 POP_EXCEPT
             20 JUMP_FORWARD             3 (to 28)
        >>   22 COPY                     3
             24 POP_EXCEPT
             26 RERAISE                  1

  7     >>   28 LOAD_CONST               3 ('finally')
             30 STORE_FAST               0 (x)

  8          32 LOAD_FAST                0 (x)
             34 RETURN_VALUE
        >>   36 PUSH_EXC_INFO

  7          38 LOAD_CONST               3 ('finally')
             40 STORE_FAST               0 (x)

  8          42 LOAD_FAST                0 (x)
             44 SWAP                     2
             46 POP_TOP
             48 SWAP                     2
             50 POP_EXCEPT
             52 RETURN_VALUE
        >>   54 COPY                     3
             56 POP_EXCEPT
             58 RERAISE                  1
ExceptionTable:
  4 to 6 -> 10 [0]
  8 to 8 -> 36 [0]
  10 to 16 -> 22 [1] lasti
  18 to 26 -> 36 [0]
  36 to 48 -> 54 [1] lasti
```

### PR DESCRIPTION
**Pull request by iritkatriel**
Closes #93356.

### CODE REVIEW

File: Python/compile.c [hunk 1]
```diff
@@ -9079,7 +9288,7 @@ normalize_basic_block(basicblock *bb) {
 }
 
 static int
-mark_reachable(struct assembler *a) {
+mark_reachable(struct compiler *c, struct assembler *a) {
```
Comment (markshannon) [inline Python/compile.c]: The `compiler *c` parameter seems to be unused.

**Review by markshannon — COMMENTED** [review]
Would it better to add a `warm` parameter to `mark_reachable`?
`mark_warm`, `mark_cold` and `mark_reachable` are all doing the same thing, except for which edges they follow.

**Comment by markshannon** [comment]
Why does fall through from a cold block to a warm block need to be treated specially?

Unless I'm mistaken:
`warm_set = reachable(follow_exception_edges=False)`
`reachable_set = reachable(follow_exception_edges=True)`
`cold_set = reachable_set - warm_set`
Am I missing something?

**Comment by iritkatriel** [comment]
> Why does fall through from a cold block to a warm block need to be treated specially?
> 
> Unless I'm mistaken: `warm_set = reachable(follow_exception_edges=False)` `reachable_set = reachable(follow_exception_edges=True)` `cold_set = reachable_set - warm_set` Am I missing something?

We can't change b->next of a block with a fallthrough.

**Comment by markshannon** [comment]
> We can't change b->next of a block with a fallthrough.

You could convert it to a jump and eliminate the fallthrough edge.

**Comment by iritkatriel** [comment]
> > We can't change b->next of a block with a fallthrough.
> 
> You could convert it to a jump and eliminate the fallthrough edge.

That's the idea. But there could already be a conditional jump there, so if we don't want to have to worry about multiple jumps in the same block for the remaining parts of the assembler, it needs to be a new block.

**Comment by iritkatriel** [comment]
> Would it better to add a `warm` parameter to `mark_reachable`?
> `mark_warm`, `mark_cold` and `mark_reachable` are all doing the same thing, except for which edges they follow.

My first version did mark_cold/warm at the same time as mark_reachable. But I had a situation where the graph changed between that time and the time when I can do the push_cold_to_end. So now mark cold/warm happens just before push_cold_to_end.   I could possibly share the code though.

File: Python/compile.c [hunk 2]
```diff
@@ -7351,6 +7357,132 @@ label_exception_targets(basicblock *entry) {
...
+    if (entry->b_next == NULL) {
+        /* single basicblock, no need to reorder */
+        return 0;
+    }
+    if (mark_cold(entry) < 0) {
+        return -1;
+    }
+
+    /* If we have a cold block with fallthrough to a warm block, add */
+    /* and explicit jump instead of fallthrough */
```
Comment (iritkatriel) [inline Python/compile.c]:
```suggestion
    /* an explicit jump instead of fallthrough */
```

File: Python/compile.c [hunk 3]
```diff
@@ -7351,6 +7357,132 @@ label_exception_targets(basicblock *entry) {
...
+        assert(!b->b_except_predecessors);
+        b->b_warm = 1;
+        basicblock *next = b->b_next;
+        if (next && !b->b_nofallthrough && !next->b_visited) {
+            *sp++ = next;
+        }
+        for (int i=0; i < b->b_iused; i++) {
+            struct instr *instr = &b->b_instr[i];
+            if (is_jump(instr) && !instr->i_target->b_visited) {
+                *sp++ = instr->i_target;
```
Comment (sweeneyde) [inline Python/compile.c:7383]: Could the stack overflow here? I'm worried about a case where lots of different instructions have the same jump target, and so that target gets put onto the stack multiple times. Should `b_visited` instead represent "Have I ever been pushed onto the stack"?

Comment (sweeneyde) [reply Python/compile.c:7383]: Maybe it is safe because each basicblock can have at most one jump instruction. It looks like `mark_reachable` takes this approach as well.

Comment (iritkatriel) [reply Python/compile.c:7383]: That's a good point, I'll change it. Maybe we can use your macros from the other PR as a general pattern at some point.

File: Python/compile.c [hunk 4]
```diff
@@ -7351,6 +7357,136 @@ label_exception_targets(basicblock *entry) {
...
+    }
+    if (mark_cold(entry) < 0) {
+        return -1;
+    }
+
+    /* If we have a cold block with fallthrough to a warm block, add */
+    /* an explicit jump instead of fallthrough */
+    for (basicblock *b = entry; b != NULL; b = b->b_next) {
+        if (b->b_cold && !b->b_nofallthrough && b->b_next && b->b_next->b_warm) {
+            basicblock *explicit_jump = compiler_new_block(c);
```
Comment (sweeneyde) [inline Python/compile.c:7456]: Shouldn't this get a NULL check?

File: Python/compile.c [hunk 5]
```diff
@@ -7351,6 +7357,136 @@ label_exception_targets(basicblock *entry) {
...
+                tail->b_next = next;
+                tail = next;
+            }
+        } else {
+            b = next;
+        }
+        if(next == origtail) {
+            break;
+        }
+    }
```
Comment (sweeneyde) [inline Python/compile.c]: This took me a while to understand, but maybe that's just the nature of linked list code.

My biggest confusion was that meaningful fallthrough `b_next` linkages are broken and then re-established. There could maybe be an inner loop to scan for streaks of cold blocks, so that they can all be moved to the end with an assignment each to `b.b_next, tail.b_next, last_of_streak.b_next`, but I'm not sure if that makes the edge cases easier or harder.

Comment (iritkatriel) [reply Python/compile.c]: I think the new version is easier to follow. Let me know.

**Comment by sweeneyde** [comment]
LGTM. I think the linked list change is clearer now, thanks.

**Comment by iritkatriel** [comment]
Buildbots are happy. 🍾
