### PR TITLE
gh-137706: make typing._is_unpacked_typevartuple check for `True` instead of truthy

### LINKED ISSUE #137706: Annotated with forward references does not partially evaluate
# Bug report

### Bug description:

I ran into this while writing tests for #135228 with additional ways to unintentionally make the old class stick around. 

MRE:

```python
from typing import Annotated
from annotationlib import get_annotations, Format

def f(x: Annotated[undefined, '']): pass

annos = get_annotations(f, format=Format.FORWARDREF)
print(annos['x'])
```

Expected: `typing.Annotated[ForwardRef('undefined', owner=...), '']`
Actual: `ForwardRef("Annotated[undefined, '']", owner=...)`

---

The cause is this:

* `_Stringifier` has a `__getattr__` that will return a new `_Stringifier`
* Annotated checks `_is_unpacked_typevartuple` to determine if it should fail
* `_is_unpacked_typevartuple` checks `getattr(x, "__typing_is_unpacked_typevartuple__", False)`
* This returns a new `_Stringifier` which is truthy
* Annotated raises a TypeError as it thinks the `_Stringifier` is an unpacked typevartuple
* `call_annotate_function` falls back to the all-stringifiers backup mode which makes the whole thing a `ForwardRef`

I think the solution for `Annotated` not partially evaluating is probably to make `typing._is_unpacked_typevartuple` check that the value is `True` rather than truthy.

---

One reason why this might matter - the exception that occurs internally can also prevent other annotations from partially evaluating:

```python
from typing import Annotated
from dataclasses import InitVar, dataclass, fields
from pprint import pp

@dataclass
class PartiallyEvaluates:
    x: InitVar[undefined]

@dataclass
class NoLongerEvaluates:
    x: InitVar[undefined]
    y: Annotated[undefined, '']
```

The addition of the `Annotated` field makes it so `x` is no longer correctly identified as an InitVar here.

[^1]: And how I discovered this initially.

### CPython versions tested on:

3.14, CPython main branch

### Operating systems tested on:

_No response_

### Linked PRs
* gh-137712
* gh-138574

### PR DESCRIPTION
**Pull request by DavidCEllis**
This resolves #137706 making `Annotated[undefined, '']` partially resolvable under `Format.FORWARDREF`

I hope I put the additional test in a reasonable place. It's a large file!

* Issue: gh-137706

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Could you add a NEWS entry?

File: Misc/NEWS.d/next/Library/2025-09-05-21-10-24.gh-issue-137706.0EztiJ.rst [hunk 1]
```diff
@@ -0,0 +1 @@
+Fix the partial evaluation of annotations that use `typing.Annotated[T, x]` where `T` is a forward reference.
```
Comment (JelleZijlstra) [inline Misc/NEWS.d/next/Library/2025-09-05-21-10-24.gh-issue-137706.0EztiJ.rst]:
```suggestion
Fix the partial evaluation of annotations that use ``typing.Annotated[T, x]`` where ``T`` is a forward reference.
```

Comment (DavidCEllis) [reply Misc/NEWS.d/next/Library/2025-09-05-21-10-24.gh-issue-137706.0EztiJ.rst]: Yeah I just saw that failure, thanks.

**Review by JelleZijlstra — APPROVED** [review]
