### PR TITLE
gh-115859: Re-enable T2 optimizer pass by default

### LINKED ISSUE #115859: Type propagation: just because something is const doesn't mean it automatically matches the type
# Bug report

### Bug description:

See log files for failure:

https://github.com/python/cpython/actions/runs/8021737661/job/21914497578

An example failure from my Windows machine:

```
Assertion failed: PyFloat_CheckExact(sym_get_const(left)), file C:\Users\Ken\Documents\GitHub\cpython\Python\tier2_redundancy_eliminator_cases.c.h, line 279
Fatal Python error: Aborted
```

Just because a constant is present, doesn't mean it's the right type. In such a case, I think we should bail from the abstract interpreter, because it's a guaranteed deopt.

E.g.
```C
    op(_GUARD_BOTH_FLOAT, (left, right -- left, right)) {
        if (sym_matches_type(left, &PyFloat_Type) &&
            sym_matches_type(right, &PyFloat_Type)) {
            REPLACE_OP(this_instr, _NOP, 0 ,0);
        }
        sym_set_type(left, &PyFloat_Type);
        sym_set_type(right, &PyFloat_Type);
    }
```
should become
```C
    op(_GUARD_BOTH_FLOAT, (left, right -- left, right)) {
        if (sym_matches_type(left, &PyFloat_Type) &&
            sym_matches_type(right, &PyFloat_Type)) {
            REPLACE_OP(this_instr, _NOP, 0 ,0);
        }
        if (sym_is_const(left)) {
            if (!sym_const_is_type(left, &PyFloat_Type) goto guaranteed_deopt;
        }
        if (sym_is_const(right)) {
            if (!sym_const_is_type(right, &PyFloat_Type) goto guaranteed_deopt;
        }
        sym_set_type(left, &PyFloat_Type);
        sym_set_type(right, &PyFloat_Type);
    }
```
While
```C
    op(_BINARY_OP_ADD_FLOAT, (left, right -- res)) {
        if (sym_is_const(left) && sym_is_const(right)) {
            assert(PyFloat_CheckExact(sym_get_const(left)));
            assert(PyFloat_CheckExact(sym_get_const(right)));
            PyObject *temp = PyFloat_FromDouble(
                PyFloat_AS_DOUBLE(sym_get_const(left)) +
                PyFloat_AS_DOUBLE(sym_get_const(right)));
            ERROR_IF(temp == NULL, error);
            OUT_OF_SPACE_IF_NULL(res = sym_new_const(ctx, temp));
            // TODO gh-115506:
            // replace opcode with constant propagated one and update tests!
        }
        else {
            OUT_OF_SPACE_IF_NULL(res = sym_new_known_type(ctx, &PyFloat_Type));
        }
    }
```
should become
```C
    op(_BINARY_OP_ADD_FLOAT, (left, right -- res)) {
        if (sym_is_const(left) && sym_is_const(right)) {
            if(!PyFloat_CheckExact(sym_get_const(left))) {
                goto guaranteed_deopt;
            }
            if(!PyFloat_CheckExact(sym_get_const(right))) {
                goto guaranteed_deopt;
            }
            PyObject *temp = PyFloat_FromDouble(
                PyFloat_AS_DOUBLE(sym_get_const(left)) +
                PyFloat_AS_DOUBLE(sym_get_const(right)));
            ERROR_IF(temp == NULL, error);
            OUT_OF_SPACE_IF_NULL(res = sym_new_const(ctx, temp));
            // TODO gh-115506:
            // replace opcode with constant propagated one and update tests!
        }
        else {
            OUT_OF_SPACE_IF_NULL(res = sym_new_known_type(ctx, &PyFloat_Type));
        }
    }
```
### CPython versions tested on:

CPython main branch

### Operating systems tested on:

_No response_

### Linked PRs
* gh-115860
* gh-116062
* gh-116079

### PR DESCRIPTION
**Pull request by gvanrossum**
This undoes the *temporary* default disabling of the T2 optimizer pass in gh-115860.

- Add a new test that reproduces Brandt's example from gh-115859; it indeed crashes before gh-116028 with PYTHONUOPSOPTIMIZE=1
- Re-enable the optimizer pass in T2, stop checking PYTHONUOPSOPTIMIZE
- Rename the env var to disable T2 entirely to PYTHON_UOPS_OPTIMIZE (must be explicitly set to 0 to disable)
- Fix skipIf conditions on tests in test_opt.py accordingly
- Export sym_is_bottom() (for debugging)
- Fix various things in the `_BINARY_OP_` specializations in the abstract interpreter:
  - DECREF(temp)
  - out-of-space check after sym_new_const()
  - add sym_matches_type() checks, so even if we somehow reach a binary op with symbolic constants of the wrong type on the stack we won't trigger the type assert

@Fidget-Spinner Please review when you get up. :-)

Fixes gh-115859.

### CODE REVIEW

**Comment by gvanrossum** [comment]
Once tests pass I will try to remember to run the leaks buildbot.

File: Python/optimizer_bytecodes.c [hunk 1]
```diff
@@ -118,14 +121,17 @@ dummy_func(void) {
             OUT_OF_SPACE_IF_NULL(res = sym_new_const(ctx, temp));
```
Comment (Fidget-Spinner) [inline Python/optimizer_bytecodes.c]: Don't you need to decref it here too on this error branch? Or am I remembering the ownership wrongly? Same for everything below.

Might be better to write it as:
```
res = sym_new_const(ctx, temp);
Py_DECREF(temp);
OUT_OF_SPACE_IF_NULL(res);
```

**Review by Fidget-Spinner — COMMENTED** [review]
Just a comment on refcounts, everything else looks good to me.

File: Python/optimizer_bytecodes.c (hunk 1 above)
Comment (gvanrossum) [reply Python/optimizer_bytecodes.c]: Good catch!

**Review by Fidget-Spinner — APPROVED** [review]

**Comment by gvanrossum** [comment]
There seems to be wrong with `test_external_inspection.py` on all the aarch64-unknown-linux CI runs; from one of the error logs:
```
Re-running test_external_inspection in verbose mode (matching: test_remote_stack_trace, test_self_trace)
test_remote_stack_trace (test.test_external_inspection.TestGetStackTrace.test_remote_stack_trace) ... ERROR
test_self_trace (test.test_external_inspection.TestGetStackTrace.test_self_trace) ... ERROR

======================================================================
ERROR: test_remote_stack_trace (test.test_external_inspection.TestGetStackTrace.test_remote_stack_trace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/cpython/cpython/Lib/test/test_external_inspection.py", line 59, in test_remote_stack_trace
    stack_trace = get_stack_trace(p.pid)
                  ~~~~~~~~~~~~~~~^^^^^^^
OSError: [Errno 38] Function not implemented

======================================================================
ERROR: test_self_trace (test.test_external_inspection.TestGetStackTrace.test_self_trace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/cpython/cpython/Lib/test/test_external_inspection.py", line 80, in test_self_trace
    stack_trace = get_stack_trace(os.getpid())
                  ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
OSError: [Errno 38] Function not implemented

----------------------------------------------------------------------
Ran 2 tests in 0.342s

FAILED (errors=2)
test test_external_inspection failed
1 test failed again:
    test_external_inspection
```

**Comment by gvanrossum** [comment]
Argh, test_type_inconsistency fails when run multiple times. Fix coming up.
