### PR TITLE
gh-89546: Clean up PyType_FromMetaclass

### LINKED ISSUE #89546: PyType_FromSpec API fails to use metaclass of bases
BPO | [45383](https://bugs.python.org/issue45383)
--- | :---
Nosy | @encukou, @seberg
PRs | <li>python/cpython#28748</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-10-05.21:51:26.452>
labels = ['interpreter-core', 'expert-C-API', 'type-crash', '3.11']
title = 'PyType_FromSpec API fails to use metaclass of bases'
updated_at = <Date 2021-12-17.17:19:49.187>
user = 'https://github.com/seberg'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-17.17:19:49.187>
actor = 'seberg'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core', 'C API']
creation = <Date 2021-10-05.21:51:26.452>
creator = 'seberg'
dependencies = []
files = []
hgrepos = []
issue_num = 45383
keywords = []
message_count = 9.0
messages = ['403273', '408532', '408720', '408723', '408790', '408791', '408793', '408797', '408801']
nosy_count = 2.0
nosy_names = ['petr.viktorin', 'seberg']
pr_nums = ['28748']
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue45383'
versions = ['Python 3.11']
```

</p></details>

### PR DESCRIPTION
**Pull request by encukou**
When changing PyType_FromMetaclass recently (GH-93012, GH-93466, GH-28748)
I found a bunch of opportunities to improve the code. Here they are.

Fixes: #89546

Automerge-Triggered-By: GH:encukou

### CODE REVIEW

**Comment by erlend-aasland** [comment]
Yes, I'll review it! 🙂

File: Modules/_testcapimodule.c [hunk 1]
```diff
@@ -1245,6 +1245,7 @@ test_from_spec_metatype_inheritance(PyObject *self, PyObject *Py_UNUSED(ignored)
         goto finally;
     }
 
+    MinimalType_spec.basicsize = ((PyTypeObject*)class)->tp_basicsize;
```
Comment (erlend-aasland) [inline Modules/_testcapimodule.c]: Downcast to `int` here, to get rid of the warning.

File: Objects/typeobject.c [hunk 2]
```diff
@@ -3398,15 +3398,64 @@ get_bases_tuple(PyObject *bases_in, PyType_Spec *spec)
     return PyTuple_Pack(1, bases_in);
 }
 
+static inline int
+check_basicsize_includes_size_and_offsets(PyTypeObject* type) {
```
Comment (erlend-aasland) [inline Objects/typeobject.c]: It's the sound of the central PEP 7 scrutinizer... 🎵 🎵 🎵 🪕 

```suggestion
check_basicsize_includes_size_and_offsets(PyTypeObject *type)
{
```

Comment (erlend-aasland) [reply Objects/typeobject.c]: OTOH, this function is hard to bend to PEP 7 without reflowing almost every line...

File: Objects/typeobject.c [hunk 3]
```diff
@@ -3398,15 +3398,64 @@ get_bases_tuple(PyObject *bases_in, PyType_Spec *spec)
...
+    if (type->tp_base && type->tp_base->tp_basicsize > type->tp_basicsize) {
+        PyErr_Format(PyExc_TypeError,
+                    "tp_basicsize for type '%s' (%d) is too small for base '%s' (%d)",
+                    type->tp_name, type->tp_basicsize,
+                    type->tp_base->tp_name, type->tp_base->tp_basicsize);
+        return 0;
+    }
+    if (type->tp_weaklistoffset + (Py_ssize_t)sizeof(PyObject*) > (Py_ssize_t)type->tp_basicsize) {
+        PyErr_Format(PyExc_TypeError,
+                    "tp_basicsize for type '%s' (%d) is too small for weaklist offset %d",
```
Comment (erlend-aasland) [inline Objects/typeobject.c]: I wonder if _"weaklist offset is out of bounds"_ would be better? Ditto for the other offset error messages below.

File: Objects/typeobject.c [hunk 4]
```diff
@@ -3611,14 +3688,26 @@ PyType_FromMetaclass(PyTypeObject *metaclass, PyObject *module,
...
+     * accessible to Python code, like __dict__.
+     */
 
     if (PyType_Ready(type) < 0) {
         goto finally;
     }
 
+    if (!check_basicsize_includes_size_and_offsets(type)) {
+        goto finally;
+    }
```
Comment (erlend-aasland) [inline Objects/typeobject.c:3715]: Better to do this check _before_ we allocate the new type?

File: Objects/typeobject.c [hunk 5]
```diff
@@ -3636,13 +3725,11 @@ PyType_FromMetaclass(PyTypeObject *metaclass, PyObject *module,
     }
 
     if (weaklistoffset) {
-        type->tp_weaklistoffset = weaklistoffset;
         if (PyDict_DelItemString((PyObject *)type->tp_dict, "__weaklistoffset__") < 0) {
```
Comment (erlend-aasland) [inline Objects/typeobject.c]: Out of curiosity; why are we doing this to the dict?

File: Objects/typeobject.c [hunk 6]
```diff
@@ -3398,15 +3398,64 @@ get_bases_tuple(PyObject *bases_in, PyType_Spec *spec)
...
 PyObject *
 PyType_FromMetaclass(PyTypeObject *metaclass, PyObject *module,
                      PyType_Spec *spec, PyObject *bases_in)
 {
+    /* Invariant: A non-NULL value in one of these means this function holds
+     * a strong reference or owns allocated memory.
+     * These get decrefed/freed/returned at the end, on both success and error.
+     */
     PyHeapTypeObject *res = NULL;
     PyObject *modname = NULL;
```
Comment (erlend-aasland) [inline Objects/typeobject.c]: Move `modname` down to where it is used, to improve scoping, while we're at it?

File: Objects/typeobject.c [hunk 7]
```diff
@@ -3398,15 +3398,64 @@ get_bases_tuple(PyObject *bases_in, PyType_Spec *spec)
...
     PyTypeObject *type;
     PyObject *bases = NULL;
+    char *tp_doc = NULL;
+    PyObject *ht_name = NULL;
+    char *_ht_tpname = NULL;
+
     int r;
+    size_t len;
```
Comment (erlend-aasland) [inline Objects/typeobject.c]: The number of local variables is getting rather large for this function. Can we try to keep it down by, for example, moving this down to where it is used? (I know there are two different users, but they've got separate scopes.)

<details>

```diff
diff --git a/Objects/typeobject.c b/Objects/typeobject.c
index 343b690470..1d3aaeb89e 100644
--- a/Objects/typeobject.c
+++ b/Objects/typeobject.c
@@ -3452,3 +3452,2 @@ PyType_FromMetaclass(PyTypeObject *metaclass, PyObject *module,
     int r;
-    size_t len;
 
@@ -3516,3 +3515,3 @@ PyType_FromMetaclass(PyTypeObject *metaclass, PyObject *module,
             else {
-                len = strlen(slot->pfunc)+1;
+                size_t len = strlen(slot->pfunc)+1;
                 tp_doc = PyObject_Malloc(len);
@@ -3663,5 +3662,5 @@ PyType_FromMetaclass(PyTypeObject *metaclass, PyObject *module,
             break;
-        case Py_tp_members:
+        case Py_tp_members: {
             /* Move the slots to the heap type itself */
-            len = Py_TYPE(type)->tp_itemsize * nmembers;
+            size_t len = Py_TYPE(type)->tp_itemsize * nmembers;
             memcpy(_PyHeapType_GET_MEMBERS(res), slot->pfunc, len);
@@ -3669,2 +3668,3 @@ PyType_FromMetaclass(PyTypeObject *metaclass, PyObject *module,
             break;
+        }
         default:
```

</details>

File: Objects/typeobject.c [hunk 8]
```diff
@@ -3444,15 +3499,70 @@ PyType_FromMetaclass(PyTypeObject *metaclass, PyObject *module,
                     vectorcalloffset = memb->offset;
                 }
             }
+            break;
+        case Py_tp_doc:
```
Comment (erlend-aasland) [inline Objects/typeobject.c:3505]: We should consider refactoring out some more helpers; for example this case. Maybe save that for another PR.

**Review by erlend-aasland — COMMENTED** [review]
First round of reviewing done. This is a nice improvement! The added comments are also very helpful.

File: Objects/typeobject.c (hunk 5 above)
Comment (encukou) [reply Objects/typeobject.c]: They're descriptors of the metaclass (`type`), so AFAIK they're not necessary.

File: Objects/typeobject.c (hunk 4 above)
Comment (encukou) [reply Objects/typeobject.c:3715]: Maybe, but here they're all nicely available in the new type object :)

Comment (erlend-aasland) [reply Objects/typeobject.c:3715]: Doh 🤦🏻 😆

File: Objects/typeobject.c (hunk 7 above)
Comment (encukou) [reply Objects/typeobject.c]: I formatted it a bit differently to
- avoid the extra `}` being at the same level as the `switch`'s `}`.
- make it more obvious that the `break` is not missing

File: Objects/typeobject.c [hunk 9]
```diff
@@ -3503,105 +3621,69 @@ PyType_FromMetaclass(PyTypeObject *metaclass, PyObject *module,
...
-                *(void**)((char*)parent_slot + subslot_offset) = slot->pfunc;
+            break;
+        default:
+            {
+                /* Copy other slots directly */
+                PySlot_Offset slotoffsets = pyslot_offsets[slot->slot];
+                short slot_offset = slotoffsets.slot_offset;
+                if (slotoffsets.subslot_offset == -1) {
+                    *(void**)((char*)res_start + slot_offset) = slot->pfunc;
+                } else {
```
Comment (erlend-aasland) [inline Objects/typeobject.c]:
```suggestion
                }
                else {
```

**Review by erlend-aasland — APPROVED** [review]
LGTM! Nice cleanup :)

**Comment by encukou** [comment]
Thank you for the review! It's much better with your suggestions :)

**Comment by erlend-aasland** [comment]
OT: how do you specify the commit message when using autocommit?

**Comment by encukou** [comment]
Miss Islington uses the first comment on the PR.
