### PR TITLE
gh-124452: Fix header mismatches when folding/unfolding with email message

### LINKED ISSUE #124452: Parsing adds whitespace to the front of long headers
# Bug report

### Bug description:

When parsing back a written email, whitespace seems to be prepended to the header if the header was wrapped upon writing.

This is particularly noticeable for message-ids, which end up different - with either a space or a newline prepended depending on what policy is set to (compat32: newline, default: space).

```python
import string

from email import message_from_bytes
from email.message import EmailMessage
import email.policy

orig = EmailMessage()
orig["Message-ID"] = string.ascii_lowercase * 3
policy = email.policy.default  # changing to compat32 emits a different error
parsed = message_from_bytes(orig.as_bytes(policy=policy), policy=policy)
assert (
    parsed["Message-ID"] == orig["Message-ID"]
), f"message ids don't match: '{orig['Message-ID']}' != '{parsed['Message-ID']}'"
```

I'm not very familiar with RFC2822, but based on the [rules it includes for "long" header fields](https://www.rfc-editor.org/rfc/rfc2822#section-2.2.3), the written email bytes look right to me, it's just when it's being read back it's not right.

### CPython versions tested on:

3.9, 3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-125919
* gh-126916
* gh-126917

### PR DESCRIPTION
**Pull request by RanKKI**
Fix: #124452 

* Issue: gh-124452

### CODE REVIEW

File: Misc/NEWS.d/next/Library/2024-10-24-10-49-47.gh-issue-124452.eqTRgx.rst [hunk 1]
```diff
@@ -0,0 +1,3 @@
+Fix the mismatched email headers after converting them to bytes and parsing them into an email message.
+This issue only occurs with long text without any spaces.
+Root cause: The email library doesn't know how to wrap long text without spaces, but it wraps it anyway with a leading WSP, which is not removed when converting bytes to EmailMessage.
```
Comment (ZeroIntensity) [inline Misc/NEWS.d/next/Library/2024-10-24-10-49-47.gh-issue-124452.eqTRgx.rst]: News entries don't need to be all that long, let's keep it short:
```suggestion
Fix the mismatched :mod:`email` headers after converting them to :class:`bytes` and parsing them into an email message.
```

File: Lib/email/policy.py [hunk 2]
```diff
@@ -125,7 +125,14 @@ def header_source_parse(self, sourcelines):
 
         """
         name, value = sourcelines[0].split(':', 1)
-        value = value.lstrip(' \t') + ''.join(sourcelines[1:])
+        no_first_value = value.strip() == '' and len(sourcelines) > 1
```
Comment (picnixz) [inline Lib/email/policy.py]:
```suggestion
        no_first_value = not value.strip() and len(sourcelines) > 1
```

File: Lib/test/test_email/test_message.py [hunk 3]
```diff
@@ -958,6 +958,46 @@ def test_folding_with_utf8_encoding_8(self):
...
+
+    def test_folding_with_long_nospace_default_policy_1(self):
+        # Fixed: https://github.com/python/cpython/issues/124452
+        #
+        # When the value is too long, it should be converted back
+        # to its original form without any modifications.
+
+        m = EmailMessage(policy.default)
+        m['Message-ID'] = '12345678912345678123456789123456789123456789'\
+                        '12345678912345678123456789123456789123456789'
```
Comment (picnixz) [inline Lib/test/test_email/test_message.py]:
```suggestion
		message_id = '123456789' * 10
        m['Message-ID'] = message_id
```

File: Lib/test/test_email/test_message.py [hunk 4]
```diff
@@ -958,6 +958,46 @@ def test_folding_with_utf8_encoding_8(self):
...
+        self.assertEqual(m.as_bytes(),
+                         b'Message-ID:\n 12345678912345678123456789123456'\
+                         b'78912345678912345678912345678123456789123456789'\
+                         b'123456789\n\n')
```
Comment (picnixz) [inline Lib/test/test_email/test_message.py]:
```suggestion
                         f'Message-ID:\n {message_id}\n\n'.encode())
```

File: Lib/test/test_email/test_message.py [hunk 5]
```diff
@@ -958,6 +958,46 @@ def test_folding_with_utf8_encoding_8(self):
...
+        self.assertEqual(parsed_msg['Message-ID'], m['Message-ID'])
+
+    def test_folding_with_long_nospace_compat32_policy_1(self):
+        # Fixed: https://github.com/python/cpython/issues/124452
+        #
+        # When the value is too long, it should be converted back
+        # to its original form without any modifications.
+
+        m = EmailMessage(policy.compat32)
+        m['Message-ID'] = '12345678912345678123456789123456789123456789'\
```
Comment (picnixz) [inline Lib/test/test_email/test_message.py]: Ditto.

File: Lib/test/test_email/test_message.py [hunk 6]
```diff
@@ -958,6 +958,46 @@ def test_folding_with_utf8_encoding_8(self):
...
 
+
+    def test_folding_with_short_nospace_1(self):
+        # bpo-36520
+        #
+        # Fold a line that contains a long whitespace after
+        # the fold point.
+
+        m = EmailMessage(policy.default)
+        m['Message-ID'] = '12345678912345678123456789123456789123456789'
```
Comment (picnixz) [inline Lib/test/test_email/test_message.py]:
```suggestion
        m['Message-ID'] = '123456789' * 3
```

(Note that there was a missing 9 in the sequence).

File: Lib/test/test_email/test_message.py [hunk 7]
```diff
@@ -958,6 +958,46 @@ def test_folding_with_utf8_encoding_8(self):
                          b'123456789-123456789\n 123456789 Hello '
                          b'=?utf-8?q?W=C3=B6rld!?= 123456789 123456789\n\n')
 
+
+    def test_folding_with_short_nospace_1(self):
```
Comment (picnixz) [inline Lib/test/test_email/test_message.py]:
```suggestion
    def test_folding_with_short_nospace_1(self):
```

File: Lib/email/_policybase.py [hunk 8]
```diff
@@ -307,7 +307,29 @@ def header_source_parse(self, sourcelines):
...
+        # Root cause: The function '_refold_parse_tree' in '_header_value_parse.py'.
+        # If there is no WSP, it can't figure out how to wrap the text.
+        # Therefore, it places the entire value directly after '\n', and because
+        # there is a WSP after '<HeaderName>:', the WSP will be moved to the front
+        # of the value according to RFC5322, section 2.2.3.
+        #
+        # However, the WSP is not part of the value; therefore, we must
+        # remove it.
+
+        no_first_value = value.strip() == '' and len(sourcelines) > 1
```
Comment (picnixz) [inline Lib/email/_policybase.py]:
```suggestion
        no_first_value = not value.strip() and len(sourcelines) > 1
```

File: Lib/email/_policybase.py [hunk 9]
```diff
@@ -307,7 +307,29 @@ def header_source_parse(self, sourcelines):
...
+        # Fixed: https://github.com/python/cpython/issues/124452
+        #
+        # Root cause: The function '_refold_parse_tree' in '_header_value_parse.py'.
+        # If there is no WSP, it can't figure out how to wrap the text.
+        # Therefore, it places the entire value directly after '\n', and because
+        # there is a WSP after '<HeaderName>:', the WSP will be moved to the front
+        # of the value according to RFC5322, section 2.2.3.
+        #
+        # However, the WSP is not part of the value; therefore, we must
+        # remove it.
```
Comment (picnixz) [inline Lib/email/_policybase.py]: I would simply keep the reference to the issue without restating the issue itself.

Comment (ZeroIntensity) [reply Lib/email/_policybase.py]: Hmm, it's useful to me when there's a comment explaining at least partially what the issue was. Maybe it could be shortened though.

Comment (bitdancer) [reply Lib/email/_policybase.py]: I would not add any comment, since the fix makes the code better match the intent of the docstring (see below for the docstring revision).

By the way, long explanations like what you wrote should *definitely* be included in the commit message.

File: Lib/email/_policybase.py [hunk 10]
```diff
@@ -307,7 +307,29 @@ def header_source_parse(self, sourcelines):
...
+
+        # When using the compat32 policy, the value is '\n'. Therefore,
+        # use an empty string if there is no value (without WSP and CRLF)
+        # on the first line
+        value = '' if no_first_value else value.lstrip(' \t')
+
+        if no_first_value and sourcelines[1][0] in ' \t':
+            sourcelines[1] = sourcelines[1][1:]
+
+        value += ''.join(sourcelines[1:])
```
Comment (bitdancer) [inline Lib/email/_policybase.py]: A much simpler fix:

```
value = ''.join((value, *sourcelines[1:])).lstrip(' \t\r\n')
```

This makes it match the *intent* of the docstring, which should be rewritten as "The value is determined by stripping the leading whitespace off the remainder of the first line joined with the all subsequent lines..."

File: Lib/test/test_email/test_message.py [hunk 11]
```diff
@@ -958,6 +958,46 @@ def test_folding_with_utf8_encoding_8(self):
...
+        #
+        # Fold a line that contains a long whitespace after
+        # the fold point.
+
+        m = EmailMessage(policy.default)
+        m['Message-ID'] = '12345678912345678123456789123456789123456789'
+        parsed_msg = message_from_bytes(m.as_bytes(), policy=policy.default)
+        self.assertEqual(parsed_msg['Message-ID'], m['Message-ID'])
+
+    def test_folding_with_long_nospace_default_policy_1(self):
```
Comment (bitdancer) [inline Lib/test/test_email/test_message.py:972]: It would be good to test with the SMTP policy, too, because that uses `\r\n`, and I almost forgot the '\r' when I was proposing the simpler fix.

File: Misc/NEWS.d/next/Library/2024-10-24-10-49-47.gh-issue-124452.eqTRgx.rst (hunk 1 above)
Comment (bitdancer) [reply Misc/NEWS.d/next/Library/2024-10-24-10-49-47.gh-issue-124452.eqTRgx.rst]: The actual bug is that the parser was not stripping all of the whitespace from the front of the value.  This but has nothing to do with wrapping, and would have manifested on parsing any message that had a header that started with a newline.  Such messages are rarely if ever encountered in the wild, though, so the (separate) folding bug is what caused this bug to manifest.

All of which is to say I would make the news item something like "Fix email parsing bug that introduced spurious leading whitespace into header values when the header includes a newline character after the ';' and before the value.

**Review by bitdancer — CHANGES_REQUESTED** [review]

File: Lib/email/_policybase.py (hunk 10 above)
Comment (RanKKI) [reply Lib/email/_policybase.py]: yeahhh, it's much easier. was trying to trim the ' \t' only.

**Comment by RanKKI** [comment]
I have made the requested changes; please review again

File: Misc/NEWS.d/next/Library/2024-10-24-10-49-47.gh-issue-124452.eqTRgx.rst [hunk 12]
```diff
@@ -0,0 +1 @@
+Fix email parsing bug that introduced spurious leading whitespace into header values when the header includes a newline character after the ';' and before the value.
```
Comment (rruuaanng) [inline Misc/NEWS.d/next/Library/2024-10-24-10-49-47.gh-issue-124452.eqTRgx.rst]: Maybe you should used rst label.
```
:mod:`email`
```
For more to see https://devguide.python.org/documentation/markup/

Comment (RanKKI) [reply Misc/NEWS.d/next/Library/2024-10-24-10-49-47.gh-issue-124452.eqTRgx.rst]: true, I'll have look at this doc

**Comment by rruuaanng** [comment]
Please specify the method. It seems that you haven't read this link carefully ：）

File: Lib/email/_policybase.py [hunk 13]
```diff
@@ -307,7 +307,7 @@ def header_source_parse(self, sourcelines):
```
Comment (bitdancer) [inline Lib/email/_policybase.py:307]: s/remainder of the first line, joining all subsequent lines together/remainder of the first line joined with all subsequent lines/

File: Lib/email/policy.py [hunk 14]
```diff
@@ -125,7 +125,7 @@ def header_source_parse(self, sourcelines):
```
Comment (bitdancer) [inline Lib/email/policy.py:125]: ditto

File: Lib/test/test_email/test_message.py [hunk 15]
```diff
@@ -958,6 +958,52 @@ def test_folding_with_utf8_encoding_8(self):
...
                          b'=?utf-8?q?W=C3=B6rld!?= 123456789 123456789\n\n')
 
+    def test_folding_with_short_nospace_1(self):
+        # bpo-36520
+        #
+        # Fold a line that contains a long whitespace after
+        # the fold point.
+
+        m = EmailMessage(policy.default)
+        m['Message-ID'] = '123456789'*3
```
Comment (picnixz) [inline Lib/test/test_email/test_message.py]:
```suggestion
        m['Message-ID'] = '123456789' * 3
```

File: Misc/NEWS.d/next/Library/2024-10-24-10-49-47.gh-issue-124452.eqTRgx.rst [hunk 16]
```diff
@@ -0,0 +1 @@
+Fix :mod:`email` parsing bug that introduced spurious leading whitespace into header values when the header includes a newline character after the ';' and before the value.
```
Comment (picnixz) [inline Misc/NEWS.d/next/Library/2024-10-24-10-49-47.gh-issue-124452.eqTRgx.rst]:
```suggestion
Fix an issue in :meth:`email.policy.EmailPolicy.header_source_parse` and
:meth:`email.policy.Compat32.header_source_parse` that introduced spurious
leading whitespaces into header values when the header includes a newline
character after the header name delimiter (`:`) and before the value.
```

Let's try to render it a bit better and say which methods were fixed.

**Review by bitdancer — APPROVED** [review]

**Comment by bitdancer** [comment]
Thanks, RanKII.  Sorry, I missed the update notification, and I only just checked back on the PR.
