### PR TITLE
bpo-40334: Always show the caret on SyntaxErrors

### LINKED ISSUE #126: Implementation of RAISE_SYNTAX_ERROR_NO_COL_OFFSET seems incorrect
From https://github.com/python/cpython/pull/20020#issuecomment-626257240, it seems that the way `RAISE_SYNTAX_ERROR_NO_COL_OFFSET` works in not correct as is always assigning the caret to the beginning of the line instead of where the error should be.

### PR DESCRIPTION
**Pull request by lysnikolaou**
This PR fixes SyntaxError locations, when the caret is not displayed,
by doing the following:
- `col_number` always gets set to the location of the offending
  node/expr. 
- Introduce a new function `_PyPegen_raise_error_known_location`,
  which can be called, when an arbitrary `lineno`/`col_offset`
  needs to be passed. This function then gets used in the grammar
  (through some new macros and inline functions) so that SyntaxError
  locations of the new parser match that of the old.

Closes we-like-parsers/cpython#126.

https://bugs.python.org/issue40334

### CODE REVIEW

File: Parser/pegen/pegen.c [hunk 1]
```diff
@@ -383,48 +383,61 @@ tokenizer_error(Parser *p)
...
 
     if (p->start_rule == Py_file_input) {
-        loc = PyErr_ProgramTextObject(p->tok->filename, t->lineno);
+        error_line = PyErr_ProgramTextObject(p->tok->filename, lineno);
     }
 
-    if (!loc) {
-        loc = get_error_line(p->tok->buf, p->start_rule == Py_file_input);
+    if (!error_line) {
+        error_line = get_error_line(p->tok->buf, p->start_rule == Py_file_input);
```
Comment (gvanrossum) [inline Parser/pegen/pegen.c:428]: There should be a NULL check here. When `get_error_line()` returns NULL, it means creating a Unicode object failed. (But there shouldn't be a NULL check on the `PyErr_ProgramTextObject()` call above -- it carefully clears error state, and NULL just means it couldn't find the line, which is apparently not an error.)

File: Parser/pegen/pegen.c [hunk 2]
```diff
@@ -383,48 +383,61 @@ tokenizer_error(Parser *p)
...
-                                          intptr_t, int);
-        } else {
-            col_offset = t->col_offset + 1;
-        }
-        col_number = byte_offset_to_character_offset(loc, col_offset);
-    }
-    else if (!loc) {
+    int col_number = byte_offset_to_character_offset(error_line, col_offset);
+
+    if (!error_line || (!with_col_number && p->start_rule != Py_file_input)) {
```
Comment (gvanrossum) [inline Parser/pegen/pegen.c]: So, I believe that `error_line` is never NULL here, so the first test (`!error_line`) seems redundant.

File: Parser/pegen/pegen.c [hunk 3]
```diff
@@ -383,48 +383,61 @@ tokenizer_error(Parser *p)
...
         Py_INCREF(Py_None);
-        loc = Py_None;
+        error_line = Py_None;
```
Comment (gvanrossum) [inline Parser/pegen/pegen.c]: I think this leaks a reference to `error_line` by overwriting it. If you check for `with_col_number` earlier you could avoid creating the initial `error_line` in the first place.

File: Parser/pegen/pegen.c [hunk 4]
```diff
@@ -383,48 +383,61 @@ tokenizer_error(Parser *p)
...
     }
 
-    tmp = Py_BuildValue("(OiiN)", p->tok->filename, t->lineno, col_number, loc);
+    tmp = Py_BuildValue("(OiiN)", p->tok->filename, lineno, col_number, error_line);
```
Comment (gvanrossum) [inline Parser/pegen/pegen.c:436]: Honestly I think it's perverse to set `error_line` to None in order to prevent the caret, since this not only prevents showing the caret but also prevents showing the text of the line in error at all. But you have the line number, so you should show the text of the line.

What I would expect is creating a tuple `(filename, lineno, None, error_line)` where `error_line` is the text of the line. (This is what I have been hinting at previously.)

File: Parser/pegen/pegen.h [hunk 5]
```diff
@@ -128,14 +128,33 @@ expr_ty _PyPegen_number_token(Parser *p);
 void *_PyPegen_string_token(Parser *p);
 const char *_PyPegen_get_expr_name(expr_ty);
 void *_PyPegen_raise_error(Parser *p, PyObject *errtype, int with_col_number, const char *errmsg, ...);
+void *_PyPegen_raise_error_known_location(Parser *p, PyObject *errtype,
+                                   int with_col_number,
+                                   int lineno, int col_offset,
```
Comment (gvanrossum) [inline Parser/pegen/pegen.h]: Can't we change the interface to remove the silly `with_col_number` flag and set `col_offset` to -1 instead? (You still would have to check for it and replace it with None, but it makes the call a bit less unwieldy.)

File: Parser/pegen/pegen.c (hunk 4 above)
Comment (lysnikolaou) [reply Parser/pegen/pegen.c:436]: > since this not only prevents showing the caret but also prevents showing the text of the line in error at all. But you have the line number, so you should show the text of the line.

The old parser behaves that way. For example:
```
╰─ python3.8                                                     
Python 3.8.1+ (heads/3.8:33e033da3c, Jan 10 2020, 01:13:05) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 1 + 1 = 2
  File "<stdin>", line 1
SyntaxError: cannot assign to operator
```
It show no carret and no text.

By looking at the code, this indeed seems to be the intention of `Python/ast.c`.
https://github.com/python/cpython/blob/cd8295ff758891f21084a6a5ad3403d35dda38f7/Python/ast.c#L643
If it were up to me, I'd completely change that behavior in the new parser and _always_  show both the caret and the error text. Would that be okay, you think?

Comment (gvanrossum) [reply Parser/pegen/pegen.c:436]: That's different. (And the variable name `loc` doesn't help.) It replaces NULL with None if `PyErr_ProgramTextObject()` couldn't find the line, and with the old parser that is always the case with REPL input. (It has to do with reading the source file a second time to get the text.)

If you put this in a file the caret points to the start of the bad statement:
```
if 1: 1+1 = 1
```
Now the old parser gives:
```
~/cpython$ ./python.exe -X oldparser t.py
  File "/Users/guido/cpython/t.py", line 1
    if 1: 1+1 = 1
          ^
SyntaxError: cannot assign to operator
~/cpython$ 
```
Please read the rest of my comments carefully.

**Comment by gvanrossum** [comment]
Another idea: why do we have RAISE_SYNTAX_ERROR_NO_COL_OFFSET at all? I see only one call. Maybe we can just display the caret there?

**Comment by lysnikolaou** [comment]
> Another idea: why do we have RAISE_SYNTAX_ERROR_NO_COL_OFFSET at all? I see only one call. Maybe we can just display the caret there?

Agreed. I think we can just go ahead and always display the caret. Working on that.

**Comment by lysnikolaou** [comment]
Just pushed a new version, after which the caret is always shown, even in cases where the old parser wouldn't show it. For example:

```
╰─ ./python.exe -X oldparser
Python 3.9.0a6+ (heads/syntaxerror-col-offset-dirty:60b761a495, May 13 2020, 02:22:06)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 1 = 2
  File "<stdin>", line 1
SyntaxError: cannot assign to literal

╰─ ./python.exe
Python 3.9.0a6+ (heads/syntaxerror-col-offset-dirty:60b761a495, May 13 2020, 02:22:06)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 1 = 2
  File "<stdin>", line 1
    1 = 2
    ^
SyntaxError: cannot assign to literal
```

**Review by gvanrossum — APPROVED** [review]
That's more like it!

**Comment by lysnikolaou** [comment]
Thanks for the help!

**Review by pablogsal — APPROVED** [review]
LGTM

**Comment by hauntsaninja** [comment]
Yay, thank you for this!
