### PR TITLE
gh-120834: fix type of *_iframe field in _PyGenObject_HEAD declaration

### LINKED ISSUE #120834: generator frame type should not be PyObject*[]
For historical reasons, the `*_iframe` field in `_PyGenObject_HEAD` is declared as ` PyObject*[]`, and later cast to `_PyInterpreterFrame *` (which is not a PyObject*). 

### Linked PRs
* gh-120835
* gh-120941
* gh-120976

### PR DESCRIPTION
**Pull request by iritkatriel**
Fixes #120834 .

* Issue: gh-120834

### CODE REVIEW

File: Include/cpython/genobject.h [hunk 1]
```diff
@@ -26,7 +28,7 @@ extern "C" {
     char prefix##_running_async;                                            \
     /* The frame */                                                         \
     int8_t prefix##_frame_state;                                            \
-    PyObject *prefix##_iframe[1];                                           \
+    struct _PyInterpreterFrame *prefix##_iframe[1];                         \
```
Comment (iritkatriel) [inline Include/cpython/genobject.h]: I tried to remove the [1] but then it crashes during the build. Not sure why.

**Review by mdboom — APPROVED** [review]
LGTM

File: Include/cpython/genobject.h (hunk 1 above)
Comment (markshannon) [reply Include/cpython/genobject.h]:
```suggestion
    struct _PyInterpreterFrame prefix##_iframe;                         \
```
It's not a pointer to a frame, it is a frame.

File: Objects/genobject.c [hunk 2]
```diff
@@ -163,7 +162,7 @@ gen_send_ex2(PyGenObject *gen, PyObject *arg, PyObject **presult,
              int exc, int closing)
 {
     PyThreadState *tstate = _PyThreadState_GET();
-    _PyInterpreterFrame *frame = (_PyInterpreterFrame *)gen->gi_iframe;
+    _PyInterpreterFrame *frame = gen->gi_iframe;
```
Comment (markshannon) [inline Objects/genobject.c]:
```suggestion
    _PyInterpreterFrame *frame = &gen->gi_iframe;
```

File: Objects/genobject.c [hunk 3]
```diff
@@ -48,7 +47,7 @@ gen_traverse(PyGenObject *gen, visitproc visit, void *arg)
     Py_VISIT(gen->gi_name);
     Py_VISIT(gen->gi_qualname);
     if (gen->gi_frame_state != FRAME_CLEARED) {
-        _PyInterpreterFrame *frame = (_PyInterpreterFrame *)(gen->gi_iframe);
+        _PyInterpreterFrame *frame = gen->gi_iframe;
```
Comment (markshannon) [inline Objects/genobject.c]:
```suggestion
        _PyInterpreterFrame *frame = &gen->gi_iframe;
```

File: Objects/genobject.c [hunk 4]
```diff
@@ -141,7 +140,7 @@ gen_dealloc(PyGenObject *gen)
         Py_CLEAR(((PyAsyncGenObject*)gen)->ag_origin_or_finalizer);
     }
     if (gen->gi_frame_state != FRAME_CLEARED) {
-        _PyInterpreterFrame *frame = (_PyInterpreterFrame *)gen->gi_iframe;
+        _PyInterpreterFrame *frame = gen->gi_iframe;
```
Comment (markshannon) [inline Objects/genobject.c]:
```suggestion
        _PyInterpreterFrame *frame = &gen->gi_iframe;
```

File: Objects/genobject.c [hunk 5]
```diff
@@ -342,7 +341,7 @@ PyObject *
 _PyGen_yf(PyGenObject *gen)
 {
     if (gen->gi_frame_state == FRAME_SUSPENDED_YIELD_FROM) {
-        _PyInterpreterFrame *frame = (_PyInterpreterFrame *)gen->gi_iframe;
+        _PyInterpreterFrame *frame = gen->gi_iframe;
```
Comment (markshannon) [inline Objects/genobject.c]:
```suggestion
        _PyInterpreterFrame *frame = &gen->gi_iframe;
```

**Review by markshannon — CHANGES_REQUESTED** [review]
To do this we'll need to either:
Move `_PyInterpreterFrame` to a public header
Move `_PyGenObject_HEAD` to a private header.

If you can avoid breaking the API, the second option is preferable.

File: Include/cpython/genobject.h (hunk 1 above)
Comment (mdboom) [reply Include/cpython/genobject.h]: That's pretty subtle, so it's nice to see this being made more explicit by this PR.

Given that, maybe the object size calculation could be simplified to not need the explicit addition (not tested or 100% sure on that, though): https://github.com/python/cpython/blob/main/Objects/genobject.c#L818

**Comment by iritkatriel** [comment]
> To do this we'll need to either: Move `_PyInterpreterFrame` to a public header Move `_PyGenObject_HEAD` to a private header.
> 
> If you can avoid breaking the API, the second option is preferable.

`PyGenObject` is API, so I don't think the second option is possible.

**Comment by markshannon** [comment]
Is the actual structure of `PyGenObject` part of the API, or just its existence.
All the API functions take `PyGenObject *`, so we can move the structure definition to an internal header and leave 
```typedef struct _PyGenObject PyGenObject;``` in the public header.

File: Include/internal/pycore_genobject.h [hunk 6]
```diff
@@ -8,7 +8,49 @@ extern "C" {
...
+};
+
+struct _PyAsyncGenObject {
+    _PyGenObject_HEAD(ag)
+};
+
+#undef _PyGenObject_HEAD
+
+static inline
+PyGenObject *_PyGen_GetGeneratorFromFrame(_PyInterpreterFrame *frame)
```
Comment (iritkatriel) [inline Include/internal/pycore_genobject.h:48]: I needed to move this here to avoid circular dependencies.

**Comment by iritkatriel** [comment]
I have made the requested changes; please review again.

**Review by markshannon — APPROVED** [review]
Nice, this will definitely make things more maintainable.

It would be good to get rid of the `_PyGenObject_HEAD` macro, but that's for another PR.

File: Include/cpython/genobject.h (hunk 1 above)
Comment (iritkatriel) [reply Include/cpython/genobject.h]: > Given that, maybe the object size calculation could be simplified to not need the explicit addition (not tested or 100% sure on that, though): https://github.com/python/cpython/blob/main/Objects/genobject.c#L818

That seems to work.

**Comment by iritkatriel** [comment]
> It would be good to get rid of the `_PyGenObject_HEAD` macro, but that's for another PR.

Do you know the history, why we have three structs with the same structure but different names?

**Comment by markshannon** [comment]
> > It would be good to get rid of the `_PyGenObject_HEAD` macro, but that's for another PR.
> 
> Do you know the history, why we have three structs with the same structure but different names?

Probably to avoid copy and pasting the struct for the coroutine classes and keep `PyGenObject` unchanged.

File: Objects/genobject.c [hunk 7]
```diff
@@ -814,8 +813,7 @@ static PyAsyncMethods gen_as_async = {
 PyTypeObject PyGen_Type = {
     PyVarObject_HEAD_INIT(&PyType_Type, 0)
     "generator",                                /* tp_name */
-    offsetof(PyGenObject, gi_iframe) +
-    offsetof(_PyInterpreterFrame, localsplus),       /* tp_basicsize */
+    sizeof(PyGenObject),                        /* tp_basicsize */
```
Comment (markshannon) [inline Objects/genobject.c:816]: I think this should be `offsetof(PyGenObject, gi_frame.localsplus)` otherwise we are overallocating one `PyObject *` slot.

Likewise for `PyCoroObject` and `PyAsyncGenObject`

**Comment by iritkatriel** [comment]
> Probably to avoid copy and pasting the struct for the coroutine classes and keep `PyGenObject` unchanged.

But PyGenObject , PyCoroObject and PyAsyncGenObject are the same thing. Why don't we have just one type for all of them?

File: Objects/genobject.c (hunk 7 above)
Comment (iritkatriel) [reply Objects/genobject.c:816]: Let's try that: https://github.com/python/cpython/pull/120941

**Comment by markshannon** [comment]
They haven't always been the same https://github.com/python/cpython/commit/299483c95d601ddcfdce2f96418b6499c1fc7b9f
