### PR TITLE
gh-97933: inline list/dict/set comprehensions

### LINKED ISSUE #97933: Inline dict/list/set comprehensions in the compiler for better performance
# Feature or enhancement

In [Cinder](https://github.com/facebookincubator/cinder) we inline some list/dict/set comprehensions in the compiler for better performance. That is, instead of creating a function object every time and calling it, for some comprehensions we just emit bytecode directly in the outer function to implement the comprehension loop.

# Pitch

This change was a significant CPU efficiency improvement on the Instagram production web tier. Allocating a new Python function object is a significant and not strictly necessary cost.

There are some backward-compatibility considerations. In the Cinder implementation, we refuse to inline comprehensions if there is a name collision between a name assigned within the comprehension and a name in the containing scope, and we delete any names defined in the comprehension immediately after the inlined bytecode, to preserve the same visibility of names defined in the comprehension. There can still be some visible changes, e.g. if `locals()` is called within the comprehension it will show names from the containing function too. If a traceback occurs within the comprehension (or `sys._getframe` is called), it will not show an additional last frame for the comprehension itself. In practice we've not observed either of these to be a problem.

I discussed this idea with @markshannon, and he suggested a couple possible improvements. Instead of refusing to inline comprehensions with name clashes, we could push the prior value of the colliding name(s) onto the stack before running the comprehension, and then pop it back into the name afterward. This would allow inlining ~all comprehensions. He also suggested that we could add `PUSH_FRAME` and `POP_FRAME` opcodes and wrap the inlined bytecode in these. Then we would still elide the cost of function object creation, but the comprehension bytecode (although part of the parent bytecode) would still run inside its own frame, eliminating the above-mentioned incompatibilities.

### Linked PRs
* gh-101310
* gh-101441
* gh-105126
* gh-105142

### PR DESCRIPTION
**Pull request by carljm**
Closes #97933.

In builds with `--enable-optimizations`:

```
➜ ./python -m pyperf timeit -s 'l = [1, 2, 3, 4, 5]' '[x for x in l]' --compare-to ../mainopt/python
/home/carljm/build/mainopt/python: ..................... 200 ns +- 3 ns
/home/carljm/build/ic2opt/python: ..................... 120 ns +- 2 ns

Mean +- std dev: [/home/carljm/build/mainopt/python] 200 ns +- 3 ns -> [/home/carljm/build/ic2opt/python] 120 ns +- 2 ns: 1.67x faster
```

Credit to @vladima for authoring the [original version](https://github.com/facebookincubator/cinder/commit/03040db7ec8d2a8439c8727925627844c49d7c14) of this code in Cinder 3.8. The compiler approach is different in this version (so as to support inlining all comprehensions, regardless of name clashes); some of the symbol table changes remain the same.

A couple implementation notes:
* We need a new opcode `LOAD_FAST_AND_CLEAR` because we need to push/pop the value of possibly-undefined variables on the stack while clearing them. To do this with existing opcodes would require eliminating the invariant/assert that `LOAD_FAST` never loads `NULL`, and would add inefficient refcount operations and interpreter loop cycles.
* If a comprehension iteration variable is a cell inside the comprehension (i.e. the comprehension builds closures) we end up including that variable in both `co_varnames` and `co_cellvars` for the inlined-into outer function and using the non-offset (varnames) storage location for it. This is how function arguments that are also cells are currently handled, so we just piggyback on that handling. This makes the needed push/pop of the outer cell simpler as we can just use `LOAD_FAST_AND_CLEAR/STORE_FAST` as-is for it, and it will push/pop the cell itself. Otherwise we would need some new handling in the compiler for allowing push/pop of a cell in offset storage.

This PR also adds a lot of new tests for comprehension scoping edge cases, and runs all new and existing scoping
tests in module, function, and class scopes (without requiring duplication of the test code.) All comprehension
scoping tests added in this diff also pass with comprehension inlining disabled (ensuring semantics did not change.)

* Issue: gh-97933

### CODE REVIEW

**Comment by carljm** [comment]
@markshannon @iritkatriel would be grateful for a pyperformance run on this one (presuming signal all looks good.)

**Comment by markshannon** [comment]
I'll run the benchmarks now

**Comment by markshannon** [comment]
Benchmarking  is delayed a bit, but should be back tomorrow at the latest.

**Comment by markshannon** [comment]
You don't seem to be clearing the inner variable before use, so that
```Python
def f():
    l = [ None ]
    [ (l[0], l) in [[1,2]] ]
    print(l)
```
will, I think, print `[1]` instead of raising an UnboundLocalError

You can actually make the code more efficient by clearing the local when stashing it on the stack:
```C
inst(LOAD_FAST_AND_CLEAR, ( -- val)) {
    val = LOCALS[oparg];
    LOCALS[oparg] = NULL;
}
as there is no need for a `NULL` check or `INCREF`.

File: Python/compile.c [hunk 1]
```diff
@@ -5375,26 +5383,148 @@ compiler_async_comprehension_generator(struct compiler *c, location loc,
...
+        for (Py_ssize_t i = PyList_GET_SIZE(state.pushed_locals); i > 0; --i) {
+            k = PyList_GetItem(state.pushed_locals, i - 1);
+            if (k == NULL) {
+                return ERROR;
+            }
+            // preserve the list/dict/set result of the comprehension as TOS; we
+            // could be cleverer about minimizing swaps but it doesn't matter
+            // because `apply_static_swaps` will eliminate all of these anyway
+            ADDOP_I(c, loc, SWAP, 2);
+            ADDOP_NAME(c, loc, STORE_FAST, k, varnames);
```
Comment (markshannon) [inline Python/compile.c]: We could be storing `NULL` here. That is OK for the interpreter, but the dataflow analysis in `add_checks_for_loads_of_uninitialized_variables` in the compiler assumes that `STORE_FAST` leaves the variable initialized.

What you'll need to do is add a pseudo instruction, and convert that to `STORE_FAST` in the assembler. That way the dataflow analysis won't be fooled.

You might want to update `add_checks_for_loads_of_uninitialized_variables` to understand the `LOAD_FAST_AND_CLEAR`, `STORE_FAST_MAYBE_NULL` pairs, but that should wait for another PR.

Comment (markshannon) [reply Python/compile.c]: Here is a test case:
```Python
def f():
     if False:
          x = 0
     [x for _ in [1]]
     return x
```

**Comment by markshannon** [comment]
A couple of obscure issues, but this looks like a very nice improvement.

I think the cost in code size is well worth the gain in performance, given how common comprehensions are.

**Comment by carljm** [comment]
> You don't seem to be clearing the inner variable before use

Your example code doesn't compile, I'm assuming you meant something like

```
def f():
    l = [ None ]
    [ (l[0], l) for l in [[1,2]] ]
    print(l)
```

But this doesn't raise `UnboundLocalError` on main either, it works fine; the iteration variable `l` is always bound within the comprehension before the expression is evaluated.

So far I haven't been able to construct a test case where failing to clear an incoming variable bound inside the comprehension has any visible effect, because AFAICT any locals in a comprehension are always (necessarily by the syntactic limitations of how a comprehension is built) defined before use. Let me know if you can think of a test case I'm missing!

> You can actually make the code more efficient by clearing the local when stashing it on the stack

But I think this is sufficient reason regardless to justify switching from `LOAD_FAST_OR_NULL` to `LOAD_FAST_AND_CLEAR`, so I'll do that!

**Comment by carljm** [comment]
Actually I don't think `LOAD_FAST_AND_CLEAR` will work, because of cases like this:

```
def f(x):
    return [x for x in x]
```

We need to save/restore the outer value of `x`, but we cannot clear it on entry because we are also relying on being able to load it when we evaluate the iterable part of the comprehension (which in the non-inlined case would have been evaluated outside the function and passed in as the `.0` parameter.) So I think we need to stick with a non-clearing `LOAD_FAST_OR_NULL` on entry.

If there were a correctness reason for needing to clear in other cases, I could add an additional `DELETE_FAST` after the `LOAD_FAST_OR_NULL`, but so far I haven't found any such correctness need, and clearing this way is not an efficiency improvement.

**Comment by carljm** [comment]
@markshannon I think `LOAD_FAST_OR_NULL` could also become a pseudo-instruction that resolves to `LOAD_FAST` (which would get around having it turned into `LOAD_FAST_CHECK`), but we'd have to remove the `assert(value != NULL)` in the `LOAD_FAST` implementation. Do you prefer keeping that assertion at the cost of another (non-pseudo) opcode?

File: Python/compile.c (hunk 1 above)
Comment (carljm) [reply Python/compile.c]: Good call, thanks!

The test case needs to use `[x for x in [1]]`, not `[x for _ in [1]]` -- in the latter case, `x` is not bound in the comprehension and is just a free var (converted to local by inlining) so we don't push/pop it at all.

**Comment by carljm** [comment]
I've addressed the review comments. I have some TODOs for potential optimizations that could be done here or in a follow-up diff:

* Eliminate some unnecessary push/pops in cases where the value is never loaded after the comprehension. This would fall into the general category of dead store elimination. I'm not sure if we can actually do this or if it violates some guarantees about introspectable frame state in tracing?
* Better handling of SWAPs on the post-comprehension pops. `apply_static_swaps` can't help us here if the comprehension value is immediately returned (because we can't "swap" a `RETURN_VALUE` -- this case would go away if we can do the dead store elimination, since if it's right before a `RETURN_VALUE` it's clearly a dead store) or if it's immediately popped (because the `POP_TOP` will have a lineno of `-1` and `apply_static_swaps` will thus refuse to swap it). Instead of having one `SWAP 2` per N pops, we could have a single `SWAP N` and do the last pop first.
* Teach `add_checks_for_loads_of_uninitialized_variables` to understand and trace through the push/pop pairs.

**Comment by markshannon** [comment]
Sorry for posting a gibberish example.
Here's what I should have posted:
```Py
def f():
    l = [ None ]
    [ 1 for (l[0], l) in [[1,2]] ]
    print(l)
f()
```
#### 3.11
```
$ python3.11 ~/test/test.py 
Traceback (most recent call last):
   ...
UnboundLocalError: cannot access local variable 'l' where it is not associated with a value
```
#### This PR
```
$ ./python ~/test/test.py 
[1]
````

**Comment by markshannon** [comment]
> Actually I don't think LOAD_FAST_AND_CLEAR will work, because of cases like this:
```py
def f(x):
    return [x for x in x]
```

This shouldn't be a problem. Let's rename for clarity:
```py
def f(x0):
    return [x1 for x1 in x0]
```
The expression `x0` should be fully evaluated before `x1` exists.

This PR stashes the variable `x0` before evaluating the expression `x0`, which seems wrong to me.
```
>>> dis.dis(f)
  1           0 RESUME                   0

  2           2 LOAD_FAST_OR_NULL        0 (x)
              4 BUILD_LIST               0
              6 LOAD_FAST                0 (x)
              8 GET_ITER
        >>   10 FOR_ITER                 4 (to 22)
             14 STORE_FAST               0 (x)
             16 LOAD_FAST                0 (x)
             18 LIST_APPEND              2
             20 JUMP_BACKWARD            6 (to 10)
        >>   22 END_FOR
             24 SWAP                     2
             26 STORE_FAST               0 (x)
             28 RETURN_VALUE
```

Note that the evaluation of `x1` occurs at 6, but `x0` is stashed at 2. The two operations should be reversed I think.

I.e. 
```py
def f(x):
    return [x for x in x]
```
should be compiled as 
```py
def f(x):
    $tmp = x
    return [x for x in $tmp]
```
(I think I'd prefer `$tmp` to be on the stack, but leaving it in local `.0` would be fine if that produces cleaner code and makes for easier debugging)

**Comment by carljm** [comment]
@markshannon Ok, I think I've addressed all review comments, and CI looks good. Ready for review and pyperformance run.

**Comment by brianm78** [comment]
This seems to result in some surprising behaviour in the presence of nested functions.  Eg:

         def f():
                x = 1
                print(f"start: {x=}")
                def g():
                        print(f"start g {x=}")
                        l = [x for x in range(10)]
                        print(f"end g {x=}")
                g()
                print(f"end f: {x=}")

This seems to result in the list comprehension overwriting the closed over cell var.  Whereas in current python this will print x=1 in all cases, with this I get:

    start: x=1
    start g x=1
    end g x=9
    end f: x=9

It works if x isn't accessed in the inner function, but if it creates a closure, the STORE_FAST in the listcomp overwrites the parent x's value, rather than a local.

**Comment by carljm** [comment]
@brianm78 Thanks! This is fixed in the latest commit.

**Comment by carljm** [comment]
Latest commit also inlines comprehensions in module and class scopes; thanks @markshannon for the suggestion.

I'll come back to this tomorrow and add some more tests to increase confidence that all the edge cases are handled, and update PEP 709 accordingly.

**Comment by carljm** [comment]
(Refleaks are actually caused by https://github.com/python/cpython/pull/102661 -- I'll run the refleak buildbots again when `main` is clean.)

**Comment by ericsnowcurrently** [comment]
@carljm, sorry about that!

**Comment by carljm** [comment]
No worries!

**Comment by carljm** [comment]
@markshannon @iritkatriel PEP 709 hasn't been accepted, but I think there's a reasonable chance it might be soon, and in case that happens, I would like to be ready to get this merged in time for 3.12b1. Reviews/comments welcome!

File: Python/flowgraph.c [hunk 2]
```diff
@@ -1653,6 +1657,8 @@ fast_scan_many_locals(basicblock *entryblock, int nlocals)
             assert(arg >= 0);
             switch (instr->i_opcode) {
                 case DELETE_FAST:
+                case LOAD_FAST_AND_CLEAR:
+                case STORE_FAST_MAYBE_NULL:
```
Comment (iritkatriel) [inline Python/flowgraph.c:1662]: The comment in line 1646 is out of date now.

File: Lib/test/test_listcomps.py [hunk 3]
```diff
@@ -87,63 +88,183 @@
...
+        """
+        outputs = {"i": 20}
+        self._check_in_scopes(code, outputs)
+
+    def test_unbound_local_after_comprehension(self):
+        def f():
+            if False:
+                x = 0
+            [x for x in [1]]
+            return x
```
Comment (JelleZijlstra) [inline Lib/test/test_listcomps.py:300]: Is it worth also checking this behavior in class and module scopes? There of course it would raise plain NameError, not UnboundLocalError.

File: Misc/NEWS.d/next/Core and Builtins/2023-01-30-15-40-29.gh-issue-97933.nUlp3r.rst [hunk 4]
```diff
@@ -0,0 +1,2 @@
+Inline list, dict and set comprehensions to improve performance
```
Comment (JelleZijlstra) [inline Misc/NEWS.d/next/Core and Builtins/2023-01-30-15-40-29.gh-issue-97933.nUlp3r.rst]: We should also highlight the minor compatibility breaks this causes. Are you planning to add that to What's New?

File: Lib/test/test_listcomps.py (hunk 3 above)
Comment (JelleZijlstra) [reply Lib/test/test_listcomps.py:300]: More test suggestions:

- double-underscored names in classes in case there's an interaction with mangling.
- A comprehension nested in another one

File: Python/compile.c [hunk 5]
```diff
@@ -4968,26 +4987,187 @@ compiler_async_comprehension_generator(struct compiler *c, location loc,
...
+        assert(PyLong_Check(v));
+        long symbol = PyLong_AS_LONG(v);
+        // only values bound in the comprehension (DEF_LOCAL) need to be handled
+        // at all; DEF_LOCAL | DEF_NONLOCAL can occur in the case of an
+        // assignment expression to a nonlocal in the comprehension, these don't
+        // need handling here since they shouldn't be isolated
+        if (symbol & DEF_LOCAL && ~symbol & DEF_NONLOCAL) {
+            if (c->u->u_ste->ste_type != FunctionBlock) {
+                // non-function scope: override this name to use fast locals
+                PyDict_SetItem(c->u->u_metadata.u_fasthidden, k, Py_True);
```
Comment (JelleZijlstra) [inline Python/compile.c]: Check the return value.

File: Python/compile.c [hunk 6]
```diff
@@ -4968,26 +4987,187 @@ compiler_async_comprehension_generator(struct compiler *c, location loc,
...
+                    }
+                }
+                // in the case of a cell, this will actually push the cell
+                // itself to the stack, then we'll create a new one for the
+                // comprehension and restore the original one after
+                ADDOP_NAME(c, loc, LOAD_FAST_AND_CLEAR, k, varnames);
+                if (scope == CELL) {
+                    ADDOP_NAME(c, loc, MAKE_CELL, k, cellvars);
+                }
+                if (PyList_Append(state->pushed_locals, k)) {
```
Comment (JelleZijlstra) [inline Python/compile.c]:
```suggestion
                if (PyList_Append(state->pushed_locals, k) < 0) {
```
Slightly clearer

File: Python/compile.c [hunk 7]
```diff
@@ -4968,26 +4987,187 @@ compiler_async_comprehension_generator(struct compiler *c, location loc,
...
+                }
+                // update the symbol to the in-comprehension version and save
+                // the outer version; we'll restore it after running the
+                // comprehension
+                Py_INCREF(outv);
+                if (PyDict_SetItem(c->u->u_ste->ste_symbols, k, v)) {
+                    Py_DECREF(outv);
+                    return ERROR;
+                }
+                if (PyDict_SetItem(state->temp_symbols, k, outv)) {
```
Comment (JelleZijlstra) [inline Python/compile.c]: Maybe assert that it's not already in temp_symbols? I'm a bit suspicious about how this works if you nest two comprehensions, though so far I haven't been able to find any code that's actually buggy.

File: Misc/NEWS.d/next/Core and Builtins/2023-01-30-15-40-29.gh-issue-97933.nUlp3r.rst (hunk 4 above)
Comment (carljm) [reply Misc/NEWS.d/next/Core and Builtins/2023-01-30-15-40-29.gh-issue-97933.nUlp3r.rst]: Good point, will add a more detailed paragraph to What's New including the behavior changes. If I do that, is there any reason to keep a NEWS entry also?

File: Python/compile.c (hunk 7 above)
Comment (carljm) [reply Python/compile.c]: `state` is per-comprehension, not global. So if there are nested comprehensions, compilation of each one has its own `temp_symbols`, and nesting works fine (the inner comprehension will see the value placed in `ste_symbols` by the outer comprehension, and save/restore that one, and then the outer comprehension will restore its saved value from outside both comprehensions). I will add some nested-comprehension test cases to ensure this.

File: Misc/NEWS.d/next/Core and Builtins/2023-01-30-15-40-29.gh-issue-97933.nUlp3r.rst (hunk 4 above)
Comment (JelleZijlstra) [reply Misc/NEWS.d/next/Core and Builtins/2023-01-30-15-40-29.gh-issue-97933.nUlp3r.rst]: I think we do still need a NEWS entry for the change, but it can stay brief; the detail can just go into the What's New.

Comment (AlexWaygood) [reply Misc/NEWS.d/next/Core and Builtins/2023-01-30-15-40-29.gh-issue-97933.nUlp3r.rst]: In https://github.com/python/cpython/pull/103348/files, I linked directly to my What's New entry from my NEWS entry -- could consider doing something similar!

Comment (carljm) [reply Misc/NEWS.d/next/Core and Builtins/2023-01-30-15-40-29.gh-issue-97933.nUlp3r.rst]: Good suggestion! In this case since there's a PEP that has even more detail than the What's New entry, I decided to have NEWS and What's New both link directly to the PEP, instead of having NEWS link to What's New.

File: Lib/test/test_listcomps.py [hunk 8]
```diff
@@ -236,6 +241,29 @@ def test_introspecting_frame_locals(self):
         outputs = {"i": 20}
         self._check_in_scopes(code, outputs)
 
+    def test_nested(self):
+        code = """
+            l = [1, 2, 3]
+            y = [x*2 for x in [x for x in l]]
```
Comment (JelleZijlstra) [inline Lib/test/test_listcomps.py]: I'd say this isn't really nested because the inner comprehension is executed in the enclosing scope.

Something like this is more interesting:

`[[x ** 2 for x in range(x)] for x in l]`

`[x for [x ** x for x in range(x)][x] in l]`

Comment (carljm) [reply Lib/test/test_listcomps.py]: Good point :) Pushed your first example as a better test.

The second example is invalid syntax as written; if there's a distinct case you were aiming to get at there, let me know and I can try to craft a test for it.

Comment (JelleZijlstra) [reply Lib/test/test_listcomps.py]: Sorry, I wrote that without testing.

Here's a version of the second example that runs:

```
>>> l = [1, 2, 3]
>>> x = 3
>>> [x for [x ** x for x in range(x)][x - 1] in l]
[3, 3, 3]
```

The point is to test cases where the nested comprehension is in the assignment target for the outer comprehension.

Comment (JelleZijlstra) [reply Lib/test/test_listcomps.py]: Even worse:

```
>>> l = [(1, 2), (3, 4), (5, 6)]
>>> [x for (x, [x ** x for x in range(x)][x - 1]) in l]
[1, 3, 5]
```
(Now both comprehensions assign to the name `x`.)

Comment (carljm) [reply Lib/test/test_listcomps.py]: Thanks for the great examples! That latter example looks like it uncovered a real incompatibility, in class/module scope only. Looking into it now.

Comment (AlexWaygood) [reply Lib/test/test_listcomps.py]: Now I need to figure out how to work one of these terrible snippets into a PR to one of Jelle's projects :)

Comment (carljm) [reply Lib/test/test_listcomps.py]: FWIW, the issue is that `u_fasthidden` (unlike the `state` tracking) is global, and does have a nesting problem; we'll clear it from `Py_True` to `Py_False` on exiting the inner comprehension, when it should remain `Py_True` until exiting the outer comprehension. Thanks for catching this!!

**Comment by JelleZijlstra** [comment]
There is a refleak. I took a quick look but it wasn't immediately obvious where the leak is.

**Review by JelleZijlstra — APPROVED** [review]
I can't say I entirely understand the compiler/symtable code here, but all the cases I can think of are covered.

File: Python/compile.c [hunk 9]
```diff
@@ -1241,9 +1245,7 @@ compiler_enter_scope(struct compiler *c, identifier name,
         /* Cook up an implicit __class__ cell. */
         int res;
```
Comment (iritkatriel) [inline Python/compile.c]:
```suggestion
        Py_ssize_t res;
```

File: Python/compile.c [hunk 10]
```diff
@@ -2235,7 +2243,6 @@ compiler_class(struct compiler *c, stmt_ty s)
                 compiler_exit_scope(c);
                 return ERROR;
             }
-            assert(i == 0);
```
Comment (iritkatriel) [inline Python/compile.c:2238]: Can this assertion be fixed rather than removed? (Is it important for anything?)

File: Python/compile.c [hunk 11]
```diff
@@ -2245,7 +2252,6 @@ compiler_class(struct compiler *c, stmt_ty s)
         }
         else {
             /* No methods referenced __class__, so just return None */
-            assert(PyDict_GET_SIZE(c->u->u_metadata.u_cellvars) == 0);
```
Comment (iritkatriel) [inline Python/compile.c:2248]: ditto

File: Python/compile.c [hunk 12]
```diff
@@ -4968,26 +4984,210 @@ compiler_async_comprehension_generator(struct compiler *c, location loc,
...
+    PyObject *k, *v;
+    Py_ssize_t pos = 0;
+    while (PyDict_Next(entry->ste_symbols, &pos, &k, &v)) {
+        assert(PyLong_Check(v));
+        long symbol = PyLong_AS_LONG(v);
+        // only values bound in the comprehension (DEF_LOCAL) need to be handled
+        // at all; DEF_LOCAL | DEF_NONLOCAL can occur in the case of an
+        // assignment expression to a nonlocal in the comprehension, these don't
+        // need handling here since they shouldn't be isolated
+        if (symbol & DEF_LOCAL && ~symbol & DEF_NONLOCAL) {
```
Comment (iritkatriel) [inline Python/compile.c]:
```suggestion
        if (symbol & DEF_LOCAL && !(symbol & DEF_NONLOCAL)) {
```

I think this is clearer.

File: Python/symtable.c [hunk 13]
```diff
@@ -558,6 +559,65 @@ analyze_name(PySTEntryObject *ste, PyObject *scopes, PyObject *name, long flags,
     return 1;
 }
 
+static int
+is_free_in_children(PySTEntryObject *entry, PyObject *key) {
```
Comment (iritkatriel) [inline Python/symtable.c]:
```suggestion
is_free_in_child(PySTEntryObject *entry, PyObject *key) {
```

(it checks for one, not all children)

File: Python/symtable.c [hunk 14]
```diff
@@ -558,6 +559,65 @@ analyze_name(PySTEntryObject *ste, PyObject *scopes, PyObject *name, long flags,
...
+
+static int
+inline_comprehension(PySTEntryObject *ste, PySTEntryObject *comp,
+                     PyObject *scopes, PyObject *comp_free)
+{
+    PyObject *k, *v;
+    Py_ssize_t pos = 0;
+    while (PyDict_Next(comp->ste_symbols, &pos, &k, &v)) {
+        // skip comprehension parameter
+        long comp_flags = PyLong_AS_LONG(v);
```
Comment (iritkatriel) [inline Python/symtable.c:584]: we don't need to check for error here?

File: Python/symtable.c [hunk 15]
```diff
@@ -558,6 +559,65 @@ analyze_name(PySTEntryObject *ste, PyObject *scopes, PyObject *name, long flags,
...
+            int ok = PyDict_SetItem(ste->ste_symbols, k, v_flags);
+            Py_DECREF(v_flags);
+            if (ok < 0) {
+                return 0;
+            }
+            SET_SCOPE(scopes, k, scope);
+        } else {
+            // free vars in comprehension that are locals in outer scope can
+            // now simply be locals, unless they are free in comp children
+            if ((PyLong_AsLong(existing) & DEF_BOUND) &&
```
Comment (iritkatriel) [inline Python/symtable.c:612]: check for error?

File: Python/compile.c (hunk 10 above)
Comment (carljm) [reply Python/compile.c:2238]: This is asserting that class scopes cannot have any cells other than the `__class__` cell. With inlining of comprehensions in class scopes, this is just not true anymore, so the assertion is not relevant; there is no other assertion to replace it with.

As far as I've been able to discover, there is no actual problem with cells in class scopes (as evidenced by the existence of `__class__` cells), it's just something that couldn't previously occur, and so it made sense to sanity-check it. Now it can occur.

File: Python/compile.c (hunk 11 above)
Comment (carljm) [reply Python/compile.c:2248]: Same as above.

**Review by carljm — COMMENTED** [review]
Thanks for review!

File: Python/symtable.c (hunk 14 above)
Comment (carljm) [reply Python/symtable.c:584]: No, I don't think we need to. The only error case for `PyLong_AS_LONG` is "doesn't fit in a long" and it's not possible for a variable's scope flags to have such a large value. There are lots of already-existing similar uses of `PyLong_AS_LONG` in `symtable.c`, and none of them check for error.

File: Python/symtable.c (hunk 15 above)
Comment (carljm) [reply Python/symtable.c:612]: same as above

File: Python/compile.c [hunk 16]
```diff
@@ -4968,26 +4984,210 @@ compiler_async_comprehension_generator(struct compiler *c, location loc,
...
+}
+
+static inline int
+compiler_comprehension_iter(struct compiler *c, location loc,
+                            comprehension_ty comp)
+{
+    VISIT(c, expr, comp->iter);
+    if (comp->is_async) {
+        ADDOP(c, loc, GET_AITER);
+    } else {
```
Comment (erlend-aasland) [inline Python/compile.c]:
```suggestion
    }
    else {
```

File: Python/compile.c [hunk 17]
```diff
@@ -4968,26 +4984,210 @@ compiler_async_comprehension_generator(struct compiler *c, location loc,
...
-    is_async_generator = c->u->u_ste->ste_coroutine;
+    outermost = (comprehension_ty) asdl_seq_GET(generators, 0);
+    if (is_inlined) {
+        if (compiler_comprehension_iter(c, loc, outermost)) {
+            goto error;
+        }
+        if (push_inlined_comprehension_state(c, loc, entry, &inline_state)) {
+            goto error;
+        }
+    } else {
```
Comment (erlend-aasland) [inline Python/compile.c]:
```suggestion
    }
    else {
```

File: Python/flowgraph.c [hunk 18]
```diff
@@ -1975,13 +1982,15 @@ push_cold_blocks_to_end(cfg_builder *g, int code_flags) {
...
 void
-_PyCfg_ConvertExceptionHandlersToNops(basicblock *entryblock)
+_PyCfg_ConvertPseudoOps(basicblock *entryblock)
 {
     for (basicblock *b = entryblock; b != NULL; b = b->b_next) {
         for (int i = 0; i < b->b_iused; i++) {
             cfg_instr *instr = &b->b_instr[i];
             if (is_block_push(instr) || instr->i_opcode == POP_BLOCK) {
                 INSTR_SET_OP0(instr, NOP);
+            } else if (instr->i_opcode == STORE_FAST_MAYBE_NULL) {
```
Comment (erlend-aasland) [inline Python/flowgraph.c]:
```suggestion
            }
            else if (instr->i_opcode == STORE_FAST_MAYBE_NULL) {
```

File: Python/symtable.c [hunk 19]
```diff
@@ -558,6 +559,65 @@ analyze_name(PySTEntryObject *ste, PyObject *scopes, PyObject *name, long flags,
     return 1;
 }
 
+static int
+is_free_in_any_child(PySTEntryObject *entry, PyObject *key) {
```
Comment (erlend-aasland) [inline Python/symtable.c]:
```suggestion
is_free_in_any_child(PySTEntryObject *entry, PyObject *key)
{
```

File: Python/symtable.c [hunk 20]
```diff
@@ -558,6 +559,65 @@ analyze_name(PySTEntryObject *ste, PyObject *scopes, PyObject *name, long flags,
...
+            if (v_flags == NULL) {
+                return 0;
+            }
+            int ok = PyDict_SetItem(ste->ste_symbols, k, v_flags);
+            Py_DECREF(v_flags);
+            if (ok < 0) {
+                return 0;
+            }
+            SET_SCOPE(scopes, k, scope);
+        } else {
```
Comment (erlend-aasland) [inline Python/symtable.c]:
```suggestion
        }
        else {
```

File: Python/symtable.c [hunk 21]
```diff
@@ -826,28 +886,52 @@ analyze_block(PySTEntryObject *ste, PyObject *bound, PyObject *free,
...
-    Py_DECREF(temp);
+    /* Splice children of inlined comprehensions into our children list */
+    for (i = PyList_GET_SIZE(ste->ste_children) - 1; i >= 0; --i) {
+        PyObject* c = PyList_GET_ITEM(ste->ste_children, i);
+        PySTEntryObject* entry;
+        assert(c && PySTEntry_Check(c));
+        entry = (PySTEntryObject*)c;
+        if (entry->ste_comp_inlined &&
+                PyList_SetSlice(ste->ste_children, i, i + 1,
+                                entry->ste_children) < 0) {
```
Comment (erlend-aasland) [inline Python/symtable.c]:
```suggestion
        if (entry->ste_comp_inlined &&
            PyList_SetSlice(ste->ste_children, i, i + 1,
                            entry->ste_children) < 0)
        {
```

**Review by iritkatriel — APPROVED** [review]

File: Python/symtable.c [hunk 22]
```diff
@@ -826,28 +886,52 @@ analyze_block(PySTEntryObject *ste, PyObject *bound, PyObject *free,
...
+
+        // we inline all non-generator-expression comprehensions
+        int inline_comp =
+            entry->ste_comprehension &&
+            !entry->ste_generator;
+
         if (!analyze_child_block(entry, newbound, newfree, newglobal,
-                                 allfree))
+                                 &child_free))
+            goto error;
```
Comment (erlend-aasland) [inline Python/symtable.c]:
```suggestion
                                 &child_free))
        {
            goto error;
        }
```

**Review by erlend-aasland — COMMENTED** [review]
I see Jelle and Irit did the heavy review, so this is your PEP-7 bot chiming in for some style suggestions 🤖

**Comment by carljm** [comment]
The buildbot worker hosting the various `s390x Fedora ...` builds appears to be out of disk space and unhealthy. So I'm satisfied that there aren't any buildbot issues caused by this PR.

Merging!
