### PR TITLE
gh-92888: Fix memoryview bad `__index__` use after free

### LINKED ISSUE #92888: Use After Free when assigning into a memoryview
**Bug report**

within memoryview.c, I have found two Use After Frees, both based around `memory_ass_sub`. 
The first is if a class with a malicious `__index__` method is used as the index for the assignment, its index method is called after the memoryview is checked if it is released. This allows the index method to release the memory view and backing buffer, leading to a write to freed memory when the write completes. The same vuln exists if the class with a malicious index method is used as the assigned value, as its `__index__` method is called inside of `pack_single`

```py
# memoryview Use After Free (memory_ass_sub)
uaf_backing = bytearray(bytearray.__basicsize__)
uaf_view = memoryview(uaf_backing).cast('n') # ssize_t format

class weird_index:
    def __index__(self):
        global memory_backing
        uaf_view.release() # release memoryview (UAF)
        # free `uaf_backing` memory and allocate a new bytearray into it
        memory_backing = uaf_backing.clear() or bytearray()
        return 2 # `ob_size` idx

# by the time this line finishes executing, it writes the max ptr size
# into the `ob_size` slot of `memory_backing`
uaf_view[weird_index()] = (2 ** (tuple.__itemsize__ * 8) - 1) // 2
memory = memoryview(memory_backing)
memory[id(250) + int.__basicsize__] = 100
print(250) # prints 100
```

**Your environment**

- CPython versions tested on: Python 3.10.2 (main, Feb  2 2022, 07:36:01) [Clang 12.0.0 (clang-1200.0.32.29)] on darwin
- Operating system and architecture: MacOS, 64bit

### PR DESCRIPTION
**Pull request by Fidget-Spinner**
Co-Authored-By: chilaxan <35645806+chilaxan@users.noreply.github.com>
Fixes #92888

### CODE REVIEW

File: Misc/NEWS.d/next/Security/2022-05-19-08-53-07.gh-issue-92888.TLtR9W.rst [hunk 1]
```diff
@@ -0,0 +1 @@
+Fix ``memoryview`` use after free when subscripting an object with bad ``__index__``. This occurs when the backing buffer is released inside ``__index__``.
```
Comment (serhiy-storchaka) [inline Misc/NEWS.d/next/Security/2022-05-19-08-53-07.gh-issue-92888.TLtR9W.rst]: It is not necessary that it is a bad `__index__`. This can occur when the backing buffer is released at the time of executing `__index__` of an index or a slice, or `__index__`, `__float__`, `__bool__` or `__len__` of the assigned value. It can occur if it is released in other thread, but it is easier to test if do it in the special method itself. It would be nice to have tests for all these cases.

And there may be similar problems with reading from a memoryview.

**Comment by serhiy-storchaka** [comment]
I have other approach, but your approach is more compatible, so it is safer to use it backports. I'll experiment with other approach in the developing branch only.

You can use the following test as a base:
```python
    def test_use_released_memory(self):
        size = 128
        def release():
            m.release()
            nonlocal ba
            ba = bytearray(size)
        class MyIndex:
            def __index__(self):
                release()
                return 4

        class MyFloat:
            def __float__(self):
                release()
                return 4.25

        class MyBool:
            def __bool__(self):
                release()
                return True

        ba = None
        m = memoryview(bytearray(b'\xff'*size))
        with self.assertRaises(ValueError):
            m[MyIndex()]

        ba = None
        m = memoryview(bytearray(b'\xff'*size))
        self.assertEqual(list(m[:MyIndex()]), [255] * 4)

        ba = None
        m = memoryview(bytearray(b'\xff'*size))
        self.assertEqual(list(m[MyIndex():8]), [255] * 4)

        ba = None
        m = memoryview(bytearray(b'\xff'*size))
        m[MyIndex()] = 42
        self.assertEqual(ba[:8], b'\0'*8)

        ba = None
        m = memoryview(bytearray(b'\xff'*size))
        m[:MyIndex()] = b'spam'
        self.assertEqual(ba[:8], b'\0'*8)

        ba = None
        m = memoryview(bytearray(b'\xff'*size))
        m[MyIndex():8] = b'spam'
        self.assertEqual(ba[:8], b'\0'*8)

        ba = None
        m = memoryview(bytearray(b'\xff'*size))
        m[0] = MyIndex()
        self.assertEqual(ba[:8], b'\0'*8)

        for fmt in 'bhilqnBHILQN':
            ba = None
            m = memoryview(bytearray(b'\xff'*size)).cast(fmt)
            m[0] = MyIndex()
            self.assertEqual(ba[:8], b'\0'*8)

        for fmt in 'fd':
            ba = None
            m = memoryview(bytearray(b'\xff'*size)).cast(fmt)
            m[0] = MyFloat()
            self.assertEqual(ba[:8], b'\0'*8)

        ba = None
        m = memoryview(bytearray(b'\xff'*size)).cast('?')
        m[0] = MyBool()
        self.assertEqual(ba[:8], b'\0'*8)
```

**Comment by Fidget-Spinner** [comment]
@serhiy-storchaka thanks taking the time to review and writing those really comprehensive tests. One part of your test fails on my branch: specifically `m[MyIndex()] = 42` raises `ValueError`. That's supposed to happen right?

**Comment by Fidget-Spinner** [comment]
Great, thanks to your tests I found that my fix didn't cover slices. It now does.

File: Lib/test/test_memoryview.py [hunk 2]
```diff
@@ -545,6 +545,83 @@ def test_pickle(self):
...
+            m[MyIndex()]
+
+        ba = None
+        m = memoryview(bytearray(b'\xff'*size))
+        self.assertEqual(list(m[:MyIndex()]), [255] * 4)
+
+        ba = None
+        m = memoryview(bytearray(b'\xff'*size))
+        self.assertEqual(list(m[MyIndex():8]), [255] * 4)
+
```
Comment (serhiy-storchaka) [inline Lib/test/test_memoryview.py:582]:
```suggestion

        ba = None
        m = memoryview(bytearray(b'\xff'*size)).cast('B', (64, 2))
        self.assertEqual(m[MyIndex(), 0], 0)

        ba = None
        m = memoryview(bytearray(b'\xff'*size)).cast('B', (2, 64))
        self.assertEqual(m[0, MyIndex()], 0)
```

File: Lib/test/test_memoryview.py [hunk 3]
```diff
@@ -545,6 +545,83 @@ def test_pickle(self):
...
+        with self.assertRaisesRegex(ValueError, "operation forbidden"):        
+            m[:MyIndex()] = b'spam'
+        self.assertEqual(ba[:8], b'\0'*8)
+
+        ba = None
+        m = memoryview(bytearray(b'\xff'*size))
+        with self.assertRaisesRegex(ValueError, "operation forbidden"):        
+            m[MyIndex():8] = b'spam'
+        self.assertEqual(ba[:8], b'\0'*8)
+
```
Comment (serhiy-storchaka) [inline Lib/test/test_memoryview.py:610]:
```suggestion

        ba = None
        m = memoryview(bytearray(b'\xff'*size)).cast('B', (64, 2))
        with self.assertRaisesRegex(ValueError, "operation forbidden"):
            m[MyIndex(), 0] = 42
        self.assertEqual(ba[8:16], b'\0'*8)

        ba = None
        m = memoryview(bytearray(b'\xff'*size)).cast('B', (2, 64))
        with self.assertRaisesRegex(ValueError, "operation forbidden"):
            m[0, MyIndex()] = 42
        self.assertEqual(ba[:8], b'\0'*8)
```

**Review by serhiy-storchaka — COMMENTED** [review]
Yet few tests.

File: Lib/test/test_memoryview.py [hunk 4]
```diff
@@ -545,6 +545,101 @@ def test_pickle(self):
...
+        m = memoryview(bytearray(b'\xff'*size))
+        self.assertEqual(list(m[:MyIndex()]), [255] * 4)
+
+        ba = None
+        m = memoryview(bytearray(b'\xff'*size))
+        self.assertEqual(list(m[MyIndex():8]), [255] * 4)
+
+        ba = None
+        m = memoryview(bytearray(b'\xff'*size)).cast('B', (64, 2))
+        self.assertEqual(m[MyIndex(), 0], 0)
```
Comment (serhiy-storchaka) [inline Lib/test/test_memoryview.py]: And here is a bug. The original bytearray does not contain zeroes.

File: Lib/test/test_memoryview.py [hunk 5]
```diff
@@ -545,6 +545,101 @@ def test_pickle(self):
...
+
+        ba = None
+        m = memoryview(bytearray(b'\xff'*size))
+        with self.assertRaisesRegex(ValueError, "operation forbidden"):
+            m[MyIndex()] = 42
+        self.assertEqual(ba[:8], b'\0'*8)
+
+        ba = None
+        m = memoryview(bytearray(b'\xff'*size))
+        with self.assertRaisesRegex(ValueError, "operation forbidden"):
```
Comment (serhiy-storchaka) [inline Lib/test/test_memoryview.py]: Trailing spaces here.

File: Lib/test/test_memoryview.py [hunk 6]
```diff
@@ -545,6 +545,101 @@ def test_pickle(self):
...
+
+        ba = None
+        m = memoryview(bytearray(b'\xff'*size))
+        with self.assertRaisesRegex(ValueError, "operation forbidden"):        
+            m[:MyIndex()] = b'spam'
+        self.assertEqual(ba[:8], b'\0'*8)
+
+        ba = None
+        m = memoryview(bytearray(b'\xff'*size))
+        with self.assertRaisesRegex(ValueError, "operation forbidden"):
```
Comment (serhiy-storchaka) [inline Lib/test/test_memoryview.py]: And here.

**Review by serhiy-storchaka — APPROVED** [review]
:+1:

File: Lib/test/test_memoryview.py [hunk 7]
```diff
@@ -545,6 +545,104 @@ def test_pickle(self):
...
+
+        ba = None
+        m = memoryview(bytearray(b'\xff'*size)).cast('B', (64, 2))
+        with self.assertRaisesRegex(ValueError, "operation forbidden"):
+            m[MyIndex(), 0]
+        
+        ba = None
+        m = memoryview(bytearray(b'\xff'*size)).cast('B', (2, 64))
+        with self.assertRaisesRegex(ValueError, "operation forbidden"):
+            m[0, MyIndex()], 0
```
Comment (serhiy-storchaka) [inline Lib/test/test_memoryview.py]: Redundant 0.

File: Lib/test/test_memoryview.py [hunk 8]
```diff
@@ -545,6 +545,104 @@ def test_pickle(self):
...
+
+        ba = None
+        m = memoryview(bytearray(b'\xff'*size))
+        self.assertEqual(list(m[MyIndex():8]), [255] * 4)
+
+        ba = None
+        m = memoryview(bytearray(b'\xff'*size)).cast('B', (64, 2))
+        with self.assertRaisesRegex(ValueError, "operation forbidden"):
+            m[MyIndex(), 0]
+
```
Comment (serhiy-storchaka) [inline Lib/test/test_memoryview.py]: Trailing whitespaces here.

**Comment by serhiy-storchaka** [comment]
I am sorry for being so pedantic. :man_facepalming:

**Comment by Fidget-Spinner** [comment]
> I am sorry for being so pedantic. man_facepalming

I didn't feel that you were. Those are errors I ought to have caught anyways. Thanks for the detailed review as always.

**Review by serhiy-storchaka — APPROVED** [review]

File: Objects/memoryobject.c [hunk 9]
```diff
@@ -1778,12 +1781,15 @@ pack_single(char *ptr, PyObject *item, const char *fmt)
     double d;
     void *p;
 
+    CHECK_RELEASED_INT(self); /* See gh-92888 for why we need this here */
```
Comment (vstinner) [inline Objects/memoryobject.c]: I don't think that it's worth it to do the check here. Doing it just before the final write is enough, no?

File: Objects/memoryobject.c [hunk 10]
```diff
@@ -381,8 +381,9 @@ copy_rec(const Py_ssize_t *shape, Py_ssize_t ndim, Py_ssize_t itemsize,
 
 /* Faster copying of one-dimensional arrays. */
 static int
-copy_single(const Py_buffer *dest, const Py_buffer *src)
+copy_single(PyMemoryViewObject *self, const Py_buffer *dest, const Py_buffer *src)
 {
+    CHECK_RELEASED_INT(self); /* See gh-92888 for why we need this here */
```
Comment (vstinner) [inline Objects/memoryobject.c]: Can you move the check after the equiv_structure() test?

File: Objects/memoryobject.c [hunk 11]
```diff
@@ -1689,6 +1690,8 @@ unpack_single(const char *ptr, const char *fmt)
     unsigned char uc;
     void *p;
 
+    CHECK_RELEASED(self); /* See gh-92888 for why we need this here */
```
Comment (vstinner) [inline Objects/memoryobject.c]: Rather than copy/paste the same comment, maybe you can add a new macro with a more explicit name, and put a long comment explaining why this macro is needed. The implementation would just call CHECK_RELEASED().

For example, CHECK_AGAIN_RELEASED().

File: Misc/NEWS.d/next/Security/2022-05-19-08-53-07.gh-issue-92888.TLtR9W.rst [hunk 12]
```diff
@@ -0,0 +1,2 @@
+Fix ``memoryview`` use after free when accessing the backing buffer in certain cases.
```
Comment (vstinner) [inline Misc/NEWS.d/next/Security/2022-05-19-08-53-07.gh-issue-92888.TLtR9W.rst:1]: I propose to mention more explicitly that the protection is about released views:

```
If a memoryview is released while getting or setting an item, raise an exception.
For example, converting an object to an index can execute arbitrary Python
code which can indirectly release the memoryview.
```

File: Lib/test/test_memoryview.py [hunk 13]
```diff
@@ -545,6 +545,104 @@ def test_pickle(self):
             with self.assertRaises(TypeError):
                 pickle.dumps(m, proto)
 
+    def test_use_released_memory(self):
```
Comment (vstinner) [inline Lib/test/test_memoryview.py:548]: Please mention a comment mentioning ``gh-92888: `` which explain the purpose of the test.

File: Lib/test/test_memoryview.py [hunk 14]
```diff
@@ -545,6 +545,104 @@ def test_pickle(self):
...
+        size = 128
+        def release():
+            m.release()
+            nonlocal ba
+            ba = bytearray(size)
```
Comment (vstinner) [inline Lib/test/test_memoryview.py:556]: That's useless, no?

File: Lib/test/test_memoryview.py [hunk 15]
```diff
@@ -545,6 +545,104 @@ def test_pickle(self):
...
+            def __float__(self):
+                release()
+                return 4.25
+        class MyBool:
+            def __bool__(self):
+                release()
+                return True
+
+        ba = None
+        m = memoryview(bytearray(b'\xff'*size))
```
Comment (vstinner) [inline Lib/test/test_memoryview.py:571]: In my PR, I tried to make the code more generic to test more cases: https://github.com/python/cpython/pull/93127/files#diff-d41c6bb40a1e03fea5a20d15c4077413e0ddde65651147922b625b03a66a2f16R399:

```
        tp = self.rw_type
        b = self.rw_type(self._source)
        view = self._view(b)
```

File: Lib/test/test_memoryview.py [hunk 16]
```diff
@@ -545,6 +545,104 @@ def test_pickle(self):
...
+        with self.assertRaises(ValueError):
+            m[MyIndex()]
```
Comment (vstinner) [inline Lib/test/test_memoryview.py:573]: This test is very long. Can you try to factorize similar code and use loop with subTest(), and put pack operations in one test method and unpack in another test method?

**Review by vstinner — COMMENTED** [review]
I like your approach to fix memory_ass_sub(). Here is a first review.

File: Objects/memoryobject.c (hunk 10 above)
Comment (serhiy-storchaka) [reply Objects/memoryobject.c]: Would not access to Py_buffer of the released object cause reading after free?

File: Lib/test/test_memoryview.py (hunk 16 above)
Comment (serhiy-storchaka) [reply Lib/test/test_memoryview.py:573]: Then we will need to duplicate the definitions of internal classes.

The tested code is so different, that it is difficult to use a loop. And I think that the result will be more complicated.

File: Misc/NEWS.d/next/Security/2022-05-19-08-53-07.gh-issue-92888.TLtR9W.rst (hunk 12 above)
Comment (serhiy-storchaka) [reply Misc/NEWS.d/next/Security/2022-05-19-08-53-07.gh-issue-92888.TLtR9W.rst:1]: Not always an exception is raised.

The bug was in reading or wring the freed memory. Now it is prevented -- you either get an exception or free the memory after reading.  @Fidget-Spinner's description is more correct.

I am going to address such inconsistency in a separate issue.

File: Lib/test/test_memoryview.py (hunk 14 above)
Comment (Fidget-Spinner) [reply Lib/test/test_memoryview.py:556]: No, we need it for tests below that tests indexing into `ba[]`.

Comment (serhiy-storchaka) [reply Lib/test/test_memoryview.py:556]: We allocate a bytearray of the same size as the bytearray just released in memoryview in hope that it will be allocated at the same memory. It helps to check that we do nor read/write a freed memory.

File: Lib/test/test_memoryview.py [hunk 17]
```diff
@@ -564,25 +567,20 @@ def __bool__(self):
                 release()
                 return True
 
-        ba = None
         m = memoryview(bytearray(b'\xff'*size))
         with self.assertRaises(ValueError):
             m[MyIndex()]
 
-        ba = None
```
Comment (serhiy-storchaka) [inline Lib/test/test_memoryview.py]: It is necessary. The old bytearray should be deallocated before creating a new bytearray, so all bytearrays will be allocated at the same place.

**Comment by Fidget-Spinner** [comment]
@vstinner do you have any major objections? Otherwise, I plan to merge.

**Comment by vstinner** [comment]
My reviews on the tests were just remarks, not objections.
