### PR TITLE
gh-92019: Make sqlite3.Blob indexing conform with the norm

### LINKED ISSUE #92019: sqlite3.Blob indexing is not conformant with existing norms
Yesterday, @JelleZijlstra enlightened me that sqlite3.Blob indexing operate with `bytes` objects of length 1. This is a deviation from how `bytes`, `bytearray`, and `memoryview` work:

```
>>> bytes(b"0")[0]
48
>>> bytearray(b"0")[0]
48
>>> memoryview(b"0")[0]
48
>>> b = bytearray(b"0")
>>> b[0] = 1
>>> b[0] = b"1"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'bytes' object cannot be interpreted as an integer
>>> m = memoryview(b)
>>> m[0] = 1
>>> m[0] = b"1"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: memoryview: invalid type for format 'B'
>>> 
```

Suggesting to align sqlite3.Blob indexing behaviour so it expects `int`s and returns `int`s.

### PR DESCRIPTION
**Pull request by erlend-aasland**
- get index now returns an int
- set index now requires an int in range(0, 256)

Resolves #92019

### CODE REVIEW

**Comment by erlend-aasland** [comment]
> All commit authors signed the Contributor License Agreement. 
> [CLA signed](https://cpython-clabot.herokuapp.com/signed-contributor-license-agreement?version=96a49432b8b111ec9bf5bfe9ad6c72c4)

FTR, I've changed the email address I'm using for CPython work from my work address to my private address.

**Comment by erlend-aasland** [comment]
I'm not sure this needs a README. The blob interface has not been part of an official release yet.

File: Modules/_sqlite/blob.c [hunk 1]
```diff
@@ -455,24 +473,27 @@ ass_subscript_index(pysqlite_Blob *self, PyObject *item, PyObject *value)
...
         return -1;
     }
 
-    Py_buffer vbuf;
-    if (PyObject_GetBuffer(value, &vbuf, PyBUF_SIMPLE) < 0) {
-        return -1;
+    long val = PyLong_AsLong(value);
+    if (val == -1 && PyErr_Occurred()) {
+        PyErr_Clear();
+        val = -1;
```
Comment (erlend-aasland) [inline Modules/_sqlite/blob.c:493]: FTR, this aligns with how `bytearray` work:

```
>>> bytearray(b"0")[0] = 2**65
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: byte must be in range(0, 256)
```

File: Modules/_sqlite/blob.c [hunk 2]
```diff
@@ -120,7 +120,25 @@ blob_seterror(pysqlite_Blob *self, int rc)
 }
 
 static PyObject *
-inner_read(pysqlite_Blob *self, Py_ssize_t length, Py_ssize_t offset)
+read_single(pysqlite_Blob *self, Py_ssize_t offset)
+{
+    assert(offset <= sqlite3_blob_bytes(self->blob));
```
Comment (JelleZijlstra) [inline Modules/_sqlite/blob.c]: This can be `<`, right? I was looking at this code last night and noticed this. I think inner_read also has a `<=` where it could be `<`.

File: Modules/_sqlite/blob.c (hunk 1 above)
Comment (JelleZijlstra) [reply Modules/_sqlite/blob.c:493]: Yes. I was thinking of promoting `_getbytevalue` in bytearrayobject.c to the internal API so we can reuse it directly, but that's probably overkill for such a simple function.

**Review by JelleZijlstra — COMMENTED** [review]
Thank you for the quick change! I'll take a closer look soon. I don't think it needs a NEWS entry because the current behavior wasn't released in any alpha.

**Comment by JelleZijlstra** [comment]
Also, something wrong on Windows:

```
FAIL: test_blob_set_item_negative_index (test.test_sqlite3.test_dbapi.BlobTests.test_blob_set_item_negative_index)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\cpython\cpython\Lib\test\test_sqlite3\test_dbapi.py", line 1210, in test_blob_set_item_negative_index
    self.assertEqual(self.blob[-1], 255)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 36281599 != 255
```

**Comment by erlend-aasland** [comment]
> Also, something wrong on Windows:

I'm on it 🕵🏻

File: Modules/_sqlite/blob.c (hunk 2 above)
Comment (erlend-aasland) [reply Modules/_sqlite/blob.c]: Yeah, good catch. I prefer to handle this in a separate PR / issue. Are you ok with that?

Comment (erlend-aasland) [reply Modules/_sqlite/blob.c]: ...or we could include it here; here's the patch:

<details>

```diff
diff --git a/Modules/_sqlite/blob.c b/Modules/_sqlite/blob.c
index d7045f030e..6d28151cc0 100644
--- a/Modules/_sqlite/blob.c
+++ b/Modules/_sqlite/blob.c
@@ -122,8 +122,6 @@ blob_seterror(pysqlite_Blob *self, int rc)
 static PyObject *
 read_single(pysqlite_Blob *self, Py_ssize_t offset)
 {
-    assert(offset <= sqlite3_blob_bytes(self->blob));
-
     unsigned long buf = 0;
     int rc;
     Py_BEGIN_ALLOW_THREADS
@@ -141,7 +139,7 @@ static PyObject *
 read_multiple(pysqlite_Blob *self, Py_ssize_t length, Py_ssize_t offset)
 {
     assert(length <= sqlite3_blob_bytes(self->blob));
-    assert(offset <= sqlite3_blob_bytes(self->blob));
+    assert(offset < sqlite3_blob_bytes(self->blob));
 
     PyObject *buffer = PyBytes_FromStringAndSize(NULL, length);
     if (buffer == NULL) {
@@ -193,6 +191,11 @@ blob_read_impl(pysqlite_Blob *self, int length)
         length = max_read_len;
     }
 
+    assert(length >= 0);
+    if (length == 0) {
+        return PyBytes_FromStringAndSize(NULL, 0);
+    }
+
     PyObject *buffer = read_multiple(self, length, self->offset);
     if (buffer == NULL) {
         return NULL;
```

</details>

Comment (JelleZijlstra) [reply Modules/_sqlite/blob.c]: Either is fine with me, I think it's small enough to just put it in here.

**Review by JelleZijlstra — APPROVED** [review]

File: Modules/_sqlite/blob.c (hunk 2 above)
Comment (erlend-aasland) [reply Modules/_sqlite/blob.c]: All right, I put it in here :)

Comment (JelleZijlstra) [reply Modules/_sqlite/blob.c]: Looks like you didn't push?

Comment (erlend-aasland) [reply Modules/_sqlite/blob.c]: I did; look again ;)

**Review by JelleZijlstra — APPROVED** [review]

**Comment by JelleZijlstra** [comment]
One buildbot failed on `FAIL: test_finalize_structseq (test.test_embed.EmbeddingTests.test_finalize_structseq)`, I think that's a known spurious failure. A few others are still running.
