### PR TITLE
gh-107895: Fix test_asyncio.test_runners when run it in CPython's "development mode"

### LINKED ISSUE #107895: test.test_asyncio.test_runners fails in "development mode"
```pytb
$ ./python -Xdev -m test test.test_asyncio.test_runners -m test_asyncio_run_debug
0:00:00 load avg: 2.08 Run tests sequentially
0:00:00 load avg: 2.08 [1/1] test.test_asyncio.test_runners
test test.test_asyncio.test_runners failed -- Traceback (most recent call last):
  File ".../Lib/test/test_asyncio/test_runners.py", line 104, in test_asyncio_run_debug
    asyncio.run(main(False))
  File ".../Lib/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File ".../Lib/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../Lib/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File ".../Lib/test/test_asyncio/test_runners.py", line 102, in main
    self.assertIs(loop.get_debug(), expected)
AssertionError: True is not False

test.test_asyncio.test_runners failed (1 failure)
...
```

### Linked PRs
* gh-108168
* gh-108196
* gh-108197

### PR DESCRIPTION
**Pull request by xncbf**
Closes #107895

* Issue: gh-107895

### CODE REVIEW

**Comment by xncbf** [comment]
@1st1

File: Misc/NEWS.d/next/Tests/2023-08-20-11-55-06.gh-issue-107895.kM3neC.rst [hunk 1]
```diff
@@ -0,0 +1 @@
+remove dependency of current debug mode
```
Comment (gvanrossum) [inline Misc/NEWS.d/next/Tests/2023-08-20-11-55-06.gh-issue-107895.kM3neC.rst]: This doesn't explain what this PR actually does. It also needs proper capitalization and punctuation.

**Review by gvanrossum — COMMENTED** [review]
IMO @serhiy-storchaka should review this, since he reported the issue.

File: Misc/NEWS.d/next/Tests/2023-08-20-11-55-06.gh-issue-107895.kM3neC.rst (hunk 1 above)
Comment (xncbf) [reply Misc/NEWS.d/next/Tests/2023-08-20-11-55-06.gh-issue-107895.kM3neC.rst]: I just edited the sentence.

File: Misc/NEWS.d/next/Tests/2023-08-20-11-55-06.gh-issue-107895.kM3neC.rst [hunk 2]
```diff
@@ -0,0 +1 @@
+Ensure test consistency regardless of debug mode.
```
Comment (corona10) [inline Misc/NEWS.d/next/Tests/2023-08-20-11-55-06.gh-issue-107895.kM3neC.rst]: Do we need to add NEWS.d? I don't think it has any user impact.

Comment (xncbf) [reply Misc/NEWS.d/next/Tests/2023-08-20-11-55-06.gh-issue-107895.kM3neC.rst]: It added because an error occurred in the workflow when NEWS.d was not added.

Comment (corona10) [reply Misc/NEWS.d/next/Tests/2023-08-20-11-55-06.gh-issue-107895.kM3neC.rst]: You can request `skip news` label if it is needed.

Comment (xncbf) [reply Misc/NEWS.d/next/Tests/2023-08-20-11-55-06.gh-issue-107895.kM3neC.rst]: I'm newbie for contribution on cpython, so I'm not used to it yet. 😅
thank you for telling me! Should I remove news.d and label it?

Comment (corona10) [reply Misc/NEWS.d/next/Tests/2023-08-20-11-55-06.gh-issue-107895.kM3neC.rst]: @serhiy-storchaka will let you know how to deal with it.

Comment (serhiy-storchaka) [reply Misc/NEWS.d/next/Tests/2023-08-20-11-55-06.gh-issue-107895.kM3neC.rst]: A NEWS entry is not needed here. This PR only fixes Python tests running in a specific environment, it does not affect common Python user.

I am not sure that third-party contributors can set labels, so I have added label "skip-news" myself.

**Review by serhiy-storchaka — APPROVED** [review]
LGTM. Thank you for your contribution @xncbf.

File: Misc/NEWS.d/next/Tests/2023-08-20-11-55-06.gh-issue-107895.kM3neC.rst (hunk 2 above)
Comment (serhiy-storchaka) [reply Misc/NEWS.d/next/Tests/2023-08-20-11-55-06.gh-issue-107895.kM3neC.rst]: But the commit message should explain changes. The proposed NEWS entry does not do this: it is not clear what test it refers, and the "debug mode" is ambiguous and can be incorrectly understood. The "-d" option of Python command is not relevant here, and the debug build of Python is not relevant either.

Comment (xncbf) [reply Misc/NEWS.d/next/Tests/2023-08-20-11-55-06.gh-issue-107895.kM3neC.rst]: Thank you for your kind explanation. @serhiy-storchaka

Comment (xncbf) [reply Misc/NEWS.d/next/Tests/2023-08-20-11-55-06.gh-issue-107895.kM3neC.rst]: I can't label it, because i am not a member btw. @serhiy-storchaka 
image
