### PR TITLE
gh-127945: fix thread safety of creating instances of ctypes structures

### LINKED ISSUE #128567: Race in ctypes PyCFuncPtr_new under free-threading
# Bug report

### Bug description:

I built cpython (3.13 branch) with free-threading and TSAN. The following python code reports TSAN warnings:
```python
import ctypes
import concurrent.futures
import threading


def raw_func(x):
    pass


def test_ctypes():
    def lookup():
        prototype = ctypes.CFUNCTYPE(None, ctypes.c_void_p)
        return prototype(raw_func)

    ctypes_args = ()
    func = lookup()
    packed_args = (ctypes.c_void_p * len(ctypes_args))()
    for argNum in range(len(ctypes_args)):
        packed_args[argNum] = ctypes.cast(ctypes_args[argNum], ctypes.c_void_p)
    func(packed_args)


if __name__ == "__main__":
    num_workers = 20

    barrier = threading.Barrier(num_workers)

    def closure():
        barrier.wait()
        test_ctypes()

    with concurrent.futures.ThreadPoolExecutor(max_workers=num_workers) as executor:
        futures = []
        for i in range(num_workers):
            futures.append(executor.submit(closure))
        assert len(list(f.result() for f in futures)) == num_workers

```
TSAN report extract:
```
WARNING: ThreadSanitizer: data race (pid=261974)
  Write of size 4 at 0x7fffbe0d0430 by thread T5:
    #0 generic_pycdata_new /project/cpython/./Modules/_ctypes/_ctypes.c:3387:17 (_ctypes.cpython-313t-x86_64-linux-gnu.so+0xdbb7) (BuildId: 6a7727f376cee83a3124898fe6eb84e45e3a54bc)
    #1 PyCFuncPtr_new /project/cpython/./Modules/_ctypes/_ctypes.c:3963:32 (_ctypes.cpython-313t-x86_64-linux-gnu.so+0x18bbb) (BuildId: 6a7727f376cee83a3124898fe6eb84e45e3a54bc)
    #2 type_call /project/cpython/Objects/typeobject.c:1981:11 (python3.13t+0x2eb032) (BuildId: 65e52348ca9319985f9f5e265fd43aab2c867d59)
    #3 _PyObject_MakeTpCall /project/cpython/Objects/call.c:242:18 (python3.13t+0x1ea44c) (BuildId: 65e52348ca9319985f9f5e265fd43aab2c867d59)
    #4 _PyObject_VectorcallTstate /project/cpython/./Include/internal/pycore_call.h:166:16 (python3.13t+0x1eb0a8) (BuildId: 65e52348ca9319985f9f5e265fd43aab2c867d59)
    #5 PyObject_Vectorcall /project/cpython/Objects/call.c:327:12 (python3.13t+0x1eb0a8)
```

[Full traceback](https://gist.github.com/vfdev-5/94ac799fddf453dc8d7186024861ccb7)
 

Related https://github.com/python/cpython/issues/128182

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

### LINKED ISSUE #128570: Race in stgdict PyCStructUnionType_update_stginfo under free-threading
# Bug report

### Bug description:

I built cpython (3.13 branch) with free-threading and TSAN. The following python code reports TSAN warnings:
```python
import ctypes
import concurrent.futures
import threading


def make_nd_memref_descriptor(rank, dtype):
    class MemRefDescriptor(ctypes.Structure):
        _fields_ = [
            ("aligned", ctypes.POINTER(dtype)),
        ]

    return MemRefDescriptor


class F32(ctypes.Structure):
    _fields_ = [("f32", ctypes.c_float)]


def test_ctypes():
    arg1_ndim = 1
    ctp = F32
    ctypes.pointer(
        ctypes.pointer(make_nd_memref_descriptor(arg1_ndim, ctp)())
    )


if __name__ == "__main__":
    num_workers = 20

    barrier = threading.Barrier(num_workers)

    def closure():
        barrier.wait()
        test_ctypes()

    with concurrent.futures.ThreadPoolExecutor(max_workers=num_workers) as executor:
        futures = []
        for i in range(num_workers):
            futures.append(executor.submit(closure))
        assert len(list(f.result() for f in futures)) == num_workers

```
TSAN report extract:
```
WARNING: ThreadSanitizer: data race (pid=264065)
  Read of size 4 at 0x7fffb80a0430 by thread T17:
    #0 PyCStructUnionType_update_stginfo /project/cpython/./Modules/_ctypes/stgdict.c:438:19 (_ctypes.cpython-313t-x86_64-linux-gnu.so+0x20976) (BuildId: 6a7727f376cee83a3124898fe6eb84e45e3a54bc)
    #1 PyCStructType_setattro /project/cpython/./Modules/_ctypes/_ctypes.c:1096:16 (_ctypes.cpython-313t-x86_64-linux-gnu.so+0xc809) (BuildId: 6a7727f376cee83a3124898fe6eb84e45e3a54bc)
    #2 PyObject_SetAttr /project/cpython/Objects/object.c:1415:15 (python3.13t+0x294fba) (BuildId: 65e52348ca9319985f9f5e265fd43aab2c867d59)
    #3 StructUnionType_init /project/cpython/./Modules/_ctypes/_ctypes.c:685:13 (_ctypes.cpython-313t-x86_64-linux-gnu.so+0xe222) (BuildId: 6a7727f376cee83a3124898fe6eb84e45e3a54bc)
    #4 PyCStructType_init /project/cpython/./Modules/_ctypes/_ctypes.c:715:12 (_ctypes.cpython-313t-x86_64-linux-gnu.so+0xc84a) (BuildId: 6a7727f376cee83a3124898fe6eb84e45e3a54bc)

```

[Full traceback](https://gist.github.com/vfdev-5/450dddf763d1ef9039c4385722cf797c)

Related to https://github.com/python/cpython/issues/127945

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

### PR DESCRIPTION
**Pull request by kumaraditya303**
* Issue: gh-127945

In free-threading, concurrent mutations to StgInfo is not thread safe.    Therefore to make it thread safe, when modifying StgInfo, this PR adds `STGINFO_LOCK` and    `STGINFO_UNLOCK` macros which are used to acquire critical section of the StgInfo.    The critical section is write only and is acquired when modifying the    StgInfo fields and while setting the `dict_final` bit. Once the `dict_final`    is set, StgInfo is treated as read only and no further modifications are    allowed. This allows to avoid acquiring the critical section for most    read operations when `dict_final` is set (general case). 

Fixes #128567
Fixes #128570

### CODE REVIEW

File: Modules/_ctypes/stgdict.c [hunk 1]
```diff
@@ -248,23 +251,30 @@ PyCStructUnionType_update_stginfo(PyObject *type, PyObject *fields, int isStruct
...
        _fields_ anymore. */
 
-    if (stginfo->flags & DICTFLAG_FINAL) {/* is final ? */
+    if (stginfo_get_dict_final(stginfo) == 1) {/* is final ? */
+        PyErr_SetString(PyExc_AttributeError,
+                        "_fields_ is final");
+        return -1;
+    }
+    STGINFO_LOCK(stginfo);
+    // check again after locking
```
Comment (colesbury) [inline Modules/_ctypes/stgdict.c]: The check *outside* the lock looks like an unnecessary optimization here. I think it's fine to check if it's marked as final once *inside* the lock.

File: Modules/_ctypes/ctypes.h [hunk 2]
```diff
@@ -399,6 +405,54 @@ typedef struct {
...
+    `STGINFO_UNLOCK` macros are used to acquire critical section of the StgInfo.
+    The critical section is write only and is acquired when modifying the
+    StgInfo fields and while setting the `dict_final` bit. Once the `dict_final`
+    is set, StgInfo is treated as read only and no further modifications are
+    allowed. This allows to avoid acquiring the critical section for most
+    read operations when `dict_final` is set (general case).
+
+    It is important to set all the fields before setting the `dict_final` bit
+    in functions like `PyCStructUnionType_update_stginfo` because the store of
+    `dict_final` uses sequential consistency memory ordering. This ensures that
```
Comment (colesbury) [inline Modules/_ctypes/ctypes.h]: Acquire/release would be fine here too, but it doesn't really matter.

File: Modules/_ctypes/ctypes.h [hunk 3]
```diff
@@ -399,6 +405,54 @@ typedef struct {
 /*      Py_ssize_t *suboffsets; */ /* unused in ctypes */
 } StgInfo;
 
+/*
+    In free-threading, concurrent mutations to StgInfo is not thread safe.
```
Comment (colesbury) [inline Modules/_ctypes/ctypes.h]: Consider something like:

```
    To ensure thread safety in the free threading build, the `STGINFO_LOCK` and
    `STGINFO_UNLOCK` macros use critical sections to protect against concurrent
    modifications to `StgInfo` and assignment of the `dict_final` field. Once
    `dict_final` is set, `StgInfo` is treated as read-only, and no further
    modifications are allowed. This approach allows most read operations to
    proceed without acquiring the critical section lock.
    
    The `dict_final` field is written only after all other modifications to
    `StgInfo` are complete. The reads and writes of `dict_final` use the
    sequentially consistent memory ordering to ensure that all other fields are
    visible to other threads before the `dict_final` bit is set.
```

File: Lib/test/test_ctypes/test_free_threading.py [hunk 4]
```diff
@@ -0,0 +1,89 @@
+from test.support import threading_helper
+import unittest
+import ctypes
+import threading
+
+threading_helper.requires_working_threading(module=True)
+
+
+class FreeThreadingTests(unittest.TestCase):
```
Comment (colesbury) [inline Lib/test/test_ctypes/test_free_threading.py]: My preference would be to get `test_ctypes` working with `--parallel-threads` instead of adding additional free-threading specific test cases.

You might need to mark some cases as `@support.thread_unsafe` if they use `warnings` or other non-thread safe code.

File: Modules/_ctypes/_ctypes.c [hunk 5]
```diff
@@ -710,13 +711,18 @@ StructUnionType_init(PyObject *self, PyObject *args, PyObject *kwds, int isStruc
...
+        int ret = 0;
+        STGINFO_LOCK(baseinfo);
         /* copy base info */
-        if (PyCStgInfo_clone(info, baseinfo) < 0) {
-            return -1;
+        ret = PyCStgInfo_clone(info, baseinfo);
+        if (ret >= 0) {
+            // clear the 'final' bit in the subclass info
+            // safe to modify without atomics as it is not exposed to other threads
+            info->dict_final = 0;
```
Comment (colesbury) [inline Modules/_ctypes/_ctypes.c]: I think this would be less confusing if the clearing of `dict_final` happens in `PyCStgInfo_clone` (just like we reset the mutex).

This is the only caller of `PyCStgInfo_clone` so I think it's functionally equivalent.

**Review by colesbury — APPROVED** [review]
Looks great! A few minor comments.

File: Lib/test/test_ctypes/test_free_threading.py (hunk 4 above)
Comment (kumaraditya303) [reply Lib/test/test_ctypes/test_free_threading.py]: > My preference would be to get test_ctypes working with --parallel-threads instead of adding additional free-threading specific test cases.

Okay, I removed the free-threading tests from this and will try to get tests working with `--parallel-threads` after this.

File: Modules/_ctypes/ctypes.h [hunk 6]
```diff
@@ -390,6 +395,7 @@ typedef struct {
     PyObject *checker;
     PyObject *module;
     int flags;                  /* calling convention and such */
+    int dict_final;
```
Comment (encukou) [inline Modules/_ctypes/ctypes.h]: Hi,
Don't have much time for a full review, all that comes to mind is conserving a bit of memory.

Could this be a bool or char, or would that hurt performance?

AFAIK flags can be uint16. And `mutex` can be moved here to fill the padding. And the `initialized` field might want to become a flag.
The rearranging could go in a separate PR, but I'd appreciate if you make `dict_final` smaller *here*, so I don't need to consult that change with free-threading experts :)

Comment (kumaraditya303) [reply Modules/_ctypes/ctypes.h]: I changed it to `uint8_t` type
