### PR TITLE
gh-139495: Fix `hashlib.file_digest()` versionchanged description of `BlockingIOError`

### LINKED ISSUE #139495: [docs] incorrect `BlockingIOError` pre-condition in versionchanged note of `hashlib.file_digest()`
`hashlib.file_digest()` now raises `BlockingIOError` if the file object is non-blocking and a syscall returns `EWOULDBLOCK`. This is incorrectly described in one spot, the `versionchanged` note.

First discussion in <https://github.com/python/cpython/pull/122183#discussion_r2398091513>, original issue #122179, original 3.13 backport #132787.
            

### Linked PRs
* gh-139496
* gh-139522
* gh-139528

### PR DESCRIPTION
**Pull request by moreati**
The sentence was missing a negation and contradicted the other two descriptions in the same commit. I believe existing code behaviour is correct.

refs #122179, fixes #139495

* Issue: gh-139495

----
📚 Documentation preview 📚: https://cpython-previews--139496.org.readthedocs.build/

### CODE REVIEW

File: Misc/NEWS.d/next/Documentation/2025-10-02-11-51-34.gh-issue-139495.y4Orqf.rst [hunk 1]
```diff
@@ -0,0 +1,2 @@
+Fix :func:`hashlib.file_digest` versionchanged description of
```
Comment (picnixz) [inline Misc/NEWS.d/next/Documentation/2025-10-02-11-51-34.gh-issue-139495.y4Orqf.rst]: There is no need for a NEWS entry I think. You can remove this file.

Comment (moreati) [reply Misc/NEWS.d/next/Documentation/2025-10-02-11-51-34.gh-issue-139495.y4Orqf.rst]: Thanks. `make patchcheck` lead me astray :)

Comment (picnixz) [reply Misc/NEWS.d/next/Documentation/2025-10-02-11-51-34.gh-issue-139495.y4Orqf.rst]: Yeah, it's unfortunate that `make patchcheck` actually tells you otherwise sometimes. We ought to improve it but nobody has really time for that (and it kinda duplicates that the CI tells you sometimes...).

**Comment by picnixz** [comment]
cc @cmaloney since you asked on the old PR

**Comment by moreati** [comment]
The label "needs backport to 3.13" is probably applicable, matching #132787

**Comment by picnixz** [comment]
Oh we backported it to 3.13.

**Review by vstinner — APPROVED** [review]
LGTM

**Review by cmaloney — APPROVED** [review]

**Review by gpshead — APPROVED** [review]
