### PR TITLE
gh-130693: Add options of the tkinter.Text.search method: -nolinestop -all -overlap -strictlimits

### LINKED ISSUE #130693: tkinter missing -nolinestop on tk.Text
# Bug report

### Bug description:

```python
# current tkinter/__init__.py

class Text(...):
[...]
    def search(self, pattern, index, stopindex=None,
           forwards=None, backwards=None, exact=None,
           regexp=None, nocase=None, count=None, elide=None):
[...]
```

The current tkinter implementation of the `tkinter.Text.search` method misses use of <a href="https://www.tcl-lang.org/man/tcl8.6/TkCmd/text.htm#M147">tcl options</a>:
-nolinestop
-all
-overlap
-strictlimits

Is there any reason on why it is not inside the CPython implementation?

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

### Linked PRs
* gh-130848
* gh-141669
* gh-141670

### PR DESCRIPTION
**Pull request by sharktide**
Add options -nolinestop, -all, -overlap, and -strictlimits to the search function of the text class of tkinter. 

Fixes #130693 
Closes #130693

Tested against 
```shell
.\PCbuild\amd64\python_d.exe -m test -ugui test_tkinter
```
And test passed. Result:
```shell
0:00:00 [1/1] test_tkinter
0:00:27 load avg: 3.93 [1/1] test_tkinter passed

== Tests result: SUCCESS ==

1 test OK.

Total duration: 27.6 sec
Total tests: run=787 skipped=11
Total test files: run=1/1
Result: SUCCESS
```
Also tested against a custom test file:
[EDITED for change to new search_all method for -all and -overlap]
```
import tkinter as tk

root = tk.Tk()
text = tk.Text(root)
text.pack()

text.insert('1.0', 'This is a test. This is only a test.\nAnother line.\nYet another line.')

# Test without options
result = text.search('test', '1.0', 'end')
print('Without options:', result)

# Test with -nolinestop
result = text.search('line', '1.0', 'end', nolinestop=True, regexp=True)
print('With -nolinestop:', result)

# Test with search_all
result = text.search_all('test', '1.0', 'end')
print('With search_all:', result)

# Test with -overlap
result = text.search_all('test', '1.0', 'end', overlap=True)
print('With -overlap:', result)

# Test with -strictlimits
result = text.search('test', '1.0', 'end', strictlimits=True)
print('With -strictlimits:', result)

root.mainloop()
```

Which returns:

```shell
Without options: 1.10
With -nolinestop: 2.8
With search_all: (<textindex object: '1.10'>, <textindex object: '1.31'>)
With -overlap: (<textindex object: '1.10'>, <textindex object: '1.31'>)
With -strictlimits: 1.10
```

Indicating that the new features are functioning correctly

* Issue: gh-130693

### CODE REVIEW

File: Misc/NEWS.d/next/Library/2025-03-04-17-19-26.gh-issue-130693.Kv01r8.rst [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+Issue: :gh:`130693`
+
+Detailed changes:
+- Enhanced the ``tkinter.Text.search`` method by adding support for the following options:
+  - ``-nolinestop``: Allows searching across lines without stopping.
+  - ``-all``: Finds all matches instead of just the first match.
+  - ``-overlap``: Finds matches that overlap with each other.
+  - ``-strictlimits``: Ensures strict boundaries for the search.
+
+These improvements align the ``tkinter.Text.search`` method with the underlying Tcl/Tk library, providing more flexibility and functionality for users.
```
Comment (Wulian233) [inline Misc/NEWS.d/next/Library/2025-03-04-17-19-26.gh-issue-130693.Kv01r8.rst]: Please delete the first few lines and summarize them in only a few sentences

Comment (sharktide) [reply Misc/NEWS.d/next/Library/2025-03-04-17-19-26.gh-issue-130693.Kv01r8.rst]: ok

Comment (sharktide) [reply Misc/NEWS.d/next/Library/2025-03-04-17-19-26.gh-issue-130693.Kv01r8.rst]: deleted them and modified it to
================
Type: Enhancement
Title: Add support for ``-nolinestop``, ``-all``, ``-overlap``, and ``-strictlimits`` options to ``tkinter.Text.search``
Issue: :gh:`130693`


Added nolinestop, all, overlap, and strictlimits to tkinter.Text.search method

Comment (sharktide) [reply Misc/NEWS.d/next/Library/2025-03-04-17-19-26.gh-issue-130693.Kv01r8.rst]: done

**Comment by sharktide** [comment]
@ZeroIntensity Could someone please review? I think the original reviewer forgot

File: Misc/NEWS.d/next/Library/2025-03-04-17-19-26.gh-issue-130693.Kv01r8.rst [hunk 2]
```diff
@@ -0,0 +1,6 @@
+================
+Type: Enhancement
```
Comment (Wulian233) [inline Misc/NEWS.d/next/Library/2025-03-04-17-19-26.gh-issue-130693.Kv01r8.rst]: Just as I mentioned in my previous comment, we don't need long news entries. Generally, filling in the title of this PR is ok

Comment (sharktide) [reply Misc/NEWS.d/next/Library/2025-03-04-17-19-26.gh-issue-130693.Kv01r8.rst]: @Wulian233 Done! Just left title & metadata:

```rst
================
Type: Enhancement
Title: Add support for ``-nolinestop``, ``-all``, ``-overlap``, and ``-strictlimits`` options to ``tkinter.Text.search``
Issue: :gh:`130693`
```

**Comment by sharktide** [comment]
@Wulian233 Please Review again

**Comment by sharktide** [comment]
I am currently pinging this PR as I have not seen a review in nearly a month. 
Could someone please review?

File: Misc/NEWS.d/next/Library/2025-03-04-17-19-26.gh-issue-130693.Kv01r8.rst (hunk 2 above)
Comment (ZeroIntensity) [reply Misc/NEWS.d/next/Library/2025-03-04-17-19-26.gh-issue-130693.Kv01r8.rst]: We don't need this metadata.

**Comment by sharktide** [comment]
Done!

**Comment by sharktide** [comment]
It has been nearly a month. @ZeroIntensity  Could you please review?

File: Misc/NEWS.d/next/Library/2025-03-04-17-19-26.gh-issue-130693.Kv01r8.rst [hunk 3]
```diff
@@ -0,0 +1,2 @@
+Add support for ``-nolinestop``, ``-all``, ``-overlap``, and ``-strictlimits`` options to ``tkinter.Text.search``
```
Comment (ZeroIntensity) [inline Misc/NEWS.d/next/Library/2025-03-04-17-19-26.gh-issue-130693.Kv01r8.rst]:
```suggestion
Add support for ``-nolinestop``, ``-all``, ``-overlap``, and ``-strictlimits`` options to :meth:`tkinter.Text.search`
```

File: Lib/tkinter/__init__.py [hunk 4]
```diff
@@ -4038,9 +4038,7 @@ def scan_dragto(self, x, y):
         scan_mark."""
         self.tk.call(self._w, 'scan', 'dragto', x, y)
 
-    def search(self, pattern, index, stopindex=None,
-           forwards=None, backwards=None, exact=None,
-           regexp=None, nocase=None, count=None, elide=None):
+    def search(self, pattern, index, stopindex=None, forwards=None, backwards=None, exact=None, regexp=None, nocase=None, count=None, elide=None, nolinestop=None, all=None, overlap=None, strictlimits=None):
```
Comment (ZeroIntensity) [inline Lib/tkinter/__init__.py]: Please change it back to the old formatting.

File: Lib/tkinter/__init__.py [hunk 5]
```diff
@@ -4052,12 +4050,18 @@ def search(self, pattern, index, stopindex=None,
...
+        if overlap: args.append('-overlap')
+        if strictlimits: args.append('-strictlimits')
         if pattern and pattern[0] == '-': args.append('--')
         args.append(pattern)
         args.append(index)
         if stopindex: args.append(stopindex)
         return str(self.tk.call(tuple(args)))
 
+
+
```
Comment (ZeroIntensity) [inline Lib/tkinter/__init__.py]: Stray newline changes:
```suggestion
```

**Review by ZeroIntensity — COMMENTED** [review]
All new features need tests. Please add one to `test_tkinter`.

**Comment by sharktide** [comment]
Will do

**Comment by sharktide** [comment]
I updated the branch as it has been a while since this PR has been opened

File: Misc/NEWS.d/next/Library/2025-03-04-17-19-26.gh-issue-130693.Kv01r8.rst [hunk 6]
```diff
@@ -0,0 +1,2 @@
+Add support for ``-nolinestop``, ``-all``, ``-overlap``, and ``-strictlimits`` options to :meth:`tkinter.Text.search`
+
```
Comment (ZeroIntensity) [inline Misc/NEWS.d/next/Library/2025-03-04-17-19-26.gh-issue-130693.Kv01r8.rst]: Ah, oops, it looks like `tkinter.Text` is undocumented. (That would be good to do in a followup.)
Also, there's another stray newline here:

```suggestion
Add support for ``-nolinestop``, ``-all``, ``-overlap``, and ``-strictlimits`` options to :meth:`!tkinter.Text.search`
```

**Comment by sharktide** [comment]
I’ll make an issue about the docs about tkinter.text later and fix everything else. For now i will not use the :meth: calls until that gets fixed. Will raise another pr for that later.

 It’ll be difficult for me to do this now as I’m going out to a dinner party and will only have my phone. I might try phone coding for the next few hrs though :)

P.S. I’m traveling and visiting family in India. That’s why it’s like night here

**Comment by sharktide** [comment]
Oh yeah and @ZeroIntensity congrats on becoming a core dev (I’ve liked you since the beginning, you are always quick in responding, know the dev guide in and out and I would say more nice things but I’m on an iPhone and my fingers are starting to hurt) I’ve mentioned this in a few places but u definitely deserve it. Maybe in a few years when I become roughly your age I hopefully might become one of ya’ll (assuming I don’t screw up up on the way, which I will)

**Comment by ZeroIntensity** [comment]
Thanks! Shoot for the stars :)

**Comment by sharktide** [comment]
Ready for review

**Comment by sharktide** [comment]
Gentle ping

File: Lib/tkinter/__init__.py [hunk 7]
```diff
@@ -4039,8 +4039,10 @@ def scan_dragto(self, x, y):
         self.tk.call(self._w, 'scan', 'dragto', x, y)
 
     def search(self, pattern, index, stopindex=None,
-           forwards=None, backwards=None, exact=None,
-           regexp=None, nocase=None, count=None, elide=None):
+               forwards=None, backwards=None, exact=None,
+               regexp=None, nocase=None, count=None,
+               elide=None, nolinestop=None, all=None,
+               overlap=None, strictlimits=None):
```
Comment (ZeroIntensity) [inline Lib/tkinter/__init__.py]: Please revert this reformat, let's just add the new arguments in the same style as the original.

**Review by ZeroIntensity — COMMENTED** [review]
I'm not a tkinter expert but I'll do my best to go through this. Conceptually, this makes sense to me.

**Comment by sharktide** [comment]
Thanks :)

**Comment by Wulian233** [comment]
Sorry I can't review it, maybe you can request tkinter expert serhiy-storchaka?

File: Lib/tkinter/__init__.py (hunk 7 above)
Comment (sharktide) [reply Lib/tkinter/__init__.py]: Unintended it 1 level

**Comment by sharktide** [comment]
@serhiy-storchaka I heard that you're a tkinter expert! If you have a little time could you please review this PR? Thanks!

File: Lib/test/test_tkinter/test_text.py [hunk 8]
```diff
@@ -94,6 +94,34 @@ def test_count(self):
         self.assertEqual(text.count('1.3', '1.3', 'update', return_ints=True), 0)
         self.assertEqual(text.count('1.3', '1.3', 'update'), None)
 
+class TextSearchOptionsTest(AbstractTkTest, unittest.TestCase):
```
Comment (Xiaokang2022) [inline Lib/test/test_tkinter/test_text.py]: Maybe this test content is more appropriate to put in the above method `TextTest.test_search`?

Both of these parts are tests for the method `Text.search`, but are split into two parts, and I think it would be better to put them together.

**Review by serhiy-storchaka — COMMENTED** [review]
Please add also an entry in the What's New document. And I concur with @Xiaokang2022, these tests can be merged with the existing test for `search`.

For `-all`, it would be more convenient to return a list or a tuple. And since the type of the result depends on the boolean argument, it would be more Pythonic to add a separate method `search_all()` instead of option`all=True` to `search()`. `overlap` should only be supported in `search_all()`, all other arguments should be supported in both methods.

**Comment by sharktide** [comment]
> Please add also an entry in the What's New document. And I concur with @Xiaokang2022, these tests can be merged with the existing test for search.

Done

> For -all, it would be more convenient to return a list or a tuple. And since the type of the result depends on the boolean argument, it would be more Pythonic to add a separate method search_all() instead of optionall=True to search(). overlap should only be supported in search_all(), all other arguments should be supported in both methods.

Will work on it

**Comment by sharktide** [comment]
I’ll make the what’s new entry after I get the search all function and update the docs too and update the test cases 

EDIT: Current test fails unrelated

**Comment by sharktide** [comment]
Added implementation. Docs, whatsnew, and news updates next

File: Doc/whatsnew/3.15.rst [hunk 9]
```diff
@@ -70,6 +70,22 @@ Summary --- release highlights
 New features
 ============
 
+.. _whatsnew315-tkinter-text:
+
+tkinter.Text
+------------
+
+The ``tkinter.Text.search`` method now supports two additional arguments:
```
Comment (serhiy-storchaka) [inline Doc/whatsnew/3.15.rst]: Please move this to the "Improved modules" section. Add a new subsection for `tkinter`.

File: Doc/whatsnew/3.15.rst [hunk 10]
```diff
@@ -70,6 +70,22 @@ Summary --- release highlights
...
+
+* ``-nolinestop`` — allows the search to continue across line boundaries.
```
Comment (serhiy-storchaka) [inline Doc/whatsnew/3.15.rst]: Do not use non-ASCII dashes. Use `--` or `---`.

File: Lib/tkinter/__init__.py [hunk 11]
```diff
@@ -4038,14 +4038,12 @@ def scan_dragto(self, x, y):
...
-           elide=None, nolinestop=None, all=None,
-           overlap=None, strictlimits=None):
+    def search(self, pattern, index, stopindex=None, *,
+            forwards=None, backwards=None, exact=None,
+            regexp=None, nocase=None, count=None,
+            elide=None, nolinestop=None, strictlimits=None):
         """Search PATTERN beginning from INDEX until STOPINDEX.
-        Return the index of the first character of a match or an
-        empty string."""
+        Return the index of the first character of a match or an empty string."""
```
Comment (serhiy-storchaka) [inline Lib/tkinter/__init__.py]: Was there a reason to change the docstring?

File: Lib/tkinter/__init__.py [hunk 12]
```diff
@@ -4055,15 +4053,43 @@ def search(self, pattern, index, stopindex=None,
...
+        args.append(pattern)
+        args.append(index)
+        if stopindex: args.append(stopindex)
+        result = self.tk.call(tuple(args))
+        if isinstance(result, tuple):
+            return [str(i) for i in result]
+        elif isinstance(result, str):
+            return result.split()
+        else:
+            return []
```
Comment (serhiy-storchaka) [inline Lib/tkinter/__init__.py]: You can use `self._tk.splitlist()`. It works for a tuple, a str and a Tcl_Obj.

File: Lib/tkinter/__init__.py [hunk 13]
```diff
@@ -4038,14 +4038,12 @@ def scan_dragto(self, x, y):
         scan_mark."""
         self.tk.call(self._w, 'scan', 'dragto', x, y)
 
-    def search(self, pattern, index, stopindex=None,
-           forwards=None, backwards=None, exact=None,
-           regexp=None, nocase=None, count=None,
-           elide=None, nolinestop=None, all=None,
-           overlap=None, strictlimits=None):
+    def search(self, pattern, index, stopindex=None, *,
```
Comment (serhiy-storchaka) [inline Lib/tkinter/__init__.py]: Oh, making the parameters keyword-only is a breaking change. I am not against it, but this is a separate issue.

**Review by serhiy-storchaka — COMMENTED** [review]
Thank you for your update.

File: Lib/tkinter/__init__.py (hunk 13 above)
Comment (sharktide) [reply Lib/tkinter/__init__.py]: Yeah I was in a rush so I forgot that it wasn’t keyword only… I fixed that. Personally I don’t see the point of making that breaking change but it could be an interesting thing to discuss

File: Lib/tkinter/__init__.py (hunk 11 above)
Comment (sharktide) [reply Lib/tkinter/__init__.py]: Yes. Tkinter.Text is not documented so I was aiming for a little more clarity for what stopindex , index, and the other params mean

File: Lib/tkinter/__init__.py [hunk 14]
```diff
@@ -4060,7 +4060,7 @@ def search(self, pattern, index, stopindex=None, *,
         if stopindex: args.append(stopindex)
         return str(self.tk.call(tuple(args)))
 
-    def search_all(self, pattern, index, stopindex=None, *,
+    def search_all(self, pattern, index, stopindex=None,
```
Comment (serhiy-storchaka) [inline Lib/tkinter/__init__.py]: You can keep it here, as this is a new method.

Comment (sharktide) [reply Lib/tkinter/__init__.py]: Give me a couple of mins. Working on what's new now

File: Lib/test/test_tkinter/test_text.py [hunk 15]
```diff
@@ -27,20 +27,36 @@ def test_debug(self):
...
+        self.assertEqual(result, '2.8')
+
+        all_res = text.search_all('test', '1.0', 'end')
+        self.assertIsInstance(all_res, list)
+        self.assertGreaterEqual(len(all_res), 2)
+        self.assertTrue(all(isinstance(i, str) for i in all_res))
+
+        overlap_res = text.search_all('test', '1.0', 'end', overlap=True)
+        self.assertIsInstance(overlap_res, list)
+        self.assertGreaterEqual(len(overlap_res), len(all_res))
```
Comment (serhiy-storchaka) [inline Lib/test/test_tkinter/test_text.py]: For `search_all()` you can add a new test method. And repeat tests with other options. But you can also leave it as is, both are fine.

Are all elements always strings? It is fine to keep Tcl_Obj here, as this is a new method. In future we can change Tcl_Obj to more specific type.

File: Lib/tkinter/__init__.py (hunk 11 above)
Comment (serhiy-storchaka) [reply Lib/tkinter/__init__.py]: The only difference here that two short lines are merged in one longer line. It is 70 characters now. `pydoc` adds 12 character indentations for method docstrings, so the total length is slightly longer that 80 characters. There are other long lines here, but this change is a regression without benefit.

Comment (sharktide) [reply Lib/tkinter/__init__.py]: Fixing

File: Lib/test/test_tkinter/test_text.py (hunk 15 above)
Comment (sharktide) [reply Lib/test/test_tkinter/test_text.py]: Search_all is basically search with 2 more options so I lumped the tests together.

> Are all elements always strings? It is fine to keep Tcl_Obj here, as this is a new method. In future we can change Tcl_Obj to more specific type.

Yes, - the Tcl result is split and converted before returning using self._tk.splitlist

Comment (sharktide) [reply Lib/test/test_tkinter/test_text.py]: Refining __init__.py now

File: Doc/whatsnew/3.15.rst [hunk 16]
```diff
@@ -369,6 +355,19 @@ tarfile
   (Contributed by Matt Prodani and Petr Viktorin in :gh:`112887`
   and :cve:`2025-4435`.)
 
+tkinter
+-------
+
+* The ``tkinter.Text.search`` method now supports two additional
+  arguments: ``-nolinestop`` which allows the search to continue across line boundaries;
+  and ``-strictlimits`` which restricts the search to within the specified range.
```
Comment (serhiy-storchaka) [inline Doc/whatsnew/3.15.rst]: If we talk about a Tkinter method instead of a Tcl/Tk command, argument names do not have initial hyphens.

One line also exceeds the recommended limit for rst files.

Comment (sharktide) [reply Doc/whatsnew/3.15.rst]: I'll fix it after the __init__.py
P.S thanks for reviewing :)

File: Lib/test/test_tkinter/test_text.py [hunk 17]
```diff
@@ -27,20 +27,36 @@ def test_debug(self):
...
+            'Another line.\n'
+            'Yet another line.')
+
+        result = text.search('line', '1.0', 'end', nolinestop=True, regexp=True)
+        self.assertEqual(result, '2.8')
+
+        all_res = text.search_all('test', '1.0', 'end')
+        self.assertIsInstance(all_res, list)
+        self.assertGreaterEqual(len(all_res), 2)
+        self.assertTrue(all(isinstance(i, str) for i in all_res))
```
Comment (serhiy-storchaka) [inline Lib/test/test_tkinter/test_text.py]: `self._tk.splitlist()` does not guarantee that items are strings. This is fine, it may be useful in future. But you perhaps cannot test the type here. Instead test the values: `str(all_res[0])` and `str(all_res[1])`.

File: Doc/whatsnew/3.15.rst [hunk 18]
```diff
@@ -354,6 +355,19 @@ tarfile
   (Contributed by Matt Prodani and Petr Viktorin in :gh:`112887`
   and :cve:`2025-4435`.)
 
+tkinter
+-------
+
+* The ``tkinter.Text.search`` method now supports two additional
```
Comment (serhiy-storchaka) [inline Doc/whatsnew/3.15.rst]:
```suggestion
* The :meth:`!tkinter.Text.search` method now supports two additional
```
So it will be formatted with the same font and color as other methods, just without a link.

File: Doc/whatsnew/3.15.rst [hunk 19]
```diff
@@ -354,6 +355,19 @@ tarfile
...
+  arguments: ``nolinestop`` which allows the search to
+  continue across line boundaries;
+  and ``strictlimits`` which restricts the search to within the specified range.
```
Comment (serhiy-storchaka) [inline Doc/whatsnew/3.15.rst]:
```suggestion
  arguments: *nolinestop* which allows the search to
  continue across line boundaries;
  and *strictlimits* which restricts the search to within the specified range.
```
Such formatting is usually used for parameters.

File: Doc/whatsnew/3.15.rst [hunk 20]
```diff
@@ -354,6 +355,19 @@ tarfile
...
+  (Contributed by Rihaan Meher in :gh:`130848`)
+
+* A new method ``tkinter.Text.search_all`` has been introduced.
```
Comment (serhiy-storchaka) [inline Doc/whatsnew/3.15.rst]:
```suggestion
* A new method :meth:`!tkinter.Text.search_all` has been introduced.
```

File: Doc/whatsnew/3.15.rst [hunk 21]
```diff
@@ -70,6 +70,8 @@ Summary --- release highlights
 New features
 ============
 
+.. tkinter.Text is not currently documented - being tracked in :gh:``135658``
+
 .. _whatsnew315-sampling-profiler:
```
Comment (serhiy-storchaka) [inline Doc/whatsnew/3.15.rst]:
```suggestion
.. _whatsnew315-sampling-profiler:
```
This is not related.

File: Lib/test/test_tkinter/test_text.py [hunk 22]
```diff
@@ -27,20 +27,38 @@ def test_debug(self):
     def test_search(self):
         text = self.text
 
-        # pattern and index are obligatory arguments.
```
Comment (serhiy-storchaka) [inline Lib/test/test_tkinter/test_text.py:30]: Restore all these comments.

File: Lib/test/test_tkinter/test_text.py [hunk 23]
```diff
@@ -27,20 +27,38 @@ def test_debug(self):
...
+        self.assertEqual(result, '2.8')
+
+        all_res = text.search_all('test', '1.0', 'end')
+        self.assertIsInstance(all_res, tuple)
+        self.assertGreaterEqual(len(all_res), 2)
+        self.assertEqual(str(all_res[0]), '1.10')
+        self.assertEqual(str(all_res[1]), '2.8')
+
+
+        overlap_res = text.search_all('test', '1.0', 'end', overlap=True)
```
Comment (serhiy-storchaka) [inline Lib/test/test_tkinter/test_text.py]: For testing `overlap`, please use a pattern that produces overlapping substrings. Test with and without `overlap=True` to show that this affects the result.

I think that it is better to extract the `search_all()` tests into a separate method -- anyway they search in a different text.

File: Lib/tkinter/__init__.py [hunk 24]
```diff
@@ -4052,12 +4053,39 @@ def search(self, pattern, index, stopindex=None,
...
         if stopindex: args.append(stopindex)
         return str(self.tk.call(tuple(args)))
 
+    def search_all(self, pattern, index, stopindex=None, *,
+            forwards=None, backwards=None, exact=None,
+            regexp=None, nocase=None, count=None,
+            elide=None, nolinestop=None, overlap=None,
+            strictlimits=None):
+        """Search all occurrences of PATTERN from INDEX to STOPINDEX.
+        Return a list of indices where matches begin."""
```
Comment (serhiy-storchaka) [inline Lib/tkinter/__init__.py]:
```suggestion
        Return a tuple of indices where matches begin."""
```

File: Misc/NEWS.d/next/Library/2025-03-04-17-19-26.gh-issue-130693.Kv01r8.rst [hunk 25]
```diff
@@ -0,0 +1 @@
+Add support for ``-nolinestop``, and ``-strictlimits`` options to ``!tkinter.Text.search``. Also add the ``tkinter.Text.search_all`` method for ``-all`` and ``overlap`` options
```
Comment (serhiy-storchaka) [inline Misc/NEWS.d/next/Library/2025-03-04-17-19-26.gh-issue-130693.Kv01r8.rst]:
```suggestion
Add support for ``-nolinestop``, and ``-strictlimits`` options to :meth:`!tkinter.Text.search`. Also add the :meth:`tkinter.Text.search_all` method for ``-all`` and ``-overlap`` options.

```

**Comment by sharktide** [comment]
Gentle ping

File: Doc/whatsnew/3.15.rst [hunk 26]
```diff
@@ -207,7 +208,6 @@ Improved error messages
               ^^^^^^^^^^^^^^
      AttributeError: 'Container' object has no attribute 'area'. Did you mean: 'inner.area'?
 
-
```
Comment (serhiy-storchaka) [inline Doc/whatsnew/3.15.rst:231]: Unrelated change.

File: Lib/test/test_tkinter/test_text.py [hunk 27]
```diff
@@ -41,6 +41,47 @@ def test_search(self):
         self.assertEqual(text.search('-test', '1.0', 'end'), '1.2')
         self.assertEqual(text.search('test', '1.0', 'end'), '1.3')
 
+        text.delete('1.0', 'end')
+        text.insert('1.0',
+            'This is a test. This is only a test.\n'
+            'Another line.\n'
+            'Yet another line.')
+
+        result = text.search('line', '1.0', 'end', nolinestop=True, regexp=True)
```
Comment (serhiy-storchaka) [inline Lib/test/test_tkinter/test_text.py]: Why `regexp=True` if it is not a regexp?

It would be nice for each option to call `search()` with the same arguments, but with and without that option (the results should be different). So we will see that it works.

File: Lib/test/test_tkinter/test_text.py [hunk 28]
```diff
@@ -41,6 +41,47 @@ def test_search(self):
...
+
+        # Check that overlap actually finds overlapping matches
+        self.assertIn('2.0', overlap_res_strs)
+        self.assertIn('2.2', overlap_res_strs)
+        self.assertIn('2.4', overlap_res_strs)
+        self.assertNotIn('2.2', all_res_strs)
+
+        # Ensure all results are valid text indices
+        for i in overlap_res:
+            self.assertRegex(str(i), r'^\d+\.\d+$')
```
Comment (serhiy-storchaka) [inline Lib/test/test_tkinter/test_text.py]: Can't we simply test `self.assertEqual(overlap_res_strs, ['1.0', '1.2', ...])`? And the same for non-overlapped search. The example should perhaps be smaller.

File: Doc/whatsnew/3.15.rst [hunk 29]
```diff
@@ -168,6 +168,7 @@ production systems where traditional profiling approaches would be too intrusive
 
 (Contributed by Pablo Galindo and László Kiss Kollár in :gh:`135953`.)
 
+=======
```
Comment (serhiy-storchaka) [inline Doc/whatsnew/3.15.rst]: Unrelated change.

**Comment by sharktide** [comment]
@serhiy-storchaka Ready for review

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution, @sharktide. I rewrote the tests, so they clearly test the new options, and added many tests for already supported options. These tests will be backported.
