### PR TITLE
gh-89973: Fix re.error in the fnmatch module.

### LINKED ISSUE #89973: Document exceptions raised by fnmtach
BPO | [45815](https://bugs.python.org/issue45815)
--- | :---
Nosy | @ezio-melotti, @DimitriPapadopoulos
Files | <li>[sre_constants.error_stderr.txt](https://bugs.python.org/file50442/sre_constants.error_stderr.txt "Uploaded as text/plain at 2021-11-16.10:46:44 by @DimitriPapadopoulos"): Last part of the stderr output of a Python script that calls fnmatch() on a bad glob</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-11-16.10:46:44.748>
labels = ['expert-regex', '3.11', 'library', 'docs']
title = 'Document exceptions raised by fnmtach'
updated_at = <Date 2021-11-16.10:46:44.748>
user = 'https://github.com/DimitriPapadopoulos'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-16.10:46:44.748>
actor = 'DimitriPapadopoulosOrfanos'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'Library (Lib)', 'Regular Expressions']
creation = <Date 2021-11-16.10:46:44.748>
creator = 'DimitriPapadopoulosOrfanos'
dependencies = []
files = ['50442']
hgrepos = []
issue_num = 45815
keywords = []
message_count = 1.0
messages = ['406396']
nosy_count = 4.0
nosy_names = ['ezio.melotti', 'mrabarnett', 'docs@python', 'DimitriPapadopoulosOrfanos']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue45815'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-139405

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
Character ranges with upper bound less that lower bound are now
interpreted as empty ranges, for compatibility with other glob
pattern implementations. Previously it was re.error.

Closes #89973.

### CODE REVIEW

File: Misc/NEWS.d/next/Library/2022-05-22-16-08-01.gh-issue-89973.jc-Q4g.rst [hunk 1]
```diff
@@ -0,0 +1,3 @@
+Fix :exc:`re.error` raised in :mod:`fnmatch` if the patterna contains
+character range with upeer bound lower than lower bound (e.g. ``[c-a]``).
```
Comment (hauntsaninja) [inline Misc/NEWS.d/next/Library/2022-05-22-16-08-01.gh-issue-89973.jc-Q4g.rst]:
```suggestion
Fix :exc:`re.error` raised in :mod:`fnmatch` if the pattern contains a
character range with upper bound lower than lower bound (e.g. ``[c-a]``).
```

**Comment by serhiy-storchaka** [comment]
Thanks @hauntsaninja!
