### PR TITLE
gh-137884: Added threading.get_native_id on Illumos/Solaris

### LINKED ISSUE #137884: Illumos and Solaris Thread Native ID
# Feature or enhancement

### Proposal:

Currently, Illumos and Solaris 11 ports of Python doesn't have `threading.get_native_id`:
~~~
$ uname -a
SunOS omnios 5.11 omnios-r151054-180b86b9dd i86pc i386 i86pc
$ python3 --version
Python 3.13.3
$ python3 -c "import threading; print(threading.get_native_id())"                  
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import threading; print(threading.get_native_id())
                            ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'threading' has no attribute 'get_native_id'
~~~

If that's OK, I'll submit a PR that enables `threading.get_native_id` on Illumos distributions and Solaris 11.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Links to previous discussion of this feature:

_No response_

### Linked PRs
* gh-137927

### PR DESCRIPTION
**Pull request by yuce**
Fixes: #137884 

This PR enables `threading.get_native_id` on Illumos distributions and Solaris.

Illumos/Solaris defines the `thr_self` function which returns the thread ID, unique for the process:
https://docs.oracle.com/cd/E36784_01/html/E36874/thr-self-3c.html
On OmniOS and Solaris, `thr_self` returns the thread IDs from 1, incrementing it for each thread.
Since it is not unique in the system, it is not usable by itself per Python doc:
https://docs.python.org/3/library/threading.html#threading.get_native_id

> get_native_id() -> integer
>    Return a non-negative integer identifying the thread as reported
>   by the OS (kernel). This may be used to uniquely identify a
>   particular thread within a system.

In order to make it unique within the system, I put the PID from `getpid` in the higher 4 bytes, and thread ID from `thr_self` in the lower 4 bytes of the returned `unsigned long`.

`getpid` doesn't return an error value, and it returns `pid_t` which is 4 bytes (`int`) on Illumos/Solaris:
https://docs.oracle.com/cd/E23824_01/html/821-1463/getpid-2.html

`thr_self` doesn't return an error value, and it returns `thread_t` which is 4 bytes (`unsigned int`) on Illumos/Solaris:
https://docs.oracle.com/cd/E36784_01/html/E36874/thr-self-3c.html

With the changes in this PR, `test_native_id_after_fork` in `Lib/test/test_threading.py` passes, which was skipped before.
This PR does not introduce any new test faliures.

* Issue: gh-137884

### CODE REVIEW

File: Python/thread_pthread.h [hunk 1]
```diff
@@ -30,6 +30,8 @@
 #   include <lwp.h>             /* _lwp_self() */
 #elif defined(__DragonFly__)
 #   include <sys/lwp.h>         /* lwp_gettid() */
+#elif defined(__sun__)
+ #   include <thread.h>
```
Comment (serhiy-storchaka) [inline Python/thread_pthread.h]:
```suggestion
#   include <thread.h>
```

File: Doc/library/_thread.rst [hunk 2]
```diff
@@ -120,13 +120,15 @@ This module defines the following constants and functions:
...
-   .. availability:: Windows, FreeBSD, Linux, macOS, OpenBSD, NetBSD, AIX, DragonFlyBSD, GNU/kFreeBSD.
+   .. availability:: Windows, FreeBSD, Linux, macOS, OpenBSD, NetBSD, AIX, DragonFlyBSD, GNU/kFreeBSD, Solaris.
 
    .. versionadded:: 3.8
 
    .. versionchanged:: 3.13
       Added support for GNU/kFreeBSD.
 
+   .. versionchanged:: 3.15
+      Added support for Solaris.
```
Comment (serhiy-storchaka) [inline Doc/library/_thread.rst:131]:
```suggestion
      Added support for Solaris.

```

File: Doc/library/_thread.rst [hunk 3]
```diff
@@ -120,13 +120,15 @@ This module defines the following constants and functions:
...
 
-   .. availability:: Windows, FreeBSD, Linux, macOS, OpenBSD, NetBSD, AIX, DragonFlyBSD, GNU/kFreeBSD.
+   .. availability:: Windows, FreeBSD, Linux, macOS, OpenBSD, NetBSD, AIX, DragonFlyBSD, GNU/kFreeBSD, Solaris.
 
    .. versionadded:: 3.8
 
    .. versionchanged:: 3.13
       Added support for GNU/kFreeBSD.
 
+   .. versionchanged:: 3.15
```
Comment (furkanonder) [inline Doc/library/_thread.rst]:
```suggestion
   .. versionchanged:: next
```

File: Doc/library/threading.rst [hunk 4]
```diff
@@ -191,13 +191,16 @@ This module defines the following functions:
...
 
-   .. availability:: Windows, FreeBSD, Linux, macOS, OpenBSD, NetBSD, AIX, DragonFlyBSD, GNU/kFreeBSD.
+   .. availability:: Windows, FreeBSD, Linux, macOS, OpenBSD, NetBSD, AIX, DragonFlyBSD, GNU/kFreeBSD, Solaris.
 
    .. versionadded:: 3.8
 
    .. versionchanged:: 3.13
       Added support for GNU/kFreeBSD.
 
+   .. versionchanged:: 3.15
```
Comment (furkanonder) [inline Doc/library/threading.rst]:
```suggestion
   .. versionchanged:: next
```

**Review by auvipy — COMMENTED** [review]
shouldn't we also try extra test for this the change?

File: Python/thread_pthread.h [hunk 5]
```diff
@@ -399,6 +401,8 @@ PyThread_get_thread_native_id(void)
 #elif defined(__DragonFly__)
     lwpid_t native_id;
     native_id = lwp_gettid();
+#elif defined(__sun__)
+    unsigned long native_id = (unsigned long)getpid() << 32 | thr_self();
```
Comment (serhiy-storchaka) [inline Python/thread_pthread.h:405]: Why is this? How does it work on 32-bit Solaris?

Comment (serhiy-storchaka) [reply Python/thread_pthread.h:405]: Well, I see now your explanation, but do 32-bit Solaris or Illumos exist?

Comment (yuce) [reply Python/thread_pthread.h:405]: Illumos doesn't have a 32-bit kernel build since 2018:
* https://www.illumos.org/issues/8685
* http://www.tribblix.org/32bit.html

It seems there's no support for 32bit hardware on Solaris 11, but I couldn't find the release which removed that:
* https://en.wikipedia.org/wiki/Oracle_Solaris

Solaris 11.4 (first release in 2018) includes Python 3.4 in its package repository, and it is 64bits.
~~~
$ uname -a
SunOS solaris 5.11 11.4.0.15.0 i86pc i386 i86pc
$ file `which python3`  
/usr/bin/python3:       ELF 64-bit LSB executable AMD64 Version 1 [SSE], dynamically linked, not stripped
~~~

**Comment by yuce** [comment]
@auvipy 

> shouldn't we also try extra test for this the change?

Could you explain that a bit?
Do you have a specific test in mind?

File: Python/thread_pthread.h (hunk 5 above)
Comment (serhiy-storchaka) [reply Python/thread_pthread.h:405]: Just in case, let's disable this on 32-bit. For example, using `defined(__sun__) && SIZEOF_LONG > 4`.

Comment (yuce) [reply Python/thread_pthread.h:405]: That makes sense. Addressed at https://github.com/python/cpython/pull/137927/commits/8c1140916fbb1e07389d5ee7d06f15b24f7bbb9a

Comment (serhiy-storchaka) [reply Python/thread_pthread.h:405]: You need to add the conditions also in other places.

Comment (yuce) [reply Python/thread_pthread.h:405]: Updated at: https://github.com/python/cpython/pull/137927/commits/e2f9c41905d629206bd3366fbaa25d86d6663abc

**Review by serhiy-storchaka — APPROVED** [review]
LGTM. :+1:

**Comment by ZeroIntensity** [comment]
> shouldn't we also try extra test for this the change?

`test_threading` *already* tests for this. The tests for `threading.get_native_id` are protected by a `hasattr`, so if a new system gets support for it, that `hasattr` now passes and runs the test.

Unfortunately, we don't have any working Solaris buildbots to confirm that those tests actually pass now.

File: Include/pythread.h [hunk 6]
```diff
@@ -42,7 +42,8 @@ PyAPI_FUNC(unsigned long) PyThread_get_thread_ident(void);
 #if (defined(__APPLE__) || defined(__linux__) || defined(_WIN32) \
      || defined(__FreeBSD__) || defined(__FreeBSD_kernel__) \
      || defined(__OpenBSD__) || defined(__NetBSD__) \
-     || defined(__DragonFly__) || defined(_AIX))
+     || defined(__DragonFly__) || defined(_AIX)) \
+     || defined(__sun__) && SIZEOF_LONG >= 8
```
Comment (picnixz) [inline Include/pythread.h]:
```suggestion
     || defined(__DragonFly__) || defined(_AIX) \
     || (defined(__sun__) && SIZEOF_LONG >= 8))
```

Let's put it inside the group

File: Doc/library/threading.rst [hunk 7]
```diff
@@ -191,13 +191,16 @@ This module defines the following functions:
...
-   .. availability:: Windows, FreeBSD, Linux, macOS, OpenBSD, NetBSD, AIX, DragonFlyBSD, GNU/kFreeBSD.
+   .. availability:: Windows, FreeBSD, Linux, macOS, OpenBSD, NetBSD, AIX, DragonFlyBSD, GNU/kFreeBSD, Solaris.
 
    .. versionadded:: 3.8
 
    .. versionchanged:: 3.13
       Added support for GNU/kFreeBSD.
 
+   .. versionchanged:: next
+      Added support for Solaris.
```
Comment (picnixz) [inline Doc/library/threading.rst:202]: Should we mention that it's only Solaris 64-bit?

Comment (serhiy-storchaka) [reply Doc/library/threading.rst:202]: When we get a report that it doesn't work on 32-bit Solaris.

For other users this is just a noise.

**Comment by serhiy-storchaka** [comment]
I tested on OpenIndiana.
