### PR TITLE
gh-117901: Add option for compiler's codegen to save nested instruction sequences for introspection

### LINKED ISSUE #117901: _PyCompile_CodeGen compiles nested function all the way to code object
# Bug report

The ``_PyCompile_CodeGen`` test utility is supposed to run only codegen and return an instruction sequence. However, it compiles nested functions all the way to code object. Need to teach it how to return the instruction sequence for the nested function.

### Linked PRs
* gh-118007

### PR DESCRIPTION
**Pull request by iritkatriel**
Fixed #117901.

* Issue: gh-117901

### CODE REVIEW

File: Python/compile.c [hunk 1]
```diff
@@ -285,6 +285,10 @@ struct compiler {
     struct compiler_unit *u;     /* compiler state for current block */
     PyObject *c_stack;           /* Python list holding compiler_unit ptrs */
     PyArena *c_arena;            /* pointer to memory allocation arena */
+
+    bool c_save_nested_seqs;     /* if true, construct recusrsive instruction sequences
```
Comment (carljm) [inline Python/compile.c]:
```suggestion
    bool c_save_nested_seqs;     /* if true, construct recursive instruction sequences
```

**Review by carljm — APPROVED** [review]
