### PR TITLE
gh-115323: Add meaningful error message for using bytearray.extend with str

### LINKED ISSUE #115323: bytearray.extend: Misleading error message
### Bug description:

```python
b=bytearray(b"abc")
b.extend('def')
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'str' object cannot be interpreted as an integer```
```
… except that `bytes.extend` doesn't even accept integers as arguments; the error refers to the first element of the string, which happens also to be a string in Python. Meh.

Could CPython please complain about requiring the string to be encoded instead?

### CPython versions tested on:

main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-115332
* gh-115894
* gh-115895

### PR DESCRIPTION
**Pull request by jayasting98**
Fixes #115323

- Check if the iterable is an instance of `str`
- Raise a TypeError when the iterable is an instance of `str`, with a more meaningful error message that says the string should be encoded

* Issue: gh-115323

### CODE REVIEW

File: Objects/bytearrayobject.c [hunk 1]
```diff
@@ -1695,6 +1695,13 @@ bytearray_extend(PyByteArrayObject *self, PyObject *iterable_of_ints)
     int value;
     char *buf;
 
+    if (PyUnicode_Check(iterable_of_ints)) {
```
Comment (eendebakpt) [inline Objects/bytearrayobject.c]: This check is in the fast path and `PyUnicode_Check` checks for subtypes. Does it slow down the normal case?

Comment (jayasting98) [reply Objects/bytearrayobject.c]: Would you prefer that I move it into the `_getbytevalue` guard clause in the while loop further down? This way, the check is only done if something actually goes wrong.

**Review by eendebakpt — APPROVED** [review]

File: Objects/bytearrayobject.c [hunk 2]
```diff
@@ -1729,6 +1729,11 @@ bytearray_extend(PyByteArrayObject *self, PyObject *iterable_of_ints)
 
     while ((item = PyIter_Next(it)) != NULL) {
         if (! _getbytevalue(item, &value)) {
+            if (PyErr_ExceptionMatches(PyExc_TypeError) && PyUnicode_Check(iterable_of_ints)) {
```
Comment (terryjreedy) [inline Objects/bytearrayobject.c:1732]: The "can't extend" message (see issue) is created on line 709-11.  I expected the "cannot interpret at integer" message here, but cannot find it in the extend code.

File: Objects/bytearrayobject.c [hunk 3]
```diff
@@ -1729,6 +1729,11 @@ bytearray_extend(PyByteArrayObject *self, PyObject *iterable_of_ints)
...
+                PyErr_Format(PyExc_TypeError,
+                             "'%.100s' object should be encoded",
+                             Py_TYPE(iterable_of_ints)->tp_name);
```
Comment (terryjreedy) [inline Objects/bytearrayobject.c]: If one passes a string literal, one should just add the `b` prefix insteand of `.encode()`.

```suggestion
                             "str object should be bytes");
```
The message is the point of his suggestion.  I am presuming that a dummy arg for the constant string is not needed.  In any case, bytes are not, in general, encoded text, although attempting to pass a str is likely to indicate that as the intended interpretation.  A bytearray would also be OK, but anyone using one would likely know that.

**Review by terryjreedy — DISMISSED** [review]

File: Objects/bytearrayobject.c (hunk 3 above)
Comment (smurfix) [reply Objects/bytearrayobject.c]: Maybe quote typenames?

File: Objects/bytearrayobject.c (hunk 1 above)
Comment (smurfix) [reply Objects/bytearrayobject.c]: Moving the test makes sense.

File: Objects/bytearrayobject.c (hunk 2 above)
Comment (jayasting98) [reply Objects/bytearrayobject.c:1732]: If I'm not wrong, lines 1709-1711 do not seem to be code relevant to the issue. The `TypeError` with the message "object cannot be interpreted as an integer" message is raised deeper in the call stack of the call to `_getbytevalue`. The `TypeError` is raised in `_PyNumber_Index`.

`_getbytevalue` from `Objects/bytearrayobject.c` calls `PyLong_AsLongAndOverflow` from `Objects/longobject.c`, which calls `_PyNumber_Index` from `Objects/abstract.c`.

I'm still new to this though, so feel free to correct me.

Comment (smurfix) [reply Objects/bytearrayobject.c:1732]: IMHO it doesn't particularly matter where the error is generated. You can check the condition (and replace the error message) one or five levels above it, nobody cares. As long as you don't leak memory, that is. ;.)

Comment (jayasting98) [reply Objects/bytearrayobject.c:1732]: Okay. Maybe I'll just leave it where it is right now then.

**Comment by jayasting98** [comment]
I have made the requested changes; please review again

File: Lib/test/test_bytes.py [hunk 4]
```diff
@@ -1599,6 +1599,8 @@ def test_extend(self):
         a = bytearray(b'')
         a.extend([Indexable(ord('a'))])
         self.assertEqual(a, b'a')
+        a = bytearray(b'abc')
+        self.assertRaises(TypeError, a.extend, 'def', msg="'str' object should be 'bytes'")
```
Comment (sobolevn) [inline Lib/test/test_bytes.py]: `str` objects should never be `bytes` :)

I propose this wording instead: `Expected ...; got: str`

File: Objects/bytearrayobject.c [hunk 5]
```diff
@@ -1729,6 +1729,10 @@ bytearray_extend(PyByteArrayObject *self, PyObject *iterable_of_ints)
 
     while ((item = PyIter_Next(it)) != NULL) {
         if (! _getbytevalue(item, &value)) {
+            if (PyErr_ExceptionMatches(PyExc_TypeError) && PyUnicode_Check(iterable_of_ints)) {
+                PyErr_Format(PyExc_TypeError,
```
Comment (sobolevn) [inline Objects/bytearrayobject.c:1733]: It is not just `bytes`, any iterable of `int`-like is fine:

```python
>>> a = bytearray(b'')
>>> a.extend([1, 2, 3])
>>> a
bytearray(b'\x01\x02\x03')
```

Typeshed's definition: https://github.com/python/typeshed/blob/a3d356c04c15afc22b254afae2e6e7adbbe031a5/stdlib/builtins.pyi#L726

Comment (jayasting98) [reply Objects/bytearrayobject.c:1733]: That's true, I forgot; it's also even written as the parameter name for `bytearray_extend` in `bytearrayobject.c`. :sweat_smile:

```
static PyObject *
bytearray_extend(PyByteArrayObject *self, PyObject *iterable_of_ints)
```

However, is this clear for users? It's not just `int` but integers in general (including bytes). Maybe `Expected iterable of integers; got: 'str'`? Or is iterable of `int` sufficient?

Comment (sobolevn) [reply Objects/bytearrayobject.c:1733]: `int`-like maybe? 🤔 
I propose searching through existing code for similar types to make it consistent.

Comment (jayasting98) [reply Objects/bytearrayobject.c:1733]: >`int`-like

I prefer this actually. However, I do not find any error messages in the repo containing something similar; I can only find documentation (and not many). I searched for int-like, 'int'-like, or integer-like through VS Code.

There are a lot of mentions for integer though. I guess I will just stick to integer then. Anyway, I think it matches the original error message. `TypeError: 'str' object cannot be interpreted as an integer`. It was not completely wrong; it was just not very clear.

Unless you still prefer `int`-like, which I don't mind since I also prefer it. 😄

Comment (terryjreedy) [reply Objects/bytearrayobject.c:1733]: Before saying 'integers' perhaps a subclass Int of int should be tested.  In the example above, `a.extend([Int(1), Int(2)])`.  The ints are required to be in range 0-255, but we do not do value typing.  I believe an int out of that range gets a separate message.

Comment (jayasting98) [reply Objects/bytearrayobject.c:1733]: This is also true. But I'm not really sure what a good catch-all term is. If we say bytes or 8-bit integers, people may think `int` cannot be used. And like you said, integer isn't completely correct.

Unless we spell it all out, and say something like `Expected iterable of integers (each from 0 to 255); got: 'str'`. However, it won't be very concise. I guess it's more clear though, and maybe clarity is more important.

Another possibility is to just leave it as it is right now, but give another error message that mentions they each need to be between 0 and 255 if the integers given are out of that range. I'm not sure if this already happens. I will check when I am able to continue working on this again.

Comment (jayasting98) [reply Objects/bytearrayobject.c:1733]: @terryjreedy Yea, it does already raise an error: `ValueError: byte must be in range(0, 256)`. This can be found in the function `_getbytevalue`. This is also already tested in the function `test_extend` of the class `test.test_bytes.ByteArrayTest` from `Lib/test/test_bytes.py`. Would this be sufficient?

Comment (jayasting98) [reply Objects/bytearrayobject.c:1733]: @sobolevn @terryjreedy Hi, may I ask if there are any other concerns you have about this? Feel free to let me know if there is anything you would still like me to change.

File: Lib/test/test_bytes.py (hunk 4 above)
Comment (terryjreedy) [reply Lib/test/test_bytes.py]: Changed to 'Expected iterable of integers; got: str'.  I assume that this statisfies the request.

File: Objects/bytearrayobject.c (hunk 5 above)
Comment (terryjreedy) [reply Objects/bytearrayobject.c:1733]: My remaining concern is elsewhere.

File: Objects/bytearrayobject.c (hunk 1 above)
Comment (terryjreedy) [reply Objects/bytearrayobject.c]: done

File: Objects/bytearrayobject.c (hunk 3 above)
Comment (terryjreedy) [reply Objects/bytearrayobject.c]: A different wording was chosen.

File: Lib/test/test_bytes.py [hunk 6]
```diff
@@ -1599,6 +1599,8 @@ def test_extend(self):
         a = bytearray(b'')
         a.extend([Indexable(ord('a'))])
         self.assertEqual(a, b'a')
+        a = bytearray(b'abc')
+        self.assertRaises(TypeError, a.extend, 'def', msg="Expected iterable of integers; got: 'str'")
```
Comment (terryjreedy) [inline Lib/test/test_bytes.py]: `msg` args are for display when a test fails, not part of the test*
```suggestion
        self.assertRaises(TypeError,
                          "Expected iterable of integers; got: 'str'",
                          a.extend, 'def')
```

File: Lib/test/test_bytes.py [hunk 7]
```diff
@@ -1599,6 +1599,10 @@ def test_extend(self):
         a = bytearray(b'')
         a.extend([Indexable(ord('a'))])
         self.assertEqual(a, b'a')
+        a = bytearray(b'abc')
+        self.assertRaises(TypeError,
+                          "Expected iterable of integers; got: 'str'",
+                          a.extend, 'def')
```
Comment (terryjreedy) [inline Lib/test/test_bytes.py]:
```suggestion
        self.assertRaisesRegex(TypeError,
                              "Expected iterable of integers; got: 'str'",
                              a.extend, 'def')
```

File: Lib/test/test_bytes.py (hunk 6 above)
Comment (terryjreedy) [reply Lib/test/test_bytes.py]: needs more

File: Lib/test/test_bytes.py [hunk 8]
```diff
@@ -1599,6 +1599,10 @@ def test_extend(self):
         a = bytearray(b'')
         a.extend([Indexable(ord('a'))])
         self.assertEqual(a, b'a')
+        a = bytearray(b'abc')
+        self.assertRaisesRegex(TypeError,
+                              "Expected iterable of integers; got: 'str'",
+                              a.extend, 'def')
```
Comment (terryjreedy) [inline Lib/test/test_bytes.py]:
```suggestion
        self.assertRaisesRegex(TypeError,
                               "Expected iterable of integers; got: 'str'",
                               a.extend, 'def')
```

**Comment by terryjreedy** [comment]
@sobolevn Ok to merge?

File: Lib/test/test_bytes.py (hunk 6 above)
Comment (jayasting98) [reply Lib/test/test_bytes.py]: Oops. Thanks for catching that. I think I need to change this in another PR as well.

File: Lib/test/test_bytes.py [hunk 9]
```diff
@@ -1599,6 +1599,10 @@ def test_extend(self):
         a = bytearray(b'')
         a.extend([Indexable(ord('a'))])
         self.assertEqual(a, b'a')
+        a = bytearray(b'abc')
+        self.assertRaisesRegex(TypeError,
+                               "Expected iterable of integers; got: 'str'",
+                               a.extend, 'def')
```
Comment (terryjreedy) [inline Lib/test/test_bytes.py]: I decided to add assertion that do not always override TypeError.
Also, messages begin with lowercase (I checked several others, including [].extend)
since printed after uppercase exception class.
```suggestion
        self.assertRaisesRegex(TypeError,  # Override for string.
                               "expected iterable of integers; got: 'str'",
                               a.extend, 'def')
        self.assertRaisesRegex(TypeError,  # But not for others.
                               "can't extend bytearray with float",
                               a.extend, 1.0)
```

File: Objects/bytearrayobject.c [hunk 10]
```diff
@@ -1729,6 +1729,10 @@ bytearray_extend(PyByteArrayObject *self, PyObject *iterable_of_ints)
...
+                             "Expected iterable of integers; got: 'str'");
```
Comment (terryjreedy) [inline Objects/bytearrayobject.c]:
```suggestion
                             "expected iterable of integers; got: 'str'");
```
