### PR TITLE
gh-110309: prune empty constant in format specs

### LINKED ISSUE #110309: empty string constant in f-string format_spec
# Bug report

### Bug description:

The f-string `f'{1:{name}}'` has a extra `Constant(value='')` in the format_spec part in 3.12, which is not part of the AST in 3.11. This has also an effect on the generated bytecode.
    
```python
import ast
import dis

print(ast.dump(ast.parse("f'{1:{name}}'"),indent=2))

dis.dis(compile("f'{1:{name}}'","<string>","exec"))
```

output (Python 3.12.0):
```python
Module(
  body=[
    Expr(
      value=JoinedStr(
        values=[
          FormattedValue(
            value=Constant(value=1),
            conversion=-1,
            format_spec=JoinedStr(
              values=[
                FormattedValue(
                  value=Name(id='name', ctx=Load()),
                  conversion=-1),
                Constant(value='')]))]))],            # <-- extra Constant
  type_ignores=[])
  0           0 RESUME                   0

  1           2 LOAD_CONST               0 (1)
              4 LOAD_NAME                0 (name)
              6 FORMAT_VALUE             0
              8 LOAD_CONST               1 ('')        # <-- extra LOAD_CONST
             10 BUILD_STRING             2             # <-- extra BUILD_STRING
             12 FORMAT_VALUE             4 (with format)
             14 POP_TOP
             16 RETURN_CONST             2 (None)
```

output (Python 3.11.3):
```python
Module(
  body=[
    Expr(
      value=JoinedStr(
        values=[
          FormattedValue(
            value=Constant(value=1),
            conversion=-1,
            format_spec=JoinedStr(
              values=[
                FormattedValue(
                  value=Name(id='name', ctx=Load()),
                  conversion=-1)]))]))],
  type_ignores=[])
  0           0 RESUME                   0

  1           2 LOAD_CONST               0 (1)
              4 LOAD_NAME                0 (name)
              6 FORMAT_VALUE             0
              8 FORMAT_VALUE             4 (with format)
             10 POP_TOP
             12 LOAD_CONST               1 (None)
             14 RETURN_VALUE
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-110320

### PR DESCRIPTION
**Pull request by sunmy2019**
close #110309 

* Issue: gh-110309

### CODE REVIEW

File: Parser/action_helpers.c [hunk 1]
```diff
@@ -998,18 +998,38 @@ _PyPegen_setup_full_format_spec(Parser *p, Token *colon, asdl_expr_seq *spec, in
...
+    // This is needed to keep compatibility with 3.11, where an empty format
+    // spec is parsed as an *empty* JoinedStr node, instead of having an empty
+    // constant in it.
+    Py_ssize_t n_items = asdl_seq_LEN(spec);
+    asdl_expr_seq *seq = _Py_asdl_expr_seq_new(n_items, p->arena);
+    if (seq == NULL) {
+        return NULL;
+    }
+    Py_ssize_t index = 0;
+    for (Py_ssize_t i = 0; i < n_items; i++) {
```
Comment (pablogsal) [inline Parser/action_helpers.c:1006]: I think it would be cleaner (and anecdotally faster) to do one pass first to count the elements (no allocations), allocate just once and then do a second pass setting the elements

Comment (sunmy2019) [reply Parser/action_helpers.c:1006]: makes sense

**Comment by pablogsal** [comment]
Thanks a lot for the PR @sunmy2019 !

File: Parser/action_helpers.c [hunk 2]
```diff
@@ -998,18 +998,39 @@ _PyPegen_setup_full_format_spec(Parser *p, Token *colon, asdl_expr_seq *spec, in
...
+    // constant in it.
+    Py_ssize_t n_items = asdl_seq_LEN(spec);
+    Py_ssize_t non_empty_count = 0;
+    for (Py_ssize_t i = 0; i < n_items; i++) {
+        expr_ty item = asdl_seq_GET(spec, i);
+        non_empty_count += !(item->kind == Constant_kind &&
+                             PyUnicode_CheckExact(item->v.Constant.value) &&
+                             PyUnicode_GET_LENGTH(item->v.Constant.value) == 0);
+    }
+    asdl_expr_seq *resized_spec;
```
Comment (pablogsal) [inline Parser/action_helpers.c]: There is no more resized arrays so this name is now a bit odd.

File: Parser/action_helpers.c [hunk 3]
```diff
@@ -998,18 +998,39 @@ _PyPegen_setup_full_format_spec(Parser *p, Token *colon, asdl_expr_seq *spec, in
...
+            if (item->kind == Constant_kind &&
+                PyUnicode_CheckExact(item->v.Constant.value) &&
+                PyUnicode_GET_LENGTH(item->v.Constant.value) == 0) {
+                continue;
+            }
+            asdl_seq_SET(resized_spec, j++, item);
+        }
+        assert(j == non_empty_count);
+    } else {
+        resized_spec = spec;
```
Comment (pablogsal) [inline Parser/action_helpers.c]: This can be done where `resized_spec` is defined and wee can skip the `else`.

File: Parser/action_helpers.c (hunk 2 above)
Comment (sunmy2019) [reply Parser/action_helpers.c]: I got it simplified.

**Comment by lysnikolaou** [comment]
I'm wondering why we cannot do this in the tokenizer directly. Wouldn't something like this work?

```diff
cpython on  main [!] via C v15.0.0-clang via 🐍 pyenv 3.11.3 (venv) took 8s 
❯ git diff
diff --git a/Parser/tokenizer.c b/Parser/tokenizer.c
index 41d0d16a47..504bc9bed9 100644
--- a/Parser/tokenizer.c
+++ b/Parser/tokenizer.c
@@ -2639,6 +2639,12 @@ tok_get_fstring_mode(struct tok_state *tok, tokenizer_mode* current_tok, struct
     tok->first_lineno = tok->lineno;
     tok->starting_col_offset = tok->col_offset;
 
+    int in_format_spec = (
+            current_tok->last_expr_end != -1
+            &&
+            INSIDE_FSTRING_EXPR(current_tok)
+    );
+
     // If we start with a bracket, we defer to the normal mode as there is nothing for us to tokenize
     // before it.
     int start_char = tok_nextc(tok);
@@ -2655,6 +2661,10 @@ tok_get_fstring_mode(struct tok_state *tok, tokenizer_mode* current_tok, struct
             return tok_get_normal_mode(tok, current_tok, token);
         }
     }
+    else if (start_char == '}' && in_format_spec) {
+        tok_backup(tok, start_char);
+        return tok_get_normal_mode(tok, current_tok, token);
+    }
     else {
         tok_backup(tok, start_char);
     }
@@ -2726,11 +2736,6 @@ tok_get_fstring_mode(struct tok_state *tok, tokenizer_mode* current_tok, struct
             end_quote_size = 0;
         }
 
-        int in_format_spec = (
-                current_tok->last_expr_end != -1
-                &&
-                INSIDE_FSTRING_EXPR(current_tok)
-        );
         if (c == '{') {
             int peek = tok_nextc(tok);
             if (peek != '{' || in_format_spec) {
```

Didn't thoroughly test it, but one pass through the tests only shows one failure that's got to do with the error message when we have a lambda in the expression part.

**Comment by sunmy2019** [comment]
> I'm wondering why we cannot do this in the tokenizer directly.

I got no objection with this.

One thing to note: the same special handling of empty str constants are at the other parts of the code.

If your idea is adopted, we'd better clean up those special handling.

**Comment by sunmy2019** [comment]
I'd propose we land this first and backport to 3.12.

Then maybe we can optimize further on the 3.13 branch.

**Review by lysnikolaou — APPROVED** [review]
Looks good!

**Comment by pablogsal** [comment]
I think we need to regenerate some files (run `make regen-all`)
