### PR TITLE
bpo-40334: Fix error location upon parsing an invalid string literal

### LINKED ISSUE #64: Failure in test_string_literals: Unexpected amount of warnings
Current Parser:
```
╰─ ./python       
Python 3.9.0a5+ (heads/pegen:99a8e2fa08, Apr  9 2020, 16:19:04) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import warnings
>>> with warnings.catch_warnings(record=True) as w:
...     warnings.simplefilter('always', category=DeprecationWarning)
...     eval("'''\n\\z'''")
... 
'\n\\z'
>>> len(w)
1
```

Pegen:
```
╰─ ./python -p new
Python 3.9.0a5+ (heads/pegen:99a8e2fa08, Apr  9 2020, 16:19:04) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import warnings
>>> with warnings.catch_warnings(record=True) as w:
...     warnings.simplefilter('always', category=DeprecationWarning)
...     eval("'''\n\\z'''")
... 
'\n\\z'
>>> len(w)
2
```

### PR DESCRIPTION
**Pull request by lysnikolaou**
When parsing a string with an invalid escape, the old parser used to
point to the beginning of the invalid string. This PR changes the new
parser to match that behavior, since it's currently pointing to the
end of the string (or to be more precise, to the beginning of the next
token).

Closes we-like-parsers/cpython#64.

https://bugs.python.org/issue40334

### CODE REVIEW

File: Parser/pegen/pegen.c [hunk 1]
```diff
@@ -1977,7 +1977,7 @@ _PyPegen_concatenate_strings(Parser *p, asdl_seq *strings)
             goto error;
         }
 
-        if (_PyPegen_parsestr(p, this_str, &this_bytesmode, &this_rawmode, &s, &fstr, &fstrlen) != 0) {
```
Comment (pablogsal) [inline Parser/pegen/pegen.c:1980]: If we pass the token, we can maybe get the value for `this_str` inside `_PyPegen_parsestr`

File: Parser/pegen/parse_string.c [hunk 2]
```diff
@@ -12,20 +12,27 @@
...
         if (PyErr_ExceptionMatches(PyExc_DeprecationWarning)) {
             /* Replace the DeprecationWarning exception with a SyntaxError
                to get a more accurate error report */
             PyErr_Clear();
+
+            /* This is a hack, in order for the SyntaxError to point to the token t,
+               since _PyPegen_raise_error always uses p->tokens[p->fill - 1] for the
+               error location. */
+            Token *old_end = p->tokens[p->fill - 1];
+            p->tokens[p->fill - 1] = t;
```
Comment (pablogsal) [inline Parser/pegen/parse_string.c]: Instead, could we have a new  `Token*` attribute on the parser that (optionally) points to a token where the syntax error happens? Then, in the raise function, we take that token as a preference over `p->tokens[p->fill - 1]`. In this way, we don't need to modify the token string, which initially feels suboptimal (I have not thought about other side effects this may had).

File: Lib/test/test_cmd_line_script.py [hunk 3]
```diff
@@ -648,7 +648,7 @@ def test_syntaxerror_invalid_escape_sequence_multi_line(self):
             self.assertEqual(
                 stderr.splitlines()[-3:],
                 [   b'    foo = """\\q"""',
-                    b'                 ^',
+                    b'          ^',
```
Comment (pablogsal) [inline Lib/test/test_cmd_line_script.py:651]: Does this work also with the old parser?

**Review by pablogsal — COMMENTED** [review]
Nice! I left some comments and questions but initially, looks great :)

File: Lib/test/test_cmd_line_script.py (hunk 3 above)
Comment (lysnikolaou) [reply Lib/test/test_cmd_line_script.py:651]: It does with `python -X oldparser -m test -v test_cmd_line_script`. I also checked on the REPL that the `SyntaxError` emitted has the same `col_offset`.

File: Parser/pegen/pegen.c (hunk 1 above)
Comment (lysnikolaou) [reply Parser/pegen/pegen.c:1980]: Done!

File: Parser/pegen/parse_string.c (hunk 2 above)
Comment (lysnikolaou) [reply Parser/pegen/parse_string.c]: You mean in the `Parser` struct?

Comment (pablogsal) [reply Parser/pegen/parse_string.c]: > You mean in the `Parser` struct?

Yup

Comment (pablogsal) [reply Parser/pegen/parse_string.c]: Maybe `p->known_err_token` or something similar.

Comment (lysnikolaou) [reply Parser/pegen/parse_string.c]: Good idea! On it.

Comment (lysnikolaou) [reply Parser/pegen/parse_string.c]: Done.

**Review by pablogsal — APPROVED** [review]
Great! LGTM

File: Lib/test/test_string_literals.py [hunk 4]
```diff
@@ -118,8 +118,7 @@ def test_eval_str_invalid_escape(self):
             eval("'''\n\\z'''")
         self.assertEqual(len(w), 1)
         self.assertEqual(w[0].filename, '<string>')
-        if use_old_parser():
-            self.assertEqual(w[0].lineno, 1)
+        self.assertEqual(w[0].lineno, 1)
```
Comment (gvanrossum) [inline Lib/test/test_string_literals.py:121]: No assert for column?

**Review by gvanrossum — APPROVED** [review]

File: Lib/test/test_string_literals.py (hunk 4 above)
Comment (lysnikolaou) [reply Lib/test/test_string_literals.py:121]: We cannot do this here, because `WarningMessage` objects do not hold column information. Added an assertion a bit further down, where a `SyntaxError` is thrown.

**Review by gvanrossum — APPROVED** [review]
How about the next test/chunk? Does it still pass with the old parser?

**Comment by lysnikolaou** [comment]
> How about the next test/chunk? Does it still pass with the old parser?

Yes, it passes with both parsers on macOS.

**Review by gvanrossum — APPROVED** [review]
