### PR TITLE
bpo-45126: Fix ref. leak in `sqlite3.Connection.__init__`

### LINKED ISSUE #89289: [sqlite3] cleanup and harden `Connection.__init__`
BPO | [45126](https://bugs.python.org/issue45126)
--- | :---
Nosy | @encukou, @corona10, @miss-islington, @erlend-aasland, @DiddiLeija
PRs | <li>python/cpython#28227</li><li>python/cpython#28231</li><li>python/cpython#28234</li><li>python/cpython#28298</li><li>python/cpython#28302</li><li>python/cpython#29160</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-09-07.11:46:02.065>
labels = ['extension-modules', '3.11']
title = '[sqlite3] cleanup and harden Connection and Cursor __init__'
updated_at = <Date 2021-11-23.13:11:11.371>
user = 'https://github.com/erlend-aasland'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-23.13:11:11.371>
actor = 'petr.viktorin'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2021-09-07.11:46:02.065>
creator = 'erlendaasland'
dependencies = []
files = []
hgrepos = []
issue_num = 45126
keywords = ['patch']
message_count = 18.0
messages = ['401248', '401352', '401356', '401357', '401358', '401359', '401361', '401362', '401363', '401366', '401371', '401561', '401666', '401682', '401684', '406406', '406419', '406838']
nosy_count = 5.0
nosy_names = ['petr.viktorin', 'corona10', 'miss-islington', 'erlendaasland', 'DiddiLeija']
pr_nums = ['28227', '28231', '28234', '28298', '28302', '29160']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue45126'
versions = ['Python 3.11']
```

</p></details>

### PR DESCRIPTION
**Pull request by erlend-aasland**
'database_obj' no longer leaks if audit fails.

- Let AC handle full conversion of 'database' arg, from pathlike object to C string
- Let AC handle resource management of 'database' arg

Resolves #89289

https://bugs.python.org/issue45126

### CODE REVIEW

**Comment by erlend-aasland** [comment]
Although this could be fixed by a decref after the audit check, it is not immediately clear why only 'database_obj' needs special treatment, and not the other arguments. Taking resource management out of `__init__` and placing it in AC is IMO a cleaner approach.

**Comment by erlend-aasland** [comment]
`test_multiprocessing_spawn` failed on the `PPC64LE RHEL8 Refleaks PR` buildbot; `test_sqlite` passed.

File: Modules/_sqlite/connection.c [hunk 1]
```diff
@@ -33,6 +33,32 @@
...
+
+    if (!PyUnicode_FSConverter(pathlike, &bytes)) {
+        goto error;
+    }
+    else if (PyBytes_AsStringAndSize(bytes, &str, &len) < 0) {
+        goto error;
+    }
+    else if ((*result = (const char *)PyMem_Malloc(len+1)) == NULL) {
+        goto error;
+    }
```
Comment (corona10) [inline Modules/_sqlite/connection.c]: For simplicity, if-else if + goto combination is too complex

```suggestion
    if (!PyUnicode_FSConverter(pathlike, &bytes)) {
        goto error;
    }
    if (PyBytes_AsStringAndSize(bytes, &str, &len) < 0) {
        goto error;
    }
    if ((*result = (const char *)PyMem_Malloc(len+1)) == NULL) {
        goto error;
    }
```

**Review by corona10 — CHANGES_REQUESTED** [review]

File: Modules/_sqlite/connection.c (hunk 1 above)
Comment (erlend-aasland) [reply Modules/_sqlite/connection.c]: > For simplicity, if-else if + goto combination is too complex

Doh, of course! It helps with a second pair of eyes :)

**Comment by erlend-aasland** [comment]
I have made the requested changes; please review again

**Review by corona10 — APPROVED** [review]
lgtm
Failed CIs doesn't look related to change.

**Comment by corona10** [comment]
@erlend-aasland Cherry-pick please.

**Comment by erlend-aasland** [comment]
> @erlend-aasland Cherry-pick please.

I'll fix the backports. Thank you so much for reviewing. Highly appreciated.

**Comment by erlend-aasland** [comment]
We backport to 3.9 from GH-28298.
