### PR TITLE
gh-104372: Drop the GIL around the vfork() call.

### LINKED ISSUE #104372: subprocess can block all Python threads when using `vfork()` until the child process `exec()` succeeds or fails.
# Background

When using the `subprocess` module on Linux, `vfork()` rather than `fork()` has been preferred when possible for a few Python releases as is generally offers MUCH higher performance, the larger the parent process, the more cpu time it saves on page table copying.

# Problem

`vfork()` - by design - does not return control to parent process until after the child process has successfully performed an `exec()` system call or has died.

Python `subprocess` uses `_posixsubprocess.fork_exec()` extension module implementation to do handle async-signal-safe fork/vfork+exec code path (as that cannot safely be implemented in Python). This function does not release the GIL. Thus the GIL is held across the `vfork()` call. Meaning the parent process does not resume execution until the exec has succeeded, or failed and returned an error which our child writes to it's `errpipe_write` fd before exiting.

This can result in **all Python threads hanging** (ie: the GIL is held by a blocked thread) when the child `exec` system call takes a long time. Such as the binary existing on a potentially slow or high latency network filesystem.  (We witnessed this on a FUSE filesystem backed by remote (high latency) cloud storage with a large executable... but any slow or high latency filesystem containing an executable or anything interfering in the exec system call can cause the same problem).

# Workarounds

Building without `vfork` support in `_posixsubprocess` or otherwise passing an arg to subprocess API that happens to disable vfork because it is incompatible with the vfork-concept are workarounds. _(I won't recommend any of those because none of them are a good idea to pass when not needed for their primary purpose)_.

Another workaround viable in our specific case is to pre-read the executable before asking subprocess to launch it as that moves the high IO latency from the `exec` system call into a read without the GIL held beforehand as it pulls the executable into a fast-enough local storage cache.  (That being useful at all depends on your particular filesystem latency implementation situation)

# Potential Solutions

If we could simply release the GIL around the `vfork()` call that would seem to be ideal... It's not clear to me that we can actually do that, I'm working out what a PR would look like or what blocks us from doing so safely.

Offering yet another keyword argument to subprocess APIs to disable the use of APIs that could block the entire process upon `exec()` such as `vfork` is viable - but doesn't feel great given our existing long list of subprocess args.

### Linked PRs
* gh-104515
* gh-104518
* gh-104697
* gh-104782
* gh-104785
* gh-104831
* gh-104833
* gh-104942
* gh-104958

### PR DESCRIPTION
**Pull request by gpshead**
On Linux where the `subprocess` module can use the `vfork` syscall for faster spawning, prevent the parent process from blocking other threads by dropping the GIL while it waits for the vfork'ed child process `exec` outcome.  This prevents spawning a binary from a slow filesystem from blocking the rest of the application.

Fixes #104372.

* Issue: gh-104372

### CODE REVIEW

**Comment by gpshead** [comment]
This PR is preferred over #104515 as it does not rely on undefined behavior magic cross-process address space sharing shenanigans.

File: Modules/_posixsubprocess.c [hunk 1]
```diff
@@ -798,14 +798,29 @@ do_fork_exec(char *const exec_array[],
...
         assert(uid == (uid_t)-1);
         assert(gid == (gid_t)-1);
         assert(extra_group_size < 0);
         assert(preexec_fn == Py_None);
 
+        /* Drop the GIL so that other threads can continue execution while this
+         * thread in the parent remains blocked per vfork-semantics on the
+         * child's exec syscall outcome. Exec does filesystem access which
+         * can take an arbitrarily long time. This addresses GH-104372.
+         *
```
Comment (Yhg1s) [inline Modules/_posixsubprocess.c:813]: Maybe add a comment explaining that the child process must not re-acquire the GIL (because of the shared address space) and also should have no need for the GIL (since it's not allowed to touch any Python objects, only exec or exit)?

**Review by Yhg1s — APPROVED** [review]
