### PR TITLE
gh-107409: set `__wrapped__` attribute in `reprlib.recursive_repr`

### LINKED ISSUE #107409: `reprlib.recursive_repr` is not setting `.__wrapped__` attribute
# Bug report
There is no way to get original actual `__repr__` function after applying `@recursive_repr` decorator

```py
import reprlib
class X:
    @reprlib.recursive_repr()
    def __repr__(self) -> str:
        return f'X({self.__dict__})'

# how to get initial X.__repr__ back?
# this doesn't work:
X.__repr__.__wrapped__ # AttributeError: 'function' object has no attribute '__wrapped__'
# this is awful:
X.__repr__.__closure__[2].cell_contents
```

# Your environment
- CPython versions tested on: 3.11, 3.13.0a0

### Linked PRs
* gh-107410

### PR DESCRIPTION
**Pull request by denballakh**
fixes #107409

* Issue: gh-107409

### CODE REVIEW

**Review by sunmy2019 — APPROVED** [review]
LG

File: Misc/NEWS.d/next/Library/2023-07-29-02-36-50.gh-issue-107409.HG27Nu.rst [hunk 1]
```diff
@@ -0,0 +1 @@
+Set `__wrapped__` attribute in `reprlib.recursive_repr`.
```
Comment (kumaraditya303) [inline Misc/NEWS.d/next/Library/2023-07-29-02-36-50.gh-issue-107409.HG27Nu.rst]:
```suggestion
Set :attr:`!__wrapped__` attribute in :func:`reprlib.recursive_repr`.
```

**Review by kumaraditya303 — APPROVED** [review]
