### PR TITLE
gh-129603: Don't segfault if sqlite3.Row description is None

### LINKED ISSUE #129603: Segfault if `pysqlite_Row->description == PyNone`
# Crash report

### What happened?

Most of the code in `Modules/_sqlite/row.c` assumes `->description` is a tuple. However, it may be `None`. Since it is possible to craft a `sqlite3.Row` object "by hand", it is easy to provoke segfauls for paths that involve the `PyTuple` API and `description == Py_None`. Any real code would never directly instantiate a row object; it would be implicitly created by the cursor (via the `.fetch*()` APIs or by iterating on the cursor). However, I don't think we should let a possible segfault hang around.

```python
import sqlite3
cx = sqlite3.connect(":memory:")
cu = cx.cursor()
row = sqlite3.Row(cu, (1,2))
row.keys()  # <= boom
```

### CPython versions tested on:

3.14, 3.13, 3.12, CPython main branch

### Operating systems tested on:

macOS

### Output from running 'python -VV' on the command line:

_No response_

### Linked PRs
* gh-129604
* gh-129923
* gh-129924

### PR DESCRIPTION
**Pull request by erlend-aasland**
* Issue: gh-129603

### CODE REVIEW

File: Modules/_sqlite/row.c [hunk 1]
```diff
@@ -151,9 +150,13 @@ pysqlite_row_subscript(PyObject *op, PyObject *idx)
         PyObject *item = PyTuple_GetItem(self->data, _idx);
         return Py_XNewRef(item);
     } else if (PyUnicode_Check(idx)) {
-        nitems = PyTuple_Size(self->description);
+        if (Py_IsNone(self->description)) {
+            PyErr_Format(PyExc_IndexError, "No item with key %R", idx);
```
Comment (erlend-aasland) [inline Modules/_sqlite/row.c:154]: IMO, this should be a `KeyError`, but that would create an inconsistency with L174. Moreover, we should also improve that error message by aligning it to this.

**Comment by erlend-aasland** [comment]
Alternatively, we could disallow instantiation of `Row` objects if `description` is `None`, but I'm not sure it is a better approach.

File: Modules/_sqlite/row.c (hunk 1 above)
Comment (picnixz) [reply Modules/_sqlite/row.c:154]: IMO it should have been a dedicated exception type inheriting from LookupError but the ship has already sailed.

Now, since using the named field instead of its position is equivalent to `row[get_index(field_name)]`, I think it's fine to keep the IndexError (even though it could be surprising at first).

Improving the error message may be good or documenting that an IndexError is raised for invalid indices or invalid keys (if it's not already done).

**Comment by erlend-aasland** [comment]
> Alternatively, we could disallow instantiation of `Row` objects if `description` is `None`, but I'm not sure it is a better approach.

Expanding on this: adding this check to the `tp_new` slot _may_ impact performance, but I would expect the added pointer check to be negligible.

File: Modules/_sqlite/row.c (hunk 1 above)
Comment (erlend-aasland) [reply Modules/_sqlite/row.c:154]: >  I think it's fine to keep the IndexError (even though it could be surprising at first).

Definitely.

> Improving the error message may be good or documenting that an IndexError is raised for invalid indices or invalid keys (if it's not already done).

Improving the error message is out of scope for this PR (such a change should not be backported). A docs update could also be nice, but I don't have the bandwidth for that right now.

**Comment by picnixz** [comment]
> Expanding on this: adding this check to the tp_new slot may impact performance, but I would expect the added pointer check to be negligible.

Are there situations where one needs to create an instance of an sqlite row from a cursor with no description? (even creating rows manually by passing a cursor feels a bit weird to me, but there are maybe cases when it's needed, I don't know, probably for libs interfacing even more with sqlite3). If so, this may be better to keep the current PR (which can be backported probably) and then do a follow-up PR and:

- Solution 1: raise if None is passed as the description.
- Solution 2: emit a deprecation warning saying that in the future rows without a description cannot be instantiated (i.e., the cursor must therefore have a description); this will not be really efficient and it would anyway add a check and could annoy users.

If it doesn't make sense to instantiate a row with a cursor that has no description (and I think it doesn't make sense to do this but I may be mistaken), then we can just have this additional check at construction time. I doubt it will slow down since it's just an additional `is None` check. The row creation looks is already fast by itself and we're already doing an `if (self == NULL)` check, which is roughly the same cost of `if (cursor->description == Py_None) { ... }`.

Now, if rows with None descriptions were instantiated manually, and even if they don't make sense or reflect bad code practice, they were already broken when keys were being used but we could still use them with numeric indices. So there *might* be some code that is not entirely broken out there. If you want to be super-conservative, let's go down the deprecation road (but it's annoying for both the users and us to maintain), so I think we can just forbid instantiating such rows in 3.14+. For 3.12 and 3.13, we can leave it as is just to avoid possible reports.

**Comment by erlend-aasland** [comment]
As I wrote in the issue OP, I don't think any real world code instantiates `Row` objects manually, _but_ you never know. This PR is probably the most conservative: we avoid crashing, but apart from that, there are no change in behaviour. Changing `__new__` to disallow missing descriptions would be a breaking change in theory, but probably not in practice. I'm not sure if it is worth it to disallow missing descriptions, though.

**Comment by picnixz** [comment]
> Changing __new__ to disallow missing descriptions would be a breaking change in theory

Yeah, that's why I suggested the (annoying) deprecation road. The PR doesn't look super complicate and I don't think we have other places where we need to be careful with the type of the description (maybe you could add a comment in the object structure saying that it can be None and thus should be carefully checked?).

**Comment by picnixz** [comment]
Note: `__getitem__` gets a tiny tiny tiny tiny slowdown since we have an additional `is not None` check every time we use a key (but this is not the dominant step of the call).

**Comment by erlend-aasland** [comment]
> Note: `__getitem__` gets a tiny tiny tiny tiny slowdown since we have an additional `is not None` check every time we use a key (but this is not the dominant step of the call).

Hm, I'm not sure we even need that check. I'm strangely unable to trigger a crash for that path.

**Comment by erlend-aasland** [comment]
Ah, it's using `PyTuple_Size`, not `PyTuple_GET_SIZE`.

**Comment by erlend-aasland** [comment]
We should be fine with using the fast get-size API for both of the cases this PR touches. That should even out the potential slowdown of the None-check.

**Comment by erlend-aasland** [comment]
> Note: `__getitem__` gets a tiny tiny tiny tiny slowdown since we have an additional `is not None` check every time we use a key (but this is not the dominant step of the call).

Slight digression: we could speed up `Row` objects a little bit by using fast tuple APIs for `->data` access. Moreover, the `PyUnicode_Check`s in `equal_ignore_case` are redundant: *left* is already checked in `pysqlite_row_subscript`, and *right* is always a unicode object (we build the description tuples in cursor.c).

**Review by picnixz — APPROVED** [review]
