### PR TITLE
gh-137576: Fix for Basic REPL Showing Incorrect Code in Tracebacks with PYTHONSTARTUP

### LINKED ISSUE #137576: traceback shows wrong source code in basic REPL when PYTHONSTARTUP is set
# Bug report

### Bug description:

Start python with the basic repl and a PYTHONSTARTUP file
```bash
export PYTHON_BASIC_REPL=1; echo 'import math' > /tmp/foo.py; export PYTHONSTARTUP="/tmp/foo.py"; python
```

type `1/0` and the traceback shows
```python
Python 3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:09:02) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 1/0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    import math
    ^^^
ZeroDivisionError: division by zero
>>> 
```

Expected behavior (i.e. `export PYTHON_BASIC_REPL=1; unset PYTHONSTARTUP; python`):
```python
>>> 1/0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    1/0
    ~^~
ZeroDivisionError: division by zero
>>>
```

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

### Linked PRs
* gh-137625
* gh-137771
* gh-137778

### PR DESCRIPTION
**Pull request by adqm**
This patch attempts to fix #137576 by changing the way `interactive_filename` is computed for the basic REPL to make sure that it always begins with `<` and ends with `>` so that doesn't get an entry in `linecache.cache` (which was causing the source from `PYTHONSTARTUP` to be used instead of the interactive input when generating tracebacks).

Updated behavior:

```
$ echo "print('hello from PYTHONSTARTUP')" > /tmp/foo.py
$ PYTHON_BASIC_REPL=1 PYTHONSTARTUP=/tmp/foo.py ./python
Python 3.15.0a0 (heads/basic_repl_error_reporting:3d46e8feed, Aug 10 2025, 21:12:17) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
hello from PYTHONSTARTUP
>>> 1/0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    1/0
    ~^~
ZeroDivisionError: division by zero
```

```
$ echo "def foo(x):  return 1/x" > /tmp/foo.py
$ PYTHON_BASIC_REPL=1 PYTHONSTARTUP=/tmp/foo.py ./python
Python 3.15.0a0 (heads/basic_repl_error_reporting:3d46e8feed, Aug 10 2025, 21:12:17) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> def bar(x):
...     return foo(x)
... 
>>> bar(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    bar(0)
    ~~~^^^
  File "<stdin>", line 2, in bar
    return foo(x)
  File "/tmp/foo.py", line 1, in foo
    def foo(x):  return 1/x
                        ~^~
ZeroDivisionError: division by zero
```

* Issue: gh-137576

### CODE REVIEW

**Comment by adqm** [comment]
My original patch here also caused the tracebacks to report the filename as `<stdin-N>` instead of `<stdin>`.  I think there's something nice about that (from the REPL, it's nice to see when the sources shown in the traceback came from different interactive inputs, better symmetry with pyrepl's reporting, etc.), but for now I added a commit to keep the reported filename as `<stdin>`.

File: Misc/NEWS.d/next/Core_and_Builtins/2025-08-10-21-34-12.gh-issue-137576.0ZicS-.rst [hunk 1]
```diff
@@ -0,0 +1,2 @@
+Fix for incorrect source code being shown in tracebacks from the Basic REPL
+when ``PYTHONSTARTUP`` is given.  Patch by Adam Hartz.
```
Comment (Eclips4) [inline Misc/NEWS.d/next/Core_and_Builtins/2025-08-10-21-34-12.gh-issue-137576.0ZicS-.rst]:
```suggestion
when :envvar:`PYTHONSTARTUP` is given. Patch by Adam Hartz.
```

File: Python/pythonrun.c [hunk 2]
```diff
@@ -1365,6 +1365,25 @@ run_eval_code_obj(PyThreadState *tstate, PyCodeObject *co, PyObject *globals, Py
     return PyEval_EvalCode((PyObject*)co, globals, locals);
 }
 
+static PyObject *
+get_interactive_filename(PyObject *filename, Py_ssize_t count){
```
Comment (Eclips4) [inline Python/pythonrun.c]:
```suggestion
get_interactive_filename(PyObject *filename, Py_ssize_t count)
{
```
PEP 7

File: Python/pythonrun.c [hunk 3]
```diff
@@ -1365,6 +1365,25 @@ run_eval_code_obj(PyThreadState *tstate, PyCodeObject *co, PyObject *globals, Py
...
+    PyObject *result;
+    Py_ssize_t len = PyUnicode_GET_LENGTH(filename);
+
+    if (len >= 2
+            && PyUnicode_ReadChar(filename, 0) == '<'
+            && PyUnicode_ReadChar(filename, len - 1) == '>') {
+        PyObject *middle = PyUnicode_Substring(filename, 1, len-1);
```
Comment (Eclips4) [inline Python/pythonrun.c:1377]: Could you please add error checks for `PyUnicode_Substring`, since it could return `NULL`?
If that happens, simply return `NULL`.
Also, in `run_mode`, please add an error check for when `get_interactive_filename` returns `NULL` (just propagate that `NULL`).

**Review by Eclips4 — APPROVED** [review]
Thank you! 
A couple of nits.

File: Python/pythonrun.c (hunk 3 above)
Comment (adqm) [reply Python/pythonrun.c:1377]: Thanks for the review!

> Could you please add error checks for `PyUnicode_Substring`, since it could return `NULL`?

Yep, I added a check there.

> Also, in `run_mode`, please add an error check for when `get_interactive_filename` returns `NULL` (just propagate that `NULL`).

I think this one is already handled, on lines 1406-1408 (which happen just after `get_interactive_filename` is called).

```
        if (interactive_filename == NULL) {
            return NULL;
        }
```

Comment (Eclips4) [reply Python/pythonrun.c:1377]: Yup. You're right

**Comment by Eclips4** [comment]
@adqm I'm going to merge this tomorrow. 
Am I right that this reproducible on 3.13 and 3.14 (I don't have access to my machine now)?

**Comment by adqm** [comment]
Great, thanks!!

I just tested; the bug is indeed present on current 3.13 and 3.14 branches.

These patches apply cleanly to 3.14 as of right now but not to 3.13 (though I'm happy to make the necessary changes there).

**Comment by Eclips4** [comment]
@adqm Could you please manually backport this to 3.13? Thanks in advance!

**Comment by serhiy-storchaka** [comment]
Reminder about backporting. @adqm @Eclips4

**Comment by adqm** [comment]
Backport to 3.13 is in #137778.  Thanks @Eclips4!
