### PR TITLE
gh-93345: Fix a crash in substitution of nested TypeVar after TypeVarTuple

### LINKED ISSUE #93345: Crash in substitution of nested TypeVar after TypeVarTuple
During work on #93330 I have found an error in the C code which causes crash when substitute a TypeVar in nested generic alias after TypeVarTuple.

For example:
```
>>> from typing import *
>>> T = TypeVar('T')
>>> Ts = TypeVarTuple('Ts')
>>> tuple[*Ts, list[T]][int, str, bool]
Segmentation fault (core dumped)
```

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
Closes #93345.

### CODE REVIEW

File: Misc/NEWS.d/next/Core and Builtins/2022-05-30-10-22-46.gh-issue-93345.gi1A4L.rst [hunk 1]
```diff
@@ -0,0 +1,2 @@
+Fix a crash in substitution of a TypeVar in nested generic alias after
+TypeVarTuple.
```
Comment (Fidget-Spinner) [inline Misc/NEWS.d/next/Core and Builtins/2022-05-30-10-22-46.gh-issue-93345.gi1A4L.rst]:
```suggestion
Fix a crash in substitution of a ``TypeVar`` in nested generic alias after
``TypeVarTuple``.
```

**Review by Fidget-Spinner — APPROVED** [review]
