### PR TITLE
gh-91632: Fix generic_alias_iterator to be finalized at exit.

### LINKED ISSUE #91632: Memory leak with static iterator types
Python does not finalizes iterators of some types at exit leading to memory leak.

Reproducer:

```py
a = type(iter(tuple[int]))
print(a.mro())
```

Leak:
```console
[<class 'generic_alias_iterator'>, <class 'object'>]
[119 refs, 46 blocks]
```

See also https://github.com/python/cpython/issues/90575

### PR DESCRIPTION
**Pull request by corona10**
## AS-IS
````
➜  cpython git:(main) ✗ cat gh-91632.py
a = type(iter(tuple[int]))
print(a.mro())
➜  cpython git:(main) ✗ ./python.exe -X showrefcount gh-91632.py
[<class 'generic_alias_iterator'>, <class 'object'>]
[119 refs, 46 blocks]

````

## TO-BE
````
➜  cpython git:(gh-91632) ✗ cat gh-91632.py
a = type(iter(tuple[int]))
print(a.mro())
➜  cpython git:(gh-91632) ✗ ./python.exe -X showrefcount gh-91632.py
[<class 'generic_alias_iterator'>, <class 'object'>]
[0 refs, 0 blocks]
````

Follow Victor's suggestion :)

closes: #91632

### CODE REVIEW

**Comment by Fidget-Spinner** [comment]
I can't review this since I have no clue on the process of freeing memory on exit. But when do we add a type to `static_types`? Is it always?

File: Objects/object.c [hunk 1]
```diff
@@ -1923,6 +1924,7 @@ static PyTypeObject* static_types[] = {
     &_PyAsyncGenWrappedValue_Type,
     &_PyContextTokenMissing_Type,
     &_PyCoroWrapper_Type,
+    &_Py_GenericAliasIterType,
```
Comment (vstinner) [inline Objects/object.c:1927]: Add `extern PyTypeObject _Py_GenericAliasIterType;` before this list is enough. There is no need to add a whole header file (Include/internal/pycore_genericaliasobject.h) just for that.

**Comment by vstinner** [comment]
> I can't review this since I have no clue on the process of freeing memory on exit. But when do we add a type to static_types? Is it always?

I propose two approaches:

* Convert static types to heap types to free memory at exit: it's a hard work, and currently hold by the SC. You need to wait until https://peps.python.org/pep-0687/ is approved for that.
* Clear static types at Python exit (usually in Py_Finalize()):

  * Add the type to the static_types list in object.c (I tried to add all types there),
  * **or**: add a "Fini" function called by finalize_interp_types() (be careful of sub-interpreters: see _Py_IsMainInterpreter() function).

File: Objects/object.c (hunk 1 above)
Comment (corona10) [reply Objects/object.c:1927]: Thanks VIctor :)

File: Objects/genericaliasobject.c [hunk 2]
```diff
@@ -683,7 +683,7 @@ ga_iter_clear(PyObject *self) {
     return 0;
 }
 
-static PyTypeObject Py_GenericAliasIterType = {
+PyTypeObject _Py_GenericAliasIterType = {
```
Comment (vstinner) [inline Objects/genericaliasobject.c:688]: Would you mind to document that this type is only exported to be able to clear it in _PyTypes_FiniTypes()?

File: Objects/genericaliasobject.c [hunk 3]
```diff
@@ -697,7 +697,7 @@ static PyTypeObject Py_GenericAliasIterType = {
 
 static PyObject *
 ga_iter(PyObject *self) {
-    gaiterobject *gi = PyObject_GC_New(gaiterobject, &Py_GenericAliasIterType);
+    gaiterobject *gi = PyObject_GC_New(gaiterobject, &_Py_GenericAliasIterType);
```
Comment (vstinner) [inline Objects/genericaliasobject.c:702]: I'm surprised that it works to use a static type without calling PyType_Ready() on it! It looks like a bug (fixed by this PR thanks to _PyTypes_InitTypes()).

File: Misc/NEWS.d/next/Core and Builtins/2022-04-20-14-43-37.gh-issue-91632.cvUhsZ.rst [hunk 4]
```diff
@@ -0,0 +1 @@
+Fix :class:`generic_alias_iterator` to be finalized at exit.
```
Comment (vstinner) [inline Misc/NEWS.d/next/Core and Builtins/2022-04-20-14-43-37.gh-issue-91632.cvUhsZ.rst]: I don't understand this NEWS entry. I'm not sure that it's worth it to document this minor fix, since only a minority of users embed Python in an application and continue to run the application once Python is finalized. Usually, the application stops when Python exits.

If you want to document it, I suggest something like:

```suggestion
Fix a minor memory leak at exit: release the memory of the :class:`generic_alias_iterator` type. Patch by Dong-hee Na.
```

**Review by vstinner — APPROVED** [review]
LGTM.

**Comment by JelleZijlstra** [comment]
Should this be backported?

**Comment by Fidget-Spinner** [comment]
@JelleZijlstra generic alias iterator is part of the variadic generics PEP which is 3.11 only iirc.

**Comment by vstinner** [comment]
> Should this be backported?

The work to clear static types at exit is new in Python 3.11 (especially the _PyTypes_FiniTypes() function).
