### PR TITLE
gh-129958: New syntax error in format spec applies to both f-strings and t-strings

### LINKED ISSUE #129958: Vague behavior when single quoted f-string format_spec contains line break
# Bug report

### Bug description:

```python
>>> value = 123
>>> f"{value:.{'2'}f}" # '123.00'
>>> f"{value:.
{'2f'}}" # '123.00'
# but, shouldn't this one below also be valid?
>>> f"{value:.
... {'2'}f}" # invalid
>>> f"{value:
... {'.2f'}}" # '123.00'
```

I am checking the code of CPython's lexer and am confused why the lexer resets to normal mode when it encounters line break in format spec
https://github.com/python/cpython/blob/d7672e5d5a7b9580a72dbe75d3a9e8840bcc604c/Parser/lexer/lexer.c#L1338-L1348

Go back to the original PR: https://github.com/python/cpython/pull/110271
Seems this case is not covered by the test cases

The case above could be recognized by tokenizer, so maybe pegen should be modified.
However, since it goes back to normal mode, some corner cases cannot be handled by tokenizer:
```python
>>> value = 123
>>> f"{value:#{'x'}}" # '0x7b'
>>> f"{value:
... #{'x'}}" # breaks the tokenizer
```

### CPython versions tested on:

3.13

### Operating systems tested on:

macOS

### Linked PRs
* gh-130063
* gh-132692
* gh-135570
* gh-135982

### PR DESCRIPTION
**Pull request by dylwil3**
Closes #129958 
(again)

And I think requires backport to 3.14.

Let me know if this warrants a test in `test_tstring.py` and/or a blurb!

* Issue: gh-129958

### CODE REVIEW

File: Parser/lexer/lexer.c [hunk 1]
```diff
@@ -1421,7 +1421,8 @@ tok_get_fstring_mode(struct tok_state *tok, tokenizer_mode* current_tok, struct
                     return MAKE_TOKEN(
                         _PyTokenizer_syntaxerror(
                             tok,
-                            "f-string: newlines are not allowed in format specifiers for single quoted f-strings"
+                            "%c-string: newlines are not allowed in format specifiers for single quoted %c-strings",
+                            TOK_GET_STRING_PREFIX(tok),TOK_GET_STRING_PREFIX(tok)
```
Comment (tomasr8) [inline Parser/lexer/lexer.c]:
```suggestion
                            TOK_GET_STRING_PREFIX(tok), TOK_GET_STRING_PREFIX(tok)
```

**Review by tomasr8 — COMMENTED** [review]
> Let me know if this warrants a test in test_tstring.py and/or a blurb!

I think it warrants both :)

File: Lib/test/test_tstring.py [hunk 2]
```diff
@@ -219,6 +219,7 @@ def test_syntax_errors(self):
             ("t'{lambda:1}'", "t-string: lambda expressions are not allowed "
                               "without parentheses"),
             ("t'{x:{;}}'", "t-string: expecting a valid expression after '{'"),
+            ("""t'{1:d\n}'""","t-string: newlines are not allowed in format specifiers")
```
Comment (lysnikolaou) [inline Lib/test/test_tstring.py]:
```suggestion
            ("t'{1:d\n}'", "t-string: newlines are not allowed in format specifiers")
```

**Review by lysnikolaou — COMMENTED** [review]
Just a minor formatting nit and it's good to go!

**Review by lysnikolaou — APPROVED** [review]
LGTM! Thanks @dylwil3!
