### PR TITLE
gh-133089: Use original timeout value for `TimeoutExpired` when the func `subprocess.run` is called with a timeout

### LINKED ISSUE #133089: Negative run-time reported by `subprocess.run`'s `TimeoutExpired` exception when setting `timeout=0`
# Bug report

### Bug description:

```python
import subprocess
subprocess.run(['echo', 'hi'], timeout = 0)

# subprocess.TimeoutExpired: Command '['echo', 'hi']' timed out after -0.00010189996100962162 seconds
# subprocess.TimeoutExpired: Command '['echo', 'hi']' timed out after -4.819990135729313e-05 seconds
```

This is quite unexpected that the measured run-time can be negative

In general, it's unclear in the docs what behavior should have `timeout=0`. I would propose that it should disable timeout control, and should be equivalent to `timeout=None`.

But in any case, negative run-times are quite strange :)

### CPython versions tested on:

3.12

### Operating systems tested on:

WSLv1+Ubuntu24.04

### Linked PRs
* gh-133103
* gh-133418

### PR DESCRIPTION
**Pull request by Zheaoli**
Fix #133089

* Issue: gh-133089

### CODE REVIEW

**Review by StanFromIreland — CHANGES_REQUESTED** [review]
What about a negative *timeout*? Why does `wait` need this too?

This needs doc updates, and a test.

File: Misc/NEWS.d/next/Library/2025-04-29-02-23-04.gh-issue-133089.8Jy1ZS.rst [hunk 1]
```diff
@@ -0,0 +1,2 @@
+Make :func:`subprocess.run`'s behavior is same with 'timeout=None' when
+the timeout is zero
```
Comment (StanFromIreland) [inline Misc/NEWS.d/next/Library/2025-04-29-02-23-04.gh-issue-133089.8Jy1ZS.rst]: Please fix the grammar and use, `inline code` and *italics*.

**Comment by Zheaoli** [comment]
> What about a negative _timeout_?

How about raise ValueError when timeout is `<=0`

**Comment by StanFromIreland** [comment]
Hmm, looking at bash functions I get conflicting results. `timeout` throws an error for negative values and has no limit on `0`, whereas other functions (e.g. `read -t 0`) actually use the limit (they stop instantly).

File: Lib/subprocess.py [hunk 2]
```diff
@@ -1268,6 +1270,7 @@ def _check_timeout(self, endtime, orig_timeout, stdout_seq, stderr_seq,
 
 
     def wait(self, timeout=None):
+        timeout = None if timeout == 0 else timeout
```
Comment (ZeroIntensity) [inline Lib/subprocess.py]: This should go after the docstring.

**Review by ZeroIntensity — CHANGES_REQUESTED** [review]
I don't think `timeout=0` should be treated the same as `timeout=None`. This isn't done anywhere else in the standard library. For example, using `asyncio` as precedent:

```py
import asyncio

async def main():
    async with asyncio.timeout(None):
        await asyncio.sleep(0)
        print("No timeout!")

    async with asyncio.timeout(0):
        await asyncio.sleep(0)  # TimeoutError

asyncio.run(main())
```

I think it would be better to fix the negative time.

**Comment by Zheaoli** [comment]
> I don't think `timeout=0` should be treated the same as `timeout=None`. This isn't done anywhere else in the standard library. For example, using `asyncio` as precedent:

Make sense, I'll find a way to patch it

File: Lib/subprocess.py [hunk 3]
```diff
@@ -2031,7 +2031,7 @@ def _wait(self, timeout):
             if self.returncode is not None:
                 return self.returncode
 
-            if timeout is not None:
+            if timeout is not None and timeout > 0:
```
Comment (gpshead) [inline Lib/subprocess.py]: _wait() with timeout <= 0 must **not** disable timeouts. That is a semantic behavior change and would cause issues in fuzzy elapsed time for timeout calculations to wind up not having a timeout in wait at all.

The goal of this ._wait implementation is to **always** call waitpid at least once before deciding if TimeoutExpired should be raised.

**Review by gpshead — CHANGES_REQUESTED** [review]
I think your documentation addition is useful, but the logic change is not what we want.

If you want a cleaner value in the TimeoutExpired error message in this situation, that could be done by catching and **replacing** the info in the TimeoutExpired exception from Popen._communicate's `self.wait(timeout=self._remaining_time(endtime))` with the orig_timeout value that is known at that point.  `.wait()` itself cannot meaningfully know that value.

File: Doc/library/subprocess.rst [hunk 4]
```diff
@@ -1525,6 +1525,30 @@ handling consistency are valid for these functions.
...
 -----
 
+.. _subprocess-timeout-behavior:
+
+Timeout Behavior
+^^^^^^^^^^^^^^^^
+
+When using the ``timeout`` parameter in functions like :func:`run`,
+:meth:`Popen.wait`, or :meth:`Popen.communicate`,
+users should be aware of the following behaviors:
```
Comment (StanFromIreland) [inline Doc/library/subprocess.rst:1535]: This seems off since the below are not subheadings of the introduction?

Comment (Zheaoli) [reply Doc/library/subprocess.rst:1535]: Done

**Review by ZeroIntensity — COMMENTED** [review]
Please add a test case.

File: Lib/subprocess.py [hunk 5]
```diff
@@ -1235,8 +1235,10 @@ def communicate(self, input=None, timeout=None):
 
             finally:
                 self._communication_started = True
-
-            sts = self.wait(timeout=self._remaining_time(endtime))
+            try:
+                sts = self.wait(timeout=self._remaining_time(endtime))
+            except TimeoutExpired:
+                raise TimeoutExpired(self.args, timeout)
```
Comment (gpshead) [inline Lib/subprocess.py]: I modified these to not create a new one, just reassign a new timeout value to the existing exception instance and reraise it.

**Review by gpshead — APPROVED** [review]
