### PR TITLE
gh-105987: Fix reference counting issue in `_asyncio._swap_current_task`

### LINKED ISSUE #105987: Crash in `_asyncio._swap_current_task` due to improper reference counting
First appeared in a474e04388c2ef6aca75c26cb70a1b6200235feb, where given function was introduced.

Repro:
```python
import _asyncio

class DummyLoop:
    pass

class DummyTask:
    pass

l = DummyLoop()
_asyncio._swap_current_task(l, DummyTask())
t = _asyncio._swap_current_task(l, None)
```
Output:
```
Modules/gcmodule.c:461: visit_decref: Assertion "!_PyObject_IsFreed(op)" failed
Enable tracemalloc to get the memory block allocation traceback

object address  : 0x7fedad081130
object refcount : 1
object type     : 0x55f665a81fe0
object type name: dict
object repr     : Segmentation fault (core dumped)
```

I'm working on a fix.

### Linked PRs
* gh-105989
* gh-106099
* gh-139538
* gh-139539

### PR DESCRIPTION
**Pull request by chgnrdv**
Fixes #105987 

`_PyDict_GetItem_KnownHash` returns borrowed reference to previous task object, so call to `_PyDict_DelItem_KnownHash`/`_PyDict_SetItem_KnownHash` can deallocate it before it will be returned from `swap_current_task` function

* Issue: gh-105987

### CODE REVIEW

**Review by carljm — COMMENTED** [review]
Code LGTM. Thanks for finding and fixing! Please add a NEWS entry.

**Comment by gvanrossum** [comment]
@carljm If you're uncomfortable merging this, can you ask @kumaraditya303 for a review?

File: Modules/_asynciomodule.c [hunk 1]
```diff
@@ -2050,17 +2050,19 @@ swap_current_task(asyncio_state *state, PyObject *loop, PyObject *task)
```
Comment (kumaraditya303) [inline Modules/_asynciomodule.c:2051]: I would prefer to have incref after check for `NULL`.

File: Lib/test/test_asyncio/test_eager_task_factory.py [hunk 2]
```diff
@@ -222,6 +224,23 @@ class PyEagerTaskFactoryLoopTests(EagerTaskFactoryLoopTests, test_utils.TestCase
 class CEagerTaskFactoryLoopTests(EagerTaskFactoryLoopTests, test_utils.TestCase):
     Task = getattr(tasks, '_CTask', None)
 
+    def test_issue105987(self):
+        code = """if 1:
```
Comment (kumaraditya303) [inline Lib/test/test_asyncio/test_eager_task_factory.py:228]: You can just copy paste the code here itself no need to run in separate python process right?

**Comment by carljm** [comment]
> uncomfortable merging this

I wasn't, was just waiting for CI signal. But glad to have @kumaraditya303 's review!

File: Lib/test/test_asyncio/test_eager_task_factory.py (hunk 2 above)
Comment (chgnrdv) [reply Lib/test/test_asyncio/test_eager_task_factory.py:228]: This gives false positive result, at least on my machine. Also I mentioned that it is common idiom to run code that used to crash in subprocess, e. g. to prevent killing of entire test suite in case of regression.

**Review by kumaraditya303 — APPROVED** [review]
