### PR TITLE
gh-124248: Fix crash in struct when processing 0p fields

### LINKED ISSUE #124248: SystemError/Assertion failure when processing struct with '0p' field
# Crash report

### What happened?

Using `struct` to process zero-width Pascal strings (`"0p"`) can lead to an assertion failure or `SystemError`.

Specifically:
* `struct.pack("<0p", b"")` leads to an assertion failure and seg fault on debug builds (tested with current `main` and 3.13 tip)
* `struct.unpack("<0p", b"")` raises an unexpected `SystemError` (tested with current `main`, 3.13 tip, non-debug builds of 3.8-3.12)

On current `main` (`8f82d9aa219`):
```shell
$ make clean && ./configure --with-pydebug && make -j
$ ./python -VV
Python 3.14.0a0 (heads/main:8f82d9aa219, Sep 19 2024, 11:08:04) [GCC 11.4.0]


$ ./python -c 'import struct; struct.unpack("<0p", b"")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import struct; struct.unpack("<0p", b"")
                   ~~~~~~~~~~~~~^^^^^^^^^^^^
SystemError: Negative size passed to PyBytes_FromStringAndSize


$ ./python -c 'import struct; struct.pack("<0p", b"")'
python: ./Modules/_struct.c:1991: s_pack_internal: Assertion `_Py_STATIC_CAST(Py_ssize_t, _Py_STATIC_CAST(unsigned char, (n))) == (n)' failed.
[1]    186971 IOT instruction (core dumped)  ./python -c 'import struct; struct.pack("<0p", b"")'
```
The same behavior is reproducible on the current 3.13 tip (`112b1704fa6`), and likely previous versions.

PR forthcoming.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.14.0a0 (heads/main:8f82d9aa219, Sep 19 2024, 11:08:04) [GCC 11.4.0]

### Linked PRs
* gh-124251
* gh-124277
* gh-124278

### PR DESCRIPTION
**Pull request by brianschubert**
Fixes gh-124248.

Adds special handling for the case when `code->size` is 0 before attempting to decrement `code->size` or read the first byte under `res`.

After this change, `0p` should behave like `0s`.

### CODE REVIEW

File: Modules/_struct.c [hunk 1]
```diff
@@ -1669,9 +1669,15 @@ s_unpack_internal(PyStructObject *soself, const char *startfrom,
             if (e->format == 's') {
                 v = PyBytes_FromStringAndSize(res, code->size);
             } else if (e->format == 'p') {
-                Py_ssize_t n = *(unsigned char*)res;
-                if (n >= code->size)
-                    n = code->size - 1;
+                Py_ssize_t n;
+                if (code->size == 0) {
+                    n = 0;
+                } else {
```
Comment (tomasr8) [inline Modules/_struct.c]: [PEP7](https://peps.python.org/pep-0007/) ;)
```suggestion
                }
                else {
```

File: Modules/_struct.c [hunk 2]
```diff
@@ -1982,8 +1988,11 @@ s_pack_internal(PyStructObject *soself, PyObject *const *args, int offset,
                     n = PyByteArray_GET_SIZE(v);
                     p = PyByteArray_AS_STRING(v);
                 }
-                if (n > (code->size - 1))
+                if (code->size == 0) {
+                    n = 0;
+                } else if (n > (code->size - 1)) {
```
Comment (tomasr8) [inline Modules/_struct.c]: ditto
```suggestion
                }
                else if (n > (code->size - 1)) {
```

File: Modules/_struct.c (hunk 1 above)
Comment (brianschubert) [reply Modules/_struct.c]: Thanks!

**Review by vstinner — APPROVED** [review]
LGTM

**Comment by vstinner** [comment]
Merged, thanks for the bug report and the fix!
