### PR TITLE
gh-128799: Add frame of except* to traceback when wrapping a naked exception

### LINKED ISSUE #128799: Unexpected location of naked exception wrapped in except* block
# Bug report

### Bug description:

When an `ExceptionGroup` is implicitly constructed by catching a naked exception in an `except*` block, the traceback of the `ExceptionGroup` seems to point to the stackframe above where it is logically created:

```python
def f():
    try:
        raise Exception  # Exception (inner) traceback terminates here
    except* Exception as e:
        raise

f()  # ExceptionGroup (wrapper) traceback terminates here
```
→
```
  + Exception Group Traceback (most recent call last):
  |   File "/home/jobh/src/hypothesis/test_naked_exception.py", line 7, in <module>
  |     f()  # ExceptionGroup (wrapper) traceback terminates here
  |     ^^^
  | ExceptionGroup:  (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/jobh/src/hypothesis/test_naked_exception.py", line 3, in f
    |     raise Exception  # Exception (inner) traceback terminates here
    |     ^^^^^^^^^^^^^^^
    | Exception
    +------------------------------------
```

I'm not sure if this should be called a bug, as it's not specifically documented how the wrapping ExceptionGroup traceback is constructed. But it is surprising, and did cause a bug in hypothesis where the Exception traceback is used to detect whether an exception originates in hypothesis itself or in user code [^1][^2]. The issue being that for wrapped naked exceptions we have to inspect the inner exception since the outer exception appears to be raised by the calling function.

As an alternative to the current behaviour, would it be possible to create the wrapper ExceptionGroup with a traceback pointing to where it is logically triggered - i.e., the `except*` block - rather than initially empty? IMO, that would be less suprising and would allow us to use the traceback without special-casing ExceptionGroup.

[^1]: https://github.com/HypothesisWorks/hypothesis/issues/4183
[^2]: https://github.com/HypothesisWorks/hypothesis/pull/4239

~([edit] Or, if the desire is to avoid branching the traceback between the wrapper and the inner exception, use the outermost frame of the naked exception as the initial ExceptionGroup traceback. This would still avoid the appearance of happening in the caller.)~

### CPython versions tested on:

3.11, 3.12, 3.13

### Operating systems tested on:

Linux

### Linked PRs
* gh-128971
* gh-129299
* gh-129328

### PR DESCRIPTION
**Pull request by iritkatriel**
Fixes #128799.

```
>>> def f():
...     try:
...         raise Exception  # Exception (inner) traceback terminates here
...     except* Exception as e:
...         raise
... 
... f()  # ExceptionGroup (wrapper) traceback terminates here
... 
  + Exception Group Traceback (most recent call last):
  |   File "<python-input-0>", line 7, in <module>
  |     f()  # ExceptionGroup (wrapper) traceback terminates here
  |     ~^^
  |   File "<python-input-0>", line 4, in f
  |     except* Exception as e:
  |         raise
  | ExceptionGroup:  (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "<python-input-0>", line 3, in f
    |     raise Exception  # Exception (inner) traceback terminates here
    |     ^^^^^^^^^^^^^^^
    | Exception
    +------------------------------------
>>> 

```

* Issue: gh-128799

### CODE REVIEW

File: Misc/NEWS.d/next/Core_and_Builtins/2025-01-18-01-06-58.gh-issue-128799.vSNagk.rst [hunk 1]
```diff
@@ -0,0 +1 @@
+Add frame of `except*` to traceback when it wraps a naked exception.
```
Comment (iritkatriel) [inline Misc/NEWS.d/next/Core_and_Builtins/2025-01-18-01-06-58.gh-issue-128799.vSNagk.rst]:
```suggestion
Add frame of ``except*`` to traceback when it wraps a naked exception.
```

**Review by gvanrossum — APPROVED** [review]
This looks right.
