### PR TITLE
gh-128049: Fix type confusion bug with the return value of a custom ExceptionGroup split function

### LINKED ISSUE #128049: Return value of <ExceptionGroup class>.split has insufficient checks leading to a type confusion bug
# Crash report

### What happened?

The following code has checks to make sure the return value is a tuple and of size 2, but only in asserts which means that these checks wont happen on a non-debug build.

https://github.com/python/cpython/blob/b92f101d0f19a1df32050b8502cfcce777b079b2/Python/ceval.c#L2093-L2101

So you can create an ExceptionGroup subclass with a custom `split` function that doesnt return a tuple, and it will try to interpret that object as a tuple.

PoC
```python
class Evil(BaseExceptionGroup):
    def split(self, *args):
        return "NOT A TUPLE!"

print("Running...")
try:
    raise Evil("wow!", [Exception()])
except* Exception:
    pass

print("program should crash before reaching this")
```
Output
```
Running...
Segmentation fault (core dumped)
```

### CPython versions tested on:

3.11, 3.12, 3.13

### Operating systems tested on:

Linux, Windows

### Output from running 'python -VV' on the command line:

_No response_

### Linked PRs
* gh-128079
* gh-128139
* gh-128140

### PR DESCRIPTION
**Pull request by Nico-Posada**
Fixes https://github.com/python/cpython/issues/128049

Still new to this whole process so feedback is appreciated :)

* Issue: gh-128049

### CODE REVIEW

**Comment by iritkatriel** [comment]
Labelling as do not merge until discussion on the issue is resolved.

File: Misc/NEWS.d/next/Core_and_Builtins/2024-12-18-14-22-48.gh-issue-128079.SUD5le.rst [hunk 1]
```diff
@@ -0,0 +1,3 @@
+Fixed a type confusion bug where the caller of an :class:`ExceptionGroup`
+object's :meth:`~BaseExceptionGroup.split` function had improper checks
+implemented leading to any return value being interpreted as a tuple.
```
Comment (iritkatriel) [inline Misc/NEWS.d/next/Core_and_Builtins/2024-12-18-14-22-48.gh-issue-128079.SUD5le.rst]:
```suggestion
Fix a bug where `except*` does not check the type of the return value of an exception's `split()` function, leading to a crash in some cases.
Now when `split` returns an invalid type, `except* ` raises a `TypeError` with the original exception
chained to it.
```

File: Python/ceval.c [hunk 2]
```diff
@@ -2095,8 +2095,15 @@ _PyEval_ExceptionGroupMatch(PyObject* exc_value, PyObject *match_type,
...
+            PyErr_Format(PyExc_TypeError,
+                        "%s.split must return a 2-tuple",
+                        Py_TYPE(exc_value)->tp_name);
+            Py_DECREF(pair);
+            return -1;
+        }
+
         *match = Py_NewRef(PyTuple_GET_ITEM(pair, 0));
         *rest = Py_NewRef(PyTuple_GET_ITEM(pair, 1));
         Py_DECREF(pair);
```
Comment (iritkatriel) [inline Python/ceval.c:2158]: If `split()` returns a tuple of length more than 2, then it used to work but now it won't. So I think we need to change the check from `PyTuple_Size(pair) != 2` to `PyTuple_Size(pair) < 2` to make sure we don't break anything.

Comment (iritkatriel) [reply Python/ceval.c:2109]: This also means we need an entry in `Doc/whatsnew/3.14.rst`, in case there's some other edge case that used to work and now will not.

File: Python/ceval.c [hunk 3]
```diff
@@ -2095,8 +2095,15 @@ _PyEval_ExceptionGroupMatch(PyObject* exc_value, PyObject *match_type,
         if (pair == NULL) {
             return -1;
         }
-        assert(PyTuple_CheckExact(pair));
-        assert(PyTuple_GET_SIZE(pair) == 2);
+
+        if (!PyTuple_CheckExact(pair) || PyTuple_Size(pair) != 2) {
+            PyErr_Format(PyExc_TypeError,
+                        "%s.split must return a 2-tuple",
+                        Py_TYPE(exc_value)->tp_name);
```
Comment (iritkatriel) [inline Python/ceval.c]: Does this work?

```suggestion
            PyErr_Format(PyExc_TypeError,
                         "invalid type returned from %s.split: expected a 2-tuple, got %s",
                        Py_TYPE(exc_value)->tp_name, Py_TYPE(pair)->tp_name);
```

Comment (Nico-Posada) [reply Python/ceval.c]: If we want the error messages to be more descriptive, we should probably split up the checks. It would be a bit confusing to see the message
```
invalid type returned from EG.split: expected a 2-tuple, got tuple
```
if you had returned a tuple of length 1

File: Python/ceval.c (hunk 2 above)
Comment (Nico-Posada) [reply Python/ceval.c:2158]: I think we keep the strict len == 2 check and make the error messages more descriptive to make it easier to resolve if there's anyone out there who has actually made this mistake unintentionally

Comment (iritkatriel) [reply Python/ceval.c:2158]: We don't break things that used to work without deprecation. We also can't backport to stable versions something that could break working code.

This PR is to fix the crash. Tightening the API is a different problem.

File: Python/ceval.c (hunk 3 above)
Comment (iritkatriel) [reply Python/ceval.c]: Good point. I guess we can just omit the ", got %s" part.

Comment (Nico-Posada) [reply Python/ceval.c]: I like the idea of having more descriptive error messages, I was thinking something like this
```c
if (!PyTuple_CheckExact(pair))
{
    PyErr_Format(PyExc_TypeError,
                "%.200s.split must return a tuple, not %.200s",
                Py_TYPE(exc_value)->tp_name, Py_TYPE(pair)->tp_name);
    Py_DECREF(pair);
    return -1;
}

if (PyTuple_GET_SIZE(pair) < 2) {
    PyErr_Format(PyExc_TypeError,
                "%.200s.split must return a 2-tuple, got tuple of size %zd",
                Py_TYPE(exc_value)->tp_name, PyTuple_GET_SIZE(pair));
    Py_DECREF(pair);
    return -1;
}
```

Comment (iritkatriel) [reply Python/ceval.c]: Ok. Should it be `%.200s.split()`?

Comment (Nico-Posada) [reply Python/ceval.c]: I personally don't think so since the func takes in an arg and that makes it look like it doesnt

File: Lib/test/test_except_star.py [hunk 4]
```diff
@@ -951,6 +951,53 @@ def derive(self, excs):
         self.assertExceptionIsLike(exc, FalsyEG("eg", [TypeError(1)]))
         self.assertExceptionIsLike(tes, FalsyEG("eg", [TypeError(1)]))
         self.assertExceptionIsLike(ves, FalsyEG("eg", [ValueError(2)]))
+    
+    def test_bad_exception_group_subclass_split_func(self):
+        # See https://github.com/python/cpython/issues/128049
+        # tuples that return less than 2 values should
+        # result in a type error with the original eg chained to it
```
Comment (iritkatriel) [inline Lib/test/test_except_star.py]:
```suggestion
        # see gh-128049.
```

File: Lib/test/test_except_star.py [hunk 5]
```diff
@@ -951,6 +951,53 @@ def derive(self, excs):
         self.assertExceptionIsLike(exc, FalsyEG("eg", [TypeError(1)]))
         self.assertExceptionIsLike(tes, FalsyEG("eg", [TypeError(1)]))
         self.assertExceptionIsLike(ves, FalsyEG("eg", [ValueError(2)]))
+    
+    def test_bad_exception_group_subclass_split_func(self):
```
Comment (iritkatriel) [inline Lib/test/test_except_star.py]:
```suggestion
    def test_exception_group_subclass_with_bad_split_func(self):
```

File: Lib/test/test_except_star.py [hunk 6]
```diff
@@ -951,6 +951,53 @@ def derive(self, excs):
...
+                return ("NOT A 2-TUPLE!",)
+
+        eg_list = [
+            (BadEG1("eg", [OSError(123), ValueError(456)]),
+             r"split must return a tuple, not str"),
+            (BadEG2("eg", [OSError(123), ValueError(456)]),
+             r"split must return a 2-tuple, got tuple of size 1")
+        ]
+
+        for EG, MSG in eg_list:
```
Comment (iritkatriel) [inline Lib/test/test_except_star.py]:
```suggestion
        for eg_class, msg in eg_list:
```

File: Lib/test/test_except_star.py [hunk 7]
```diff
@@ -951,6 +951,53 @@ def derive(self, excs):
...
+            with self.assertRaisesRegex(TypeError, MSG) as m:
+                try:
+                    raise EG
+                except* ValueError:
+                    pass
+                except* OSError:
+                    pass
+
```
Comment (iritkatriel) [inline Lib/test/test_except_star.py:980]: let's assert that `m.exception` is the `TypeError` as well.

File: Lib/test/test_except_star.py [hunk 8]
```diff
@@ -951,6 +951,53 @@ def derive(self, excs):
...
+            self.assertExceptionIsLike(m.exception.__context__, EG)
+
+        # although it isn't expected, still allow tuples of length > 2
+        # all tuple items past the second one will be ignored
+        # this quirk may be deprecated in the future
```
Comment (iritkatriel) [inline Lib/test/test_except_star.py]:
```suggestion
        # we allow tuples of length > 2 for backwards compatibility
```

File: Python/ceval.c [hunk 9]
```diff
@@ -2095,8 +2095,28 @@ _PyEval_ExceptionGroupMatch(PyObject* exc_value, PyObject *match_type,
         if (pair == NULL) {
             return -1;
         }
-        assert(PyTuple_CheckExact(pair));
-        assert(PyTuple_GET_SIZE(pair) == 2);
+
+        if (!PyTuple_CheckExact(pair))
+        {
```
Comment (iritkatriel) [inline Python/ceval.c]:
```suggestion
        if (!PyTuple_CheckExact(pair)) {
```

File: Python/ceval.c [hunk 10]
```diff
@@ -2095,8 +2095,28 @@ _PyEval_ExceptionGroupMatch(PyObject* exc_value, PyObject *match_type,
...
+        }
+
+        // NOTE due to a previous bug which allowed tuples of length > 2 to
+        // work without problem, we are still allowing them to work even
+        // though the error says otherwise
+        if (PyTuple_GET_SIZE(pair) < 2) {
+            PyErr_Format(PyExc_TypeError,
+                        "%.200s.split must return a 2-tuple, "
+                        "got tuple of size %zd",
+                        Py_TYPE(exc_value)->tp_name, PyTuple_GET_SIZE(pair));
```
Comment (iritkatriel) [inline Python/ceval.c]:
```suggestion
            PyErr_Format(PyExc_TypeError,
                         "%.200s.split must return a 2-tuple, "
                         "got tuple of size %zd",
                         Py_TYPE(exc_value)->tp_name, PyTuple_GET_SIZE(pair));
```

File: Python/ceval.c [hunk 11]
```diff
@@ -2095,8 +2095,28 @@ _PyEval_ExceptionGroupMatch(PyObject* exc_value, PyObject *match_type,
...
+            PyErr_Format(PyExc_TypeError,
+                        "%.200s.split must return a tuple, not %.200s",
+                        Py_TYPE(exc_value)->tp_name, Py_TYPE(pair)->tp_name);
+            Py_DECREF(pair);
+            return -1;
+        }
+
+        // NOTE due to a previous bug which allowed tuples of length > 2 to
+        // work without problem, we are still allowing them to work even
+        // though the error says otherwise
```
Comment (iritkatriel) [inline Python/ceval.c]:
```suggestion
        // allow tuples of length > 2 for backwards compatibility
```

**Review by iritkatriel — COMMENTED** [review]
Looks good. I just made a few stylistic suggestions.

File: Lib/test/test_except_star.py (hunk 7 above)
Comment (Nico-Posada) [reply Lib/test/test_except_star.py:980]: assertRaisesRegex should be doing that

**Review by iritkatriel — APPROVED** [review]

**Comment by iritkatriel** [comment]
Thank you @Nico-Posada !
