### PR TITLE
gh-119506: fix `_io.TextIOWrapper.write()` write during flush

### LINKED ISSUE #119506: `_io.TextIOWrapper.write`: write during flush causes `pending_bytes` length mismatch
# Crash report

### What happened?

Bisected to #24592.
Simple repro:
```python
import _io

class MyIO(_io.BytesIO):
    def __init__(self):
        _io.BytesIO.__init__(self)
        self.writes = []

    def write(self, b):
        self.writes.append(b)
        tw.write("c")
        return len(b)

buf = MyIO()
tw = _io.TextIOWrapper(buf)

CHUNK_SIZE = 8192

tw.write("a" * (CHUNK_SIZE - 1))
tw.write("b" * 2)

tw.flush()

assert b''.join(tw.buffer.writes) == b"a" * (CHUNK_SIZE - 1) + b"b" * 2 + b"c"
```
On debug build it causes C assertion failure:
```
python: ./Modules/_io/textio.c:1582: _textiowrapper_writeflush: Assertion `PyUnicode_GET_LENGTH(pending) == self->pending_bytes_count' failed.

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7c84537 in __GI_abort () at abort.c:79
#2  0x00007ffff7c8440f in __assert_fail_base (fmt=0x7ffff7dfb688 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=0x555555a24d40 "PyUnicode_GET_LENGTH(pending) == self->pending_bytes_count", file=0x555555a25332 "./Modules/_io/textio.c", line=1582, 
    function=<optimized out>) at assert.c:92
#3  0x00007ffff7c93662 in __GI___assert_fail (assertion=assertion@entry=0x555555a24d40 "PyUnicode_GET_LENGTH(pending) == self->pending_bytes_count", 
    file=file@entry=0x555555a25332 "./Modules/_io/textio.c", line=line@entry=1582, 
    function=function@entry=0x555555a256b0 <__PRETTY_FUNCTION__.9> "_textiowrapper_writeflush") at assert.c:101
#4  0x00005555559102b9 in _textiowrapper_writeflush (self=self@entry=0x7ffff77896d0) at ./Modules/_io/textio.c:1582
#5  0x000055555591065d in _io_TextIOWrapper_flush_impl (self=0x7ffff77896d0) at ./Modules/_io/textio.c:3092
#6  0x0000555555910791 in _io_TextIOWrapper_flush (self=<optimized out>, _unused_ignored=<optimized out>) at ./Modules/_io/clinic/textio.c.h:1105
#7  0x0000555555693483 in method_vectorcall_NOARGS (func=0x7ffff7731250, args=0x7ffff7fc1070, nargsf=<optimized out>, kwnames=<optimized out>)
    at Objects/descrobject.c:447
#8  0x0000555555680d7c in _PyObject_VectorcallTstate (tstate=0x555555be4678 <_PyRuntime+294136>, callable=0x7ffff7731250, args=0x7ffff7fc1070, 
    nargsf=9223372036854775809, kwnames=0x0) at ./Include/internal/pycore_call.h:168
#9  0x0000555555680e97 in PyObject_Vectorcall (callable=callable@entry=0x7ffff7731250, args=args@entry=0x7ffff7fc1070, nargsf=<optimized out>, 
    kwnames=kwnames@entry=0x0) at Objects/call.c:327
#10 0x000055555580876d in _PyEval_EvalFrameDefault (tstate=tstate@entry=0x555555be4678 <_PyRuntime+294136>, frame=0x7ffff7fc1020, throwflag=throwflag@entry=0)
    at Python/generated_cases.c.h:813
...
```

If `_io.TextIOWrapper.write()` tries to store more than `self->chunk_size` data in `self->pending_bytes`, it calls `_textiowrapper_writeflush()`:
https://github.com/python/cpython/blob/b48a3dbff4d70e72797e67b46276564fc63ddb89/Modules/_io/textio.c#L1726-L1733
`_textiowrapper_writeflush()` flushes `self->pending_bytes` contents to wrapped buffer through `write()` method call:
https://github.com/python/cpython/blob/b48a3dbff4d70e72797e67b46276564fc63ddb89/Modules/_io/textio.c#L1621-L1628
The problem is that call to `write()` method can cause `_io.TextIOWrapper.write()` call (directly, as in repro, or from other thread), which re-sets `self->pending_bytes` and `self->pending_bytes_count` values.

### CPython versions tested on:

3.10, 3.11, 3.12, CPython main branch

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.14.0a0 (heads/main:e94dbe4ed8, May 24 2024, 00:47:49) [GCC 10.2.1 20210110]

### Linked PRs
* gh-119507
* gh-119964
* gh-119965
* gh-120314

### PR DESCRIPTION
**Pull request by chgnrdv**
Fixes #119506

* check if call to `_textiowrapper_writeflush()` has left any data in `self->pending_bytes`. If so, store them in `self->pending_bytes` after `b`
* add test

* Issue: gh-119506

### CODE REVIEW

**Comment by chgnrdv** [comment]
cc @methane @eryksun

**Comment by methane** [comment]
Thank you. The patch looks good to me.

**Comment by chgnrdv** [comment]
Now it crashes if any of these calls fails: length of`self->pending_bytes` doesn't match `self->pending_bytes_count` on return.
https://github.com/python/cpython/blob/bf5b6467f8cc06759f3396ab1a8ad64fe7d1db2e/Modules/_io/textio.c#L1735
https://github.com/python/cpython/blob/bf5b6467f8cc06759f3396ab1a8ad64fe7d1db2e/Modules/_io/textio.c#L1745

File: Modules/_io/textio.c [hunk 1]
```diff
@@ -1719,21 +1719,31 @@ _io_TextIOWrapper_write_impl(textio *self, PyObject *text)
...
             Py_DECREF(b);
             return NULL;
         }
+        if (self->pending_bytes) {
+            // gh-119506: call to _textiowrapper_writeflush()
+            // can write new data to pending_bytes
+            pending = self->pending_bytes;
+            self->pending_bytes = b;
+            b = pending;
+        }
```
Comment (methane) [inline Modules/_io/textio.c]: why do you swap data here?
* `self->pending` can be list
* call from other thread might be returned already.
  * "first returned first write" seems correct than "first called first write".

File: Modules/_io/textio.c [hunk 2]
```diff
@@ -1719,21 +1719,31 @@ _io_TextIOWrapper_write_impl(textio *self, PyObject *text)
...
     }
 
-    if (self->pending_bytes == NULL) {
-        self->pending_bytes_count = 0;
-        self->pending_bytes = b;
-    }
-    else if (self->pending_bytes_count + bytes_len > self->chunk_size) {
+    PyObject *pending = self->pending_bytes;
+
+    if (self->pending_bytes_count + bytes_len > self->chunk_size) {
```
Comment (methane) [inline Modules/_io/textio.c]: How about `while` instead of `if`?

**Comment by elistevens** [comment]
This PR seems to be addressing a similar issue as https://github.com/python/cpython/pull/119107 but I don't think that this PR fixes the race condition present when multi-threaded writes happen.

File: Modules/_io/textio.c (hunk 2 above)
Comment (elistevens) [reply Modules/_io/textio.c]: That would also need a check to make sure that `bytes_len > self->chunk_size` isn't true.

File: Modules/_io/textio.c (hunk 1 above)
Comment (elistevens) [reply Modules/_io/textio.c]: If you look at the test case, where flushing the stream triggers a write, it's not a threading thing, it's because of write being called recursively.

**Comment by elistevens** [comment]
After fixing my original test case, I think that this minimal patch addresses the issue in practical terms:

```
diff --git a/Modules/_io/textio.c b/Modules/_io/textio.c
index 3de4c06704..e084d04428 100644
--- a/Modules/_io/textio.c
+++ b/Modules/_io/textio.c
@@ -1701,16 +1701,16 @@ _io_TextIOWrapper_write_impl(textio *self, PyObject *text)
         bytes_len = PyBytes_GET_SIZE(b);
     }
 
-    if (self->pending_bytes == NULL) {
-        self->pending_bytes_count = 0;
-        self->pending_bytes = b;
-    }
-    else if (self->pending_bytes_count + bytes_len > self->chunk_size) {
+    if (self->pending_bytes_count + bytes_len > self->chunk_size) {
         // Prevent to concatenate more than chunk_size data.
         if (_textiowrapper_writeflush(self) < 0) {
             Py_DECREF(b);
             return NULL;
         }
+    }
+
+    if (self->pending_bytes == NULL) {
+        assert(self->pending_bytes_count == 0);
         self->pending_bytes = b;
     }
     else if (!PyList_CheckExact(self->pending_bytes)) {
```
there is still an issue where since there isn't a lock AFAIK, another thread could modify `self->pending_bytes` between check and assignment here:
```
    if (self->pending_bytes == NULL) {
        assert(self->pending_bytes_count == 0);
        self->pending_bytes = b;
    }
```
but that doesn't seem to be an issue in practice.

**Comment by elistevens** [comment]
I should note that there's a similar race condition issue in `_textiowrapper_writeflush` where we don't ensure that the list hasn't been modified between `for (Py_ssize_t i = 0; i < PyList_GET_SIZE(pending); i++) {` and `self->pending_bytes = NULL;`.

**Comment by methane** [comment]
> I should note that there's a similar race condition issue in `_textiowrapper_writeflush` where we don't ensure that the list hasn't been modified between `for (Py_ssize_t i = 0; i < PyList_GET_SIZE(pending); i++) {` and `self->pending_bytes = NULL;`.

Note that default Python build with GIL doesn't have such race.

`_textiowrapper_writeflush` releases GIL when it calls `buffer.write()`:

```
    self->pending_bytes_count = 0;
    self->pending_bytes = NULL;
    Py_DECREF(pending);

    PyObject *ret;
    do {
        ret = PyObject_CallMethodOneArg(self->buffer, &_Py_ID(write), b);
    } while (ret == NULL && _PyIO_trap_eintr());
```

Other thread may call TextIOWrapper.write(b) and it appends b to self->pending_bytes.
We can not assume `self->pending_bytes == NULL` and `self->pending_bytes_count == 0` after `_textiowrapper_writeflush`. That was the bug.

**Comment by elistevens** [comment]
> Note that default Python build with GIL doesn't have such race.
> _textiowrapper_writeflush releases GIL when it calls buffer.write()

Ah, that makes sense.  Thank you for explaining!

File: Modules/_io/textio.c (hunk 1 above)
Comment (methane) [reply Modules/_io/textio.c]: Even single thread case, it is not possble to guarantee "first called, first written."
Simple implementation is more important.

**Comment by elistevens** [comment]
Thanks for bringing this home!  Does this qualify as a security issue?  I'm wondering if it will be backported to 3.10.

File: Modules/_io/textio.c [hunk 3]
```diff
@@ -1737,6 +1747,9 @@ _io_TextIOWrapper_write_impl(textio *self, PyObject *text)
             Py_DECREF(b);
             return NULL;
         }
+        // Since Python 3.12, allocating GC object won't trigger GC and release
+        // GIL. See https://github.com/python/cpython/issues/97922
+        assert(!PyList_CheckExact(self->pending_bytes));
```
Comment (methane) [inline Modules/_io/textio.c:1752]: I am not sure about this patch will be backported to security branches.
If it will, this line needs additional fixes. So backport is not simple.
