### PR TITLE
gh-79579: Improve DML query detection in sqlite3

### LINKED ISSUE #79579: SQLite incorrect row count for UPDATE
BPO | [35398](https://bugs.python.org/issue35398)
--- | :---
Nosy | @berkerpeksag, @lysnikolaou, @tirkarthi, @erlend-aasland
PRs | <li>python/cpython#10913</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-12-04.02:27:45.503>
labels = ['3.8', '3.7', 'library']
title = 'SQLite incorrect row count for UPDATE'
updated_at = <Date 2021-08-11.21:01:29.425>
user = 'https://bugs.python.org/MontanaLow'
```

bugs.python.org fields:
```python
activity = <Date 2021-08-11.21:01:29.425>
actor = 'erlendaasland'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2018-12-04.02:27:45.503>
creator = 'Montana Low'
dependencies = []
files = []
hgrepos = []
issue_num = 35398
keywords = ['patch']
message_count = 4.0
messages = ['331006', '331069', '331090', '399417']
nosy_count = 7.0
nosy_names = ['ghaering', 'zzzeek', 'berker.peksag', 'lys.nikolaou', 'xtreak', 'Montana Low', 'erlendaasland']
pr_nums = ['10913']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue35398'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

### PR DESCRIPTION
**Pull request by erlend-aasland**
Strip whitespace and comments from queries in order to harden DML query
detection.

Resolves #79579

### CODE REVIEW

**Comment by erlend-aasland** [comment]
cc. @animalize

**Comment by erlend-aasland** [comment]
If the `sqlite3_normalized_sql` API becomes enabled by default in the future, we can get rid of our own parser helper, and just use `sqlite3_normalized_sql` to strip whitespace and comments. We'll see what the future brings.

File: Misc/NEWS.d/next/Library/2022-06-06-12-58-27.gh-issue-79579.e8rB-M.rst [hunk 1]
```diff
@@ -0,0 +1,2 @@
+:mod:`sqlite3` now correctly detects DML queries, even when prefixed with
+comments. Patch by Erlend E. Aasland.
```
Comment (erlend-aasland) [inline Misc/NEWS.d/next/Library/2022-06-06-12-58-27.gh-issue-79579.e8rB-M.rst]: I think the NEWS entry can still be improved. Perhaps:

```suggestion
:mod:`sqlite3` now strips leading whitespace and comments from SQL queries,
thus improving DML detection. Patch by Erlend E. Aasland.
```

File: Modules/_sqlite/statement.c [hunk 2]
```diff
@@ -139,23 +131,27 @@ stmt_traverse(pysqlite_Statement *self, visitproc visit, void *arg)
 }
 
 /*
- * Checks if there is anything left in an SQL string after SQLite compiled it.
+ * Strips leading whitespace and SQL comments from input string and returns a
+ * pointer to the first non-whitespace, non-comment character.
```
Comment (erlend-aasland) [inline Modules/_sqlite/statement.c]:
```suggestion
 * Strip leading whitespace and SQL comments from input string, and return a
 * pointer to the first non-whitespace, non-comment character.
```

File: Lib/test/test_sqlite3/test_dbapi.py [hunk 3]
```diff
@@ -906,6 +906,31 @@ def test_rowcount_update_returning(self):
         self.assertEqual(self.cu.fetchone()[0], 1)
         self.assertEqual(self.cu.rowcount, 1)
 
+    def test_rowcount_prefixed_with_comment(self):
+        # gh-79579: rowcount is updated even if query is prefixed with comments
+        #self.cu.execute("/* foo */ insert into test(name) values (?)", ('foo',))
```
Comment (erlend-aasland) [inline Lib/test/test_sqlite3/test_dbapi.py]:
```suggestion
```

File: Misc/NEWS.d/next/Library/2022-06-06-12-58-27.gh-issue-79579.e8rB-M.rst (hunk 1 above)
Comment (ghost) [reply Misc/NEWS.d/next/Library/2022-06-06-12-58-27.gh-issue-79579.e8rB-M.rst]: The current code already skips whitespace.
Something like this: Correctly detect DML statement when there are leading comments.

File: Modules/_sqlite/statement.c [hunk 4]
```diff
@@ -165,6 +161,9 @@ static int pysqlite_check_remaining_sql(const char* tail)
                 break;
             case ' ':
             case '\t':
+                if (state == COMMENTEND_1) {
+                    state = IN_COMMENT;
+                }
                 break;
             case '\n':
             case 13:
```
Comment (ghost) [inline Modules/_sqlite/statement.c]: Since we are here, how about change `13` to '\r' for better readability.

**Review by ghost — COMMENTED** [review]
Please merge after a few days, maybe there is something not currently thought of.

File: Modules/_sqlite/statement.c (hunk 4 above)
Comment (erlend-aasland) [reply Modules/_sqlite/statement.c]: +1

File: Misc/NEWS.d/next/Library/2022-06-06-12-58-27.gh-issue-79579.e8rB-M.rst (hunk 1 above)
Comment (erlend-aasland) [reply Misc/NEWS.d/next/Library/2022-06-06-12-58-27.gh-issue-79579.e8rB-M.rst]: Thanks!

File: Modules/_sqlite/statement.c [hunk 5]
```diff
@@ -82,20 +82,12 @@ pysqlite_statement_create(pysqlite_Connection *connection, PyObject *sql)
...
-            case '\t':
-                continue;
-        }
-
+    const char *p = lstrip_sql(sql_cstr);
+    if (p != NULL) {
         is_dml = (PyOS_strnicmp(p, "insert", 6) == 0)
                   || (PyOS_strnicmp(p, "update", 6) == 0)
                   || (PyOS_strnicmp(p, "delete", 6) == 0)
                   || (PyOS_strnicmp(p, "replace", 7) == 0);
```
Comment (erlend-aasland) [inline Modules/_sqlite/statement.c:81]: Note this remark in the `sqlite3_changes` docs:

> auxiliary changes caused by [triggers](https://www.sqlite.org/lang_createtrigger.html), [foreign key actions](https://www.sqlite.org/foreignkeys.html#fk_actions) or [REPLACE](https://www.sqlite.org/lang_replace.html) constraint resolution are not counted.

This is a separate issue, out of scope for this PR.

**Comment by erlend-aasland** [comment]
Thanks for reviewing, Ma Lin. Highly appreciated 🙏🏻

The buildbot run for 5918fbed3b50177058b128ee64662f7d6a965869 completed without failures.

I'll let this PR sit around for some days to give Serhiy a chance to review. I'll merge sometime next week.

**Comment by animalize** [comment]
As I said before, I'm not a deep user of SQL. So when in very complex situations, there may be things that I can't think of.
But I will try my best to learn and understand.

File: Modules/_sqlite/statement.c [hunk 6]
```diff
@@ -139,23 +131,25 @@ stmt_traverse(pysqlite_Statement *self, visitproc visit, void *arg)
...
-    const char* pos = tail;
+    const char *pos = sql;
 
     parse_remaining_sql_state state = NORMAL;
 
     for (;;) {
         switch (*pos) {
             case 0:
-                return 0;
+                return NULL;
```
Comment (erlend-aasland) [inline Modules/_sqlite/statement.c]: Note to self: this `case` makes the `return NULL` at the end of the function unreachable. This can be easily fixed with a tiny refactor, where `case 0` is removed:

```c
lstrip_sql(const char *sql)
{
    parse_remaining_sql_state state = NORMAL;

    for (const char *pos = sql; *pos; pos++) {
        ...
    }

    return NULL;
```

I'll add that in a separate PR.

**Comment by animalize** [comment]
In current code, this code can't be processed correctly.
```sql
-
- INSERT INTO test(income) VALUES(?)
```
Maybe there are some corner cases that cannot be handled correctly as well.

IMHO, sqlite's code is simple and robust.
https://github.com/sqlite/sqlite/blob/37d4ec86bfa78c31732132b7729b8ce0e47da891/src/complete.c#L158-L164

**Comment by erlend-aasland** [comment]
> In current code, this code can't be processed correctly.

With "current", you mean the PR or `main`?

> IMHO, SQLite's code is simple and robust [...]
> It uses a loop to skip comment, we can use this method instead of the state machine.

Yes, I thought about using something like that, but used the existing helper function to reduce the size of the diff. I already fixed another bug in the current helper, so it does not surprise me that there are more. I'll add something similar to what's in the SQLite sources. Thanks for helping improve this PR by finding more corner cases :)

**Comment by erlend-aasland** [comment]
Note that `\r` is swallowed by SQLite line comments; only `\n` ends them.

**Comment by erlend-aasland** [comment]
> It uses a loop to skip comment, we can use this method instead of the state machine.

Also note that the loop in complete.c _is_ a state machine ;) (but one that is simpler than the old thing we've got in the sqlite3 extension module)

**Comment by erlend-aasland** [comment]
Buildbots finished without complaints. Does this look good to you, @animalize? Can you spot further corner-cases? Code coverage for `statement.c` has never been better 😎

**Comment by erlend-aasland** [comment]
I think the PR is fine to land now. I'll merge it in a couple of days. If you've got objections, please chime in @animalize.

File: Modules/_sqlite/statement.c (hunk 5 above)
Comment (erlend-aasland) [reply Modules/_sqlite/statement.c:81]: See also [Discussion on Discourse](https://discuss.python.org/t/introducing-a-pep-249-compliant-transaction-behaviour-to-sqlite3/16516?u=erlendaasland)
