### PR TITLE
gh-143674: Document F/D complex format characters in struct module

### LINKED ISSUE #143674: Struct module docstring lacks format characters for complex types (F/D)
```pycon
>>> import struct
>>> print(struct.__doc__)
Functions to convert between Python values and C structs.
Python bytes objects are used to hold the data representing the C struct
and also as format strings (explained below) to describe the layout of data
in the C struct.

The optional first format char indicates byte order, size and alignment:
  @: native order, size & alignment (default)
  =: native order, std. size & alignment
  <: little-endian, std. size & alignment
  >: big-endian, std. size & alignment
  !: same as >

The remaining chars indicate types of args and must match exactly;
these can be preceded by a decimal repeat count:
  x: pad byte (no data); c:char; b:signed byte; B:unsigned byte;
  ?: _Bool (requires C99; if not available, char is used instead)
  h:short; H:unsigned short; i:int; I:unsigned int;
  l:long; L:unsigned long; f:float; d:double; e:half-float.
Special cases (preceding decimal count indicates length):
  s:string (array of char); p: pascal string (with count byte).
Special cases (only available in native format):
  n:ssize_t; N:size_t;
  P:an integer type that is wide enough to hold a pointer.
Special case (not in native mode unless 'long long' in platform C):
  q:long long; Q:unsigned long long
Whitespace between formats is ignored.

The variable struct.error is an exception raised on errors.

```

### Linked PRs
* gh-143675
* gh-143879
* gh-143918

### PR DESCRIPTION
**Pull request by moneebullah25**
Fixes https://github.com/python/cpython/issues/143674

## Changes
- Added documentation for `F` (complex from two floats) and `D` (complex from two doubles) format characters to the struct module docstring

## Rationale
These format characters are implemented in the struct module (lines 858-859, 1189-1190, 1504-1505 in Modules/_struct.c) but were missing from the module's docstring documentation. Users consulting the docstring with `help(struct)` would not know these options exist.

## Testing
- Verified that F and D format characters are implemented in the code
- Confirmed the docstring change follows the existing format and style
- The change is minimal and only adds missing documentation

## Checklist
- [x] Minimal change - only added missing documentation
- [x] Followed existing docstring format and style
- [x] Commit message follows CPython guidelines

* Issue: gh-143674

### CODE REVIEW

**Comment by moneebullah25** [comment]
> Most changes to Python [require a NEWS entry](https://devguide.python.org/core-developers/committing/#updating-news-and-what-s-new-in-python). Add one using the [blurb_it](https://blurb-it.herokuapp.com) web app or the [blurb](https://pypi.org/project/blurb/) command-line tool.
> 
> If this change has little impact on Python users, wait for a maintainer to apply the `skip news` label instead.

No NEWS entry is required for this pull request because this PR is a documentation-only change

**Comment by moneebullah25** [comment]
> Are you using generative AI for this pr?

Yep I use it for commit message and comment

File: Modules/_struct.c [hunk 1]
```diff
@@ -2689,6 +2689,7 @@ these can be preceded by a decimal repeat count:\n\
   ?: _Bool (requires C99; if not available, char is used instead)\n\
   h:short; H:unsigned short; i:int; I:unsigned int;\n\
   l:long; L:unsigned long; f:float; d:double; e:half-float.\n\
+  F:complex (two floats); D:complex (two doubles).\n\
```
Comment (skirpichev) [inline Modules/_struct.c]:
```suggestion
  F:float complex; D:double complex.\n\
```

**Review by skirpichev — APPROVED** [review]

**Comment by quanghuynh10111-lab** [comment]
[Uploading JailbreakInterposer.c…]()
