### PR TITLE
gh-92898: Make _Py_Cast C++ version compatible with cast operator

### LINKED ISSUE #92898: changes to PyObject casting macros causing build failures with python-greenlet
**Bug report**

There have been changes to how the macros for casting PyObject pointers per https://github.com/python/cpython/pull/91959#issuecomment-1114651243  by @vstinner any new compiler warnings are a regression.  

There were two types of errors in greenlet, one related to const correctness which has been fixed via https://github.com/python/cpython/pull/92138) and one related to casting wrapper classes (that has not been fixed).

Per @serge-sans-paille in https://github.com/python/cpython/pull/92138#issuecomment-1116983125

> That's an interesting situation: greenlets are written in C++, and the object that raises issues is of type greenlet::refs::OwnedErrPiece that has a conversion operator to PyObject* (namely: https://github.com/python-greenlet/greenlet/blob/be41e1a24925326b72a02ef5cb6d1ed9643eb062/src/greenlet/greenlet_refs.hpp#L924 ) Using C-style cast or static_cast directly uses that operator so that's fine. But a reinterpret_cast won't work.

and suggests a patch to CPython.

https://github.com/python-greenlet/greenlet/pull/302 is a fix on the greenlet side.

The key line of the error is

```
src/greenlet/greenlet_refs.hpp: In member function ‘void greenlet::refs::PyErrPieces::normalize()’:
/home/tcaswell/.pybuild/bleeding/include/python3.12/pyport.h:30:25: error: invalid cast from type ‘greenlet::refs::OwnedErrPiece’ to type ‘const PyObject*’ {aka ‘const _object*’}
   30 |        const_cast<type>(reinterpret_cast<const type>(expr))
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This is also affecting https://github.com/python/pyperformance/issues/198

A bunch of links: https://github.com/python/cpython/issues/92800#issuecomment-1126809930

**Your environment**

- CPython versions tested on: main branch
- Operating system and architecture: linux and x86_64

### PR DESCRIPTION
**Pull request by serge-sans-paille**
Use the adequate kind of cast based on the macro argument: const ref, cont
pointer, ref or pointer.

This should be compatible with C++ overloads.

Fix #92898

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
cc @vstinner

**Review by corona10 — CHANGES_REQUESTED** [review]
Would you like to add NEWS.d about compatible?

File: Lib/test/_testcppext.cpp [hunk 1]
```diff
@@ -31,6 +31,7 @@ test_api_casts(PyObject *Py_UNUSED(module), PyObject *Py_UNUSED(args))
         return nullptr;
     }
 
+
```
Comment (corona10) [inline Lib/test/_testcppext.cpp]:
```suggestion
```

**Comment by serge-sans-paille** [comment]
@corona10 I'm not sure, there's already an entry

```
.. date: 2022-04-26-16-51-31
.. gh-issue: 91320
.. nonce: QDHmTv
.. section: C API

Fix C++ compiler warnings about "old-style cast" (``g++ -Wold-style-cast``)
in the Python C API. Use C++ ``reinterpret_cast<>`` and ``static_cast<>``
casts when the Python C API is used in C++. Patch by Victor Stinner.
```

And this is just patching that  entry

**Comment by tacaswell** [comment]
I am now seeing errors compiling numpy with this branch:

```
      In file included from /home/tcaswell/.pybuild/bleeding/include/python3.12/Python.h:38,
                       from numpy/core/include/numpy/npy_common.h:5,
                       from numpy/core/include/numpy/npy_math.h:8,
                       from numpy/core/src/npysort/selection.cpp:18:
      /home/tcaswell/.pybuild/bleeding/include/python3.12/pyport.h:31:1: error: template with C linkage
         31 | template <typename type, typename expr_type>
            | ^~~~~~~~
      numpy/core/include/numpy/npy_math.h:5:1: note: ‘extern "C"’ linkage started here
          5 | extern "C" {
            | ^~~~~~~~~~
      /home/tcaswell/.pybuild/bleeding/include/python3.12/pyport.h:36:1: error: template with C linkage
         36 | template <typename type, typename expr_type>
            | ^~~~~~~~
      numpy/core/include/numpy/npy_math.h:5:1: note: ‘extern "C"’ linkage started here
          5 | extern "C" {
            | ^~~~~~~~~~
      /home/tcaswell/.pybuild/bleeding/include/python3.12/pyport.h:41:1: error: template with C linkage
         41 | template <typename type, typename expr_type>
            | ^~~~~~~~
      numpy/core/include/numpy/npy_math.h:5:1: note: ‘extern "C"’ linkage started here
          5 | extern "C" {
            | ^~~~~~~~~~
      /home/tcaswell/.pybuild/bleeding/include/python3.12/pyport.h:46:1: error: template with C linkage
         46 | template <typename type, typename expr_type>
            | ^~~~~~~~
      numpy/core/include/numpy/npy_math.h:5:1: note: ‘extern "C"’ linkage started here
          5 | extern "C" {
            | ^~~~~~~~~~

```

```
g++ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DNO_ATLAS_INFO=1 -DHAVE_CBLAS -I/usr/local/include -I/home/tcaswell/.virtualenvs/bleeding/include -Ibuild/src.linux-x86_64-3.12/numpy/core/src/multiarray -Ibuild/src.linux-x86_64-3.12/numpy/core/src/common -Ibuild/src.linux-x86_64-3.12/numpy/core/src/umath -Inumpy/core/include -Ibuild/src.linux-x86_64-3.12/numpy/core/include/numpy -Ibuild/src.linux-x86_64-3.12/numpy/distutils/include -Ibuild/src.linux-x86_64-3.12/numpy/core/src/npysort -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/src/_simd -I/home/tcaswell/.virtualenvs/bleeding/include -I/home/tcaswell/.pybuild/bleeding/include/python3.12 -Ibuild/src.linux-x86_64-3.12/numpy/core/src/common -Ibuild/src.linux-x86_64-3.12/numpy/core/src/npymath -c numpy/core/src/npysort/selection.cpp -o build/temp.linux-x86_64-3.12/numpy/core/src/npysort/selection.o -MMD -MF build/temp.linux-x86_64-3.12/numpy/core/src/npysort/selection.o.d -msse -msse2 -msse3 -std=c++11 -D__STDC_VERSION__=0 -fno-exceptions -fno-rtti
```

**Comment by serge-sans-paille** [comment]
@tacaswell indeed. I can work around this :-)

**Comment by tacaswell** [comment]
@serge-sans-paille I should note this is with numpy main, I have not gone back to see if released versions work or not.

**Comment by serge-sans-paille** [comment]
@tacaswell should be good now?

**Comment by tacaswell** [comment]
Through numpy, starting scipy.  Will update if the whole environment builds cleanly (including greenlet main).

**Comment by tacaswell** [comment]
It built clean including master-branch greenlet 👍🏻

**Review by corona10 — APPROVED** [review]

**Comment by vstinner** [comment]
I created a follow-up PR: https://github.com/python/cpython/pull/93111
