### PR TITLE
gh-99266: ctypes: Preserve a more detailed exception in _SimpleCData.from_param

### LINKED ISSUE #99266: ctypes: wrong exception message in docs
# Documentation

The ctypes docs say that the message of the `ArgumentError` for the presented example should be as follows:
image

In fact, it looks like this:
```
>>> strchr = libc.strchr
>>> strchr.restype = c_char_p
>>> strchr.argtypes = [c_char_p, c_char]
>>> 
>>> strchr(b"abcdef", b"def")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ctypes.ArgumentError: argument 2: TypeError: wrong type
```

I will prepare a PR.

* PR: gh-99267

* PR: gh-99760

### PR DESCRIPTION
**Pull request by kamilturek**
Closes #99266.

The exception from `fd->setfunc` is now saved and then restored if the object doesn't have an `_as_parameter_`.

* Issue: gh-99266

### CODE REVIEW

**Review by eric-wieser — APPROVED** [review]
This LGTM, thanks!

**Review by kumaraditya303 — CHANGES_REQUESTED** [review]
Please add some tests, the doctests are not run by the buildbots.

**Comment by kamilturek** [comment]
I have made the requested changes; please review again

File: Modules/_ctypes/_ctypes.c [hunk 1]
```diff
@@ -2244,10 +2245,16 @@ PyCSimpleType_from_param(PyObject *type, PyObject *value)
         value = PyCSimpleType_from_param(type, as_parameter);
         _Py_LeaveRecursiveCall();
         Py_DECREF(as_parameter);
+        Py_XDECREF(exc);
+        Py_XDECREF(val);
+        Py_XDECREF(tb);
```
Comment (eric-wieser) [inline Modules/_ctypes/_ctypes.c:2256]: Doesn't this need to be before line 2243? otherwise you might leak these references.

Comment (kamilturek) [reply Modules/_ctypes/_ctypes.c:2256]: Yes, I think you're right. I pushed an update. Thanks! 🙌

Comment (kumaraditya303) [reply Modules/_ctypes/_ctypes.c:2256]: It is also required on line 2238

**Review by kumaraditya303 — APPROVED** [review]
LGTM, thanks!

File: Misc/NEWS.d/next/Library/2022-11-24-21-52-31.gh-issue-99266.88GcV9.rst [hunk 2]
```diff
@@ -0,0 +1 @@
+Make ctypes fundamental data types preserve a more detail exception in ``from_param``.
```
Comment (kumaraditya303) [inline Misc/NEWS.d/next/Library/2022-11-24-21-52-31.gh-issue-99266.88GcV9.rst]:
```suggestion
Preserve more detailed error messages in :mod:`ctypes`.
```

**Comment by kamilturek** [comment]
Thanks for the help and review! 🙂 That was a pleasure.
