### PR TITLE
gh-114083: apply optimization of LOAD_CONST instructions to the whole CFG before optimize_basic_block.

### LINKED ISSUE #114083: Python/flowgraph.c:497: _Bool no_redundant_jumps(cfg_builder *): Assertion `0' failed.
# Bug report

### Bug description:

Another crash in the compiler found by the fuzzer:

```
~/p/cpython ❯❯❯ ./python.exe -c 'compile("if 9<9<9and 9or 9or 9:9", "", "exec")'
:1: SyntaxWarning: invalid decimal literal
:1: SyntaxWarning: invalid decimal literal
:1: SyntaxWarning: invalid decimal literal
Assertion failed: (0), function no_redundant_jumps, file flowgraph.c, line 497.
fish: Job 1, './python.exe -c 'compile("if 9<…' terminated by signal SIGABRT (Abort)
```

cc: @iritkatriel 

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

_No response_

### Linked PRs
* gh-114408

### PR DESCRIPTION
**Pull request by iritkatriel**
Fixes #114083.

Currently, folding LOAD_CONST + TO_BOOL + CONDITIONAL_JUMP into an unconditional JUMP occurs in the same pass as jump threading. For this code:

```
Block1:
    JUMP Block2

Block2:
   LOAD_CONST x
   TO_BOOL
   CONDITIONAL_JUMP Block3

Block3:
    ...
```

We try to thread the jump in block1 before we collapse block2 into an unconditional jump, so threading is not applied, and we can end up with a redundant jump.

This PR splits the folding of LOAD_CONST + the following instruction into a separate pass, before the pass that applies jump threading. 

* Issue: gh-114083

### CODE REVIEW

File: Python/flowgraph.c [hunk 1]
```diff
@@ -1771,13 +1809,13 @@ optimize_cfg(cfg_builder *g, PyObject *consts, PyObject *const_cache, int firstl
...
-        RETURN_IF_ERROR(remove_redundant_jumps(g));
-    }
-
+    int removed_nops, removed_jumps;
+    do {
+        removed_nops = remove_redundant_nops(g);
+        RETURN_IF_ERROR(removed_nops);
+        removed_jumps = remove_redundant_jumps(g);
+        RETURN_IF_ERROR(removed_jumps);
+    } while(removed_nops + removed_jumps > 0);
```
Comment (markshannon) [inline Python/flowgraph.c:1821]: Could you add a comment about why this is guaranteed to terminate.
I presume it is guaranteed, as both `remove_redundant_nops` and `remove_redundant_jumps` monotonically reduce the number of instructions?

File: Python/flowgraph.c [hunk 2]
```diff
@@ -1479,16 +1493,12 @@ apply_static_swaps(basicblock *block, int i)
 }
 
 static int
-optimize_basic_block(PyObject *const_cache, basicblock *bb, PyObject *consts)
+basicblock_fold_load_const(PyObject *const_cache, basicblock *bb, PyObject *consts)
```
Comment (markshannon) [inline Python/flowgraph.c]: "fold" has many meanings in CS.
Maybe `fold_jumps`?

**Review by markshannon — CHANGES_REQUESTED** [review]
Looks good.
There are a couple of things that could do with minor clarifications.

File: Misc/NEWS.d/next/Core and Builtins/2024-01-22-09-48-58.gh-issue-114083.hf1-ku.rst
Comment (AlexWaygood) [inline Misc/NEWS.d/next/Core and Builtins/2024-01-22-09-48-58.gh-issue-114083.hf1-ku.rst:1]: looks like you have two identical news entries here :)

File: Python/flowgraph.c (hunk 2 above)
Comment (iritkatriel) [reply Python/flowgraph.c]: It's not only jumps. This function also fold LOAD_CONST + POP_TOP/RETURN_VALUE/TO_BOOL etc

File: Python/flowgraph.c (hunk 1 above)
Comment (iritkatriel) [reply Python/flowgraph.c:1821]: remove_redundant_jumps may not reduce the number of instructions - it may replace a jump by a NOP.

File: Misc/NEWS.d/next/Core and Builtins/2024-01-22-09-48-58.gh-issue-114083.hf1-ku.rst
Comment (iritkatriel) [reply Misc/NEWS.d/next/Core and Builtins/2024-01-22-09-48-58.gh-issue-114083.hf1-ku.rst:1]: I used the web blurb thing to create it. It seems to have created two.

Comment (AlexWaygood) [reply Misc/NEWS.d/next/Core and Builtins/2024-01-22-09-48-58.gh-issue-114083.hf1-ku.rst:1]: your contribution has been deemed doubly newsworthy by the blurb_it gods

File: Python/flowgraph.c (hunk 2 above)
Comment (iritkatriel) [reply Python/flowgraph.c]: I'll call it `optimize_load_const` instead of `fold_load_const`.

**Comment by iritkatriel** [comment]
I have made the requested changes; please review again.

**Review by markshannon — APPROVED** [review]
