### PR TITLE
gh-104432: Use `memcpy()` to avoid misaligned loads

### LINKED ISSUE #104432: UBSan misaligned load errors in `gethost_common()`, `mkgrent()`
test.test_asyncio.test_events.KqueueEventLoopTests.test_create_connection triggers `-fsanitize=alignment` errors on macOS (i.e. Darwin):

```
Modules/socketmodule.c:5790:34: runtime error: load of misaligned address 0x60d0001ca152 for type 'char *', which requires 8 byte alignment
0x60d0001ca152: note: pointer points here
 6f 73  74 00 62 a1 1c 00 d0 60  00 00 00 00 00 00 00 00  00 00 31 2e 30 2e 30 2e  31 32 37 2e 69 6e
              ^ 
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior Modules/socketmodule.c:5790:34 in 
Modules/socketmodule.c:5792:40: runtime error: load of misaligned address 0x60d0001ca152 for type 'char *', which requires 8 byte alignment
0x60d0001ca152: note: pointer points here
 6f 73  74 00 62 a1 1c 00 d0 60  00 00 00 00 00 00 00 00  00 00 31 2e 30 2e 30 2e  31 32 37 2e 69 6e
              ^ 
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior Modules/socketmodule.c:5792:40 in 
Modules/socketmodule.c:5804:32: runtime error: load of misaligned address 0x60d0001ca179 for type 'char *', which requires 8 byte alignment
0x60d0001ca179: note: pointer points here
 72 70 61  00 89 a1 1c 00 d0 60 00  00 00 00 00 00 00 00 00  00 7f 00 00 01 00 00 00  b9 96 6e cc b9
              ^ 
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior Modules/socketmodule.c:5804:32 in 
Modules/socketmodule.c:5817:35: runtime error: load of misaligned address 0x60d0001ca179 for type 'char *', which requires 8 byte alignment
0x60d0001ca179: note: pointer points here
 72 70 61  00 89 a1 1c 00 d0 60 00  00 00 00 00 00 00 00 00  00 7f 00 00 01 00 00 00  b9 96 6e cc b9
              ^ 
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior Modules/socketmodule.c:5817:35 in 
```

I believe this issue is also present in this line (but I am not aware if any tests cover it):
https://github.com/python/cpython/blob/ac66cc17f21653b66321b50d0a1f792982fca21f/Modules/socketmodule.c#L5834

Likewise in test.test_grp.GroupDatabaseTestCase.test_errors:

```
Modules/grpmodule.c:68:30: runtime error: load of misaligned address 0x6080006331f4 for type 'char *', which requires 8 byte alignment
0x6080006331f4: note: pointer points here
  72 00 2a 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  10 32 63 00 80 60 00 00
              ^ 
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior Modules/grpmodule.c:68:30 in 
Modules/grpmodule.c:69:49: runtime error: load of misaligned address 0x60c00474bcdb for type 'char *', which requires 8 byte alignment
0x60c00474bcdb: note: pointer points here
 64  00 2a 00 eb bc 74 04 c0  60 00 00 00 00 00 00 00  00 00 00 5f 6b 6e 6f 77  6c 65 64 67 65 67 72
              ^ 
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior Modules/grpmodule.c:69:49 in 
```

To be clear, these tests pass, and the misaligned pointers are produced by the OS and not Python. The misaligned pointers appear to be a known issue, presumably one which Apple may never resolve (given these are functions inherited from BSD, and newer functions like `getaddrinfo()` are preferred according to man pages). The workaround is to use `memcpy()` (see e.g. https://github.com/php/php-src/commit/26ac6cb6be807d9e654b4a0c9b970908e210f269).

### Linked PRs
* gh-104433
* gh-107355
* gh-107356

### PR DESCRIPTION
**Pull request by chrstphrchvz**
Fixes #104432.

* Issue: gh-104432

### CODE REVIEW

File: Modules/socketmodule.c [hunk 1]
```diff
@@ -5787,9 +5787,14 @@ gethost_common(socket_state *state, struct hostent *h, struct sockaddr *addr,
 
     /* SF #1511317: h_aliases can be NULL */
     if (h->h_aliases) {
-        for (pch = h->h_aliases; *pch != NULL; pch++) {
+        for (pch = h->h_aliases; ; pch++) {
             int status;
-            tmp = PyUnicode_FromString(*pch);
+            char *s;
```
Comment (gpshead) [inline Modules/socketmodule.c]: rather than `s` for the variable name, lets call it `host_alias` to more clearly indicate what it is.  (here and the loop below)

File: Modules/grpmodule.c [hunk 2]
```diff
@@ -65,8 +65,13 @@ mkgrent(PyObject *module, struct group *p)
         Py_DECREF(v);
         return NULL;
     }
-    for (member = p->gr_mem; *member != NULL; member++) {
-        PyObject *x = PyUnicode_DecodeFSDefault(*member);
+    for (member = p->gr_mem; ; member++) {
+        char *s;
```
Comment (gpshead) [inline Modules/grpmodule.c]: rather than `s` lets call this `group_member` to reflect what it actually is.

**Review by gpshead — CHANGES_REQUESTED** [review]

**Comment by chrstphrchvz** [comment]
I have made the requested changes; please review again

**Review by gpshead — APPROVED** [review]

File: Misc/NEWS.d/next/Core and Builtins/2023-07-27-11-47-29.gh-issue-104432.oGHF-z.rst [hunk 3]
```diff
@@ -0,0 +1,4 @@
+Fix potential unaligned memory access on C APIs involving returned sequences
+of `char *` pointers within the :mod:`grp` and :mod:`socket` modules. These
+were revealed using a ``-fsaniziter=alignment`` build on ARM macOS. Patch by
```
Comment (chrstphrchvz) [inline Misc/NEWS.d/next/Core and Builtins/2023-07-27-11-47-29.gh-issue-104432.oGHF-z.rst:3]: To clarify, I observed this on macOS for Intel. I have not confirmed if this also occurs on macOS for ARM, but I would not be surprised if it still does.

Comment (gpshead) [reply Misc/NEWS.d/next/Core and Builtins/2023-07-27-11-47-29.gh-issue-104432.oGHF-z.rst:3]: Oops I shouldn't have bothered mentioning the architecture. no big deal though (feel free to make an edit PR if it bothers you).

I chose the word "revealed" in the wording as a way to indicate _how_ it was found which is more interesting.  I suspect the alignment sanitizer may flag this regardless of compilation target architecture but I didn't try to reproduce it myself. :)

I expect the fixup applies all over the place. Regardless of native transparent hardware support (x86) or triggering a trap to the OS to fix the unaligned access up (Alpha & a pile of very RISC thing) they are usually less efficient - so directly using code that detects it and does it right rather than triggering an even slower path is good.
