### PR TITLE
gh-131204: Fix `difflib.HtmlDiff` may not use monospaced font

### LINKED ISSUE #131204: `difflib`-generated HTML file does not use monospaced font
# Bug report

### Bug description:

`difflib.HtmlDiff.make_file` writes an HTML file with a CSS rule specifying Courier as the font to use. On systems which don't have it installed, browsers may fall back to the system default font, which likely won't be monospaced.

```python
import difflib
import webbrowser

hd = difflib.HtmlDiff()
html = hd.make_file(["a", "aab", "c" + "f" * 20, "eg", "ry"], ["aab", "f" * 19, "ry"])
with open("diff.html", "w") as writer:
    print(html, file=writer)
webbrowser.open("diff.html")
```

On my system (which does not have Courier), the default font is Signika, which is what Firefox used to render the text.

Image

* Python 3.13.2 (main, Feb  5 2025, 08:05:21) [GCC 14.2.1 20250128]
* glibc 2.41+r9+ga900dbaf70f0-1
* Arch Linux (64-bit)

I _think_ is is sufficient to do:

```diff
diff --git a/Lib/difflib.py b/Lib/difflib.py
index bc09aa128aa..11d286a4aa8 100644
--- a/Lib/difflib.py
+++ b/Lib/difflib.py
@@ -1633,7 +1633,7 @@ def _line_pair_iterator():
 
 _styles = """
         :root {color-scheme: light dark}
-        table.diff {font-family:Courier; border:medium;}
+        table.diff {font-family:monospace; border:medium;}
         .diff_header {background-color:#e0e0e0}
         td.diff_header {text-align:right}
         .diff_next {background-color:#c0c0c0}
```

and will follow up with a pull request soon.

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

### Linked PRs
* gh-131221
* gh-131242
* gh-131243

### PR DESCRIPTION
**Pull request by Wulian233**
Fixes https://github.com/python/cpython/issues/131204.

* Issue: gh-131204

### CODE REVIEW

**Comment by Wulian233** [comment]
CC @hugovk request review :)

File: Misc/NEWS.d/next/Library/2025-03-14-09-28-13.gh-issue-131204.wogNEX.rst [hunk 1]
```diff
@@ -0,0 +1 @@
+Fix :class:`difflib.HtmlDiff` may not use monospaced font
```
Comment (hugovk) [inline Misc/NEWS.d/next/Library/2025-03-14-09-28-13.gh-issue-131204.wogNEX.rst]:
```suggestion
Use monospace font from System Font Stack for cross-platform support in  :class:`difflib.HtmlDiff`.
```

**Review by hugovk — APPROVED** [review]

**Comment by hugovk** [comment]
Thank you!

**Comment by Wulian233** [comment]
> @Wulian233 Please could you take care of backports? Thank you!

Sure!

https://github.com/python/cpython/pull/131242
https://github.com/python/cpython/pull/131243
