### PR TITLE
gh-110237: Check `PyList_Append` for errors in `_PyEval_MatchClass`

### LINKED ISSUE #110237: Missing error checks in `_PyEval_MatchClass`
Several places in `_PyEval_MatchClass` call `PyList_Append` without checking the return value (e.g., https://github.com/python/cpython/blob/fc2cb86d210555d509debaeefd370d5331cd9d93/Python/ceval.c#L509C13-L509C26). However, `PyList_Append` can fail. It will only fail if we're out of memory or if we passed a non-list, so it's unlikely to come up in practice, but we should still check for errors.

cc @brandtbucher for pattern matching

### Linked PRs
* gh-110238
* gh-110511
* gh-110512

### PR DESCRIPTION
**Pull request by denballakh**
fix #110237 

* Issue: gh-110237

### CODE REVIEW

File: Misc/NEWS.d/next/Core and Builtins/2023-10-02-23-17-08.gh-issue-110237._Xub0z.rst [hunk 1]
```diff
@@ -0,0 +1 @@
+Check `PyList_Append` for errors in `_PyEval_MatchClass`
```
Comment (JelleZijlstra) [inline Misc/NEWS.d/next/Core and Builtins/2023-10-02-23-17-08.gh-issue-110237._Xub0z.rst]:
```suggestion
Fix missing error checks for calls to ``PyList_Append`` in ``_PyEval_MatchClass``.
```

File: Python/ceval.c [hunk 2]
```diff
@@ -506,7 +506,9 @@ _PyEval_MatchClass(PyThreadState *tstate, PyObject *subject, PyObject *type,
         }
         if (match_self) {
             // Easy. Copy the subject itself, and move on to kwargs.
-            PyList_Append(attrs, subject);
+            if (PyList_Append(attrs, subject) == -1) {
```
Comment (JelleZijlstra) [inline Python/ceval.c]:
```suggestion
            if (PyList_Append(attrs, subject) < 0) {
```
I think this is more idiomatic

Comment (JelleZijlstra) [reply Python/ceval.c]: Never mind, either is fine.
