### PR TITLE
gh-102381: don't call watcher callback with dead object

### LINKED ISSUE #102381: raising an exception in a dict/code/function watcher callback will segfault on a DEALLOCATED event
Because the object we pass into the callback is dead (zero refcount), and if the callback raises an error we try to `PyErr_WriteUnraisable` with that object as context, which increfs and decrefs it, which recursively again tries to deallocate it, and we end up in infinite recursion and overflowing the stack.

There are various other ways a callback could trigger this issue. We shouldn't pass around dead objects; instead `*_dealloc` should temporarily resurrect it before calling the callback.

### Linked PRs
* gh-102382

### PR DESCRIPTION
**Pull request by carljm**
Fixes #102381, #102351 and #102385.

Ensure that `func_dealloc`, `code_dealloc`, and `dict_dealloc` temporarily incref the function/code object/dict before calling the watcher callback, so we don't pass around dead objects.

A watcher callback could take a reference to the object; check for this and allow it to be resurrected in that case, rather than going ahead and freeing it (making the taken reference a pointer to freed memory.)

Also, don't pass the object itself to `PyErr_WriteUnraisable` if the callback raises, allowing an unraisablehook to take a reference to the object and resurrect it and, in the worst case, causing an infinite loop. Safer to construct an informative debug string and pass that as context to `PyErr_WriteUnraisable`. This actually provides more debug information than before, since the new message clarifies that the error occurred in a watcher callback for the mentioned object.

* Issue: gh-102381

### CODE REVIEW

**Comment by carljm** [comment]
Skipping news since this is just fixing a bug in an unreleased new feature.

File: Objects/codeobject.c [hunk 1]
```diff
@@ -25,7 +28,13 @@ notify_code_watchers(PyCodeEvent event, PyCodeObject *co)
             // callback must be non-null if the watcher bit is set
             assert(cb != NULL);
             if (cb(event, co) < 0) {
-                PyErr_WriteUnraisable((PyObject *) co);
+                // Don't risk resurrecting the object if an unraisablehook keeps
+                // a reference; pass a string as context.
+                PyObject *repr = code_repr(co);
```
Comment (JelleZijlstra) [inline Objects/codeobject.c:46]: What if code_repr() fails?

Comment (carljm) [reply Objects/codeobject.c:46]: Updating to account for the possibility that `code_repr`, `func_repr`, or even `PyUnicode_FromFormat` might fail; in this case we can pass in a more generic context message built with `PyUnicode_FromString`. I think the only way `PyUnicode_FromString` can fail (given a literal string known to be of OK size and not have encoding errors) is an OOM condition? I guess in that case the best we can do is just skip the `PyErr_WriteUnraisable`, given we have no context object we can safely pass to it (and if we are out of memory it will probably fail anyway.)

Comment (carljm) [reply Objects/codeobject.c:46]: I'm not sure even the generic fallback message via `PyUnicode_FromString` is worth it, given how rare it seems it should be even for `code_repr` or `func_repr` to fail. We could also just skip `PyErr_WriteUnraisable` given a repr failure. But I'll push the version that handles the repr failure a bit more gracefully, and see what you think.

Comment (JelleZijlstra) [reply Objects/codeobject.c:46]: Agree that these are very unlikely failure scenarios, but I feel we should at least try to give a useful error. "Errors should never pass silently" :)

Comment (carljm) [reply Objects/codeobject.c:46]: I decided the least-silent option is to fall back to `Py_None` as context object if we can't even build a useful context string, and still try to call `PyErr_WriteUnraisable` so whatever error happened doesn't pass totally silently.

**Review by JelleZijlstra — APPROVED** [review]
Looks good, thanks for fixing this! I'd like other reviewers to also have a look though.

File: Objects/codeobject.c [hunk 2]
```diff
@@ -1667,7 +1683,14 @@ code_new_impl(PyTypeObject *type, int argcount, int posonlyargcount,
 static void
 code_dealloc(PyCodeObject *co)
 {
+    assert(Py_REFCNT(co) == 0);
+    Py_SET_REFCNT(co, 1);
     notify_code_watchers(PY_CODE_EVENT_DESTROY, co);
+    if (Py_REFCNT(co) > 1) {
+        Py_DECREF(co);
```
Comment (Yhg1s) [inline Objects/codeobject.c]: Don't call Py_DECREF here; when checking refcounts (i.e. a Py_DEBUG build) DECREF and INCREF need to be balanced. Since the refcount was increased by calling Py_SET_REFCNT, you need to decrease it the same way.

File: Objects/dictobject.c [hunk 3]
```diff
@@ -2308,7 +2308,14 @@ _PyDict_FromKeys(PyObject *cls, PyObject *iterable, PyObject *value)
 static void
 dict_dealloc(PyDictObject *mp)
 {
+    assert(Py_REFCNT(mp) == 0);
+    Py_SET_REFCNT(mp, 1);
     _PyDict_NotifyEvent(PyDict_EVENT_DEALLOCATED, mp, NULL, NULL);
+    if(Py_REFCNT(mp) > 1) {
+        Py_DECREF(mp);
```
Comment (Yhg1s) [inline Objects/dictobject.c]: Py_SET_REFCNT here too.

File: Objects/dictobject.c [hunk 4]
```diff
@@ -2308,7 +2308,14 @@ _PyDict_FromKeys(PyObject *cls, PyObject *iterable, PyObject *value)
 static void
 dict_dealloc(PyDictObject *mp)
 {
+    assert(Py_REFCNT(mp) == 0);
+    Py_SET_REFCNT(mp, 1);
     _PyDict_NotifyEvent(PyDict_EVENT_DEALLOCATED, mp, NULL, NULL);
+    if(Py_REFCNT(mp) > 1) {
```
Comment (Yhg1s) [inline Objects/dictobject.c]:
```suggestion
    if (Py_REFCNT(mp) > 1) {
```

File: Objects/dictobject.c [hunk 5]
```diff
@@ -5744,9 +5751,17 @@ _PyDict_SendEvent(int watcher_bits,
...
             PyDict_WatchCallback cb = interp->dict_state.watchers[i];
             if (cb && (cb(event, (PyObject*)mp, key, value) < 0)) {
-                // some dict modification paths (e.g. PyDict_Clear) can't raise, so we
-                // can't propagate exceptions from dict watchers.
-                PyErr_WriteUnraisable((PyObject *)mp);
+                // We don't want to resurrect the dict by potentially having an
+                // unraisablehook keep a reference to it, so we don't pass the
+                // dict as context, just an informative string message.  Dict
+                // repr can call arbitrary code, so we invent a simpler version.
+                PyObject *context = PyUnicode_FromFormat("watcher callback for <dict at %p>", mp);
```
Comment (Yhg1s) [inline Objects/dictobject.c]: Wrap lines (PEP 7 line length is 79 chars).

File: Objects/funcobject.c [hunk 6]
```diff
@@ -21,7 +23,20 @@ notify_func_watchers(PyInterpreterState *interp, PyFunction_WatchEvent event,
...
+                // reference; pass a string as context.
+                PyObject *context = NULL;
+                PyObject *repr = func_repr(func);
+                if (repr != NULL) {
+                    context = PyUnicode_FromFormat("watcher callback for %U", repr);
+                    Py_DECREF(repr);
+                }
+                if (context == NULL) {
+                    context = Py_None;
+                    Py_INCREF(context);
```
Comment (Yhg1s) [inline Objects/funcobject.c]:
```suggestion
                    context = Py_NewRef(Py_None);
```

File: Objects/codeobject.c [hunk 7]
```diff
@@ -25,7 +28,20 @@ notify_code_watchers(PyCodeEvent event, PyCodeObject *co)
...
+                // a reference; pass a string as context.
+                PyObject *context = NULL;
+                PyObject *repr = code_repr(co);
+                if (repr) {
+                    context = PyUnicode_FromFormat("watcher callback for %U", repr);
+                    Py_DECREF(repr);
+                }
+                if (context == NULL) {
+                    context = Py_None;
+                    Py_INCREF(context);
```
Comment (Yhg1s) [inline Objects/codeobject.c]:
```suggestion
                    context = Py_NewRef(Py_None);
```

File: Doc/c-api/function.rst [hunk 8]
```diff
@@ -173,8 +173,15 @@ There are a few functions specific to Python functions.
    runtime behavior depending on optimization decisions, it does not change
    the semantics of the Python code being executed.
 
-   If the callback returns with an exception set, it must return ``-1``; this
-   exception will be printed as an unraisable exception using
-   :c:func:`PyErr_WriteUnraisable`. Otherwise it should return ``0``.
+   If *event* is ``PyFunction_EVENT_DESTROY``, there may already be a pending
```
Comment (Yhg1s) [inline Doc/c-api/function.rst]: Does it make sense to guarantee that the other event handlers are never called with an exception set?

Is it forbidden or problematic for the callback to store the pending exception, call API functions, and restore it before returning 0? (The wording seems to imply so.)

File: Doc/c-api/function.rst [hunk 9]
```diff
@@ -173,8 +173,15 @@ There are a few functions specific to Python functions.
...
+   exception set on entry to the callback; in this case, the callback may not
+   execute Python code or otherwise disturb the pending exception. Taking a
+   reference in the callback to an about-to-be-destroyed function will resurrect
+   it and prevent it from being freed.
```
Comment (Yhg1s) [inline Doc/c-api/function.rst]:
```suggestion
   it, preventing it from being freed at this time. When the resurrected object is destroyed later,
   any watcher callbacks active at the time will be called again.
```

File: Objects/dictobject.c [hunk 10]
```diff
@@ -5744,9 +5751,17 @@ _PyDict_SendEvent(int watcher_bits,
...
+                if (context == NULL) {
+                    context = Py_None;
+                    Py_INCREF(context);
```
Comment (Yhg1s) [inline Objects/dictobject.c]:
```suggestion
                    context = Py_NewRef(Py_None);
```

File: Objects/funcobject.c [hunk 11]
```diff
@@ -766,7 +782,14 @@ func_clear(PyFunctionObject *op)
 static void
 func_dealloc(PyFunctionObject *op)
 {
+    assert(Py_REFCNT(op) == 0);
+    Py_SET_REFCNT(op, 1);
     handle_func_event(PyFunction_EVENT_DESTROY, op, NULL);
+    if (Py_REFCNT(op) > 1) {
+        Py_DECREF(op);
```
Comment (Yhg1s) [inline Objects/funcobject.c]: Py_SET_REFCNT here too.

File: Objects/codeobject.c (hunk 2 above)
Comment (carljm) [reply Objects/codeobject.c]: Ah right, you mentioned this in debugging, but clearly it didn't stick :) I'll remember now.

It would be nice if _something_ in CI would catch this problem. Even refleak buildbots didn't catch it. I guess it would just hide out until someone manually noticed a discrepancy in `gettotalrefcount()`? If so, it would surprise me if we don't already have such discrepancies hiding some places.

File: Doc/c-api/function.rst (hunk 8 above)
Comment (carljm) [reply Doc/c-api/function.rst]: I don't want to make this a guarantee for the callbacks, because it's quite expensive to check `PyErr_Occurred()` and then save/restore the exception. The intended use case for these callbacks is performance-sensitive, and generally should not involve the callback doing anything that even uses the CPython C API; just doing some cheap updates to internal bookkeeping of e.g. a JIT.

But you're right that if a callback really wants to save/clear/restore the exception itself and do something with the C API while it's cleared, that should be fine. I'll update the wording accordingly.

EDIT: I think I misinterpreted your comment. You said "other event handlers" -- I'm thinking now that you meant I shouldn't word things so as to sound like only the dealloc event can be called with exception set. I don't _think_ the other events will ever be called with exception set, but I don't know that for sure. I guess it's probably safer to just say callbacks generally need to be prepared to handle this.

**Comment by carljm** [comment]
Thanks @Yhg1s for the review! I've updated per all comments.

File: Objects/codeobject.c [hunk 12]
```diff
@@ -1667,7 +1682,14 @@ code_new_impl(PyTypeObject *type, int argcount, int posonlyargcount,
 static void
 code_dealloc(PyCodeObject *co)
 {
+    assert(Py_REFCNT(co) == 0);
+    Py_SET_REFCNT(co, 1);
```
Comment (Yhg1s) [inline Objects/codeobject.c:1700]: Do you still want to move this to the event handler function? I imagine it would use a return value to indicate whether the object was resurrected.

File: Objects/dictobject.c [hunk 13]
```diff
@@ -5744,9 +5751,17 @@ _PyDict_SendEvent(int watcher_bits,
...
             if (cb && (cb(event, (PyObject*)mp, key, value) < 0)) {
-                // some dict modification paths (e.g. PyDict_Clear) can't raise, so we
-                // can't propagate exceptions from dict watchers.
-                PyErr_WriteUnraisable((PyObject *)mp);
+                // We don't want to resurrect the dict by potentially having an
+                // unraisablehook keep a reference to it, so we don't pass the
+                // dict as context, just an informative string message.  Dict
+                // repr can call arbitrary code, so we invent a simpler version.
+                PyObject *context = PyUnicode_FromFormat(
+                    "watcher callback for <dict at %p>", mp);
```
Comment (Yhg1s) [inline Objects/dictobject.c]: Mention the event type here as well?

Comment (carljm) [reply Objects/dictobject.c]: Done.

File: Objects/codeobject.c (hunk 12 above)
Comment (carljm) [reply Objects/codeobject.c:1700]: This adds complexity (particularly for dict watchers, where the notify func already has a return value, the new dict version tag.) It's doable, but I think it is only worth doing if it makes a detectable difference in pyperformance, and it doesn't seem to; this PR as-is is "1.00x faster" than the last merged commit from main branch.

Comment (Yhg1s) [reply Objects/codeobject.c:1700]: FWIW, another option is just 'if refcount is no longer 0, return'. I think it makes sense for code cleanliness more than performance reasons to put the refcount shenanigans inside the only branch that cares about them, but if you prefer it like this, that's fine.

File: Include/cpython/dictobject.h [hunk 14]
```diff
@@ -90,13 +90,18 @@ PyAPI_FUNC(PyObject *) _PyDictView_Intersect(PyObject* self, PyObject *other);
 
 /* Dictionary watchers */
 
+#define FOREACH_DICT_EVENT(V) \
```
Comment (Yhg1s) [inline Include/cpython/dictobject.h]: This (and the other ones) would need a PY_ prefix.

File: Objects/codeobject.c [hunk 15]
```diff
@@ -11,9 +11,23 @@
 #include "pycore_tuple.h"         // _PyTuple_ITEMS()
 #include "clinic/codeobject.c.h"
 
+static PyObject* code_repr(PyCodeObject *co);
+
+static const char *
+code_event_name(PyCodeEvent event) {
```
Comment (Yhg1s) [inline Objects/codeobject.c:17]: FWIW, I'm not sure this stringification is worth the effort (I would just give the enums an explicit value, so you can manually map back, and log the integer), but this may make more sense as an inline function in codeobject.h so the FOREACH_CODE_EVENT macro doesn't have to leave the header.

File: Objects/codeobject.c [hunk 16]
```diff
@@ -11,9 +11,23 @@
...
+    switch (event) {
+        #define CASE(op)                \
+        case PY_CODE_EVENT_##op:         \
+            return "PY_CODE_EVENT_" #op;
+        FOREACH_CODE_EVENT(CASE)
+        #undef CASE
+    }
```
Comment (Yhg1s) [inline Objects/codeobject.c:24]: Need a default and/or error return after the switch.

File: Objects/codeobject.c (hunk 12 above)
Comment (carljm) [reply Objects/codeobject.c:1700]: Hmm. The current version seems cleaner to me. The "branch that cares about" this is specifically the dealloc path, where refcount is 0. Ideally `*_dealloc` shouldn't be handing off a dead object to the black-box notify func (which is also used by many other paths that don't deal with dead objects), and the current version cleanly and clearly ensures that in the spot where we already know we have a dead object.

If it were a performance issue to do this refcount bump when there is no callback installed, then we could more tightly couple the notify func to the dealloc path, by making the notify func responsible for the fact that it might receive a dead object, when it's called with the dealloc event type. But that seems to me like a concession, reducing code cleanliness slightly in exchange for performance.

File: Include/cpython/dictobject.h (hunk 14 above)
Comment (carljm) [reply Include/cpython/dictobject.h]: Ah good call. I just copied the existing one for `FOREACH_FUNC_EVENT`, which I guess should have had the prefix but didn't.

I guess if we follow your other comment and move the `*_event_name` functions to the header and undef the macro, we don't need the prefix?

Comment (carljm) [reply Include/cpython/dictobject.h]: `FOREACH_FUNC_EVENT` is also used in the unit tests currently (in `Modules/_testcapi/watchers.c`, which is why it already existed. So I guess I'll give it the prefix.

File: Objects/codeobject.c (hunk 15 above)
Comment (carljm) [reply Objects/codeobject.c:17]: I also initially didn't think the stringification was worth the effort, which is why I hadn't logged the event type at all. I didn't really consider the option of just logging the integer and giving the enums explicit values. But I guess now that I've done the stringification, it seems like the bit of additional code is probably worth it for the improved debuggability? If you think not, I can revert all the stringification stuff and just log the integer event type instead.

File: Include/cpython/dictobject.h (hunk 14 above)
Comment (JelleZijlstra) [reply Include/cpython/dictobject.h]: I think even if we define then undefine the macro in a header, it could interfere with other user code that uses the same macro name, so we should still use the prefix.

File: Objects/codeobject.c (hunk 16 above)
Comment (carljm) [reply Objects/codeobject.c:24]: Ugh, thanks, been writing too much C++ with non-exhaustive switch errors turned on.

File: Objects/codeobject.c (hunk 15 above)
Comment (carljm) [reply Objects/codeobject.c:17]: Given that `FOREACH_FUNC_EVENT` already has to escape the header, do you think it's worth having `FOREACH_DICT_EVENT` and `FOREACH_CODE_EVENT` not escape, or better to handle all of them the same way? I'd lean towards consistency in all three cases.

**Comment by carljm** [comment]
@Yhg1s I pushed the explicit exhaustiveness check, and one possible way of addressing your comments about the x-macros. I really don't feel strongly about how to handle the event type logging, so if you have a clearly preferred approach, just let me know and I'll do that.

File: Objects/codeobject.c (hunk 15 above)
Comment (Yhg1s) [reply Objects/codeobject.c:17]: Yeah, there's enough subtle differences between the three systems already, let's keep them as similar as we can.

File: Objects/codeobject.c (hunk 12 above)
Comment (Yhg1s) [reply Objects/codeobject.c:1700]: Ah, yeah, I forgot about the fact that the callback-caller gets called from other places too, which obviously don't have the refcount=0 problem. Better to handle it in the dealloc function, yes.

**Review by Yhg1s — APPROVED** [review]

File: Include/cpython/code.h [hunk 17]
```diff
@@ -224,9 +224,14 @@ PyAPI_FUNC(int) PyCode_Addr2Line(PyCodeObject *, int);
...
 
-typedef enum PyCodeEvent {
-  PY_CODE_EVENT_CREATE,
-  PY_CODE_EVENT_DESTROY
+#define PY_FOREACH_CODE_EVENT(V) \
+    V(CREATE)                 \
+    V(DESTROY)
+
+typedef enum {
+    #define DEF_EVENT(op) PY_CODE_EVENT_##op,
```
Comment (JelleZijlstra) [inline Include/cpython/code.h]: Shouldn't this also have the PY_ prefix?

File: Include/cpython/dictobject.h [hunk 18]
```diff
@@ -90,13 +90,18 @@ PyAPI_FUNC(PyObject *) _PyDictView_Intersect(PyObject* self, PyObject *other);
...
+    V(DEALLOCATED)
+
 typedef enum {
-    PyDict_EVENT_ADDED,
-    PyDict_EVENT_MODIFIED,
-    PyDict_EVENT_DELETED,
-    PyDict_EVENT_CLONED,
-    PyDict_EVENT_CLEARED,
-    PyDict_EVENT_DEALLOCATED,
+    #define DEF_EVENT(EVENT) PyDict_EVENT_##EVENT,
```
Comment (JelleZijlstra) [inline Include/cpython/dictobject.h]: Same

File: Include/cpython/funcobject.h [hunk 19]
```diff
@@ -131,16 +131,16 @@ PyAPI_DATA(PyTypeObject) PyStaticMethod_Type;
...
-    V(MODIFY_DEFAULTS)        \
+#define PY_FOREACH_FUNC_EVENT(V) \
+    V(CREATE)                    \
+    V(DESTROY)                   \
+    V(MODIFY_CODE)               \
+    V(MODIFY_DEFAULTS)           \
     V(MODIFY_KWDEFAULTS)
 
 typedef enum {
     #define DEF_EVENT(EVENT) PyFunction_EVENT_##EVENT,
```
Comment (JelleZijlstra) [inline Include/cpython/funcobject.h]: And again

**Review by JelleZijlstra — COMMENTED** [review]
Sorry, noticed one more thing. I think this can affect users who include the header in C code that independently defines a `DEF_EVENT` macro.

**Comment by JelleZijlstra** [comment]
And as discussed offline, let's run the buildbots again to be safe; after that feel free to merge.

File: Include/cpython/code.h (hunk 17 above)
Comment (Yhg1s) [reply Include/cpython/code.h]: We don't generally use them for macros that are undefined right after, but you're right, it's a fairly generic name and it's technically possible for something to define DEF_EVENT before including Python.h

File: Objects/funcobject.c [hunk 20]
```diff
@@ -766,7 +795,14 @@ func_clear(PyFunctionObject *op)
...
 func_dealloc(PyFunctionObject *op)
 {
+    assert(Py_REFCNT(op) == 0);
+    Py_SET_REFCNT(op, 1);
     handle_func_event(PyFunction_EVENT_DESTROY, op, NULL);
+    if (Py_REFCNT(op) > 1) {
+        Py_SET_REFCNT(op, Py_REFCNT(op) - 1);
+        return;
+    }
+    Py_SET_REFCNT(op, 0);
```
Comment (kumaraditya303) [inline Objects/funcobject.c:805]: Is this `Py_SET_REFCNT` necessary? IIUC this is redundant here otherwise it isn't obvious to me and a comment would be nice.

**Comment by markshannon** [comment]
I can't help feeling that we would be better off without these watchers.
They appear to be bug magnets. Handling the "zombie" objects is tricky and error prone.
How is the watcher interacting with the freed object if there are no references to it?

This PR adds quite a lot of code to `dict_dealloc` which is called for every dictionary created, which has performance implications.

I think we should just remove these watchers. What are they for?
I've been going through possible optimizations for CPython and these watchers aren't needed for any of them.
I don't see why Cinder would need them either.

(As an aside: we won't need the creation events either, but I can see why Cinder wants those).

File: Objects/funcobject.c (hunk 20 above)
Comment (carljm) [reply Objects/funcobject.c:805]: In the normal case, assuming the watcher has not taken any new reference to the object, the refcount will be `1` at this point (because we set it to 1 above.) We should set it to `0` before continuing with deallocation, because objects being deallocated should have a refcount of zero.

Comment (markshannon) [reply Objects/funcobject.c:805]: The watcher *must* take a reference to any object it is watching, otherwise the refcount is incorrect and we crash and burn.

The GC, or an optimizer, can legitimately assume that any object with a reference count of zero and no weakrefs is to be freed and re-use the memory. That's not going to end well if the watcher still thinks that memory is still a dictionary.

**Comment by carljm** [comment]
> This PR adds quite a lot of code to dict_dealloc which is called for every dictionary created, which has performance implications.

I was also initially concerned about adding an incref and decref in this path, but on a pyperformance run (with `--enable-optimizations` build, on a bare-metal AWS host) this PR was `1.00x faster` than the base commit in `main`, so it doesn't seem to have a detectable impact?

> I don't see why Cinder would need them either.

In general, in Cinder they are used for de-registering objects from JIT registries consisting of borrowed references, to avoid having dangling pointers in these registries. E.g. for each watched dict, we remember what key(s) we care about in that dict, and for each key we may also watch a different builtins (and maybe also globals) dict that that key might actually have been found in (or might still need to be found in if the key goes away in the main dict). If the main dict is deallocated we unwatch the additional globals/builtins dicts, and erase the whole entry from the registry. Similarly, we have a registry of created functions/code-objects that are pending compilation (in some modes we don't compile eagerly but do a multi-threaded compilation of everything pending compilation, right before fork), so if a function or code object is deallocated we remove it from that registry.

In every case the deallocated handler doesn't _do_ anything with the zombie `PyObject` itself, it just needs the pointer value to erase any registry entry for that pointer value.

File: Objects/funcobject.c (hunk 20 above)
Comment (carljm) [reply Objects/funcobject.c:805]: @markshannon I think your comment is more relevant to the discussion below (about why to have dealloc watchers at all) than it is to this thread, so I'll reply below.

The answer to @kumaraditya303's question here is that this `Py_SET_REFCNT(op, 0)` is the decref that has to be paired with the incref `Py_SET_REFCNT(op, 1);` that occurs on line 799. We use explicit `Py_SET_REFCNT` instead of `Py_INCREF` and `Py_DECREF` because `Py_DECREF` would cause recursive deallocation, and if we use `Py_SET_REFCNT` for the decref we have to use it for the incref also, otherwise the total refcount tracking will be off.

**Comment by carljm** [comment]
> The watcher must take a reference to any object it is watching, otherwise the refcount is incorrect and we crash and burn.

Cinder JIT currently doesn't take references to objects it is watching, so as not to keep them alive if they would otherwise die. There is no "crash and burn" precisely because of the dealloc events; if the object is deallocated we know about it and can erase any pointer to it we were keeping. Effectively it's like we are keeping a weakref, but without the allocation and indirection overhead of an actual weakref object. Perhaps we should be keeping an actual weakref instead; it would take some experimentation to check the performance impact of that.
