### PR TITLE
gh-95231: Disable md5 & crypt modules if FIPS is enabled

### LINKED ISSUE #95231: crypt module fails to import in FIPS mode
# Bug report

If kernel fips is enabled, we get permission error upon doing `import crypt`.
```
Python 3.9.1 (default, May 10 2022, 11:36:26)
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

            import crypt
            Traceback (most recent call last):
            File "", line 1, in
            File "/usr/lib/python3.9/crypt.py", line 117, in
            _add_method('MD5', '1', 8, 34)
            File "/usr/lib/python3.9/crypt.py", line 94, in _add_method
            result = crypt('', salt)
            File "/usr/lib/python3.9/crypt.py", line 82, in crypt
            return _crypt.crypt(word, salt)
            PermissionError: [Errno 1] Operation not permitted
```

# Your environment
VMware Photon OS 4.0
x86_64 machine
Python-3.9.1
Kernel fips is enabled

### PR DESCRIPTION
**Pull request by sshedi**
If kernel fips is enabled, we get permission error upon doing
`import crypt`. So, if kernel fips is enabled, disable the
unallowed hashing methods.

Python 3.9.1 (default, May 10 2022, 11:36:26)
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import crypt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/crypt.py", line 117, in <module>
    _add_method('MD5', '1', 8, 34)
  File "/usr/lib/python3.9/crypt.py", line 94, in _add_method
    result = crypt('', salt)
  File "/usr/lib/python3.9/crypt.py", line 82, in crypt
    return _crypt.crypt(word, salt)
PermissionError: [Errno 1] Operation not permitted

Signed-off-by: Shreenidhi Shedi <sshedi@vmware.com>

* Issue: gh-95231

Automerge-Triggered-By: GH:tiran

### CODE REVIEW

**Comment by sshedi** [comment]
Hi @vstinner, @erlend-aasland, @rhettinger 
Please take a look at my code changes. Do I need to create a github issue for this? This is my first attempt to contribute to upstream python. Please help me out.

**Comment by sshedi** [comment]
Hi @gvanrossum @benjaminp @birkenfeld @freddrake,

Please review this PR, need your inputs.

**Comment by birkenfeld** [comment]
Please abstain from pinging random developers. See https://www.python.org/dev/core-mentorship/ for getting help with your first contributions and in general https://devguide.python.org/ for documentation of our process.

**Comment by erlend-aasland** [comment]
Hi, @sshedi; thanks for your interest in improving CPython! Please create an issue and explain why these changes are needed.

Also, for the future, please follow Georg Brandl's advice: start with the devguide; it contains a lot of important information for new contributors.

**Comment by sshedi** [comment]
Thanks @erlend-aasland and @birkenfeld for your response.

I have created an issue here https://github.com/python/cpython/issues/95231
I will go through the development process, I checked the top contributors and tagged them here to get some insights on my PR.

I believe I have given sufficient info on the issue I'm facing.

**Review by tiran — CHANGES_REQUESTED** [review]
The approach with reading from ``/proc/sys/crypto/fips_enabled`` and manually disabling MD5 and CRYPT is not portable. The proc interface is Linux specific. The system may block more or less algorithms depending on the local crypto policy.

I recommend that we should catch more errno values in ``_add_method`` instead.

```
diff --git a/Lib/crypt.py b/Lib/crypt.py
index 46c3de8474b..92e70415e1a 100644
--- a/Lib/crypt.py
+++ b/Lib/crypt.py
@@ -100,6 +100,9 @@ def _add_method(name, *args, rounds=None):
         # Not all libc libraries support all encryption methods.
         if e.errno == errno.EINVAL:
             return False
+        # unsupported or blocked by crypto policy
+        if e.errno in {errno.EPERM, errno.ENOSYS}:
+            return False
         raise
     if result and len(result) == method.total_size:
         methods.append(method)
```

**Comment by erlend-aasland** [comment]
Also, please add a NEWS entry using the `blurb` tool.

https://devguide.python.org/getting-started/pull-request-lifecycle/

**Comment by sshedi** [comment]
@tiran Valid point. But how other python modules are detecting kernel fips status?
I made my changes using https://github.com/python/cpython/blob/310f94871a923f6cf3dc9259e732ce2376578b26/Lib/test/pythoninfo.py#L840 as reference.

Suggested code works but can we have something to know that we got EPERM because of fips?

**Comment by tiran** [comment]
Your proposed solution is solving the wrong problem, or at least a too narrow part of a general problem. It is trying to detect FIPS mode and then hard-codes which algorithms it thinks are disabled in FIPS mode. FIPS is an evolving standard. For example FIPS 140-3 blocks some algorithms are are allowed in FIPS 140-2. There are also more crypto policy standards than FIPS. FIPS is only relevant for the US government. It is irrelevant for the rest of the world and non-government software inside the US.

My solution is simpler and should fix your problem with less code. It is also not tight to FIPS and can handle other crypto policies that block algorithms.

I don't know why libcrypt on your system raises a permission error. I recommend that your contact your vendor and make an inquiry.

**Comment by sshedi** [comment]
Thanks @tiran for the detailed explanation, I agree. I will make the suggested changes.

**Comment by sshedi** [comment]
The EPERM error is coming from libcrypt and glibc is doing it.

https://github.com/bminor/glibc/blob/ca4d3ea5130d66e66c5af14e958e99341bf20689/crypt/crypt-entry.c#L89
```
      /* FIPS rules out MD5 password encryption.  */
      if (fips_enabled_p ())
	{
	  __set_errno (EPERM);
	  return NULL;
	}
```

**Comment by erlend-aasland** [comment]
For the record; please do not force push PRs, as the GitHub UI do not play well with force-pushes. Please use `git merge --no-ff main` instead.

File: Misc/NEWS.d/next/Library/2022-07-25-15-45-06.gh-issue-95231.i807-g.rst [hunk 1]
```diff
@@ -0,0 +1,2 @@
+If kernel fips is enabled, we get permission error upon doing import crypt.
+So, if kernel fips is enabled, disable the unallowed hashing methods.
```
Comment (erlend-aasland) [inline Misc/NEWS.d/next/Library/2022-07-25-15-45-06.gh-issue-95231.i807-g.rst]: Please update the NEWS entry to more accurately reflect the change. You may mention FIPS as a case where EPERM is triggered.

**Comment by sshedi** [comment]
Sorry @erlend-aasland , it has become a habit for me now. `git push origin -f <my-branch-name>`
Will give your suggestion a try.

File: Misc/NEWS.d/next/Library/2022-07-25-15-45-06.gh-issue-95231.i807-g.rst [hunk 2]
```diff
@@ -0,0 +1,3 @@
+Handle EPERM errors gracefully in Lib/crypt.py
+One of the scenarios we hit this condition is when kernel fips is enabled
+and trying to use md5 from crypt module.
```
Comment (erlend-aasland) [inline Misc/NEWS.d/next/Library/2022-07-25-15-45-06.gh-issue-95231.i807-g.rst]: How about this? cc. @tiran 

```suggestion
Fail gracefully if :data:`~errno.EPROM` or :data:`~errno.ENOSYS` is raised when loading
:mod:`crypt` methods. This may happen when trying to load ``MD5`` on a Linux kernel
with :abbr:`FIPS (Federal Information Processing Standard)` enabled.
```

**Comment by sshedi** [comment]
I have made the requested changes; please review again.

@erlend-aasland - Sorry, I amended y changes addressing review comments so I have to force push to my branch.

**Comment by sshedi** [comment]
I have made the requested changes; please review again.
cc: @erlend-aasland @tiran

File: Lib/crypt.py [hunk 3]
```diff
@@ -100,6 +100,9 @@ def _add_method(name, *args, rounds=None):
         # Not all libc libraries support all encryption methods.
         if e.errno == errno.EINVAL:
             return False
+        # unsupported or blocked by crypto policy
```
Comment (erlend-aasland) [inline Lib/crypt.py]: The comment in line 100 also speaks for the condition below.

```suggestion
```

**Comment by sshedi** [comment]
Hi @erlend-aasland & @tiran , shall we merge this change? Please let me know if any further modifications needed.

**Review by erlend-aasland — CHANGES_REQUESTED** [review]

File: Lib/crypt.py (hunk 3 above)
Comment (sshedi) [reply Lib/crypt.py]: Thanks for the suggestion @erlend-aasland.
In that case shall we use:
```
if e.errno in {errno.EINVAL ,errno.EPERM, errno.ENOSYS}:
    return False
```

**Comment by sshedi** [comment]
I have made the requested changes; please review again.

File: Misc/NEWS.d/next/Library/2022-07-25-15-45-06.gh-issue-95231.i807-g.rst [hunk 4]
```diff
@@ -0,0 +1,3 @@
+Fail gracefully if :data:`~errno.EPROM` or :data:`~errno.ENOSYS` is raised when loading
```
Comment (erlend-aasland) [inline Misc/NEWS.d/next/Library/2022-07-25-15-45-06.gh-issue-95231.i807-g.rst]:
```suggestion
Fail gracefully if :data:`~errno.EPERM` or :data:`~errno.ENOSYS` is raised when loading
```

**Review by erlend-aasland — APPROVED** [review]
Looks good, as far as I can see; thanks!

**Comment by sshedi** [comment]
@tiran & @erlend-aasland , please merge this PR.

**Comment by erlend-aasland** [comment]
> @tiran & @erlend-aasland , please merge this PR.

Please wait until Christian gives his thumbs up; he requested changes, and he should be allowed to review those before this PR lands.

**Comment by sshedi** [comment]
@tiran I have made the requested changes; please review again.

**Review by erlend-aasland — APPROVED** [review]

**Comment by erlend-aasland** [comment]
Updating branch to retrigger Azure Pipelines CI.

**Comment by mixmind** [comment]
Hi everyone, any chance of porting it to 3.9 too??

**Comment by vstinner** [comment]
> Hi everyone, any chance of backport it to 3.9 too??

That's somehow a new feature, and 3.9 only accept security fixes: https://devguide.python.org/versions/
