### PR TITLE
gh-106723: forward -Xfrozen_modules option to spawned interpreters

### LINKED ISSUE #106723: Multiprocessing not propagating -Xfrozen_modules=off
# Bug report

After python3.11 changes around frozen imports, when using multiprocessing contexts other than `fork`, the newly added `-Xfrozen_modules=off` isn't passed to spawned process interpreters.

Simple snippet demonstrating the issue:

```python
"""

$ python -Xfrozen_modules=off test.py
main: {'frozen_modules': 'off'}
forkserver: {}
spawn: {}
fork: {'frozen_modules': 'off'}

"""

import sys
import multiprocessing

def xoptions():
    return sys._xoptions

def main():
    print('main:', xoptions())
    for ctx in ('forkserver', 'spawn', 'fork'):
        with multiprocessing.get_context(ctx).Pool(1) as pool:
            print(f'{ctx}:', pool.apply(xoptions))

if __name__ == '__main__':
    main()
```

The issue seems to be `subprocess._args_from_interpreter_flags` not honoring `frozen_modules` key from `sys._xoptions`.

```bash
$ python -Xfrozen_modules=off -c 'import subprocess;print(subprocess._args_from_interpreter_flags())'
[]
```

# Your environment

python 3.11.4

### Linked PRs
* gh-106724
* gh-107367
* gh-107368

### PR DESCRIPTION
**Pull request by ergoithz**
Fixes https://github.com/python/cpython/issues/106723

* Issue: gh-106723

### CODE REVIEW

File: Misc/NEWS.d/next/Core and Builtins/2023-07-13-14-55-45.gh-issue-106723.KsMufQ.rst [hunk 1]
```diff
@@ -0,0 +1 @@
+Fix -Xfrozen_modules=off passing to multiprocessing subinterpreters.
```
Comment (kumaraditya303) [inline Misc/NEWS.d/next/Core and Builtins/2023-07-13-14-55-45.gh-issue-106723.KsMufQ.rst]:
```suggestion
Propagate ``frozen_modules`` to multiprocessing subinterpreters.
```

**Review by kumaraditya303 — APPROVED** [review]

**Review by gpshead — APPROVED** [review]
