### PR TITLE
gh-104536: Improve `multiprocessing.process._cleanup` logic

### LINKED ISSUE #104536: multiprocessing.process._children is not multithread-safe, BaseProcess.close() function would cause AttributeError
# Bug report

I have a project that uses threading.Thread and multiprocessing.Process for handling concurrent tasks. While under certain circumstances, there is the possibility that when I try new a `Process()` instance and call the `Process.start()` function, an error would occur:
`AttributeError: 'NoneType' object has no attribute 'poll'`

I tried debugging my project and found that under the `multiprocessing.process` module a global variable `_children` is used for managing all child processes, the variable is not thread-safe and the error would occur occasionally. I made a simple test code with minor modification on the `multiprocessing.process`

test.py
```py
from multiprocessing import Process
from threading import Thread


def helper():
    time.sleep(0.1)
    return 1


def close_process(p_: Process):
    p.terminate()
    p_.close()


if __name__ == "__main__":
    process_list = []
    for _ in range(1):
        p = Process(target=helper)
        p.start()
        time.sleep(0.2)
        process_list.append(p)

    for _ in range(1):
        t = Thread(target=close_process, args=(process_list[_],))
        t.start()

    new_p = Process(target=helper)
    time.sleep(0.2)
    new_p.start()
```

multiprocessing.process.py class BaseProcess
```py
    def close(self):
        '''
        Close the Process object.

        This method releases resources held by the Process object.  It is
        an error to call this method if the child process is still running.
        '''
        if self._popen is not None:
            if self._popen.poll() is None:
                raise ValueError("Cannot close a process while it is still running. "
                                 "You should first call join() or terminate().")
            self._popen.close()
            self._popen = None
            import time
            time.sleep(5)
            del self._sentinel
            _children.discard(self)
        self._closed = True
```

I simply add `time.sleep()` for `BaseProcess.close()` class and now every time I run the` test.py,` the error would occur.

# Your environment

- CPython versions tested on: python 3.7
- Operating system and architecture: windows 10 or linux el7

### Linked PRs
* gh-104537
* gh-104737

### PR DESCRIPTION
**Pull request by z764969689**
* Issue: gh-104536

Fixes #104536.

### CODE REVIEW

File: Misc/NEWS.d/next/Library/2023-05-16-10-07-16.gh-issue-104536.hFWD8f.rst [hunk 1]
```diff
@@ -0,0 +1 @@
+fix multiprocess.process._cleanup logic
```
Comment (arhadthedev) [inline Misc/NEWS.d/next/Library/2023-05-16-10-07-16.gh-issue-104536.hFWD8f.rst]:
```suggestion
Fix :meth:`!multiprocess.process._cleanup` logic.
```

**Comment by arhadthedev** [comment]
`test__xxsubinterpreters` failure in `Hypothesis Tests on Ubuntu` is a known problem tracked in gh-104341.

File: Lib/multiprocessing/process.py [hunk 2]
```diff
@@ -61,7 +61,7 @@ def parent_process():
 def _cleanup():
     # check for processes which have finished
     for p in list(_children):
-        if p._popen.poll() is not None:
+        if p._popen is not None and p._popen.poll() is not None:
```
Comment (gpshead) [inline Lib/multiprocessing/process.py]: Since you were encountering a concurrency error where p._popen was None, this change does not actually fix it yet, it just narrows the window.  The value could change between the is not None check and the next reference.

Instead, use something like this, it does the attribute lookup on p _a single time_ so there is no race condition.

```python
if (child_popen := p._popen) and child_popen.poll() is not None:
    _children.discard(p)
```

This still assumes that keeping the `multiprocess.popen_*.Popen` instance alive and calling poll on it after the process has already been observed to exit is okay, but that is likely true (it should just take the fast path and return the saved returncode).  _children is a set, it is safe to discard() something from a set that doesn't exist.

Comment (z764969689) [reply Lib/multiprocessing/process.py]: Agreed, never used the walrus operator before, it keeps the line pythonic as it was.

**Review by gpshead — APPROVED** [review]
