### PR TITLE
gh-98366: use sphinx.locale._ as gettext() in pyspecific.py

### LINKED ISSUE #98366: Python 3.10.7 Docs fails with Sphinx 5.3.0
Noticed that here:
https://build.opensuse.org/package/live_build_log/openSUSE:Factory:Staging:L/python310:doc/standard/x86_64

```
[   32s] + /usr/bin/make -O -j8 V=1 VERBOSE=1 -j1 html
[   32s] mkdir -p build
[   32s] Using existing Misc/NEWS file
[   32s] PATH=./venv/bin:$PATH sphinx-build -b html -d build/doctrees  -j auto  -W . build/html 
[   33s] Running Sphinx v5.3.0
[   33s] making output directory... done
[   33s] building [mo]: targets for 0 po files that are out of date
[   33s] building [html]: targets for 487 source files that are out of date
[   34s] updating environment: [new config] 487 added, 0 changed, 0 removed
[   34s] 
[   34s] Sphinx parallel build error:
[   34s] KeyError: 'sphinx'

```

The problematic line:
`395          label = translators['sphinx'].gettext(label)`

If I print the content of `translators` I get:

```
{('console', 'sphinx'): <gettext.NullTranslations object at 0x7ffff7664eb0>, ('general', 'sphinx'): <gettext.NullTranslations object at 0x7ffff6113cd0>, ('general', 'sphinxcontrib.applehelp'): <gettext.NullTranslations object at 0x7ffff5620910>, ('console', 'sphinxcontrib.applehelp'): <gettext.NullTranslations object at 0x7ffff56209d0>, ('general', 'sphinxcontrib.devhelp'): <gettext.NullTranslations object at 0x7ffff5622d40>, ('console', 'sphinxcontrib.devhelp'): <gettext.NullTranslations object at 0x7ffff5623e20>, ('general', 'sphinxcontrib.htmlhelp'): <gettext.NullTranslations object at 0x7ffff5623f10>, ('console', 'sphinxcontrib.htmlhelp'): <gettext.NullTranslations object at 0x7ffff5623f40>, ('general', 'sphinxcontrib.serializinghtml'): <gettext.NullTranslations object at 0x7ffff564ceb0>, ('console', 'sphinxcontrib.serializinghtml'): <gettext.NullTranslations object at 0x7ffff564cf10>, ('general', 'sphinxcontrib.qthelp'): <gettext.NullTranslations object at 0x7ffff564cfa0>, ('console', 'sphinxcontrib.qthelp'): <gettext.NullTranslations object at 0x7ffff564d630>, ('general', 'about'): <gettext.NullTranslations object at 0x7ffff56a2830>, ('general', 'bugs'): <gettext.NullTranslations object at 0x7ffff56a3790>, ('general', 'c-api'): <gettext.NullTranslations object at 0x7ffff536a800>}
```

@AA-Turner

* PR: gh-99358

* PR: gh-99359

### PR DESCRIPTION
**Pull request by mattwang44**
sphinx 5.3 changed `sphinx.locale.translators` from a `defaultdict(gettext.NullTranslations)` to a `dict` ([commit](https://github.com/sphinx-doc/sphinx/commit/0466fa88ebd7b97e7ddda292450a349f17dde4a7)), which led to failure of pyspecific.py. Use `sphinx.locale._` as `gettext()` to fix the issue.

* Issue: gh-98366

### CODE REVIEW

File: Misc/NEWS.d/next/Documentation/2022-10-19-07-15-52.gh-issue-98366.UskMXF.rst [hunk 1]
```diff
@@ -0,0 +1 @@
+Use sphinx.locale._ as the gettext function in pyspecific.py.
```
Comment (mattwang44) [inline Misc/NEWS.d/next/Documentation/2022-10-19-07-15-52.gh-issue-98366.UskMXF.rst]: Is the NEWS required? or should I delete this file and add the `skip news` label to this PR?

**Comment by marxin** [comment]
May I please ping this, it's blocking `Sphinx` `5.3` update in openSUSE CI right now.

**Comment by mcepl** [comment]
> May I please ping this, it's blocking `Sphinx` `5.3` update in openSUSE CI right now.

@ezio-melotti, @merwok, @JulienPalard, @willingc You are enlisted on https://devguide.python.org/core-developers/experts/ as experts for documentation. Could you please review this PR? Thank you.

File: Misc/NEWS.d/next/Documentation/2022-10-19-07-15-52.gh-issue-98366.UskMXF.rst (hunk 1 above)
Comment (merwok) [reply Misc/NEWS.d/next/Documentation/2022-10-19-07-15-52.gh-issue-98366.UskMXF.rst]: I think this change is not very relevant for readers of the Python doc.  I added the label!

Comment (mattwang44) [reply Misc/NEWS.d/next/Documentation/2022-10-19-07-15-52.gh-issue-98366.UskMXF.rst]: ok thanks! I've dropped the commit.

**Comment by AA-Turner** [comment]
Desk review looks reasonable, though ideally we'd confirm by building one of the translations against this PR.

A

**Review by AA-Turner — APPROVED** [review]

**Comment by AlexWaygood** [comment]
> ideally we'd confirm by building one of the translations against this PR.

@mattwang44, are you able to do that?

File: Misc/NEWS.d/next/Documentation/2022-10-19-07-15-52.gh-issue-98366.UskMXF.rst (hunk 1 above)
Comment (merwok) [reply Misc/NEWS.d/next/Documentation/2022-10-19-07-15-52.gh-issue-98366.UskMXF.rst]: Cool!  For future Python PRs, please don’t use force pushes, github has a poor experience for reviewers.
Guide: https://devguide.python.org/getting-started/pull-request-lifecycle/index.html

**Comment by mattwang44** [comment]
@AA-Turner @AlexWaygood 
A PR ([cpython/python-docs-zh-tw#331](https://github.com/python/python-docs-zh-tw/pull/331)) for testing this branch is created and [the affiliated CI job is passed](https://github.com/python/python-docs-zh-tw/actions/runs/3298769014/jobs/5441315620).

**Comment by AA-Turner** [comment]
Great that the build passed. Is the translation correct for implementation detail directives, to sanity check that the new code works?

A

**Comment by mattwang44** [comment]
> Great that the build passed. Is the translation correct for implementation detail directives, to sanity check that the new code works?
> 
> A

The static site of translated doc in zh_TW has been deployed to the [GitHub page](https://python.github.io/python-docs-zh-tw/) (GitHub Action logs is [here](https://github.com/python/python-docs-zh-tw/actions/runs/3307244245/jobs/5458729198)). I've checked a couple of recently-merged translation PRs and it looks fine to me.

**Review by ezio-melotti — APPROVED** [review]

**Comment by ezio-melotti** [comment]
Should this be backported to `3.11` and `3.10` too?

**Comment by AA-Turner** [comment]
Yes!

A
