### PR TITLE
gh-120973: Fix thread-safety issues with `threading.local`

### LINKED ISSUE #118490: `test_threading_local_clear_race` segmentation fault in free-threaded CI
# Crash report

A segmentation fault in the macOS M1 arm64 refleaks buildbot:

Seen in https://buildbot.python.org/all/#/builders/1367/builds/146/steps/5/logs/stdio

```
test_threading_local_clear_race (test.test_threading_local.PyThreadingLocalTest.test_threading_local_clear_race) ... Fatal Python error: Segmentation fault
Current thread 0x00000001d8941300 (most recent call first):
  File "/Users/ec2-user/buildbot/buildarea/pull_request.itamaro-macos-arm64-aws.macos-with-brew.refleak.nogil/build/Lib/test/test_threading_local.py", line 206 in test_threading_local_clear_race
  File "/Users/ec2-user/buildbot/buildarea/pull_request.itamaro-macos-arm64-aws.macos-with-brew.refleak.nogil/build/Lib/unittest/case.py", line 606 in _callTestMethod
  File "/Users/ec2-user/buildbot/buildarea/pull_request.itamaro-macos-arm64-aws.macos-with-brew.refleak.nogil/build/Lib/unittest/case.py", line 651 in run
  File "/Users/ec2-user/buildbot/buildarea/pull_request.itamaro-macos-arm64-aws.macos-with-brew.refleak.nogil/build/Lib/unittest/case.py", line 707 in __call__
  File "/Users/ec2-user/buildbot/buildarea/pull_request.itamaro-macos-arm64-aws.macos-with-brew.refleak.nogil/build/Lib/unittest/suite.py", line 122 in run
  File "/Users/ec2-user/buildbot/buildarea/pull_request.itamaro-macos-arm64-aws.macos-with-brew.refleak.nogil/build/Lib/unittest/suite.py", line 84 in __call__
  File "/Users/ec2-user/buildbot/buildarea/pull_request.itamaro-macos-arm64-aws.macos-with-brew.refleak.nogil/build/Lib/unittest/suite.py", line 122 in run
  File "/Users/ec2-user/buildbot/buildarea/pull_request.itamaro-macos-arm64-aws.macos-with-brew.refleak.nogil/build/Lib/unittest/suite.py", line 84 in __call__
  File "/Users/ec2-user/buildbot/buildarea/pull_request.itamaro-macos-arm64-aws.macos-with-brew.refleak.nogil/build/Lib/unittest/runner.py", line 240 in run
  File "/Users/ec2-user/buildbot/buildarea/pull_request.itamaro-macos-arm64-aws.macos-with-brew.refleak.nogil/build/Lib/test/libregrtest/single.py", line 57 in _run_suite
  File "/Users/ec2-user/buildbot/buildarea/pull_request.itamaro-macos-arm64-aws.macos-with-brew.refleak.nogil/build/Lib/test/libregrtest/single.py", line 37 in run_unittest
  File "/Users/ec2-user/buildbot/buildarea/pull_request.itamaro-macos-arm64-aws.macos-with-brew.refleak.nogil/build/Lib/test/libregrtest/single.py", line 132 in test_func
  File "/Users/ec2-user/buildbot/buildarea/pull_request.itamaro-macos-arm64-aws.macos-with-brew.refleak.nogil/build/Lib/test/libregrtest/refleak.py", line 106 in runtest_refleak
  File "/Users/ec2-user/buildbot/buildarea/pull_request.itamaro-macos-arm64-aws.macos-with-brew.refleak.nogil/build/Lib/test/libregrtest/single.py", line 84 in regrtest_runner
  File "/Users/ec2-user/buildbot/buildarea/pull_request.itamaro-macos-arm64-aws.macos-with-brew.refleak.nogil/build/Lib/test/libregrtest/single.py", line 135 in _load_run_test
  File "/Users/ec2-user/buildbot/buildarea/pull_request.itamaro-macos-arm64-aws.macos-with-brew.refleak.nogil/build/Lib/test/libregrtest/single.py", line 178 in _runtest_env_changed_exc
  File "/Users/ec2-user/buildbot/buildarea/pull_request.itamaro-macos-arm64-aws.macos-with-brew.refleak.nogil/build/Lib/test/libregrtest/single.py", line 278 in _runtest
  File "/Users/ec2-user/buildbot/buildarea/pull_request.itamaro-macos-arm64-aws.macos-with-brew.refleak.nogil/build/Lib/test/libregrtest/single.py", line 309 in run_single_test
  File "/Users/ec2-user/buildbot/buildarea/pull_request.itamaro-macos-arm64-aws.macos-with-brew.refleak.nogil/build/Lib/test/libregrtest/worker.py", line 77 in worker_process
  File "/Users/ec2-user/buildbot/buildarea/pull_request.itamaro-macos-arm64-aws.macos-with-brew.refleak.nogil/build/Lib/test/libregrtest/worker.py", line 112 in main
  File "/Users/ec2-user/buildbot/buildarea/pull_request.itamaro-macos-arm64-aws.macos-with-brew.refleak.nogil/build/Lib/test/libregrtest/worker.py", line 116 in <module>
  File "/Users/ec2-user/buildbot/buildarea/pull_request.itamaro-macos-arm64-aws.macos-with-brew.refleak.nogil/build/Lib/runpy.py", line 88 in _run_code
  File "/Users/ec2-user/buildbot/buildarea/pull_request.itamaro-macos-arm64-aws.macos-with-brew.refleak.nogil/build/Lib/runpy.py", line 198 in _run_module_as_main
```

### PR DESCRIPTION
**Pull request by mpage**
This is a small refactoring to the current design that allows us to avoid manually iterating over threads.

This should also fix gh-118490.

* Issue: gh-120973

### CODE REVIEW

File: Modules/_threadmodule.c [hunk 1]
```diff
@@ -1413,80 +1424,59 @@ static PyType_Spec local_dummy_type_spec = {
...
+    PyObject *wr = PyWeakref_NewRef(tstate->threading_local_sentinel, cb);
+    Py_DECREF(cb);
 
-err:
-    Py_XDECREF(ldict);
-    Py_XDECREF(wr);
-    Py_XDECREF(dummy);
-    return NULL;
+    return wr;
 }
```
Comment (ambv) [inline Modules/_threadmodule.c:1476]: Haha, kind of a frustrating diff here given that the functions before and after don't have much in common.

**Review by ambv — APPROVED** [review]
Tested locally, works for me. Read through the implementation, clever trick with the sentinel. I find it just a tiny bit uglier that thread state now is concerned with thread locals, but it makes sense given the problem this PR is solving.

File: Modules/_threadmodule.c [hunk 2]
```diff
@@ -1513,28 +1503,18 @@ local_new(PyTypeObject *type, PyObject *args, PyObject *kw)
...
         goto err;
     }
-    self->wr_callback = PyCFunction_NewEx(&wr_callback_def, wr, NULL);
-    Py_DECREF(wr);
-    if (self->wr_callback == NULL) {
-        goto err;
-    }
-    if (_local_create_dummy(self, state) == NULL) {
+
+    if (_ldict(self, state) == NULL) {
```
Comment (colesbury) [inline Modules/_threadmodule.c]: What's the point of this call to `_ldict`?

File: Modules/_threadmodule.c [hunk 3]
```diff
@@ -1595,49 +1557,81 @@ local_dealloc(localobject *self)
...
 static PyObject *
 _ldict(localobject *self, thread_module_state *state)
 {
-    PyObject *tdict = PyThreadState_GetDict();
-    if (tdict == NULL) {
-        PyErr_SetString(PyExc_SystemError,
-                        "Couldn't get thread-state dictionary");
-        return NULL;
-    }
+    PyThreadState *tstate = PyThreadState_Get();
```
Comment (colesbury) [inline Modules/_threadmodule.c]: The inline function `_PyThreadState_GET()` is going to a little bit faster for internal code.

File: Modules/_threadmodule.c [hunk 4]
```diff
@@ -1595,49 +1557,81 @@ local_dealloc(localobject *self)
...
+    }
+
+    if (PySet_Add(self->thread_watchdogs, wr) < 0) {
+        PyDict_DelItem(self->localdicts, tstate->threading_local_key);
+        Py_DECREF(wr);
+        return NULL;
+    }
+
+    if (Py_TYPE(self)->tp_init != PyBaseObject_Type.tp_init &&
+        Py_TYPE(self)->tp_init((PyObject *)self, self->args, self->kw) < 0) {
```
Comment (colesbury) [inline Modules/_threadmodule.c:1683]: Hmm... I'm seeing `__init__` get called twice in the thread that instantiates a thread local subclass, which seems different from the previous behavior.

File: Modules/_threadmodule.c [hunk 5]
```diff
@@ -1595,49 +1557,81 @@ local_dealloc(localobject *self)
...
+    if (PyDict_SetItem(self->localdicts, tstate->threading_local_key, ldict) <
+        0) {
+        Py_DECREF(ldict);
+        return NULL;
+    }
+    Py_DECREF(ldict);
+
+    PyObject *wr = create_sentinel_wr(self);
+    if (wr == NULL) {
+        PyDict_DelItem(self->localdicts, tstate->threading_local_key);
```
Comment (colesbury) [inline Modules/_threadmodule.c]: I think we want to avoid making these sorts of API calls with an exception set, because things can break in weird ways if the code internally relies on `PyErr_Occurred()`.

I think the proper way to do this looks something like:

```c
    PyObject *exc = PyErr_GetRaisedException();
    if (PyDict_DelItem(self->localdicts, tstate->threading_local_key) < 0) {
        PyErr_WriteUnraisable(self);
    }
    PyErr_SetRaisedException(exc);
```

File: Modules/_threadmodule.c [hunk 6]
```diff
@@ -1595,49 +1557,81 @@ local_dealloc(localobject *self)
...
             return NULL;
         }
     }
-    else {
-        assert(Py_IS_TYPE(dummy, state->local_dummy_type));
-        ldict = ((localdummyobject *) dummy)->localdict;
+
+    /* Check if a locals dict already exists */
+    PyObject *ldict =
+        PyDict_GetItemWithError(self->localdicts, tstate->threading_local_key);
```
Comment (colesbury) [inline Modules/_threadmodule.c]: Would it be possible to use strong references (i.e., `PyDict_GetItemRef`) here and in the return value for `_ldict` or would that be too awkward?

I think the current usage is probably thread-safe, but we've generally tried to avoid APIs that return borrowed references for thread-safe code.

File: Modules/_threadmodule.c [hunk 7]
```diff
@@ -1413,80 +1424,59 @@ static PyType_Spec local_dummy_type_spec = {
...
+    if (args == NULL) {
+        Py_DECREF(self_wr);
+        return NULL;
     }
-    Py_CLEAR(wr);
-    r = PyDict_SetItem(tdict, self->key, (PyObject *) dummy);
-    if (r < 0) {
-        goto err;
+    PyTuple_SetItem(args, 0, self_wr);
+    PyTuple_SetItem(args, 1, Py_NewRef(tstate->threading_local_key));
```
Comment (colesbury) [inline Modules/_threadmodule.c]: minor, but I'd use `PyTuple_SET_ITEM`. The macro version seems to be much more commonly used, with the exception of modules that use the limited C API.

**Review by colesbury — COMMENTED** [review]
Overall, I think the design looks good. Some comments below.

File: Modules/_threadmodule.c (hunk 2 above)
Comment (mpage) [reply Modules/_threadmodule.c]: It preserves the behavior of the previous implementation where the locals dictionary for the current thread was created upon construction of the `threading.local`. I don't think that's necessary for correctness; I was just trying to match the behavior of the existing implementation.

File: Modules/_threadmodule.c (hunk 4 above)
Comment (mpage) [reply Modules/_threadmodule.c:1683]: Hrm that's odd and unintentional. Will take a look...

File: Modules/_threadmodule.c (hunk 6 above)
Comment (mpage) [reply Modules/_threadmodule.c]: I don't think that'll be too awkward. For the purposes of making the review easier I was trying to mirror the existing implementation.

**Comment by mpage** [comment]
@colesbury - I think this should be good to go. Would you please have another look?

**Review by colesbury — APPROVED** [review]
LGTM

I'll wait until today's releases finish before merging this.

**Comment by colesbury** [comment]
!buildbot AMD64 Ubuntu NoGIL Refleaks
