### PR TITLE
gh-104482: Fix error handling bugs in ast.c

### LINKED ISSUE #104482: Error handling bugs in ast.c
in validate_pattern, there are two places where in case of error we break out of a loop, but we also need to break out of the switch.

```
--- a/Python/ast.c
+++ b/Python/ast.c
@@ -580,7 +580,9 @@ validate_pattern(struct validator *state, pattern_ty p, int star_ok)
                     break;
                 }
             }
-
+            if (ret == 0) {
+                break;
+            }
             ret = validate_patterns(state, p->v.MatchMapping.patterns, /*star_ok=*/0);
             break;
         case MatchClass_kind:
@@ -620,6 +622,9 @@ validate_pattern(struct validator *state, pattern_ty p, int star_ok)
                 }
             }
 
+            if (ret == 0) {
+                break;
+            }
             if (!validate_patterns(state, p->v.MatchClass.patterns, /*star_ok=*/0)) {
                 ret = 0;
                 break;
```

If we don't do this we can end up calling _PyAST_Compile with an error set.

### Linked PRs
* gh-104483
* gh-104514

### PR DESCRIPTION
**Pull request by iritkatriel**
Fixes #104482.

* Issue: gh-104482

### CODE REVIEW

**Comment by iritkatriel** [comment]
I don't know if you want to add more tests for this - the assertion I added would fail without this fix.

File: Python/ast.c [hunk 1]
```diff
@@ -620,6 +622,9 @@ validate_pattern(struct validator *state, pattern_ty p, int star_ok)
                 }
             }
```
Comment (iritkatriel) [inline Python/ast.c]:
```suggestion
```

**Review by carljm — APPROVED** [review]

File: Python/compile.c [hunk 2]
```diff
@@ -567,6 +567,7 @@ PyCodeObject *
 _PyAST_Compile(mod_ty mod, PyObject *filename, PyCompilerFlags *pflags,
                int optimize, PyArena *arena)
 {
+    assert(!PyErr_Occurred());
```
Comment (isidentical) [inline Python/compile.c:570]: This feels like an overly generalized handler, and IIRC we should already have an ast validation phase at the parser when the debug mode is applied. Is there a case where this catches something and that doesn't (I assume manually produced trees might fit but they are always validated).

**Review by isidentical — APPROVED** [review]

File: Python/compile.c (hunk 2 above)
Comment (iritkatriel) [reply Python/compile.c:570]: IIUC the bug this PR is fixing is in the AST validation code. 

I don't think anyone should call ``_PyAST_Compile`` with an exception set.

File: Python/ast.c [hunk 3]
```diff
@@ -619,7 +621,9 @@ validate_pattern(struct validator *state, pattern_ty p, int star_ok)
                     break;
                 }
             }
-
+            if (ret == 0) {
+                break;
+            }
```
Comment (iritkatriel) [inline Python/ast.c:636]: We need another such break in line 616 (after the while(1) loop). Will add.

Comment (carljm) [reply Python/ast.c:636]: Can you confirm that the assert you added in `_PyAST_Compile` is triggered in the existing test suite by all three of the cases where you're now adding a fix? If not, I do think we need more tests to ensure all of these are covered.

Comment (iritkatriel) [reply Python/ast.c:636]: The third one didn't trigger it. The first two did.

Comment (iritkatriel) [reply Python/ast.c:636]: I could add the assert at the beginning of each of the validate_* functions.

Comment (carljm) [reply Python/ast.c:636]: > I could add the assert at the beginning of each of the validate_* functions.

Not sure I follow. In my mental model, either the code path causing an error at that particular spot is exercised by the test suite, or it isn't. How does adding more asserts at different places help catch it? Is that third error code path already exercised, but exercised in a way that either doesn't end up calling `_PyAST_Compile`, or ends up silencing the error before it does?

Comment (iritkatriel) [reply Python/ast.c:636]: The code path is hit in the test, but then the for loop doesn't run because ``asdl_seq_LEN(p->v.MatchClass.kwd_attrs) == 0`` and so the ``if(ret == 0)`` I added after the for loop exits with the error.  I'll try to add a test that does go into the for loop, and then the new assert should trip.

File: Misc/NEWS.d/next/Core and Builtins/2023-05-14-18-56-54.gh-issue-104482.yaQsv8.rst [hunk 4]
```diff
@@ -0,0 +1 @@
+Fix two error handling bugs in ast.c's parsing of pattern matching statements.
```
Comment (carljm) [inline Misc/NEWS.d/next/Core and Builtins/2023-05-14-18-56-54.gh-issue-104482.yaQsv8.rst]: s/two/three/ :)

File: Python/ast.c [hunk 5]
```diff
@@ -685,22 +703,24 @@ _validate_nonempty_seq(asdl_seq *seq, const char *what, const char *owner)
...
     return validate_nonempty_seq(body, "body", owner) && validate_stmts(state, body);
 }
 
 static int
 validate_stmt(struct validator *state, stmt_ty stmt)
 {
+    assert(!PyErr_Occurred());
     VALIDATE_POSITIONS(stmt);
     int ret = -1;
-    Py_ssize_t i;
```
Comment (carljm) [inline Python/ast.c:703]: is this change to the scope of `i` important for a functional reason, or just a coding style preference?

Comment (iritkatriel) [reply Python/ast.c:703]: Just style. It’s very old fashioned to declare a loop index like that.

File: Misc/NEWS.d/next/Core and Builtins/2023-05-14-18-56-54.gh-issue-104482.yaQsv8.rst (hunk 4 above)
Comment (iritkatriel) [inline Misc/NEWS.d/next/Core and Builtins/2023-05-14-18-56-54.gh-issue-104482.yaQsv8.rst]:
```suggestion
Fix three error handling bugs in ast.c's parsing of pattern matching statements.
```

File: Misc/NEWS.d/next/Core and Builtins/2023-05-14-18-56-54.gh-issue-104482.yaQsv8.rst [hunk 6]
```diff
@@ -0,0 +1 @@
+Fix three error handling bugs in ast.c's parsing of pattern matching statements.
```
Comment (iritkatriel) [inline Misc/NEWS.d/next/Core and Builtins/2023-05-14-18-56-54.gh-issue-104482.yaQsv8.rst]:
```suggestion
Fix three error handling bugs in ast.c's validation of pattern matching statements.
```

**Comment by iritkatriel** [comment]
The hypothesis bot fails everywhere. We’re good.
